/**
 * Resource Ordering Management
 * This is Swagger UI environment generated for the TMF Resource Ordering Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CancelResourceOrder } from './cancelResourceOrder';

/**
 * The event data structure
 */
export interface CancelResourceOrderStateChangeEventPayload { 
    cancelResourceOrder?: CancelResourceOrder;
}