CREATE TABLE T_MWF_PRODUKT_POSITION
(
  ID                     NUMBER(19)             NOT NULL,
  VERSION                NUMBER(19)             DEFAULT 0                     NOT NULL,
  MELDUNG_ID             NUMBER(19),
  AKTIONSCODE            VARCHAR2(10 BYTE)      NOT NULL,
  PRODUKTBEZEICHNER      VARCHAR2(15 BYTE),
  UEBERTRAGUNGSVERFAHREN VARCHAR2(3 BYTE)
);

ALTER TABLE T_MWF_PRODUKT_POSITION ADD PRIMARY KEY (ID);

ALTER TABLE T_MWF_PRODUKT_POSITION ADD (
  CONSTRAINT T_MWF_PRODUKT_POSITION_FK
  FOREIGN KEY (MELDUNG_ID)
  REFERENCES T_MWF_MELDUNG (ID));

GRANT SELECT ON T_MWF_PRODUKT_POSITION TO R_HURRICAN_READ_ONLY;

GRANT INSERT, SELECT, UPDATE ON T_MWF_PRODUKT_POSITION TO R_HURRICAN_USER;


CREATE SEQUENCE S_T_MWF_PRODUKT_POSITION_0;

GRANT SELECT ON S_T_MWF_PRODUKT_POSITION_0 TO PUBLIC;

