ALTER TABLE T_MWF_ANLAGE
 ADD CONSTRAINT FK_MWF_ANLAGE_2_GF
  FOREIGN KEY (GESCHAEFTSFALL_ID)
  REFERENCES T_MWF_GESCHAEFTSFALL (ID);

ALTER TABLE T_MWF_ANLAGE
 ADD CONSTRAINT FK_MWF_ANLAGE_2_MELDUNG
  FOREIGN KEY (MELDUNG_ID)
  REFERENCES T_MWF_MELDUNG (ID);
