UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'DataRateUp' WHERE PARAM_NAME = 'Rate Up';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'DataRateDown' WHERE PARAM_NAME = 'Rate Down';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'Spectrum' WHERE PARAM_NAME = 'G.fast Line Spectrum';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'Sos' WHERE PARAM_NAME = 'SOS';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'VirtualNoise' WHERE PARAM_NAME = 'Virtual Noise';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'ImpulseNoiseMonitoring' WHERE PARAM_NAME = 'INM';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'RadioFrequencyInterference' WHERE PARAM_NAME = 'RFI';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'PowerBackOffUp' WHERE PARAM_NAME = 'UPBO';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'PowerBackOffDown' WHERE PARAM_NAME = 'DPBO';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'NoiseMargin' WHERE PARAM_NAME = 'noise margin';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'ImpulseNoiseProtectionDelay' WHERE PARAM_NAME = 'INP Delay';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'TrafficTableUp' WHERE PARAM_NAME = 'Traffic Table Upstream';
UPDATE T_PROFILE_PARAMETER_MAPPER SET PARAM_CPS_NAME = 'TrafficTableDown' WHERE PARAM_NAME = 'Traffic Table Downstream';

