DELETE FROM T_PROFILE_AUFTRAG_VALUE WHERE PARAMETER_NAME = 'TDD Profil';
DELETE FROM T_PROFILE_PARAMETER WHERE PARAMETER_NAME = 'TDD Profil';
DELETE FROM T_PROFILE_PARAMETER_MAPPER WHERE PARAM_NAME = 'TDD Profil';
