CREATE OR REPLACE VIEW V_ANSPRECHPARTNER_PRO_KUNDE AS (
SELECT DISTINCT
    AP.ID AS ANSPRECHPARTNER_ID,
    TREF.STR_VALUE AS TYP,
    AP.AUFTRAG_ID,
    AP.TYPE_REF_ID,
    ADR.ID AS ADDRESS_ID,
    ADR.NAME,
    ADR.VORNAME,
    ADR.TELEFON,
    ADR.HANDY,
    ADR.EMAIL,
    AUF.KUNDE__NO AS KUNDE_NR,
    AD.PRODAK_ORDER__NO AS ORDER_NR,
    AD.BUENDEL_NR
  FROM T_AUFTRAG AUF
    INNER JOIN T_ANSPRECHPARTNER AP ON (AUF.ID = AP.AUFTRAG_ID)
    INNER JOIN T_AUFTRAG_DATEN AD ON (AUF.ID = AD.AUFTRAG_ID)
    INNER JOIN T_ADDRESS ADR ON (AP.ADDRESS_ID = ADR.ID)
    INNER JOIN T_REFERENCE TREF ON (AP.TYPE_REF_ID = TREF.ID)
);

GRANT SELECT ON V_ANSPRECHPARTNER_PRO_KUNDE TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON V_ANSPRECHPARTNER_PRO_KUNDE TO R_HURRICAN_USER;