-- drop no longer used Quartz table for SIG (long running) jobs
DROP TABLE QRTZ_SIG_TRIGGER_LISTENERS;
DROP TABLE QRTZ_SIG_BLOB_TRIGGERS;
DROP TABLE QRTZ_SIG_CRON_TRIGGERS;
DROP TABLE QRTZ_SIG_SIMPLE_TRIGGERS;
DROP TABLE QRTZ_SIG_TRIGGERS;
DROP TABLE QRTZ_SIG_JOB_LISTENERS;
DROP TABLE QRTZ_SIG_JOB_DETAILS;
DROP TABLE QRTZ_SIG_CALENDARS;
DROP TABLE QRTZ_SIG_FIRED_TRIGGERS;
DROP TABLE QRTZ_SIG_LOCKS;
DROP TABLE QRTZ_SIG_PAUSED_TRIGGER_GRPS;
DROP TABLE QRTZ_SIG_SCHEDULER_STATE;

