--
-- Skript, um weitere Tabellen u. Referenzdaten fuer die Port-Schwenks aufzusetzen
--

insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (22100, 'PORT_SCHWENK', 'Baugruppentyp aendern', '1', 10, 'Port-Schwenk definiert, dass ein Baugruppentyp geaendert wird');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (22101, 'PORT_SCHWENK', 'einfacher Kartenwechsel', '1', 20, 'Port-Schwenk definiert einen einfachen Kartenwechsel');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (22102, 'PORT_SCHWENK', 'Karten zusammenlegen', '1', 30, 'Port-Schwenk definiert, dass mehrere Karten zu einer Karte zusammengelegt werden');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (22103, 'PORT_SCHWENK', 'DSLAM Splitt', '1', 40, 'Port-Schwenk definiert, dass Karten aus einem DSLAM in einen anderen verschoben werden');

-- Tabelle fuer Typ 'Baugruppentyp aendern'
create table T_HW_BG_CHANGE_BG_TYPE (
    ID NUMBER(10) NOT NULL
  , HW_BG_CHANGE_ID NUMBER(10) NOT NULL
  , HW_BAUGRUPPEN_ID NUMBER(10) NOT NULL
  , HW_BAUGRUPPENTYP_NEW NUMBER(10) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
comment on table T_HW_BG_CHANGE_BG_TYPE is 'Tabelle definiert die Daten fuer den Port-Schwenk vom Typ <Baugruppentyp aendern>';
comment on column T_HW_BG_CHANGE_BG_TYPE.HW_BAUGRUPPEN_ID is 'ID der Baugruppe, deren Typ geaendert werden soll';
comment on column T_HW_BG_CHANGE_BG_TYPE.HW_BAUGRUPPENTYP_NEW is 'Baugruppentyp, auf den gewechselt wird';

create SEQUENCE S_T_HW_BG_CHANGE_BG_TYPE_0 start with 1;
grant select on S_T_HW_BG_CHANGE_BG_TYPE_0 to public;

ALTER TABLE T_HW_BG_CHANGE_BG_TYPE ADD CONSTRAINT PK_T_HW_BG_CHANGE_BG_TYPE PRIMARY KEY (ID);

CREATE INDEX IX_FK_HWBGCBGT_2_HWBGC ON T_HW_BG_CHANGE_BG_TYPE (HW_BG_CHANGE_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_BG_TYPE ADD CONSTRAINT FK_HWBGCBGT_2_HWBGC
  FOREIGN KEY (HW_BG_CHANGE_ID) REFERENCES T_HW_BG_CHANGE (ID);

GRANT SELECT ON T_HW_BG_CHANGE_BG_TYPE TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HW_BG_CHANGE_BG_TYPE TO R_HURRICAN_USER;



-- Tabelle fuer Typ 'einfacher Kartenwechsel' u. 'Karten zusammenlegen'
create table T_HW_BG_CHANGE_CARD (
    ID NUMBER(10) NOT NULL
  , HW_BG_CHANGE_ID NUMBER(10) NOT NULL
  , HW_BAUGRUPPEN_ID_NEW NUMBER(10) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
comment on table T_HW_BG_CHANGE_CARD is 'Tabelle definiert die Daten fuer den Port-Schwenk vom Typ <einfacher Kartenwechsel> u. <Karten zusammenlegen>';
comment on column T_HW_BG_CHANGE_CARD.HW_BAUGRUPPEN_ID_NEW is 'ID der neuen bzw. zu erhaltenden Baugruppe';
create SEQUENCE S_T_HW_BG_CHANGE_CARD_0 start with 1;
grant select on S_T_HW_BG_CHANGE_CARD_0 to public;
ALTER TABLE T_HW_BG_CHANGE_CARD ADD CONSTRAINT PK_T_HW_BG_CHANGE_CARD PRIMARY KEY (ID);
CREATE INDEX IX_FK_HWBGCCARD_2_HWBGC ON T_HW_BG_CHANGE_CARD (HW_BG_CHANGE_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_CARD ADD CONSTRAINT FK_HWBGCCARD_2_HWBGC
  FOREIGN KEY (HW_BG_CHANGE_ID) REFERENCES T_HW_BG_CHANGE (ID);
GRANT SELECT ON T_HW_BG_CHANGE_CARD TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HW_BG_CHANGE_CARD TO R_HURRICAN_USER;

-- Sub-Tabelle fuer Kartenwechsel
create table T_HW_BG_CHANGE_CARD_SOURCE (
    ID NUMBER(10) NOT NULL
  , HW_BG_CHANGE_CARD_ID NUMBER(10) NOT NULL
  , HW_BAUGRUPPEN_ID_TO_CHANGE NUMBER(10) NOT NULL
  , ORDER_NO NUMBER(10) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
comment on table T_HW_BG_CHANGE_CARD_SOURCE is 'Sub-Tabelle fuer T_HW_BG_CHANGE_CARD um die abzuloesenden Karten anzugeben';
comment on column T_HW_BG_CHANGE_CARD_SOURCE.HW_BAUGRUPPEN_ID_TO_CHANGE is 'ID einer Baugruppe, die abgeloest werden soll';
create SEQUENCE S_T_HW_BG_CHANGE_CARD_SOURCE_0 start with 1;
grant select on S_T_HW_BG_CHANGE_CARD_SOURCE_0 to public;
ALTER TABLE T_HW_BG_CHANGE_CARD_SOURCE ADD CONSTRAINT PK_T_HW_BG_CHANGE_CARD_SOURCE PRIMARY KEY (ID);
CREATE INDEX IX_FK_HWBGCCARDSOURCE_2_CARD ON T_HW_BG_CHANGE_CARD_SOURCE (HW_BG_CHANGE_CARD_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_CARD_SOURCE ADD CONSTRAINT FK_HWBGCCARDSOURCE_2_CARD
  FOREIGN KEY (HW_BG_CHANGE_CARD_ID) REFERENCES T_HW_BG_CHANGE_CARD (ID);
GRANT SELECT ON T_HW_BG_CHANGE_CARD_SOURCE TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HW_BG_CHANGE_CARD_SOURCE TO R_HURRICAN_USER;


-- Tabelle fuer Port-Schwenk 'DSLAM Splitt'
create table T_HW_BG_CHANGE_DSLAM_SPLIT (
    ID NUMBER(10) NOT NULL
  , HW_BG_CHANGE_ID NUMBER(10) NOT NULL
  , HW_RACK_ID_OLD NUMBER(10) NOT NULL
  , SUBRACK_ID_OLD NUMBER(10) NOT NULL
  , HW_RACK_ID_NEW NUMBER(10) NOT NULL
  , SUBRACK_ID_NEW NUMBER(10) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
comment on table T_HW_BG_CHANGE_DSLAM_SPLIT is 'Tabelle definiert die Daten fuer einen Port-Schwenk vom Typ <DSLAM Splitt>';
comment on column T_HW_BG_CHANGE_DSLAM_SPLIT.HW_RACK_ID_OLD is 'ID des urspruenglichen DSLAMs (HW_RACK)';
comment on column T_HW_BG_CHANGE_DSLAM_SPLIT.SUBRACK_ID_OLD is 'ID des urspruenglichen Subracks (HW_SUBRACK)';
comment on column T_HW_BG_CHANGE_DSLAM_SPLIT.HW_RACK_ID_NEW is 'ID des neuen DSLAMs (HW_RACK)';
comment on column T_HW_BG_CHANGE_DSLAM_SPLIT.SUBRACK_ID_NEW is 'ID des neuen Subracks (HW_SUBRACK)';

create SEQUENCE S_T_HW_BG_CHANGE_DSLAM_SPLIT_0 start with 1;
grant select on S_T_HW_BG_CHANGE_DSLAM_SPLIT_0 to public;
ALTER TABLE T_HW_BG_CHANGE_DSLAM_SPLIT ADD CONSTRAINT PK_T_HW_BG_CHANGE_DSLAM_SPLIT PRIMARY KEY (ID);
CREATE INDEX IX_FK_HWBGCDSLAM_2_HWBGC ON T_HW_BG_CHANGE_DSLAM_SPLIT (HW_BG_CHANGE_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_DSLAM_SPLIT ADD CONSTRAINT FK_HWBGCDSLAM_2_HWBGC
  FOREIGN KEY (HW_BG_CHANGE_ID) REFERENCES T_HW_BG_CHANGE (ID);
GRANT SELECT ON T_HW_BG_CHANGE_DSLAM_SPLIT TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HW_BG_CHANGE_DSLAM_SPLIT TO R_HURRICAN_USER;






