
-- Surf&Fon - VDSL 18.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1200, 900, 513, 'phone_dsl', 1, 0);

-- Surf&Fon - VDSL mit Komfort 18.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1201, 900, 513, 'dsl', 1, 0);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1201, 999, 513, 'phone', 1, 0);

-- Surf&Fon - TAL analog 18.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1202, 900, 421, 'phone_dsl', 2, 0);

-- Surf&Fon - TAL analog 18.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1203, 900, 420, 'dsl', 2, 0);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1203, 999, 420, 'phone', 2, 0);

 
-- Surf&Fon - VDSL 50.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1204, 901, 513, 'phone_dsl', 1, 0);

-- Surf&Fon - VDSL mit Komfort 50.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1205, 901, 513, 'dsl', 1, 0);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1205, 999, 513, 'phone', 1, 0);
  
 
-- Surf&Fon - TAL VDSL 50.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1206, 901, 514, 'phone_dsl', 2, 0);

-- Surf&Fon - TAL VDSL mit Komfort 50.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1207, 901, 514, 'dsl', 2, 0);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1207, 999, 514, 'phone', 2, 0);
  
  
-- Surf&Fon - VDSL 100.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1208, 902, 513, 'phone_dsl', 1, 0);

-- Surf&Fon - VDSL mit Komfort 100.000
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1209, 902, 513, 'dsl', 1, 0);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1209, 999, 513, 'phone', 1, 0);
  
 
-- Telefon-Flat - VDSL (Mapping bereits vorhanden 511/511)
