-- Surf-Flat 18.000 - VSDL
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1211, 903, 512, 'phone_dsl', 1, 0);

-- Surf-Flat 18.000 - TAL
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, PRIORITY, VERSION)
 values (1210, 903, 440, 'phone_dsl', 2, 0);
 