-- Füge Referenz von Aufträgen des Typs "MVS Site" auf "MVS Enterprise"
ALTER TABLE T_AUFTRAG_MVS ADD (PARENT NUMBER(10));
ALTER TABLE T_AUFTRAG_MVS ADD CONSTRAINT FK_MVS_SITE_2_ENTERPRISE FOREIGN KEY (PARENT) REFERENCES T_AUFTRAG_MVS (ID);