CREATE TABLE T_MAIL (
    ID NUMBER(18) PRIMARY KEY,
    MAIL_FROM VARCHAR2(50 BYTE) NOT NULL,
    CC VARCHAR2(50 BYTE),
    MAIL_TO VARCHAR2(50 BYTE) NOT NULL,
    SUBJECT VARCHAR2(50 BYTE) NOT NULL,
    TEXT VARCHAR2(50 BYTE),

    NUMBER_OF_TRIES NUMBER(10) NOT NULL,
    SENT_AT VARCHAR2(50 BYTE),
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR2(50 BYTE) NOT NULL,
    VERSION NUMBER(18) NOT NULL
);

CREATE SEQUENCE S_T_MAIL_0;

GRANT SELECT ON T_MAIL TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_MAIL TO R_HURRICAN_TECHNIKMUC;
GRANT SELECT, UPDATE ON T_MAIL TO R_HURRICAN_TOOLS;
GRANT INSERT, SELECT, UPDATE ON T_MAIL TO R_HURRICAN_USER;
GRANT SELECT ON S_T_MAIL_0 TO PUBLIC;


CREATE TABLE T_MAIL_ATTACHMENT (
    ID NUMBER(18) PRIMARY KEY,
    FILE_NAME VARCHAR2(100 BYTE) NOT NULL,
    ATTACHMENT_FILE BLOB NOT NULL,
    MAIL_ID NUMBER(18) NOT NULL,
    VERSION NUMBER(18) NOT NULL,
    CONSTRAINT FK_MAIL_ATTACHMENT_2_MAIL FOREIGN KEY (MAIL_ID) REFERENCES T_MAIL(ID)
);

CREATE INDEX IX_MAIL_ATTACHMENT_MAIL_ID ON T_MAIL_ATTACHMENT(MAIL_ID);

CREATE SEQUENCE S_T_MAIL_ATTACHMENT_0;

GRANT SELECT ON T_MAIL_ATTACHMENT TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_MAIL_ATTACHMENT TO R_HURRICAN_TECHNIKMUC;
GRANT SELECT, UPDATE ON T_MAIL_ATTACHMENT TO R_HURRICAN_TOOLS;
GRANT INSERT, SELECT, UPDATE ON T_MAIL_ATTACHMENT TO R_HURRICAN_USER;
GRANT SELECT ON S_T_MAIL_ATTACHMENT_0 TO PUBLIC;
