ALTER TABLE T_MAIL ADD (AUFTRAG_ID NUMBER(10));
ALTER TABLE T_MAIL ADD (VERLAUF_ID NUMBER(10));

ALTER TABLE T_MAIL ADD CONSTRAINT FK_T_MAIL_2_T_AUFTRAG_ID FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);
ALTER TABLE T_MAIL ADD CONSTRAINT FK_T_MAIL_2_T_VERLAUF_ID FOREIGN KEY (VERLAUF_ID) REFERENCES T_VERLAUF (ID);

CREATE INDEX IX_MAIL_AUFTRAG_ID ON T_MAIL (AUFTRAG_ID);
CREATE INDEX IX_MAIL_VERLAUF_ID ON T_MAIL (VERLAUF_ID);
