-- SQL Script, um weitere Housing-Daten aufzunehmen

create table T_HOUSING_BUILDING (
    ID NUMBER(10) NOT NULL
  , BUILDING VARCHAR2(50) NOT NULL
  , ADDRESS_ID NUMBER(10) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_HOUSING_BUILDING ADD CONSTRAINT PK_T_HOUSING_BUILDING PRIMARY KEY (ID);
CREATE INDEX IX_FK_HOB_2_ADDRESS ON T_HOUSING_BUILDING (ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HOUSING_BUILDING ADD CONSTRAINT FK_HOB_2_ADDRESS
  FOREIGN KEY (ADDRESS_ID) REFERENCES T_ADDRESS (ID);
create SEQUENCE S_T_HOUSING_BUILDING_0 start with 1;
grant select on S_T_HOUSING_BUILDING_0 to public;
GRANT SELECT ON T_HOUSING_BUILDING TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HOUSING_BUILDING TO R_HURRICAN_USER;


create table T_HOUSING_FLOOR (
    ID NUMBER(10) NOT NULL
  , BUILDING_ID NUMBER(10) NOT NULL
  , FLOOR VARCHAR2(20) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_HOUSING_FLOOR ADD CONSTRAINT PK_T_HOUSING_FLOOR PRIMARY KEY (ID);
CREATE INDEX IX_FK_HOFLOOR_2_BUILDING ON T_HOUSING_FLOOR (BUILDING_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HOUSING_FLOOR ADD CONSTRAINT FK_HOFLOOR_2_BUILDING
  FOREIGN KEY (BUILDING_ID) REFERENCES T_HOUSING_BUILDING (ID);
create SEQUENCE S_T_HOUSING_FLOOR_0 start with 1;
grant select on S_T_HOUSING_FLOOR_0 to public;
GRANT SELECT ON T_HOUSING_FLOOR TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HOUSING_FLOOR TO R_HURRICAN_USER;



create table T_HOUSING_ROOM (
    ID NUMBER(10) NOT NULL
  , FLOOR_ID NUMBER(10) NOT NULL
  , ROOM VARCHAR2(20) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_HOUSING_ROOM ADD CONSTRAINT PK_T_HOUSING_ROOM PRIMARY KEY (ID);
CREATE INDEX IX_FK_HOFROOM_2_FLOOR ON T_HOUSING_ROOM (FLOOR_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HOUSING_ROOM ADD CONSTRAINT FK_HOFROOM_2_FLOOR
  FOREIGN KEY (FLOOR_ID) REFERENCES T_HOUSING_ROOM (ID);
create SEQUENCE S_T_HOUSING_ROOM_0 start with 1;
grant select on S_T_HOUSING_ROOM_0 to public;
GRANT SELECT ON T_HOUSING_ROOM TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HOUSING_ROOM TO R_HURRICAN_USER;



create table T_HOUSING_PARCEL (
    ID NUMBER(10) NOT NULL
  , ROOM_ID NUMBER(10) NOT NULL
  , PARCEL VARCHAR2(20) NOT NULL
  , QM NUMBER(10)
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_HOUSING_PARCEL ADD CONSTRAINT PK_T_HOUSING_PARCEL PRIMARY KEY (ID);
CREATE INDEX IX_FK_HOFPARCEL_2_ROOM ON T_HOUSING_PARCEL (ROOM_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HOUSING_PARCEL ADD CONSTRAINT FK_HOPARCEL_2_ROOM
  FOREIGN KEY (ROOM_ID) REFERENCES T_HOUSING_PARCEL (ID);
create SEQUENCE S_T_HOUSING_PARCEL_0 start with 1;
grant select on S_T_HOUSING_PARCEL_0 to public;
GRANT SELECT ON T_HOUSING_PARCEL TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HOUSING_PARCEL TO R_HURRICAN_USER;


alter table T_AUFTRAG_HOUSING add BUILDING_ID NUMBER(10);
alter table T_AUFTRAG_HOUSING add FLOOR_ID NUMBER(10);
alter table T_AUFTRAG_HOUSING add ROOM_ID NUMBER(10);
alter table T_AUFTRAG_HOUSING add PARCELL_ID NUMBER(10);
alter table T_AUFTRAG_HOUSING add RACK VARCHAR2(20);
alter table T_AUFTRAG_HOUSING add RACK_UNITS NUMBER(10);
alter table T_AUFTRAG_HOUSING add ELECTRIC_CIRCUIT_COUNT NUMBER(10);
alter table T_AUFTRAG_HOUSING add ELECTRIC_CAPACITY NUMBER(10);
alter table T_AUFTRAG_HOUSING add ELECTRIC_SAFEGUARD NUMBER(10);
alter table T_AUFTRAG_HOUSING add ELECTRIC_COUNTER_START NUMBER(10);
alter table T_AUFTRAG_HOUSING add ELECTRIC_COUNTER_END NUMBER(10);




