-- baugruppenTyp 231
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_10000_H',null,'50000','10000','0',null,24,28,null,'1',0,null,null,'0',231,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_20000_H',null,'50000','20000','0',null,24,54,null,'1',0,null,null,'0',231,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_5000_H',null,'25000','5000','0',null,23,27,null,'1',0,null,null,'0',231,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_10000_H',null,'25000','10000','0',null,23,28,null,'1',0,null,null,'0',231,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_1000_H',null,'16000','1000','0',null,12,22,null,'1',0,null,null,'0',231,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_2000_H',null,'16000','2000','0',null,12,26,null,'1',0,null,null,'0',231,null,null,null,'0');
-- baugruppenTyp 175
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_100000_20000_H',null,'100000','20000','0',null,25,54,null,'1',0,null,null,'0',175,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_10000_H',null,'50000','10000','0',null,24,28,null,'1',0,null,null,'0',175,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_20000_H',null,'50000','20000','0',null,24,54,null,'1',0,null,null,'0',175,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_5000_H',null,'25000','5000','0',null,23,27,null,'1',0,null,null,'0',175,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_10000_H',null,'25000','10000','0',null,23,28,null,'1',0,null,null,'0',175,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_1000_H',null,'16000','1000','0',null,12,22,null,'1',0,null,null,'0',175,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_2000_H',null,'16000','2000','0',null,12,26,null,'1',0,null,null,'0',175,null,null,null,'0');
-- baugruppenTyp 174 (50000)
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_10000_H',null,'50000','10000','0',null,24,28,null,'1',0,null,null,'0',174,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_20000_H',null,'50000','20000','0',null,24,54,null,'1',0,null,null,'0',174,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_5000_H',null,'25000','5000','0',null,23,27,null,'1',0,null,null,'0',174,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_10000_H',null,'25000','10000','0',null,23,28,null,'1',0,null,null,'0',174,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_1000_H',null,'16000','1000','0',null,12,22,null,'1',0,null,null,'0',174,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_2000_H',null,'16000','2000','0',null,12,26,null,'1',0,null,null,'0',174,null,null,null,'0');
-- baugruppenTyp 172
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_100000_20000_H',null,'100000','20000','0',null,25,54,null,'1',0,null,null,'0',172,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_10000_H',null,'50000','10000','0',null,24,28,null,'1',0,null,null,'0',172,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_20000_H',null,'50000','20000','0',null,24,54,null,'1',0,null,null,'0',172,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_5000_H',null,'25000','5000','0',null,23,27,null,'1',0,null,null,'0',172,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_10000_H',null,'25000','10000','0',null,23,28,null,'1',0,null,null,'0',172,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_1000_H',null,'16000','1000','0',null,12,22,null,'1',0,null,null,'0',172,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_2000_H',null,'16000','2000','0',null,12,26,null,'1',0,null,null,'0',172,null,null,null,'0');
-- baugruppenTyp 151 (50000)
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_10000_H',null,'50000','10000','0',null,24,28,null,'1',0,null,null,'0',151,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_20000_H',null,'50000','20000','0',null,24,54,null,'1',0,null,null,'0',151,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_5000_H',null,'25000','5000','0',null,23,27,null,'1',0,null,null,'0',151,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_10000_H',null,'25000','10000','0',null,23,28,null,'1',0,null,null,'0',151,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_1000_H',null,'16000','1000','0',null,12,22,null,'1',0,null,null,'0',151,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_2000_H',null,'16000','2000','0',null,12,26,null,'1',0,null,null,'0',151,null,null,null,'0');
-- baugruppenTyp 37
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_100000_20000_H',null,'100000','20000','0',null,25,54,null,'1',0,null,null,'0',37,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_10000_H',null,'50000','10000','0',null,24,28,null,'1',0,null,null,'0',37,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_50000_20000_H',null,'50000','20000','0',null,24,54,null,'1',0,null,null,'0',37,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_5000_H',null,'25000','5000','0',null,23,27,null,'1',0,null,null,'0',37,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_25000_10000_H',null,'25000','10000','0',null,23,28,null,'1',0,null,null,'0',37,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_1000_H',null,'16000','1000','0',null,12,22,null,'1',0,null,null,'0',37,null,null,null,'0');
INSERT INTO T_DSLAM_PROFILE (ID,NAME,BEMERKUNG,DOWNSTREAM,UPSTREAM,FASTPATH,UETV,DOWNSTREAM_TECH_LS,UPSTREAM_TECH_LS,FASTPATH_TECH_LS,GUELTIG,VERSION,TM_DOWN,TM_UP,ADSL1FORCE,BAUGRUPPEN_TYP,DOWNSTREAM_NETTO,UPSTREAM_NETTO,L2POWER,ENABLED_FOR_AUTOCHANGE)
    VALUES (S_T_DSLAM_PROFILE_0.nextVal,'MD_16000_2000_H',null,'16000','2000','0',null,12,26,null,'1',0,null,null,'0',37,null,null,null,'0');


