--
-- SQL-Script um notwendige GRANTs anzulegen.
--

-- Grants fuer HURRICAN definieren
GRANT SELECT, INSERT, UPDATE ON T_CPS_TX TO R_HURRICAN_USER;
GRANT SELECT ON T_CPS_TX TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_CPS_TX_LOG TO R_HURRICAN_USER;
GRANT SELECT ON T_CPS_TX_LOG TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_CPS_TX_SUB_ORDERS TO R_HURRICAN_USER;
GRANT SELECT ON T_CPS_TX_SUB_ORDERS TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CPS_DATA_CHAIN_CONFIG TO R_HURRICAN_USER;
GRANT SELECT ON T_CPS_DATA_CHAIN_CONFIG TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_EMERGENCYCALL_CONFIG TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_EMERGENCYCALL_CONFIG TO R_HURRICAN_USER;
GRANT SELECT ON T_CFG_REG_EXP TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_CFG_REG_EXP TO R_HURRICAN_USER;


-- Grants fuer TAIFUN definieren
GRANT SELECT ON DN_TNB TO R_MNET_READ_ONLY;
