CREATE TABLE T_VERLAUF_SUB_ORDERS(VERLAUF_ID INTEGER NOT NULL, AUFTRAG_ID INTEGER NOT NULL);

COMMENT ON TABLE T_VERLAUF_SUB_ORDERS IS 'Enthält zusätzliche Aufträge die in einem Verlauf gebündelt sind.';
COMMENT ON COLUMN T_VERLAUF_SUB_ORDERS.VERLAUF_ID IS 'Referenzierter Verlauf';
COMMENT ON COLUMN T_VERLAUF_SUB_ORDERS.AUFTRAG_ID IS 'Referenzierter Auftrag';

ALTER TABLE T_VERLAUF_SUB_ORDERS ADD (CONSTRAINT PK_T_VERLAUF_SUB_ORDERS PRIMARY KEY(VERLAUF_ID));

ALTER TABLE T_VERLAUF_SUB_ORDERS ADD (CONSTRAINT FK_VERLSUBORDERS_2_VERLAUF FOREIGN KEY (VERLAUF_ID) REFERENCES T_VERLAUF (ID),
  CONSTRAINT FK_VERLSUBORDERS_2_AUFTRAG FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID));

GRANT SELECT ON T_VERLAUF_SUB_ORDERS TO R_HURRICAN_READ_ONLY;
GRANT INSERT, SELECT, UPDATE, DELETE ON T_VERLAUF_SUB_ORDERS TO R_HURRICAN_USER;
