create table area (
  AREA_NO INT(9),
  DESCRIPTION VARCHAR(200),
  constraint PK_AREA primary key (AREA_NO)
) ENGINE=MyISAM;

create table ADRESSE(
    ADRESSE_NO INT(10),
    KUNDE_NO INT(10),
    IS_KUNDE CHAR (1) default '1',
    IS_KORRESPONDENZ CHAR (1) default '0',
    ANREDE VARCHAR (40) default 'KEINE',
    VORNAME VARCHAR (30),
    NAME VARCHAR (50),
    TITLE VARCHAR (50),
    NAME_ADD VARCHAR (60),
    STRASSE VARCHAR (60),
    STREET_ADD VARCHAR (60),
    POSTFACH VARCHAR (20),
    PLZ CHAR (10),
    ORT VARCHAR (40),
    LOCATION_ADD VARCHAR (60),
    FORMAT VARCHAR (20),
    HIST_NAME_ZUSATZ VARCHAR (30),
    VORSATZWORT CHAR (10),
    HIST_NAME_ZUSATZ2 VARCHAR (30),
    TITEL2 VARCHAR (50),
    VORNAME2 VARCHAR (30),
    VORSATZWORT2 CHAR (10),
    NAME2 VARCHAR (40),
    SONST_NAME_ZUSATZ VARCHAR (30),
    NUMMER CHAR (10),
    HAUSNUMMER_ZUSATZ CHAR (6),
    ANSPRECHPARTNER VARCHAR (30),
    constraint PK_ADRESSE primary key (ADRESSE_NO)
) ENGINE=MyISAM;

create table ADDRESS_FORMAT(
	FORMAT_NAME VARCHAR(40),
	DEFAULT_FORMAT TEXT,
	SHORT_FORMAT TEXT,
	NAME_FORMAT TEXT,
	SALUTATION_FORMAT TEXT
) ENGINE=MyISAM;

create table AUFTRAG(
    AUFTRAG_NO INT(10),
    AUFTRAG__NO INT(10) default 0,
    GUELTIG_VON DATE default null,
    GUELTIG_BIS DATE default null,
    HIST_STATUS CHAR (3) default 'NEU',
    HIST_CNT INT(10) default 0,
    HIST_LAST CHAR (1) default '1',
    PRIMARY_INSTANCE CHAR (1) default '1',
    ATYP CHAR (5),
    ASTATUS INT(10),
    OE__NO INT(10),
    KUNDE__NO INT(10),
    BEARBEITER_NO INT(10),
    WUNSCH_TERMIN DATE default null,
    BEMERKUNGEN VARCHAR (2000),
    BUNDLE_ORDER_NO INT(10),
    R_INFO__NO INT(10),
    SAP_ID VARCHAR (15),
    AP_ADDRESS_NO INT(10),
    USERW CHAR (10),
    DATEW DATE default null,
    BEARBEITER_KUNDE VARCHAR (60),
    BEARBEITER_KUNDE_FAX CHAR (20),
    BEARBEITER_KUNDE_RN CHAR (20),
    BEARBEITER_KUNDE_EMAIL VARCHAR (40),
    HAENDLER__NO INT(10),
    BUSINESS_UNIT INT(10),
    VERTRAGSDATUM DATE default null,
    OLD_SERVICE__NO VARCHAR (20),
    BESTELL_ID VARCHAR (20),
    INV_ELECTRONIC CHAR(1),
    INV_MAXI CHAR(1),
    constraint PK_AUFTRAG primary key (AUFTRAG_NO)
) ENGINE=MyISAM;


create table ACCOUNT(
    AUFTRAG_NO INT (10),
    ACCOUNT_ID CHAR (20),
    ACCOUNTNAME VARCHAR(30),
    USERW CHAR (10),
    DATEW DATE default null
) ENGINE=MyISAM;

create table CONTACT(
    CONTACT_NO INT(10),
    KUNDE__NO INT(10),
    AUFTRAG__NO INT(10),
    CONTACT_TYPE VARCHAR (50),
    SALUTATION VARCHAR (10),
    TITLE VARCHAR (30),
    FIRSTNAME VARCHAR (30),
    NAME VARCHAR (40),
    STREET VARCHAR (40),
    ADDRESS_LINE1 VARCHAR (60),
    ADDRESS_LINE2 VARCHAR (60),
    POSTBOX VARCHAR (20),
    ZIP CHAR (10),
    LOCATION VARCHAR (40),
    PHONE VARCHAR (30),
    MOBILE VARCHAR (30),
    PAGER VARCHAR (30),
    FAX VARCHAR (30),
    EMAIL VARCHAR (50),
    DESCRIPTION VARCHAR (255),
    USERW CHAR (10),
    DATEW DATE default null,
    ANSPRECHPARTNER_INFO VARCHAR (50),
    constraint PK_CONTACT primary key (CONTACT_NO)
) ENGINE=MyISAM;

create table AUFTRAGPOS(
	ITEM_NO INT(10), 
	ITEM__NO INT(10), 
	ORDER__NO INT(10), 
	CREATE_ORDER_NO INT (10),
    TERMINATE_ORDER_NO INT(10),
    IS_PLANNED CHAR (1) default '0',
    SERVICE_ELEM__NO INT(10),
    CHARGE_FROM DATE default null,
    CHARGE_TO DATE default null,
    CHARGED_UNTIL DATE default null,
    PARAMETER VARCHAR (50),
    QUANTITY DECIMAL (18, 2),
    PRICE DECIMAL(18, 2),
    CURRENCY_ID CHAR (3),
    FREETEXT VARCHAR (64),
    constraint PK_AUFTRAGPOS primary key (ITEM_NO)
) ENGINE=MyISAM;

create table DN_BLOCK(
    BLOCK_NO INT(10),
    BLOCK__NO INT(10) default 0,
    VALID_FROM DATE default null,
    VALID_TO DATE default null,
    HIST_STATE CHAR (3) default 'NEU',
    HIST_CNT INT(10) default 0,
    HIST_LAST CHAR (1) default '1',
    PRIMARY_INSTANCE CHAR (1) default '1',
    ONKZ VARCHAR (10),
    BLOCK_ID VARCHAR (10),
    LENGTH CHAR (4),
    PUBLISH_DATE DATE default null,
    CARRIER CHAR (20),
    PARTITIONED INT(10) default 0,
    REMARKS VARCHAR (200),
    constraint PK_DN_BLOCK primary key (BLOCK_NO)
) ENGINE=MyISAM;

create table DN(
    DN_NO INT(10),
    DN__NO INT(10) default 0,
    VALID_FROM DATE default null,
    VALID_TO DATE default null,
    HIST_STATE CHAR (3) default 'NEU',
    HIST_CNT INT(10) default 0,
    HIST_LAST CHAR (1) default '1',
    PRIMARY_INSTANCE CHAR (1) default '1',
    ORDER__NO INT(10),
    BLOCK__NO INT(10),
    ONKZ VARCHAR (10),
    DN_BASE VARCHAR (10),
    DIRECT_DIAL VARCHAR (5),
    RANGE_FROM CHAR (5),
    RANGE_TO CHAR (5),
    DN_SIZE INT(10),
    ALLOCATED_SIZE INT(10),
    STATE VARCHAR (20),
    FREE_DATE DATE default null,
    CONNECTION_TYPE VARCHAR (50) default 'Unbekannt',
    IS_MAIN_NUMBER CHAR (1) default '0',
    OE__NO INT(10),
    SWITCH_ID VARCHAR (10),
    ACCOUNT_NST CHAR (1) default '0',
    PORT_MODE VARCHAR (50),
    WISH_DATE DATE default null,
    WISH_TIME DATE default null,
    LAST_CARRIER CHAR (20),
    ACT_CARRIER CHAR (20),
    FUTURE_CARRIER CHAR (20),
    EDITOR_NO INT(10),
    NON_BILLABLE CHAR (1) default '0',
    REMARKS VARCHAR (200),
    REAL_DATE DATE default null,
    REAL_TIME_FROM DATE default null,
    REAL_TIME_TO DATE default null,
    PORT_DOC_SENT DATE default null,
    PORT_DOC_RECEIVED DATE default null,
    constraint PK_DN primary key (DN_NO)
) ENGINE=MyISAM;

create table KUNDE(
    KUNDE_NO INT(10),
    KUNDE__NO INT(10) default 0,
    GUELTIG_VON DATE default null,
    GUELTIG_BIS DATE default null,
    HIST_STATUS CHAR (3) default 'NEU',
    HIST_CNT INT(10) default 0,
    HIST_LAST CHAR (1) default '1',
    PRIMARY_INSTANCE CHAR (1) default '1',
    NAME VARCHAR (40),
    VORNAME VARCHAR (40),
    PASSWORD VARCHAR (32),
    KUNDENSEGMENT_NO INT(10),
    HAUPTRUFNUMMER CHAR (20),
    RN_GESCHAEFT CHAR (20),
    RN_FAX CHAR (20),
    RN_MOBILE CHAR (20),
    EMAIL VARCHAR (96),
    HOMEPAGE VARCHAR (96),
    NATIONALITAET_ID CHAR (2) default 'DE',
    AREA_NO INT(10),
    KUNDENTYP CHAR (15),
    COMPANY_TYPE_NO INT(10) default 0,
    HAUPT_KUNDE_NO INT(10),
    KUNDENBETREUER_NO INT(10),
    ACCOUNT_MANAGER INT(10),
    BRANCHE_NO INT(10),
    LEGAL_FORM VARCHAR (15),
    BONITAET_ID CHAR (2) default '00',
    IST_KUNDE CHAR (1) default '1',
    IST_CARRIER CHAR (1) default '0',
    PRINT_FEATURE CHAR (10) default '',
    REC_SOURCE CHAR (10) default 'MNet',
    EXT_CUSTOMER_ID VARCHAR (20),
    USERW CHAR (10),
    DATEW DATE default null,
    HANDELSREG_NR CHAR (10),
    REGISTERGER_NR VARCHAR (50),
    RESELLER_KUNDE_NO INT(10),
    VIP CHAR (4) default 'Nein',
    AUF_BLACKLIST CHAR (1),
    LISTENDATUM DATE default null,
    IST_HAUPTKUNDE CHAR (1) default '1',
    IST_HAENDLER CHAR (1) default '0',
    IST_RESELLER CHAR (1) default '0',
    IST_BETREIBER CHAR (1) default '0',
    HAENDLER_ID VARCHAR (12),
    IST_INTERESSENT CHAR (1) default '0',
    IST_MITA_CNS CHAR (1) default '0',
    FREIGABE_RECHSTELL CHAR (4) default 'Ja',
    MAHNSTOPP_ID CHAR (2),
    REC_APPROVED CHAR (4) default 'Ja',
    ANZAHL_MITARB CHAR (10),
    FERNKATASTROPHE CHAR (1) default '0',
    BONI_INDEX CHAR (4),
    KREDIT_LIMIT CHAR (6),
    constraint PK_KUNDE primary key (KUNDE_NO)
) ENGINE=MyISAM;

create table LEISTUNG(
    LEISTUNG_NO INT(10),
    LEISTUNG__NO INT(10) default 0,
    GUELTIG_VON DATE default null,
    GUELTIG_BIS DATE default null,
    HIST_STATUS CHAR (3) default 'NEU',
    HIST_CNT INT(10) default 0,
    HIST_LAST CHAR (1) default '1',
    PRIMARY_INSTANCE CHAR (1) default '1',
    GENERATE_BILLPOS CHAR (1) default '1',
    NAME VARCHAR (40),
    LEISTUNGCODE CHAR (20),
    DIS_GROUP_NO INT(10),
    BILLING_CODE VARCHAR (20),
    TECH_EXPORT CHAR (1) default '0',
    PARAM_VALUES VARCHAR (512),
    OE__NO INT(10),
    LER_NO INT(10),
    LEISTUNGKAT CHAR (15) default 'WIEDERHOLT',
    MENGE_EDITIERBAR CHAR (1) default '0',
    MENGE DECIMAL (18, 2),
    BEDINGUNG VARCHAR (100),
    MERKMAL VARCHAR (50),
    MASS CHAR (8),
    BILLING_PRICE_SOURCE VARCHAR (20),
    BILLING_QUANTITY_SOURCE VARCHAR (20),
    HAUPTGRUPPE VARCHAR (10),
    GRUPPE VARCHAR (10),
    UNTERGRUPPE VARCHAR (10),
    SAP_AUFTRAG_ID CHAR (10),
    LEISTUNGEXTERN CHAR (30),
    BESCHREIBUNG VARCHAR (2000),
    FIBU_ACCOUNT CHAR (15),
    FIBU_TAX_TYPE CHAR (15),
    BS_RELEVANT CHAR (1),
    EXT_MISC__NO INT(10),
    EXT_PRODUKT__NO INT(10),
    EXT_LEISTUNG__NO INT(10),
    CUSTOMER_CAT_NO INT(10),
    constraint PK_LEISTUNG primary key (LEISTUNG_NO)
) ENGINE=MyISAM;

create table LEISTUNG_LANG(
    LEISTUNG_LANG_NO INT(10),
    VALUE VARCHAR (100),
    LEISTUNG_NO INT(10),
    LANGUAGE CHAR (12),
    NAME VARCHAR (100),
    constraint PK_LEISTUNG_LANG primary key (LEISTUNG_LANG_NO)
) ENGINE=MyISAM;

create table OE(
    OE_NO INT(10),
    OE__NO INT(10) default 0,
    VATER_OE_NO INT(10),
    VORG_OE_NO INT(10),
    GUELTIG_VON DATE default null,
    GUELTIG_BIS DATE default null,
    HIST_STATUS CHAR (3) default 'NEU',
    PRIMARY_INSTANCE CHAR (1) default '1',
    HIST_CNT INT(10) default 0,
    HIST_LAST CHAR (1) default '1',
    OETYP CHAR (20),
    PRODUKTCODE CHAR (10),
    PRODUCT_ID VARCHAR (20),
    BILLING_CODE VARCHAR (10),
    NAME VARCHAR (30),
    MINDESTUMSATZ INT(10),
    MINDESTVERTRAGSDAUER INT(10),
    PRODUKTEXTERN CHAR (10),
    AUFTRAG_ZUSATZ VARCHAR (40),
    AUFTRAG_KLASSE VARCHAR (40),
    BESCHREIBUNG VARCHAR (2000),
    FIBU_PRODUCT_TYPE VARCHAR (15),
    FIBU_COST_OBJECT VARCHAR (15),
    INVOICE_FEATURE CHAR (20),
    constraint PK_OE primary key (OE_NO)
) ENGINE=MyISAM;

create table OE_LANG(
    OE_NO INT(10),
    LANGUAGE CHAR (12),
    NAME VARCHAR (50),
    constraint PK_OE_LANG primary key (OE_NO, LANGUAGE)
) ENGINE=MyISAM;

create table PERSON(
    PERSON_NO INT(10),
    KURZBEZ CHAR (10),
    GESCHLECHT CHAR (1),
    NAME VARCHAR (30),
    VORNAME VARCHAR (20),
    OE__NO INT(10),
    STRASSE VARCHAR (40),
    NUMMER VARCHAR (40),
    PLZ VARCHAR (10),
    ORT VARCHAR (60),
    RN_GESCH CHAR (20),
    RN_PRIV CHAR (20),
    RN_FAX CHAR (20),
    RN_MOBILE CHAR (20),
    PRINTER_ID CHAR (20),
    EMAIL VARCHAR (40),
    constraint PK_PERSON primary key (PERSON_NO)
) ENGINE=MyISAM;

create table PRODUCT_TYPE(
    PRODUCT_OE__NO INT(10) default 0,
    PRODUCT_TYPE CHAR (20),
    ANZ_RN INT(10),
    RN_AUTO CHAR (1),
    BLOCK CHAR (1) default '0',
    DN_SIZE_FROM INT(10),
    DN_SIZE_TO INT(10),
    CONNECTION_TYPE VARCHAR (50) default 'Unbekannt',
    OE__NO INT(10),
    ANZ_VN INT(10),
    VN_AUTO CHAR (1) default '0',
    BETRIEBSWEISE CHAR (1) default '0',
    PROTOKOLL CHAR (10),
    ANSCHLUSS_ART CHAR (20),
    DTAG_KEY CHAR (20),
    AUFTRAGSBINDUNG INT(10),
    BESCHREIBUNG VARCHAR (2000),
    constraint PK_PRODUCT_TYPE primary key (PRODUCT_OE__NO)
) ENGINE=MyISAM;

create table R_INFO(
    R_INFO_NO INT(10),
    R_INFO__NO INT(10) default 0,
    DESCRIPTION VARCHAR (250),
    KUNDE_NO INT(10),
    FINANZ_NO INT(10),
    ADRESSE_NO INT(10),
    IS_DEFAULT CHAR (1),
    RECH_PERIODE INT (3) default 1,
    RECHNUNGSWHRG_ID CHAR (3) default 'EUR',
    constraint PK_R_INFO primary key (R_INFO_NO)
) ENGINE=MyISAM;

create table SERVICE_VALUE_PRICE(
    LEISTUNG_NO INT(10),
    VALUE VARCHAR (100),
    VALUE_QUANTITY DECIMAL (18, 4),
    VALUE_PRICE VARCHAR (250),
    IS_DEFAULT CHAR (1) default '0',
    ORDER_FIELD INT(10),
    EXT_MISC__NO INT(10),
    EXT_PRODUKT__NO INT(10),
    EXT_LEISTUNG__NO INT(10),
    FIBU_ACCOUNT CHAR (15),
    constraint PK_SERVICE_VALUE_PRICE primary key (LEISTUNG_NO, VALUE)
) ENGINE=MyISAM;


CREATE INDEX IX_DN_ONKZ ON DN (ONKZ ASC);
CREATE INDEX IX_DN_BASE ON DN (DN_BASE ASC);
CREATE INDEX IX_KUNDE ON KUNDE (KUNDE__NO ASC);
CREATE INDEX IX_AUFTRAG__NO ON AUFTRAG (AUFTRAG__NO ASC);
CREATE INDEX IX_AUFTRAG_NO ON AUFTRAG (AUFTRAG_NO ASC);
CREATE INDEX IX_AUFTRAGPOS ON AUFTRAGPOS (ORDER__NO ASC);
CREATE INDEX IX_AUFTRAGPOS_SERVELEM ON AUFTRAGPOS (SERVICE_ELEM__NO ASC);
CREATE INDEX IX_LEISTUNG ON LEISTUNG (LEISTUNG__NO ASC);
CREATE INDEX IX_LEISTUNG_NO ON LEISTUNG (LEISTUNG_NO ASC);
CREATE INDEX IX_LEISTUNG_LANG ON LEISTUNG_LANG (VALUE ASC);
CREATE INDEX IX_LEISTUNG_LANG_NO ON LEISTUNG_LANG (LEISTUNG_NO ASC);
CREATE INDEX IX_ADRESSE ON ADRESSE (ADRESSE_NO ASC);
CREATE INDEX IX_ADRESSE_KUNDE ON ADRESSE (KUNDE_NO ASC);
CREATE INDEX IX_SERVICE_VAL ON SERVICE_VALUE_PRICE (VALUE ASC);
CREATE INDEX IX_OE__NO ON OE (OE__NO ASC);
CREATE INDEX IX_DN__NO ON DN (DN__NO ASC);
CREATE INDEX IX_KUNDE__NO ON KUNDE (KUNDE__NO ASC);
CREATE INDEX IX_RINFO__NO ON R_INFO (RINFO__NO ASC);
CREATE INDEX IX_ACCOUNT_ID ON ACCOUNT (ACCOUNT_ID ASC);

