-- ANF-767 Neuer RackTyp
-- Korrektur des vorherigen Skripts

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE T_HW_RACK_DPU';
EXCEPTION
  WHEN OTHERS
    THEN
  NULL;
END;
/

DELETE FROM T_HW_BG_TYP_2_PHYSIK_TYP WHERE PHYSIKTYP_ID = 810;

DELETE FROM T_PHYSIKTYP WHERE ID = 810;

DELETE FROM T_HW_BAUGRUPPEN_TYP WHERE NAME = 'MA5811S AE04';
DELETE FROM T_HW_BAUGRUPPEN_TYP WHERE NAME = 'MA5811S AE08';
DELETE FROM T_HW_BAUGRUPPEN_TYP WHERE NAME = 'MA5811S DE16';

DELETE FROM T_REFERENCE WHERE ID = 9601;


-- Neuanlage der Daten

CREATE TABLE T_HW_RACK_DPU (
  RACK_ID NUMBER(19) PRIMARY KEY NOT NULL,
  OLT_RACK_ID NUMBER(19) NOT NULL,
  SERIAL_NO varchar2(50),
  OLT_FRAME varchar2(2) NOT NULL,
  OLT_SHELF varchar2(2) NOT NULL,
  OLT_GPON_PORT varchar2(2) NOT NULL,
  OLT_GPON_ID varchar2(3) NOT NULL,
  OLT_SUBRACK varchar2(2),
  FREIGABE timestamp,
  DPU_TYPE varchar2(16) NOT NULL,
  REVERSE_POWER char(1),
  VERSION decimal(18) DEFAULT 0  NOT NULL
);

ALTER TABLE T_HW_RACK_DPU ADD CONSTRAINT FK_HWRACKDPU_2_HWRACK FOREIGN KEY (RACK_ID) REFERENCES T_HW_RACK (ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK_DPU TO R_HURRICAN_HW_ADMIN;
GRANT SELECT ON T_HW_RACK_DPU TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_HW_RACK_DPU TO R_HURRICAN_TECHNIKMUC;

INSERT INTO T_REFERENCE (ID,TYPE,STR_VALUE,INT_VALUE,FLOAT_VALUE,UNIT_ID,GUI_VISIBLE,ORDER_NO,DESCRIPTION,VERSION)
VALUES (9601,'HW_RACK_TYPE','DPU',null,null,null,'1',110,'HW-Rack Typ DPU.',0);


-- Baugruppen-Typen anlegen
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, TUNNELING, DEF_SCHICHT2_PROTOKOLL, MAX_BANDWIDTH_DOWNSTREAM,
                                 MAX_BANDWIDTH_UPSTREAM, BONDING_CAPABLE)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'MA5811S_AE04', 4, 'Huawei MA5811S AE04 mit 4 Ports', '1', 'GFAST', 'DPU',
   2, 0, NULL, NULL, 150000, 100000, '0');

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, TUNNELING, DEF_SCHICHT2_PROTOKOLL, MAX_BANDWIDTH_DOWNSTREAM,
                                 MAX_BANDWIDTH_UPSTREAM, BONDING_CAPABLE)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'MA5811S_AE08', 8, 'Huawei MA5811S AE08 mit 8 Ports', '1', 'GFAST', 'DPU',
   2, 0, NULL, NULL, 150000, 100000, '0');

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, TUNNELING, DEF_SCHICHT2_PROTOKOLL, MAX_BANDWIDTH_DOWNSTREAM,
                                 MAX_BANDWIDTH_UPSTREAM, BONDING_CAPABLE)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'MA5811S_DE16', 16, 'Huawei MA5811S DE16 mit 16 Ports', '1', 'GFAST', 'DPU',
   2, 0, NULL, NULL, 150000, 100000, '0');

-- Physiktyp fuer DPU anlegen
INSERT INTO T_PHYSIKTYP
   (ID, NAME, BESCHREIBUNG, HVT_TECHNIK_ID, HW_SCHNITTSTELLE,
    PT_GROUP, CPS_TRANSFER_METHOD, VERSION, MAX_BANDWIDTH_DOWNSTREAM, MAX_BANDWIDTH_UPSTREAM)
 Values
   (810, 'FTTB_GFAST', 'FTTB G.fast Breitband Versorgung', NULL, 'GFAST',
    NULL, NULL, 0, 150000, 100000);


-- FTTB_GFAST Physiktyp mit Baugruppen mappen
INSERT INTO T_HW_BG_TYP_2_PHYSIK_TYP
(ID, BAUGRUPPEN_TYP_ID, PHYSIKTYP_ID, VERSION)
VALUES
  (S_T_HW_BG_TYP_2_PHYSIK_TYP_0.nextval, (SELECT
                                            bgt.id
                                          FROM T_HW_BAUGRUPPEN_TYP bgt
                                          WHERE bgt.name = 'MA5811S_AE04'), 810, 0);

INSERT INTO T_HW_BG_TYP_2_PHYSIK_TYP
(ID, BAUGRUPPEN_TYP_ID, PHYSIKTYP_ID, VERSION)
VALUES
  (S_T_HW_BG_TYP_2_PHYSIK_TYP_0.nextval, (SELECT
                                            bgt.id
                                          FROM T_HW_BAUGRUPPEN_TYP bgt
                                          WHERE bgt.name = 'MA5811S_AE08'), 810, 0);

INSERT INTO T_HW_BG_TYP_2_PHYSIK_TYP
(ID, BAUGRUPPEN_TYP_ID, PHYSIKTYP_ID, VERSION)
VALUES
  (S_T_HW_BG_TYP_2_PHYSIK_TYP_0.nextval, (SELECT
                                            bgt.id
                                          FROM T_HW_BAUGRUPPEN_TYP bgt
                                          WHERE bgt.name = 'MA5811S_DE16'), 810, 0);
