-- ANF-767 Typen der OLT Childs (MDU, ONT, DPO und DPU) vergroesern
ALTER TABLE T_HW_RACK_DPO MODIFY (DPO_TYPE VARCHAR2(16));
ALTER TABLE T_HW_RACK_ONT MODIFY (ONT_TYPE VARCHAR2(16));
ALTER TABLE T_HW_RACK_MDU MODIFY (MDU_TYPE VARCHAR2(16));
