ALTER TABLE T_USER_TASK DROP CONSTRAINT T_USER_TASK_TAM_STATUS;

ALTER TABLE T_USER_TASK ADD CONSTRAINT T_USER_TASK_TAM_STATUS
  CHECK ("TAM_BEARBEITUNG_STATUS"='OFFEN' OR "TAM_BEARBEITUNG_STATUS"='IN_BEARBEITUNG' OR "TAM_BEARBEITUNG_STATUS"='KUNDE_NICHT_ERREICHT' OR "TAM_BEARBEITUNG_STATUS"='KUNDE_MELDET_SICH' OR "TAM_BEARBEITUNG_STATUS"='TV_60_TAGE' OR "TAM_BEARBEITUNG_STATUS"='TV_30_TAGE' OR "TAM_BEARBEITUNG_STATUS"='INFO_MAILED' );
