-- T_SMS_CONFIG um eine Spalte fuer den Meldungscode erweitern (wird fuer TKG-TAM verwendet)
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE T_SMS_CONFIG DROP CONSTRAINT UK_SMS_CONFIG';
  EXCEPTION
  WHEN OTHERS
  THEN
  NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UK_SMS_CONFIG';
  EXCEPTION
  WHEN OTHERS
  THEN
  NULL;
END;
/

