-- FFM Product Mappings
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 600, 11002,
    'BSA_Entstoerung', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 600, 11008,
    'BSA_Entstoerung', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 600, 11011,
    'BSA_Entstoerung', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 600, 11017,
    'BSA_Entstoerung', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG');