
CREATE TABLE T_EG_TYPE (
  ID                NUMBER(10)             NOT NULL,
  HERSTELLER        VARCHAR2(50)           NOT NULL,
  MODELL            VARCHAR2(50)           NOT NULL,
  USERW             VARCHAR2(15),
  DATEW             DATE,
  VERSION           NUMBER(18)   DEFAULT 0 NOT NULL
);


COMMENT ON TABLE T_EG_TYPE IS 'Tabelle haelt Hersteller und Typ Informationen von Endgeraeten';
COMMENT ON COLUMN T_EG_TYPE.ID IS 'ID des Datensatzes';
COMMENT ON COLUMN T_EG_TYPE.HERSTELLER IS 'Herstellername des Endgeraetetyps';
COMMENT ON COLUMN T_EG_TYPE.MODELL IS 'Modellbezeichnung des Endgeraetetyps';
COMMENT ON COLUMN T_EG_TYPE.USERW IS 'Schreibender Zugriff des letzten Benutzers';
COMMENT ON COLUMN T_EG_TYPE.DATEW IS 'Datum des letzten schreibenden Zugriffs';


CREATE SEQUENCE S_T_EG_TYPE_0 start with 1;
GRANT SELECT ON S_T_EG_TYPE_0 to public;

ALTER TABLE T_EG_TYPE ADD CONSTRAINT PK_T_EG_TYPE PRIMARY KEY (ID);

CREATE TRIGGER TRBIU_EG_TYPES BEFORE INSERT or UPDATE on T_EG_TYPE
for each row
BEGIN
 -- TIMESTAMP setzen
 SELECT CURRENT_TIMESTAMP INTO :new.DATEW FROM dual;
END;
/

GRANT SELECT ON T_EG_TYPE TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_EG_TYPE TO R_HURRICAN_USER;


ALTER TABLE T_EG_CONFIG ADD EG_TYPE_ID NUMBER(10);
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EG_TYPE_ID
  FOREIGN KEY (EG_TYPE_ID) REFERENCES T_EG_TYPE (ID);


COMMENT ON COLUMN T_EG_CONFIG.EG_TYPE_ID IS 'ID der Endgeraetetypen (T_EG_TYPE)';

CREATE INDEX IX_FK_EG_TYPE_ID ON T_EG_CONFIG (EG_TYPE_ID) TABLESPACE "I_HURRICAN";
