
alter table DEPARTMENT add HURRICAN_ABT_ID NUMBER(10);

update DEPARTMENT set HURRICAN_ABT_ID=1 WHERE ID=1;
update DEPARTMENT set HURRICAN_ABT_ID=2 WHERE ID=2;
update DEPARTMENT set HURRICAN_ABT_ID=3 WHERE ID=3;
update DEPARTMENT set HURRICAN_ABT_ID=4 WHERE ID=4;
update DEPARTMENT set HURRICAN_ABT_ID=5 WHERE ID=5;
update DEPARTMENT set HURRICAN_ABT_ID=7 WHERE ID=7;
update DEPARTMENT set HURRICAN_ABT_ID=10 WHERE ID=10;
update DEPARTMENT set HURRICAN_ABT_ID=11 WHERE ID=11;
update DEPARTMENT set HURRICAN_ABT_ID=13 WHERE ID=18;

