-- aktiviert optimistisches locking für fehlende Tabellen

ALTER TABLE USERSESSION RENAME COLUMN VERSION TO APP_VERSION;

ALTER TABLE ACCOUNT ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE APPLICATION ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE COMPBEHAVIOR ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE DB ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE DEPARTMENT ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE GUICOMPONENT ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE PWHISTORY ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE ROLE ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE USERS ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE USERACCOUNT ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE USERROLE ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;
ALTER TABLE USERSESSION ADD VERSION NUMBER(18) DEFAULT 0 NOT NULL;