ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(NT_OUTER NUMBER(10));

ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(NT_INNER NUMBER(10));

ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(LT_OUTER NUMBER(10));

ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(LT_INNER NUMBER(10));

ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(BRAS_OUTER NUMBER(10));

ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(BRAS_INNER NUMBER(10));

ALTER TABLE T_EQ_CROSS_CONNECTION
 ADD (BRAS_POOL_ID NUMBER(10));
 
ALTER TABLE T_EQ_CROSS_CONNECTION
 ADD CONSTRAINT FK_CC_2_BRAS_POOL FOREIGN KEY (BRAS_POOL_ID)
 REFERENCES T_BRAS_POOLS (ID);
