--
-- Fuegt alle bekannten TAL UseCases der CarrierKennung fuer Muenchen hinzu
--

insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (25, 1, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (26, 2, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (27, 3, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (28, 4, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (29, 6, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (30, 8, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (31, 9, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (32, 10, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (33, 11, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (34, 12, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (35, 13, 4);
insert into T_CB_USECASE_2_CARRIER_KNG (ID, USECASE_ID, CARRIERKENNUNG_ID) values (36, 14, 4);

