--
-- Loescht nicht mehr benoetigte Daten aus der Datenbank
--

ALTER TABLE T_EG_CONFIG DROP COLUMN EG_COUNT_ACT;

ALTER TABLE T_EG_CONFIG DROP COLUMN EG_COUNT_1YEAR;

ALTER TABLE T_EG_CONFIG DROP COLUMN EG_COUNT_2YEARS;

ALTER TABLE T_EG_CONFIG DROP COLUMN IP_VIRTUELL_WEB;
