CREATE TABLE T_ANSPRECHPARTNER
(
  ID           NUMBER(10)                       NOT NULL,
  ADDRESS_ID   NUMBER(10)                       NOT NULL,
  AUFTRAG_ID   NUMBER(10)                       NOT NULL,
  TYPE_REF_ID  NUMBER(10)                       NOT NULL,
  PREFERRED    CHAR(1 BYTE)                     NOT NULL,
  TEXT         VARCHAR2(255 BYTE)
) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING;


ALTER TABLE T_ANSPRECHPARTNER ADD (CONSTRAINT T_ANSPRECHPARTNER_PK PRIMARY KEY (ID));

ALTER TABLE T_ANSPRECHPARTNER ADD (
  CONSTRAINT FK_ANSPRECHPARTNER_REFERENCE FOREIGN KEY (TYPE_REF_ID)
   REFERENCES T_REFERENCE (ID) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT FK_ANSPRECHPARTNER_AUFTRAG FOREIGN KEY (AUFTRAG_ID)
   REFERENCES T_AUFTRAG (ID) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT FK_ANSPRECHPARTNER_ADDRESS FOREIGN KEY (ADDRESS_ID)
   REFERENCES T_ADDRESS (ID) DEFERRABLE INITIALLY IMMEDIATE);

	
ALTER TABLE T_ADDRESS
 ADD (TELEFON  VARCHAR2(50 BYTE));

ALTER TABLE T_ADDRESS
 ADD (HANDY  VARCHAR2(50 BYTE));

ALTER TABLE T_ADDRESS
 ADD (FAX  VARCHAR2(50 BYTE));

ALTER TABLE T_ADDRESS
 ADD (EMAIL  VARCHAR2(100 BYTE));

	
INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16000, 'ANSPRECHPARTNER', 'Kunde',
    null, null, null, 1, 10, 'Ansprechpartner: Kunde');
    
INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16001, 'ANSPRECHPARTNER', 'Rechnung',
    null, null, null, 1, 20, 'Ansprechpartner: Rechnung');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16002, 'ANSPRECHPARTNER', 'vor Ort',
    null, null, null, 1, 30, 'Ansprechpartner:Kunde');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16003, 'ANSPRECHPARTNER', 'Rückfrage',
    null, null, null, 1, 40, 'Ansprechpartner: Rückfrage');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16004, 'ANSPRECHPARTNER', 'Technischer Service',
    null, null, null, 1, 50, 'Ansprechpartner: Technischen Service');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16005, 'ANSPRECHPARTNER', 'IPSec-C2S-Kontakt',
    null, null, null, 1, 60, 'Ansprechpartner: IPSec-C2S-Kontakt');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16006, 'ANSPRECHPARTNER', 'Hotline Partner',
    null, null, null, 1, 70, 'Ansprechpartner: Hotline Partner');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16007, 'ANSPRECHPARTNER', 'Endstelle A',
    null, null, null, 1, 80, 'Ansprechpartner: Endstelle A');

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16008, 'ANSPRECHPARTNER', 'Endstelle B',
    null, null, null, 1, 90, 'Ansprechpartner:Endstelle B');
