CREATE SEQUENCE S_T_ANSPRECHPARTNER_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

GRANT SELECT ON S_T_ANSPRECHPARTNER_0 TO PUBLIC;
GRANT SELECT ON T_ANSPRECHPARTNER TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ANSPRECHPARTNER TO R_HURRICAN_USER;

