UPDATE T_REFERENCE SET ID = 16009, ORDER_NO = 100 WHERE ID = 16008;
UPDATE T_REFERENCE SET ID = 16008, ORDER_NO = 90 WHERE ID = 16007;
UPDATE T_REFERENCE SET ID = 16007, ORDER_NO = 80 WHERE ID = 16006;

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
VALUES ( 16006, 'ANSPRECHPARTNER', 'Hotline Service',
    null, null, null, 1, 70, 'Ansprechpartner: Hotline Service');
