INSERT INTO DEVICE__FRITZBOX
(DEV_NO, CWMP_ID, PASSPHRASE, SCAN_SERIENNUMMER, SCAN_CWMP_ACCOUNT)
VALUES (
  ${deviceNo:-NULL},
  '${cwmpId:-S123456789}',
  '${passphrase:-test123}',
  NULL,
  NULL
)