Insert into CUSTOMER
   (CUST_NO, PARENT_CUST_NO, VALID_FROM, IS_ACTIVE, NAME, FIRSTNAME, CUSTOMER_SEGMENT_NO, CUSTOMER_TYPE, COMPANY_TYPE_NO, CREDIT_RATING_ID, CREDIT_RATING_USERW, CREDIT_RATING_DATEW,
   NATIONALITY_ID, PHONE_CENTRAL, PHONE_BUSINESS, FAX, EMAIL, POSTAL_ADDR_NO, IS_SALES_LEAD, IS_CARRIER, IS_DEALER, IS_EMPLOYEE, IS_CUSTOMER, IS_RESELLER, AREA_NO,
   REC_SOURCE, LANGUAGE, RESELLER_CUST_NO, USERW, DATEW, CREATED_AT, IS_PARTNER, VIP, AUF_BLACKLIST, IST_BETREIBER, IST_HAUPTKUNDE, FREIGABE_RECHSTELL, REC_APPROVED,
   FERNKATASTROPHE, BONI_INDEX, IS_VERIFIED, ALLOW_TELEMARKETING_CALLS, ALLOW_EMAIL_NEWSLETTERS, ALLOW_POSTAL_ADVERTISEMENTS, COLLATERAL_DEPOSITED)
 Values (
   ${kundeNo:-NULL},
   ${hauptKundenNo:-NULL},
   sysdate,
   '1',
   '${name:-NULL}',
   '${vorname:-NULL}',
    1,
    '${kundenTyp:-PRIVAT}',
    0,
    '40',
    2035,
    TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    'DE',
    '0123/445566',
    '0123/445566',
    '0123/445566',
    '${email:-hurrican_developer@m-net.de}',
    NULL,
    '0',
    '0',
    '0',
    '0',
    '1',
    '0',
    2,
    'Test-Data',
    'DE',
    100000081,
    'TEST',
    sysdate,
    sysdate,
    '0',
    'Nein',
    '0',
    '0',
    '0',
    'Ja',
    'Ja',
    '0',
    '815',
    '1',
    '0',
    '0',
    '0',
    '0')