ALTER TABLE T_EG_CONFIG ADD DNS_SERVER_IP VARCHAR2(40);
ALTER TABLE T_EG_CONFIG ADD DNS_SERVER_SUBNET VARCHAR2(40);
ALTER TABLE T_EG_CONFIG ADD MTU NUMBER(10);

COMMENT ON COLUMN T_EG_CONFIG.DNS_SERVER_IP IS 'IP Adresse des DNS Servers';
COMMENT ON COLUMN T_EG_CONFIG.DNS_SERVER_SUBNET IS 'Subnetmaske des DNS Servers';
COMMENT ON COLUMN T_EG_CONFIG.MTU IS 'Maximum Transmission Unit (MTU) beschreibt die maximale Paketgröße eines Protokolls der Vermittlungsschicht (Schicht 3)';