grant select on ACT_GE_PROPERTY to R_HURRICAN_READ_ONLY;
grant select on ACT_GE_BYTEARRAY to R_HURRICAN_READ_ONLY;
grant select on ACT_RE_DEPLOYMENT to R_HURRICAN_READ_ONLY;
grant select on ACT_RU_EXECUTION to R_HURRICAN_READ_ONLY;
grant select on ACT_RU_JOB to R_HURRICAN_READ_ONLY;
grant select on ACT_RE_PROCDEF to R_HURRICAN_READ_ONLY;
grant select on ACT_RU_TASK to R_HURRICAN_READ_ONLY;
grant select on ACT_RU_IDENTITYLINK to R_HURRICAN_READ_ONLY;
grant select on ACT_RU_VARIABLE to R_HURRICAN_READ_ONLY;
grant select on ACT_HI_PROCINST to R_HURRICAN_READ_ONLY;
grant select on ACT_HI_ACTINST to R_HURRICAN_READ_ONLY;
grant select on ACT_HI_TASKINST to R_HURRICAN_READ_ONLY;
grant select on ACT_HI_DETAIL to R_HURRICAN_READ_ONLY;
grant select on ACT_HI_COMMENT to R_HURRICAN_READ_ONLY;
grant select on ACT_HI_ATTACHMENT to R_HURRICAN_READ_ONLY;
grant select on ACT_ID_GROUP to R_HURRICAN_READ_ONLY;
grant select on ACT_ID_MEMBERSHIP to R_HURRICAN_READ_ONLY;
grant select on ACT_ID_USER to R_HURRICAN_READ_ONLY;
grant select on ACT_ID_INFO to R_HURRICAN_READ_ONLY;

grant select, insert, update, delete on ACT_GE_PROPERTY to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_GE_BYTEARRAY to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RE_DEPLOYMENT to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RU_EXECUTION to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RU_JOB to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RE_PROCDEF to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RU_TASK to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RU_IDENTITYLINK to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_RU_VARIABLE to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_HI_PROCINST to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_HI_ACTINST to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_HI_TASKINST to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_HI_DETAIL to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_HI_COMMENT to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_HI_ATTACHMENT to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_ID_GROUP to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_ID_MEMBERSHIP to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_ID_USER to R_HURRICAN_USER;
grant select, insert, update, delete on ACT_ID_INFO to R_HURRICAN_USER;
