
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL,
    PARENTPHYSIKTYP_ID, VERSION)
 Values
   (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 338, 120, NULL, '0',
    NULL, 0);

Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 1, 'EQ_IN', 'hwSchnittstelle',
    'PDH-IN', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 2, 'EQ_OUT', 'status',
    'frei', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 1, 'EQ_IN', 'status',
    'frei', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 2, 'EQ_OUT', 'rangSchnittstelle',
    'H', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 3, 'EQ_OUT', 'hwSchnittstelle',
    'PDH-OUT', 0, '0', '1');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 3, 'EQ_OUT', 'status',
    'frei', 0, '0', '1');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 4, 'EQ_IN', 'hwSchnittstelle',
    'SDH', 0, '0', '1');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 338, 4, 'EQ_IN', 'status',
    'frei', 0, '0', '1');

