DELETE FROM T_BA_ZUSATZ WHERE ID IN (
    SELECT Z2.ID FROM T_BA_ZUSATZ Z1
    JOIN T_BA_ZUSATZ Z2 ON Z1.ID <> Z2.ID AND Z2.USERW = 'schmidan'
        AND Z1.BA_VERL_CONFIG_ID = Z2.BA_VERL_CONFIG_ID AND Z1.HVT_GRUPPE_ID = Z2.HVT_GRUPPE_ID
        AND Z1.ABT_ID = Z2.ABT_ID AND Z1.GUELTIG_BIS = Z2.GUELTIG_BIS
);