-- FttX-Standorte
UPDATE T_HVT_STANDORT HVT SET HVT.AUTO_VERTEILEN = 1 WHERE STANDORT_TYP_REF_ID IN (11008, 11012);

-- nicht auto verteilen
UPDATE T_BA_VERL_CONFIG SET AUTO_VERTEILEN = 0 WHERE PROD_ID IN (511,512,513);
