apiVersion: apps/v1
kind: Deployment
metadata:
  name: adlatus-gui-deployment
  namespace: adl
spec:
  template:
    spec:
      containers:
        - name: adlatus-gui
          ports:
            - $patch: replace
            - containerPort: 80
              hostPort: 8081
      imagePullSecrets:
        - name: docker-regcred
