globalProperties:
  apis: ""
  supportingFiles: ""
  models: false

additionalProperties:
  modelsLibrary: de.bitconex.tmf.rcm.model
  basePackage: de.bitconex.tmf.rcm.client
  invokerPackage: de.bitconex.tmf.rcm.client
  apiPackage: de.bitconex.tmf.rcm.client.api
