INSERT INTO T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 VALUES
   (22313, 'GEOID_CLARIFICATION_TYPE', 'KVZ_ASSIGNMENT', NULL, NULL,
    NULL, '1', 30, NULL, 0);

INSERT INTO T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 VALUES
   (22314, 'GEOID_CLARIFICATION_TYPE', 'KVZ_DIFFERENT', NULL, NULL,
    NULL, '1', 30, NULL, 0);