Insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, UNIT_ID, GUI_VISIBLE, VERSION, DESCRIPTION)
 Values
   (11014, 'STANDORT_TYP', 'ABSTRACT', null, '1', 0, 'Standort-Typ fuer Dummy-Standorte (z.B. <M-net Netz>, <LeasedLine>, <Virtuell> etc.)');


Insert into T_HVT_GRUPPE
   (HVT_GRUPPE_ID, ONKZ, ORTSTEIL, NIEDERLASSUNG_ID, VERSION, EXPORT_4_PORTAL)
 Values
   (S_T_HVT_GRUPPE_0.nextVal, null, 'M-net Netz', 5, 0, '0');
Insert into T_HVT_GRUPPE
   (HVT_GRUPPE_ID, ONKZ, ORTSTEIL, NIEDERLASSUNG_ID, VERSION, EXPORT_4_PORTAL)
 Values
   (S_T_HVT_GRUPPE_0.nextVal, null, 'LeasedLine', 5, 0, '0');
Insert into T_HVT_GRUPPE
   (HVT_GRUPPE_ID, ONKZ, ORTSTEIL, NIEDERLASSUNG_ID, VERSION, EXPORT_4_PORTAL)
 Values
   (S_T_HVT_GRUPPE_0.nextVal, null, 'Virtuell', 5, 0, '0');


Insert into T_HVT_STANDORT
   (HVT_ID_STANDORT, HVT_GRUPPE_ID, STANDORT_TYP_REF_ID, HOCHGERECHNETER_TERMIN, GESICHERTE_REALISIERUNG, GUELTIG_VON, GUELTIG_BIS,
   CARRIER_ID, CPS_PROVISIONING, BREAK_RANG, VERSION, AUTO_VERTEILEN)
 Values
   (S_T_HVT_STANDORT_0.nextVal, (select HVT_GRUPPE_ID from T_HVT_GRUPPE hg where hg.ORTSTEIL='M-net Netz'), 11014, 'in Betrieb', 'in Betrieb',
    TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    null, '0', '0', 0, '1');
Insert into T_HVT_STANDORT
   (HVT_ID_STANDORT, HVT_GRUPPE_ID, STANDORT_TYP_REF_ID, HOCHGERECHNETER_TERMIN, GESICHERTE_REALISIERUNG, GUELTIG_VON, GUELTIG_BIS,
   CARRIER_ID, CPS_PROVISIONING, BREAK_RANG, VERSION, AUTO_VERTEILEN)
 Values
   (S_T_HVT_STANDORT_0.nextVal, (select HVT_GRUPPE_ID from T_HVT_GRUPPE hg where hg.ORTSTEIL='LeasedLine'), 11014, 'in Betrieb', 'in Betrieb',
    TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    null, '0', '0', 0, '1');
Insert into T_HVT_STANDORT
   (HVT_ID_STANDORT, HVT_GRUPPE_ID, STANDORT_TYP_REF_ID, HOCHGERECHNETER_TERMIN, GESICHERTE_REALISIERUNG, GUELTIG_VON, GUELTIG_BIS,
   CARRIER_ID, CPS_PROVISIONING, BREAK_RANG, VERSION, AUTO_VERTEILEN)
 Values
   (S_T_HVT_STANDORT_0.nextVal, (select HVT_GRUPPE_ID from T_HVT_GRUPPE hg where hg.ORTSTEIL='Virtuell'), 11014, 'in Betrieb', 'in Betrieb',
    TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    null, '0', '0', 0, '1');


