
Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, ANSCHLUSSART, PROD_NAME_PATTERN, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
   BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
   BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP,
   ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
   CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
   VERTEILUNG_DURCH, BA_RUECKLAEUFER, VERLAUF_CHAIN_ID,
   VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
   CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
   TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, VIER_DRAHT, VERSION, MIN_DN_COUNT, CPS_IP_DEFAULT, CPS_MULTI_DRAHT)
 Values
   (541, 21, 'Glasfaser SDSL', 'Glasfaser SDSL {DOWNSTREAM}',
    1, 0, null, null,
    '0', TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1',
    '0', '1', '0', 1,
    'X9', 1, '1', '0', '0',
    '0', '0', '0', '1', '1',
    4, '0', 45,
    15, '1', '0', '0', '1',
    'GlasfaserSDSL', '1', '1', 'SDSL', '1',
    'W', 'V', '0', 0, 0, '1', '0');

-- techn. Lst 5000 kbit/s Downstream
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_LEISTUNG__NO, TYP, LONG_VALUE, STR_VALUE, PROD_NAME_STR, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (51, '5000 kbit/s', 10051, 'DOWNSTREAM',
    5000, '5000', '5000',
    '0', '0', '0', '1', '0',
    '1', TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);
-- techn. Lst 25000 kbit/s Upstream
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_LEISTUNG__NO, TYP, LONG_VALUE, STR_VALUE, PROD_NAME_STR, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (52, '25000 kbit/s', 10052, 'UPSTREAM',
    25000, '25000', '25000',
    '0', '0', '0', '1', '0',
    '1', TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);
-- techn. Lst 50000 kbit/s Upstream
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_LEISTUNG__NO, TYP, LONG_VALUE, STR_VALUE, PROD_NAME_STR, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (53, '50000 kbit/s', 10053, 'UPSTREAM',
    50000, '50000', '50000',
    '0', '0', '0', '1', '0',
    '1', TO_DATE('02/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);


-- DSLAM Profile anlegen
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_50000_50000_H', '50000', '50000', '0', 24, 24, '1', 0, '0', null);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_50000_50000_H', '50000', '50000', '0', 24, 24, '1', 0, '0', 37);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_50000_50000_H', '50000', '50000', '0', 24, 24, '1', 0, '0', 151);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_50000_50000_H', '50000', '50000', '0', 24, 24, '1', 0, '0', 172);

Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_25000_25000_H', '25000', '25000', '0', 23, 23, '1', 0, '0', null);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_25000_25000_H', '25000', '25000', '0', 23, 23, '1', 0, '0', 37);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_25000_25000_H', '25000', '25000', '0', 23, 23, '1', 0, '0', 151);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_25000_25000_H', '25000', '25000', '0', 23, 23, '1', 0, '0', 172);

Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_10000_10000_H', '10000', '10000', '0', 33, 33, '1', 0, '0', null);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_10000_10000_H', '10000', '10000', '0', 33, 33, '1', 0, '0', 37);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_10000_10000_H', '10000', '10000', '0', 33, 33, '1', 0, '0', 151);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_10000_10000_H', '10000', '10000', '0', 33, 33, '1', 0, '0', 172);

Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_5000_5000_H', '5000', '5000', '0', 51, 51, '1', 0, '0', null);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_5000_5000_H', '5000', '5000', '0', 51, 51, '1', 0, '0', 37);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_5000_5000_H', '5000', '5000', '0', 51, 51, '1', 0, '0', 151);
Insert into T_DSLAM_PROFILE
 (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP)
 Values (S_T_DSLAM_PROFILE_0.nextVal, 'MD_5000_5000_H', '5000', '5000', '0', 51, 51, '1', 0, '0', 172);


-- DSLAM Profile zuordnen
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
 Values (541, (select d.id from T_DSLAM_PROFILE d where d.NAME='MD_5000_5000_H' and d.BAUGRUPPEN_TYP is null));
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
 Values (541, (select d.id from T_DSLAM_PROFILE d where d.NAME='MD_10000_10000_H' and d.BAUGRUPPEN_TYP is null));
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
 Values (541, (select d.id from T_DSLAM_PROFILE d where d.NAME='MD_25000_25000_H' and d.BAUGRUPPEN_TYP is null));
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
 Values (541, (select d.id from T_DSLAM_PROFILE d where d.NAME='MD_50000_50000_H' and d.BAUGRUPPEN_TYP is null));


-- Produktaenderungen konfigurieren
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 Values (S_T_PROD_2_PROD_0.nextVal, 513, 541, 5000, 1, 0);
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 Values (S_T_PROD_2_PROD_0.nextVal, 512, 541, 5000, 1, 0);
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 Values (S_T_PROD_2_PROD_0.nextVal, 540, 541, 5000, 1, 0);
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 Values (S_T_PROD_2_PROD_0.nextVal, 541, 512, 5000, 1, 0);
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 Values (S_T_PROD_2_PROD_0.nextVal, 541, 513, 5000, 1, 0);
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 Values (S_T_PROD_2_PROD_0.nextVal, 541, 540, 5000, 1, 0);


-- techn. Leistungen dem Produkt zuordnen
-- 5000 Down / 5000 Up
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 51, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 27, 51, '1', 0);
-- 10000 Down / 10000 Up
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 33, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 28, 33, '1', 0);
-- 25000 Down / 25000 Up
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 23, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 52, 23, '1', 0);
-- 50000 Down / 50000 Up
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 24, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 53, 24, '1', 0);
-- feste IP
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 6, '1', 0);
-- QoS
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 50, '0', 0);

-- Equipment-Konfig definieren
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, VERSION)
 Values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 541, 1, 'EQ_OUT', 'carrier', 'MNET', 0);
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, VERSION)
 Values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 541, 1, 'EQ_OUT', 'rangSSType', 'FttB', 0);

-- Physikzuordnung
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, VIRTUELL, VERSION)
 Values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 541, 800, '0', 0);
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, VIRTUELL, VERSION)
 Values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 541, 803, '0', 0);
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, VIRTUELL, VERSION)
 Values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 541, 804, '0', 0);

-- Standorttypen definieren
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
 Values (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 541, 11011, 1, 'IMPORT', SYSDATE, 0);
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
 Values (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 541, 11002, 2, 'IMPORT', SYSDATE, 0);
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
 Values (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 541, 11013, 3, 'IMPORT', SYSDATE, 0);

-- Produktmapping
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values (1044, 541, 541, 'sdsl', 0);

-- BA Anlaesse konfigurieren
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) Values (541, 1);
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) Values (541, 2);


-- BA Konfiguration
Insert into T_BA_VERL_CONFIG
   (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 Values
   (S_T_BA_VERL_CONFIG_0.nextVal, 541, 27, 18, SYSDATE,
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), SYSDATE, 'Import', 0, '1', '1');
Insert into T_BA_VERL_CONFIG
   (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 Values
   (S_T_BA_VERL_CONFIG_0.nextVal, 541, 13, 18, SYSDATE,
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), SYSDATE, 'Import', 0, '1', '1');

-- Schnittstelle definieren
Insert into T_PRODUKT_2_SCHNITTSTELLE (PROD_ID, SCHNITTSTELLE_ID) Values (541, 38);

-- Sperren
Insert into T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID) Values (541, 2);

-- CPS-Chains
Insert into T_SERVICE_CHAIN (ID, NAME, TYPE, DESCRIPTION, VERSION)
 Values (58, 'CPS - FttX SDSL', 'CPS_DATA', 'Chain-Definition, um Daten fuer SDSL FttX-Produkte zu ermitteln.', 0);

Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5001, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 10, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5003, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 30, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5004, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 40, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5005, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 50, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5006, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 60, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5002, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 70, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5013, 58, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 80, 0);

-- CPS
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 541, 14000, 58, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 541, 14001, 58, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 541, 14002, 54, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 541, 14006, 58, 0);

-- EG Konfig
Insert into T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION)
 Values (S_T_PROD_2_EG_0.nextVal, 541, 5, '1', '1', 0);

