-- Neue technische Leistung anlegen
insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP, 
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION, 
    DISPO, EWSD, SDH, IPS, SCT, 
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (56, 'dynamische IPv4', NULL, NULL, 'ONL_IP_OPTION', 
    NULL, NULL, NULL, ' ', NULL, 
    '0', '0', '0', '0', '0', 
    NULL, '1', TO_DATE('01/11/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP, 
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION, 
    DISPO, EWSD, SDH, IPS, SCT, 
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (57, 'dynamische IPv6', NULL, NULL, 'ONL_IP_OPTION', 
    NULL, NULL, NULL, ' ', NULL, 
    '0', '0', '0', '0', '0', 
    NULL, '1', TO_DATE('01/11/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);
