/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import java.time.OffsetDateTime;
    import com.fasterxml.jackson.annotation.*;

        /**
* Base event with common attributes.
*/
    @JsonPropertyOrder({
        BaseEventAllOf.JSON_PROPERTY_EVENT,
        BaseEventAllOf.JSON_PROPERTY_EVENT_ID,
        BaseEventAllOf.JSON_PROPERTY_EVENT_TIME,
        BaseEventAllOf.JSON_PROPERTY_EVENT_TYPE,
        BaseEventAllOf.JSON_PROPERTY_CORRELATION_ID,
        BaseEventAllOf.JSON_PROPERTY_DOMAIN,
        BaseEventAllOf.JSON_PROPERTY_TITLE,
        BaseEventAllOf.JSON_PROPERTY_DESCRIPTION,
        BaseEventAllOf.JSON_PROPERTY_PRIORITY,
        BaseEventAllOf.JSON_PROPERTY_TIME_OCURRED
    })
            @JsonTypeName("BaseEvent_allOf")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class BaseEventAllOf {
        public static final String JSON_PROPERTY_EVENT = "event";
            private Object event;

        public static final String JSON_PROPERTY_EVENT_ID = "eventId";
            private String eventId;

        public static final String JSON_PROPERTY_EVENT_TIME = "eventTime";
            private OffsetDateTime eventTime;

        public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
            private String eventType;

        public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
            private String correlationId;

        public static final String JSON_PROPERTY_DOMAIN = "domain";
            private String domain;

        public static final String JSON_PROPERTY_TITLE = "title";
            private String title;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_PRIORITY = "priority";
            private String priority;

        public static final String JSON_PROPERTY_TIME_OCURRED = "timeOcurred";
            private OffsetDateTime timeOcurred;



}

