/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.rcm.model.TimePeriod;
    import com.fasterxml.jackson.annotation.*;

        /**
* specification of a value (number or text or an object) that can be assigned to a Characteristic. This is an abstract base class, the actual value is in one of the strongly-typed subclasses
*/
    @JsonPropertyOrder({
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_VALUE_TYPE,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_IS_DEFAULT,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_UNIT_OF_MEASURE,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_VALID_FOR,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_VALUE_FROM,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_VALUE_TO,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_RANGE_INTERVAL,
        CharacteristicValueSpecificationAllOf.JSON_PROPERTY_REGEX
    })
            @JsonTypeName("CharacteristicValueSpecification_allOf")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class CharacteristicValueSpecificationAllOf {
        public static final String JSON_PROPERTY_VALUE_TYPE = "valueType";
            private String valueType;

        public static final String JSON_PROPERTY_IS_DEFAULT = "isDefault";
            private Boolean isDefault;

        public static final String JSON_PROPERTY_UNIT_OF_MEASURE = "unitOfMeasure";
            private String unitOfMeasure;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_VALUE_FROM = "valueFrom";
            private Integer valueFrom;

        public static final String JSON_PROPERTY_VALUE_TO = "valueTo";
            private Integer valueTo;

        public static final String JSON_PROPERTY_RANGE_INTERVAL = "rangeInterval";
            private String rangeInterval;

        public static final String JSON_PROPERTY_REGEX = "regex";
            private String regex;



}

