/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonSubTypes;
    import com.fasterxml.jackson.annotation.JsonTypeInfo;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.rcm.model.TimePeriod;
    import java.net.URI;
    import com.fasterxml.jackson.annotation.*;

        /**
* FeatureSpecificationRelationshipFVO
*/
    @JsonPropertyOrder({
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_AT_TYPE,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_AT_BASE_TYPE,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_RELATIONSHIP_TYPE,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_FEATURE_ID,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_PARENT_SPECIFICATION_ID,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_PARENT_SPECIFICATION_HREF,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_NAME,
        FeatureSpecificationRelationshipFVO.JSON_PROPERTY_VALID_FOR
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)

public class FeatureSpecificationRelationshipFVO {
        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            protected String atType;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private String atSchemaLocation;

              /**
   * This is the type of the feature specification relationship.
   */
  public enum RelationshipTypeEnum {
    EXCLUDED("excluded"),
    
    INCLUDES("includes"),
    
    MAY_INCLUDE("may include"),
    
    REQUIRES("requires");

    private String value;

    RelationshipTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RelationshipTypeEnum fromValue(String value) {
      for (RelationshipTypeEnum b : RelationshipTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

        public static final String JSON_PROPERTY_RELATIONSHIP_TYPE = "relationshipType";
            private RelationshipTypeEnum relationshipType;

        public static final String JSON_PROPERTY_FEATURE_ID = "featureId";
            private String featureId;

        public static final String JSON_PROPERTY_PARENT_SPECIFICATION_ID = "parentSpecificationId";
            private String parentSpecificationId;

        public static final String JSON_PROPERTY_PARENT_SPECIFICATION_HREF = "parentSpecificationHref";
            private URI parentSpecificationHref;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;



}

