/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.rcm.model.JobStateType;
    import java.net.URI;
    import java.time.OffsetDateTime;
    import com.fasterxml.jackson.annotation.*;

        /**
* Represents a task used to import resources from a file
*/
    @JsonPropertyOrder({
        ImportJobFVOAllOf.JSON_PROPERTY_COMPLETION_DATE,
        ImportJobFVOAllOf.JSON_PROPERTY_CONTENT_TYPE,
        ImportJobFVOAllOf.JSON_PROPERTY_CREATION_DATE,
        ImportJobFVOAllOf.JSON_PROPERTY_ERROR_LOG,
        ImportJobFVOAllOf.JSON_PROPERTY_PATH,
        ImportJobFVOAllOf.JSON_PROPERTY_STATUS,
        ImportJobFVOAllOf.JSON_PROPERTY_URL,
        ImportJobFVOAllOf.JSON_PROPERTY_ID
    })
            @JsonTypeName("ImportJob_FVO_allOf")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class ImportJobFVOAllOf {
        public static final String JSON_PROPERTY_COMPLETION_DATE = "completionDate";
            private OffsetDateTime completionDate;

        public static final String JSON_PROPERTY_CONTENT_TYPE = "contentType";
            private String contentType;

        public static final String JSON_PROPERTY_CREATION_DATE = "creationDate";
            private OffsetDateTime creationDate;

        public static final String JSON_PROPERTY_ERROR_LOG = "errorLog";
            private String errorLog;

        public static final String JSON_PROPERTY_PATH = "path";
            private String path;

        public static final String JSON_PROPERTY_STATUS = "status";
            private JobStateType status;

        public static final String JSON_PROPERTY_URL = "url";
            private URI url;

        public static final String JSON_PROPERTY_ID = "id";
            private String id;



}

