/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonSubTypes;
    import com.fasterxml.jackson.annotation.JsonTypeInfo;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.rcm.model.AttachmentRefOrValue;
    import de.bitconex.tmf.rcm.model.CharacteristicSpecification;
    import de.bitconex.tmf.rcm.model.ExternalIdentifier;
    import de.bitconex.tmf.rcm.model.FeatureSpecification;
    import de.bitconex.tmf.rcm.model.IntentSpecificationRef;
    import de.bitconex.tmf.rcm.model.RelatedPartyRefOrPartyRoleRef;
    import de.bitconex.tmf.rcm.model.ResourceSpecification;
    import de.bitconex.tmf.rcm.model.ResourceSpecificationRelationship;
    import de.bitconex.tmf.rcm.model.TargetResourceSchema;
    import de.bitconex.tmf.rcm.model.TimePeriod;
    import java.time.OffsetDateTime;
    import java.util.ArrayList;
    import java.util.List;
    import com.fasterxml.jackson.annotation.*;

        /**
* PhysicalResourceSpecification
*/
    @JsonPropertyOrder({
        PhysicalResourceSpecification.JSON_PROPERTY_MODEL,
        PhysicalResourceSpecification.JSON_PROPERTY_PART,
        PhysicalResourceSpecification.JSON_PROPERTY_SKU,
        PhysicalResourceSpecification.JSON_PROPERTY_VENDOR
    })
@lombok.Data
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)

public class PhysicalResourceSpecification extends ResourceSpecification {
        public static final String JSON_PROPERTY_MODEL = "model";
            private String model;

        public static final String JSON_PROPERTY_PART = "part";
            private String part;

        public static final String JSON_PROPERTY_SKU = "sku";
            private String sku;

        public static final String JSON_PROPERTY_VENDOR = "vendor";
            private String vendor;



}

