/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import com.fasterxml.jackson.annotation.*;

        /**
* This is a derived class of ResourceSpecification, and is used to define the invariant characteristics and behavior (attributes, methods, constraints, and relationships) of a PhysicalResource.
*/
    @JsonPropertyOrder({
        PhysicalResourceSpecificationAllOf.JSON_PROPERTY_MODEL,
        PhysicalResourceSpecificationAllOf.JSON_PROPERTY_PART,
        PhysicalResourceSpecificationAllOf.JSON_PROPERTY_SKU,
        PhysicalResourceSpecificationAllOf.JSON_PROPERTY_VENDOR
    })
            @JsonTypeName("PhysicalResourceSpecification_allOf")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class PhysicalResourceSpecificationAllOf {
        public static final String JSON_PROPERTY_MODEL = "model";
            private String model;

        public static final String JSON_PROPERTY_PART = "part";
            private String part;

        public static final String JSON_PROPERTY_SKU = "sku";
            private String sku;

        public static final String JSON_PROPERTY_VENDOR = "vendor";
            private String vendor;



}

