/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.rcm.model.ConnectionSpecification;
    import de.bitconex.tmf.rcm.model.ResourceGraphSpecificationRelationship;
    import java.util.ArrayList;
    import java.util.List;
    import com.fasterxml.jackson.annotation.*;

        /**
* Resource graph specification.
*/
    @JsonPropertyOrder({
        ResourceGraphSpecificationAllOf.JSON_PROPERTY_NAME,
        ResourceGraphSpecificationAllOf.JSON_PROPERTY_DESCRIPTION,
        ResourceGraphSpecificationAllOf.JSON_PROPERTY_GRAPH_SPECIFICATION_RELATIONSHIP,
        ResourceGraphSpecificationAllOf.JSON_PROPERTY_CONNECTION_SPECIFICATION
    })
            @JsonTypeName("ResourceGraphSpecification_allOf")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class ResourceGraphSpecificationAllOf {
        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_GRAPH_SPECIFICATION_RELATIONSHIP = "graphSpecificationRelationship";
            private List<ResourceGraphSpecificationRelationship> graphSpecificationRelationship;

        public static final String JSON_PROPERTY_CONNECTION_SPECIFICATION = "connectionSpecification";
            private List<ConnectionSpecification> connectionSpecification;



}

