/*
 * Resource Catalog Management
 * ### February 2023 Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.  ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonSubTypes;
    import com.fasterxml.jackson.annotation.JsonTypeInfo;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.rcm.model.ExternalIdentifierMVO;
    import de.bitconex.tmf.rcm.model.ResourceCategoryRefMVO;
    import de.bitconex.tmf.rcm.model.ResourceSpecificationRefMVO;
    import de.bitconex.tmf.rcm.model.TimePeriod;
    import java.time.OffsetDateTime;
    import java.util.ArrayList;
    import java.util.List;
    import com.fasterxml.jackson.annotation.*;

        /**
* ResourceCandidateMVO
*/
    @JsonPropertyOrder({
        ResourceCandidateMVO.JSON_PROPERTY_AT_TYPE,
        ResourceCandidateMVO.JSON_PROPERTY_AT_BASE_TYPE,
        ResourceCandidateMVO.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        ResourceCandidateMVO.JSON_PROPERTY_DESCRIPTION,
        ResourceCandidateMVO.JSON_PROPERTY_VERSION,
        ResourceCandidateMVO.JSON_PROPERTY_VALID_FOR,
        ResourceCandidateMVO.JSON_PROPERTY_LAST_UPDATE,
        ResourceCandidateMVO.JSON_PROPERTY_LIFECYCLE_STATUS,
        ResourceCandidateMVO.JSON_PROPERTY_CATEGORY,
        ResourceCandidateMVO.JSON_PROPERTY_RESOURCE_SPECIFICATION,
        ResourceCandidateMVO.JSON_PROPERTY_EXTERNAL_IDENTIFIER
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)

public class ResourceCandidateMVO {
        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            protected String atType;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private String atSchemaLocation;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_VERSION = "version";
            private String version;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
            private OffsetDateTime lastUpdate;

        public static final String JSON_PROPERTY_LIFECYCLE_STATUS = "lifecycleStatus";
            private String lifecycleStatus;

        public static final String JSON_PROPERTY_CATEGORY = "category";
            private List<ResourceCategoryRefMVO> category;

        public static final String JSON_PROPERTY_RESOURCE_SPECIFICATION = "resourceSpecification";
            private ResourceSpecificationRefMVO resourceSpecification;

        public static final String JSON_PROPERTY_EXTERNAL_IDENTIFIER = "externalIdentifier";
            private List<ExternalIdentifierMVO> externalIdentifier;



}

