CREATE TABLE T_WBCI_VORABSTIMMUNG_FAX (
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  AUFTRAG_ID NUMBER(19) NOT NULL,
  VORABSTIMMUNG_ID VARCHAR(50) NOT NULL,
  CREATED DATE NOT NULL,
  VERSION NUMBER(19) DEFAULT 0 NOT NULL);

CREATE SEQUENCE S_T_WBCI_VORABSTIMMUNG_FAX START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE CACHE 20;

GRANT SELECT, INSERT, UPDATE ON T_WBCI_VORABSTIMMUNG_FAX TO R_HURRICAN_USER;
GRANT SELECT ON T_WBCI_VORABSTIMMUNG_FAX TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON S_T_WBCI_VORABSTIMMUNG_FAX TO PUBLIC;