CREATE TABLE T_CAL_TRANSACTION_LOG (
  TRANSACTION_ID     VARCHAR2(255) NOT NULL,
  REFERENCE_ID  VARCHAR2(255)     NOT NULL,
  REFERENCE_TYPE   VARCHAR2(255) NOT NULL,
  ACTION   VARCHAR2(255) NOT NULL,
  CREATED      TIMESTAMP     NOT NULL,
  CONSTRAINT T_CAL_TRANSACTION_LOG_PK primary key (TRANSACTION_ID, ACTION)
);

ALTER TABLE T_CAL_TRANSACTION_LOG
  ADD CONSTRAINT T_CAL_TRANSACTION_LOG_ACTION CHECK (ACTION IN ('PORT_RESERVE', 'PORT_RELEASE'));

ALTER TABLE T_CAL_TRANSACTION_LOG
  ADD CONSTRAINT T_CAL_TRANSACTION_LOG_REF_TYPE CHECK (REFERENCE_TYPE IN ('T_EQUIPMENT'));


COMMENT ON COLUMN T_CAL_TRANSACTION_LOG.TRANSACTION_ID IS 'TransaktionsID von Callisto, zu welcher die Aenderungen gehoeren. I.d.R. die OrderID von TOMS';
COMMENT ON COLUMN T_CAL_TRANSACTION_LOG.REFERENCE_ID IS 'Referenz auf den geaenderten Datensatz in der Hurrican Datenbank';
COMMENT ON COLUMN T_CAL_TRANSACTION_LOG.REFERENCE_TYPE IS 'Der Name der Tabelle, in welcher die REFERENCE_ID der Primary Key ist.';
COMMENT ON COLUMN T_CAL_TRANSACTION_LOG.ACTION IS 'Aktion, die in dieser Transaktion durchgefuehrt wurde.';