--
-- CAL-348: HurricanDB: Neue Spalte T_DSLAM_PROFILE.LINE_SPECTRUM mit Daten ergänzen
--    Download < 100Mbit und Upload < 50Mbit dann '17a'  sonst '30a'
-- Nur für MDU, DPU und DPO (VDSL Devices)
--
-- Kontrollqueries:
-- Alle:
-- SELECT bgt.HW_TYPE_NAME, p.NAME, p.UPSTREAM, p.DOWNSTREAM, p.LINE_SPECTRUM FROM T_HW_BAUGRUPPEN_TYP bgt
-- INNER JOIN T_DSLAM_PROFILE p ON bgt.ID = p.BAUGRUPPEN_TYP and bgt.HW_TYPE_NAME in ('MDU', 'DPO', 'DPU')
-- 30a:
-- SELECT bgt.HW_TYPE_NAME, p.NAME, p.UPSTREAM, p.DOWNSTREAM, p.LINE_SPECTRUM FROM T_HW_BAUGRUPPEN_TYP bgt
-- INNER JOIN T_DSLAM_PROFILE p ON bgt.ID = p.BAUGRUPPEN_TYP and bgt.HW_TYPE_NAME in ('MDU', 'DPO', 'DPU')
-- WHERE p.UPSTREAM >=50000 OR p.DOWNSTREAM >=100000;
-- 17a:
-- SELECT bgt.HW_TYPE_NAME, p.NAME, p.UPSTREAM, p.DOWNSTREAM, p.LINE_SPECTRUM FROM T_HW_BAUGRUPPEN_TYP bgt
-- INNER JOIN T_DSLAM_PROFILE p ON bgt.ID = p.BAUGRUPPEN_TYP and bgt.HW_TYPE_NAME in ('MDU', 'DPO', 'DPU')
-- WHERE p.UPSTREAM < 50000 AND p.DOWNSTREAM < 100000;


UPDATE T_DSLAM_PROFILE p set p.LINE_SPECTRUM='17a'
WHERE p.BAUGRUPPEN_TYP in (SELECT bgt.id FROM  T_HW_BAUGRUPPEN_TYP bgt
  WHERE bgt.HW_TYPE_NAME in ('MDU', 'DPO', 'DPU'))
  AND p.UPSTREAM <50000
  AND p.DOWNSTREAM <100000;

UPDATE T_DSLAM_PROFILE p set p.LINE_SPECTRUM='30a'
WHERE p.BAUGRUPPEN_TYP in (SELECT bgt.id FROM  T_HW_BAUGRUPPEN_TYP bgt
  WHERE bgt.HW_TYPE_NAME in ('MDU', 'DPO', 'DPU'))
  AND (p.UPSTREAM >=50000 OR p.DOWNSTREAM >=100000);
