delete from T_WBCI_GESCHAEFTSFALL_ANSCHL where GESCHAEFTSFALL_ID in (select ID from T_WBCI_GESCHAEFTSFALL where VORABSTIMMUNGSID = 'testVaId-123');
delete from T_WBCI_GESCHAEFTSFALL where VORABSTIMMUNGSID = 'testVaId-123';
