globalProperties:
  models: ""
  supportingFiles: false
  apis: false

additionalProperties:
  library: webclient
  basePackage: de.bitconex.tmf.rim
  invokerPackage: de.bitconex.tmf.rim
  modelPackage: de.bitconex.tmf.rim.model
  useLombok: true
  useSerializable: true
