/*
 * Appointment
 * ## TMF API Reference : TMF 646 - Appointment  An Appointment is an arrangement to do something or meet someone at a particular time and place. It is previously made during an interaction or may be necessary to solve a customer problem or to deliver a product order item. The appointment API goal is to manage an appointment with all the necessary characteristics. First, the API consists in searching free time slots based on given parameters.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.appointment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
    import com.fasterxml.jackson.annotation.*;
import java.io.Serializable;

        /**
* The notification data structure
*/
    @JsonPropertyOrder({
        AppointmentStateChangeEvent.JSON_PROPERTY_ID,
        AppointmentStateChangeEvent.JSON_PROPERTY_HREF,
        AppointmentStateChangeEvent.JSON_PROPERTY_EVENT_ID,
        AppointmentStateChangeEvent.JSON_PROPERTY_EVENT_TIME,
        AppointmentStateChangeEvent.JSON_PROPERTY_EVENT_TYPE,
        AppointmentStateChangeEvent.JSON_PROPERTY_CORRELATION_ID,
        AppointmentStateChangeEvent.JSON_PROPERTY_DOMAIN,
        AppointmentStateChangeEvent.JSON_PROPERTY_TITLE,
        AppointmentStateChangeEvent.JSON_PROPERTY_DESCRIPTION,
        AppointmentStateChangeEvent.JSON_PROPERTY_PRIORITY,
        AppointmentStateChangeEvent.JSON_PROPERTY_TIME_OCURRED,
        AppointmentStateChangeEvent.JSON_PROPERTY_EVENT
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class AppointmentStateChangeEvent implements Serializable {
        public static final String JSON_PROPERTY_ID = "id";
            private String id;

        public static final String JSON_PROPERTY_HREF = "href";
            private String href;

        public static final String JSON_PROPERTY_EVENT_ID = "eventId";
            private String eventId;

        public static final String JSON_PROPERTY_EVENT_TIME = "eventTime";
            private OffsetDateTime eventTime;

        public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
            private String eventType;

        public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
            private String correlationId;

        public static final String JSON_PROPERTY_DOMAIN = "domain";
            private String domain;

        public static final String JSON_PROPERTY_TITLE = "title";
            private String title;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_PRIORITY = "priority";
            private String priority;

        public static final String JSON_PROPERTY_TIME_OCURRED = "timeOcurred";
            private OffsetDateTime timeOcurred;

        public static final String JSON_PROPERTY_EVENT = "event";
            private AppointmentStateChangeEventPayload event;



}

