/*
 * API Resource Inventory Management
 * ## TMF API Reference: TMF639 - Resource Inventory   ### Release : 19.5 - December 2019  Resource Inventory  API goal is to provide the ability to manage Resources.  ### Operations Resource Inventory API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rim.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.net.URI;

        /**
* Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)
*/
    @JsonPropertyOrder({
        Error.JSON_PROPERTY_CODE,
        Error.JSON_PROPERTY_REASON,
        Error.JSON_PROPERTY_MESSAGE,
        Error.JSON_PROPERTY_STATUS,
        Error.JSON_PROPERTY_REFERENCE_ERROR,
        Error.JSON_PROPERTY_AT_BASE_TYPE,
        Error.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        Error.JSON_PROPERTY_AT_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class Error implements Serializable {
        public static final String JSON_PROPERTY_CODE = "code";
            private String code;

        public static final String JSON_PROPERTY_REASON = "reason";
            private String reason;

        public static final String JSON_PROPERTY_MESSAGE = "message";
            private String message;

        public static final String JSON_PROPERTY_STATUS = "status";
            private String status;

        public static final String JSON_PROPERTY_REFERENCE_ERROR = "referenceError";
            private URI referenceError;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

