/*
 * API Resource Inventory Management
 * ## TMF API Reference: TMF639 - Resource Inventory   ### Release : 19.5 - December 2019  Resource Inventory  API goal is to provide the ability to manage Resources.  ### Operations Resource Inventory API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rim.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

        /**
* Configuration feature.
*/
    @JsonPropertyOrder({
        Feature.JSON_PROPERTY_ID,
        Feature.JSON_PROPERTY_IS_BUNDLE,
        Feature.JSON_PROPERTY_IS_ENABLED,
        Feature.JSON_PROPERTY_NAME,
        Feature.JSON_PROPERTY_CONSTRAINT,
        Feature.JSON_PROPERTY_FEATURE_CHARACTERISTIC,
        Feature.JSON_PROPERTY_FEATURE_RELATIONSHIP
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class Feature implements Serializable {
        public static final String JSON_PROPERTY_ID = "id";
            private String id;

        public static final String JSON_PROPERTY_IS_BUNDLE = "isBundle";
            private Boolean isBundle;

        public static final String JSON_PROPERTY_IS_ENABLED = "isEnabled";
            private Boolean isEnabled;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_CONSTRAINT = "constraint";
            private List<ConstraintRef> constraint;

        public static final String JSON_PROPERTY_FEATURE_CHARACTERISTIC = "featureCharacteristic";
            private List<Characteristic> featureCharacteristic = new ArrayList<>();

        public static final String JSON_PROPERTY_FEATURE_RELATIONSHIP = "featureRelationship";
            private List<FeatureRelationship> featureRelationship;



}

