
ALTER TABLE T_EG ADD USERW VARCHAR(25);
ALTER TABLE T_EG ADD EGTYPES NUMBER(10);
ALTER TABLE T_EG_TYPE ADD EGGRUPPEN NUMBER(10);

CREATE TABLE T_EG_2_EG_TYPE (
  EG_ID                NUMBER(10)                  NOT NULL,
  EG_TYPE_ID           NUMBER(10)                  NOT NULL
);

COMMENT ON TABLE T_EG_2_EG_TYPE IS 'Mapping T_EG zu T_EG_TYPES, many to many';

ALTER TABLE T_EG_2_EG_TYPE ADD CONSTRAINT PK_T_EG_2_T_EG_TYPE PRIMARY KEY (EG_ID, EG_TYPE_ID);

ALTER TABLE T_EG_2_EG_TYPE
  ADD CONSTRAINT FK_EG_2_EG_2_EG_TYPE
      FOREIGN KEY (EG_ID)
      REFERENCES T_EG (ID);

ALTER TABLE T_EG_2_EG_TYPE
  ADD CONSTRAINT FK_EG_TYPE_2_T_EG_2_EG_TYPE
      FOREIGN KEY (EG_TYPE_ID)
      REFERENCES T_EG_TYPE (ID);


-- DB-Grants ausfuehren
grant select, insert, update, delete on T_EG_2_EG_TYPE to R_HURRICAN_USER;
grant select on T_EG_2_EG_TYPE to R_HURRICAN_READ_ONLY;
commit;