-- Bisherige 'ngn.m-online.net' als einzige und fault SIP Domain auf Glasfaser Produkte konfigurieren
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DEFAULT_DOMAIN)
    VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 440, 22343, 22204, 'ITS HURRICAN', '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DEFAULT_DOMAIN)
    VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 511, 22343, 22204, 'ITS HURRICAN', '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DEFAULT_DOMAIN)
    VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 512, 22343, 22204, 'ITS HURRICAN', '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DEFAULT_DOMAIN)
    VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 513, 22343, 22204, 'ITS HURRICAN', '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DEFAULT_DOMAIN)
    VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 540, 22343, 22204, 'ITS HURRICAN', '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DEFAULT_DOMAIN)
    VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 541, 22343, 22204, 'ITS HURRICAN', '1');
