-- Update Script activiti 5.5 -> 5.6

ALTER TABLE ACT_RU_JOB MODIFY(EXCEPTION_MSG_ NVARCHAR2(2000));
ALTER TABLE ACT_RU_JOB MODIFY(HANDLER_CFG_ NVARCHAR2(2000));
ALTER TABLE ACT_RE_PROCDEF MODIFY(RESOURCE_NAME_ NVARCHAR2(2000));
ALTER TABLE ACT_RE_PROCDEF MODIFY(DGRM_RESOURCE_NAME_ VARCHAR(4000));
ALTER TABLE ACT_RU_TASK MODIFY(DESCRIPTION_ NVARCHAR2(2000));
ALTER TABLE ACT_RU_VARIABLE MODIFY(TEXT_ NVARCHAR2(2000));
ALTER TABLE ACT_RU_VARIABLE MODIFY(TEXT2_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_TASKINST MODIFY(DESCRIPTION_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_TASKINST MODIFY(DELETE_REASON_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_DETAIL MODIFY(TEXT_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_DETAIL MODIFY(TEXT2_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_COMMENT MODIFY(MESSAGE_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_ATTACHMENT MODIFY(DESCRIPTION_ NVARCHAR2(2000));
ALTER TABLE ACT_HI_ATTACHMENT MODIFY(URL_ NVARCHAR2(2000));

UPDATE   ACT_GE_PROPERTY P
   SET   P.REV_ = 2, P.VALUE_ = '5.6'
   where P.NAME_ = 'schema.version';

