--
-- Konfiguriert die Produkte fuer die Verbindungsbezeichnung
--

update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='C', TDN_KIND_OF_USE_TYPE='A' where PROD_ID in (322,340,5,318);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='C', TDN_KIND_OF_USE_TYPE='V' where PROD_ID in (511,501);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='C', TDN_KIND_OF_USE_TYPE='M' where PROD_ID in (336,323,2,38,319);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='C', TDN_KIND_OF_USE_TYPE='T' where PROD_ID in (1,337,37);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='C', TDN_KIND_OF_USE_TYPE='P' where PROD_ID in (338,3,4,443);

update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='W', TDN_KIND_OF_USE_TYPE='A' where PROD_ID in (400,410,411,420,421,430,431,440,55);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='W', TDN_KIND_OF_USE_TYPE='S' where PROD_ID in (60,61,62,63,64,65,66,67,99,312,313,51,52,53,54,11,12,16,17,18);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='W', TDN_KIND_OF_USE_TYPE='V' where PROD_ID in (512,513,502,503);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='W', TDN_KIND_OF_USE_TYPE='F' where PROD_ID in (455);

update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='F', TDN_KIND_OF_USE_TYPE='P' where PROD_ID in (6,7,8,19,20,21,22,23,24,25,26,45,46,47,48,39);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='F', TDN_KIND_OF_USE_TYPE='S' where PROD_ID in (42,43,44);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='F', TDN_KIND_OF_USE_TYPE='?' where PROD_ID in (450);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='F', TDN_KIND_OF_USE_TYPE='E' where PROD_ID in (451);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='F', TDN_KIND_OF_USE_TYPE='D' where PROD_ID in (453,454);

update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='V', TDN_KIND_OF_USE_TYPE='L' where PROD_ID in (300,301,302,303,304,305,314,441);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='V', TDN_KIND_OF_USE_TYPE='F' where PROD_ID in (442,444);
update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='V', TDN_KIND_OF_USE_TYPE='F' where PROD_ID in (452);

update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT='M', TDN_KIND_OF_USE_TYPE='K' where PROD_ID in (500);

update T_PRODUKT set TDN_KIND_OF_USE_PRODUCT=SUBSTR(LTGNR_VORS, 0, 1) where LTGNR_ANLEGEN='1' and TDN_KIND_OF_USE_PRODUCT is null;
update T_PRODUKT set TDN_KIND_OF_USE_TYPE=SUBSTR(LTGNR_VORS, 2, 1) where LTGNR_ANLEGEN='1' and TDN_KIND_OF_USE_TYPE is null;

