--
-- Reference-Values for KIND_OF_USE_xxx
--

delete from T_REFERENCE where ID in (18100, 18101, 18102, 18103, 18104, 18105, 18106, 18107, 18108, 18109);

insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18100, 'TDN_TYPE', 'A', '1', 10, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18102, 'TDN_TYPE', 'C', '1', 30, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18103, 'TDN_TYPE', 'D', '1', 40, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18104, 'TDN_TYPE', 'E', '1', 50, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18105, 'TDN_TYPE', 'F', '1', 60, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18108, 'TDN_TYPE', 'I', '1', 90, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18110, 'TDN_TYPE', 'K', '1', 110, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18111, 'TDN_TYPE', 'L', '1', 120, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18112, 'TDN_TYPE', 'M', '1', 130, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18115, 'TDN_TYPE', 'P', '1', 160, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18118, 'TDN_TYPE', 'S', '1', 190, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18119, 'TDN_TYPE', 'T', '1', 200, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18121, 'TDN_TYPE', 'V', '1', 220, '');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION)
  values (18122, 'TDN_TYPE', 'W', '1', 230, '');
