--
-- 4-Draht SDSL konfigurieren

insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 99, 9);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 99, 106);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 99, 107);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 99, 108);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 99, 509);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 99, 515);
