-- Produkt L2TP erhaelt als Physiktyp ATM u. L2TP

insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 300, 109);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 300, 110);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 301, 109);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 301, 110);

