

Insert into T_HW_BAUGRUPPEN_TYP
   (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE,
    HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID, VERSION)
 Values
   (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'O-0881V-P_RF', 8, 'RF-Ports der Alcatel MDU O-0881V-P', '1',
    'RF', 'MDU', 6, 0);

Insert into T_HW_BAUGRUPPEN_TYP
   (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE,
    HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID, VERSION)
 Values
   (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'MA5652G_RF', 8, 'RF-Ports der Huawei MDU MA5652G', '1',
    'RF', 'MDU', 2, 0);
