Insert into T_PHYSIKTYP
   (ID, NAME, BESCHREIBUNG, HVT_TECHNIK_ID, MAX_BANDWIDTH,
    HW_SCHNITTSTELLE, PT_GROUP, CPS_TRANSFER_METHOD, VERSION)
 Values
   (805, 'FTTB_RF', NULL, 3, NULL,
    NULL, 3, NULL, 0);
