ALTER TABLE T_EQUIPMENT ADD (UEVT_CLUSTER_NO NUMERIC(10));


UPDATE T_EQUIPMENT EQ
   SET EQ.UEVT_CLUSTER_NO =
          (SELECT U.UEVT_CLUSTER_NO
             FROM T_HVT_STANDORT HVT
                  LEFT OUTER JOIN T_UEVT U
                  ON U.HVT_ID_STANDORT = HVT.HVT_ID_STANDORT
            WHERE HVT.HVT_ID_STANDORT = EQ.HVT_ID_STANDORT
                  AND U.UEVT = EQ.RANG_VERTEILER)
 WHERE EQ.HVT_ID_STANDORT IS NOT NULL
       AND EQ.RANG_VERTEILER IS NOT NULL;


ALTER TABLE T_UEVT DROP COLUMN UEVT_CLUSTER_NO;
