CREATE TABLE T_CARRIERBESTELLUNG_ANLAGETYP
(
   ID                   NUMBER (19, 0) NOT NULL,
   TYP_NAME             VARCHAR2 (50) NOT NULL,
   VERSION              NUMBER (19, 0) DEFAULT 0 NOT NULL,
   PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_CARRIERBESTELLUNG_ANLAGETYP TO R_HURRICAN_USER;
GRANT SELECT ON T_CARRIERBESTELLUNG_ANLAGETYP TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_CARRIERBESTELLUNG_ATYP_0
   START WITH 1;

GRANT SELECT ON S_T_CARRIERBESTELLUNG_ATYP_0 TO PUBLIC;

CREATE TABLE T_CARRIERBESTELLUNG_ANLAGE
(
   ID                   NUMBER (19, 0) NOT NULL,
   VERSION              NUMBER (19, 0) DEFAULT 0 NOT NULL,
   DATEINAME            VARCHAR2 (255) NOT NULL,
   DATEITYP             VARCHAR2 (10) NOT NULL,
   BESCHREIBUNG         VARCHAR2 (160),
   INHALT               BLOB NOT NULL,
   ANLAGENTYP           NUMBER (19,0) NOT NULL,
   constraint           FK_CBA_2_ANLAGETYP
   foreign key          (ANLAGENTYP)
   references           T_CARRIERBESTELLUNG_ANLAGETYP (ID),
   CARRIERBESTELLUNG_ID NUMBER(19,0) NOT NULL,
   constraint           FK_CBA_2_CB
   foreign key          (CARRIERBESTELLUNG_ID)
   references           T_CARRIERBESTELLUNG (CB_ID),   
   PRIMARY KEY          (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_CARRIERBESTELLUNG_ANLAGE TO R_HURRICAN_USER;
GRANT SELECT ON T_CARRIERBESTELLUNG_ANLAGE TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_CARRIERBESTELLUNG_ANLAGE_0
   START WITH 1;

GRANT SELECT ON S_T_CARRIERBESTELLUNG_ANLAGE_0 TO PUBLIC;
                
