ALTER TABLE T_CB_VORGANG
 ADD (WITA_AUFTRAG_KLAMMER  NUMBER(10));

ALTER TABLE T_CB_VORGANG
 ADD (WITA_PROJEKT_KENNER  VARCHAR2(30));

ALTER TABLE T_CB_VORGANG
 ADD (WITA_KOPPLUNG_KENNER  VARCHAR2(30));

CREATE SEQUENCE S_T_CB_VORGANG_AUF_KLAMMER_0
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999
NOCACHE
NOCYCLE
NOORDER;

