CREATE TABLE T_MWF_AUFTRAGSKENNER
(
  ID                NUMBER(19)                  NOT NULL,
  VERSION           NUMBER(19)     DEFAULT 0    NOT NULL,
  AUFTRAG_KLAMMER   NUMBER(10)                  NOT NULL,
  ANZAHL_AUFTRAEGE  NUMBER(10)                  NOT NULL
);


ALTER TABLE T_MWF_AUFTRAGSKENNER ADD (
  CONSTRAINT T_MWF_AUFTRAGSKENNER_PK
  PRIMARY KEY
  (ID));

ALTER TABLE T_MWF_GESCHAEFTSFALL
 ADD (AUFTRAGSKENNER_ID  NUMBER(19));

ALTER TABLE T_MWF_GESCHAEFTSFALL ADD (
  FOREIGN KEY (AUFTRAGSKENNER_ID)
  REFERENCES T_MWF_AUFTRAGSKENNER (ID));

GRANT SELECT, INSERT, UPDATE ON T_MWF_AUFTRAGSKENNER to R_HURRICAN_USER;
GRANT SELECT ON T_MWF_AUFTRAGSKENNER to R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_MWF_AUFTRAGSKENNER_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


GRANT SELECT ON S_T_MWF_AUFTRAGSKENNER_0 TO PUBLIC;

