ALTER TABLE T_MWF_GESCHAEFTSFALL DROP COLUMN AUFTRAGSKENNER_ID;

ALTER TABLE T_MWF_REQUEST
 ADD (AUFTRAGSKENNER_ID  NUMBER(19));

ALTER TABLE T_MWF_REQUEST ADD CONSTRAINT FK_MWF_REQUEST_AKENNER
  FOREIGN KEY (AUFTRAGSKENNER_ID)
  REFERENCES T_MWF_AUFTRAGSKENNER (ID);