ALTER TABLE T_CB_VORGANG
 DROP COLUMN WITA_PROJEKT_KENNER;

ALTER TABLE T_CB_VORGANG
 DROP COLUMN WITA_KOPPLUNG_KENNER;

ALTER TABLE T_CARRIERBESTELLUNG
 ADD (PROJEKT_KENNER  VARCHAR2(30));

ALTER TABLE T_CARRIERBESTELLUNG
 ADD (KOPPLUNG_KENNER  VARCHAR2(30));

