CREATE TABLE T_MWF_MELDUNG_AUFTRAGSTYP
(
  ID                     NUMBER(19)             NOT NULL,
  VERSION                NUMBER(19) DEFAULT 0   NOT NULL,
  GESCHAEFTSFALLTYP      VARCHAR2(40)           NOT NULL,
  AENDERUNGSKENNZEICHEN  VARCHAR2(20)           NOT NULL,
  GESCHAEFTSFALLART      VARCHAR2(25)           NOT NULL,
  primary key (ID)
);

ALTER TABLE T_MWF_MELDUNG
 ADD (AUFTRAGSTYP_ID NUMBER(19));

ALTER TABLE T_MWF_MELDUNG ADD CONSTRAINT FK_MWF_MELDUNG_AUFTRAGSTYP
  FOREIGN KEY (AUFTRAGSTYP_ID)
  REFERENCES T_MWF_MELDUNG_AUFTRAGSTYP (ID);

GRANT SELECT, INSERT, UPDATE ON T_MWF_MELDUNG_AUFTRAGSTYP to R_HURRICAN_USER;
GRANT SELECT ON T_MWF_MELDUNG_AUFTRAGSTYP to R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_MWF_MELDUNG_AUFTRAGSTYP_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


GRANT SELECT ON S_T_MWF_MELDUNG_AUFTRAGSTYP_0 TO PUBLIC;
