alter table T_MWF_STANDORT_KUNDE add GEBAEUDETEILNAME VARCHAR2(25);
alter table T_MWF_STANDORT_KUNDE add GEBAEUDETEILZUSATZ VARCHAR2(25);

alter table T_ADDRESS add GEBAEUDETEILNAME VARCHAR2(25);
alter table T_ADDRESS add GEBAEUDETEILZUSATZ VARCHAR2(25);
