grant select, insert, update on  T_MWF_AUFNEHMENDER_PROVIDER to R_HURRICAN_USER;
grant select on  T_MWF_AUFNEHMENDER_PROVIDER to R_HURRICAN_READ_ONLY;

GRANT SELECT ON S_T_MWF_AUFNEHMENDER_PROVIDER TO PUBLIC;