CREATE TABLE T_MWF_PERSON
(
  ID               NUMBER(19)                   NOT NULL,
  VERSION          NUMBER(19)    DEFAULT 0      NOT NULL,
  ANREDE varchar2(10) NOT NULL,
  NACHNAME varchar2(30) NOT NULL,
  VORNAME varchar2(30),
  primary key (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_MWF_PERSON to R_HURRICAN_USER;
GRANT SELECT ON T_MWF_PERSON to R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_MWF_PERSON_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

GRANT SELECT ON S_T_MWF_PERSON_0 TO PUBLIC;

ALTER TABLE T_MWF_MELDUNG ADD (ENDKUNDE_ID NUMBER(19,0));

ALTER TABLE T_MWF_MELDUNG ADD CONSTRAINT FK_MWF_MELDUNG_ENDKUNDE
  FOREIGN KEY (ENDKUNDE_ID)
  REFERENCES T_MWF_PERSON (ID);
  