ALTER TABLE T_MWF_STANDORT_AI add (PERSON_ID NUMBER(19));
ALTER TABLE T_MWF_STANDORT_KUNDE add (PERSON_ID NUMBER(19));

ALTER TABLE T_MWF_STANDORT_AI ADD CONSTRAINT FK_MWF_STANDORTAI_PERSON
  FOREIGN KEY (PERSON_ID)
  REFERENCES T_MWF_PERSON (ID);
  
ALTER TABLE T_MWF_STANDORT_KUNDE ADD CONSTRAINT FK_MWF_STANDORTKUNDE_PERSON
  FOREIGN KEY (PERSON_ID)
  REFERENCES T_MWF_PERSON (ID);
  

ALTER TABLE T_MWF_STANDORT_AI drop column anrede;
ALTER TABLE T_MWF_STANDORT_AI drop column nachname;
ALTER TABLE T_MWF_STANDORT_AI drop column vorname;  
  
ALTER TABLE T_MWF_STANDORT_KUNDE drop column anrede;
ALTER TABLE T_MWF_STANDORT_KUNDE drop column nachname;
ALTER TABLE T_MWF_STANDORT_KUNDE drop column vorname;

  