DROP SEQUENCE S_T_MWF_PERSON_0;
CREATE SEQUENCE S_T_MWF_KUNDENNAME_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
GRANT SELECT ON S_T_MWF_KUNDENNAME_0 TO PUBLIC;

ALTER TABLE T_MWF_PERSON rename to T_MWF_KUNDENNAME;
ALTER TABLE T_MWF_KUNDENNAME add (KUNDENNAMETYP varchar2(10));
ALTER TABLE T_MWF_KUNDENNAME modify (NACHNAME varchar2(30) NULL);
ALTER TABLE T_MWF_KUNDENNAME add (ERSTERTEIL varchar2(30) NULL);
ALTER TABLE T_MWF_KUNDENNAME add (ZWEITERTEIL varchar2(30) NULL);

ALTER TABLE T_MWF_MONTAGELEISTUNG add (PERSONENNAME_ID decimal(19));
ALTER TABLE T_MWF_MONTAGELEISTUNG drop column ANREDE;
ALTER TABLE T_MWF_MONTAGELEISTUNG drop column NACHNAME;
ALTER TABLE T_MWF_MONTAGELEISTUNG drop column VORNAME;

ALTER TABLE T_MWF_MONTAGELEISTUNG ADD CONSTRAINT FK_MWF_MONTLSTG_KUNDENNAME
  FOREIGN KEY (PERSONENNAME_ID)
  REFERENCES T_MWF_KUNDENNAME (ID);
  
ALTER TABLE T_MWF_STANDORT_AI rename column PERSON_ID to KUNDENNAME_ID;
ALTER TABLE T_MWF_STANDORT_KUNDE rename column PERSON_ID to KUNDENNAME_ID;

ALTER TABLE T_MWF_STANDORT_AI rename CONSTRAINT FK_MWF_STANDORTAI_PERSON to FK_MWF_STANDORTAI_NAME;
ALTER TABLE T_MWF_STANDORT_KUNDE rename CONSTRAINT FK_MWF_STANDORTKUNDE_PERSON to FK_MWF_STANDORTKUNDE_NAME;