ALTER TABLE T_MWF_RUFNR_BLOCK_PORTIERUNG drop CONSTRAINT FK_MWF_RUFNR_PORTIERUNG;
ALTER TABLE T_MWF_MELDUNG DROP COLUMN RUFNUMMERNPORTIERUNG_ID;

drop table T_MWF_RUFNR_BLOCK_PORTIERUNG;
drop table T_MWF_MELDUNG_RUF_PORTIERUNG;
drop sequence S_T_MWF_MELDUNG_PORTIERUNG_0;
drop sequence S_T_MWF_RUFNR_BLK_PORT;