CREATE TABLE T_MWF_ABGEBENDERPROVIDER
(
  ID               NUMBER(19)                   NOT NULL,
  VERSION          NUMBER(19)    DEFAULT 0      NOT NULL,
  ABGABE_DATUM     DATE NOT NULL,
  ANTWORT_CODE     varchar2(40),
  ANTWORT_TEXT     varchar2(255),
  PROVIDER_NAME varchar2(60) NOT NULL,
  ZUSTIMMUNG_PROVIDER_WECHSEL varchar2(1) NOT NULL,
  primary key (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_MWF_ABGEBENDERPROVIDER to R_HURRICAN_USER;
GRANT SELECT ON T_MWF_ABGEBENDERPROVIDER to R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_MWF_ABGEBENDERPROVIDER_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

GRANT SELECT ON S_T_MWF_ABGEBENDERPROVIDER_0 TO PUBLIC;

ALTER TABLE T_MWF_MELDUNG ADD (ABGEBENDER_PROVIDER_ID NUMBER(19,0));

ALTER TABLE T_MWF_MELDUNG ADD CONSTRAINT FK_MWF_MELDUNG_ABGPROVIDER
  FOREIGN KEY (ABGEBENDER_PROVIDER_ID)
  REFERENCES T_MWF_ABGEBENDERPROVIDER (ID);
  