ALTER TABLE T_WBCI_GESCHAEFTSFALL
ADD CONSTRAINT CK_WBCIGF_TYP
CHECK (TYP IN (
    'VA_KUE_MRN',
    'VA_KUE_ORN',
    'VA_RRNP',
    'STR_AUF',
    'STR_AEN',
    'TVS_VA',
    'VA_UNBEKANNT'
  )) ENABLE NOVALIDATE;
