-- add new column STANDORT_ABWEICHEND_ID
ALTER TABLE T_WBCI_MELDUNG_POSITION ADD (STANDORT_ABWEICHEND_ID NUMBER(19,0));

ALTER TABLE T_WBCI_MELDUNG_POSITION ADD CONSTRAINT FK_STANDORT_ABWEICHEND_ID FOREIGN KEY (STANDORT_ABWEICHEND_ID) REFERENCES T_WBCI_STANDORT;