CREATE TABLE T_WBCI_LEITUNG (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), UEBERNAHME_MELDUNG_ID NUMBER(19, 0), PRIMARY KEY (id));
ALTER TABLE T_WBCI_MELDUNG ADD (UEBERNAHME NUMBER(1, 0), SICHERER_HAFEN NUMBER(1, 0), PORTIERUNGSKENNUNGPKIAUF VARCHAR2(255 CHAR));

ALTER TABLE T_WBCI_LEITUNG ADD CONSTRAINT FK_LEITUNG_UE_MELDUNG_ID FOREIGN KEY (UEBERNAHME_MELDUNG_ID) REFERENCES T_WBCI_MELDUNG;

GRANT SELECT, INSERT, UPDATE ON T_WBCI_LEITUNG TO R_HURRICAN_USER;
GRANT SELECT ON T_WBCI_LEITUNG TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_LEITUNG_0;
GRANT SELECT ON S_T_WBCI_LEITUNG_0 TO PUBLIC;
