--add IO_TYPE to Table T_WBCI_REQUEST
--normally the table should be empty .. but if not the IO_Type should be OUT
ALTER TABLE T_WBCI_REQUEST ADD IO_TYPE VARCHAR2(10 CHAR);
UPDATE T_WBCI_REQUEST set IO_TYPE='OUT' WHERE IO_TYPE is NULL;
ALTER TABLE T_WBCI_REQUEST MODIFY IO_TYPE NOT NULL;

--add column IO_TYPE to WBCI_Meldung
ALTER TABLE T_WBCI_MELDUNG ADD IO_TYPE VARCHAR2(10 CHAR);
UPDATE T_WBCI_MELDUNG set IO_TYPE='IN' WHERE IO_TYPE is NULL;
ALTER TABLE T_WBCI_MELDUNG MODIFY IO_TYPE NOT NULL;

--rename column meldung_type
ALTER TABLE T_WBCI_MELDUNG RENAME COLUMN MELDUNG_TYP TO TYP;

--refactor sent_at and received at to processed at
ALTER TABLE T_WBCI_MELDUNG RENAME COLUMN SENT_AT to PROCESSED_AT;
ALTER TABLE T_WBCI_REQUEST drop column RECEIVED_AT;
ALTER TABLE T_WBCI_REQUEST RENAME COLUMN SENT_AT to PROCESSED_AT;