
CREATE TABLE T_WBCI_TV
  (id NUMBER(19, 0) NOT NULL,
  version NUMBER(19, 0),
  AENDERUNGS_ID varchar2(21),
  TV_TERMIN DATE not null,
  ENDKUNDE_ID NUMBER(19, 0),
  PRIMARY KEY (id));

GRANT SELECT, INSERT, UPDATE ON T_WBCI_TV TO R_HURRICAN_USER;
GRANT SELECT ON T_WBCI_TV TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_TV_0;
GRANT SELECT ON S_T_WBCI_TV_0 TO PUBLIC;

ALTER TABLE T_WBCI_TV ADD CONSTRAINT
  FK_WBCITV_2_ENDKUNDE FOREIGN KEY (ENDKUNDE_ID) REFERENCES T_WBCI_PERSON_ODER_FIRMA(ID);

alter table T_WBCI_REQUEST add TV_ID NUMBER(19,0);
ALTER TABLE T_WBCI_REQUEST ADD CONSTRAINT
  FK_WBCIREQ_2_TV FOREIGN KEY (TV_ID) REFERENCES T_WBCI_TV(ID);
