ALTER TABLE T_WBCI_REQUEST drop constraint CK_WBCIREQ_TYP;
ALTER TABLE T_WBCI_REQUEST
ADD CONSTRAINT CK_WBCIREQ_TYP
CHECK (TYP IN (
    'VA',
    'TV',
    'STR-AUFH-ABG',
    'STR-AUFH-AUF',
    'STR-AEN-ABG',
    'STR-AEN-AUF'
  )) ENABLE NOVALIDATE;
