DROP SEQUENCE S_T_WBCI_TV_0;
ALTER TABLE T_WBCI_REQUEST DROP CONSTRAINT FK_WBCIREQ_2_TV;
ALTER TABLE T_WBCI_REQUEST DROP COLUMN TV_ID;
DROP TABLE  T_WBCI_TV;

ALTER TABLE T_WBCI_REQUEST add
  TV_TERMIN DATE;
