ALTER TABLE T_CARRIER add VA_MODUS VARCHAR2(30 char) DEFAULT 'FAX' NOT NULL;

ALTER TABLE T_CARRIER
ADD CONSTRAINT CK_VA_MODUS_TYP
CHECK (VA_MODUS IN (
    'WBCI',
    'PORTAL',
    'FAX'
  )) ENABLE NOVALIDATE;