ALTER TABLE T_CARRIER_CONTACT ADD TYPE_REF_ID NUMBER(19,0);

ALTER TABLE T_CARRIER_CONTACT ADD CONSTRAINT FK_CONTACT_TYP_REFERENCE_ID FOREIGN KEY (TYPE_REF_ID) REFERENCES T_REFERENCE;

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, DESCRIPTION) VALUES (23000, 'CARRIER_CONTACT_TYPE', 'Allgemein', 1, 'Kontaktperson für allgemeine Angelegenheiten');
INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, DESCRIPTION) VALUES (23001, 'CARRIER_CONTACT_TYPE', 'WBCI-Kontakt', 1, 'Kontaktperson für WBCI Angelegenheiten');
INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, DESCRIPTION) VALUES (23002, 'CARRIER_CONTACT_TYPE', 'WITA-Kontakt', 1, 'Kontaktperson für WITA Angelegenheiten');

