CREATE INDEX IX_WBCILTG_2_UEMID ON T_WBCI_LEITUNG (UEBERNAHME_MELDUNG_ID) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_WBCIMLD_2_RNPID ON T_WBCI_MELDUNG (RUFNUMMERPORTIERUNG_ID) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_WBCIMPOS_2_MLDID ON T_WBCI_MELDUNG_POSITION (MELDUNG_ID) TABLESPACE "I_HURRICAN";
CREATE INDEX IX_WBCIMPOS_2_STORTABWID ON T_WBCI_MELDUNG_POSITION (STANDORT_ABWEICHEND_ID) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_WBCIMPOSRN_2_MPOSID ON T_WBCI_MPOS_ABBM_RUFNUMMER (MPOS_ABBM_ID) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_WBCIRNPONKZ_2_RNPEINZID ON T_WBCI_RNP_EINZELN_RN_ONKZ (RNP_EINZELN_ID) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_WBCIRNB_2_RNBCKID ON T_WBCI_RUFNUMMERNBLOCK (RUFNUMMER_BLOCK_ID) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_WBCITECHRES_2_MLDID ON T_WBCI_TECHNISCHE_RESSOURCE (MELDUNG_ID) TABLESPACE "I_HURRICAN";
