-- Insert a new config property wbci.count.of.minutes.meldung.onhold
INSERT INTO T_WITA_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, VERSION) VALUES (S_T_WITA_CONFIG_0.nextval, 'wbci.count.of.minutes.meldung.onhold', '15', 1);

ALTER TABLE T_WBCI_REQUEST ADD (SEND_AFTER TIMESTAMP);
ALTER TABLE T_WBCI_MELDUNG ADD (SEND_AFTER TIMESTAMP);

CREATE INDEX IX_WBCIREQ_2_SENDAFTER ON T_WBCI_REQUEST (SEND_AFTER) TABLESPACE "I_HURRICAN";
CREATE INDEX IX_WBCIMLD_2_SENDAFTER ON T_WBCI_MELDUNG (SEND_AFTER) TABLESPACE "I_HURRICAN";
