-- Wholesale FttB Produkt anlegen
Insert into T_PRODUKTGRUPPE (ID, PRODUKTGRUPPE, AM_RESPONSIBILITY, VERSION)
 values (32, 'Wholesale', 1201, 0);

Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, 
    LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP, 
    BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN, 
    BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG, 
    ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, 
    CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT, 
    EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, 
    VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, 
    CPS_PROD_NAME, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, 
    TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER, VIER_DRAHT, VERSION, MIN_DN_COUNT, 
    TDN_KIND_OF_USE_TYPE_VPN, CPS_IP_DEFAULT, CPS_MULTI_DRAHT, IP_POOL, IP_PURPOSE_V4, 
    IP_PURPOSE_V4_EDITABLE, IP_NETMASK_SIZE_V4, IP_NETMASK_SIZE_V6, IP_NETMASK_SIZE_EDITABLE)
 Values
   (600, 32, NULL, 'Wholesale FTTB', NULL, 
    NULL, 0, 0, '0', NULL, 
    '0', TO_DATE('03/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '0', 
    '0', '0', '0', 0, 'Wholesale FttB Auftrag', 
    NULL, NULL, '0', '0', '0', 
    '0', '0', '0', '0', '0', 
    NULL, NULL, '0', NULL, NULL, 
    NULL, '0', '0', '0', '0', 
    NULL, '0', NULL, NULL, NULL, 
    NULL, NULL, '0', 0, 0, 
    NULL, '0', '0', NULL, NULL, 
    NULL, NULL, NULL, NULL);


-- Standorttyp 'FTTB' zuordnen
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
 values (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 600, 11002, 1, 'IMPORT', SYSDATE, 0);

-- Physiktyp 'FTTB_VDSL2' zuordnen
Insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, VIRTUELL, VERSION)
 values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 600, 800, '0', 0);

-- Technische Leistungen
-- Upstream 20000 (doppelter Upstream fuer FTTB 50 und 100)
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP, 
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION, 
    DISPO, EWSD, SDH, IPS, SCT, 
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (54, '20000 kbit/s', NULL, 10054, 'UPSTREAM', 
    20000, '20000', NULL, '20000', NULL, 
    '0', '0', '0', '0', '0', 
    NULL, '1', TO_DATE('03/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

-- TP (Multicast)
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP, 
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION, 
    DISPO, EWSD, SDH, IPS, SCT, 
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (425, 'TP (Multicast)', NULL, 10300, 'WHOLESALE', 
    NULL, NULL, NULL, ' ', 'Wholesale Multicast fuer bspw. TV', 
    '0', '0', '0', '0', '0', 
    NULL, '1', TO_DATE('03/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

-- Leistungsmapping erstellen
-- Downstream 16000
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 12, NULL, '0', 0);
-- Downstream 25000
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 23, NULL, '0', 0);
-- Downstream 50000
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 24, NULL, '0', 0);
-- Downstream 100000
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 25, NULL, '0', 0);

-- Upstream 1000 abhaengig von 16000, default
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 22, 12, '1', 0);
-- Upstream 2000 (doppelter Upstream 16000)
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 26, NULL, '0', 0);
-- Upstream 5000 abhaengig von 25000, default
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 27, 23, '1', 0);
-- Upstream 10000 abhaengig von 50000, default; aber auch doppelter Upstream 25000
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 28, 24, '1', 0);
-- Upstream 10000 abhaengig von 100000, default; aber auch doppelter Upstream 25000
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 28, 25, '1', 0);
-- Upstream 20000 (doppelter Upstream 50000 und 100000)
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 54, NULL, '0', 0);

 -- Multicast
 Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 600, 425, NULL, '0', 0);

