Delete from USERACCOUNT where USER_ID = 0;

Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 27, 3, 0);
Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 28, 4, 0);
Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 48, 10, 0);
Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 47, 7, 0);
Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 31, 13, 0);
Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 67, 5, 0);
Insert into USERACCOUNT (ID, USER_ID, ACCOUNT_ID, DB_ID, VERSION)
 Values (S_USERACCOUNT_0.nextval, 0, 49, 12, 0);