
update LEISTUNG set EXT_PRODUKT__NO=420, EXT_LEISTUNG__NO=10011 where LEISTUNG__NO=24497 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=420, EXT_LEISTUNG__NO=10012 where LEISTUNG__NO=24659 and VALID_TO>SYSDATE;

update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3309 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3310 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3311 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3312 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3313 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3314 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3315 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3316 and VALID_TO>SYSDATE;

update LEISTUNG set EXT_PRODUKT__NO=420 where EXT_PRODUKT__NO=422;
