-- weitere Leistungs-Konfiguration fuer Produkt-Mapping Taifun / Hurrican

-- Maxi ISDN
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=24331 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=22167 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=22230 and VALID_TO>SYSDATE;

-- MaxiDSL mit analog
update LEISTUNG set EXT_PRODUKT__NO=421, EXT_LEISTUNG__NO=10013 where LEISTUNG__NO=22914 and VALID_TO>SYSDATE;

-- MaxiDSL + ISDN
update LEISTUNG set EXT_PRODUKT__NO=420, EXT_LEISTUNG__NO=10012 where LEISTUNG__NO=22698 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=22699 and VALID_TO>SYSDATE;


update LEISTUNG set EXT_PRODUKT__NO=420, EXT_LEISTUNG__NO=10010 where LEISTUNG__NO=22233 and VALID_TO>SYSDATE;

