
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3309 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3310 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3311 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3312 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3313 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3314 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3315 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=NULL, EXT_LEISTUNG__NO=NULL where LEISTUNG__NO=3316 and VALID_TO>SYSDATE;

update LEISTUNG set EXT_PRODUKT__NO=336, EXT_LEISTUNG__NO=20003 where LEISTUNG__NO=25622 and VALID_TO>SYSDATE;

-- Produkt MPR --> Konfig auf Maxi statt auf Premium
update LEISTUNG set EXT_PRODUKT__NO=323 where LEISTUNG__NO=22052 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323 where LEISTUNG__NO=22551 and VALID_TO>SYSDATE;

-- Produkt PLUS (Premium)
update LEISTUNG set EXT_PRODUKT__NO=430 where LEISTUNG__NO=22193 and VALID_TO>SYSDATE;

-- Produkt SEKPR (Maxi)
update LEISTUNG set EXT_PRODUKT__NO=420 where LEISTUNG__NO=22218 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323 where LEISTUNG__NO=22368 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=422 where LEISTUNG__NO=23376 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323 where LEISTUNG__NO=24042 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=323 where LEISTUNG__NO=24648 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=421 where LEISTUNG__NO=25326 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=421 where LEISTUNG__NO=25536 and VALID_TO>SYSDATE;

-- Produkt SEK (Premium)
update LEISTUNG set EXT_PRODUKT__NO=337 where LEISTUNG__NO=22046 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=336 where LEISTUNG__NO=22154 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=432 where LEISTUNG__NO=22516 and VALID_TO>SYSDATE;

-- Produkt Maxi S ALT
update LEISTUNG set EXT_PRODUKT__NO=421 where LEISTUNG__NO=21452 and VALID_TO>SYSDATE;

-- Produkt Maxi M ALT
update LEISTUNG set EXT_PRODUKT__NO=421 where LEISTUNG__NO=21718 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=420 where LEISTUNG__NO=21758 and VALID_TO>SYSDATE;
update LEISTUNG set EXT_PRODUKT__NO=420 where LEISTUNG__NO=21824 and VALID_TO>SYSDATE;



