--
-- Service-Chains fuer Maxi MAX
--

INSERT INTO T_SERVICE_COMMANDS (ID, NAME, CLASS, TYPE, DESCRIPTION) 
	VALUES (24, 'check.physiktyp.compatibility', 
	'de.augustakom.hurrican.service.cc.impl.command.physik.CheckPhysiktypCompatibilityCommand', 
	'PHYSIK', 'Ueberprueft, ob der Physiktyp des alten Auftrags fuer den neuen Auftrag verwendet werden kann.');

-- Chain-Definition fuer Anschlussuebernahmen aendern 
-- Es wird jetzt zusaetzlich ueberprueft, ob der Physiktyp des alten Auftrags
-- fuer den neuen Auftrag verwendet werden kann
DELETE FROM T_SERVICECHAIN_2_COMMAND where CHAIN_ID=1;
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 15, 1);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 24, 2);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 8, 3);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 2, 4);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 3, 5);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 4, 6);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 16, 7);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 11, 8);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 5, 9);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 22, 10);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 7, 11);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 21, 12);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (1, 10, 13);

-- Anschlussuebernahme von AK-ADSLxxx, DSLplus xxx und Maxi DSL xxx auf Maxi MAX
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (9, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (56, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (57, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (321, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (315, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (316, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (317, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (320, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (324, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (325, 327, 5000, 1);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (326, 327, 5000, 1);

-- Chain-Definition fuer Bandbreitenaenderungen aendern.
-- Es wird jetzt zusaetzlich ueberprueft, ob der Physiktyp des alten Auftrags
-- fuer den neuen Auftrag verwendet werden kann
delete from T_SERVICECHAIN_2_COMMAND where chain_id in (3);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 15, 1);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 24, 2);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 1, 3);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 3, 4);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 4, 5);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 6, 6);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 5, 7);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 16, 8);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 7, 9);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 2, 10);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 21, 11);
INSERT INTO T_SERVICECHAIN_2_COMMAND (CHAIN_ID, COMMAND_ID, ORDER_NO) VALUES (3, 10, 12);

-- Bandbreitenaenderung von Maxi DSL xxx auf Maxi MAX
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (324, 327, 5004, 3);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (325, 327, 5004, 3);
INSERT INTO T_PROD_2_PROD (PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID) VALUES (326, 327, 5004, 3);






