--
-- Skript zur Anlage des Produktes M-Net Premium
--

insert into T_PRODUKT (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, LEITUNGSART, AKTIONS_ID, BRAUCHT_DN, DN_MOEGLICH, MAX_DN_COUNT, DN_BLOCK, DN_TYP, BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_VORS, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT, EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, BRAUCHT_VPI_VCI, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER)
values (446, 18, null, 'M-Net Premium DSL + ANALOG', 'M-Net Premium DSL + ANALOG', null ,  1, 1, 0, 1, 0, 60, 0, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), 0, 'DV', 1, 0, 1, 0, 1, null, 'XA', 1, 1, 0, 0, 0, 1, 1, 1, 1, null, 4, 0, 0, null, 16, 13, 0, 0,0, 1, 'PremiumDSL+ANALOG', null, 1, 'MAXI-HSI', 1, 'W', 'A', null);

-- T_PRODUKT_MAPPING
INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE)
VALUES (446, 446, 446, 'dsl');

-- T_PRODUKT_2_PHYSIKTYP
INSERT INTO T_PRODUKT_2_PHYSIKTYP (id, prod_id, physiktyp, PHYSIKTYP_ADDITIONAL, VIRTUELL)
VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextval, 446, 7, 12, '0');
INSERT INTO T_PRODUKT_2_PHYSIKTYP (id, prod_id, physiktyp, PHYSIKTYP_ADDITIONAL, VIRTUELL)
VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextval, 446, 507, 512, null);
INSERT INTO T_PRODUKT_2_PHYSIKTYP (id, prod_id, physiktyp, PHYSIKTYP_ADDITIONAL, VIRTUELL)
VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextval, 446, 513, 512, null);

-- T_PROD_2_TECH_LEISTUNG
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 1, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 3, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 4, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 7, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 21, null, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 22, 21, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 50, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 100, null, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 103, null, 0);

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 8, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 9, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 10, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 11, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 33, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 38, null, 0);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 13, 8, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 13, 9, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 14, 10, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 14, 11, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 15, 33, 1);
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 446, 15, 38, 1);

-- T_BA_VERL_AEND_PROD_2_GRUPPE
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (prod_id, ba_verl_aend_gruppe_id)
VALUES(446, 1);
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (prod_id, ba_verl_aend_gruppe_id)
VALUES(446, 2);
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (prod_id, ba_verl_aend_gruppe_id)
VALUES(446, 4);

-- T_BA_VERL_CONFIG
insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW)
values (S_T_BA_VERL_CONFIG_0.nextval, 446, 67, 2, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), to_date('01.11.2009', 'dd.mm.yyyy'), 'HURRICAN');
insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW)
values (S_T_BA_VERL_CONFIG_0.nextval, 446, 43, 16, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), to_date('01.11.2009', 'dd.mm.yyyy'), 'HURRICAN');
insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW)
values (S_T_BA_VERL_CONFIG_0.nextval, 446, 27, 15, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), to_date('01.11.2009', 'dd.mm.yyyy'), 'HURRICAN');
insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW)
values (S_T_BA_VERL_CONFIG_0.nextval, 446, 13, 16, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), to_date('01.11.2009', 'dd.mm.yyyy'), 'HURRICAN');
insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW)
values (S_T_BA_VERL_CONFIG_0.nextval, 446, 16, 5, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), to_date('01.11.2009', 'dd.mm.yyyy'), 'HURRICAN');
insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW)
values (S_T_BA_VERL_CONFIG_0.nextval, 446, 14, 5, to_date('01.11.2009', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), to_date('01.11.2009', 'dd.mm.yyyy'), 'HURRICAN');


-- T_CPS_DATA_CHAIN_CONFIG
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 446, 14000, 51);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 446, 14001, 51);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 446, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 446, 14006, 51);

-- T_SPERRE_VERTEILUNG
insert into T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID)
values (446, 2);
insert into T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID)
values (446, 3);

-- T_PROD_2_EG
insert into T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE)
values (S_T_PROD_2_EG_0.nextval, 446, 50, 0, 1);

-- T_PROD_2_DSLAMPROFILE
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 83);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 84);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 45);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 47);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 53);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 55);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 61);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 62);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 58);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 60);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 63);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 64);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 65);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 66);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 67);
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
values (446, 69);


-- T_PRODUKT_2_SCHNITTSTELLE
insert into T_PRODUKT_2_SCHNITTSTELLE (PROD_ID, SCHNITTSTELLE_ID)
values (446, 32);
