--
-- View um die aktuellste ABM aller WITA Geschaeftsfaelle mit Zieltermin in der Zukunft zu ermitteln
--
CREATE OR REPLACE FORCE VIEW MIGRATION_TAL_BESTELLUNGEN_FFM AS
  SELECT
    m.VERBINDLICHER_LIEFERTERMIN AS ABM_LIEFERTERMIN,
    m.ID                         AS ABM_ID,
    m.EXT_AUFTRAGS_NR            AS EXTERNE_AUFTRAGS_NR,
    mp.MELDUNGS_CODE             AS MELDUNGS_CODE,
    rq.ID                        AS REQUEST_ID,
    kwt.ZEITFENSTER              AS KWT_ZEITFENSTER,
    cbv.ID                       AS CB_VORGANG_ID,
    cbv.AUFTRAG_ID               AS AUFTRAG_ID,
    cb.CB_ID                     AS CB_ID,
    v.ID                         AS VERLAUF_ID,
    va.ID                        AS FFM_VERLAUF_ID,
    va.DATUM_ERLEDIGT            AS FFM_DATUM_ERLEDIGT
  FROM T_MWF_MELDUNG m
    INNER JOIN T_MWF_REQUEST rq ON (m.EXT_AUFTRAGS_NR = rq.EXTERNE_AUFTRAGSNUMMER AND rq.REQUESTTYPE = 'Auftrag')
    INNER JOIN T_MWF_GESCHAEFTSFALL gf ON rq.GESCHAEFTSFALL_ID = gf.ID
    INNER JOIN T_MWF_KUNDENWUNSCHTERMIN kwt ON gf.KUNDENWUNSCHTERMIN_ID = kwt.ID
    INNER JOIN T_CB_VORGANG cbv ON rq.CB_VORGANG_ID = cbv.ID
    LEFT JOIN T_CARRIERBESTELLUNG cb ON cbv.CB_ID = cb.CB_ID
    LEFT JOIN T_MWF_MELDUNGS_POSITION mp ON (m.ID = mp.MELDUNG_ID AND mp.MELDUNGS_CODE = '0011')
    LEFT JOIN T_VERLAUF v ON (cbv.AUFTRAG_ID = v.AUFTRAG_ID
        AND v.AKT = '1'
        AND (v.PROJEKTIERUNG IS NULL OR v.PROJEKTIERUNG = '0'))
    LEFT JOIN T_VERLAUF_ABTEILUNG va ON (v.ID = va.VERLAUF_ID AND va.ABTEILUNG_ID = 14)
  WHERE m.MELDUNGSTYP = 'ABM'
        AND m.VERBINDLICHER_LIEFERTERMIN > SYSDATE
        AND m.ID = (SELECT max(m2.ID)
                    FROM T_MWF_MELDUNG m2
                    WHERE m.EXT_AUFTRAGS_NR = m2.EXT_AUFTRAGS_NR AND m2.MELDUNGSTYP = 'ABM' AND
                          m2.VERBINDLICHER_LIEFERTERMIN > SYSDATE
                    GROUP BY m2.EXT_AUFTRAGS_NR)
  ORDER BY m.VERBINDLICHER_LIEFERTERMIN;

GRANT SELECT ON MIGRATION_TAL_BESTELLUNGEN_FFM TO R_HURRICAN_USER;
