GRANT USAGE ON * . * TO "report-admin"@"10.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-admin"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_template` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`T_SERVICE_COMMAND_MAPPING` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_2_prod` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_rep2prod_stati` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_rep2prod_techls` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_2_userrole` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_data` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_2_gruppe` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_gruppe_2_report` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_gruppe` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_gruppe` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_reason` TO "report-admin"@"10.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_archiv_daten` TO "report-admin"@"10.%";

GRANT USAGE ON * . * TO "report-admin"@"192.168.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_template` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`T_SERVICE_COMMAND_MAPPING` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_2_prod` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_rep2prod_stati` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_rep2prod_techls` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_2_userrole` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_data` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_2_gruppe` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_gruppe_2_report` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_gruppe` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_gruppe` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_reason` TO "report-admin"@"192.168.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_archiv_daten` TO "report-admin"@"192.168.%";

GRANT USAGE ON * . * TO "report-admin"@"172.22.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_template` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`T_SERVICE_COMMAND_MAPPING` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_2_prod` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_rep2prod_stati` TO "report-admin"@"172.22..%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_rep2prod_techls` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_2_userrole` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_data` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_2_gruppe` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_gruppe_2_report` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_txt_baustein_gruppe` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_gruppe` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_report_reason` TO "report-admin"@"172.22.%";
GRANT INSERT , UPDATE , DELETE ON `hurrican`.`t_archiv_daten` TO "report-admin"@"172.22.%";
 
GRANT USAGE ON * . * TO "report-user"@"10.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-user"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-user"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_data` TO "report-user"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-user"@"10.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_archiv_daten` TO "report-user"@"10.%";
GRANT USAGE ON * . * TO "report-user"@"192.168.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_data` TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_archiv_daten` TO "report-user"@"192.168.%";
GRANT USAGE ON * . * TO "report-user"@"172.22.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-user"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-user"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_data` TO "report-user"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-user"@"172.22.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_archiv_daten` TO "report-user"@"172.22.%";
GRANT USAGE ON * . * TO "report-user"@"172.16.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-user"@"172.16.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-user"@"172.16.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_data` TO "report-user"@"172.16.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-user"@"172.16.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_archiv_daten` TO "report-user"@"172.16.%";

GRANT USAGE ON * . * TO "report-user"@"192.168.%" IDENTIFIED BY "troper" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT ON `hurrican` . * TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_request` TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_report_data` TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_telefonbuch_anschreiben` TO "report-user"@"192.168.%";
GRANT INSERT , UPDATE ON `hurrican`.`t_archiv_daten` TO "report-user"@"192.168.%";
