--
-- PrimaryKeys und Indexe auf der AUTHENTICATION DB erzeugen.
--

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)
/
ALTER TABLE ACCOUNT ADD CONSTRAINT UK_ACCOUNT_NAME UNIQUE (ACC_NAME)
/
CREATE INDEX APP_ID
	ON ACCOUNT (APP_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE APPLICATION ADD CONSTRAINT PK_APPLICATION PRIMARY KEY (ID)
/
ALTER TABLE APPLICATION ADD CONSTRAINT UK_APPLICATION_NAME UNIQUE (NAME)
/
ALTER TABLE COMPBEHAVIOR ADD CONSTRAINT PK_COMPBEHAVIOR PRIMARY KEY (ID)
/
ALTER TABLE COMPBEHAVIOR ADD CONSTRAINT UK_COMPBEHAVIOR UNIQUE (COMP_ID, ROLE_ID)
/
CREATE INDEX ROLE_ID
	ON COMPBEHAVIOR (ROLE_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX COMP_ID
	ON COMPBEHAVIOR (COMP_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE DB ADD CONSTRAINT PK_DB PRIMARY KEY (ID)
/
ALTER TABLE DB ADD CONSTRAINT UK_DB_NAME UNIQUE (NAME)
/
ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)
/
ALTER TABLE DEPARTMENT ADD CONSTRAINT UK_DEPARTMENT_NAME UNIQUE (NAME)
/
ALTER TABLE GUICOMPONENT ADD CONSTRAINT PK_GUICOMPONENT PRIMARY KEY (ID)
/
ALTER TABLE GUICOMPONENT ADD CONSTRAINT UK_GUICOMPONENT UNIQUE (NAME, PARENT, APP_ID)
/
CREATE INDEX GUICOMP_APP_ID
	ON GUICOMPONENT (APP_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE PWHISTORY ADD CONSTRAINT PK_PWHISTORY PRIMARY KEY (ID)
/
CREATE INDEX USER_ID
	ON PWHISTORY (USER_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID)
/
ALTER TABLE ROLE ADD CONSTRAINT UK_ROLE UNIQUE (NAME, APP_ID)
/
CREATE INDEX ROLE_APP_ID
	ON ROLE (APP_ID) TABLESPACE "I_HURRICAN"
/

ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (ID)
/
ALTER TABLE USERS ADD CONSTRAINT UK_USER_LOGINNAME UNIQUE (LOGINNAME)
/
CREATE INDEX IX_USER_DEP
	ON USERS (DEP_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX IX_USER_PW
	ON USERS (PASSWORD) TABLESPACE "I_HURRICAN"
/
ALTER TABLE USERACCOUNT ADD CONSTRAINT PK_USERACCOUNT PRIMARY KEY (ID)
/
ALTER TABLE USERACCOUNT ADD CONSTRAINT UK_USERACCOUNT_USERACC UNIQUE (USER_ID, ACCOUNT_ID)
/
ALTER TABLE USERACCOUNT ADD CONSTRAINT UK_USERACCOUNT_USERDB UNIQUE (USER_ID, DB_ID)
/
CREATE INDEX ACCOUNT_ID
	ON USERACCOUNT (ACCOUNT_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX UACC_USER_ID
	ON USERACCOUNT (USER_ID) TABLESPACE "I_HURRICAN"
/

CREATE INDEX DB_ID
	ON USERACCOUNT (DB_ID) TABLESPACE "I_HURRICAN"
/

ALTER TABLE USERROLE ADD CONSTRAINT PK_USERROLE PRIMARY KEY (ID)
/
ALTER TABLE USERROLE ADD CONSTRAINT UK_USERROLE UNIQUE (USER_ID, ROLE_ID)
/

CREATE INDEX UR_USER_ID
	ON USERROLE (USER_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX UR_ROLE_ID
	ON USERROLE (ROLE_ID) TABLESPACE "I_HURRICAN"
/

ALTER TABLE USERSESSION ADD CONSTRAINT PK_USERSESSION PRIMARY KEY (SESSION_ID)
/
CREATE INDEX US_USER_ID
	ON USERSESSION (USER_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX US_APP_ID
	ON USERSESSION (APP_ID) TABLESPACE "I_HURRICAN"
/


