--
-- ForeignKeys auf der AUTHENTICATION DB anlegen.
--


ALTER TABLE ROLE
  ADD CONSTRAINT FK_ROLE_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE ACCOUNT
  ADD CONSTRAINT FK_DBACCOUNT_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE ACCOUNT
  ADD CONSTRAINT FK_DBACCOUNT_TO_DB
      FOREIGN KEY (DB_ID)
      REFERENCES DB (ID);

ALTER TABLE GUICOMPONENT
  ADD CONSTRAINT FK_GUICOMPONENT_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE USERS
  ADD CONSTRAINT FK_USER_TO_DEPART
      FOREIGN KEY (DEP_ID)
      REFERENCES DEPARTMENT (ID);

ALTER TABLE USERSESSION
  ADD CONSTRAINT FK_USERSESSION_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERSESSION
  ADD CONSTRAINT FK_USERSESSION_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE PWHISTORY
  ADD CONSTRAINT FK_PWHISTORY_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERACCOUNT
  ADD CONSTRAINT FK_USERACCOUNT_TO_ACC
      FOREIGN KEY (ACCOUNT_ID)
      REFERENCES ACCOUNT (ID);

ALTER TABLE USERACCOUNT
  ADD CONSTRAINT FK_USERACCOUNT_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERACCOUNT
  ADD CONSTRAINT FK_USERACC_2_DB
      FOREIGN KEY (DB_ID)
      REFERENCES DB (ID);

ALTER TABLE COMPBEHAVIOR
  ADD CONSTRAINT FK_COMPBEHAVIOR_TO_ROLE
      FOREIGN KEY (ROLE_ID)
      REFERENCES ROLE (ID);

ALTER TABLE COMPBEHAVIOR
  ADD CONSTRAINT FK_COMPBEHAVIOR_TO_COMP
      FOREIGN KEY (COMP_ID)
      REFERENCES GUICOMPONENT (ID);

ALTER TABLE USERROLE
  ADD CONSTRAINT FK_UR_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERROLE
  ADD CONSTRAINT FK_UR_TO_ROLE
      FOREIGN KEY (ROLE_ID)
      REFERENCES ROLE (ID);
