--
-- GRANTs fuer die DB-Rolle 'R_AUTHENTICATION_USER'
--

CREATE ROLE "R_AUTHENTICATION_USER" NOT IDENTIFIED;
GRANT SELECT ON ACCOUNT TO R_AUTHENTICATION_USER;
GRANT SELECT ON APPLICATION TO R_AUTHENTICATION_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMPBEHAVIOR TO R_AUTHENTICATION_USER;
GRANT SELECT ON DB TO R_AUTHENTICATION_USER;
GRANT SELECT ON DEPARTMENT TO R_AUTHENTICATION_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON GUICOMPONENT TO R_AUTHENTICATION_USER;
GRANT SELECT, INSERT, UPDATE ON PWHISTORY TO R_AUTHENTICATION_USER;
GRANT SELECT ON ROLE TO R_AUTHENTICATION_USER;
GRANT SELECT ON USERACCOUNT TO R_AUTHENTICATION_USER;
GRANT SELECT ON USERROLE TO R_AUTHENTICATION_USER;
GRANT SELECT, UPDATE ON USERS TO R_AUTHENTICATION_USER;
GRANT SELECT, INSERT, DELETE ON USERSESSION TO R_AUTHENTICATION_USER;
GRANT SELECT ON V_EXT_SERVICE_PROVIDER TO R_AUTHENTICATION_USER;
GRANT SELECT ON V_NIEDERLASSUNG TO R_AUTHENTICATION_USER;
commit;

