/*
 * Resource Ordering Management
 * This is Swagger UI environment generated for the TMF Resource Ordering Management specification
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rom.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.io.Serializable;
import java.net.URI;
import java.time.OffsetDateTime;

        /**
* Request for cancellation an existing resource order Skipped properties: id,href,state,effectiveCancellationDate
*/
    @JsonPropertyOrder({
        CancelResourceOrderCreate.JSON_PROPERTY_CANCELLATION_REASON,
        CancelResourceOrderCreate.JSON_PROPERTY_REQUESTED_CANCELLATION_DATE,
        CancelResourceOrderCreate.JSON_PROPERTY_RESOURCE_ORDER,
        CancelResourceOrderCreate.JSON_PROPERTY_AT_BASE_TYPE,
        CancelResourceOrderCreate.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        CancelResourceOrderCreate.JSON_PROPERTY_AT_TYPE
    })
            @JsonTypeName("CancelResourceOrder_Create")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class CancelResourceOrderCreate implements Serializable {
        public static final String JSON_PROPERTY_CANCELLATION_REASON = "cancellationReason";
            private String cancellationReason;

        public static final String JSON_PROPERTY_REQUESTED_CANCELLATION_DATE = "requestedCancellationDate";
            private OffsetDateTime requestedCancellationDate;

        public static final String JSON_PROPERTY_RESOURCE_ORDER = "resourceOrder";
            private ResourceOrderRef resourceOrder;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

