/*
 * Resource Ordering Management
 * This is Swagger UI environment generated for the TMF Resource Ordering Management specification
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rom.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.net.URI;
import java.time.OffsetDateTime;

        /**
* A Order cancel is a type of task which  can  be used to place a request to cancel an order
*/
    @JsonPropertyOrder({
        CancelOrder.JSON_PROPERTY_ID,
        CancelOrder.JSON_PROPERTY_HREF,
        CancelOrder.JSON_PROPERTY_CANCELLATION_REASON,
        CancelOrder.JSON_PROPERTY_EFFECTIVE_CANCELLATION_DATE,
        CancelOrder.JSON_PROPERTY_REQUESTED_CANCELLATION_DATE,
        CancelOrder.JSON_PROPERTY_STATE,
        CancelOrder.JSON_PROPERTY_AT_BASE_TYPE,
        CancelOrder.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        CancelOrder.JSON_PROPERTY_AT_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class CancelOrder implements Serializable {
        public static final String JSON_PROPERTY_ID = "id";
            private String id;

        public static final String JSON_PROPERTY_HREF = "href";
            private String href;

        public static final String JSON_PROPERTY_CANCELLATION_REASON = "cancellationReason";
            private String cancellationReason;

        public static final String JSON_PROPERTY_EFFECTIVE_CANCELLATION_DATE = "effectiveCancellationDate";
            private OffsetDateTime effectiveCancellationDate;

        public static final String JSON_PROPERTY_REQUESTED_CANCELLATION_DATE = "requestedCancellationDate";
            private OffsetDateTime requestedCancellationDate;

        public static final String JSON_PROPERTY_STATE = "state";
            private TaskStateType state;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

