-- TECH_LS und TECH_LS_DEPENDENCY sind verkehrt herum; default muss gesetzt sein
update T_PROD_2_TECH_LEISTUNG set  TECH_LS_ID=43, TECH_LS_DEPENDENCY=560, IS_DEFAULT='1'
    where PROD_ID=511 and TECH_LS_ID=560 and TECH_LS_DEPENDENCY=43;

update T_PROD_2_TECH_LEISTUNG set  TECH_LS_ID=22, TECH_LS_DEPENDENCY=560, IS_DEFAULT='1'
    where PROD_ID=511 and TECH_LS_ID=560 and TECH_LS_DEPENDENCY=22;
