
INSERT INTO T_PROD_2_CVLAN (ID,VERSION,PROD_ID,CVLAN_TYP,IS_MANDATORY,TECH_LOCATION_TYPE_REF_ID,HVT_TECHNIK_ID)
    VALUES (S_T_PROD_2_CVLAN_0.nextVal,0,511,'POTS','0',11013,6);
INSERT INTO T_PROD_2_CVLAN (ID,VERSION,PROD_ID,CVLAN_TYP,IS_MANDATORY,TECH_LOCATION_TYPE_REF_ID,HVT_TECHNIK_ID)
    VALUES (S_T_PROD_2_CVLAN_0.nextVal,0,511,'VOIP','0',11013,2);

INSERT INTO T_TECH_LEISTUNG_2_CVLAN (ID,VERSION,TECH_LS_ID,CVLAN_TYP) VALUES (S_T_TECH_LEISTUNG_2_CVLAN_0.nextVal,0,111,'POTS');