
-- EFM default fuer SDSL 15000 und 20000
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
    values  (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 68, 550, null,'1', 0);
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
    values  (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 69, 550, null,'1', 0);

-- EFM als abhaengige Leistung von VOIP_READY_66 fuer SDSL 2300, 4600, 6800, 10000
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
    values  (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 63, 550, 460,'0', 0);
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
    values  (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 64, 550, 460,'0', 0);
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
    values  (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 66, 550, 460,'0', 0);
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
    values  (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 67, 550, 460,'0', 0);
