INSERT INTO T_TECH_LEISTUNG_2_CVLAN (ID,VERSION,TECH_LS_ID,CVLAN_TYP,REMOVE_LOGIC)
    VALUES (S_T_TECH_LEISTUNG_2_CVLAN_0.nextVal,0,560,'VOIP', '1');
INSERT INTO T_TECH_LEISTUNG_2_CVLAN (ID,VERSION,TECH_LS_ID,CVLAN_TYP,REMOVE_LOGIC)
    VALUES (S_T_TECH_LEISTUNG_2_CVLAN_0.nextVal,0,560,'POTS', '1');