DELETE FROM T_WBCI_ANTWORTFRIST;

ALTER TABLE T_WBCI_ANTWORTFRIST ADD TYP VARCHAR2(25) NOT NULL;

ALTER TABLE T_WBCI_ANTWORTFRIST DROP CONSTRAINT UQ_WBCI_ANTWORTFRIST_STATUS;
DROP INDEX UQ_WBCI_ANTWORTFRIST_STATUS;

ALTER TABLE T_WBCI_ANTWORTFRIST
ADD CONSTRAINT CK_WBCI_ANTWORTFRIST_TYP
CHECK (TYP IN (
    'VA',
    'STR_AUFH_ABG',
    'STR_AUFH_AUF',
    'STR_AEN_ABG',
    'STR_AEN_AUF',
    'TV'
  )) ENABLE NOVALIDATE;

ALTER TABLE T_WBCI_ANTWORTFRIST
ADD CONSTRAINT UQ_WBCI_ANTWORTFRIST_TYP
UNIQUE (TYP, STATUS);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'VA', 'VA_EMPFANGEN', 72, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'VA', 'VA_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'VA', 'RUEM_VA_VERSENDET', 192, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'VA', 'RUEM_VA_EMPFANGEN', 192, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'TV', 'TV_EMPFANGEN', 72, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'TV', 'TV_VERSENDET', 72, 0);

-- STORNO EMPFANGEN

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_ABG', 'STORNO_EMPFANGEN', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_AUF', 'STORNO_EMPFANGEN', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_ABG', 'STORNO_EMPFANGEN', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_AUF', 'STORNO_EMPFANGEN', 72, 0);

-- STORNO VERSENDET

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_ABG', 'STORNO_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_AUF', 'STORNO_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_ABG', 'STORNO_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_AUF', 'STORNO_VERSENDET', 72, 0);

-- STORNO ERLM EMPFANGEN

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_ABG', 'STORNO_ERLM_EMPFANGEN', 24, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_AUF', 'STORNO_ERLM_EMPFANGEN', 24, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_ABG', 'STORNO_ERLM_EMPFANGEN', 168, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_AUF', 'STORNO_ERLM_EMPFANGEN', 168, 0);

-- STORNO ERLM VERSENDET

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_ABG', 'STORNO_ERLM_VERSENDET', 24, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AUFH_AUF', 'STORNO_ERLM_VERSENDET', 24, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_ABG', 'STORNO_ERLM_VERSENDET', 168, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, TYP, STATUS, FRIST_IN_STUNDEN, VERSION)
VALUES  (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STR_AEN_AUF', 'STORNO_ERLM_VERSENDET', 168, 0);
