CREATE TABLE T_WBCI_AUTOMATION_TASK (
    ID NUMBER(19, 0) NOT NULL,
    VERSION NUMBER(19, 0) NOT NULL,
    TASK_NAME VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(30 CHAR),
    GESCHAEFTSFALL_ID NUMBER(19, 0),
    CREATED_AT DATE NOT NULL,
    COMPLETED_AT DATE,
    USER_ID NUMBER(19,0) NOT NULL,
    USER_NAME VARCHAR2 (50 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE T_WBCI_AUTOMATION_TASK ADD CONSTRAINT FK_AUTOMATION_TASK_GF_ID FOREIGN KEY (GESCHAEFTSFALL_ID) REFERENCES T_WBCI_GESCHAEFTSFALL;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_WBCI_AUTOMATION_TASK TO R_HURRICAN_USER;

GRANT SELECT ON T_WBCI_AUTOMATION_TASK TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_AUTOMATION_TASK_0;

GRANT SELECT ON S_T_WBCI_AUTOMATION_TASK_0 TO PUBLIC;
