-- Insert a new WBCI_WITA_AUTO_PROCESSING feature flag
INSERT INTO T_FEATURE (ID, NAME, FLAG) VALUES (S_T_FEATURE_0.NEXTVAL, 'WBCI_WITA_AUTO_PROCESSING', '0');

-- Rename WBCI_AUTO_PROCESSING feature flag to WBCI_KFT_TEST_MODE
UPDATE T_FEATURE SET NAME='WBCI_KFT_TEST_MODE', FLAG='0' WHERE NAME='WBCI_AUTO_PROCESSING';
