-- MD_50000_50000_H
Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_50000_50000_H', '50000', '50000', '0',
   24, 53, '1', 0, '0',
   '0', sysdate,
   null);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_50000_50000_H', '50000', '50000', '0',
   24, 53, '1', 0, '0',
   '0', sysdate,
   37);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_50000_50000_H', '50000', '50000', '0',
   24, 53, '1', 0, '0',
   '0', sysdate,
   151);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_50000_50000_H', '50000', '50000', '0',
   24, 53, '1', 0, '0',
   '0', sysdate,
   172);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_50000_50000_H', '50000', '50000', '0',
   24, 53, '1', 0, '0',
   '0', sysdate,
   351);

-- MD_100000_100000_H
Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_100000_100000_H', '100000', '100000', '0',
   25, 71, '1', 0, '0',
   '0', sysdate,
   null);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_100000_100000_H', '100000', '100000', '0',
   25, 71, '1', 0, '0',
   '0', sysdate,
   37);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_100000_100000_H', '100000', '100000', '0',
   25, 71, '1', 0, '0',
   '0', sysdate,
   172);

Insert into T_DSLAM_PROFILE
(ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH,
 DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE,
 ENABLED_FOR_AUTOCHANGE, CHANGED_AT,
 BAUGRUPPEN_TYP)
Values
  (S_T_DSLAM_PROFILE_0.nextval, 'MD_100000_100000_H', '100000', '100000', '0',
   25, 71, '1', 0, '0',
   '0', sysdate,
   351);

-- DSLAM Profile zuordnen
-- 50.000/50.000
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_50000_50000_H' AND d.BAUGRUPPEN_TYP IS NULL));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_50000_50000_H' AND d.BAUGRUPPEN_TYP = 37));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_50000_50000_H' AND d.BAUGRUPPEN_TYP = 151));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_50000_50000_H' AND d.BAUGRUPPEN_TYP = 172));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_50000_50000_H' AND d.BAUGRUPPEN_TYP = 351));

-- 100.000/100.000
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_100000_100000_H' AND d.BAUGRUPPEN_TYP IS NULL));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_100000_100000_H' AND d.BAUGRUPPEN_TYP = 37));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_100000_100000_H' AND d.BAUGRUPPEN_TYP = 172));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
VALUES (541, (SELECT
                d.id
              FROM T_DSLAM_PROFILE d
              WHERE d.NAME = 'MD_100000_100000_H' AND d.BAUGRUPPEN_TYP = 351));
