ALTER TABLE T_PHYSIKTYP MODIFY MAX_BANDWIDTH NUMBER(19, 0);
ALTER TABLE T_PHYSIKTYP RENAME COLUMN MAX_BANDWIDTH TO max_Bandwidth_downstream;
ALTER TABLE T_PHYSIKTYP ADD max_Bandwidth_upstream NUMBER(19, 0);

ALTER TABLE T_HW_BAUGRUPPEN_TYP RENAME COLUMN MAX_BANDWIDTH TO max_Bandwidth_downstream;
ALTER TABLE T_HW_BAUGRUPPEN_TYP ADD max_Bandwidth_upstream NUMBER(19, 0);
