Insert into T_ABTEILUNG
   (ID, TEXT, NIEDERLASSUNG_ID, RELEVANT_4_PROJ, RELEVANT_4_BA, VERSION)
 Values
   (14, 'FFM', 3, '0', '1', 0);


Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (
   S_T_ABT_2_NL_0.nextVal,
   14,
   1, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (
   S_T_ABT_2_NL_0.nextVal,
   14,
   3, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (
   S_T_ABT_2_NL_0.nextVal,
   14,
   4, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (
   S_T_ABT_2_NL_0.nextVal,
   14,
   6, 0);
