CREATE TABLE T_FFM_PRODUCT_MAPPING (
  id                   NUMBER(19, 0) NOT NULL,
  VERSION NUMBER(19, 0) DEFAULT 0 NOT NULL,
  PROD_ID              NUMBER(19, 0) NOT NULL,
  BA_ANLASS_ID         NUMBER(19, 0) NOT NULL,
  STANDORT_TYP         NUMBER(19, 0) NOT NULL,
  FFM_ACTIVITY_TYPE    VARCHAR2(100) NOT NULL,
  FFM_PLANNED_DURATION NUMBER(19, 0) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE T_FFM_PRODUCT_MAPPING ADD CONSTRAINT FK_FFMPROD_2_PRODUCT FOREIGN KEY (PROD_ID) REFERENCES T_PRODUKT (PROD_ID);
ALTER TABLE T_FFM_PRODUCT_MAPPING ADD CONSTRAINT FK_FFMPROD_2_BAANLASS FOREIGN KEY (BA_ANLASS_ID) REFERENCES T_BA_VERL_ANLASS (ID);
ALTER TABLE T_FFM_PRODUCT_MAPPING ADD CONSTRAINT FK_FFMPROD_2_STDREF FOREIGN KEY (STANDORT_TYP) REFERENCES T_REFERENCE (ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON T_FFM_PRODUCT_MAPPING TO R_HURRICAN_USER;
GRANT SELECT ON T_FFM_PRODUCT_MAPPING TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_FFM_PRODUCT_MAPPING_0;
GRANT SELECT ON S_T_FFM_PRODUCT_MAPPING_0 TO PUBLIC;


CREATE TABLE T_FFM_QUALIFICATION (
  id                     NUMBER(19, 0) NOT NULL,
  VERSION NUMBER(19, 0) DEFAULT 0 NOT NULL,
  FFM_PRODUCT_MAPPING_ID NUMBER(19, 0) NOT NULL,
  FFM_QUALIFICATION      VARCHAR2(100) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE T_FFM_QUALIFICATION ADD CONSTRAINT FK_FFMQUAL_2_FFMPRODMAP FOREIGN KEY (FFM_PRODUCT_MAPPING_ID) REFERENCES T_FFM_PRODUCT_MAPPING (ID);
ALTER TABLE T_FFM_QUALIFICATION ADD CONSTRAINT UQ_FFM_QUALIFICATION UNIQUE (FFM_PRODUCT_MAPPING_ID, FFM_QUALIFICATION);

GRANT SELECT, INSERT, UPDATE, DELETE ON T_FFM_QUALIFICATION TO R_HURRICAN_USER;
GRANT SELECT ON T_FFM_QUALIFICATION TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_FFM_QUALIFICATION_0;
GRANT SELECT ON S_T_FFM_QUALIFICATION_0 TO PUBLIC;
