-- Produkt 'FTTX DSL+Fon'    (HVT, FTTC_KVZ, FTTB, FTTH)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 72, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 27, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 43, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 72, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 27, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 43, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 72, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 27, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 43, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 513, 72, 11013, 'RTL_Neu_MK_FttC', 45);


-- Produkt 'FTTX DSL'   (HVT, FTTC_KVZ, FTTB, FTTH)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 72, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 27, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 43, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 72, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 27, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 43, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 72, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 27, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 43, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 512, 72, 11013, 'RTL_Neu_MK_FttC', 45);

-- Produkt 'FTTX Telefon'   (HVT, FTTC_KVZ, FTTB, FTTH)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 72, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 27, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 43, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 72, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 27, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 43, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 72, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 27, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 43, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 511, 72, 11013, 'RTL_Neu_MK_FttC', 45);

-- Produkt 'DSL + analog'  (nur mit HVT realisiert!)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 421, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 421, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 421, 72, 11000, 'RTL_Neu_MK_HVT', 45);

-- Produkt 'DSL + ISDN'  (nur mit HVT realisiert!)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 420, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 420, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 420, 72, 11000, 'RTL_Neu_MK_HVT', 45);

-- Produkt 'DSL only'  (HVT und FTTC_KVZ)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 440, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 440, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 440, 72, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 440, 27, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 440, 43, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 440, 72, 11013, 'RTL_Neu_MK_FttC', 45);

-- Produkt 'DSL only (IPv6)'   (nur HVT)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 481, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 481, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 481, 72, 11000, 'RTL_Neu_MK_HVT', 45);

-- Produkt 'DSL + VoIP'    (nur HVT)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 480, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 480, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 480, 72, 11000, 'RTL_Neu_MK_HVT', 45);

-- Produkt 'Premium Glasfaser DSL DoppelFlat'   (HVT, FTTC_KVZ, FTTB, FTTH)
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 27, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 43, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 72, 11000, 'RTL_Neu_MK_HVT', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 27, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 43, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 72, 11002, 'RTL_Neu_MK_FttB', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 27, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 43, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 72, 11011, 'RTL_Neu_MK_FttH', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 27, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 43, 11013, 'RTL_Neu_MK_FttC', 45);
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 540, 72, 11013, 'RTL_Neu_MK_FttC', 45);


INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11000;

INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTB'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11002;

INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11011;

INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTC'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11013;