-- Migriert die Bandbreiten der Huawei HG8012H
CREATE OR REPLACE PROCEDURE update_hg8012h_bg_type
AS
  bgTypeId T_HW_BAUGRUPPEN_TYP.ID%TYPE;
  BEGIN
    SELECT
      ID
    INTO bgTypeId
    FROM T_HW_BAUGRUPPEN_TYP
    WHERE HW_TYPE_NAME = 'ONT' AND NAME = 'HG8012H_ETH' AND HW_SCHNITTSTELLE_NAME = 'ETH';

    IF bgTypeId IS NOT NULL
    THEN
      UPDATE T_HW_BAUGRUPPEN_TYP
      SET MAX_BANDWIDTH_DOWNSTREAM = 1000000, MAX_BANDWIDTH_UPSTREAM = 1000000
      WHERE ID = bgTypeId;
    END IF;
  END;
/

CALL update_hg8012h_bg_type();
DROP PROCEDURE update_hg8012h_bg_type;
