alter table T_FFM_PRODUCT_MAPPING add AGGREGATION_STRATEGY varchar2(25);
update T_FFM_PRODUCT_MAPPING set AGGREGATION_STRATEGY='HEADER_ONLY'
  where FFM_ACTIVITY_TYPE in ('RTL_Neu_MK_HVT', 'RTL_Neu_MK_FttC');
update T_FFM_PRODUCT_MAPPING set AGGREGATION_STRATEGY='TECHNICAL_PARAMS_INCLUDED'
  where FFM_ACTIVITY_TYPE in ('RTL_Neu_MK_FttB', 'RTL_Neu_MK_FttH');
alter table T_FFM_PRODUCT_MAPPING modify AGGREGATION_STRATEGY not null;


ALTER TABLE T_FFM_PRODUCT_MAPPING ADD (
  CONSTRAINT CK_FFMPRODMAP_AGGSTRATEGY
  CHECK (AGGREGATION_STRATEGY IN (
    'HEADER_ONLY',
    'TECHNICAL_PARAMS_INCLUDED'
  )));
