alter table T_FFM_PRODUCT_MAPPING drop constraint CK_FFMPRODMAP_AGGSTRATEGY;

ALTER TABLE T_FFM_PRODUCT_MAPPING ADD (
  CONSTRAINT CK_FFMPRODMAP_AGGSTRATEGY
  CHECK (AGGREGATION_STRATEGY IN (
    'HEADER_ONLY',
    'HEADER_ONLY_INTERN',
    'TECHNICAL_PARAMS_INCLUDED'
  )));

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 110, 70, null,
    'RTL_Int', 45, 'HEADER_ONLY_INTERN');

INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'interne Arbeit'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 110;