alter table T_FFM_PRODUCT_MAPPING modify AGGREGATION_STRATEGY varchar2(50);

alter table T_FFM_PRODUCT_MAPPING drop constraint CK_FFMPRODMAP_AGGSTRATEGY;

update T_FFM_PRODUCT_MAPPING set AGGREGATION_STRATEGY='TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT'
  where AGGREGATION_STRATEGY='HEADER_ONLY';
update T_FFM_PRODUCT_MAPPING set AGGREGATION_STRATEGY='TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT'
  where AGGREGATION_STRATEGY='TECHNICAL_PARAMS_INCLUDED';
update T_FFM_PRODUCT_MAPPING set AGGREGATION_STRATEGY='HEADER_ONLY_WITHOUT_TIMESLOT'
  where AGGREGATION_STRATEGY='HEADER_ONLY_INTERN';

ALTER TABLE T_FFM_PRODUCT_MAPPING ADD (
  CONSTRAINT CK_FFMPRODMAP_AGGSTRATEGY
  CHECK (AGGREGATION_STRATEGY IN (
    'HEADER_ONLY_WITHOUT_TIMESLOT',
    'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT',
    'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT'
  )));



-- weitere Produkte konfigurieren
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 514, 27, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 515, 27, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 445, 27, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 446, 27, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 430, 27, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 431, 27, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');

INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 514, 72, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 515, 72, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 445, 72, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 446, 72, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 430, 72, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 431, 72, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');


INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 514, 43, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 515, 43, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 445, 43, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 446, 43, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 430, 43, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 431, 43, 11000, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');


INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.prod_id in (514,515,445,446,430,431);


INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 445, 27, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 446, 27, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 430, 27, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 431, 27, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');

INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 445, 72, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 446, 72, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 430, 72, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 431, 72, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');

INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 445, 43, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 446, 43, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 430, 43, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
VALUES (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 431, 43, 11013, 'RTL_Neu_MK_FttC', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');


INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTC'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.prod_id in (445,446,430,431) and ffm.standort_typ=11013;

