INSERT INTO T_SPERRKLASSEN (ID,SPERRKLASSE,ABGEHEND,NATIONAL,INNOVATIVE_DIENSTE,MABEZ,MOBIL,VPN,PRD,AUSKUNFTSDIENSTE,
    INTERNATIONAL,OFF_LINE,VERSION,PREMIUM_SERVICES_INT,SPERRKLASSE_IMS,NAME)
VALUES (S_T_SPERRKLASSEN_0.nextVal,0,'0','0','0','0','0','0','0','0','0','0',0,'0',0,'Keine Sperre');
