-- Required for Hibernate's 'all-delete-orphan' cascade
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PORT_FORWARD TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_EG_IP TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_EG_ROUTING TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_BRAS_POOLS TO R_HURRICAN_USER;

GRANT SELECT, INSERT, UPDATE ON T_CARRIERBESTELLUNG TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_CB_VORGANG TO R_HURRICAN_USER;
