CREATE ROLE "R_PORTAL" NOT IDENTIFIED;
CREATE USER "PORTAL" PROFILE "DEFAULT" IDENTIFIED BY "portal#1" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "PORTAL";
grant R_PORTAL to PORTAL;
grant R_HURRICAN_BSI_VIEWS to PORTAL;
