--
-- GRANTs fuer die DB-Rolle 'R_REPORT_ADMIN'
--

--Rolle fuer Report-Administration anlegen
CREATE ROLE "R_REPORT_ADMIN" NOT IDENTIFIED;
GRANT INSERT , UPDATE ON t_archiv_daten TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE ON t_report TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE, DELETE ON t_report_request TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE, DELETE ON t_report_data TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE, DELETE ON t_report_template TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON T_SERVICE_COMMAND_MAPPING TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_report_2_prod TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_rep2prod_stati TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_rep2prod_techls TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_report_2_userrole TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_report_data TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_report_gruppe TO R_REPORT_ADMIN;
GRANT SELECT , UPDATE , DELETE ON T_REPORT_PAPERFORMAT TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_report_reason TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_txt_baustein TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_txt_baustein_2_gruppe TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_txt_baustein_gruppe_2_report TO R_REPORT_ADMIN;
GRANT INSERT , UPDATE , DELETE ON t_txt_baustein_gruppe TO R_REPORT_ADMIN;

