--
-- GRANTs fuer die DB-Rolle 'R_HURRICAN_TOOLS'
--

-- Rolle fuer externe Tools anlegen
CREATE ROLE "R_HURRICAN_TOOLS" NOT IDENTIFIED;
GRANT SELECT, UPDATE ON T_AUFTRAG_DATEN TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_CARRIERBESTELLUNG TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_CARRIER_CONTACT TO R_HURRICAN_TOOLS;
GRANT SELECT, INSERT, UPDATE ON T_DIALER TO R_HURRICAN_TOOLS;
GRANT SELECT, INSERT, UPDATE ON T_DSLAM TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE, INSERT ON T_DSLAM_PROFILE_CHANGE TO R_HURRICAN_TOOLS;
GRANT SELECT ON T_DSLAM_PROFILE_CHANGE_REASON TO R_HURRICAN_TOOLS;
-- TODO nur auf NAME, RANGIER_ID, RANGIER_ID_ADD, HVT_ID_STD
GRANT UPDATE ON T_ENDSTELLE TO R_HURRICAN_TOOLS;
GRANT SELECT, INSERT, UPDATE ON T_EQUIPMENT TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_INT_ACCOUNT TO R_HURRICAN_TOOLS;
GRANT SELECT, INSERT, UPDATE ON T_LEISTUNG_DN TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_LEISTUNG_4_DN TO R_HURRICAN_TOOLS;
GRANT SELECT, INSERT, UPDATE ON T_RANGIERUNG TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_SPERRE TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_VERLAUF TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_VERLAUF_ABTEILUNG TO R_HURRICAN_TOOLS;
-- TODO nur auf KOSTENSTELLE, INNENAUFTRAG
GRANT UPDATE ON T_HVT_GRUPPE TO R_HURRICAN_TOOLS;
GRANT UPDATE ON T_IA_MAT_ENTNAHME_ARTIKEL TO R_HURRICAN_TOOLS;
GRANT SELECT, UPDATE ON T_RANGIERUNGS_AUFTRAG TO R_HURRICAN_TOOLS;
GRANT SELECT ON MIG_MIGRATIONRESULT TO R_HURRICAN_TOOLS;
GRANT SELECT ON MIG_LOG TO R_HURRICAN_TOOLS;
GRANT SELECT ON MIG_AUFTRAG_MAPPING TO R_HURRICAN_TOOLS;
GRANT SELECT ON MIG_V_RESULT_ACCOUNT_TO_ORDER TO R_HURRICAN_TOOLS;
