--
-- Script mit create/grant Befehlen, um den DB-User
-- 'TOOL' anzulegen.
-- (User fuer Scripte/Tools anderer Abteilungen als IT.)
--

CREATE USER "TOOL" PROFILE "DEFAULT" IDENTIFIED BY "TOOL" 
  DEFAULT TABLESPACE "T_HURRICAN" TEMPORARY TABLESPACE "TEMPORARY" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "TOOL";
GRANT "R_HURRICAN_TOOLS" TO "TOOL";
GRANT "R_HURRICAN_READ_ONLY" TO "TOOL";
GRANT "R_HURRICAN_BSI_VIEWS" TO "TOOL";
GRANT "R_HURRICAN_HW_ADMIN" TO "TOOL";

commit;

