--
-- GRANTs fuer die DB-Rolle 'R_HURRICAN_TAIFUN_VIEWS'
-- (Rolle besitzt nur Lese-Rechte auf die fuer TAIFUN erstellte DB-Views.)
--

CREATE ROLE "R_HURRICAN_TAIFUN_VIEWS" NOT IDENTIFIED;

GRANT SELECT ON VH_H2T_SERVICE_ROOM TO R_HURRICAN_TAIFUN_VIEWS;
GRANT SELECT ON V_H2T_SERVICE_ROOM TO R_HURRICAN_TAIFUN_VIEWS;

commit;
