--
-- Script mit create/grant Befehlen, um den DB-User
-- 'HURRICANREADER' anzulegen.
-- (Datenbankbenutzer mit Leseberechtigungen auf der DB HURRICAN.)
--

CREATE USER "HURRICANREADER" PROFILE "DEFAULT" IDENTIFIED BY "nacirruh" 
  DEFAULT TABLESPACE "T_HURRICAN" TEMPORARY TABLESPACE "TEMPORARY" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HURRICANREADER";
GRANT "R_HURRICAN_READ_ONLY" TO "HURRICANREADER";

commit;

