/*
 * Resource Catalog Management
 * ## TMF API Reference: TMF634 - Resource Catalog Management  ### December 2019  Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.   ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.net.URI;

        /**
* specification of a value (number or text or an object) that can be assigned to a Characteristic.
*/
    @JsonPropertyOrder({
        CharacteristicValueSpecification.JSON_PROPERTY_IS_DEFAULT,
        CharacteristicValueSpecification.JSON_PROPERTY_RANGE_INTERVAL,
        CharacteristicValueSpecification.JSON_PROPERTY_REGEX,
        CharacteristicValueSpecification.JSON_PROPERTY_UNIT_OF_MEASURE,
        CharacteristicValueSpecification.JSON_PROPERTY_VALUE_FROM,
        CharacteristicValueSpecification.JSON_PROPERTY_VALUE_TO,
        CharacteristicValueSpecification.JSON_PROPERTY_VALUE_TYPE,
        CharacteristicValueSpecification.JSON_PROPERTY_VALID_FOR,
        CharacteristicValueSpecification.JSON_PROPERTY_VALUE,
        CharacteristicValueSpecification.JSON_PROPERTY_AT_BASE_TYPE,
        CharacteristicValueSpecification.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        CharacteristicValueSpecification.JSON_PROPERTY_AT_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class CharacteristicValueSpecification implements Serializable {
        public static final String JSON_PROPERTY_IS_DEFAULT = "isDefault";
            private Boolean isDefault;

        public static final String JSON_PROPERTY_RANGE_INTERVAL = "rangeInterval";
            private String rangeInterval;

        public static final String JSON_PROPERTY_REGEX = "regex";
            private String regex;

        public static final String JSON_PROPERTY_UNIT_OF_MEASURE = "unitOfMeasure";
            private String unitOfMeasure;

        public static final String JSON_PROPERTY_VALUE_FROM = "valueFrom";
            private Integer valueFrom;

        public static final String JSON_PROPERTY_VALUE_TO = "valueTo";
            private Integer valueTo;

        public static final String JSON_PROPERTY_VALUE_TYPE = "valueType";
            private String valueType;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_VALUE = "value";
            private Object value;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

