/*
 * Resource Catalog Management
 * ## TMF API Reference: TMF634 - Resource Catalog Management  ### December 2019  Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.   ### Operations Resource Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.rcm.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.net.URI;
import java.util.List;

        /**
* Specification for resource, service or product features
*/
    @JsonPropertyOrder({
        FeatureSpecification.JSON_PROPERTY_ID,
        FeatureSpecification.JSON_PROPERTY_HREF,
        FeatureSpecification.JSON_PROPERTY_IS_BUNDLE,
        FeatureSpecification.JSON_PROPERTY_IS_ENABLED,
        FeatureSpecification.JSON_PROPERTY_NAME,
        FeatureSpecification.JSON_PROPERTY_VERSION,
        FeatureSpecification.JSON_PROPERTY_CONSTRAINT,
        FeatureSpecification.JSON_PROPERTY_FEATURE_SPEC_CHARACTERISTIC,
        FeatureSpecification.JSON_PROPERTY_FEATURE_SPEC_RELATIONSHIP,
        FeatureSpecification.JSON_PROPERTY_VALID_FOR,
        FeatureSpecification.JSON_PROPERTY_AT_BASE_TYPE,
        FeatureSpecification.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        FeatureSpecification.JSON_PROPERTY_AT_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class FeatureSpecification implements Serializable {
        public static final String JSON_PROPERTY_ID = "id";
            private String id;

        public static final String JSON_PROPERTY_HREF = "href";
            private URI href;

        public static final String JSON_PROPERTY_IS_BUNDLE = "isBundle";
            private Boolean isBundle;

        public static final String JSON_PROPERTY_IS_ENABLED = "isEnabled";
            private Boolean isEnabled;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_VERSION = "version";
            private String version;

        public static final String JSON_PROPERTY_CONSTRAINT = "constraint";
            private List<ConstraintRef> constraint;

        public static final String JSON_PROPERTY_FEATURE_SPEC_CHARACTERISTIC = "featureSpecCharacteristic";
            private List<FeatureSpecificationCharacteristic> featureSpecCharacteristic;

        public static final String JSON_PROPERTY_FEATURE_SPEC_RELATIONSHIP = "featureSpecRelationship";
            private List<FeatureSpecificationRelationship> featureSpecRelationship;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

