INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE) 
    VALUES (71,'Anbieterwechsel §46TKG Änderung',1,'1','0',null,'1',14001);
-- config von 'Änderung des Routings' kopieren 
insert into T_BA_VERL_CONFIG (ID, ANLASS, PROD_ID, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, AUTO_VERTEILEN, CPS_NECESSARY)
      (select S_T_BA_VERL_CONFIG_0.nextVal, 71, c2.PROD_ID, c2.ABT_CONFIG_ID, c2.GUELTIG_VON, c2.GUELTIG_BIS, sysdate, 'dbscript', c2.AUTO_VERTEILEN, c2.CPS_NECESSARY 
       from T_BA_VERL_CONFIG c2 where c2.GUELTIG_BIS >= sysdate AND c2.ANLASS = 9);
    
INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE) 
    VALUES (72,'Anbieterwechsel §46TKG Neuschaltung',1,'0','1',110,'1',14000);
-- config von 'Neuschaltung' kopieren 
insert into T_BA_VERL_CONFIG (ID, ANLASS, PROD_ID, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, AUTO_VERTEILEN, CPS_NECESSARY)
      (select S_T_BA_VERL_CONFIG_0.nextVal, 72, c2.PROD_ID, c2.ABT_CONFIG_ID, c2.GUELTIG_VON, c2.GUELTIG_BIS, sysdate, 'dbscript', c2.AUTO_VERTEILEN, c2.CPS_NECESSARY 
       from T_BA_VERL_CONFIG c2 where c2.GUELTIG_BIS >= sysdate AND c2.ANLASS = 27);
