spring:
  application:
    name: agreement-management
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}
  cloud:
    config:
      uri: ${CONFIG_SERVER:http://localhost:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
