spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adlatus
    username: adlatus
    password: adlatusPass
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/postgresql/changelog-postgresql.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
hub:
  eventRegistrationService: EventRegistrationServiceJpa
