-- TDN -> VBZ in T_REFERENCE

UPDATE   T_REFERENCE r
   SET   R.TYPE = 'VBZ_TYPE'
 WHERE   R.TYPE = 'TDN_TYPE'
/

UPDATE   T_REFERENCE r
   SET   R.TYPE = 'VBZ_PRODUCT'
 WHERE   R.TYPE = 'TDN_PRODUCT'
/
