UPDATE T_BA_ABT_CONFIG SET NAME = REGEXP_REPLACE(NAME, '(.*)SCV(.*)', '\1AM\2');

UPDATE T_BA_ABT_CONFIG SET NAME = REGEXP_REPLACE(NAME, '(.*)SCT(.*)', '\1FieldService\2');

UPDATE T_BA_ABT_CONFIG SET NAME = REGEXP_REPLACE(NAME, '(.*)EWSD(.*)', '\1ST Voice\2');

UPDATE T_BA_ABT_CONFIG SET NAME = REGEXP_REPLACE(NAME, '(.*)SDH(.*)', '\1ST Connect\2');

UPDATE T_BA_ABT_CONFIG SET NAME = REGEXP_REPLACE(NAME, '(.*)IPS(.*)', '\1ST Online\2');
