-- Korrektur der FFM_PLANED_DURATION für RTL_NEU an FTTC_KVZ: von 45 auf 90 Minuten
UPDATE T_FFM_PRODUCT_MAPPING SET FFM_PLANNED_DURATION = 90
  WHERE STANDORT_TYP = 11013
    AND lower(FFM_ACTIVITY_TYPE) LIKE 'rtl_neu%'
    AND FFM_PLANNED_DURATION = 45;
