Insert into T_KUENDIGUNG_FRIST
   (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF,
    VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION, VERSION, AUTO_VERLAENGERUNG)
 Values
   (S_T_KUENDIGUNG_FRIST_0.nextVal, 98, '0', 6, 'EINGANGSDATUM',
    2009, 4, '6 Wochen ab Eingangsdatum', 0, 0);
Insert into T_KUENDIGUNG_FRIST
   (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF,
    VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION, VERSION, AUTO_VERLAENGERUNG)
 Values
   (S_T_KUENDIGUNG_FRIST_0.nextVal, 47, '1', 12, 'ENDE_MVLZ',
    2008, 4, '3 Monate zum Ende der MVLZ', 0, 12);
