-- Standorttyp 'KVZ' korrigieren (doppelten RTL_Entstoerung Eintrag entfernen)
delete from T_FFM_PRODUCT_MAPPING where STANDORT_TYP=11001 and FFM_ACTIVITY_TYPE='RTL_Entstoerung';
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11001, 'RTL_Entstoerung', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG');


-- Eintraege fuer Standorttyp 'GEWOFAG' anlegen - analog zu HVT
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11009, 'RTL_Neu_MK_HVT', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'NEU');
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11009, 'RTL_Entstoerung', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG');
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11009, 'RTL_Kuendigung', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'KUENDIGUNG');


Insert into T_FFM_QUALIFICATION_MAPPING
   (ID, QUALIFICATION_ID, STANDORT_REF_ID, VERSION)
 Values
   (S_T_FFM_QUAL_MAPPING_0.nextVal,
     (select q.ID from T_FFM_QUALIFICATION q where q.QUALIFICATION='Endkundenservice GEWOFAG'),
   11009, 0);

