alter table T_FFM_QUALIFICATION_MAPPING add VPN CHAR(1);

ALTER TABLE T_FFM_QUALIFICATION_MAPPING drop constraint CK_FFM_QUALMAP_IDS;
ALTER TABLE T_FFM_QUALIFICATION_MAPPING ADD (
  CONSTRAINT CK_FFM_QUALMAP_IDS
  CHECK (
     (PRODUCT_ID IS NOT NULL AND TECH_LEISTUNG_ID IS NULL and STANDORT_REF_ID IS NULL and VPN is null)
  OR (TECH_LEISTUNG_ID IS NOT NULL AND PRODUCT_ID IS NULL AND STANDORT_REF_ID IS NULL and VPN is null)
  OR (STANDORT_REF_ID IS NOT NULL AND PRODUCT_ID IS NULL AND TECH_LEISTUNG_ID IS NULL and VPN is null)
  OR (VPN IS NOT NULL AND PRODUCT_ID IS NULL AND TECH_LEISTUNG_ID IS NULL AND STANDORT_REF_ID IS NULL))
);

insert into T_FFM_QUALIFICATION_MAPPING (ID, QUALIFICATION_ID, VPN, VERSION)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 1, '1', 0);
