DROP SEQUENCE S_T_CB_VORGANG_CARRIERREFNR_0;

CREATE SEQUENCE S_T_CB_VORGANG_CARRIERREFNR_0
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

GRANT SELECT ON S_T_CB_VORGANG_CARRIERREFNR_0 TO PUBLIC;
