-- Umsetzung im Rahmen von OR-Release ANF-722
-- TV Signallieferung MV für FFM konfigurieren
Insert into T_FFM_PRODUCT_MAPPING
 (ID, VERSION, PROD_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 select S_T_FFM_PRODUCT_MAPPING_0.nextval, 0, 522, 'RTL_sonstige', 60,
  'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'NEU'
  from dual where not exists (select * from T_FFM_PRODUCT_MAPPING where PROD_ID = 522 and FFM_ACTIVITY_TYPE = 'RTL_sonstige')
  ;

Insert into T_FFM_PRODUCT_MAPPING
 (ID, VERSION, PROD_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 select S_T_FFM_PRODUCT_MAPPING_0.nextval, 0, 522, 'RTL_Kuendigung', 30,
  'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'KUENDIGUNG'
  from dual where not exists (select * from T_FFM_PRODUCT_MAPPING where PROD_ID = 522 and FFM_ACTIVITY_TYPE = 'RTL_Kuendigung')
  ;

Insert into T_FFM_PRODUCT_MAPPING
 (ID, VERSION, PROD_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY, BA_FFM_TYP)
 select S_T_FFM_PRODUCT_MAPPING_0.nextval, 0, 522, 'RTL_Entstoerung', 90,
  'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT', 'ENTSTOERUNG'
  from dual where not exists (select * from T_FFM_PRODUCT_MAPPING where PROD_ID = 522 and FFM_ACTIVITY_TYPE = 'RTL_Entstoerung')
  ;
