ALTER TABLE T_HW_BAUGRUPPEN_TYP ADD TUNNELING VARCHAR2(6) CHECK (TUNNELING IN ('VLAN', 'CC'));

INSERT INTO T_HW_BAUGRUPPEN_TYP
(ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH)
  VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'NGLT-A', 8, 'ALU GPON-Karte für FTTC-DSLAM', 1, null, null, 6, 0, 100000)
;
