-- Add WITA_VERSION to T_MWF_REQUEST and T_MWF_MELDUNG tables

alter table T_MWF_REQUEST add (WITA_VERSION varchar2(2));
update T_MWF_REQUEST set WITA_VERSION = '4';
ALTER TABLE T_MWF_REQUEST MODIFY (WITA_VERSION NOT NULL);

alter table T_MWF_MELDUNG add (WITA_VERSION varchar2(2));
update T_MWF_MELDUNG set WITA_VERSION = '4';
ALTER TABLE T_MWF_MELDUNG MODIFY (WITA_VERSION NOT NULL);
