-- Add Zeitfenster to T_MWF_REQUEST tables
ALTER TABLE T_MWF_REQUEST ADD (TIME_SLOT varchar2(6));
ALTER TABLE T_MWF_REQUEST ADD
  CONSTRAINT T_MWF_REQUEST_TIME_SLOT
  CHECK (TIME_SLOT in ('SLOT_1','SLOT_2','SLOT_3','SLOT_4','SLOT_6','SLOT_7'));
