-- WBCI Model Schema
--  contains only the DB schema for the VA Anfrage use case. The other tables will be added in subsequent sprints

CREATE TABLE T_WBCI_GESCHAEFTSFALL (TYP VARCHAR2(31 CHAR) NOT NULL, id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), abgebenderEKP VARCHAR2(255 CHAR), absender VARCHAR2(255 CHAR), aufnehmenderEKP VARCHAR2(255 CHAR), kundenwunschtermin RAW(255), vorabstimmungsId VARCHAR2(255 CHAR), wbciVersion VARCHAR2(255 CHAR), ENDKUNDE_ID NUMBER(19, 0), PROJECT_ID NUMBER(19, 0), STANDORT_ID NUMBER(19, 0), RUFNUMMERPORTIERUNG_ID NUMBER(19, 0), ANSCHLUSSIDENTIFIKATION_ID NUMBER(19, 0), PRIMARY KEY (id));
CREATE TABLE T_WBCI_GESCHAFTSFALL_ANSCHLUSS (GESCHAEFTSFALL_ID NUMBER(19, 0) NOT NULL, ANSCHLUSS_ID NUMBER(19, 0) NOT NULL, UNIQUE (ANSCHLUSS_ID));
CREATE TABLE T_WBCI_PERSON_ODER_FIRMA (typ VARCHAR2(31 CHAR) NOT NULL, id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), anrede VARCHAR2(255 CHAR), firmenname VARCHAR2(255 CHAR), firmennamenZusatz VARCHAR2(255 CHAR), nachname VARCHAR2(255 CHAR), vorname VARCHAR2(255 CHAR), PRIMARY KEY (id));
CREATE TABLE T_WBCI_PROJEKT (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), kopplungsKenner VARCHAR2(255 CHAR), projektKenner VARCHAR2(255 CHAR), PRIMARY KEY (id));
CREATE TABLE T_WBCI_REQUEST (TYP VARCHAR2(31 CHAR) NOT NULL, id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), CREATION_DATE TIMESTAMP NOT NULL, SENT_AT TIMESTAMP, wbciGeschaeftsfall_id NUMBER(19, 0), PRIMARY KEY (id));
CREATE TABLE T_WBCI_RUFNUMMERNBLOCK (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), rnrBlockBis VARCHAR2(255 CHAR), rnrBlockVon VARCHAR2(255 CHAR), RUFNUMMER_BLOCK_ID NUMBER(19, 0) NOT NULL, PRIMARY KEY (id));
CREATE TABLE T_WBCI_RUFNUMMERPORTIERUNG (TYP VARCHAR2(31 CHAR) NOT NULL, id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), portierungszeitfenster VARCHAR2(255 CHAR), abfragestelle VARCHAR2(255 CHAR), durchwahlnummer VARCHAR2(255 CHAR), onkz VARCHAR2(255 CHAR), alleRufnummernPortieren NUMBER(1, 0), PRIMARY KEY (id));
CREATE TABLE T_WBCI_RUFNUMMER_ONKZ (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), onkz VARCHAR2(255 CHAR), rufnummer VARCHAR2(255 CHAR), RUFNUMMER_ONKZ_ID NUMBER(19, 0) NOT NULL, PRIMARY KEY (id));
CREATE TABLE T_WBCI_STANDORT (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), ort VARCHAR2(255 CHAR), postleitzahl VARCHAR2(255 CHAR), hausnummer VARCHAR2(255 CHAR), hausnummernZusatz VARCHAR2(255 CHAR), strassenname VARCHAR2(255 CHAR), PRIMARY KEY (id));

ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD CONSTRAINT FK3A3A4DA5DD0595A1 FOREIGN KEY (PROJECT_ID) REFERENCES T_WBCI_PROJEKT;
ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD CONSTRAINT FK3A3A4DA55C16E2B FOREIGN KEY (ENDKUNDE_ID) REFERENCES T_WBCI_PERSON_ODER_FIRMA;
ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD CONSTRAINT FK3A3A4DA55557902B FOREIGN KEY (RUFNUMMERPORTIERUNG_ID) REFERENCES T_WBCI_RUFNUMMERPORTIERUNG;
ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD CONSTRAINT FK3A3A4DA5CF712974 FOREIGN KEY (ANSCHLUSSIDENTIFIKATION_ID) REFERENCES T_WBCI_RUFNUMMER_ONKZ;
ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD CONSTRAINT FK3A3A4DA557F9FC2B FOREIGN KEY (STANDORT_ID) REFERENCES T_WBCI_STANDORT;
ALTER TABLE T_WBCI_GESCHAFTSFALL_ANSCHLUSS ADD CONSTRAINT FKBC7E298BA641EC5C FOREIGN KEY (GESCHAEFTSFALL_ID) REFERENCES T_WBCI_GESCHAEFTSFALL;
ALTER TABLE T_WBCI_GESCHAFTSFALL_ANSCHLUSS ADD CONSTRAINT FKBC7E298B565634C1 FOREIGN KEY (ANSCHLUSS_ID) REFERENCES T_WBCI_PERSON_ODER_FIRMA;
ALTER TABLE T_WBCI_REQUEST ADD CONSTRAINT FKCF2142AC5609A80B FOREIGN KEY (wbciGeschaeftsfall_id) REFERENCES T_WBCI_GESCHAEFTSFALL;
ALTER TABLE T_WBCI_RUFNUMMERNBLOCK ADD CONSTRAINT FKA1CFF932E07BD36 FOREIGN KEY (RUFNUMMER_BLOCK_ID) REFERENCES T_WBCI_RUFNUMMERPORTIERUNG;
ALTER TABLE T_WBCI_RUFNUMMER_ONKZ ADD CONSTRAINT FK3B1777391621EB5A FOREIGN KEY (RUFNUMMER_ONKZ_ID) REFERENCES T_WBCI_RUFNUMMERPORTIERUNG;

GRANT SELECT, INSERT, UPDATE ON T_WBCI_GESCHAEFTSFALL TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_GESCHAFTSFALL_ANSCHLUSS TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_PERSON_ODER_FIRMA TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_PROJEKT TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_REQUEST TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_RUFNUMMERNBLOCK TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_RUFNUMMERPORTIERUNG TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_RUFNUMMER_ONKZ TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_STANDORT TO R_HURRICAN_USER;

GRANT SELECT ON T_WBCI_GESCHAEFTSFALL TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_GESCHAFTSFALL_ANSCHLUSS TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_PERSON_ODER_FIRMA TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_PROJEKT TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_REQUEST TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_RUFNUMMERNBLOCK TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_RUFNUMMERPORTIERUNG TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_RUFNUMMER_ONKZ TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_STANDORT TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_GESCHAEFTSFALL_0;
CREATE SEQUENCE S_T_WBCI_PERSON_ODER_FIRMA_0;
CREATE SEQUENCE S_T_WBCI_PROJEKT_0;
CREATE SEQUENCE S_T_WBCI_REQUEST_0;
CREATE SEQUENCE S_T_WBCI_RUFNUMMERNBLOCK_0;
CREATE SEQUENCE S_T_WBCI_RUFNUMMERPORTIERUNG_0;
CREATE SEQUENCE S_T_WBCI_RUFNUMMER_0;
CREATE SEQUENCE S_T_WBCI_STANDORT_0;

GRANT SELECT ON S_T_WBCI_GESCHAEFTSFALL_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_PERSON_ODER_FIRMA_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_PROJEKT_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_REQUEST_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_RUFNUMMERNBLOCK_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_RUFNUMMERPORTIERUNG_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_RUFNUMMER_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_STANDORT_0 TO PUBLIC;

