CREATE TABLE T_WBCI_RNP_EINZELN_RN_ONKZ (RNP_EINZELN_ID NUMBER(19, 0) NOT NULL, RUFNUMMER_ONKZ_ID NUMBER(19, 0) NOT NULL, UNIQUE (RUFNUMMER_ONKZ_ID));
ALTER TABLE T_WBCI_RNP_EINZELN_RN_ONKZ ADD CONSTRAINT FK_RNP_EINZELN_ID FOREIGN KEY (RNP_EINZELN_ID) REFERENCES T_WBCI_RUFNUMMERPORTIERUNG;
ALTER TABLE T_WBCI_RNP_EINZELN_RN_ONKZ ADD CONSTRAINT FK_RUFNUMMER_ONKZ_ID FOREIGN KEY (RUFNUMMER_ONKZ_ID) REFERENCES T_WBCI_RUFNUMMER_ONKZ;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_RNP_EINZELN_RN_ONKZ TO R_HURRICAN_USER;
GRANT SELECT ON T_WBCI_RNP_EINZELN_RN_ONKZ TO R_HURRICAN_READ_ONLY;

ALTER TABLE T_WBCI_RUFNUMMER_ONKZ DROP COLUMN RUFNUMMER_ONKZ_ID;
