-- add new column IO_SOURCE to indicate the origin of the record: WITA or WBCI Fassade

ALTER TABLE T_IO_ARCHIVE ADD (IO_SOURCE VARCHAR2(10));
UPDATE T_IO_ARCHIVE set IO_SOURCE = 'WITA';
ALTER TABLE T_IO_ARCHIVE MODIFY (IO_SOURCE NOT NULL ENABLE NOVALIDATE);