-- add new WBCI Request Geschaeftsfaelle to CK_IO_ARCHIVE_GF check constraint

ALTER TABLE T_IO_ARCHIVE DROP CONSTRAINT CK_IO_ARCHIVE_GF;

ALTER TABLE T_IO_ARCHIVE
ADD CONSTRAINT CK_IO_ARCHIVE_GF
CHECK (REQUEST_GESCHAEFTSFALL IN (
    'BEREITSTELLUNG',
    'BESTANDSUEBERSICHT',
    'KUENDIGUNG_KUNDE',
    'KUENDIGUNG_TELEKOM',
    'LEISTUNGSMERKMAL_AENDERUNG',
    'LEISTUNGS_AENDERUNG',
    'PORTWECHSEL',
    'PRODUKTGRUPPENWECHSEL',
    'PROVIDERWECHSEL',
    'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG',
    'VERBUNDLEISTUNG',
    'UNBEKANNT',
    'VA_KUE_MRN',
    'VA_KUE_ORN',
    'VA_RRNP',
    'VA_UNBEKANNT'
  )) ENABLE NOVALIDATE;