ALTER TABLE T_FTTX_CVLAN
 ADD (VLAN_VALUE_NUM  NUMBER(10));

ALTER TABLE T_FTTX_CVLAN
 ADD (PBIT_LIMIT_NUM  NUMBER(10));

UPDATE   T_FTTX_CVLAN C
   SET   C.VLAN_VALUE_NUM = C.VLAN_VALUE;

UPDATE   T_FTTX_CVLAN C
   SET   C.PBIT_LIMIT_NUM = C.PBIT_LIMIT;

ALTER TABLE T_FTTX_CVLAN DROP COLUMN VLAN_VALUE;

ALTER TABLE T_FTTX_CVLAN
RENAME COLUMN VLAN_VALUE_NUM TO VLAN_VALUE;

ALTER TABLE T_FTTX_CVLAN
MODIFY(VLAN_VALUE  NOT NULL);

ALTER TABLE T_FTTX_CVLAN DROP COLUMN PBIT_LIMIT;

ALTER TABLE T_FTTX_CVLAN
RENAME COLUMN PBIT_LIMIT_NUM TO PBIT_LIMIT;