ALTER TABLE T_FTTX_CVLAN
 DROP CONSTRAINT CONSTR_CVLAN_TYP;

UPDATE T_FTTX_CVLAN SET TYP = 'MC'
WHERE TYP = 'TV';

alter table T_FTTX_CVLAN add constraint CONSTR_CVLAN_TYP check (TYP in ('HSI', 'HSIPLUS', 'VOIP', 'POTS', 'IAD', 'MC', 'VOD'));
