delete from T_DB_QUERIES where ID in (24,25,26,27);

Insert into T_DB_QUERIES
   (ID, NAME, DESCRIPTION, SERVICE, SQL_QUERY,
    PARAMS, VERSION)
 Values
   (24, 'PK Servicelevel ueberschritten', 'Ermittelt Privatkunden Auftraege, deren Service-Level überschritten ist', 'BILLING',
   'SELECT A.EINGANGS_ZEIT, C.NAME||'', ''||C.FIRSTNAME AS KUNDENNAME, R.NAME||'' ''||R.FIRSTNAME AS NIEDERLASSUNG,
    OE.NAME AS PRODUKT, P.USERNAME AS BEARBEITER, A.VALID_FROM, A.AUFTRAG__NO, S.NAME AS STATUS, JA.NOTES AS BEMERKUNG
    FROM AUFTRAG A
    LEFT JOIN CUSTOMER C ON C.CUST_NO = A.CUST_NO
    LEFT JOIN CUSTOMER R ON R.CUST_NO = C.RESELLER_CUST_NO
    LEFT JOIN OE ON OE.OE__NO = A.OE__NO
    LEFT JOIN PERSON P ON P.PERSON_NO = A.BEARBEITER_NO
    LEFT JOIN AUFTRAGSTATUS S ON S.ASTATUS = A.ASTATUS
    LEFT JOIN TRF_JOURNAL_AUFTRAG JA ON (JA.AUFTRAG__NO = A.AUFTRAG__NO AND JA.TYPE_UID = 1002480 AND JA.REASON_UID = 270203875)
    WHERE A.EINGANGS_ZEIT + 42 < SYSDATE
    AND A.ASTATUS NOT IN (5, 7, 8, 31, 41)
    AND A.HIST_STATUS = ''NEU''
    AND C.CUSTOMER_TYPE = ''PRIVAT''
    AND OE.HIST_STATUS = ''AKT''',
    NULL, 0);

Insert into T_DB_QUERIES
   (ID, NAME, DESCRIPTION, SERVICE, SQL_QUERY,
    PARAMS, VERSION)
 Values
   (25, 'PK Servicelevel kritisch', 'Ermittelt Privatkunden Auftraege, deren Service-Level kritisch ist', 'BILLING',
   'SELECT A.EINGANGS_ZEIT, C.NAME||'', ''||C.FIRSTNAME AS KUNDENNAME, R.NAME||'' ''||R.FIRSTNAME AS NIEDERLASSUNG,
    OE.NAME AS PRODUKT, P.USERNAME AS BEARBEITER, A.VALID_FROM, A.AUFTRAG__NO, S.NAME AS STATUS, JA.NOTES AS BEMERKUNG
    FROM AUFTRAG A
    LEFT JOIN CUSTOMER C ON C.CUST_NO = A.CUST_NO
    LEFT JOIN CUSTOMER R ON R.CUST_NO = C.RESELLER_CUST_NO
    LEFT JOIN OE ON OE.OE__NO = A.OE__NO
    LEFT JOIN PERSON P ON P.PERSON_NO = A.BEARBEITER_NO
    LEFT JOIN AUFTRAGSTATUS S ON S.ASTATUS = A.ASTATUS
    LEFT JOIN TRF_JOURNAL_AUFTRAG JA ON (JA.AUFTRAG__NO = A.AUFTRAG__NO AND JA.TYPE_UID = 1002480 AND JA.REASON_UID = 270203875)
    WHERE A.EINGANGS_ZEIT + 28 < SYSDATE
    AND A.ASTATUS NOT IN (5, 7, 8, 31, 41)
    AND A.HIST_STATUS = ''NEU''
    AND C.CUSTOMER_TYPE = ''PRIVAT''
    AND OE.HIST_STATUS = ''AKT''',
    NULL, 0);

Insert into T_DB_QUERIES
   (ID, NAME, DESCRIPTION, SERVICE, SQL_QUERY,
    PARAMS, VERSION)
 Values
   (26, 'GK Servicelevel ueberschritten', 'Ermittelt Geschaeftskunden Auftraege, deren Service-Level ueberschritten ist', 'BILLING',
   'SELECT A.EINGANGS_ZEIT, C.NAME||'' ''||C.FIRSTNAME AS KUNDENNAME, R.NAME||'' ''||R.FIRSTNAME AS NIEDERLASSUNG,
    OE.NAME AS PRODUKT, P.USERNAME AS BEARBEITER, A.VALID_FROM, A.AUFTRAG__NO, S.NAME AS STATUS, JA.NOTES AS BEMERKUNG
    FROM AUFTRAG A
    LEFT JOIN CUSTOMER C ON C.CUST_NO = A.CUST_NO
    LEFT JOIN CUSTOMER R ON R.CUST_NO = C.RESELLER_CUST_NO
    LEFT JOIN OE ON OE.OE__NO = A.OE__NO
    LEFT JOIN PERSON P ON P.PERSON_NO = A.BEARBEITER_NO
    LEFT JOIN AUFTRAGSTATUS S ON S.ASTATUS = A.ASTATUS
    LEFT JOIN TRF_JOURNAL_AUFTRAG JA ON (JA.AUFTRAG__NO = A.AUFTRAG__NO AND JA.TYPE_UID = 1002480 AND JA.REASON_UID = 270203875)
    WHERE A.EINGANGS_ZEIT + 35 < SYSDATE
    AND A.ASTATUS NOT IN (5, 7, 8, 31, 41)
    AND A.HIST_STATUS = ''NEU''
    AND C.CUSTOMER_TYPE = ''GEWERBLICH''
    AND OE.HIST_STATUS = ''AKT''',
    NULL, 0);

Insert into T_DB_QUERIES
   (ID, NAME, DESCRIPTION, SERVICE, SQL_QUERY,
    PARAMS, VERSION)
 Values
   (27, 'GK Servicelevel kritisch', 'Ermittelt Geschaeftskunden Auftraege, deren Service-Level kritisch ist', 'BILLING',
   'SELECT A.EINGANGS_ZEIT, C.NAME||'' ''||C.FIRSTNAME AS KUNDENNAME, R.NAME||'' ''||R.FIRSTNAME AS NIEDERLASSUNG,
    OE.NAME AS PRODUKT, P.USERNAME AS BEARBEITER, A.VALID_FROM, A.AUFTRAG__NO, S.NAME AS STATUS, JA.NOTES AS BEMERKUNG
    FROM AUFTRAG A
    LEFT JOIN CUSTOMER C ON C.CUST_NO = A.CUST_NO
    LEFT JOIN CUSTOMER R ON R.CUST_NO = C.RESELLER_CUST_NO
    LEFT JOIN OE ON OE.OE__NO = A.OE__NO
    LEFT JOIN PERSON P ON P.PERSON_NO = A.BEARBEITER_NO
    LEFT JOIN AUFTRAGSTATUS S ON S.ASTATUS = A.ASTATUS
    LEFT JOIN TRF_JOURNAL_AUFTRAG JA ON (JA.AUFTRAG__NO = A.AUFTRAG__NO AND JA.TYPE_UID = 1002480 AND JA.REASON_UID = 270203875)
    WHERE A.EINGANGS_ZEIT + 21 < SYSDATE
    AND A.ASTATUS NOT IN (5, 7, 8, 31, 41)
    AND A.HIST_STATUS = ''NEU''
    AND C.CUSTOMER_TYPE = ''GEWERBLICH''
    AND OE.HIST_STATUS = ''AKT''',
    NULL, 0);
