--
-- Initilaisierungsscript fuer die Authentication-Datenbank.
-- Setzt die Rollen, die GUI-Komponenten und die zugehoerigen Rollen-Verhalten.
--

-- Rollen setzen
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (1, 'hurrican.ADMIN', 'Rolle besitzt Administrator-Rechte', 1, 1);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (8, 'default.reader', 'Rolle für Benutzer, die folgende Daten sehen dürfen: <br>\n- Aufträge (inkl. VPN)<br>\n- HVTs<br>', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (9, 'auftrag.bearbeiter', 'Rolle für Benutzer, die Aufträge anlegen\nund ändern dürfen. <br>\nDabei handelt es sich sowohl um Standard-Auftr.\nals auch um VPN-Aufträge', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (10, 'auftrag.bearbeiter.sdhphysik', 'Rolle für Benutzer, die die SDH-Physik\nzu einem Auftrag anlegen/ändern dürfen.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (11, 'auftrag.bearbeiter.inhouse', 'Rolle für Benutzer, die die Inhouse-Daten zu einem\nAuftrag anlegen/ändern dürfen.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (12, 'faktura.reader', 'Rolle für Benutzer, die die Faktura-Daten <br>\nlesen dürfen. <br>\nZu den Faktura-Daten zählen auch die Daten <br>\nvon EQ-Housing.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (13, 'faktura.bearbeiter', 'Rolle für Benutzer, die die Faktura-Daten <br>\nbearbeiten dürfen. <br>\nZu den Faktura-Daten zählen auch die Daten <br>\nvon EQ-Housing.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (14, 'admin.rangierung', 'Rolle hat folgende Berechtigungen: <br>\n - Rangierungsmatrix bearbeiten <br>\n - Rangierungen freigeben', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (15, 'admin.hvt', 'Rollenrechte: <br>\n - HVTs bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (16, 'admin.produkt', 'Rollenrechte: <br>\n - Produkte bearbeiten / konfigurieren', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (17, 'admin.sperre', 'Rollenrechte: <br>\n - Sperr-Benachrichtigungen konfigurieren', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (18, 'sperre.ersteller', 'Rollenrechte: <br>\n - Sperren einrichten\n - Entsperren', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (19, 'sperre.bearbeiter', 'Rollenrechte: <br>\n - bestehende Sperr-Einträge bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (20, 'verlauf.view', 'Rollenrechte: <br>\n - Anzeige ALLER Bauaufträge/Projektierungen', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (21, 'verlauf.konfig', 'Rollenrechte: <br>\n - Konfiguration der autom. Verlaufs-Verteilung', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (22, 'verlauf.dispo', 'Rollenrechte: <br>\n - Bauaufträge/Proj. von Dispo bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (23, 'verlauf.scv', 'Rollenrechte:  <br>\n - Bauaufträge/Proj. von SCV bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (24, 'verlauf.sct', 'Rollenrechte: <br>\n - Bauaufträge/Proj. von SCT bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (25, 'verlauf.ewsd', 'Rollenrechte: <br>\n - Bauaufträge/Proj. von EWSD bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (26, 'verlauf.sdh', 'Rollenrechte: <br>\n - Bauaufträge/Proj. von SDH bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (27, 'verlauf.np', 'Rollenrechte: <br>\n - Bauaufträge/Proj. von NP bearbeiten', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (28, 'verlauf.ips', 'Rollenrechte: <br>\n - Bauaufträge/Proj. von IPS bearbeiten <br>', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (29, 'verlauf.ersteller', 'Rollenrechte: <br>\n - Bauaufträge und <br>\n - Projektierungen <br>\nerstellen.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (30, 'auftrag.bearbeiter.vpn', 'Rollenrechte:<br>\n - VPN-Aufträge bearbeiten.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (31, 'account.password.viewer', 'Rollenrechte:<br>\n - Account-Passwoerter ansehen.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (32, 'hvt.ueberwachung', 'Rollenrechte:<br>\n - HVT-Bestellungen<br>\n - Stift-Vergabe.', 1, 0);
INSERT INTO role (ID, NAME, DESCRIPTION, APP_ID, IS_ADMIN) VALUES (33, 'kubena', 'Rollenrechte:<br>\n - Erstellen u. Bearbeiten der Kubena', 1, 0);

-- GUI-Komponenten setzen
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (1, 'open.auftrag.search.frame.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'TButton,MenuItem', 'Toolbar-Button und MenuItem,\num die Kunden- und \nAuftrags- Suchmaske \nzu öffnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (2, 'open.hvt.search.frame.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'TButton,MenuItem', 'Toolbar-Button und MenuItem,\num die HVT-Suchmaske zu \nöffnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (3, 'open.vpn.uebersicht.frame.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Toolbar.Button', 'Toolbar-Button, um die\nVPN-Aufträge anzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (4, 'open.test.frame', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Toolbar.Button', 'Test-Button in der\nToolbar.\nNur f. Admins sichtbar!', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (5, 'menu.search', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für die unterschiedlichen\nSuch-Masken.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (8, 'menu.vpn', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu f. die VPN-Aktionen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (10, 'menu.faktura', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu f. die Faktura-Einträge', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (11, 'open.faktura.frame.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um das Frame\nfür das Durchführen der\nFakturierung zu öffnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (12, 'faktura.zahlungsart.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um eine\nÜbersicht über die Zahlungs-\narten bei den Faktura-Aufträgen\nzu erhalten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (13, 'faktura.kontrolle.kennzeichnung.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem zur Kontrolle\nder Rechnungs-Kennzeichnungen\nbei Faktura-Aufträgen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (14, 'menu.eq.housing', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für die EQ-Housing\nAktionen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (15, 'eq.housing.uebersicht.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für eine\nÜbersicht der aktuellen\nEQ-Housing Aufträge.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (16, 'eq.housing.erfassen.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um einen neuen\nEQ-Housing Auftrag zu\nerfassen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (17, 'menu.el.verlauf', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für den el. Verlauf.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (18, 'open.auftrags.vorlauf.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige\naller noch nicht realisierten\nAufträge.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (19, 'open.scv.auftraege.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige\naller noch nicht vollständigen\nAufträge.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (20, 'open.ba.verteilung.neuanlage.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Konfiguration\nder Bauauftrags-Verteilung\nbei Auftrags-Neuanlagen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (21, 'open.ba.verteilung.aenderung.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Konfiguration\nder Bauaufträge bei\nAuftrags-Änderungen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (22, 'open.ba.verlauf.dispo.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige\nder Bauaufträge f. DISPO.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (23, 'open.ba.verlauf.sdh.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, für die Anzeige \nder Bauaufträge f. SDH.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (24, 'open.ba.verlauf.ewsd.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Bauaufträge EWSD.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (25, 'open.ba.verlauf.sct.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Bauaufträge SCT (A.)', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (26, 'open.ba.verlauf.sctk.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Bauaufträge SCT (K)', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (27, 'open.ba.verlauf.ips.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Bauaufträge IPS.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (28, 'open.ba.verlauf.dispo.rl.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Bauauftrags-Rückläufer \nDISPO.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (29, 'open.ba.verlauf.scv.rl.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Bauauftrags-Rückläufer \nSCV.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (30, 'menu.bauauftraege', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Sub-Menu f. die MenuItems\nder Bauaufträge.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (31, 'menu.verlauf.konfig', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Sub-Menu für die \nKonfiguration der\nBauauftrags-Verteilung.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (32, 'menu.projektierung', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Sub-Menu für die MenuItems \nder Projektierungen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (33, 'open.projektierung.dispo.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen DISPO.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (34, 'open.projektierung.np.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen \nNetzplanung (NP).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (35, 'open.projektierung.sdh.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen SDH.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (36, 'open.projektierung.ewsd.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen EWSD.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (37, 'open.projektierung.sct.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen SCT.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (38, 'open.projektierung.sctk.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen SCT (K).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (39, 'open.projektierung.ips.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungen IPS.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (40, 'open.projektierung.dispo.rl.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungs-RL \nvon DISPO.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (41, 'open.projektierung.scv.rl.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Anzeige \nder Projektierungs-RL \nvon SCV.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (42, 'save', 'de.augustakom.hurrican.gui.verlauf.BAVerlaufNeuZusatzDialog', 'Button', 'Button (Save), um bei der\nBauauftrags-Konfiguration \neine zus. Abteilung hinzu-\nzufügen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (43, 'add', 'de.augustakom.hurrican.gui.verlauf.BAVerlaufNeuZusatzPanel', 'Button', 'Button, um zu einer \nBA-Verteilungs-Konfiguration \neine zus. Abteilung hinzuzu-\nfügen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (44, 'delete', 'de.augustakom.hurrican.gui.verlauf.BAVerlaufNeuZusatzPanel', 'Button', 'Button, um einen BA-\nKonfigurationszusatz zu \nlöschen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (45, 'ra.new', 'de.augustakom.hurrican.gui.shared.RaBvPanel', 'Button', 'Button (New), um eine\nneue Rechnungsanschrift\nanzulegen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (46, 'ra.save', 'de.augustakom.hurrican.gui.shared.RaBvPanel', 'Button', 'Button (Save), um eine \nRechnungsanschrift zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (47, 'ra.delete', 'de.augustakom.hurrican.gui.shared.RaBvPanel', 'Button', 'Button (Delete), um eine \nRechnungsanschrift zu \nlöschen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (48, 'save', 'de.augustakom.hurrican.gui.eqhousing.EQHousingErfassenFrame', 'Button', 'Button (Save), um einen \nEQ-Housing Auftrag zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (49, 'faktura.eqh', 'de.augustakom.hurrican.gui.faktura.FakturierungPanel', 'Button', 'Button, um die EQH-Faktura \nzu starten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (50, 'faktura.connect', 'de.augustakom.hurrican.gui.faktura.FakturierungPanel', 'Button', 'Button, um die Connect-\nFaktura zu starten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (51, 'report.eqh', 'de.augustakom.hurrican.gui.faktura.FakturierungPanel', 'Button', 'Button, um die \nEQH-Rechnungen zu \nerstellen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (52, 'report.connect', 'de.augustakom.hurrican.gui.faktura.FakturierungPanel', 'Button', 'Button, um die Connect-\nRechnungen zu erstellen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (53, 'new.bearbeiter', 'de.augustakom.hurrican.gui.faktura.FakturierungPanel', 'Button', 'Button (New), um einen \nneuen Faktura-Bearbeiter \nanzulegen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (54, 'save.bearbeiter', 'de.augustakom.hurrican.gui.faktura.FakturierungPanel', 'Button', 'Button (Save), um einen \nFaktura-Bearbeiter zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (55, 'auto', 'de.augustakom.hurrican.gui.verlauf.BauauftragDISPOPanel', 'Button', 'Button, um einen BA \nautomatisch zu verteilen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (56, 'manuell', 'de.augustakom.hurrican.gui.verlauf.BauauftragDISPOPanel', 'Button', 'Button, um einen Bauauftrag \nmanuell zu verteilen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (57, 'rueckruf', 'de.augustakom.hurrican.gui.verlauf.BauauftragDISPOPanel', 'Button', 'Button, um einen bereits\nverteilten Bauauftrag wieder \nzurückzurufen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (58, 'print', 'de.augustakom.hurrican.gui.verlauf.BauauftragDISPOPanel', 'Button', 'Button, um einen Bauauftrag\nzu drucken (aus DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (59, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragDISPOPanel', 'Button', 'Button, um die Bauauftrags-\nBemerkungen anzuzeigen \n(aus DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (60, 'rufnummern', 'de.augustakom.hurrican.gui.verlauf.BauauftragDISPOPanel', 'Button', 'Button, um die Rufnummern \nzu einem Auftrag anzuzeigen \n(aus BA-DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (61, 'uebernahme', 'de.augustakom.hurrican.gui.verlauf.BauauftragSDHPanel', 'Button', 'Button, um einen Bauauftrag \nzu übernehmen (SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (62, 'print', 'de.augustakom.hurrican.gui.verlauf.BauauftragSDHPanel', 'Button', 'Button, um einen Bauauftrag \nzu drucken (aus SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (63, 'ba.erledigen.sdh', 'de.augustakom.hurrican.gui.verlauf.BauauftragSDHPanel', 'Button', 'Button, um einen Bauauftrag \nauf <erledigt> zu setzen \n(aus SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (64, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragSDHPanel', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag \nanzuzeigen (aus SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (65, 'pvc.erfassen', 'de.augustakom.hurrican.gui.verlauf.BauauftragSDHPanel', 'Button', 'Button, um die PVC-Daten zu \neinem Auftrag zu erfassen \n(aus BA-SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (66, 'save', 'de.augustakom.hurrican.gui.auftrag.SDHPhysikDialog', 'Button', 'Button (Save), um die \nPVC-Daten (SDH-Physik) zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (67, 'print', 'de.augustakom.hurrican.gui.verlauf.BauauftragEWSDPanel', 'Button', 'Button, um einen Bauauftrag \nzu drucken (aus BA-EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (68, 'ba.erledigen.ewsd', 'de.augustakom.hurrican.gui.verlauf.BauauftragEWSDPanel', 'Button', 'Button, um einen Bauauftrag \nauf <erledigt> zu setzen \n(EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (69, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragEWSDPanel', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag \nanzuzeigen (EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (70, 'rufnummern', 'de.augustakom.hurrican.gui.verlauf.BauauftragEWSDPanel', 'Button', 'Button, um die Rufnummern \nzu einem Auftrag anzuzeigen \n(aus BA-EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (71, 'uebernahme', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel.SCT', 'Button', 'Button, um einen Bauauftrag \nzu übernehmen (SCT).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (72, 'print', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel', 'Button', 'Button, um einen Bauauftrag \nzu drucken (SCT und SCTK).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (73, 'ba.erledigen.sct', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel.SCT', 'Button', 'Button, um einen Bauauftrag \nauf <erledigt> zu setzen \n(SCT).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (74, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag \nanzuzeigen (SCT).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (75, 'rufnummern', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel', 'Button', 'Button, um die Rufnummern \nzu einem Auftrag anzuzeigen \n(aus BA-SCT).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (76, 'uebernahme', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel.SCTK', 'Button', 'Button, um einen Bauauftrag \nzu übernehmen (SCTK).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (77, 'ba.erledigen.sct', 'de.augustakom.hurrican.gui.verlauf.BauauftragSCTPanel.SCTK', 'Button', 'Button, um einen Bauauftrag \nauf <erledigt> zu setzen \n(SCTK).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (78, 'print', 'de.augustakom.hurrican.gui.verlauf.BauauftragIPSPanel', 'Button', 'Button, um einen Bauauftrag \nzu drucken (IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (79, 'ba.erledigen.ips', 'de.augustakom.hurrican.gui.verlauf.BauauftragIPSPanel', 'Button', 'Button, um einen Bauauftrag \nauf <erledigt> zu setzen (IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (80, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragIPSPanel', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag \nanzuzeigen (aus IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (81, 'uebernahme', 'de.augustakom.hurrican.gui.verlauf.BauauftragIPSPanel', 'Button', 'Button, um einen Bauauftrag \nzu übernehmen (aus IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (82, 'abschliessen', 'de.augustakom.hurrican.gui.verlauf.BauauftragDispoRLPanel', 'Button', 'Button, um einen Bauauftrag \nabzuschliessen \n(aus DISPO Rückläufer).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (83, 'storno', 'de.augustakom.hurrican.gui.verlauf.BauauftragDispoRLPanel', 'Button', 'Button, um einen Bauauftrag \nzu stornieren (DISPO RL).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (84, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragDispoRLPanel', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag\nanzuzeigen (aus DISPO RL).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (85, 'ba.abschliessen.am', 'de.augustakom.hurrican.gui.verlauf.BauauftragAmRlPanel', 'Button', 'Button, um einen Bauauftrag \nkomplett abzuschliessen und \nden zug. Auftrag auf <in \nBetrieb> zu setzen (AM RL).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (86, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.BauauftragAmRlPanel', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag \nanzuzeigen (AM RL).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (87, 'verlauf.bemerkung.DISPO', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon DISPO.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (88, 'verlauf.bemerkung.SCV', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon SCV.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (89, 'verlauf.bemerkung.SDH', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'Button', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon SDH.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (90, 'verlauf.bemerkung.IPS', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon IPS', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (91, 'verlauf.bemerkung.EWSD', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon EWSD', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (92, 'verlauf.bemerkung.SCT', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon SCT.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (93, 'verlauf.bemerkung.NP', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon NP', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (94, 'verlauf.bemerkung.SCTK', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'TextArea', 'TextArea für die Bauauftrags- \nbzw. Projektierungsbemerk.\nvon SCTK.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (95, 'verteilen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoPanel', 'Button', 'Button, um eine Projektierung \nzu verteilen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (96, 'eingabe', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoPanel', 'Button', 'Button, um zus. Daten zu \neiner Projektierung zu \nerfassen (DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (97, 'print', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoPanel', 'Button', 'Button, um eine Projektierung \nzu drucken (DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (98, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoPanel', 'Button', 'Button, um die Bemerkungen \nzu einer Projektierung \nanzuzeigen (DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (99, 'save', 'de.augustakom.hurrican.gui.verlauf.VerlaufsBemerkungenDialog', 'Button', 'Button, um die Bemerkungen \nzu einem Bauauftrag bzw. zu \neiner Projektierung zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (100, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel.NP', 'Button', 'Button, um eine Projektierung \nabzuschliessen (NP).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (101, 'uebernehmen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel.NP', 'Button', 'Button, um eine Projektierung \nzu übernehmen (NP).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (102, 'print', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel', 'Button', 'Button, um eine Projektierung \nzu drucken (SCT, SCTK \nund NP).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (103, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel', 'Button', 'Button, um die Bemerkungen \nzu einer Projektierung \nanzuzeigen (SCT, SCTK \nund NP).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (104, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSdhEwsdPanel.SDH', 'Button', 'Button, um eine Projektierung \nabzuschliessen (SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (105, 'uebernehmen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSdhEwsdPanel.SDH', 'Button', 'Button, um eine Projektierung \nzu übernehmen (SDH).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (106, 'print', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSdhEwsdPanel', 'Button', 'Button, um eine Projektierung \nzu drucken (SDH und EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (107, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSdhEwsdPanel', 'Button', 'Button, um die Bemerkungen \nzu einer Projektierung \nanzuzeigen (SDH und EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (108, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSdhEwsdPanel.EWSD', 'Button', 'Button, um eine Projektierung \nabzuschliessen (EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (109, 'uebernehmen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSdhEwsdPanel.EWSD', 'Button', 'Button, um eine Projektierung \nzu übernehmen (EWSD).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (110, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel.SCT', 'Button', 'Button, um eine Projektierung \nabzuschliessen (SCT).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (111, 'uebernehmen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel.SCT', 'Button', 'Button, um eine Projektierung \nzu übernehmen (SCT).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (112, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel.SCTK', 'Button', 'Button, um eine Projektierung \nabzuschliessen (SCTK).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (113, 'uebernehmen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungSctNPPanel.SCTK', 'Button', 'Button, um eine Projektierung \nzu übernehmen (SCTK).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (114, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungIPSPanel', 'Button', 'Button, um eine Projektierung \nabzuschliessen (IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (115, 'uebernehmen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungIPSPanel', 'Button', 'Button, um eine Projektierung \nzu übernehmen (IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (116, 'print', 'de.augustakom.hurrican.gui.verlauf.ProjektierungIPSPanel', 'Button', 'Button, um eine Projektierung \nzu drucken (IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (117, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungIPSPanel', 'Button', 'Button, um die Bemerkungen \nzu einer Projektierung \nanzuzeigen (IPS).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (118, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoRLPanel', 'Button', 'Button, um eine Projektierung \nabzuschliessen (RL DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (119, 'eingabe', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoRLPanel', 'Button', 'Button, um zus. Daten zu \neiner Projektierung zu erfassen\n(RL DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (120, 'print', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoRLPanel', 'Button', 'Button, um eine Projektierung \nzu drucken (RL DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (121, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoRLPanel', 'Button', 'Button, um die Bemerkungen \nzu einer Projektierung \nanzuzeigen (RL DISPO).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (122, 'erledigen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungAmRlPanel', 'Button', 'Button, um eine Projektierung \nkomplett abzuschliessen \n(RL AM).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (123, 'bemerkungen', 'de.augustakom.hurrican.gui.verlauf.ProjektierungAmRlPanel', 'Button', 'Button, um die Bemerkungen \nzu einer Projektierung \nanzuzeigen (RL AM).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (124, 'save', 'de.augustakom.hurrican.gui.verlauf.ProjektierungDispoEingabeDialog', 'Button', 'Button, um Zusatzdaten zu \neiner Projektierung bzw. zu \ndem Auftrag zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (125, 'Kunde', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für die Actions, die \nKunden-Objekten zugeordnet \nsind.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (126, 'menu.administration', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für die Administrations-\nActions.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (127, 'admin.rangierungsmatrix.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Konfiguration \nder Rangierungsmatrix.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (128, 'admin.rangierungsfreigabe.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Freigabe \nvon Rangierungen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (129, 'admin.hvt.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die Administration \nder HVTs', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (130, 'admin.produkte.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die \nAdministration der Produkte.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (131, 'admin.sperre.info.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die \nAdministration der \nSperr-Benachrichtigungen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (132, 'admin.anschlussarten.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die \nAdministration der versch. \nAnschlussarten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (133, 'admin.physiktypen.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für die \nAdministration der \nPhysik-Typen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (134, 'save', 'de.augustakom.hurrican.gui.stammdaten.AnschlussartenAdminFrame', 'Button', 'Button, um eine \nAnschlussart zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (135, 'create.new', 'de.augustakom.hurrican.gui.stammdaten.AnschlussartenAdminFrame', 'Button', 'Button, um eine neue \nAnschlussart zu erzeugen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (136, 'save', 'de.augustakom.hurrican.gui.stammdaten.PhysikTypenAdminFrame', 'Button', 'Button, um einen \nPhysikTyp zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (137, 'create.new', 'de.augustakom.hurrican.gui.stammdaten.PhysikTypenAdminFrame', 'Button', 'Button, um einen neuen \nPhysik-Typ anzulegen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (138, 'save', 'de.augustakom.hurrican.gui.stammdaten.SperreInfoAdminFrame', 'Button', 'Button, um eine \nSperr-Benachrichtigung zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (139, 'create.new', 'de.augustakom.hurrican.gui.stammdaten.SperreInfoAdminFrame', 'Button', 'Button, um eine neue \nSperr-Benachrichtigung \neinzurichten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (140, 'save', 'de.augustakom.hurrican.gui.hvt.HVTAdminFrame', 'Button', 'Button, um eine HVT-Gruppe \nzu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (141, 'create.new', 'de.augustakom.hurrican.gui.hvt.HVTAdminFrame', 'Button', 'Button, um eine neue \nHVT-Gruppe bzw einen \nneuen HVT-Standort \nzu erzeugen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (142, 'save.hvt.standort', 'de.augustakom.hurrican.gui.hvt.HVTAdminFrame', 'Button', 'Button, um einen \nHVT-Standort zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (143, 'create.matrix', 'de.augustakom.hurrican.gui.hvt.HVTUevtAdminPanel', 'Button', 'Button, um die Rangierungs-\nmatrix für einen best. UEVT \nanzulegen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (144, 'add.ziel', 'de.augustakom.hurrican.gui.hvt.HVTUevtAdminPanel', 'Button', 'Button, um einen Ziel-HVT \nfür ein best. Produkt an \neinem best. HVT zu \ndefinieren (t_uevt_2_ziel).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (145, 'remove.ziel', 'de.augustakom.hurrican.gui.hvt.HVTUevtAdminPanel', 'Button', 'Button, um die Definition \neines Ziel-HVTs zu einem \nbest. Produkt an einem best. \nHVT zu löschen (t_uevt_2_ziel).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (146, 'save', 'de.augustakom.hurrican.gui.stammdaten.ProduktAdminFrame', 'Button', 'Button, um ein Produkt \nzu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (147, 'create.new', 'de.augustakom.hurrican.gui.stammdaten.ProduktAdminFrame', 'Button', 'Button, um ein neues \nProdukt zu definieren.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (148, 'new.p2pt', 'de.augustakom.hurrican.gui.stammdaten.ProduktAdminPanel', 'Button', 'Button, um einem Produkt \neinen Physik-Typ zuzuordnen\n(t_produkt_2_physiktyp).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (149, 'delete.p2pt', 'de.augustakom.hurrican.gui.stammdaten.ProduktAdminPanel', 'Button', 'Button, um eine Produkt- \nPhysikTyp-Zuordnung zu \nlöschen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (150, 'new', 'de.augustakom.hurrican.gui.stammdaten.RangierungsmatrixAdminPanel', 'Button', 'Button, um <zu Fuss> eine \nneue Rangierungsmatrix \nanzulegen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (151, 'save', 'de.augustakom.hurrican.gui.stammdaten.RangierungsmatrixAdminPanel', 'Button', 'Button, um eine best. \nRangierungsmatrix zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (152, 'delete', 'de.augustakom.hurrican.gui.stammdaten.RangierungsmatrixAdminPanel', 'Button', 'Button, um eine best. \nRangierungsmatrix zu \nlöschen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (153, 'create.complete.matrix', 'de.augustakom.hurrican.gui.stammdaten.RangierungsmatrixAdminPanel', 'Button', 'Button, um für alle UEVTs \nund alle Produkte eine \nStandard-Rangierungsmatrix \nzu erstellen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (154, 'create.auftrag', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um einen neuen \nHurrican-Auftrag (z.B. \nAK-Connect) anzulegen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (155, 'show.auftragsmonitor', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um den Auftrags-\nmonitor Hurrican-->Mistral \nzu öffnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (156, 'uebersicht.mistral', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für eine Übersicht \nder Mistral-Aufträge zu einem \nbest. Kunden.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (157, 'sperre.history', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um die bisherigen \nSperren zu einem Kunden \nanzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (158, 'sperren', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um einen best. \nKunden zu sperren bzw. um \ndie Sperre aufzuheben.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (159, 'Auftrag', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für die Actions, die\nden Aufträgen zugeordnet \nsind.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (160, 'show.billing.auftragpos', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um eine Übersicht \naller Mistral-Auftragspos. zu \neinem best. Auftrag \nanzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (161, 'bauauftrag.erstellen', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um f. einen best. \nAuftrag einen Bauauftrag \nzu erstellen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (162, 'bauauftrag.stornieren', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um den Bauauftrag \neines best. Auftrags zu \nstornieren.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (163, 'print.bauauftrag', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um den aktuellen \nBauauftrag eines best. \nAuftrags zu drucken.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (164, 'projektierung.erstellen', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um für einen best. \nAuftrag eine Projektierung \nzu erstellen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (165, 'print.projektierung', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um die aktuelle \nProjektierung eines Auftrags \nzu drucken.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (166, 'auftrag.absage', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um einen Auftrag \nauf <Absage> zu setzen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (167, 'auftrag.aendern', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um einen aktiven \nAuftrag zu ändern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (168, 'verlauf.history.anzeigen', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um die Verlaufs-\nHistorie eines Auftrags \nanzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (169, 'ba.realdate.aendern', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um den \nRealisierungstermin eines \naktiven Bauauftrags zu \nändern (nur bei S2M !!!).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (170, 'save.auftrag.stammdaten.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button (Save), um die \nAuftrags-Stammdaten zu \nspeichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (171, 'save.auftrag.rufnummer.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button, um die Rufnummer-\nDaten eines Auftrags zu \nspeichern.\nz.Z. überall deaktiviert !!!', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (172, 'switch1', 'de.augustakom.hurrican.gui.auftrag.AuftragEndstellenPanel', 'Button', 'Button, um eine Endstelle \nüber die AUG-01 zu \nschalten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (173, 'switch2', 'de.augustakom.hurrican.gui.auftrag.AuftragEndstellenPanel', 'Button', 'Button, um eine Endstelle \nüber die AUG-02 zu \nschalten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (174, 'save.auftrag.endstellen.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button, um die Endstellen-\nDaten eines Auftrags \nzu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (175, 'physik.zuordnen', 'de.augustakom.hurrican.gui.auftrag.RangierungPanel', 'Button', 'Button ordnet einer Endstelle \nautomatisch eine Physik zu.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (176, 'physik.uebernehmen', 'de.augustakom.hurrican.gui.auftrag.RangierungPanel', 'Button', 'Button ordnet der Endstelle \neine Physik eines \nbestehenden bzw. alten \nAuftrags zu.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (177, 'new', 'de.augustakom.hurrican.gui.auftrag.CarrierbestellungPanel', 'Button', 'Button, um eine neue \nCarrierbestellung zu einer \nEndstelle zu erfassen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (178, 'aqs.anzeigen', 'de.augustakom.hurrican.gui.auftrag.CarrierbestellungPanel', 'Button', 'Button, um die Aderquery-\nschnitte einer Strasse \nanzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (179, 'save.auftrag.in.dienste.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button (Save), um die \nIN-Dienste zu einem Auftrag \nzu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (180, 'new', 'de.augustakom.hurrican.gui.auftrag.AuftragINDienstePanel', 'Button', 'Button, um einen neuen \nIN-Dienst zu einem Auftrag \nzu erfassen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (181, 'delete', 'de.augustakom.hurrican.gui.auftrag.AuftragINDienstePanel', 'Button', 'Button, um einen IN-Dienst \nvon einem Auftrag zu \nentfernen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (182, 'vpn.konf.tdn.remove', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNKonfigPanel', 'Button', 'Button, um die phys. Leitung \naus einer VPN-Konfiguration \nzu entfernen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (183, 'save.auftrag.vpn.konfig.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button, um die VPN-Konfig. \neines Auftrags zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (184, 'vpn.konf.tdn', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNKonfigPanel', 'Button', 'Button, um einer VPN-Konf. \neine phys. Leitung zuzuordnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (185, 'save.auftrag.faktura.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button, um die Abrechnungs-\ndaten (Faktura) eines \nAuftrags zu erfassen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (186, 'save.auftrag.internet.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'Button', 'Button (Save) für die \nInternet-Daten. \nDer Button ist immer \ndeaktiviert !!!', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (187, 'save', 'de.augustakom.hurrican.gui.auftrag.InhouseDialog', 'Button', 'Button (Save), um die \nInhouse-Daten zu einer \nEndstelle zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (188, 'edit.inhouse', 'de.augustakom.hurrican.gui.auftrag.InhousePanel', 'Button', 'Button, um einen \nbestehenden Inhouse-\nDatensatz zu editieren \n(öffnet einen Dialog).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (189, 'new.inhouse', 'de.augustakom.hurrican.gui.auftrag.InhousePanel', 'Button', 'Button, um für eine \nEndstelle einen neuen \nInhouse-Datensatz zu \nerstellen (öffnen einen Dialog).', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (190, 'faktura.kontrolle.berechnungsdatum.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um eine Übersicht \nüber alle Faktura-Aufträge \nohne Berechnungsdatum \nanzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (191, 'menu.tools', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu für die \nGruppierung von \nverschiedenen Tools.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (192, 'menu.e.rechnung', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Sub-Menu fuer die \nMenu-Items der \neRechnung.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (193, 'e.rechnung.nachdruck.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für den \nNachdruck von \neRechnung-Accounts.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (194, 'e.rechnung.password.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem für den \nDruck der PIN-Taschen \nfür eRechnung-Accounts.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (195, 'angebot.am', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'DateComp', 'Datumsfeld f. \nAngebot-am', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (196, 'auftrag.am', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'DateComp', 'Datumsfeld f. \nAuftrag-am', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (197, 'vorgabe.am', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'DateComp', 'Datumsfeld f. \nVorgabe AM.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (198, 'mmz', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'ComboBox', 'ComboBox fuer die \nAuswahl der \nMindestvertragslaufzeit.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (199, 'anbindungsart', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'ComboBox', 'ComboBox fuer die \nAuswahl der \nRealisierungsart (z.B. HVT)', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (200, 'bestell.nr', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'TextField', 'TextField fuer die \nAngabe einer externen \nBestell-Nr.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (201, 'bemerkung', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'TextArea', 'TextArea fuer die \nAngabe einer Bemerkung.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (202, 'strasse.suchen', 'de.augustakom.hurrican.gui.auftrag.AuftragEndstellenPanel', 'Button', 'Button fuer die Auswahl \neiner Endstellen-Strasse.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (203, 'save', 'de.augustakom.hurrican.gui.shared.StrasseSearchDialog', 'Button', 'Button fuer die Auswahl \neiner Strasse im \nStrassen-Such-Dialog.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (204, 'print', 'de.augustakom.hurrican.gui.auftrag.AuftragStammdatenPanel', 'Button', 'Button, um einen Auftrag \nzu drucken.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (205, 'copy.es.daten', 'de.augustakom.hurrican.gui.auftrag.AuftragEndstellenPanel', 'Button', 'Button, um die Daten einer \nanderen Endstelle zu \nkopieren.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (206, 'uebernahme', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNVertragsUebersichtPanel', 'BUTTON', 'Button, um einen VPN-\nAuftrag zu übernehmen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (207, 'edit', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNVertragsUebersichtPanel', 'BUTTON', 'Button, um einen \nVPN-Auftrag zu bearbeiten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (208, 'details', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNVertragsUebersichtPanel', 'BUTTON', 'Button, um die Details eines \nVPN-Auftrags anzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (209, 'save', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNUebernahmeDialog', 'BUTTON', 'Button, um einen VPN-\nAuftrag zu übernehmen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (210, 'save', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNEditDialog', 'BUTTON', 'Button, um einen \nVPN-Auftrag zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (211, 'add', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNAuftragPanel', 'BUTTON', 'Button, um einen selektierten \nAuftrag in ein VPN zu \nübernehmen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (212, 'remove', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNAuftragPanel', 'BUTTON', 'Button, um einen Auftrag \naus dem VPN zu \nentfernen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (213, 'print.online', 'de.augustakom.hurrican.gui.auftrag.internet.InternetPanel', 'BUTTON', 'Button, um das Online-\nAnschreiben eines Kunden \nzu drucken.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (214, 'save.auftrag.endgeraet.zugang.panel', 'de.augustakom.hurrican.gui.auftrag.AuftragDataFrame', 'BUTTON', 'Button fuer das Speichern \nvon Zugangsdaten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (215, 'print.vpn.account', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNKonfigPanel', 'BUTTON', 'Button, um die Account-Daten \neines Auftrags zu drucken, der \neinem VPN zugeordnet ist.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (216, 'cb.kuendigen', 'de.augustakom.hurrican.gui.auftrag.CarrierbestellungPanel', 'BUTTON', 'Button, um eine \nCarrierbestellung zu \nkündigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (217,	'save',	'de.augustakom.hurrican.gui.verlauf.BauauftragErledigenDialog',	'BUTTON', 'Button, um Abschlussdaten f. BAs von IPS einzutragen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (218,	'save',	'de.augustakom.hurrican.gui.verlauf.VerlaufAbtAuswahlDialog',	'BUTTON', 'Button, um manuelle Verteilung (DISPO) zu bestaetigen', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (219,	'copy.password', 'de.augustakom.hurrican.gui.auftrag.internet.InternetPanel', 'MENUITEM', 'MenuItem, um das Passwort eines Einwahlaccounts in die Zwischenablage zu kopieren.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (220, 'hvt.tool', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'Menu', 'Menu fuer die HVT-Tools.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (221, 'hvt.bestellung.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem fuer die \nHVT-Bestellungen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (222, 'hvt.ueberwachung.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem zur Anzeige \nder HVT-Belegungen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (223, 'save', 'de.augustakom.hurrican.gui.hvt.UEVTLeistenDefinitionsDialog', 'Button', 'Button, um Stiften eine \nPhysik zuzuordnen und um \nRangierungen zu erzeugen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (224, 'edit', 'de.augustakom.hurrican.gui.hvt.HVTBestellungenPanel', 'Button', 'Button, um eine \nHVT-Bestellung zu bearbeiten.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (225, 'history', 'de.augustakom.hurrican.gui.hvt.HVTBestellungenPanel', 'Button', 'Button, um die History \neiner HVT-Bestellung \nanzuzeigen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (226, 'new', 'de.augustakom.hurrican.gui.hvt.HVTBestellungEditPanel', 'Button', 'Button, um eine neue \nHVT-Bestellung zu \nerstellen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (227, 'save', 'de.augustakom.hurrican.gui.hvt.HVTBestellungEditPanel', 'Button', 'Button, um eine \nHVT-Bestellung zu speichern.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (228, 'new.leiste', 'de.augustakom.hurrican.gui.hvt.UEVTStiftVergabePanel', 'Button', 'Button, um Stifte einer \nHVT-Best. einer neuen \nLeiste zuzuordnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (229, 'fill.leiste', 'de.augustakom.hurrican.gui.hvt.UEVTStiftVergabePanel', 'Button', 'Button, um Stifte einer \nHVT-Best. in eine best. \nLeiste einzuspielen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (230, 'kubena.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem u. Toolbar-Btn \nfuer die Kubena.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (231, 'cuda.vorschau.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'MenuItem, um die \nCuDA-Vorschau zu \noeffnen.', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (232, 'save', 'de.augustakom.hurrican.gui.auftrag.SperreAuswahlDialog', '', '', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (233, 'new.kubena', 'de.augustakom.hurrican.gui.kubena.KubenaDefinitionPanel', '', '', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (234, 'save.kubena', 'de.augustakom.hurrican.gui.kubena.KubenaDefinitionPanel', '', '', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (235, 'save', 'de.augustakom.hurrican.gui.auftrag.vpn.VPNAuftragAuswahlDialog', '', '', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (236, 'print.online', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', '', '', 1);
INSERT INTO guicomponent (ID, NAME, PARENT, TYPE, DESCRIPTION, APP_ID) VALUES (237, 'sct.sperren.action', 'de.augustakom.hurrican.gui.system.HurricanMainFrame', 'MenuItem', 'Menu, um die SCT-Sperren \nanzuzeigen.', 1);

-- Rollen-GUI-Verhalten (CompBehaviour)
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (203, 1, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (204, 2, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (205, 3, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (206, 4, 15, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (207, 4, 19, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (208, 4, 8, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (209, 4, 26, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (210, 4, 23, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (211, 4, 11, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (212, 4, 16, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (213, 4, 18, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (214, 4, 12, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (215, 4, 27, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (216, 4, 22, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (217, 4, 17, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (218, 4, 13, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (219, 4, 9, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (220, 4, 28, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (221, 4, 21, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (222, 4, 20, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (223, 4, 14, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (224, 4, 25, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (225, 4, 24, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (226, 4, 10, 0, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (227, 5, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (230, 8, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (232, 10, 12, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (233, 11, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (234, 12, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (235, 13, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (236, 14, 12, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (237, 14, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (238, 15, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (239, 15, 12, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (240, 16, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (241, 17, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (243, 18, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (244, 19, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (245, 20, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (246, 21, 21, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (247, 22, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (248, 22, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (253, 17, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (258, 23, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (259, 24, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (260, 25, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (261, 26, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (262, 27, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (263, 28, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (264, 29, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (265, 30, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (266, 31, 21, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (267, 32, 21, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (268, 32, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (269, 33, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (270, 34, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (271, 35, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (272, 36, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (273, 37, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (274, 38, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (275, 39, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (276, 40, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (277, 41, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (278, 42, 21, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (279, 43, 21, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (280, 44, 21, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (281, 45, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (282, 46, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (283, 47, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (284, 48, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (285, 49, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (286, 50, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (287, 51, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (288, 52, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (289, 53, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (290, 54, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (291, 55, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (292, 56, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (293, 57, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (294, 58, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (295, 58, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (296, 59, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (297, 59, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (298, 60, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (299, 60, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (300, 61, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (301, 62, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (302, 63, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (303, 64, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (304, 65, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (305, 66, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (306, 67, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (307, 67, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (308, 68, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (309, 69, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (310, 70, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (311, 71, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (312, 72, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (313, 73, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (314, 74, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (315, 75, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (316, 76, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (317, 77, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (318, 78, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (319, 79, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (320, 80, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (321, 81, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (322, 81, 20, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (323, 82, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (324, 83, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (325, 84, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (326, 85, 23, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (327, 86, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (328, 87, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (329, 88, 23, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (330, 89, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (331, 90, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (332, 91, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (333, 92, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (334, 93, 27, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (335, 94, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (336, 95, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (337, 96, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (338, 97, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (339, 98, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (340, 99, 23, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (341, 99, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (342, 99, 21, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (343, 99, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (344, 99, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (345, 99, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (346, 99, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (347, 99, 27, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (348, 100, 27, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (349, 101, 27, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (350, 102, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (351, 103, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (352, 104, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (353, 105, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (354, 106, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (355, 107, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (356, 108, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (357, 109, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (358, 110, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (359, 111, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (360, 112, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (361, 113, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (362, 114, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (363, 115, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (364, 116, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (365, 117, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (366, 118, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (367, 119, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (368, 120, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (369, 121, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (370, 122, 23, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (371, 123, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (372, 124, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (373, 125, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (374, 126, 17, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (375, 126, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (376, 126, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (377, 126, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (378, 127, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (379, 128, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (380, 129, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (381, 130, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (382, 131, 17, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (383, 132, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (384, 133, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (385, 134, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (386, 135, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (387, 136, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (388, 137, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (389, 138, 17, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (390, 139, 17, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (391, 140, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (392, 141, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (393, 142, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (394, 143, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (395, 129, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (396, 144, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (397, 144, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (398, 145, 15, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (399, 145, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (400, 146, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (401, 147, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (402, 148, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (403, 149, 16, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (404, 150, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (405, 151, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (406, 152, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (407, 153, 14, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (409, 65, 10, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (410, 66, 10, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (412, 154, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (413, 155, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (414, 156, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (415, 156, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (416, 157, 19, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (417, 157, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (418, 157, 18, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (419, 158, 18, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (420, 159, 9, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (421, 159, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (422, 160, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (423, 161, 18, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (424, 161, 29, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (425, 162, 29, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (426, 163, 29, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (427, 163, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (428, 164, 29, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (429, 165, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (430, 165, 29, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (431, 166, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (432, 167, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (433, 168, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (434, 168, 20, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (435, 169, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (436, 169, 29, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (437, 170, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (438, 172, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (439, 173, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (440, 174, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (441, 175, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (442, 176, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (443, 177, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (444, 178, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (445, 178, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (446, 179, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (447, 180, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (448, 181, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (450, 182, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (451, 183, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (453, 184, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (454, 185, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (455, 185, 9, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (456, 187, 11, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (457, 188, 11, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (458, 189, 11, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (459, 190, 13, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (463, 191, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (483, 192, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (484, 192, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (485, 193, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (486, 194, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (487, 195, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (488, 196, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (489, 197, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (490, 198, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (491, 199, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (492, 200, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (493, 201, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (494, 202, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (495, 203, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (496, 204, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (497, 205, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (498, 206, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (499, 207, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (500, 208, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (501, 209, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (502, 210, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (503, 211, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (504, 212, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (505, 213, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (506, 214, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (507, 215, 30, 1, 0);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (508, 215, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (509, 216, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (510, 217, 25, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (511, 218, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (512, 217, 22, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (513, 217, 23, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (514, 217, 24, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (515, 217, 26, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (516, 217, 27, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (517, 217, 28, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (518, 219, 31, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (520, 220, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (521, 221, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (522, 222, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (523, 223, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (524, 224, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (525, 225, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (526, 226, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (527, 227, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (528, 228, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (529, 229, 32, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (530, 230, 33, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (531, 168, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (532, 231, 8, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (534, 204, 34, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (535, 167, 34, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (536, 232, 18, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (537, 171, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (538, 14, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (539, 15, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (540, 16, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (541, 45, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (542, 46, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (543, 47, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (544, 48, 35, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (545, 233, 33, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (546, 234, 33, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (547, 235, 30, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (548, 213, 31, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (549, 236, 31, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (550, 236, 9, 1, 1);
INSERT INTO compbehavior (ID, COMP_ID, ROLE_ID, VISIBLE, EXECUTABLE) VALUES (551, 237, 24, 1, 1);
