-- create an index and a foreign key constrain for the column AUFTRAG_ID
ALTER TABLE T_WBCI_GESCHAEFTSFALL MODIFY (AUFTRAG_ID NOT NULL);

ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD CONSTRAINT FK_WBCI_GF_AUFTRAG_ID
  FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

CREATE INDEX IX_FK_WBCI_GF_AUFTRAG_ID ON T_WBCI_GESCHAEFTSFALL(AUFTRAG_ID) TABLESPACE "I_HURRICAN";
