CREATE TABLE T_WBCI_MELDUNG (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), meldung_typ VARCHAR2(30 CHAR), vorabstimmungsId VARCHAR2(21 CHAR), geschaeftsfallTyp VARCHAR2(31 CHAR), abgebenderEKP VARCHAR2(255 CHAR), absender VARCHAR2(255 CHAR), aufnehmenderEKP VARCHAR2(255 CHAR), technologie VARCHAR2(25 CHAR), wechseltermin DATE, RUFNUMMERPORTIERUNG_ID NUMBER(19, 0), PRIMARY KEY (id));
CREATE TABLE T_WBCI_MELDUNG_POSITION (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), MELDUNG_ID NUMBER(19, 0), position_typ VARCHAR2(30 CHAR), meldung_code VARCHAR2(10 CHAR), meldung_text VARCHAR2(255 CHAR), PRIMARY KEY (id));
CREATE TABLE T_WBCI_TECHNISCHE_RESSOURCE (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), MELDUNG_ID NUMBER(19, 0), vertragsnummer VARCHAR2(10 CHAR), line_id VARCHAR2(21 CHAR), identifizierer VARCHAR2(20 CHAR), tnb_kennung_abg VARCHAR2(4 CHAR), PRIMARY KEY (id));

ALTER TABLE T_WBCI_MELDUNG ADD CONSTRAINT FK_MELDUNG_RNP_ID FOREIGN KEY (RUFNUMMERPORTIERUNG_ID) REFERENCES T_WBCI_RUFNUMMERPORTIERUNG;
ALTER TABLE T_WBCI_MELDUNG_POSITION ADD CONSTRAINT FK_MPOS_MELDUNG_ID FOREIGN KEY (MELDUNG_ID) REFERENCES T_WBCI_MELDUNG;
ALTER TABLE T_WBCI_TECHNISCHE_RESSOURCE ADD CONSTRAINT FK_TR_MELDUNG_ID FOREIGN KEY (MELDUNG_ID) REFERENCES T_WBCI_MELDUNG;

GRANT SELECT, INSERT, UPDATE ON T_WBCI_MELDUNG TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_MELDUNG_POSITION TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE ON T_WBCI_TECHNISCHE_RESSOURCE TO R_HURRICAN_USER;

GRANT SELECT ON T_WBCI_MELDUNG TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_MELDUNG_POSITION TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_TECHNISCHE_RESSOURCE TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_MELDUNG_0;
CREATE SEQUENCE S_T_WBCI_MELDUNG_POSITION_0;
CREATE SEQUENCE S_T_WBCI_TECH_RESSOURCE_0;

GRANT SELECT ON S_T_WBCI_MELDUNG_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_MELDUNG_POSITION_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_TECH_RESSOURCE_0 TO PUBLIC;
