update T_WBCI_RUFNUMMERPORTIERUNG set TYP='ANLAGEN_ANSCHLUSS' where TYP='ANLAGENASCHLUSS';
update T_WBCI_RUFNUMMERPORTIERUNG set TYP='EINZEL_ANSCHLUSS' where TYP='EINZELNANSCHLUSS';

ALTER TABLE T_WBCI_RUFNUMMERPORTIERUNG
ADD CONSTRAINT CK_WBCIRNPORTIERUNG_TYP
CHECK (TYP IN (
    'ANLAGEN_ANSCHLUSS',
    'EINZEL_ANSCHLUSS'
  )) ENABLE NOVALIDATE;