server:
  ssl:
    key-store: classpath:ssl-server.jks
    key-store-password: ${KEY_STORE_PASS}
    key-alias: selfsigned_localhost_sslserver
  port: 443
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    gateway:
      enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: 
              - POST
              - GET
              - PATCH
              - DELETE
            allowedHeaders: '*'
      routes:
        - id: agreement
          uri: http://localhost:8606/
          predicates:
            - Path=/agreementManagement/v4/**
          filters:
            - StripPrefix=2
        - id: appointment
          uri: http://localhost:8585/
          predicates:
            - Path=/tmf-api/appointment/v4/**
          filters:
            - StripPrefix=3
        - id: geo
          uri: http://localhost:8484/
          predicates:
            - Path=/tmf-api/geographicLocation/v4/**
          filters:
            - StripPrefix=3
        - id: party
          uri: http://localhost:8383/
          predicates:
            - Path=/tmf-api/party/v4/**
          filters:
            - StripPrefix=3
        - id: resourceCatalog
          uri: http://localhost:8282/
          predicates:
            - Path=/tmf-api/resourceCatalog/v4/**
          filters:
            - StripPrefix=3
        - id: resourceInventory
          uri: http://localhost:8181/
          predicates:
            - Path=/tmf-api/resourceInventoryManagement/v4/**
          filters:
            - StripPrefix=3
        - id: resourceOrderManagement
          uri: http://localhost:8080/
          predicates:
            - Path=/tmf-api/resourceOrdering/v4/**
          filters:
            - StripPrefix=3
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh,gateway"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true