ALTER TABLE T_ANBIETERWECHSELCONFIG MODIFY (NEUPRODUKT varchar2(18));

INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (1, 0, 'DTAG', 'DTAG_ANY', 'TAL', 'VERBUNDLEISTUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (2, 0, 'DTAG', 'DTAG_ANY', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (3, 0, 'OTHER', 'CLS', 'TAL', 'VERBUNDLEISTUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (4, 0, 'OTHER', 'ADSL_SH', 'TAL', 'VERBUNDLEISTUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (5, 0, 'OTHER', 'TAL', 'TAL', 'PROVIDERWECHSEL');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (6, 0, 'OTHER', 'VDSL', 'TAL', 'BEREITSTELLUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (7, 0, 'OTHER', 'SDSL', 'TAL', 'BEREITSTELLUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (8, 0, 'OTHER', 'ADSL_SA', 'TAL', 'BEREITSTELLUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (9, 0, 'OTHER', 'CLS', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (10, 0, 'OTHER', 'ADSL_SH', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (11, 0, 'OTHER', 'TAL', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (12, 0, 'OTHER', 'VDSL', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (13, 0, 'OTHER', 'SDSL', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');
INSERT INTO T_ANBIETERWECHSELCONFIG (ID, VERSION, CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT,GESCHAEFTSFALLTYP) VALUES (14, 0, 'OTHER', 'ADSL_SA', 'KEINE_DTAG_LEITUNG', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG');

ALTER TABLE T_ANBIETERWECHSELCONFIG
 ADD CONSTRAINT T_ANBIETERWECHSELCONFIG_CRR
  CHECK (CARRIERABGEBEND IN ('DTAG','OTHER'));
  
ALTER TABLE T_ANBIETERWECHSELCONFIG
 ADD CONSTRAINT T_ANBIETERWECHSELCONFIG_ALT
  CHECK (ALTPRODUKT IN ('DTAG_ANY','CLS', 'ADSL_SH', 'TAL', 'VDSL', 'SDSL', 'ADSL_SA'));  
  
ALTER TABLE T_ANBIETERWECHSELCONFIG
 ADD CONSTRAINT T_ANBIETERWECHSELCONFIG_NEU
  CHECK (NEUPRODUKT IN ('TAL', 'KEINE_DTAG_LEITUNG')); 
  
ALTER TABLE T_ANBIETERWECHSELCONFIG
 ADD CONSTRAINT T_ANBIETERWECHSELCONFIG_GFT
  CHECK (GESCHAEFTSFALLTYP IN ('BEREITSTELLUNG', 'VERBUNDLEISTUNG', 'PROVIDERWECHSEL', 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG')); 

ALTER TABLE T_ANBIETERWECHSELCONFIG
 ADD CONSTRAINT T_ANBIETERWECHSELCONFIG_UNI
  UNIQUE (CARRIERABGEBEND,ALTPRODUKT,NEUPRODUKT);
