ALTER TABLE T_CARRIERBESTELLUNG_PV DROP CONSTRAINT C_CBPV_PRODUKT;

update T_CARRIERBESTELLUNG_PV set PRODUKT_GRUPPE = 'DTAG_ANY' where PRODUKT_GRUPPE = 'SONSTIGES';

ALTER TABLE T_CARRIERBESTELLUNG_PV ADD CONSTRAINT C_CBPV_PRODUKT CHECK (PRODUKT_GRUPPE IN ('DTAG_ANY','CLS', 'ADSL_SH', 'TAL', 'VDSL', 'SDSL', 'ADSL_SA'));  
 