ALTER TABLE T_MWF_MELDUNGS_POSITION add (MELDUNG_ID number(19));

UPDATE T_MWF_MELDUNGS_POSITION SET MELDUNG_ID = ABM_MELDUNG_ID WHERE ABM_MELDUNG_ID IS NOT NULL;
UPDATE T_MWF_MELDUNGS_POSITION SET MELDUNG_ID = ABBM_MELDUNG_ID WHERE ABBM_MELDUNG_ID IS NOT NULL;
UPDATE T_MWF_MELDUNGS_POSITION SET MELDUNG_ID = ABBMPV_MELDUNG_ID WHERE ABBMPV_MELDUNG_ID IS NOT NULL;

ALTER TABLE T_MWF_MELDUNGS_POSITION drop column ABM_MELDUNG_ID;
ALTER TABLE T_MWF_MELDUNGS_POSITION drop column ABBM_MELDUNG_ID;
ALTER TABLE T_MWF_MELDUNGS_POSITION drop column ABBMPV_MELDUNG_ID;

ALTER TABLE T_MWF_MELDUNGS_POSITION
  ADD CONSTRAINT T_MWF_MELDUNGS_POSITION_FK
      FOREIGN KEY (MELDUNG_ID)
      REFERENCES T_MWF_MELDUNG (ID);
