CREATE TABLE T_TAM_USER_TASK
(
  ID                        NUMBER(19)          NOT NULL,
  VERSION                   NUMBER(19)          NOT NULL,
  TAM_STATUS                VARCHAR2(10 BYTE)   NOT NULL,
  BEMERKUNGEN               VARCHAR2(2000 BYTE),
  LETZTE_AENDERUNG          DATE,
  LETZTER_BEARBEITER        VARCHAR2(50 BYTE)
);

ALTER TABLE T_TAM_USER_TASK ADD (
  CONSTRAINT T_TAM_USER_TASK_TAM_STATUS
  CHECK (TAM_STATUS IN ('OFFEN','KUNDE_NICHT_ERREICHT','KUNDE_MELDET_SICH','TV_60_TAGE','INFO_MAILED')),
  CONSTRAINT PK_T_TAM_USER_TASK
  PRIMARY KEY (ID));

grant select, insert, update, delete on T_TAM_USER_TASK to R_HURRICAN_USER;
grant select on T_TAM_USER_TASK to R_HURRICAN_READ_ONLY;

create sequence S_T_TAM_USER_TASK_0 start with 1;
grant select on S_T_TAM_USER_TASK_0 to public;

ALTER TABLE T_CB_VORGANG ADD (TAM_USER_TASK_ID  NUMBER(19));
