
alter table T_USER_TASK drop constraint PK_T_TAM_USER_TASK;

ALTER TABLE T_USER_TASK ADD (
  CONSTRAINT PK_T_USER_TASK
  PRIMARY KEY (ID));

ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CB_VORGANG_2_USER_TASK
      FOREIGN KEY (USER_TASK_ID)
      REFERENCES T_USER_TASK (ID);
