ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN RENAME COLUMN AUFTRAGDATENID TO AUFTRAGID;
ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN RENAME COLUMN KUEDDTTASKID TO KUEDTTASKID;

ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN DROP CONSTRAINT FK_UT2AD_2_AUFTRAGDATEN;

UPDATE T_USER_TASK_2_AUFTRAGDATEN a SET AUFTRAGID = (select auftrag_id from T_AUFTRAG_DATEN where id = a.auftragid);

ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN ADD CONSTRAINT FK_UT2AD_2_AUFTRAG
  FOREIGN KEY (AUFTRAGID) REFERENCES T_AUFTRAG(ID);
