-- Tabelle um mehrere nicht billing relevante Taifun Auftragsdaten zum WBCI Geschaeftsfall zuzuordnen
CREATE TABLE T_WBCI_GF_BILLING_ORDER_NO (GESCHAEFTSFALL_ID NUMBER(19, 0) NOT NULL, BILLING_ORDER__NO NUMBER(19, 0) NOT NULL);

ALTER TABLE T_WBCI_GF_BILLING_ORDER_NO ADD CONSTRAINT FK_WBCI_GESCHAEFTSFALL_ID FOREIGN KEY (GESCHAEFTSFALL_ID) REFERENCES T_WBCI_GESCHAEFTSFALL;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_WBCI_GF_BILLING_ORDER_NO TO R_HURRICAN_USER;
GRANT SELECT ON T_WBCI_GF_BILLING_ORDER_NO TO R_HURRICAN_READ_ONLY;

