/*
 * API Party
 * ## TMF API Reference : TMF 632 - Party   ### Release : 19.0   The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3 rd payer for a given offer and, then, allows consultation or update of his information.  ### Resources - Organization - Individual - Hub  Party API performs the following operations : - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organizatin or individual
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.pm.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.io.Serializable;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.List;

        /**
* Individual represents a single human being (a man, woman or child). The individual can be a customer, an employee or any other person that the organization needs to store information about. Skipped properties: id,href
*/
    @JsonPropertyOrder({
        IndividualUpdate.JSON_PROPERTY_ARISTOCRATIC_TITLE,
        IndividualUpdate.JSON_PROPERTY_BIRTH_DATE,
        IndividualUpdate.JSON_PROPERTY_COUNTRY_OF_BIRTH,
        IndividualUpdate.JSON_PROPERTY_DEATH_DATE,
        IndividualUpdate.JSON_PROPERTY_FAMILY_NAME,
        IndividualUpdate.JSON_PROPERTY_FAMILY_NAME_PREFIX,
        IndividualUpdate.JSON_PROPERTY_FORMATTED_NAME,
        IndividualUpdate.JSON_PROPERTY_FULL_NAME,
        IndividualUpdate.JSON_PROPERTY_GENDER,
        IndividualUpdate.JSON_PROPERTY_GENERATION,
        IndividualUpdate.JSON_PROPERTY_GIVEN_NAME,
        IndividualUpdate.JSON_PROPERTY_LEGAL_NAME,
        IndividualUpdate.JSON_PROPERTY_LOCATION,
        IndividualUpdate.JSON_PROPERTY_MARITAL_STATUS,
        IndividualUpdate.JSON_PROPERTY_MIDDLE_NAME,
        IndividualUpdate.JSON_PROPERTY_NATIONALITY,
        IndividualUpdate.JSON_PROPERTY_PLACE_OF_BIRTH,
        IndividualUpdate.JSON_PROPERTY_PREFERRED_GIVEN_NAME,
        IndividualUpdate.JSON_PROPERTY_TITLE,
        IndividualUpdate.JSON_PROPERTY_CONTACT_MEDIUM,
        IndividualUpdate.JSON_PROPERTY_CREDIT_RATING,
        IndividualUpdate.JSON_PROPERTY_DISABILITY,
        IndividualUpdate.JSON_PROPERTY_EXTERNAL_REFERENCE,
        IndividualUpdate.JSON_PROPERTY_INDIVIDUAL_IDENTIFICATION,
        IndividualUpdate.JSON_PROPERTY_LANGUAGE_ABILITY,
        IndividualUpdate.JSON_PROPERTY_OTHER_NAME,
        IndividualUpdate.JSON_PROPERTY_PARTY_CHARACTERISTIC,
        IndividualUpdate.JSON_PROPERTY_RELATED_PARTY,
        IndividualUpdate.JSON_PROPERTY_SKILL,
        IndividualUpdate.JSON_PROPERTY_STATUS,
        IndividualUpdate.JSON_PROPERTY_TAX_EXEMPTION_CERTIFICATE,
        IndividualUpdate.JSON_PROPERTY_AT_BASE_TYPE,
        IndividualUpdate.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        IndividualUpdate.JSON_PROPERTY_AT_TYPE
    })
            @JsonTypeName("Individual_Update")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class IndividualUpdate implements Serializable {
        public static final String JSON_PROPERTY_ARISTOCRATIC_TITLE = "aristocraticTitle";
            private String aristocraticTitle;

        public static final String JSON_PROPERTY_BIRTH_DATE = "birthDate";
            private OffsetDateTime birthDate;

        public static final String JSON_PROPERTY_COUNTRY_OF_BIRTH = "countryOfBirth";
            private String countryOfBirth;

        public static final String JSON_PROPERTY_DEATH_DATE = "deathDate";
            private OffsetDateTime deathDate;

        public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
            private String familyName;

        public static final String JSON_PROPERTY_FAMILY_NAME_PREFIX = "familyNamePrefix";
            private String familyNamePrefix;

        public static final String JSON_PROPERTY_FORMATTED_NAME = "formattedName";
            private String formattedName;

        public static final String JSON_PROPERTY_FULL_NAME = "fullName";
            private String fullName;

        public static final String JSON_PROPERTY_GENDER = "gender";
            private String gender;

        public static final String JSON_PROPERTY_GENERATION = "generation";
            private String generation;

        public static final String JSON_PROPERTY_GIVEN_NAME = "givenName";
            private String givenName;

        public static final String JSON_PROPERTY_LEGAL_NAME = "legalName";
            private String legalName;

        public static final String JSON_PROPERTY_LOCATION = "location";
            private String location;

        public static final String JSON_PROPERTY_MARITAL_STATUS = "maritalStatus";
            private String maritalStatus;

        public static final String JSON_PROPERTY_MIDDLE_NAME = "middleName";
            private String middleName;

        public static final String JSON_PROPERTY_NATIONALITY = "nationality";
            private String nationality;

        public static final String JSON_PROPERTY_PLACE_OF_BIRTH = "placeOfBirth";
            private String placeOfBirth;

        public static final String JSON_PROPERTY_PREFERRED_GIVEN_NAME = "preferredGivenName";
            private String preferredGivenName;

        public static final String JSON_PROPERTY_TITLE = "title";
            private String title;

        public static final String JSON_PROPERTY_CONTACT_MEDIUM = "contactMedium";
            private List<ContactMedium> contactMedium;

        public static final String JSON_PROPERTY_CREDIT_RATING = "creditRating";
            private List<PartyCreditProfile> creditRating;

        public static final String JSON_PROPERTY_DISABILITY = "disability";
            private List<Disability> disability;

        public static final String JSON_PROPERTY_EXTERNAL_REFERENCE = "externalReference";
            private List<ExternalReference> externalReference;

        public static final String JSON_PROPERTY_INDIVIDUAL_IDENTIFICATION = "individualIdentification";
            private List<IndividualIdentification> individualIdentification;

        public static final String JSON_PROPERTY_LANGUAGE_ABILITY = "languageAbility";
            private List<LanguageAbility> languageAbility;

        public static final String JSON_PROPERTY_OTHER_NAME = "otherName";
            private List<OtherNameIndividual> otherName;

        public static final String JSON_PROPERTY_PARTY_CHARACTERISTIC = "partyCharacteristic";
            private List<Characteristic> partyCharacteristic;

        public static final String JSON_PROPERTY_RELATED_PARTY = "relatedParty";
            private List<RelatedParty> relatedParty;

        public static final String JSON_PROPERTY_SKILL = "skill";
            private List<Skill> skill;

        public static final String JSON_PROPERTY_STATUS = "status";
            private IndividualStateType status;

        public static final String JSON_PROPERTY_TAX_EXEMPTION_CERTIFICATE = "taxExemptionCertificate";
            private List<TaxExemptionCertificate> taxExemptionCertificate;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

