/*
 * API Party
 * ## TMF API Reference : TMF 632 - Party   ### Release : 19.0   The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3 rd payer for a given offer and, then, allows consultation or update of his information.  ### Resources - Organization - Individual - Hub  Party API performs the following operations : - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organizatin or individual
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.pm.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.io.Serializable;
import java.net.URI;
import java.util.List;

        /**
* Organization represents a group of people identified by shared interests or purpose. Examples include business, department and enterprise. Because of the complex nature of many businesses, both organizations and organization units are represented by the same data. Skipped properties: id,href
*/
    @JsonPropertyOrder({
        OrganizationCreate.JSON_PROPERTY_IS_HEAD_OFFICE,
        OrganizationCreate.JSON_PROPERTY_IS_LEGAL_ENTITY,
        OrganizationCreate.JSON_PROPERTY_NAME,
        OrganizationCreate.JSON_PROPERTY_NAME_TYPE,
        OrganizationCreate.JSON_PROPERTY_ORGANIZATION_TYPE,
        OrganizationCreate.JSON_PROPERTY_TRADING_NAME,
        OrganizationCreate.JSON_PROPERTY_CONTACT_MEDIUM,
        OrganizationCreate.JSON_PROPERTY_CREDIT_RATING,
        OrganizationCreate.JSON_PROPERTY_EXISTS_DURING,
        OrganizationCreate.JSON_PROPERTY_EXTERNAL_REFERENCE,
        OrganizationCreate.JSON_PROPERTY_ORGANIZATION_CHILD_RELATIONSHIP,
        OrganizationCreate.JSON_PROPERTY_ORGANIZATION_IDENTIFICATION,
        OrganizationCreate.JSON_PROPERTY_ORGANIZATION_PARENT_RELATIONSHIP,
        OrganizationCreate.JSON_PROPERTY_OTHER_NAME,
        OrganizationCreate.JSON_PROPERTY_PARTY_CHARACTERISTIC,
        OrganizationCreate.JSON_PROPERTY_RELATED_PARTY,
        OrganizationCreate.JSON_PROPERTY_STATUS,
        OrganizationCreate.JSON_PROPERTY_TAX_EXEMPTION_CERTIFICATE,
        OrganizationCreate.JSON_PROPERTY_AT_BASE_TYPE,
        OrganizationCreate.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        OrganizationCreate.JSON_PROPERTY_AT_TYPE
    })
            @JsonTypeName("Organization_Create")
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class OrganizationCreate implements Serializable {
        public static final String JSON_PROPERTY_IS_HEAD_OFFICE = "isHeadOffice";
            private Boolean isHeadOffice;

        public static final String JSON_PROPERTY_IS_LEGAL_ENTITY = "isLegalEntity";
            private Boolean isLegalEntity;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_NAME_TYPE = "nameType";
            private String nameType;

        public static final String JSON_PROPERTY_ORGANIZATION_TYPE = "organizationType";
            private String organizationType;

        public static final String JSON_PROPERTY_TRADING_NAME = "tradingName";
            private String tradingName;

        public static final String JSON_PROPERTY_CONTACT_MEDIUM = "contactMedium";
            private List<ContactMedium> contactMedium;

        public static final String JSON_PROPERTY_CREDIT_RATING = "creditRating";
            private List<PartyCreditProfile> creditRating;

        public static final String JSON_PROPERTY_EXISTS_DURING = "existsDuring";
            private TimePeriod existsDuring;

        public static final String JSON_PROPERTY_EXTERNAL_REFERENCE = "externalReference";
            private List<ExternalReference> externalReference;

        public static final String JSON_PROPERTY_ORGANIZATION_CHILD_RELATIONSHIP = "organizationChildRelationship";
            private List<OrganizationChildRelationship> organizationChildRelationship;

        public static final String JSON_PROPERTY_ORGANIZATION_IDENTIFICATION = "organizationIdentification";
            private List<OrganizationIdentification> organizationIdentification;

        public static final String JSON_PROPERTY_ORGANIZATION_PARENT_RELATIONSHIP = "organizationParentRelationship";
            private OrganizationParentRelationship organizationParentRelationship;

        public static final String JSON_PROPERTY_OTHER_NAME = "otherName";
            private List<OtherNameOrganization> otherName;

        public static final String JSON_PROPERTY_PARTY_CHARACTERISTIC = "partyCharacteristic";
            private List<Characteristic> partyCharacteristic;

        public static final String JSON_PROPERTY_RELATED_PARTY = "relatedParty";
            private List<RelatedParty> relatedParty;

        public static final String JSON_PROPERTY_STATUS = "status";
            private OrganizationStateType status;

        public static final String JSON_PROPERTY_TAX_EXEMPTION_CERTIFICATE = "taxExemptionCertificate";
            private List<TaxExemptionCertificate> taxExemptionCertificate;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

