-- added missing unique key constraints for storno and tv change ids

-- all existing change ids have to be reset (i.e. set to null), so that the unique constraints can be applied
UPDATE T_WBCI_MELDUNG SET AENDERUNG_ID_REF = NULL, STORNO_ID_REF = NULL;
UPDATE T_WBCI_REQUEST SET AENDERUNGS_ID = NULL;

-- now add the constraints
ALTER TABLE T_WBCI_MELDUNG ADD CONSTRAINT UK_WBCI_MELDUNG_AENDERUNG_ID UNIQUE (AENDERUNG_ID_REF);
ALTER TABLE T_WBCI_MELDUNG ADD CONSTRAINT UK_WBCI_MELDUNG_STORNO_ID UNIQUE (STORNO_ID_REF);
ALTER TABLE T_WBCI_REQUEST ADD CONSTRAINT UK_WBCI_REQUEST_AENDERUNGS_ID UNIQUE (AENDERUNGS_ID);