ALTER TABLE T_CB_VORGANG drop column CBVORGANG_HVT_REF_ID;
ALTER TABLE T_CB_VORGANG ADD CBVORGANG_REF_ID  NUMBER(19);
COMMENT ON COLUMN T_CB_VORGANG.CBVORGANG_REF_ID IS 'Referenz auf einen anderen CB-Vorgang; fuer Umschaltung HVT->KVZ';