-- flag for wita-klaerfall
ALTER TABLE T_CB_VORGANG ADD KLAERFALL NUMBER(1, 0);
UPDATE T_CB_VORGANG SET KLAERFALL = 0;
ALTER TABLE T_CB_VORGANG MODIFY KLAERFALL NUMBER(1, 0) NOT NULL;

-- comments for the wita-klaerfall
ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD (KLAERFALL_BEMERKUNG VARCHAR2(2000 BYTE));
