-- remove wrong column in wbci GF
UPDATE T_WBCI_GESCHAEFTSFALL SET KLAERFALL_BEMERKUNG = null;
ALTER TABLE T_WBCI_GESCHAEFTSFALL DROP COLUMN KLAERFALL_BEMERKUNG;

ALTER TABLE T_CB_VORGANG ADD (KLAERFALL_BEMERKUNG VARCHAR2(2000 BYTE));