-- Insert a new columns for the current bearbeiter
ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD (CURRENT_USER_ID NUMBER(19,0));

ALTER TABLE T_WBCI_GESCHAEFTSFALL ADD (AKTUELLER_BEARBEITER_NAME VARCHAR2(50));
