apiVersion: v1
kind: Service
metadata:
  name: agreement-api-service
  namespace: adl
spec:
  $patch: replace
  selector:
    app: agreement-api
  ports:
    - $patch: replace
    - port: 80
      targetPort: 8080
      name: port1
    - port: 8080
      targetPort: 8080
      name: port2