create table T_HW_BG_CHANGE_DLU (
    ID NUMBER(10) NOT NULL
  , HW_BG_CHANGE_ID NUMBER(10) NOT NULL
  , DLU_RACK_ID_OLD NUMBER(10) NOT NULL
  , DLU_NUMBER_NEW VARCHAR2(4) NOT NULL
  , DLU_SWITCH_NEW VARCHAR2(20) NOT NULL
  , DLU_MEDIAGATEWAY_NEW VARCHAR2(50)
  , DLU_ACCESSCONTROLLER_NEW VARCHAR2(50)
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
comment on table T_HW_BG_CHANGE_DLU is 'Tabelle fuer Protokollierung eines DLU Wechsels (EWSD auf HiG bzw. umgekehrt)';
comment on column T_HW_BG_CHANGE_DLU.DLU_RACK_ID_OLD is 'Rack-ID der DLU, die gewechselt werden soll';
comment on column T_HW_BG_CHANGE_DLU.DLU_NUMBER_NEW is 'neue DLU-Nummer';
comment on column T_HW_BG_CHANGE_DLU.DLU_SWITCH_NEW is 'Angabe der Switch-Kennung, dem die neue DLU zugeordnet ist';
comment on column T_HW_BG_CHANGE_DLU.DLU_MEDIAGATEWAY_NEW is 'Angabe des MediaGateways fuer die neue DLU';
comment on column T_HW_BG_CHANGE_DLU.DLU_ACCESSCONTROLLER_NEW is 'Angabe des AccessControllers fuer die neue DLU';

create SEQUENCE S_T_HW_BG_CHANGE_DLU_0 start with 1;
grant select on S_T_HW_BG_CHANGE_DLU_0 to public;

ALTER TABLE T_HW_BG_CHANGE_DLU ADD CONSTRAINT PK_T_HW_BG_CHANGE_DLU PRIMARY KEY (ID);

CREATE INDEX IX_FK_HWBGCDLU_2_HWBGC ON T_HW_BG_CHANGE_DLU (HW_BG_CHANGE_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_DLU ADD CONSTRAINT FK_HWBGCDLU_2_HWBGC
  FOREIGN KEY (HW_BG_CHANGE_ID) REFERENCES T_HW_BG_CHANGE (ID);

CREATE INDEX IX_FK_HWBGCDLU_2_RACK ON T_HW_BG_CHANGE_DLU (DLU_RACK_ID_OLD) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_DLU ADD CONSTRAINT FK_HWBGCDLU_2_RACK
  FOREIGN KEY (DLU_RACK_ID_OLD) REFERENCES T_HW_RACK (ID);

GRANT SELECT ON T_HW_BG_CHANGE_DLU TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_HW_BG_CHANGE_DLU TO R_HURRICAN_USER;

