create table T_HW_BG_CHANGE_DLU_V5 (
    ID NUMBER(10) NOT NULL
  , HW_BG_CHANGE_DLU_ID NUMBER(10) NOT NULL
  , EQUIPMENT_ID NUMBER(10) NOT NULL
  , HW_EQN VARCHAR2(13) NOT NULL
  , V5_PORT VARCHAR2(13) NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
comment on table T_HW_BG_CHANGE_DLU_V5 is 'Tabelle fuer die Angabe der neuen V5 Ports zu einem (alten) HW_EQN';
comment on column T_HW_BG_CHANGE_DLU_V5.EQUIPMENT_ID is 'ID des Equipments zur HW_EQN, das den V5 Port erhaelt';
comment on column T_HW_BG_CHANGE_DLU_V5.HW_EQN is 'die urspruengliche HW_EQN Bezeichnung des Ports';
comment on column T_HW_BG_CHANGE_DLU_V5.V5_PORT is 'die neue V5 Port Bezeichnung';

create SEQUENCE S_T_HW_BG_CHANGE_DLU_V5_0 start with 1;
grant select on S_T_HW_BG_CHANGE_DLU_V5_0 to public;

ALTER TABLE T_HW_BG_CHANGE_DLU_V5 ADD CONSTRAINT PK_T_HW_BG_CHANGE_DLU_V5 PRIMARY KEY (ID);

CREATE INDEX IX_FK_HWBGCDLUV5_2_HWBGCDLU ON T_HW_BG_CHANGE_DLU_V5 (HW_BG_CHANGE_DLU_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_DLU_V5 ADD CONSTRAINT FK_HWBGCDLUV5_2_HWBGCDLU
  FOREIGN KEY (HW_BG_CHANGE_DLU_ID) REFERENCES T_HW_BG_CHANGE_DLU (ID);

CREATE INDEX IX_FK_HWBGCDLUV5_2_EQ ON T_HW_BG_CHANGE_DLU_V5 (EQUIPMENT_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BG_CHANGE_DLU_V5 ADD CONSTRAINT FK_HWBGCDLUV5_2_EQ
  FOREIGN KEY (EQUIPMENT_ID) REFERENCES T_EQUIPMENT (EQ_ID);

GRANT SELECT ON T_HW_BG_CHANGE_DLU_V5 TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_BG_CHANGE_DLU_V5 TO R_HURRICAN_USER;

