-- Physiktyp-Mapping
-- DSL + a/b
INSERT INTO T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, 
    PARENTPHYSIKTYP_ID, VERSION)
 VALUES
   (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 480, 516, 512, NULL, 
    NULL, 0)
;
-- DSL only
INSERT INTO T_PRODUKT_2_PHYSIKTYP
  (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, 
   PARENTPHYSIKTYP_ID, VERSION)
 VALUES
  (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 480, 517, NULL, NULL, 
   NULL, 0)
;
-- Alcatel IP
-- ADSL2+
INSERT INTO T_PRODUKT_2_PHYSIKTYP
  (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, 
   PARENTPHYSIKTYP_ID, VERSION)
 VALUES
  (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 480, 102, 104, NULL, 
   NULL, 0)
;
-- ADSL2+ only
INSERT INTO T_PRODUKT_2_PHYSIKTYP
  (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, 
   PARENTPHYSIKTYP_ID, VERSION)
 VALUES
  (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 480, 105, NULL, NULL, 
   NULL, 0)
;