-- Leistungsbuendel
-- Surf&Fon-Flat 18 (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77776, NULL, 3401, NULL, 
    0)
;
-- Surf&Fon-Flat 100 (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77778, NULL, 3401, NULL, 
    0)
;
-- Surf&Fon-Flat 25 (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77779, NULL, 3401, NULL, 
    0)
;
-- Surf&Fon-Flat 50 (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77777, NULL, 3401, NULL, 
    0)
;
-- Surf&Fon-Flat 18 Regio (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77780, NULL, 3401, NULL, 
    0)
;
-- Surf&Fon-Flat 25 Regio (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77782, NULL, 3401, NULL, 
    0)
;
-- Surf&Fon-Flat 50 Regio (IPv6)
INSERT INTO T_LB_2_PRODUKT
   (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, 
    VERSION)
 VALUES
   (13, 77781, NULL, 3401, NULL, 
    0)
;
