-- Produktmapping
-- Surf&Fon-Flat 18 (IPv6)
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1230, 480, 513, 'phone_dsl', 0, 1)
;
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1231, 480, 480, 'phone_dsl', 0, 2)
;
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1232, 480, 480, 'phone_dsl', 0, 2)
;
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1232, 997, 480, '.', 0, NULL)
;

-- Surf-Flat 18 (IPv6)
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1233, 481, 512, 'dsl', 0, 1)
;
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1234, 481, 480, 'dsl', 0, 2)
;
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1235, 481, 480, 'dsl', 0, 2)
;
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 VALUES
   (1235, 997, 480, '.', 0, NULL)
;
