--
-- SQL-Script fuer Aenderungen in der Quell-DB (MySQL) VOR der DML-Generierung!
--

DROP TABLE serienbrief;

ALTER TABLE T_PORT_GESAMT ADD ID INT(11);

-- Boolean-Felder auf BIT aendern
alter table T_PRODUKT change DN_BLOCK DN_BLOCK BIT;
alter table T_PRODUKT change BRAUCHT_DN4ACCOUNT BRAUCHT_DN4ACCOUNT BIT;
alter table T_PRODUKT change ELVERLAUF ELVERLAUF BIT;
alter table T_PRODUKT change VPN_PHYSIK VPN_PHYSIK BIT;
alter table T_PRODUKT change PROJEKTIERUNG PROJEKTIERUNG BIT;
alter table T_PRODUKT change IS_PARENT IS_PARENT BIT;
alter table T_PRODUKT change CHECK_CHILD CHECK_CHILD BIT;
alter table T_PRODUKT change IS_COMBI_PRODUKT IS_COMBI_PRODUKT BIT;
alter table T_PRODUKT change AUTO_PRODUCT_CHANGE AUTO_PRODUCT_CHANGE BIT;
alter table T_PRODUKT change EXPORT_KDP_M EXPORT_KDP_M BIT;
alter table T_PRODUKT change CREATE_KDP_ACCOUNT_REPORT CREATE_KDP_ACCOUNT_REPORT BIT;
alter table T_PRODUKT change EXPORT_AK_PRODUKTE EXPORT_AK_PRODUKTE BIT;
alter table T_PRODUKT change BA_RUECKLAEUFER BA_RUECKLAEUFER BIT;
alter table T_PRODUKT change BRAUCHT_VPI_VCI BRAUCHT_VPI_VCI BIT;
alter table T_PRODUKT change ABRECHNUNG_IN_HURRICAN ABRECHNUNG_IN_HURRICAN BIT;
alter table T_PRODUKT change BRAUCHT_BUENDEL BRAUCHT_BUENDEL BIT;
alter table T_PRODUKT change LTGNR_ANLEGEN LTGNR_ANLEGEN BIT;
alter table T_PRODUKT change AUFTRAGSERSTELLUNG AUFTRAGSERSTELLUNG BIT;
alter table T_PRODUKT change BRAUCHT_DN BRAUCHT_DN BIT;

alter table T_ABTEILUNG change RELEVANT_4_PROJ RELEVANT_4_PROJ BIT;
alter table T_ABTEILUNG change RELEVANT_4_BA RELEVANT_4_BA BIT;

alter table T_AK0800 change UEBERNAHME UEBERNAHME BIT;
alter table T_AK0800 change NEUSCHALTUNG NEUSCHALTUNG BIT;

alter table T_AUFTRAG_DATEN change TELBUCH TELBUCH BIT;
alter table T_AUFTRAG_DATEN change INVERSSUCHE INVERSSUCHE BIT;

alter table T_AUFTRAG_TECHNIK change PROJEKTIERUNG PROJEKTIERUNG BIT;

alter table T_BA_VERL_ANLASS change IS_CONFIGURABLE IS_CONFIGURABLE BIT;
alter table T_BA_VERL_ANLASS change IS_AUFTRAGSART IS_AUFTRAGSART BIT;

alter table T_BA_ZUSATZ change AUCH_SM AUCH_SM BIT;

alter table T_CARRIER change CB_NOTWENDIG CB_NOTWENDIG BIT;

alter table T_CARRIERBESTELLUNG change KUNDE_VOR_ORT KUNDE_VOR_ORT BIT;

alter table T_DSLAM change SCHMIDTSCHES_KONZEPT SCHMIDTSCHES_KONZEPT BIT;

alter table T_DSLAM_PROFILE change FASTPATH FASTPATH BIT;

alter table T_EG change CONFIGURABLE CONFIGURABLE BIT;
alter table T_EG change CONF_PORTFORWARDING CONF_PORTFORWARDING BIT;
alter table T_EG change CONF_S0BACKUP CONF_S0BACKUP BIT;

alter table T_EG_2_AUFTRAG change SELBSTABHOLUNG SELBSTABHOLUNG BIT;

alter table T_EG_CONFIG change NAT NAT BIT;
alter table T_EG_CONFIG change DHCP DHCP BIT;

alter table T_EQ_DATEN change NOTSTROM NOTSTROM BIT;
alter table T_EQ_DATEN change KLIMAANLAGE KLIMAANLAGE BIT;
alter table T_EQ_DATEN change ZUGANG_24H ZUGANG_24H BIT;

alter table T_FAKTURA_BEARBEITER change AKT AKT BIT;

alter table T_GUI_DEFINITION change ADD_SEPARATOR ADD_SEPARATOR BIT;
alter table T_GUI_DEFINITION change ACTIVE ACTIVE BIT;

alter table T_HVT_STANDORT change VIRTUELL VIRTUELL BIT;

alter table T_IA_BUDGET change STORNIERT STORNIERT BIT;

alter table T_IA_MAT_ENTNAHME change ENTNAHMETYP ENTNAHMETYP BIT;

alter table T_INT_ACCOUNT change GESPERRT GESPERRT BIT;

alter table T_KUBENA_TDN change VORH VORH BIT;

alter table T_LB_2_LEISTUNG change STANDARD STANDARD BIT;

alter table T_PHYSIKAENDERUNGSTYP change EWSD EWSD BIT;
alter table T_PHYSIKAENDERUNGSTYP change SDH SDH BIT;
alter table T_PHYSIKAENDERUNGSTYP change IPS IPS BIT;
alter table T_PHYSIKAENDERUNGSTYP change SCT SCT BIT;

alter table T_PORT_FORWARD change ACTIVE ACTIVE BIT;

alter table T_PRODUKT_2_PHYSIKTYP change VIRTUELL VIRTUELL BIT;

alter table T_PROD_2_EG change IS_DEFAULT IS_DEFAULT BIT;

alter table T_PROD_2_TECH_LEISTUNG change IS_DEFAULT IS_DEFAULT BIT;

alter table T_PROD_SL_FREIGABE change POSSIBLE POSSIBLE BIT;

alter table T_PVC_VORGABE change IST_VATER IST_VATER BIT;

alter table T_RANGIERUNGSMATRIX change PROJEKTIERUNG PROJEKTIERUNG BIT;

alter table T_RECHNUNGSANSCHRIFT change EINZEL_RE EINZEL_RE BIT;

alter table T_REFERENCE change GUI_VISIBLE GUI_VISIBLE BIT;

alter table T_SDH_PROFIL change VPIVCI_ALLOWED VPIVCI_ALLOWED BIT;

alter table T_SPERRE_INFO change ACTIVE ACTIVE BIT;

alter table T_SPERRKLASSEN change ABGEHEND ABGEHEND BIT;
alter table T_SPERRKLASSEN change NATIONAL NATIONAL BIT;
alter table T_SPERRKLASSEN change INNOVATIVE_DIENSTE INNOVATIVE_DIENSTE BIT;
alter table T_SPERRKLASSEN change MABEZ MABEZ BIT;
alter table T_SPERRKLASSEN change MOBIL MOBIL BIT;
alter table T_SPERRKLASSEN change VPN VPN BIT;
alter table T_SPERRKLASSEN change PRD PRD BIT;
alter table T_SPERRKLASSEN change AUSKUNFTSDIENSTE AUSKUNFTSDIENSTE BIT;
alter table T_SPERRKLASSEN change INTERNATIONAL INTERNATIONAL BIT;
alter table T_SPERRKLASSEN change ANSICHT ANSICHT BIT;
alter table T_SPERRKLASSEN change OFFLINE OFF_LINE BIT;

alter table T_TECH_LEISTUNG change DISPO DISPO BIT;
alter table T_TECH_LEISTUNG change EWSD EWSD BIT;
alter table T_TECH_LEISTUNG change SDH SDH BIT;
alter table T_TECH_LEISTUNG change IPS IPS BIT;
alter table T_TECH_LEISTUNG change SCT SCT BIT;
alter table T_TECH_LEISTUNG change CHECK_QUANTITY CHECK_QUANTITY BIT;
alter table T_TECH_LEISTUNG change SNAPSHOT_REL SNAPSHOT_REL BIT;

alter table T_UEVT change PROJEKTIERUNG PROJEKTIERUNG BIT;

alter table T_VERLAUF change AKT AKT BIT;
alter table T_VERLAUF change VERSCHOBEN VERSCHOBEN BIT;
alter table T_VERLAUF change OBSERVE_PROCESS OBSERVE_PROCESS BIT;

alter table T_VPN_KONF change KANALB KANALB BIT;
alter table T_VPN_KONF change DIAL_OUT DIAL_OUT BIT;

alter table T_AUFTRAG_VOIP change IS_ACTIVE IS_ACTIVE BIT;

alter table T_CB_VORGANG change RET_OK RET_OK BIT;

alter table T_ARCHIV_PARAMETER_2_OBJECT change IS_DEFAULT IS_DEFAULT BIT;
alter table T_ARCHIV_PARAMETER_2_OBJECT change IS_APPEND_KEY IS_APPEND_KEY BIT;

alter table T_ES_ANSP drop foreign key FK_T_ES_ANSP_1;
alter table T_ES_ANSP drop column AUFTRAG_TECHNIK_ID;

alter table T_EG_2_PAKET drop column PROD_ID;

