--
-- ForeignKeys anlegen.
--

ALTER TABLE t_auftrag_import
  ADD CONSTRAINT FK_AUFTRAGIMPORT_2_STATUS
      FOREIGN KEY (IMPORT_STATUS)
      REFERENCES t_auftrag_import_status (ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_AUFTRAG_TECHNIK_2_INTACC
      FOREIGN KEY (INT_ACCOUNT_ID)
      REFERENCES t_int_account (ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_TECHNIK_2_ANBART
      FOREIGN KEY (ANBINDUNGSART_ID)
      REFERENCES t_anbindungsart (ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_ATECHNIK_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_ATECHNIK_2_TDN
      FOREIGN KEY (TDN_ID)
      REFERENCES t_tdn (ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_ATECHNIK_2_ES
      FOREIGN KEY (AT_2_ES_ID)
      REFERENCES t_auftrag_technik_2_endstelle (ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_ATECHNIK_2_VPN
      FOREIGN KEY (VPN_ID)
      REFERENCES t_vpn (VPN_ID);

ALTER TABLE t_auftrag_technik
  ADD CONSTRAINT FK_ATANLASS_2_BAANLASS
      FOREIGN KEY (AUFTRAGSART)
      REFERENCES t_ba_verl_anlass (ID);

ALTER TABLE t_carrier_kennung
  ADD CONSTRAINT FK_CKENNUNG_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES t_carrier (ID);

ALTER TABLE t_hvt_gruppe
  ADD CONSTRAINT FK_HVTGRUPPE_2_NL
      FOREIGN KEY (NIEDERLASSUNG_ID)
      REFERENCES t_niederlassung (ID);

ALTER TABLE t_abteilung
  ADD CONSTRAINT FK_ABTEILUNG_2_NL
      FOREIGN KEY (NIEDERLASSUNG_ID)
      REFERENCES t_niederlassung (ID);

ALTER TABLE t_hvt_standort
  ADD CONSTRAINT FK_HVTSTD_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES t_carrier (ID);

ALTER TABLE t_hvt_standort
  ADD CONSTRAINT FK_HVTSTD_2_CKENNUNG
      FOREIGN KEY (CARRIER_KENNUNG_ID)
      REFERENCES t_carrier_kennung (ID);

ALTER TABLE t_hvt_standort
  ADD CONSTRAINT FK_HVTSTD_2_HVTGR
      FOREIGN KEY (HVT_GRUPPE_ID)
      REFERENCES t_hvt_gruppe (HVT_GRUPPE_ID);

ALTER TABLE t_eg_2_auftrag
  ADD CONSTRAINT FK_EG2A_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID);

ALTER TABLE t_eg_2_auftrag
  ADD CONSTRAINT FK_EG2A_2_EG
      FOREIGN KEY (EG_ID)
      REFERENCES t_eg (ID);

ALTER TABLE t_eg_2_auftrag
  ADD CONSTRAINT FK_EG2A_2_EGHERKUNFT
      FOREIGN KEY (EG_HERKUNFT)
      REFERENCES t_eg_herkunft (ID);

ALTER TABLE t_eg_2_auftrag
  ADD CONSTRAINT FK_EG2A_2_MONTAGEART
      FOREIGN KEY (MONTAGEART)
      REFERENCES t_montageart (ID);

ALTER TABLE t_lieferschein
  ADD CONSTRAINT FK_LIEFERSCHEIN_2_REPREQ
      FOREIGN KEY (REQUEST_ID)
      REFERENCES t_report_request (ID);

ALTER TABLE t_lieferschein
  ADD CONSTRAINT FK_LIEFERSCHEIN_2_REFSTATUS
      FOREIGN KEY (STATUS_ID)
      REFERENCES t_reference (ID);

ALTER TABLE t_lieferschein
  ADD CONSTRAINT FK_LIEFERSCHEIN_2_REFREASON
      FOREIGN KEY (RETOURE_GRUND_ID)
      REFERENCES t_reference (ID);
      

ALTER TABLE t_physiktyp
  ADD CONSTRAINT FK_PHYSIKTYP_2_HVTTEC
      FOREIGN KEY (HVT_TECHNIK_ID)
      REFERENCES t_hvt_technik (ID);

ALTER TABLE t_dslam
  ADD CONSTRAINT FK_DSLAM_2_HVTTECH
      FOREIGN KEY (HVT_TECHNIK_ID)
      REFERENCES t_hvt_technik (ID);

ALTER TABLE t_dslam
  ADD CONSTRAINT FK_DSLAM_2_HVTSTD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

ALTER TABLE t_eq_objekt
  ADD CONSTRAINT FK_EQ_OBJEKT_2_GEBAEUDE
      FOREIGN KEY (GEBAEUDE_ID)
      REFERENCES t_eq_gebaeude (ID);

ALTER TABLE t_equipment
  ADD CONSTRAINT FK_EQUIPMENT_2_DSLAM
      FOREIGN KEY (DSLAM_ID)
      REFERENCES t_dslam (DSLAM);

ALTER TABLE t_equipment
  ADD CONSTRAINT FK_EQUIPMENT_2_HVTST
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

ALTER TABLE t_faktura_nr
  ADD CONSTRAINT FK_FAKTURANR_2_MONAT
      FOREIGN KEY (FAKTURA_MONAT)
      REFERENCES t_faktura_monat (ID);

ALTER TABLE t_faktura_nr
  ADD CONSTRAINT FK_FAKTURANR_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES t_rechnungsanschrift (ID);

ALTER TABLE t_faktura_nr
  ADD CONSTRAINT FK_FAKTURA_2_BEARB
      FOREIGN KEY (BEARBEITER)
      REFERENCES t_faktura_bearbeiter (ID);

ALTER TABLE t_hvt_bestellung
  ADD CONSTRAINT FK_HVTBEST_2_UEVT
      FOREIGN KEY (UEVT_ID)
      REFERENCES t_uevt (UEVT_ID);

ALTER TABLE t_produkt
  ADD CONSTRAINT FK_PRODUKT_2_ABT
      FOREIGN KEY (VERTEILUNG_DURCH)
      REFERENCES t_abteilung (ID);

ALTER TABLE t_produkt
  ADD CONSTRAINT FK_PRODUKT_2_LART
      FOREIGN KEY (LEITUNGSART)
      REFERENCES t_leitungsart (ID);

ALTER TABLE t_produkt
  ADD CONSTRAINT FK_T_PRODUKT_2_GRUPPE
      FOREIGN KEY (PRODUKTGRUPPE_ID)
      REFERENCES t_produktgruppe (ID);

ALTER TABLE t_produkt
  ADD CONSTRAINT FK_PROD_2_VERLCHAIN
      FOREIGN KEY (VERLAUF_CHAIN_ID)
      REFERENCES t_service_chain (ID);

ALTER TABLE t_produkt
  ADD CONSTRAINT FK_PROD_2_VERLCANCELCHAIN
      FOREIGN KEY (VERLAUF_CANCEL_CHAIN_ID)
      REFERENCES t_service_chain (ID);

ALTER TABLE t_rangierung
  ADD CONSTRAINT FK_RANGOUT_2_EQ
      FOREIGN KEY (EQ_OUT_ID)
      REFERENCES t_equipment (EQ_ID);

ALTER TABLE t_rangierung
  ADD CONSTRAINT FK_RANG_2_PHYSIKTYP
      FOREIGN KEY (PHYSIK_TYP)
      REFERENCES t_physiktyp (ID);

ALTER TABLE t_rangierung
  ADD CONSTRAINT FK_RANGINT_2_EQ
      FOREIGN KEY (EQ_IN_ID)
      REFERENCES t_equipment (EQ_ID);

ALTER TABLE t_rangierung
  ADD CONSTRAINT FK_RANG_2_HVTSTD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

ALTER TABLE t_rangierung
  ADD CONSTRAINT FK_RANG_2_RANGAUFTRAG
      FOREIGN KEY (RAUFTRAG_ID)
      REFERENCES t_rangierungs_auftrag (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ENDSTELLE_2_RANG
      FOREIGN KEY (RANGIER_ID)
      REFERENCES t_rangierung (RANGIER_ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ENDSTELLE_2_ANSCHLUSSART
      FOREIGN KEY (ANSCHLUSSART)
      REFERENCES t_anschlussart (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ENDSTELLE_2_MONTAGEART
      FOREIGN KEY (NT_MONTAGEART)
      REFERENCES t_montageart (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ES_2_CB2ES
      FOREIGN KEY (CB_2_ES_ID)
      REFERENCES t_cb_2_es (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ES_RADD_2_RANG
      FOREIGN KEY (RANGIER_ID_ADDITIONAL)
      REFERENCES t_rangierung (RANGIER_ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_T_ENDSTELLE_2_SL
      FOREIGN KEY (SL_ID)
      REFERENCES t_strassenliste (SL_ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_T_ENDSTELLE_2_HVTSTD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_T_ENDSTELLE_2_ESGR
      FOREIGN KEY (ES_GRUPPE)
      REFERENCES t_auftrag_technik_2_endstelle (ID);

ALTER TABLE t_rechnungsanschrift
  ADD CONSTRAINT FK_RAMWST_2_REF
      FOREIGN KEY (MWST_ID)
      REFERENCES t_reference (ID);

ALTER TABLE t_strassenliste
  ADD CONSTRAINT FK_STRASSENLISTE_2_HVTGR
      FOREIGN KEY (HVT_GRUPPE_ID)
      REFERENCES t_hvt_gruppe (HVT_GRUPPE_ID);

ALTER TABLE t_tal_aenderungstyp
  ADD CONSTRAINT FK_TAL_AENDERUNGSTYP_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES t_carrier (ID);

ALTER TABLE t_uevt
  ADD CONSTRAINT FK_T_UEVT_1
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

ALTER TABLE t_ba_verl_anlass
  ADD CONSTRAINT FK_BA_VERL_ANLASS_2_AENDGROUP
      FOREIGN KEY (BA_VERL_GRUPPE)
      REFERENCES t_ba_verl_aend_gruppe (ID);

ALTER TABLE t_produkt_2_physiktyp
  ADD CONSTRAINT FK_P2PTADD_2_PHYSIKTYP
      FOREIGN KEY (PHYSIKTYP_ADDITIONAL)
      REFERENCES t_physiktyp (ID);

ALTER TABLE t_produkt_2_physiktyp
  ADD CONSTRAINT FK_P2PT_2_PT
      FOREIGN KEY (PARENTPHYSIKTYP_ID)
      REFERENCES t_physiktyp (ID);

ALTER TABLE t_produkt_2_physiktyp
  ADD CONSTRAINT FK_PROD2PTYP_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID);

ALTER TABLE t_produkt_2_physiktyp
  ADD CONSTRAINT FK_PROD2PTYP_2_PTYP
      FOREIGN KEY (PHYSIKTYP)
      REFERENCES t_physiktyp (ID);

ALTER TABLE t_ba_verl_config
  ADD CONSTRAINT FK_VERLCONF_2_ABTCONF
      FOREIGN KEY (ABT_CONFIG_ID)
      REFERENCES t_ba_abt_config (ID);

ALTER TABLE t_ba_verl_config
  ADD CONSTRAINT FK_BAVERLCONFIG_2_ANLASS
      FOREIGN KEY (ANLASS)
      REFERENCES t_ba_verl_anlass (ID);

ALTER TABLE t_ia
  ADD CONSTRAINT FK_IA_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID);

ALTER TABLE t_ia
  ADD CONSTRAINT FK_IA_2_RANGAUFTRAG
      FOREIGN KEY (RANGIERUNGS_AUFTRAG_ID)
      REFERENCES t_rangierungs_auftrag (ID);

ALTER TABLE t_verlauf
  ADD CONSTRAINT FK_VERLAUF_2_AS
      FOREIGN KEY (STATUS_ID_ALT)
      REFERENCES t_auftrag_status (ID)
;

ALTER TABLE t_verlauf
  ADD CONSTRAINT FK_VERLAUF_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_verlauf
  ADD CONSTRAINT FK_VERLAUF_2_VS
      FOREIGN KEY (VERLAUF_STATUS_ID)
      REFERENCES t_verlauf_status (ID)
;

ALTER TABLE t_verlauf
  ADD CONSTRAINT FK_VERL_2_PORTART
      FOREIGN KEY (PORTIERUNGSART)
      REFERENCES t_portierungsart (ID)
;

ALTER TABLE t_verlauf
  ADD CONSTRAINT FK_VERLAUF_2_BAANLASS
      FOREIGN KEY (ANLASS)
      REFERENCES t_ba_verl_anlass (ID)
;

ALTER TABLE t_ia_budget
  ADD CONSTRAINT FK_IABUDGET_2_IA
      FOREIGN KEY (IA_ID)
      REFERENCES t_ia (ID)
;

ALTER TABLE t_ia_mat_entnahme
  ADD CONSTRAINT FK_IAMATENT_2_BUDGET
      FOREIGN KEY (BUDGET_ID)
      REFERENCES t_ia_budget (ID)
;

ALTER TABLE t_ia_mat_entnahme
  ADD CONSTRAINT FK_IAMATENT_2_LAGER
      FOREIGN KEY (LAGER_ID)
      REFERENCES t_lager (ID)
;

ALTER TABLE T_DSLAM_PROFILE
  ADD CONSTRAINT FK_DP_2_TECHLS_DOWN
      FOREIGN KEY (DOWNSTREAM_TECH_LS)
      REFERENCES t_tech_leistung (ID)
;

ALTER TABLE T_DSLAM_PROFILE
  ADD CONSTRAINT FK_DP_2_TECHLS_UP
      FOREIGN KEY (UPSTREAM_TECH_LS)
      REFERENCES t_tech_leistung (ID)
;

ALTER TABLE T_DSLAM_PROFILE
  ADD CONSTRAINT FK_DP_2_TECHLS_FAST
      FOREIGN KEY (FASTPATH_TECH_LS)
      REFERENCES t_tech_leistung (ID)
;

ALTER TABLE T_DSLAM_PROFILE_CHANGE
  ADD CONSTRAINT FK_DPC_2_REASON
      FOREIGN KEY (CHANGE_REASON_ID)
      REFERENCES T_DSLAM_PROFILE_CHANGE_REASON (ID)
;

ALTER TABLE t_auftrag_2_tech_ls
  ADD CONSTRAINT FK_ATLS_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_auftrag_2_tech_ls
  ADD CONSTRAINT FK_ATLS_2_TECHLS
      FOREIGN KEY (TECH_LS_ID)
      REFERENCES t_tech_leistung (ID)
;

ALTER TABLE t_auftrag_2_tech_ls
  ADD CONSTRAINT FK_ATLS_KUEND_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID_KUEND)
      REFERENCES t_verlauf (ID)
;

ALTER TABLE t_auftrag_2_tech_ls
  ADD CONSTRAINT FK_ATLS_REAL_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID_REAL)
      REFERENCES t_verlauf (ID)
;

ALTER TABLE t_auftrag_daten
  ADD CONSTRAINT FK_ADMMZ_2_REF
      FOREIGN KEY (MMZ_ID)
      REFERENCES t_reference (ID)
;

ALTER TABLE t_auftrag_daten
  ADD CONSTRAINT FK_AUFTRAGDATEN_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_auftrag_daten
  ADD CONSTRAINT FK_ADATEN_2_ASTATUS
      FOREIGN KEY (STATUS_ID)
      REFERENCES t_auftrag_status (ID)
;

ALTER TABLE t_auftrag_daten
  ADD CONSTRAINT FK_T_ADATEN_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_auftrag_faktura
  ADD CONSTRAINT FK_AFAKTURA_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_auftrag_faktura
  ADD CONSTRAINT FK_AUFTRAG_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES t_rechnungsanschrift (ID)
;

ALTER TABLE t_auftrag_import_files
  ADD CONSTRAINT FK_AIMPORTFILES_2_AIMP
      FOREIGN KEY (AUFTRAG_IMPORT_ID)
      REFERENCES t_auftrag_import (ID)
;

ALTER TABLE t_ba_verl_aend_prod_2_gruppe
  ADD CONSTRAINT FK_BAVAENDP2GR_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_ba_verl_aend_prod_2_gruppe
  ADD CONSTRAINT FK_BAVAENDP2GR_2_BAVG
      FOREIGN KEY (BA_VERL_AEND_GRUPPE_ID)
      REFERENCES t_ba_verl_aend_gruppe (ID)
;

ALTER TABLE t_bankverbindung
  ADD CONSTRAINT FK_BANK_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES t_rechnungsanschrift (ID)
;

ALTER TABLE t_carrier_lbz
  ADD CONSTRAINT FK_CARRIER_LBZ_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES t_carrier (ID)
;

ALTER TABLE t_carrierbestellung
  ADD CONSTRAINT FK_CB_2_AENDERUNGSTYP
      FOREIGN KEY (TAL_NA_TYP)
      REFERENCES t_tal_aenderungstyp (ID)
;

ALTER TABLE t_carrierbestellung
  ADD CONSTRAINT FK_CB_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID_4_TAL_NA)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_carrierbestellung
  ADD CONSTRAINT FK_CB_2_CB2ES
      FOREIGN KEY (CB_2_ES_ID)
      REFERENCES t_cb_2_es (ID)
;

ALTER TABLE t_carrierbestellung
  ADD CONSTRAINT FK_CB_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES t_carrier (ID)
;

ALTER TABLE t_eg_config
  ADD CONSTRAINT FK_IPCONFIG_2_EG2A
      FOREIGN KEY (EG2A_ID)
      REFERENCES t_eg_2_auftrag (ID)
;

ALTER TABLE t_eq_daten
  ADD CONSTRAINT FK_EQ_DATEN_2_OBJEKT
      FOREIGN KEY (OBJEKT_ID)
      REFERENCES t_eq_objekt (ID)
;

ALTER TABLE t_eq_daten
  ADD CONSTRAINT FK_EQ_DATEN_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES t_rechnungsanschrift (ID)
;

ALTER TABLE t_es_ansp
  ADD CONSTRAINT FK_ES_ANSP_2_ES
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
;

ALTER TABLE t_es_ltg_daten
  ADD CONSTRAINT FK_LTG_DATEN_2_LART
      FOREIGN KEY (LEITUNGSART)
      REFERENCES t_leitungsart (ID)
;

ALTER TABLE t_es_ltg_daten
  ADD CONSTRAINT FK_ESLTGDATEN_2_SCHNITT
      FOREIGN KEY (SCHNITTSTELLE_ID)
      REFERENCES t_schnittstelle (ID)
;

ALTER TABLE t_es_ltg_daten
  ADD CONSTRAINT FK_ESLTGDATEN_2_ES
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
;

ALTER TABLE t_faktura
  ADD CONSTRAINT FK_FAKTURA_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_faktura
  ADD CONSTRAINT FK_FAKTURA_2_FNR
      FOREIGN KEY (FNR_ID)
      REFERENCES t_faktura_nr (ID)
;

ALTER TABLE t_faktura_no
  ADD CONSTRAINT FK_FAKTURANO_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_faktura_no
  ADD CONSTRAINT FK_FAKTURANO_2_MONAT
      FOREIGN KEY (FAKTURA_MONAT)
      REFERENCES t_faktura_monat (ID)
;

ALTER TABLE t_gui_mapping
  ADD CONSTRAINT FK_GUI_MAPPING_2_GUIDEF
      FOREIGN KEY (GUI_ID)
      REFERENCES t_gui_definition (ID)
;

ALTER TABLE t_hvt_bes_hist
  ADD CONSTRAINT FK_HVTBESHIST_2_HVTBEST
      FOREIGN KEY (BEST_ID)
      REFERENCES t_hvt_bestellung (ID)
;

ALTER TABLE t_hvt_standort_2_technik
  ADD CONSTRAINT FK_ST2T_2_STD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT)
;

ALTER TABLE t_hvt_standort_2_technik
  ADD CONSTRAINT FK_ST2T_2_TECHNIK
      FOREIGN KEY (HVT_TECHNIK_ID)
      REFERENCES t_hvt_technik (ID)
;

ALTER TABLE t_inhouse
  ADD CONSTRAINT FK_T_INHOUSE_2_ES
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
;

ALTER TABLE t_int_druck
  ADD CONSTRAINT FK_INT_DRUCK_2_INTACCOUNT
      FOREIGN KEY (INT_ACCOUNT_ID)
      REFERENCES t_int_account (ID)
;

ALTER TABLE t_kubena_hvt
  ADD CONSTRAINT FK_KUBENAHVT_2_KUBENA
      FOREIGN KEY (KUBENA_ID)
      REFERENCES t_kubena (ID)
;

ALTER TABLE t_kubena_hvt
  ADD CONSTRAINT FK_KUBENAHVT_2_HVTSTD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT)
;

ALTER TABLE t_kubena_prod
  ADD CONSTRAINT FK_KUBENAPROD_2_KUBENA
      FOREIGN KEY (KUBENA_ID)
      REFERENCES t_kubena (ID)
;

ALTER TABLE t_kubena_prod
  ADD CONSTRAINT FK_KUBENAPROD_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_kubena_tdn
  ADD CONSTRAINT FK_KUBENATDN_2_KUBENA
      FOREIGN KEY (KUBENA_ID)
      REFERENCES t_kubena (ID)
;

ALTER TABLE t_lb_2_leistung
  ADD CONSTRAINT FK_LB_2_Leistung_1
      FOREIGN KEY (LB_ID)
      REFERENCES t_leistungsbuendel (ID)
;

ALTER TABLE t_lb_2_leistung
  ADD CONSTRAINT FK_LB2LST_2_LEISTUNG
      FOREIGN KEY (LEISTUNG_ID)
      REFERENCES t_leistung_4_dn (ID)
;

ALTER TABLE t_lb_2_produkt
  ADD CONSTRAINT FK_LB2PROD_2_LB
      FOREIGN KEY (LB_ID)
      REFERENCES t_leistungsbuendel (ID)
;

ALTER TABLE t_leistung_2_parameter
  ADD CONSTRAINT FK_LST2PARAM_2_LPARAM
      FOREIGN KEY (LEISTUNG_PARAMETER_ID)
      REFERENCES t_leistung_parameter (ID)
;

ALTER TABLE t_leistung_2_parameter
  ADD CONSTRAINT FK_LST2PARAM_2_LST
      FOREIGN KEY (LEISTUNG_ID)
      REFERENCES t_leistung_4_dn (ID)
;

ALTER TABLE t_leistung_dn
  ADD CONSTRAINT FK_LEISTUNGDN_2_LEISTUNG4DN
      FOREIGN KEY (LEISTUNG4DN_ID)
      REFERENCES t_leistung_4_dn (ID)
;

ALTER TABLE t_leistung_dn
  ADD CONSTRAINT FK_LEISTUNGDN_2_LEISTBUENDEL
      FOREIGN KEY (LEISTUNGSBUENDEL_ID)
      REFERENCES t_leistungsbuendel (ID)
;

ALTER TABLE t_physikuebernahme
  ADD CONSTRAINT FK_PHYSIKUEB_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES t_verlauf (ID)
;

ALTER TABLE t_physikuebernahme
  ADD CONSTRAINT FK_PHYSIKUEB_2_TYP
      FOREIGN KEY (AENDERUNGSTYP)
      REFERENCES t_physikaenderungstyp (ID)
;

ALTER TABLE t_physikuebernahme
  ADD CONSTRAINT FK_PU_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID_A)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_physikuebernahme
  ADD CONSTRAINT FK_PU_2_AUFTRAG_B
      FOREIGN KEY (AUFTRAG_ID_B)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_port_forward
  ADD CONSTRAINT FK_PORTFW_2_REF
      FOREIGN KEY (PROTOCOL)
      REFERENCES t_reference (ID)
;

ALTER TABLE t_prod_2_eg
  ADD CONSTRAINT FK_PROD2EG_2_EG
      FOREIGN KEY (EG_ID)
      REFERENCES t_eg (ID)
;

ALTER TABLE t_prod_2_eg
  ADD CONSTRAINT FK_PROD2EG_2_PRODUKT
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_prod_2_prod
  ADD CONSTRAINT FK_P2PDEST_2_PROD
      FOREIGN KEY (PROD_DEST)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_prod_2_prod
  ADD CONSTRAINT FK_P2PSRC_2_PROD
      FOREIGN KEY (PROD_SRC)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_prod_2_prod
  ADD CONSTRAINT FK_P2P_2_CHAIN
      FOREIGN KEY (CHAIN_ID)
      REFERENCES t_service_chain (ID)
;

ALTER TABLE t_prod_2_prod
  ADD CONSTRAINT FK_P2P_PHAENDTYP
      FOREIGN KEY (PHYSIKAEND_TYP)
      REFERENCES t_physikaenderungstyp (ID)
;

ALTER TABLE t_prod_2_sl
  ADD CONSTRAINT FK_PRODSL_2_SL
      FOREIGN KEY (SL_ID)
      REFERENCES t_strassenliste (SL_ID)
      ON DELETE CASCADE
;

ALTER TABLE t_prod_2_sl
  ADD CONSTRAINT FK_PRODSL_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_prod_2_sl
  ADD CONSTRAINT FK_PRODSL_2_FREI
      FOREIGN KEY (FREIGABE_ID)
      REFERENCES t_prod_sl_freigabe (ID)
;

ALTER TABLE t_prod_2_tech_leistung
  ADD CONSTRAINT FK_P2TL_2_TL
      FOREIGN KEY (TECH_LS_ID)
      REFERENCES t_tech_leistung (ID)
;

ALTER TABLE t_prod_2_tech_leistung
  ADD CONSTRAINT FK_P2TLS_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_produkt_2_schnittstelle
  ADD CONSTRAINT FK_PROD2SCHN_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_produkt_2_schnittstelle
  ADD CONSTRAINT FK_PROD2SCHN_2_SCHN
      FOREIGN KEY (SCHNITTSTELLE_ID)
      REFERENCES t_schnittstelle (ID)
;

ALTER TABLE t_produkt_mapping
  ADD CONSTRAINT FK_PRODMAP_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_pvc_2_profil
  ADD CONSTRAINT FK_PVC2PROFIL_2_PROFIL
      FOREIGN KEY (PROFIL_ID)
      REFERENCES t_sdh_profil (ID)
;

ALTER TABLE t_pvc_2_profil
  ADD CONSTRAINT FK_PVC2PROFIL_2_PVC
      FOREIGN KEY (PVC_ID)
      REFERENCES t_pvc_vorgabe (ID)
;

ALTER TABLE t_rangierungsmatrix
  ADD CONSTRAINT FK_RMATRIX_2_HVT
      FOREIGN KEY (HVT_STANDORT_ID_ZIEL)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT)
;

ALTER TABLE t_rangierungsmatrix
  ADD CONSTRAINT FK_RMATRIX_2_P2P
      FOREIGN KEY (PRODUKT2PHYSIKTYP_ID)
      REFERENCES t_produkt_2_physiktyp (ID)
;

ALTER TABLE t_rangierungsmatrix
  ADD CONSTRAINT FK_RMATRIX_2_PRODUKT
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_rangierungsmatrix
  ADD CONSTRAINT FK_RMATRIX_2_UEVT
      FOREIGN KEY (UEVT_ID)
      REFERENCES t_uevt (UEVT_ID)
;

ALTER TABLE t_sdh_physik
  ADD CONSTRAINT FK_SDHPHYSIK_2_PROFIL
      FOREIGN KEY (PROFIL_ID)
      REFERENCES t_sdh_profil (ID)
;

ALTER TABLE t_sdh_physik
  ADD CONSTRAINT FK_SDHPHYSIK_2_PVC
      FOREIGN KEY (NETZKOPPLUNG_ID)
      REFERENCES t_pvc_vorgabe (ID)
;

ALTER TABLE t_sdh_physik
  ADD CONSTRAINT FK_SDHPHYSIK_2_PVC_ANSCHALT
      FOREIGN KEY (ANSCHALTPUNKT_ID)
      REFERENCES t_pvc_vorgabe (ID)
;

ALTER TABLE t_sdh_physik
  ADD CONSTRAINT FK_SDH_PHYSIK_2_ES
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
;

ALTER TABLE t_sperre
  ADD CONSTRAINT FK_SPERRE_2_ABT
      FOREIGN KEY (S_ABT_ID)
      REFERENCES t_abteilung (ID)
;

ALTER TABLE t_sperre_info
  ADD CONSTRAINT FK_SPERRE_INFO_2_ABT
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES t_abteilung (ID)
;

ALTER TABLE t_sperre_verteilung
  ADD CONSTRAINT FK_SPERREVERT_2_ABT
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES t_abteilung (ID)
;

ALTER TABLE t_sperre_verteilung
  ADD CONSTRAINT FK_SPERREVERT_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_strassen_details
  ADD CONSTRAINT FK_STRDETAILS_2_SL
      FOREIGN KEY (SL_ID)
      REFERENCES t_strassenliste (SL_ID)
      ON DELETE CASCADE
;

ALTER TABLE t_tdn_zaehler
  ADD CONSTRAINT FK_TDN_ZAEHLER_2_NL
      FOREIGN KEY (NK)
      REFERENCES t_niederlassung (ID)
;

ALTER TABLE t_uevt_2_ziel
  ADD CONSTRAINT FK_UEVT2ZIEL_2_HVT
      FOREIGN KEY (HVT_STANDORT_ID_ZIEL)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT)
;

ALTER TABLE t_uevt_2_ziel
  ADD CONSTRAINT FK_UEVT2ZIEL_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_uevt_2_ziel
  ADD CONSTRAINT FK_UEVT2ZIEL_2_UEVT
      FOREIGN KEY (UEVT_ID)
      REFERENCES t_uevt (UEVT_ID)
;

ALTER TABLE t_verlauf_abteilung
  ADD CONSTRAINT FK_VABT_2_ABT
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES t_abteilung (ID)
;

ALTER TABLE t_verlauf_abteilung
  ADD CONSTRAINT FK_VABT_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES t_verlauf (ID)
;

ALTER TABLE t_verlauf_abteilung
  ADD CONSTRAINT FK_VABT_2_VSTATUS
      FOREIGN KEY (VERLAUF_STATUS_ID)
      REFERENCES t_verlauf_status (ID)
;

ALTER TABLE T_VPN_KONF
  ADD CONSTRAINT FK_VPNKONF_2_AUFTRAG
      FOREIGN KEY (NR)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE T_VPN_KONF
  ADD CONSTRAINT FK_VPNKONF_2_AUFTRAGPHYS
      FOREIGN KEY (PHYS_AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_zugang
  ADD CONSTRAINT FK_ZUGANG_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_ba_abtconfig_2_abt
  ADD CONSTRAINT FK_BAABTCONFIGABT_2_ABTCONFIG
      FOREIGN KEY (CONFIG_ID)
      REFERENCES t_ba_abt_config (ID)
;

ALTER TABLE t_ba_zusatz
  ADD CONSTRAINT FK_BAZUSATZ_2_VERLCONFIG
      FOREIGN KEY (BA_VERL_CONFIG_ID)
      REFERENCES t_ba_verl_config (ID)
;

ALTER TABLE t_ia_mat_entnahme_artikel
  ADD CONSTRAINT FK_IA_ENTART_2_ENTNAHME
      FOREIGN KEY (MAT_ENTNAHME_ID)
      REFERENCES t_ia_mat_entnahme (ID)
;

ALTER TABLE T_AUFTRAG_2_DSLAMPROFILE
  ADD CONSTRAINT FK_ADP_2_DSLAMPROF
      FOREIGN KEY (DSLAM_PROFILE_ID)
      REFERENCES T_DSLAM_PROFILE (ID)
;

ALTER TABLE T_AUFTRAG_2_DSLAMPROFILE
  ADD CONSTRAINT FK_A2DP_2_CHANGEREASON
      FOREIGN KEY (CHANGE_REASON_ID)
      REFERENCES T_DSLAM_PROFILE_CHANGE_REASON (ID)
;

ALTER TABLE T_AUFTRAG_2_DSLAMPROFILE
  ADD CONSTRAINT FK_ADP_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE T_PROD_2_DSLAMPROFILE
  ADD CONSTRAINT FK_PDP_2_PROFIL
      FOREIGN KEY (DSLAM_PROFILE_ID)
      REFERENCES T_DSLAM_PROFILE (ID)
;

ALTER TABLE T_PROD_2_DSLAMPROFILE
  ADD CONSTRAINT FK_PDP_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID)
;

ALTER TABLE t_ak0800
  ADD CONSTRAINT FK_AK0800_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID)
;

ALTER TABLE t_ak0800
  ADD CONSTRAINT FK_T_AK0800_2_MODELL
      FOREIGN KEY (MODELL_ID)
      REFERENCES t_ak0800_modell (ID)
;

ALTER TABLE t_report
  ADD CONSTRAINT FK_T_REPORT_2_PAPERSITE1
      FOREIGN KEY (FIRST_PAGE)
      REFERENCES t_report_paperformat (ID);

ALTER TABLE t_report
  ADD CONSTRAINT FK_T_REPORT_2_PAPERSITE2
      FOREIGN KEY (SECOND_PAGE)
      REFERENCES t_report_paperformat (ID);

ALTER TABLE t_report
  ADD CONSTRAINT FK_REPORT_2_ARCHIVOBJECT
      FOREIGN KEY (ARCHIV_OBJECT_ID)
      REFERENCES t_archiv_object (ID);

ALTER TABLE t_report
  ADD CONSTRAINT FK_REPORT_2_REPGRUPPE
      FOREIGN KEY (REPORT_GRUPPE_ID)
      REFERENCES t_report_gruppe (ID);

ALTER TABLE t_report_request
  ADD CONSTRAINT FK_REPREQUEST_2_REPORT
      FOREIGN KEY (REP_ID)
      REFERENCES t_report (ID);

ALTER TABLE t_report_request
  ADD CONSTRAINT FK_REPREQUEST_2_REASON
      FOREIGN KEY (PRINT_REASON)
      REFERENCES t_report_reason (ID);

ALTER TABLE t_report_2_prod
  ADD CONSTRAINT FK_REP2PROD_2_PRODUKT
      FOREIGN KEY (PROD_ID)
      REFERENCES t_produkt (PROD_ID);

ALTER TABLE t_report_2_prod
  ADD CONSTRAINT FK_REP2PROD_2_REPORT
      FOREIGN KEY (REP_ID)
      REFERENCES t_report (ID);

ALTER TABLE t_rep2prod_stati
  ADD CONSTRAINT FK_REP2PROD_2_ASTATUS
      FOREIGN KEY (STATUS_ID)
      REFERENCES t_auftrag_status (ID);
      
ALTER TABLE t_rep2prod_stati
  ADD CONSTRAINT FK_REP2PRODSTATI_2_RP
      FOREIGN KEY (REP2PROD_ID)
      REFERENCES t_report_2_prod (ID);

ALTER TABLE t_report_data
  ADD CONSTRAINT FK_REPDATA_2_REQUEST
      FOREIGN KEY (REQ_ID)
      REFERENCES t_report_request (ID);
      
ALTER TABLE t_report_template
  ADD CONSTRAINT FK_REPTEMP_2_REPORT
      FOREIGN KEY (REP_ID)
      REFERENCES t_report (ID);
      
ALTER TABLE t_rep2prod_techls
  ADD CONSTRAINT FK_REP2PRODTLS_2_REP2PROD
  	  FOREIGN KEY (REP2PROD_ID)
  	  REFERENCES t_report_2_prod (ID);

ALTER TABLE t_rep2prod_techls
  ADD CONSTRAINT FK_REP2PRODTLS_2_TECHLS
  	  FOREIGN KEY (TECHLS_ID)
  	  REFERENCES t_tech_leistung (ID);

ALTER TABLE t_report_2_userrole
  ADD CONSTRAINT FK_REP2ROLE_2_REP
  	  FOREIGN KEY (REPORT_ID)
  	  REFERENCES t_report (ID);
      
ALTER TABLE T_AUFTRAG_VOIP
  ADD CONSTRAINT FK_AUFTRAGVOIP_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES t_auftrag (ID);

ALTER TABLE T_AUFTRAG_VOIP
  ADD CONSTRAINT FK_AUFTRAGVOIP_2_REF
      FOREIGN KEY (EG_MODE)
      REFERENCES t_reference (ID);
     
ALTER TABLE t_archiv_parameter_2_object
  add CONSTRAINT FK_ARCHP2OBJ_2_OBJECT
      FOREIGN KEY (OBJECT_ID_INTERN)
      REFERENCES T_ARCHIV_OBJECT (ID);

ALTER TABLE t_archiv_parameter_2_object
  add CONSTRAINT FK_ARCHP2OBJ_2_PARAM
      FOREIGN KEY (PARAMETER_ID_INTERN)
      REFERENCES t_archiv_possible_parameter (ID);

ALTER TABLE t_archiv_parameter_2_object
  add CONSTRAINT FK_ARCHP2OBJ_2_AUSWAHL
      FOREIGN KEY (AUSWAHL_ID)
      REFERENCES t_archiv_auswahl (ID);


ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CB_VORGANG_2_CB
      FOREIGN KEY (CB_ID)
      REFERENCES T_CARRIERBESTELLUNG (CB_ID);

ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CBVORGANG_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID);

ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CB_VORGANG_2_REF_TYP
      FOREIGN KEY (TYP)
      REFERENCES T_REFERENCE (ID);

ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CB_VORGANG_2_REF_STATUS
      FOREIGN KEY (STATUS)
      REFERENCES T_REFERENCE (ID);
      
ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CB_VORGANG_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES T_CARRIER (ID);            

ALTER TABLE T_CB_VORGANG
  ADD CONSTRAINT FK_CBVORGANG_2_USEC
      FOREIGN KEY (USECASE_ID)
      REFERENCES T_CB_USECASE (ID);

ALTER TABLE T_CB_USECASE_2_CARRIER_KNG
  ADD CONSTRAINT FK_CBUC_2_CKNG
      FOREIGN KEY (CARRIERKENNUNG_ID)
      REFERENCES T_CARRIER_KENNUNG (ID);

ALTER TABLE T_CB_USECASE_2_CARRIER_KNG
  ADD CONSTRAINT FK_CBUC_2_UC
      FOREIGN KEY (USECASE_ID)
      REFERENCES T_CB_USECASE (ID);

ALTER TABLE T_CB_CONFIG
  ADD CONSTRAINT FK_CBCONFIG_2_USECASE
      FOREIGN KEY (USECASE_ID)
      REFERENCES T_CB_USECASE (ID);

ALTER TABLE T_CB_CONFIG
  ADD CONSTRAINT FK_CBCONFIG_2_CMD
      FOREIGN KEY (COMMAND_ID)
      REFERENCES T_SERVICE_COMMANDS (ID);      

ALTER TABLE t_txt_baustein_2_gruppe
  ADD CONSTRAINT FK_TXTBAUSTEIN_2_GRUPPE
      FOREIGN KEY (GRUPPE_ID)
      REFERENCES T_TXT_BAUSTEIN_GRUPPE (ID);

ALTER TABLE t_txt_baustein_gruppe_2_report
  ADD CONSTRAINT FK_TXTBSTGRUPPE_2_GRUPPE
      FOREIGN KEY (GRUPPE_ID)
      REFERENCES T_TXT_BAUSTEIN_GRUPPE (ID);

ALTER TABLE t_txt_baustein_gruppe_2_report
  ADD CONSTRAINT FK_TXTBSTGRUPPE_2_REP
      FOREIGN KEY (REPORT_ID)
      REFERENCES T_REPORT (ID);

ALTER TABLE T_PRINTER_2_PAPER
  ADD CONSTRAINT FK_PRINTER2PAP_2_PRINTER
      FOREIGN KEY (PRINTER_ID)
      REFERENCES T_PRINTER (ID);

ALTER TABLE T_PRINTER_2_PAPER
  ADD CONSTRAINT FK_PRINTER2PAP_2_PAPER
      FOREIGN KEY (PAPER_ID)
      REFERENCES T_REPORT_PAPERFORMAT (ID);

ALTER TABLE T_ADDRESS
  ADD CONSTRAINT FK_ADDRESS_2_REF
      FOREIGN KEY (ADDRESS_TYPE)
      REFERENCES T_REFERENCE (ID);

ALTER TABLE T_RANGIERUNGS_AUFTRAG
  ADD CONSTRAINT FK_RA_2_HVTSTD
      FOREIGN KEY (HVT_STD_ID)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_RANGIERUNGS_AUFTRAG
  ADD CONSTRAINT FK_RA_2_PHYSIKTYP1
      FOREIGN KEY (PHYSIKTYP_PARENT)
      REFERENCES T_PHYSIKTYP (ID);

ALTER TABLE T_RANGIERUNGS_AUFTRAG
  ADD CONSTRAINT FK_RA_2_PHYSIKTYP2
      FOREIGN KEY (PHYSIKTYP_CHILD)
      REFERENCES T_PHYSIKTYP (ID);

ALTER TABLE T_AUFTRAG_QOS
  ADD CONSTRAINT FK_AUFTRAGQOS_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID);

ALTER TABLE T_AUFTRAG_QOS
  ADD CONSTRAINT FK_AUFTRAGQOS_2_REF
      FOREIGN KEY (QOS_CLASS_REF_ID)
      REFERENCES T_REFERENCE (ID);       
       
ALTER TABLE T_REPORT_REQUEST
  ADD CONSTRAINT FK_REPREQ_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID);
      
ALTER TABLE T_EG_IAD
  ADD CONSTRAINT FK_EG_IAD_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID);
   
ALTER TABLE T_EG_IAD
  ADD CONSTRAINT FK_EG_IAD_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES T_VERLAUF (ID);
      
ALTER TABLE T_EG_IAD
  ADD CONSTRAINT FK_EG_IAD_2_EG
      FOREIGN KEY (EG_ID)
      REFERENCES T_EG (ID);		
       