ALTER TABLE T_MWF_MELDUNG
 ADD (KUNDEN_NUMMER_BESTELLER  VARCHAR2(10));

ALTER TABLE T_MWF_MELDUNG
 ADD (ANSCHLUSS_ONKZ  VARCHAR2(10));

ALTER TABLE T_MWF_MELDUNG
 ADD (ANSCHLUSS_RUFNUMMER  VARCHAR2(20));