ALTER TABLE T_ANREDE
  ADD CONSTRAINT UQ_T_ANREDE
      UNIQUE (ANREDE_KEY, ANREDE_ART);

ALTER TABLE T_VPN
  ADD CONSTRAINT UQ_T_VPN
      UNIQUE (VPN_NR);

ALTER TABLE T_TDN
  ADD CONSTRAINT UQ_T_TDN_1
      UNIQUE (TDN);

ALTER TABLE T_GUI_DEFINITION
  ADD CONSTRAINT UQ_T_GUI_DEFINITION
      UNIQUE (CLASS);

ALTER TABLE T_AK0800_MODELL
  ADD CONSTRAINT UQ_T_AK0800_MODELL
      UNIQUE (NAME);

ALTER TABLE T_ACC_ART
  ADD CONSTRAINT UQ_T_ACC_ART
      UNIQUE (LI_NR);

ALTER TABLE T_FAKTURA_MONAT
  ADD CONSTRAINT UQ_FAKTURA_MONAT
      UNIQUE (RECHNUNGSTEXT);

ALTER TABLE T_FAKTURA_MONAT
  ADD CONSTRAINT UQ_FAKTURA_MONAT_DATE
      UNIQUE (VON, BIS);

ALTER TABLE T_FAKTURA_BEARBEITER
  ADD CONSTRAINT UQ_FAKTURA_BEARBEITER
      UNIQUE (NAME);

ALTER TABLE T_SIGNATURED_FILES
  ADD CONSTRAINT UQ_T_SIGNATURE
      UNIQUE (FILENAME);

ALTER TABLE T_PHYSIKTYP
  ADD CONSTRAINT UQ_T_PHYSIKTYP
      UNIQUE (NAME);

ALTER TABLE T_BA_VERL_AEND
  ADD CONSTRAINT UQ_T_BA_VERL_AEND
      UNIQUE (TEXT);

ALTER TABLE T_BA_VERL_NEU
  ADD CONSTRAINT UQ_T_BA_VERL_NEU
      UNIQUE (PROD_ID);

ALTER TABLE T_RANGIERUNG
  ADD CONSTRAINT UQ_RANGIERUNG_LTG
      UNIQUE (LEITUNG_GESAMT_ID, LEITUNG_LFD_NR, HISTORY_COUNT);

ALTER TABLE T_PRODUKT_2_PHYSIKTYP
  ADD CONSTRAINT UQ_P2PTYP
      UNIQUE (PROD_ID, PHYSIKTYP, PARENTPHYSIKTYP_ID);

ALTER TABLE T_AUFTRAG_IMPORT
  ADD CONSTRAINT UQ_AUFTRAG_IMPORT_XML
      UNIQUE (XML_FILE);

ALTER TABLE T_AUFTRAG_IMPORT
  ADD CONSTRAINT UQ_AUFTRAG_IMPORT_REF
      UNIQUE (REF_ID);

ALTER TABLE T_BA_VERL_NEU_ZUSATZ
  ADD CONSTRAINT UQ_T_BA_VERL_NEU_ZUSATZ
      UNIQUE (BA_VERL_NEU_ID, ABTEILUNG_ID, HVT_GRUPPE_ID);

ALTER TABLE T_BANKVERBINDUNG
  ADD CONSTRAINT UQ_T_BANKVERBINDUNG
      UNIQUE (RA_ID);

ALTER TABLE T_GUI_MAPPING
  ADD CONSTRAINT UQ_T_GUI_MAPPING
      UNIQUE (GUI_ID, REFERENZ_ID, REFERENZ_HERKUNFT);

ALTER TABLE T_SPERRE_INFO
  ADD CONSTRAINT UQ_SPERRE_INFO
      UNIQUE (ABTEILUNG_ID, EMAIL);

ALTER TABLE T_FAKTURA
  ADD CONSTRAINT UQ_FAKTURA
      UNIQUE (FNR_ID, AUFTRAG_ID);

ALTER TABLE T_FAKTURA_NO
  ADD CONSTRAINT UQ_FAKTURA_NO
      UNIQUE (AUFTRAG_ID, FAKTURA_MONAT);

ALTER TABLE T_UEVT_2_ZIEL
  ADD CONSTRAINT UQ_UEVT2ZIEL
      UNIQUE (PROD_ID, UEVT_ID, HVT_STANDORT_ID_ZIEL);

ALTER TABLE T_VERLAUF_ABTEILUNG
  ADD CONSTRAINT UQ_VERLAUF_ABT
      UNIQUE (VERLAUF_ID, ABTEILUNG_ID);

ALTER TABLE T_PHYSIKUEBERNAHME
  ADD CONSTRAINT UQ_PHYSIKUEB_VERL_ID
      UNIQUE (VERLAUF_ID);

ALTER TABLE T_KUBENA_HVT
  ADD CONSTRAINT UQ_KUBENA_HVT
      UNIQUE (KUBENA_ID, HVT_ID_STANDORT);

ALTER TABLE T_KUBENA_TDN
  ADD CONSTRAINT UQ_KUBENA_TDN
      UNIQUE (KUBENA_ID, TDN);

ALTER TABLE T_KUBENA_PROD
  ADD CONSTRAINT UQ_KUBENA_PROD
      UNIQUE (KUBENA_ID, PROD_ID);

ALTER TABLE T_PVC_2_PROFIL
  ADD CONSTRAINT UQ_PVC_2_PROFIL
      UNIQUE (PVC_ID, PROFIL_ID);
