CREATE TABLE T_AUFTRAG (
       ID NUMBER(9) NOT NULL
     , KUNDE__NO NUMBER(10) NOT NULL
);

CREATE TABLE T_EQ_GEBAEUDE (
       ID NUMBER(9) NOT NULL
     , GEBAEUDE VARCHAR2(50)
     , STRASSE VARCHAR2(50)
     , PLZ VARCHAR2(10)
     , ORT VARCHAR2(50)
     , RE_STRASSE VARCHAR2(50)
);

CREATE TABLE T_ANREDE (
       ID NUMBER(9) NOT NULL
     , ANREDE_KEY VARCHAR2(10) NOT NULL
     , ANREDE CHAR(50)
     , ANREDE_ART NUMBER(9)
     , PERS_ANREDE NUMBER(1)
);

CREATE TABLE T_AUFTRAG_STATUS (
       ID NUMBER(9) NOT NULL
     , STATUS_TEXT VARCHAR2(100) NOT NULL
);

CREATE TABLE T_VPN (
       VPN_ID NUMBER(9) NOT NULL
     , VPN_NR NUMBER(9) NOT NULL
     , VPN_PROJLEITER VARCHAR2(50) NOT NULL
     , VPN_DATUM DATE NOT NULL
     , VPN_KUNDEN__NO NUMBER(9) NOT NULL
     , VPN_TIMESTAMP DATE
     , VPN_BEMERKUNG VARCHAR2(1000)
     , VPN_EINWAHL VARCHAR2(20)
);

CREATE TABLE T_WOHNHEIM (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(100) NOT NULL
     , STRASSE VARCHAR2(50) NOT NULL
     , PLZ VARCHAR2(10) NOT NULL
     , ORT VARCHAR2(50) NOT NULL
     , LEITUNGSNR VARCHAR2(20) NOT NULL
     , KUNDE__NO NUMBER(10) NOT NULL
);

CREATE TABLE T_BA_VERL_AEND_GRUPPE (
       ID NUMBER(9) NOT NULL
     , BESCHREIBUNG VARCHAR2(50)
);

CREATE TABLE T_PRODUKTGRUPPE (
       ID NUMBER(9) NOT NULL
     , PRODUKTGRUPPE CHAR(30)
);

CREATE TABLE T_SCHNITTSTELLE (
       ID NUMBER(9) NOT NULL
     , SCHNITTSTELLE CHAR(20) NOT NULL
);

CREATE TABLE T_TDN (
       ID NUMBER(9) NOT NULL
     , TDN VARCHAR2(50) NOT NULL
);

CREATE TABLE T_EG_TYP (
       ID NUMBER(9) NOT NULL
     , BESCHREIBUNG VARCHAR2(30)
);

CREATE TABLE T_EG_HERKUNFT (
       ID NUMBER(9) NOT NULL
     , BESCHREIBUNG VARCHAR2(30)
);

CREATE TABLE T_INT_ACCOUNT (
       ID NUMBER(9) NOT NULL
     , ACCOUNT VARCHAR2(10)
     , PASSWORT VARCHAR2(10)
     , URL VARCHAR2(255)
     , GESPERRT NUMBER(1)
     , RUFNUMMER VARCHAR2(40)
     , LOESCHDATUM DATE
     , KUENDIGUNGSDATUM DATE
     , AENDERUNGSDATUM DATE
     , ERSTELLDATUM DATE
     , NUMMER VARCHAR2(10)
     , STATUS NUMBER(4)
     , FREIGABE NUMBER(1)
     , STATUS_INTERN NUMBER(9)
     , KENNZ NUMBER(4)
     , BEMERKUNG VARCHAR2(255)
     , LI_NR NUMBER(9)
     , ABRECHNUNGSMONAT NUMBER(4)
     , MAIL_NEU NUMBER(9)
     , HOSTING_NEU NUMBER(9)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_AUFTRAG_TECHNIK_2_ENDSTELLE (
       ID NUMBER(9) NOT NULL
);

CREATE TABLE T_CARRIER (
       ID NUMBER(9) NOT NULL
     , TEXT VARCHAR2(30)
     , ORDER_NO NUMBER(9)
     , CB_NOTWENDIG NUMBER(1)
);

CREATE TABLE T_NIEDERLASSUNG (
       ID NUMBER(9) NOT NULL
     , TEXT VARCHAR2(50)
);

CREATE TABLE T_GUI_DEFINITION (
       ID NUMBER(9) NOT NULL
     , CLASS VARCHAR2(255) NOT NULL
     , TYPE VARCHAR2(50) NOT NULL
     , NAME VARCHAR2(50)
     , TEXT VARCHAR2(255)
     , TOOLTIP VARCHAR2(255)
     , ICON VARCHAR2(255)
     , ADD_SEPARATOR NUMBER(1)
     , ORDER_NO NUMBER(9)
     , ACTIVE NUMBER(1)
);

CREATE TABLE T_LEITUNGSART (
       ID NUMBER(9) NOT NULL
     , NAME CHAR(30) NOT NULL
);

CREATE TABLE T_MONTAGEART (
       ID NUMBER(9) NOT NULL
     , NAME CHAR(30) NOT NULL
);

CREATE TABLE T_PVC_VORGABE (
       ID NUMBER(9) NOT NULL
     , VATER_ID NUMBER(9) NOT NULL
     , IST_VATER NUMBER(1) NOT NULL
     , TEXT VARCHAR2(50) NOT NULL
);

CREATE TABLE T_AK0800_MODELL (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(50) NOT NULL
     , BESCHREIBUNG VARCHAR2(255)
);

CREATE TABLE T_ACC_ART (
       ID NUMBER(9) NOT NULL
     , LI_NR NUMBER(9) NOT NULL
     , TEXT VARCHAR2(100) NOT NULL
);

CREATE TABLE T_HVT_TECHNIK (
       ID NUMBER(9) NOT NULL
     , HERSTELLER VARCHAR2(100) NOT NULL
     , NAME VARCHAR2(100) NOT NULL
     , BESCHREIBUNG VARCHAR2(255)
);

CREATE TABLE T_ANBINDUNGSART (
       ID NUMBER(9) NOT NULL
     , ANBINDUNGSART VARCHAR2(50) NOT NULL
);

CREATE TABLE T_FAKTURA_MONAT (
       ID NUMBER(9) NOT NULL
     , VON DATE NOT NULL
     , BIS DATE NOT NULL
     , RECHNUNGSTEXT CHAR(25) NOT NULL
);

CREATE TABLE T_COUNTER (
       COUNTER CHAR(25) NOT NULL
     , INTVALUE NUMBER(9) NOT NULL
);

CREATE TABLE T_CB_2_ES (
       ID NUMBER(9) NOT NULL
);

CREATE TABLE T_VERLAUF_STATUS (
       ID NUMBER(9) NOT NULL
     , VERLAUF_STATUS VARCHAR2(50) NOT NULL
);

CREATE TABLE T_FAKTURA_BEARBEITER (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(30) NOT NULL
     , IHRE_ZEICHEN VARCHAR2(30)
     , UNSERE_ZEICHEN VARCHAR2(10)
     , TELEFON VARCHAR2(5) NOT NULL
     , TELEFAX VARCHAR2(5)
     , AKT NUMBER(1)
);

CREATE TABLE T_PORTIERUNGSART (
       ID NUMBER(9) NOT NULL
     , TEXT VARCHAR2(50) NOT NULL
);

CREATE TABLE T_E_RECHNUNG_DRUCK (
       ID NUMBER(9) NOT NULL
     , KUNDE__NO NUMBER(9) NOT NULL
     , BEARBEITER_DRUCK VARCHAR2(50) NOT NULL
     , DATUM_DRUCK DATE NOT NULL
     , BILL_ACCOUNT_NO NUMBER(9) NOT NULL
     , LOGIN_NO NUMBER(9) NOT NULL
     , BEARBEITER_LISTE VARCHAR2(50)
     , DATUM_LISTE DATE
     , BEARBEITER_DRUCK_MAXI CHAR(50)
     , DATUM_DRUCK_MAXI DATE
     , BEARBEITER_LISTE_MAXI CHAR(50)
     , DATUM_LISTE_MAXI DATE
     , BRIEFANREDE VARCHAR2(50)
     , ANSCHRIFT1 VARCHAR2(50)
     , ANSCHRIFT2 VARCHAR2(50)
     , ANSCHRIFT3 VARCHAR2(50)
     , ANSCHRIFT4 VARCHAR2(50)
     , STRASSE VARCHAR2(50)
     , PLZ VARCHAR2(10)
     , ORT VARCHAR2(50)
     , TIMESTAMP TIMESTAMP
);

CREATE TABLE T_REGISTRY (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(100) NOT NULL
     , STR_VALUE VARCHAR2(255)
     , INT_VALUE NUMBER(9)
     , DESCRIPTION VARCHAR2(255)
);

CREATE TABLE T_PHYSIKAENDERUNGSTYP (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(50) NOT NULL
     , EWSD NUMBER(1)
     , SDH NUMBER(1)
     , IPS NUMBER(1)
     , SCT NUMBER(1)
);

CREATE TABLE T_KUBENA (
       ID NUMBER(9) NOT NULL
     , DATUM DATE
     , KRITERIUM NUMBER(2) NOT NULL
     , NAME VARCHAR2(30) NOT NULL
     , SZR_VON DATE
     , SZR_BIS DATE
);

CREATE TABLE T_PROD_SL_FREIGABE (
       ID NUMBER(9) NOT NULL
     , TEXT VARCHAR2(100)
     , POSSIBLE NUMBER(1)
);

CREATE TABLE T_LEISTUNG (
       LEISTUNG_NO_DN NUMBER(10) NOT NULL
     , LEISTUNG_DN VARCHAR2(50)
     , LEISTUNG_BESCHREIBUNG VARCHAR2(255)
     , LEISTUNG_PARAMETER NUMBER(2)
     , LEISTUNG_PARAMETER_BESCHREIBUNG VARCHAR2(255)
     , MISTRAL_LEISTUNGS_NO NUMBER(10)
     , MEHRFACH NUMBER(10)
     , OE__NO NUMBER(10)
     , EMAIL_SCV_BEI_KUENDIGUNG NUMBER(2)
);

CREATE TABLE T_LEISTUNG_DN (
       LFDNR NUMBER(10) NOT NULL
     , DN_NO NUMBER(10)
     , LEISTUNG_NO_DN NUMBER(10)
     , LEISTUNG_PARAMETER VARCHAR2(255)
     , SCV_USER_REALISIERUNG VARCHAR2(50)
     , SCV_REALISIERUNG DATE
     , SCV_USER_KUENDIGUNG VARCHAR2(50)
     , SCV_KUENDIGUNG DATE
     , EWSD_USER_REALISIERUNG VARCHAR2(50)
     , EWSD_REALISIERUNG DATE
     , EWSD_USER_KUENDIGUNG VARCHAR2(50)
     , EWSD_KUENDIGUNG DATE
     , BILLING_CHECK NUMBER(2)
);

CREATE TABLE T_DB_QUERIES (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(100) NOT NULL
     , DESCRIPTION VARCHAR2(255)
     , SQL_QUERY VARCHAR2(4000) NOT NULL
     , SERVICE CHAR(25) NOT NULL
     , PARAMS VARCHAR2(1000)
);

CREATE TABLE T_SERVICE_CHAIN (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(50) NOT NULL
     , DESCRIPTION VARCHAR2(255)
);

CREATE TABLE T_SERVICE_COMMANDS (
       ID NUMBER(9) DEFAULT 0 NOT NULL
     , NAME VARCHAR2(100) NOT NULL
     , CLASS VARCHAR2(255) NOT NULL
     , TYPE VARCHAR2(10) NOT NULL
     , DESCRIPTION VARCHAR2(500)
);

CREATE TABLE T_TAL_AENDERUNGSTYP (
       ID NUMBER(9) DEFAULT 0 NOT NULL
     , CARRIER_ID NUMBER(9) DEFAULT 0 NOT NULL
     , NAME VARCHAR2(50) NOT NULL
     , REPORT_NAME VARCHAR2(255)
     , DESCRIPTION VARCHAR2(255)
);

CREATE TABLE T_SDH_PROFIL (
       ID NUMBER(9) NOT NULL
     , NAME CHAR(50) NOT NULL
     , VPIVCI_ALLOWED NUMBER(1)
);

CREATE TABLE T_BILLING_LEISTUNG_KONFIG (
       ID NUMBER(9) NOT NULL
     , EXTERN_LEISTUNG__NO NUMBER(10) NOT NULL
     , NAME VARCHAR2(100)
     , IS_DEFAULT NUMBER(1)
     , DISPO NUMBER(1)
     , EWSD NUMBER(1)
     , SDH NUMBER(1)
     , SCT NUMBER(1)
     , IPS NUMBER(1)
     , PARAMETER VARCHAR2(50)
     , DESCRIPTION VARCHAR2(255)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE WISSEN (
       ID NUMBER(9) NOT NULL
     , DB VARCHAR2(50) NOT NULL
     , TABELLE VARCHAR2(50) NOT NULL
     , SPALTE VARCHAR2(50) NOT NULL
     , WERT VARCHAR2(100) NOT NULL
     , ERKLAERUNG VARCHAR2(500)
);

CREATE TABLE T_AUFTRAG_IMPORT_STATUS (
       ID NUMBER(9) NOT NULL
     , STATUS_TEXT VARCHAR2(50) NOT NULL
     , IMPORT_ACTIVE NUMBER(1)
);

CREATE TABLE T_SIGNATURED_FILES (
       ID NUMBER(9) NOT NULL
     , BILLING_YEAR CHAR(4) NOT NULL
     , BILLING_MONTH CHAR(2) NOT NULL
     , FILENAME VARCHAR2(255) NOT NULL
     , SIGNATURE_START DATE NOT NULL
     , SIGNATURE_END DATE
     , ABSOLUTE_PATH VARCHAR2(500) NOT NULL
);

CREATE TABLE T_DIALER (
       ID NUMBER(9) NOT NULL
     , KENNZAHL VARCHAR2(18) NOT NULL
     , BESCHREIBUNG VARCHAR2(50)
     , TYP VARCHAR2(20) NOT NULL
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE
     , USER_GUELTIG_VON VARCHAR2(25) NOT NULL
     , USER_GUELTIG_BIS VARCHAR2(25)
     , GESPERRT_AB DATE
     , GESPERRT_BIS DATE
     , USER_GESPERRT_AB VARCHAR2(25)
     , USER_GESPERRT_BIS VARCHAR2(25)
);

CREATE TABLE T_REFERENCE (
       ID NUMBER(9) NOT NULL
     , TYPE VARCHAR2(20) NOT NULL
     , STR_VALUE VARCHAR2(100)
     , INT_VALUE NUMBER(9)
     , UNIT_ID NUMBER(1)
     , GUI_VISIBLE NUMBER(1)
     , ORDER_NO NUMBER(9)
     , DESCRIPTION VARCHAR2(255)
);

CREATE TABLE T_ANSCHLUSSART (
       ID NUMBER(9) NOT NULL
     , ANSCHLUSSART CHAR(20)
);

CREATE TABLE T_HVT_GRUPPE (
       HVT_GRUPPE_ID NUMBER(9) NOT NULL
     , ONKZ CHAR(8)
     , ORTSTEIL CHAR(50)
     , STRASSE CHAR(50)
     , HAUS_NR CHAR(5)
     , PLZ CHAR(10)
     , ORT CHAR(50)
     , SWITCH CHAR(20)
     , NIEDERLASSUNG_ID NUMBER(9)
     , MONTAG CHAR(1)
     , DIENSTAG CHAR(1)
     , MITTWOCH CHAR(1)
     , DONNERSTAG CHAR(1)
     , FREITAG CHAR(1)
     , DSL_ANALOG_TERMIN DATE
     , DSL_ISDN_TERMIN DATE
     , DSL2P_ANALOG_TERMIN DATE
     , DSL2P_ISDN_TERMIN DATE
);

CREATE TABLE T_HVT_STANDORT (
       HVT_ID_STANDORT NUMBER(9) NOT NULL
     , HVT_GRUPPE_ID NUMBER(9) DEFAULT 0
     , ASB NUMBER(9) DEFAULT 0
     , HOCHGERECHNETER_TERMIN CHAR(40)
     , GESICHERTE_REALISIERUNG CHAR(40)
     , ZBDTAG NUMBER(9)
     , EWSD_OR1 NUMBER(9)
     , EWSD_OR2 NUMBER(9)
     , BESCHREIBUNG CHAR(50)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , VIRTUELL NUMBER(1)
     , CARRIER_ID NUMBER(9)
     , CARRIER_KENNUNG_ID NUMBER(10)
     , KOSTENSTELLE VARCHAR2(50)
     , INNENAUFTRAG VARCHAR2(50)
);

CREATE TABLE T_STRASSENLISTE (
       SL_ID NUMBER(9) NOT NULL
     , HVT_GRUPPE_ID NUMBER(9)
     , ONKZ CHAR(8)
     , ORT CHAR(50)
     , ORTSZUSATZ VARCHAR2(50)
     , STRASSE CHAR(50)
     , ABSCHNITT VARCHAR2(30)
     , PLZ VARCHAR2(15)
     , ENTFERNUNG CHAR(10)
     , BEMERKUNG CHAR(100)
);

CREATE TABLE T_PHYSIKTYP (
       ID NUMBER(9) NOT NULL
     , NAME CHAR(50)
     , BESCHREIBUNG CHAR(100)
     , HVT_TECHNIK_ID NUMBER(9)
);

CREATE TABLE T_PRODUKT (
       PROD_ID NUMBER(9) NOT NULL
     , PRODUKTGRUPPE_ID NUMBER(9) NOT NULL
     , PRODUKT_NR CHAR(10)
     , ANSCHLUSSART CHAR(30)
     , LEITUNGSART NUMBER(9)
     , UPSTREAM NUMBER(9)
     , AKTIONS_ID NUMBER(4) DEFAULT 0 NOT NULL
     , MOEGLICHE_S0 NUMBER(2)
     , BRAUCHT_DN CHAR(1) DEFAULT '0' NOT NULL
     , BRAUCHT_DN4ACCOUNT NUMBER(1)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , AUFTRAGSERSTELLUNG CHAR(1) DEFAULT '0' NOT NULL
     , LTGNR_VORS CHAR(10)
     , LTGNR_ANLEGEN CHAR(1) DEFAULT '0' NOT NULL
     , BRAUCHT_BUENDEL CHAR(1) DEFAULT '0' NOT NULL
     , PROD_ID_TEXT CHAR(9)
     , ELVERLAUF NUMBER(1)
     , ABRECHNUNG_IN_HURRICAN CHAR(1) DEFAULT '0' NOT NULL
     , ENDSTELLEN_TYP NUMBER(9) DEFAULT 0 NOT NULL
     , BESCHREIBUNG CHAR(100)
     , ACCOUNT_VORS VARCHAR2(5)
     , LI_NR NUMBER(9)
     , VPN_PHYSIK NUMBER(1)
     , PROJEKTIERUNG NUMBER(9)
     , IS_PARENT NUMBER(1)
     , CHECK_CHILD NUMBER(1)
     , EXPORT_KDP_M NUMBER(1)
     , VERTEILUNG_DURCH NUMBER(9)
     , BRACHT_VPI_VCI NUMBER(1)
);

CREATE TABLE T_EQUIPMENT (
       EQ_ID NUMBER(9) NOT NULL
     , HVT_ID_STANDORT NUMBER(9)
     , SWITCH VARCHAR2(10)
     , HW_PORT VARCHAR2(10)
     , HW_EQN VARCHAR2(40)
     , HW_SCHNITTSTELLE VARCHAR2(50)
     , TS1 VARCHAR2(40)
     , TS2 VARCHAR2(40)
     , RANG_VERTEILER VARCHAR2(40)
     , RANG_REIHE VARCHAR2(40)
     , RANG_BUCHT VARCHAR2(40)
     , RANG_LEISTE1 VARCHAR2(40)
     , RANG_STIFT1 VARCHAR2(40)
     , RANG_LEISTE2 VARCHAR2(40)
     , RANG_STIFT2 VARCHAR2(10)
     , RANG_SCHNITTSTELLE VARCHAR2(50)
     , CARRIER VARCHAR2(50)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , STATUS VARCHAR2(50)
     , BEMERKUNG VARCHAR2(255)
     , USERW VARCHAR2(8)
     , DATEW DATE
     , RANG_SS_TYPE VARCHAR2(10)
     , UETV VARCHAR2(100)
);

CREATE TABLE T_UEVT (
       UEVT_ID NUMBER(9) NOT NULL
     , HVT_ID_STANDORT NUMBER(9)
     , UEVT VARCHAR2(10)
     , SCHWELLWERT NUMBER(9)
     , PROJEKTIERUNG NUMBER(1)
);

CREATE TABLE T_RECHNUNGSANSCHRIFT (
       ID NUMBER(9) NOT NULL
     , ANREDE VARCHAR2(36)
     , VORNAME VARCHAR2(36)
     , NACHNAME VARCHAR2(36)
     , ZUSATZ VARCHAR2(36)
     , POSTFACH VARCHAR2(30)
     , STRASSE VARCHAR2(50)
     , PLZ VARCHAR2(10)
     , ORT VARCHAR2(50)
     , KUNDE__NO NUMBER(10) NOT NULL
     , VB VARCHAR2(20)
     , MWST NUMBER(5, 2)
     , MWST_ID NUMBER(9)
     , LKZ VARCHAR2(2)
     , EINZEL_RE NUMBER(1)
);

CREATE TABLE T_EQ_OBJEKT (
       ID NUMBER(9) NOT NULL
     , OBJEKT VARCHAR2(50)
     , QM NUMBER(12, 2)
     , GEBAEUDE_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_BA_VERL_AEND (
       ID NUMBER(9) NOT NULL
     , TEXT VARCHAR2(100) NOT NULL
     , DISPO NUMBER(1)
     , EWSD NUMBER(1)
     , SDH NUMBER(1)
     , SCT NUMBER(1)
     , IPS NUMBER(1)
     , MANUELL NUMBER(1)
     , BA_VERL_AEND_GRUPPE_ID NUMBER(9)
     , CONFIGURABLE NUMBER(1)
     , IS_AUFTRAGSART NUMBER(1)
     , AKT NUMBER(1)
     , ORDER_NO NUMBER(9)
);

CREATE TABLE T_BA_VERL_NEU (
       ID NUMBER(9) NOT NULL
     , PROD_ID NUMBER(9) NOT NULL
     , DISPO NUMBER(1)
     , EWSD NUMBER(1)
     , SDH NUMBER(1)
     , SCT NUMBER(1)
     , IPS NUMBER(1)
     , KDP_M NUMBER(1)
     , AUSBLENDEN NUMBER(1)
);

CREATE TABLE T_ENDSTELLE (
       ID NUMBER(9) NOT NULL
     , ES_GRUPPE NUMBER(9)
     , CB_2_ES_ID NUMBER(9)
     , ES_TYP VARCHAR2(1)
     , ENDSTELLE VARCHAR2(100)
     , NAME VARCHAR2(100)
     , ORT VARCHAR2(50)
     , PLZ VARCHAR2(15)
     , GESCHUE2 VARCHAR2(50)
     , GESCHUE1 VARCHAR2(50)
     , ORTSNETZKENNZAHL VARCHAR2(10)
     , SL_ID NUMBER(9)
     , ANSCHLUSSART NUMBER(9)
     , BEMSTAWA VARCHAR2(70)
     , HVT_SCHALTUNG VARCHAR2(50)
     , NT_MONTAGEART NUMBER(9)
     , RANGIER_ID NUMBER(9)
     , HVT_ID_STANDORT NUMBER(9)
);

CREATE TABLE T_AUFTRAG_TECHNIK (
       ID NUMBER(9) NOT NULL
     , TDN_ID NUMBER(9)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , AT_2_ES_ID NUMBER(9)
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , INT_ACCOUNT_ID NUMBER(9)
     , ANBINDUNGSART VARCHAR2(30)
     , ANBINDUNGSART_ID NUMBER(9)
     , VPN_ID NUMBER(9)
     , PROJEKTIERUNG NUMBER(1)
     , AUFTRAGSART NUMBER(9)
);

CREATE TABLE T_ABTEILUNG (
       ID NUMBER(9) NOT NULL
     , TEXT VARCHAR2(50)
     , NIEDERLASSUNG_ID NUMBER(9)
     , RELEVANT_4_PROJ NUMBER(1)
     , RELEVANT_4_BA NUMBER(1)
);

CREATE TABLE T_RANGIERUNG (
       RANGIER_ID NUMBER(9) NOT NULL
     , EQ_IN_ID NUMBER(9)
     , EQ_OUT_ID NUMBER(9)
     , HVT_ID_STANDORT NUMBER(9) NOT NULL
     , PHYSIK_TYP NUMBER(9)
     , FREIGEGEBEN VARCHAR2(1)
     , FREIGABE_AB DATE
     , LEITUNGSNR_EXTERN VARCHAR2(9)
     , LNR_LFD VARCHAR2(4)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , LEITUNG_GESAMT_ID NUMBER(9)
     , LEITUNG_LFD_NR NUMBER(9)
     , LEITUNG_LOESCHEN NUMBER(1)
     , BEMERKUNG VARCHAR2(255)
     , USERW VARCHAR2(8)
     , DATEW DATE
     , ES_ID NUMBER(9)
     , LAST_ES_ID NUMBER(9)
     , TIMEST TIMESTAMP
     , HISTORY_FROM_RID NUMBER(9) DEFAULT null
     , HISTORY_COUNT NUMBER(9)
);

CREATE TABLE T_FAKTURA_NR (
       ID NUMBER(9) NOT NULL
     , RA_ID NUMBER(9) NOT NULL
     , RE_ART VARCHAR2(50)
     , FAKTURA_MONAT NUMBER(9) NOT NULL
     , BEARBEITER NUMBER(9) NOT NULL
     , BETRAG_NETTO NUMBER(12, 2)
     , BETRAG_MWST NUMBER(12, 2)
);

CREATE TABLE T_PRODUKT_2_PHYSIKTYP (
       ID NUMBER(9) NOT NULL
     , PROD_ID NUMBER(9) NOT NULL
     , PHYSIKTYP NUMBER(9) NOT NULL
     , VIRTUELL NUMBER(1)
     , PARENTPHYSIKTYP_ID NUMBER(9)
);

CREATE TABLE T_VERLAUF (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , ANLASS NUMBER(9) NOT NULL
     , VERLAUF_STATUS_ID NUMBER(9) NOT NULL
     , STATUS_ID_ALT NUMBER(9)
     , PROJEKTIERUNG NUMBER(1)
     , REALISIERUNGSTERMIN DATE
     , AKT NUMBER(1)
     , MANUELL_VERTEILT NUMBER(1)
     , PORTIERUNGSART NUMBER(9)
     , VERSCHOBEN NUMBER(1)
     , BEMERKUNG VARCHAR2(255)
);

CREATE TABLE T_HVT_BESTELLUNG (
       ID NUMBER(9) NOT NULL
     , UEVT_ID NUMBER(9) NOT NULL
     , ANGEBOT_DATUM DATE NOT NULL
     , PHYSIKTYP VARCHAR2(10) NOT NULL
     , ANZAHL_CUDA NUMBER(9) NOT NULL
     , BESTELLDATUM DATE
     , BESTELLNR_AKOM VARCHAR2(50)
     , BESTELLNR_DTAG VARCHAR2(50)
     , BEREITGESTELLT DATE
     , RECHNUNG_NR_DTAG VARCHAR2(50)
     , RECHNUNG_BEZAHLT DATE
     , TIMEST TIMESTAMP
);

CREATE TABLE T_AUFTRAG_IMPORT (
       ID NUMBER(9) NOT NULL
     , KUNDE__NO NUMBER(9)
     , XML_FILE VARCHAR2(255) NOT NULL
     , REF_ID VARCHAR2(25) NOT NULL
     , PARTNER_ID VARCHAR2(25)
     , AKTION VARCHAR2(50)
     , COUPON VARCHAR2(100)
     , AG_NAME VARCHAR2(100)
     , AG_VORNAME VARCHAR2(100)
     , AG_STRASSE VARCHAR2(100)
     , AG_PLZ VARCHAR2(10)
     , AG_ORT VARCHAR2(100)
     , A_NAME VARCHAR2(100)
     , A_VORNAME VARCHAR2(100)
     , A_ORT VARCHAR2(100)
     , A_STRASSE VARCHAR2(100)
     , ALT_NAME VARCHAR2(100)
     , ALT_VORNAME VARCHAR2(100)
     , ALT_STRASSE VARCHAR2(100)
     , ALT_ORT VARCHAR2(100)
     , RUFNUMMER VARCHAR2(50)
     , PRODUKT_NAME VARCHAR2(100)
     , PORTIERUNG NUMBER(1)
     , TARIFWECHSEL NUMBER(1)
     , UMZUG NUMBER(1)
     , WUNSCHTERMIN DATE
     , ACTIVE NUMBER(1)
     , IMPORT_STATUS NUMBER(9)
     , AUFTRAGS_EINGANG DATE
     , BEMERKUNG VARCHAR2(255)
     , BEARBEITER VARCHAR2(30)
     , LAST_MODIFIED TIMESTAMP
     , PREIS NUMBER(5, 2)
);

CREATE TABLE T_CARRIER_KENNUNG (
       ID NUMBER(9) NOT NULL
     , CARRIER_ID NUMBER(9) NOT NULL
     , BEZEICHNUNG VARCHAR2(15)
     , KUNDE_NR VARCHAR2(15)
     , PORTIERUNGSKENNUNG VARCHAR2(10)
     , NAME VARCHAR2(50)
     , STRASSE VARCHAR2(50)
     , PLZ VARCHAR2(10)
     , ORT VARCHAR2(50)
);

CREATE TABLE T_BA_VERL_NEU_ZUSATZ (
       ID NUMBER(9) NOT NULL
     , BA_VERL_NEU_ID NUMBER(9)
     , ABTEILUNG_ID NUMBER(9)
     , HVT_GRUPPE_ID NUMBER(9)
     , AUCH_SM NUMBER(1)
);

CREATE TABLE T_CARRIERBESTELLUNG (
       CB_ID NUMBER(9) NOT NULL
     , CB_2_ES_ID NUMBER(9)
     , CARRIER_ID NUMBER(9)
     , BESTELLT_AM DATE
     , ZURUECK_AM DATE
     , BEREITSTELLUNG_AM DATE
     , LBZ VARCHAR2(30)
     , VTRNR VARCHAR2(25)
     , AQS VARCHAR2(70)
     , LL VARCHAR2(70)
     , NEGATIVERM VARCHAR2(50)
     , WIEDERVORLAGE DATE
     , TIMESTAMP TIMESTAMP
     , KUENDIGUNG_AN_CARRIER DATE
     , KUENDBESTAETIGUNG_CARRIER DATE
     , AUFTRAG_ID_4_TAL_NA NUMBER(9)
     , TAL_NA_TYP NUMBER(9)
);

CREATE TABLE T_AUFTRAG_DATEN (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , PRODAK_ORDER__NO NUMBER(10)
     , PROD_ID NUMBER(9) NOT NULL
     , STATUS_ID NUMBER(9)
     , MMZ VARCHAR2(15)
     , MMZ_ID NUMBER(9)
     , BEMERKUNGEN VARCHAR2(255)
     , ANGEBOT_DATUM DATE
     , AUFTRAG_DATUM DATE
     , INBETRIEBNAHME DATE
     , KUENDIGUNG DATE
     , VORGABE_SCV DATE
     , VORGABE_KUNDE DATE
     , BESTELLNR VARCHAR2(20)
     , BUENDEL_NR NUMBER(9)
     , BUENDEL_NR_HERKUNFT VARCHAR2(20)
     , LA_GESP NUMBER(9)
     , BEARBEITER VARCHAR2(100) NOT NULL
     , TELBUCH NUMBER(1)
     , INVERSSUCHE NUMBER(1)
     , LBZ_LIEFERANT VARCHAR2(255)
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE NOT NULL
);

CREATE TABLE T_AUFTRAG_FAKTURA (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , RA_ID NUMBER(9) NOT NULL
     , BERECHNUNGSDATUM DATE DEFAULT null
     , BERECHNUNG_BIS DATE DEFAULT null
     , ANGEBOTSPREIS_MONATLICH NUMBER(12, 2)
     , ANGEBOTSPREIS_EINMALIG NUMBER(12, 2)
     , AUFTRAGSPREIS_MONATLICH NUMBER(12, 2)
     , AUFTRAGSPREIS_EINMALIG NUMBER(12, 2)
     , RABATT NUMBER(5, 2)
     , ENTGELD_MONATLICH NUMBER(12, 2)
     , KENNZEICHNUNG VARCHAR2(50)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , PRODUKTCODE VARCHAR2(30)
);

CREATE TABLE T_BANKVERBINDUNG (
       ID NUMBER(9) NOT NULL
     , BANK VARCHAR2(50)
     , BANKLEITZAHL VARCHAR2(9)
     , KONTO_NR VARCHAR2(50)
     , KONTOINHABER VARCHAR2(50)
     , ZAHLUNGSART VARCHAR2(50)
     , RA_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_EQ_DATEN (
       ID NUMBER(9) NOT NULL
     , MIETBEGINN DATE NOT NULL
     , MIETDAUER VARCHAR2(50) NOT NULL
     , MIETENDE DATE
     , KUENDIGUNGSTERMIN DATE
     , MIETZINS NUMBER(12, 2) NOT NULL
     , ABSCHLAG_STROM NUMBER(12, 2)
     , SONSTIGE_KOSTENTEXT VARCHAR2(70)
     , SONSTIGE_KOSTENMONATLICH NUMBER(12, 2)
     , SONSTIGE_KOSTEN NUMBER(12, 2)
     , NOTSTROM NUMBER(1)
     , KLIMAANLAGE NUMBER(1)
     , ZUGANG_24H NUMBER(1)
     , RA_ID NUMBER(9) NOT NULL
     , OBJEKT_ID NUMBER(9) NOT NULL
     , KUNDE__NO NUMBER(10) NOT NULL
     , EQ_RE_TEXT VARCHAR2(70)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_BA_VERL_HIST (
       ID NUMBER(9) NOT NULL
     , BENUTZER VARCHAR2(25) NOT NULL
     , TABELLE VARCHAR2(25) NOT NULL
     , FELD VARCHAR2(25) NOT NULL
     , WERT VARCHAR2(100) NOT NULL
     , DATUM DATE NOT NULL
     , BA_VERL_NEU_ID NUMBER(9)
     , BA_VERL_AEND_ID NUMBER(9)
     , BA_VERL_ZUSATZ_ID NUMBER(9)
);

CREATE TABLE T_AK0800 (
       ID NUMBER(9) NOT NULL
     , ZIEL VARCHAR2(100)
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , AUFTRAGSEINGANG DATE
     , UEBERNAHME NUMBER(1)
     , NEUSCHALTUNG NUMBER(1)
     , WUNSCHTERMIN DATE
     , CODENUMMER VARCHAR2(15)
     , VORWAHL VARCHAR2(6)
     , RUFNUMMER VARCHAR2(12)
     , KUENDIGUNG DATE
     , INBETRIEBNAHME DATE
     , WIRKSAM_AB DATE
     , MODELL_ID NUMBER(9)
     , REG_AN DATE
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
     , TS TIMESTAMP
);

CREATE TABLE T_SPERRE (
       S_ID NUMBER(9) NOT NULL
     , S_VORGANG NUMBER(9) NOT NULL
     , S_KD_NR NUMBER(10) NOT NULL
     , S_ART_SPERRE VARCHAR2(50) NOT NULL
     , S_TYP VARCHAR2(50) NOT NULL
     , S_ABT_ID NUMBER(9)
     , S_ABT VARCHAR2(50) NOT NULL
     , S_USER VARCHAR2(50)
     , S_DATUM DATE
     , S_TIMEST DATE
);

CREATE TABLE T_ZUGANG (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , EINWAHLRUFNUMMER VARCHAR2(50) NOT NULL
     , ART VARCHAR2(20) NOT NULL
);

CREATE TABLE T_BA_VERL_AEND_PROD_2_GRUPPE (
       PROD_ID NUMBER(9) NOT NULL
     , BA_VERL_AEND_GRUPPE_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_PRODUKT_2_SCHNITTSTELLE (
       PROD_ID NUMBER(9) NOT NULL
     , SCHNITTSTELLE_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_ES_ANSP (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_TECHNIK_ID NUMBER(9) NOT NULL
     , ES_ID NUMBER(9)
     , ANSPRECHPARTNER VARCHAR2(50)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_ES_LTG_DATEN (
       ID NUMBER(9) NOT NULL
     , ES_ID NUMBER(9) NOT NULL
     , LEITUNGSART NUMBER(9)
     , SCHNITTSTELLE_ID NUMBER(9) NOT NULL
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_INHOUSE (
       ID NUMBER(9) NOT NULL
     , ES_ID NUMBER(9)
     , RAUMNUMMER VARCHAR2(50)
     , VERKABELUNG VARCHAR2(50)
     , ANSPRECHPARTNER VARCHAR2(50)
     , BEMERKUNG VARCHAR2(255)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_ENDGERAET (
       ID NUMBER(9) NOT NULL
     , EG_TYP_ID NUMBER(9)
     , EG_HERKUNFT_ID NUMBER(9)
     , ES_ID NUMBER(9) NOT NULL
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_INT_DRUCK (
       ID NUMBER(9) NOT NULL
     , INT_ACCOUNT_ID NUMBER(9)
     , DATUM DATE
     , BEARBEITER VARCHAR2(40)
);

CREATE TABLE T_VPN_KONF (
       ID NUMBER(9) NOT NULL
     , KANALB NUMBER(1)
     , ANZ_KAN NUMBER(4)
     , DIAL_OUT NUMBER(1)
     , NR NUMBER(9) NOT NULL
     , PHYS_AUFTRAG_ID NUMBER(9)
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);

CREATE TABLE T_TDN_ZAEHLER (
       NK NUMBER(9) NOT NULL
     , WERT NUMBER(9) NOT NULL
);

CREATE TABLE T_GUI_MAPPING (
       ID NUMBER(9) NOT NULL
     , GUI_ID NUMBER(9) NOT NULL
     , REFERENZ_ID NUMBER(9) NOT NULL
     , REFERENZ_HERKUNFT VARCHAR2(255) NOT NULL
);

CREATE TABLE T_SDH_PHYSIK (
       SDHP_ID NUMBER(9) NOT NULL
     , ES_ID NUMBER(9) NOT NULL
     , NETZKOPPLUNG_ID NUMBER(9) NOT NULL
     , ANSCHALTPUNKT_ID NUMBER(9)
     , PROFIL_ID NUMBER(9)
     , CONNECTION_TYPE NUMBER(2)
     , VPI_A VARCHAR2(50) NOT NULL
     , VCI_A VARCHAR2(50) NOT NULL
     , VPI_B VARCHAR2(50) NOT NULL
     , VCI_B VARCHAR2(50) NOT NULL
     , ENDPUNKT VARCHAR2(50) NOT NULL
     , LFD_NR NUMBER(9) NOT NULL
     , BEZEICHNUNG VARCHAR2(50) NOT NULL
     , VERWENDET_VON DATE NOT NULL
     , VERWENDET_BIS DATE NOT NULL
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE NOT NULL
     , TIMEST TIMESTAMP
);

CREATE TABLE T_SPERRE_VERTEILUNG (
       PROD_ID NUMBER(9) NOT NULL
     , ABTEILUNG_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_SPERRE_INFO (
       ID NUMBER(9) NOT NULL
     , ABTEILUNG_ID NUMBER(9) NOT NULL
     , EMAIL VARCHAR2(100) NOT NULL
     , ACTIVE NUMBER(1)
);

CREATE TABLE T_FAKTURA (
       ID NUMBER(9) NOT NULL
     , FNR_ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , AUFTRAGSPREIS_EINMALIG NUMBER(12, 2) DEFAULT 0 NOT NULL
     , AUFTRAGSPREIS_MONATLICH NUMBER(12, 2) DEFAULT 0 NOT NULL
     , AUFTRAGSPREIS_ANTEILIG NUMBER(12, 2) DEFAULT 0 NOT NULL
     , INBETRIEBNAHME DATE
     , BERECHNUNGSDATUM DATE
     , BERECHNUNG_BIS DATE
);

CREATE TABLE T_FAKTURA_NO (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9)
     , FAKTURA_MONAT NUMBER(9) NOT NULL
     , GRUND VARCHAR2(50) NOT NULL
);

CREATE TABLE T_UEVT_2_ZIEL (
       ID NUMBER(9) NOT NULL
     , PROD_ID NUMBER(9) NOT NULL
     , UEVT_ID NUMBER(9) NOT NULL
     , HVT_STANDORT_ID_ZIEL NUMBER(9) NOT NULL
);

CREATE TABLE T_RANGIERUNGSMATRIX (
       ID NUMBER(9) NOT NULL
     , PROD_ID NUMBER(9) NOT NULL
     , UEVT_ID NUMBER(9) NOT NULL
     , PRODUKT2PHYSIKTYP_ID NUMBER(9) NOT NULL
     , PRIORITY NUMBER(9)
     , HVT_STANDORT_ID_ZIEL NUMBER(9)
     , PROJEKTIERUNG NUMBER(1)
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE NOT NULL
     , BEARBEITER VARCHAR2(50) NOT NULL
);

CREATE TABLE T_VERLAUF_ABTEILUNG (
       ID NUMBER(9) NOT NULL
     , VERLAUF_ID NUMBER(9) NOT NULL
     , DATUM_AN DATE
     , BEARBEITER VARCHAR2(100)
     , ABTEILUNG_ID NUMBER(9) NOT NULL
     , DATUM_ERLEDIGT DATE
     , AUSGETRAGEN_AM DATE
     , AUSGETRAGEN_VON VARCHAR2(100)
     , VERLAUF_STATUS_ID NUMBER(9)
     , BEMERKUNG VARCHAR2(255)
);

CREATE TABLE T_PHYSIKUEBERNAHME (
       ID NUMBER(9) NOT NULL
     , VORGANG NUMBER(9) NOT NULL
     , AUFTRAG_ID_A NUMBER(9) NOT NULL
     , AUFTRAG_ID_B NUMBER(9) NOT NULL
     , KRITERIUM VARCHAR2(10) NOT NULL
     , AENDERUNGSTYP NUMBER(9)
     , VERLAUF_ID NUMBER(9)
     , DATEW TIMESTAMP
);

CREATE TABLE T_PROD_2_SL (
       ID NUMBER(9) NOT NULL
     , PROD_ID NUMBER(9) DEFAULT 0 NOT NULL
     , SL_ID NUMBER(9) DEFAULT 0 NOT NULL
     , FREIGABE_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_HVT_BES_HIST (
       ID NUMBER(9) NOT NULL
     , BEST_ID NUMBER(9) NOT NULL
     , LEISTE VARCHAR2(7)
     , ANZAHL NUMBER(9)
     , BEARBEITER VARCHAR2(50)
     , DATUM DATE
);

CREATE TABLE T_KUBENA_HVT (
       ID NUMBER(9) NOT NULL
     , KUBENA_ID NUMBER(9)
     , HVT_ID_STANDORT NUMBER(9) NOT NULL
);

CREATE TABLE T_KUBENA_TDN (
       ID NUMBER(9) NOT NULL
     , KUBENA_ID NUMBER(9)
     , TDN VARCHAR2(50)
     , INPUT VARCHAR2(1)
     , VORH NUMBER(1) DEFAULT 0
);

CREATE TABLE T_KUBENA_PROD (
       ID NUMBER(9) NOT NULL
     , KUBENA_ID NUMBER(9)
     , PROD_ID NUMBER(9) DEFAULT 0
);

CREATE TABLE T_HVT_STANDORT_2_TECHNIK (
       HVT_ID_STANDORT NUMBER(9) NOT NULL
     , HVT_TECHNIK_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_CARRIER_LBZ (
       ID NUMBER(9) NOT NULL
     , CARRIER_ID NUMBER(9) NOT NULL
     , CLASS VARCHAR2(255) NOT NULL
     , REG_EXP VARCHAR2(255)
     , TYPE VARCHAR2(50) NOT NULL
);

CREATE TABLE T_PROD_2_PROD (
       ID NUMBER(9) NOT NULL
     , PROD_SRC NUMBER(9) DEFAULT 0 NOT NULL
     , PROD_DEST NUMBER(9) DEFAULT 0 NOT NULL
     , PHYSIKAEND_TYP NUMBER(9) DEFAULT 0 NOT NULL
     , CHAIN_ID NUMBER(9)
     , DESCRIPTION VARCHAR2(255)
);

CREATE TABLE T_SERVICECHAIN_2_COMMAND (
       ID NUMBER(9) NOT NULL
     , CHAIN_ID NUMBER(9) DEFAULT 0 NOT NULL
     , COMMAND_ID NUMBER(9) DEFAULT 0 NOT NULL
     , ORDER_NO NUMBER(3)
);

CREATE TABLE T_PVC_2_PROFIL (
       ID NUMBER(9) NOT NULL
     , PVC_ID NUMBER(9) NOT NULL
     , PROFIL_ID NUMBER(9) NOT NULL
);

CREATE TABLE T_LEISTUNG_SNAPSHOT (
       ID NUMBER(9) NOT NULL
     , VERLAUF_ID NUMBER(9) DEFAULT 0 NOT NULL
     , AUFTRAG_ID NUMBER(9) DEFAULT 0 NOT NULL
     , EXTERN_LEISTUNG__NO NUMBER(10) NOT NULL
);

CREATE TABLE T_VERLAUF_ACTIONS (
       ID NUMBER(9) NOT NULL
     , VERLAUF_ID NUMBER(9) DEFAULT 0 NOT NULL
     , IS_ZUGANG NUMBER(1)
     , IS_ABGANG NUMBER(1)
     , EXTERN_LEISTUNG__NO NUMBER(10) NOT NULL
);

CREATE TABLE T_AUFTRAG_IMPORT_FILES (
       ID NUMBER(9) NOT NULL
     , AUFTRAG_IMPORT_ID NUMBER(9) NOT NULL
     , ORIG_FILE_NAME VARCHAR2(255)
     , FILE_TYPE NUMBER(1) NOT NULL
     , FILE_STREAM BLOB NOT NULL
);

CREATE TABLE T_IP_ENDGERAET (
       ID NUMBER(9) NOT NULL
     , IP_ENDGERAET__ID NUMBER(9) NOT NULL
     , AUFTRAG_ID NUMBER(9) NOT NULL
     , HERSTELLER VARCHAR2(50)
     , MODELL VARCHAR2(50)
     , SERIAL_NUMBER VARCHAR2(50)
     , TYP NUMBER(9)
     , NAT NUMBER(1)
     , IP_LAN VARCHAR2(15)
     , SUBNETMASK VARCHAR2(15)
     , DHCP NUMBER(1)
     , ANZAHL_IP NUMBER(2)
     , IP_VIRTUELL_WEB NUMBER(2)
     , BEMERKUNG VARCHAR2(2000)
     , ANSP_ADMIN NUMBER(9)
     , ANSP_TECHNICAL NUMBER(9)
     , BEARBEITER VARCHAR2(50)
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE NOT NULL
);

CREATE TABLE T_PORT_FORWARD (
       ID NUMBER(9) NOT NULL
     , IP_ENDGERAET__ID NUMBER(9) NOT NULL
     , PROTOCOL NUMBER(9) NOT NULL
     , IP_ADDRESS VARCHAR2(15) NOT NULL
     , BEMERKUNG VARCHAR2(2000)
     , ACTIVE NUMBER(1)
     , BEARBEITER VARCHAR2(50)
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE NOT NULL
);

CREATE TABLE T_DSLAM (
       DSLAM NUMBER(9) NOT NULL
     , VPI_UBR_ADSL NUMBER(9)
     , VPI_SDSL NUMBER(9)
     , OUTER_TAG_ADSL NUMBER(9)
     , OUTER_TAG_SDSL NUMBER(9)
     , IP_ADDRESS VARCHAR2(20)
     , EINBAUPLATZ VARCHAR2(10)
     , VERSION VARCHAR2(10)
     , HVT_ID_STANDORT NUMBER(9)
     , HVT_TECHNIK_ID NUMBER(9) NOT NULL
     , GUELTIG_VON DATE
     , GUELTIG_BIS DATE
);





