ALTER TABLE T_AUFTRAG
  ADD CONSTRAINT PK_T_AUFTRAG
      PRIMARY KEY (ID);

ALTER TABLE T_EQ_GEBAEUDE
  ADD CONSTRAINT PK_T_EQ_GEBAEUDE
      PRIMARY KEY (ID);

ALTER TABLE T_ANREDE
  ADD CONSTRAINT PK_T_ANREDE
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_STATUS
  ADD CONSTRAINT PK_T_AUFTRAG_STATUS
      PRIMARY KEY (ID);

ALTER TABLE T_VPN
  ADD CONSTRAINT PK_T_VPN
      PRIMARY KEY (VPN_ID);

ALTER TABLE T_WOHNHEIM
  ADD CONSTRAINT PK_T_WOHNHEIM
      PRIMARY KEY (ID);

ALTER TABLE T_BA_VERL_AEND_GRUPPE
  ADD CONSTRAINT PK_T_BA_VERL_AEND_GRUPPE
      PRIMARY KEY (ID);

ALTER TABLE T_PRODUKTGRUPPE
  ADD CONSTRAINT PK_T_PRODUKTGRUPPE
      PRIMARY KEY (ID);

ALTER TABLE T_SCHNITTSTELLE
  ADD CONSTRAINT PK_T_SCHNITTSTELLE
      PRIMARY KEY (ID);

ALTER TABLE T_TDN
  ADD CONSTRAINT PK_T_TDN
      PRIMARY KEY (ID);

ALTER TABLE T_EG_TYP
  ADD CONSTRAINT PK_T_EG_TYP
      PRIMARY KEY (ID);

ALTER TABLE T_EG_HERKUNFT
  ADD CONSTRAINT PK_T_EG_HERKUNFT
      PRIMARY KEY (ID);

ALTER TABLE T_INT_ACCOUNT
  ADD CONSTRAINT PK_T_INT_ACCOUNT
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_TECHNIK_2_ENDSTELLE
  ADD CONSTRAINT PK_T_AUFTRAG_TECHNIK_2_ENDSTELLE
      PRIMARY KEY (ID);

ALTER TABLE T_CARRIER
  ADD CONSTRAINT PK_T_CARRIER
      PRIMARY KEY (ID);

ALTER TABLE T_NIEDERLASSUNG
  ADD CONSTRAINT PK_T_NIEDERLASSUNG
      PRIMARY KEY (ID);

ALTER TABLE T_GUI_DEFINITION
  ADD CONSTRAINT PK_T_GUI_DEFINITION
      PRIMARY KEY (ID);

ALTER TABLE T_LEITUNGSART
  ADD CONSTRAINT PK_T_LEITUNGSART
      PRIMARY KEY (ID);

ALTER TABLE T_MONTAGEART
  ADD CONSTRAINT PK_T_MONTAGEART
      PRIMARY KEY (ID);

ALTER TABLE T_PVC_VORGABE
  ADD CONSTRAINT PK_T_PVC_VORGABE
      PRIMARY KEY (ID);

ALTER TABLE T_AK0800_MODELL
  ADD CONSTRAINT PK_T_AK0800_MODELL
      PRIMARY KEY (ID);

ALTER TABLE T_ACC_ART
  ADD CONSTRAINT PK_T_ACC_ART
      PRIMARY KEY (ID);

ALTER TABLE T_HVT_TECHNIK
  ADD CONSTRAINT PK_T_HVT_TECHNIK
      PRIMARY KEY (ID);

ALTER TABLE T_ANBINDUNGSART
  ADD CONSTRAINT PK_T_ANBINDUNGSART
      PRIMARY KEY (ID);

ALTER TABLE T_FAKTURA_MONAT
  ADD CONSTRAINT PK_T_FAKTURA_MONAT
      PRIMARY KEY (ID);

ALTER TABLE T_COUNTER
  ADD CONSTRAINT PK_T_COUNTER
      PRIMARY KEY (COUNTER);

ALTER TABLE T_CB_2_ES
  ADD CONSTRAINT PK_T_CB_2_ES
      PRIMARY KEY (ID);

ALTER TABLE T_VERLAUF_STATUS
  ADD CONSTRAINT PK_T_VERLAUF_STATUS
      PRIMARY KEY (ID);

ALTER TABLE T_FAKTURA_BEARBEITER
  ADD CONSTRAINT PK_T_FAKTURA_BEARBEITER
      PRIMARY KEY (ID);

ALTER TABLE T_PORTIERUNGSART
  ADD CONSTRAINT PK_T_PORTIERUNGSART
      PRIMARY KEY (ID);

ALTER TABLE T_E_RECHNUNG_DRUCK
  ADD CONSTRAINT PK_T_E_RECHNUNG_DRUCK
      PRIMARY KEY (ID);

ALTER TABLE T_REGISTRY
  ADD CONSTRAINT PK_T_REGISTRY
      PRIMARY KEY (ID);

ALTER TABLE T_PHYSIKAENDERUNGSTYP
  ADD CONSTRAINT PK_T_PHYSIKAENDERUNGSTYP
      PRIMARY KEY (ID);

ALTER TABLE T_KUBENA
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_PROD_SL_FREIGABE
  ADD CONSTRAINT PK_T_PROD_SL_FREIGABE
      PRIMARY KEY (ID);

ALTER TABLE T_LEISTUNG
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (LEISTUNG_NO_DN);

ALTER TABLE T_LEISTUNG_DN
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (LFDNR);

ALTER TABLE T_DB_QUERIES
  ADD CONSTRAINT PK_T_DB_QUERIES
      PRIMARY KEY (ID);

ALTER TABLE T_SERVICE_CHAIN
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_SERVICE_COMMANDS
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_TAL_AENDERUNGSTYP
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_SDH_PROFIL
  ADD CONSTRAINT PK_T_SDH_PROFIL
      PRIMARY KEY (ID);

ALTER TABLE T_BILLING_LEISTUNG_KONFIG
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE WISSEN
  ADD CONSTRAINT PK_WISSEN
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_IMPORT_STATUS
  ADD CONSTRAINT PK_T_AUFTRAG_IMPORT_STATUS
      PRIMARY KEY (ID);

ALTER TABLE T_SIGNATURED_FILES
  ADD CONSTRAINT PK_T_SIGNATURED_FILES
      PRIMARY KEY (ID);

ALTER TABLE T_DIALER
  ADD CONSTRAINT PK_T_DIALER
      PRIMARY KEY (ID);

ALTER TABLE T_REFERENCE
  ADD CONSTRAINT PK_T_REFERENCE
      PRIMARY KEY (ID);

ALTER TABLE T_ANSCHLUSSART
  ADD CONSTRAINT PK_T_ANSCHLUSSART
      PRIMARY KEY (ID);

ALTER TABLE T_HVT_GRUPPE
  ADD CONSTRAINT PK_T_HVT_GRUPPE
      PRIMARY KEY (HVT_GRUPPE_ID);

ALTER TABLE T_HVT_STANDORT
  ADD CONSTRAINT PK_T_HVT_STANDORT
      PRIMARY KEY (HVT_ID_STANDORT);

ALTER TABLE T_STRASSENLISTE
  ADD CONSTRAINT PK_T_STRASSENLISTE
      PRIMARY KEY (SL_ID);

ALTER TABLE T_PHYSIKTYP
  ADD CONSTRAINT PK_T_PHYSIKTYP
      PRIMARY KEY (ID);

ALTER TABLE T_PRODUKT
  ADD CONSTRAINT PK_T_PRODUKT
      PRIMARY KEY (PROD_ID);

ALTER TABLE T_EQUIPMENT
  ADD CONSTRAINT PK_T_EQUIPMENT
      PRIMARY KEY (EQ_ID);

ALTER TABLE T_UEVT
  ADD CONSTRAINT PK_T_UEVT
      PRIMARY KEY (UEVT_ID);

ALTER TABLE T_RECHNUNGSANSCHRIFT
  ADD CONSTRAINT PK_T_RECHNUNGSANSCHRIFT
      PRIMARY KEY (ID);

ALTER TABLE T_EQ_OBJEKT
  ADD CONSTRAINT PK_T_EQ_OBJEKT
      PRIMARY KEY (ID);

ALTER TABLE T_BA_VERL_AEND
  ADD CONSTRAINT PK_T_BA_VERL_AEND
      PRIMARY KEY (ID);

ALTER TABLE T_BA_VERL_NEU
  ADD CONSTRAINT PK_T_BA_VERL_NEU
      PRIMARY KEY (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT PK_T_ENDSTELLE
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT PK_T_AUFTRAG_TECHNIK
      PRIMARY KEY (ID);

ALTER TABLE T_ABTEILUNG
  ADD CONSTRAINT PK_T_ABTEILUNG
      PRIMARY KEY (ID);

ALTER TABLE T_RANGIERUNG
  ADD CONSTRAINT PK_T_RANGIERUNG
      PRIMARY KEY (RANGIER_ID);

ALTER TABLE T_FAKTURA_NR
  ADD CONSTRAINT PK_T_FAKTURA_NR
      PRIMARY KEY (ID);

ALTER TABLE T_PRODUKT_2_PHYSIKTYP
  ADD CONSTRAINT PK_T_PRODUKT_2_PHYSIKTYP
      PRIMARY KEY (ID);

ALTER TABLE T_VERLAUF
  ADD CONSTRAINT PK_T_VERLAUF
      PRIMARY KEY (ID);

ALTER TABLE T_HVT_BESTELLUNG
  ADD CONSTRAINT PK_T_HVT_BESTELLUNG
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_IMPORT
  ADD CONSTRAINT PK_T_AUFTRAG_IMPORT
      PRIMARY KEY (ID);

ALTER TABLE T_CARRIER_KENNUNG
  ADD CONSTRAINT PK_T_CARRIER_KENNUNG
      PRIMARY KEY (ID);

ALTER TABLE T_BA_VERL_NEU_ZUSATZ
  ADD CONSTRAINT PK_T_BA_VERL_NEU_ZUSATZ
      PRIMARY KEY (ID);

ALTER TABLE T_CARRIERBESTELLUNG
  ADD CONSTRAINT PK_T_CARRIERBESTELLUNG
      PRIMARY KEY (CB_ID);

ALTER TABLE T_AUFTRAG_DATEN
  ADD CONSTRAINT PK_T_AUFTRAG_DATEN
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_FAKTURA
  ADD CONSTRAINT PK_T_AUFTRAG_FAKTURA
      PRIMARY KEY (ID);

ALTER TABLE T_BANKVERBINDUNG
  ADD CONSTRAINT PK_T_BANKVERBINDUNG
      PRIMARY KEY (ID);

ALTER TABLE T_EQ_DATEN
  ADD CONSTRAINT PK_T_EQ_DATEN
      PRIMARY KEY (ID);

ALTER TABLE T_BA_VERL_HIST
  ADD CONSTRAINT PK_T_BA_VERL_HIST
      PRIMARY KEY (ID);

ALTER TABLE T_AK0800
  ADD CONSTRAINT PK_T_AK0800
      PRIMARY KEY (ID);

ALTER TABLE T_SPERRE
  ADD CONSTRAINT PK_T_SPERRE
      PRIMARY KEY (S_ID);

ALTER TABLE T_ZUGANG
  ADD CONSTRAINT PK_T_ZUGANG
      PRIMARY KEY (ID);

ALTER TABLE T_BA_VERL_AEND_PROD_2_GRUPPE
  ADD CONSTRAINT PK_T_BA_VERL_AEND_PROD_2_GRUPPE
      PRIMARY KEY (PROD_ID, BA_VERL_AEND_GRUPPE_ID);

ALTER TABLE T_PRODUKT_2_SCHNITTSTELLE
  ADD CONSTRAINT PK_T_PRODUKT_2_SCHNITTSTELLE
      PRIMARY KEY (PROD_ID, SCHNITTSTELLE_ID);

ALTER TABLE T_ES_ANSP
  ADD CONSTRAINT PK_T_ES_ANSP
      PRIMARY KEY (ID);

ALTER TABLE T_ES_LTG_DATEN
  ADD CONSTRAINT PK_T_ES_LTG_DATEN
      PRIMARY KEY (ID);

ALTER TABLE T_INHOUSE
  ADD CONSTRAINT PK_T_INHOUSE
      PRIMARY KEY (ID);

ALTER TABLE T_ENDGERAET
  ADD CONSTRAINT PK_T_ENDGERAET
      PRIMARY KEY (ID);

ALTER TABLE T_INT_DRUCK
  ADD CONSTRAINT PK_T_INT_DRUCK
      PRIMARY KEY (ID);

ALTER TABLE T_VPN_KONF
  ADD CONSTRAINT PK_T_VPN_KONF
      PRIMARY KEY (ID);

ALTER TABLE T_TDN_ZAEHLER
  ADD CONSTRAINT PK_T_TDN_ZAEHLER
      PRIMARY KEY (NK);

ALTER TABLE T_GUI_MAPPING
  ADD CONSTRAINT PK_T_GUI_MAPPING
      PRIMARY KEY (ID);

ALTER TABLE T_SDH_PHYSIK
  ADD CONSTRAINT PK_T_SDH_PHYSIK
      PRIMARY KEY (SDHP_ID);

ALTER TABLE T_SPERRE_VERTEILUNG
  ADD CONSTRAINT PK_T_SPERRE_VERTEILUNG
      PRIMARY KEY (PROD_ID, ABTEILUNG_ID);

ALTER TABLE T_SPERRE_INFO
  ADD CONSTRAINT PK_T_SPERRE_INFO
      PRIMARY KEY (ID);

ALTER TABLE T_FAKTURA
  ADD CONSTRAINT PK_T_FAKTURA
      PRIMARY KEY (ID);

ALTER TABLE T_FAKTURA_NO
  ADD CONSTRAINT PK_T_FAKTURA_NO
      PRIMARY KEY (ID);

ALTER TABLE T_UEVT_2_ZIEL
  ADD CONSTRAINT PK_T_UEVT_2_ZIEL
      PRIMARY KEY (ID);

ALTER TABLE T_RANGIERUNGSMATRIX
  ADD CONSTRAINT PK_T_RANGIERUNGSMATRIX
      PRIMARY KEY (ID);

ALTER TABLE T_VERLAUF_ABTEILUNG
  ADD CONSTRAINT PK_T_VERLAUF_ABTEILUNG
      PRIMARY KEY (ID);

ALTER TABLE T_PHYSIKUEBERNAHME
  ADD CONSTRAINT PK_T_PHYSIKUEBERNAHME
      PRIMARY KEY (ID);

ALTER TABLE T_PROD_2_SL
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_HVT_BES_HIST
  ADD CONSTRAINT PK_T_HVT_BES_HIST
      PRIMARY KEY (ID);

ALTER TABLE T_KUBENA_HVT
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_KUBENA_TDN
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_KUBENA_PROD
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_HVT_STANDORT_2_TECHNIK
  ADD CONSTRAINT PK_T_HVT_STANDORT_2_TECHNIK
      PRIMARY KEY (HVT_ID_STANDORT, HVT_TECHNIK_ID);

ALTER TABLE T_CARRIER_LBZ
  ADD CONSTRAINT PK_T_CARRIER_LBZ
      PRIMARY KEY (ID);

ALTER TABLE T_PROD_2_PROD
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_SERVICECHAIN_2_COMMAND
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_PVC_2_PROFIL
  ADD CONSTRAINT PK_T_PVC_2_PROFIL
      PRIMARY KEY (ID);

ALTER TABLE T_LEISTUNG_SNAPSHOT
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_VERLAUF_ACTIONS
  ADD CONSTRAINT PRIMARY
      PRIMARY KEY (ID);

ALTER TABLE T_AUFTRAG_IMPORT_FILES
  ADD CONSTRAINT PK_T_AUFTRAG_IMPORT_FILES
      PRIMARY KEY (ID);

ALTER TABLE T_IP_ENDGERAET
  ADD CONSTRAINT PK_T_IP_ENDGERAET
      PRIMARY KEY (ID);

ALTER TABLE T_PORT_FORWARD
  ADD CONSTRAINT PK_T_PORT_FORWARD
      PRIMARY KEY (ID);

ALTER TABLE T_DSLAM
  ADD CONSTRAINT PK_T_DSLAM
      PRIMARY KEY (DSLAM);

