ALTER TABLE T_HVT_GRUPPE
  ADD CONSTRAINT FK_T_HVT_GRUPPE_1
      FOREIGN KEY (NIEDERLASSUNG_ID)
      REFERENCES T_NIEDERLASSUNG (ID);

ALTER TABLE T_HVT_STANDORT
  ADD CONSTRAINT FK_T_HVT_STANDORT_1
      FOREIGN KEY (HVT_GRUPPE_ID)
      REFERENCES T_HVT_GRUPPE (HVT_GRUPPE_ID);

ALTER TABLE T_HVT_STANDORT
  ADD CONSTRAINT FK_HVTSTD_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES T_CARRIER (ID);

ALTER TABLE T_HVT_STANDORT
  ADD CONSTRAINT FK_HVTSTD_2_CKENNUNG
      FOREIGN KEY (CARRIER_KENNUNG_ID)
      REFERENCES T_CARRIER_KENNUNG (ID);

ALTER TABLE T_STRASSENLISTE
  ADD CONSTRAINT FK_T_STRASSENLISTE_1
      FOREIGN KEY (HVT_GRUPPE_ID)
      REFERENCES T_HVT_GRUPPE (HVT_GRUPPE_ID);

ALTER TABLE T_PHYSIKTYP
  ADD CONSTRAINT FK_PHYSIKTYP_2_HVTTEC
      FOREIGN KEY (HVT_TECHNIK_ID)
      REFERENCES T_HVT_TECHNIK (ID);

ALTER TABLE T_PRODUKT
  ADD CONSTRAINT FK_T_PRODUKT_2_GRUPPE
      FOREIGN KEY (PRODUKTGRUPPE_ID)
      REFERENCES T_PRODUKTGRUPPE (ID);

ALTER TABLE T_PRODUKT
  ADD CONSTRAINT FK_PRODUKT_2_LART
      FOREIGN KEY (LEITUNGSART)
      REFERENCES T_LEITUNGSART (ID);

ALTER TABLE T_PRODUKT
  ADD CONSTRAINT FK_T_PRODUKT_3
      FOREIGN KEY (UPSTREAM)
      REFERENCES T_LEITUNGSART (ID);

ALTER TABLE T_PRODUKT
  ADD CONSTRAINT FK_PRODUKT_2_ABT
      FOREIGN KEY (VERTEILUNG_DURCH)
      REFERENCES T_ABTEILUNG (ID);

ALTER TABLE T_EQUIPMENT
  ADD CONSTRAINT FK_EQUIPMENT_2_HVTST
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_UEVT
  ADD CONSTRAINT FK_T_UEVT_1
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_RECHNUNGSANSCHRIFT
  ADD CONSTRAINT FK_RAMWST_2_REF
      FOREIGN KEY (MWST_ID)
      REFERENCES T_REFERENCE (ID);

ALTER TABLE T_EQ_OBJEKT
  ADD CONSTRAINT FK_EQ_OBJEKT_2_GEBAEUDE
      FOREIGN KEY (GEBAEUDE_ID)
      REFERENCES T_EQ_GEBAEUDE (ID);

ALTER TABLE T_BA_VERL_AEND
  ADD CONSTRAINT FK_T_BA_VERL_AEND_1
      FOREIGN KEY (BA_VERL_AEND_GRUPPE_ID)
      REFERENCES T_BA_VERL_AEND_GRUPPE (ID);

ALTER TABLE T_BA_VERL_NEU
  ADD CONSTRAINT FK_BA_NEU_2_PRODGR
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_T_ENDSTELLE_2
      FOREIGN KEY (SL_ID)
      REFERENCES T_STRASSENLISTE (SL_ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_T_ENDSTELLE_3
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_T_ENDSTELLE_4
      FOREIGN KEY (ES_GRUPPE)
      REFERENCES T_AUFTRAG_TECHNIK_2_ENDSTELLE (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ENDSTELLE_2_ANSCHLUSSART
      FOREIGN KEY (ANSCHLUSSART)
      REFERENCES T_ANSCHLUSSART (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ENDSTELLE_2_MONTAGEART
      FOREIGN KEY (NT_MONTAGEART)
      REFERENCES T_MONTAGEART (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ES_2_CB2ES
      FOREIGN KEY (CB_2_ES_ID)
      REFERENCES T_CB_2_ES (ID);

ALTER TABLE T_ENDSTELLE
  ADD CONSTRAINT FK_ENDSTELLE2_RANG
      FOREIGN KEY (RANGIER_ID)
      REFERENCES T_RANGIERUNG (RANGIER_ID)
   
   ;

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_T_AUFTRAG_TECHNIK_1
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_T_AUFTRAG_TECHNIK_2
      FOREIGN KEY (TDN_ID)
      REFERENCES T_TDN (ID)
   
   ;

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_AUFTRAG_TECHNIK_2_INTACCOUNT
      FOREIGN KEY (INT_ACCOUNT_ID)
      REFERENCES T_INT_ACCOUNT (ID)
   
   ;

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_T_AUFTRAG_TECHNIK_6
      FOREIGN KEY (AT_2_ES_ID)
      REFERENCES T_AUFTRAG_TECHNIK_2_ENDSTELLE (ID)
   
   ;

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_T_AUFTRAG_TECHNIK_8
      FOREIGN KEY (VPN_ID)
      REFERENCES T_VPN (VPN_ID);

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_TECHNIK_2_ANBART
      FOREIGN KEY (ANBINDUNGSART_ID)
      REFERENCES T_ANBINDUNGSART (ID)
   
   ;

ALTER TABLE T_AUFTRAG_TECHNIK
  ADD CONSTRAINT FK_AT_2_VERLAEND
      FOREIGN KEY (AUFTRAGSART)
      REFERENCES T_BA_VERL_AEND (ID)
   
   ;

ALTER TABLE T_ABTEILUNG
  ADD CONSTRAINT FK_T_ABTEILUNG_1
      FOREIGN KEY (NIEDERLASSUNG_ID)
      REFERENCES T_NIEDERLASSUNG (ID)
   
   ;

ALTER TABLE T_RANGIERUNG
  ADD CONSTRAINT FK_T_RANGIERUNG_1
      FOREIGN KEY (EQ_IN_ID)
      REFERENCES T_EQUIPMENT (EQ_ID)
   
   ;

ALTER TABLE T_RANGIERUNG
  ADD CONSTRAINT FK_RANG_2_PHYSIKTYP
      FOREIGN KEY (PHYSIK_TYP)
      REFERENCES T_PHYSIKTYP (ID);

ALTER TABLE T_RANGIERUNG
  ADD CONSTRAINT FK_T_RANGIERUNG_3
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_RANGIERUNG
  ADD CONSTRAINT FK_RANGOUT_2_EQ
      FOREIGN KEY (EQ_OUT_ID)
      REFERENCES T_EQUIPMENT (EQ_ID)
   
   ;

ALTER TABLE T_FAKTURA_NR
  ADD CONSTRAINT FK_FAKTURANR_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES T_RECHNUNGSANSCHRIFT (ID)
   
   ;

ALTER TABLE T_FAKTURA_NR
  ADD CONSTRAINT FK_FAKTURANR_2_MONAT
      FOREIGN KEY (FAKTURA_MONAT)
      REFERENCES T_FAKTURA_MONAT (ID)
   
   ;

ALTER TABLE T_FAKTURA_NR
  ADD CONSTRAINT FK_FAKTURA_2_BEARB
      FOREIGN KEY (BEARBEITER)
      REFERENCES T_FAKTURA_BEARBEITER (ID)
   
   ;

ALTER TABLE T_PRODUKT_2_PHYSIKTYP
  ADD CONSTRAINT FK_PROD2PTYP_2_PTYP
      FOREIGN KEY (PHYSIKTYP)
      REFERENCES T_PHYSIKTYP (ID)
   
   ;

ALTER TABLE T_PRODUKT_2_PHYSIKTYP
  ADD CONSTRAINT FK_PROD2PTYP_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_PRODUKT_2_PHYSIKTYP
  ADD CONSTRAINT FK_P2PT_2_PT
      FOREIGN KEY (PARENTPHYSIKTYP_ID)
      REFERENCES T_PHYSIKTYP (ID)
   
   ;

ALTER TABLE T_VERLAUF
  ADD CONSTRAINT FK_VERLAUF_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_VERLAUF
  ADD CONSTRAINT FK_VERLAUF_2_BAVERLAEND
      FOREIGN KEY (ANLASS)
      REFERENCES T_BA_VERL_AEND (ID)
   
   ;

ALTER TABLE T_VERLAUF
  ADD CONSTRAINT FK_VERLAUF_2_AS
      FOREIGN KEY (STATUS_ID_ALT)
      REFERENCES T_AUFTRAG_STATUS (ID)
   
   ;

ALTER TABLE T_VERLAUF
  ADD CONSTRAINT FK_VERLAUF_2_VS
      FOREIGN KEY (VERLAUF_STATUS_ID)
      REFERENCES T_VERLAUF_STATUS (ID)
   
   ;

ALTER TABLE T_VERLAUF
  ADD CONSTRAINT FK_VERL_2_PORTART
      FOREIGN KEY (PORTIERUNGSART)
      REFERENCES T_PORTIERUNGSART (ID)
   
   ;

ALTER TABLE T_HVT_BESTELLUNG
  ADD CONSTRAINT FK_HVTBEST_2_UEVT
      FOREIGN KEY (UEVT_ID)
      REFERENCES T_UEVT (UEVT_ID)
   
   ;

ALTER TABLE T_AUFTRAG_IMPORT
  ADD CONSTRAINT FK_AUFTRAGIMPORT_2_STATUS
      FOREIGN KEY (IMPORT_STATUS)
      REFERENCES T_AUFTRAG_IMPORT_STATUS (ID)
   
   ;

ALTER TABLE T_CARRIER_KENNUNG
  ADD CONSTRAINT FK_CKENNUNG_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES T_CARRIER (ID)
   
   ;

ALTER TABLE T_BA_VERL_NEU_ZUSATZ
  ADD CONSTRAINT FK_T_BA_VERL_NEU_ZUSATZ_1
      FOREIGN KEY (BA_VERL_NEU_ID)
      REFERENCES T_BA_VERL_NEU (ID)
   
   ;

ALTER TABLE T_BA_VERL_NEU_ZUSATZ
  ADD CONSTRAINT FK_T_BA_VERL_NEU_ZUSATZ_2
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES T_ABTEILUNG (ID)
   
   ;

ALTER TABLE T_BA_VERL_NEU_ZUSATZ
  ADD CONSTRAINT FK_T_BA_VERL_NEU_ZUSATZ_3
      FOREIGN KEY (HVT_GRUPPE_ID)
      REFERENCES T_HVT_GRUPPE (HVT_GRUPPE_ID)
   
   ;

ALTER TABLE T_CARRIERBESTELLUNG
  ADD CONSTRAINT FK_T_CARRIERBESTELLUNG_2
      FOREIGN KEY (CARRIER_ID)
      REFERENCES T_CARRIER (ID)
   
   ;

ALTER TABLE T_CARRIERBESTELLUNG
  ADD CONSTRAINT FK_CB_2_CB2ES
      FOREIGN KEY (CB_2_ES_ID)
      REFERENCES T_CB_2_ES (ID)
   
   ;

ALTER TABLE T_CARRIERBESTELLUNG
  ADD CONSTRAINT FK_CB_2_TALTYP
      FOREIGN KEY (TAL_NA_TYP)
      REFERENCES T_TAL_AENDERUNGSTYP (ID)
   
   ;

ALTER TABLE T_CARRIERBESTELLUNG
  ADD CONSTRAINT FK_CB_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID_4_TAL_NA)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_AUFTRAG_DATEN
  ADD CONSTRAINT FK_AUFTRAGDATEN_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_AUFTRAG_DATEN
  ADD CONSTRAINT FK_AUFTRAG_DATEN_ASTATUS
      FOREIGN KEY (STATUS_ID)
      REFERENCES T_AUFTRAG_STATUS (ID)
   
   ;

ALTER TABLE T_AUFTRAG_DATEN
  ADD CONSTRAINT FK_T_AUFTRAG_DATEN_3
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_AUFTRAG_DATEN
  ADD CONSTRAINT FK_ADMMZ_2_REF
      FOREIGN KEY (MMZ_ID)
      REFERENCES T_REFERENCE (ID)
   ON DELETE CASCADE
   ON UPDATE NO ACTION;

ALTER TABLE T_AUFTRAG_FAKTURA
  ADD CONSTRAINT FK_AUFTRAG_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES T_RECHNUNGSANSCHRIFT (ID)
   
   ;

ALTER TABLE T_AUFTRAG_FAKTURA
  ADD CONSTRAINT FK_AFAKTURA_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_BANKVERBINDUNG
  ADD CONSTRAINT FK_BANK_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES T_RECHNUNGSANSCHRIFT (ID)
   
   ;

ALTER TABLE T_EQ_DATEN
  ADD CONSTRAINT FK_EQ_DATEN_2_RA
      FOREIGN KEY (RA_ID)
      REFERENCES T_RECHNUNGSANSCHRIFT (ID)
   
   ;

ALTER TABLE T_EQ_DATEN
  ADD CONSTRAINT FK_EQ_DATEN_2_OBJEKT
      FOREIGN KEY (OBJEKT_ID)
      REFERENCES T_EQ_OBJEKT (ID)
   
   ;

ALTER TABLE T_BA_VERL_HIST
  ADD CONSTRAINT FK_BA_VERL_HIST_2_VERL_NEU
      FOREIGN KEY (BA_VERL_NEU_ID)
      REFERENCES T_BA_VERL_NEU (ID)
   
   ;

ALTER TABLE T_BA_VERL_HIST
  ADD CONSTRAINT FK_BA_VERL_HIST_2_VERLHIST
      FOREIGN KEY (BA_VERL_AEND_ID)
      REFERENCES T_BA_VERL_AEND (ID)
   
   ;

ALTER TABLE T_BA_VERL_HIST
  ADD CONSTRAINT FK_BA_HIST_2_ZUSATZ
      FOREIGN KEY (BA_VERL_ZUSATZ_ID)
      REFERENCES T_BA_VERL_NEU_ZUSATZ (ID)
   
   ;

ALTER TABLE T_AK0800
  ADD CONSTRAINT FK_AK0800_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_AK0800
  ADD CONSTRAINT FK_T_AK0800_2_MODELL
      FOREIGN KEY (MODELL_ID)
      REFERENCES T_AK0800_MODELL (ID)
   
   ;

ALTER TABLE T_SPERRE
  ADD CONSTRAINT FK_SPERRE_2_ABT
      FOREIGN KEY (S_ABT_ID)
      REFERENCES T_ABTEILUNG (ID)
   
   ;

ALTER TABLE T_ZUGANG
  ADD CONSTRAINT FK_ZUGANG_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_BA_VERL_AEND_PROD_2_GRUPPE
  ADD CONSTRAINT FK_T_BA_VERL_AEND_PROD_2_GRUPPE_1
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID);

ALTER TABLE T_BA_VERL_AEND_PROD_2_GRUPPE
  ADD CONSTRAINT FK_T_BA_VERL_AEND_PROD_2_GRUPPE_2
      FOREIGN KEY (BA_VERL_AEND_GRUPPE_ID)
      REFERENCES T_BA_VERL_AEND_GRUPPE (ID);

ALTER TABLE T_PRODUKT_2_SCHNITTSTELLE
  ADD CONSTRAINT FK_T_PRODUKT_2_SCHNITTSTELLE_1
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID);

ALTER TABLE T_PRODUKT_2_SCHNITTSTELLE
  ADD CONSTRAINT FK_T_PRODUKT_2_SCHNITTSTELLE_2
      FOREIGN KEY (SCHNITTSTELLE_ID)
      REFERENCES T_SCHNITTSTELLE (ID);

ALTER TABLE T_ES_ANSP
  ADD CONSTRAINT FK_T_ES_ANSP_1
      FOREIGN KEY (AUFTRAG_TECHNIK_ID)
      REFERENCES T_AUFTRAG_TECHNIK (ID)
   
   ;

ALTER TABLE T_ES_ANSP
  ADD CONSTRAINT FK_ES_ANSP_2_ES
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
   
   ;

ALTER TABLE T_ES_LTG_DATEN
  ADD CONSTRAINT FK_T_ES_LTG_DATEN_2
      FOREIGN KEY (SCHNITTSTELLE_ID)
      REFERENCES T_SCHNITTSTELLE (ID)
   
   ;

ALTER TABLE T_ES_LTG_DATEN
  ADD CONSTRAINT FK_T_ES_LTG_DATEN_3
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
   
   ;

ALTER TABLE T_ES_LTG_DATEN
  ADD CONSTRAINT FK_LTG_DATEN_2_LART
      FOREIGN KEY (LEITUNGSART)
      REFERENCES T_LEITUNGSART (ID)
   
   ;

ALTER TABLE T_INHOUSE
  ADD CONSTRAINT FK_T_INHOUSE_1
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
   
   ;

ALTER TABLE T_ENDGERAET
  ADD CONSTRAINT FK_T_ENDGERAET_1
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
   
   ;

ALTER TABLE T_ENDGERAET
  ADD CONSTRAINT FK_T_ENDGERAET_2
      FOREIGN KEY (EG_TYP_ID)
      REFERENCES T_EG_TYP (ID)
   
   ;

ALTER TABLE T_ENDGERAET
  ADD CONSTRAINT FK_T_ENDGERAET_3
      FOREIGN KEY (EG_HERKUNFT_ID)
      REFERENCES T_EG_HERKUNFT (ID)
   
   ;

ALTER TABLE T_INT_DRUCK
  ADD CONSTRAINT FK_INT_DRUCK_2_INTACCOUNT
      FOREIGN KEY (INT_ACCOUNT_ID)
      REFERENCES T_INT_ACCOUNT (ID)
   
   ;

ALTER TABLE T_VPN_KONF
  ADD CONSTRAINT FK_T_VPN_KONF_1
      FOREIGN KEY (NR)
      REFERENCES T_AUFTRAG (ID);

ALTER TABLE T_VPN_KONF
  ADD CONSTRAINT FK_T_VPN_KONF_2
      FOREIGN KEY (PHYS_AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_TDN_ZAEHLER
  ADD CONSTRAINT FK_TDN_ZAEHLER_2_NL
      FOREIGN KEY (NK)
      REFERENCES T_NIEDERLASSUNG (ID);

ALTER TABLE T_GUI_MAPPING
  ADD CONSTRAINT FK_T_GUI_MAPPING_1
      FOREIGN KEY (GUI_ID)
      REFERENCES T_GUI_DEFINITION (ID)
   
   ;

ALTER TABLE T_SDH_PHYSIK
  ADD CONSTRAINT FK_SDH_PHYSIK_2_ES
      FOREIGN KEY (ES_ID)
      REFERENCES T_ENDSTELLE (ID)
   
   ;

ALTER TABLE T_SDH_PHYSIK
  ADD CONSTRAINT FK_SDHPHYSIK_2_PVC
      FOREIGN KEY (NETZKOPPLUNG_ID)
      REFERENCES T_PVC_VORGABE (ID)
   
   ;

ALTER TABLE T_SDH_PHYSIK
  ADD CONSTRAINT FK_SDHPHYSIK_2_PVC_ANSCHALT
      FOREIGN KEY (ANSCHALTPUNKT_ID)
      REFERENCES T_PVC_VORGABE (ID)
   
   ;

ALTER TABLE T_SDH_PHYSIK
  ADD CONSTRAINT FK_SDHPHYSIK_2_PROFIL
      FOREIGN KEY (PROFIL_ID)
      REFERENCES T_SDH_PROFIL (ID)
   
   ;

ALTER TABLE T_SPERRE_VERTEILUNG
  ADD CONSTRAINT FK_SPERREVERT_2_ABT
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES T_ABTEILUNG (ID)
   
   ;

ALTER TABLE T_SPERRE_VERTEILUNG
  ADD CONSTRAINT FK_SPERREVERT_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_SPERRE_INFO
  ADD CONSTRAINT FK_SPERRE_INFO_2_ABT
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES T_ABTEILUNG (ID)
   
   ;

ALTER TABLE T_FAKTURA
  ADD CONSTRAINT FK_FAKTURA_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_FAKTURA
  ADD CONSTRAINT FK_FAKTURA_2_FNR
      FOREIGN KEY (FNR_ID)
      REFERENCES T_FAKTURA_NR (ID)
   
   ;

ALTER TABLE T_FAKTURA_NO
  ADD CONSTRAINT FK_FAKTURANO_2_MONAT
      FOREIGN KEY (FAKTURA_MONAT)
      REFERENCES T_FAKTURA_MONAT (ID)
   
   ;

ALTER TABLE T_FAKTURA_NO
  ADD CONSTRAINT FK_FAKTURANO_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_UEVT_2_ZIEL
  ADD CONSTRAINT FK_UEVT2ZIEL_2_UEVT
      FOREIGN KEY (UEVT_ID)
      REFERENCES T_UEVT (UEVT_ID)
   
   ;

ALTER TABLE T_UEVT_2_ZIEL
  ADD CONSTRAINT FK_UEVT2ZIEL_2_HVT
      FOREIGN KEY (HVT_STANDORT_ID_ZIEL)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT)
   
   ;

ALTER TABLE T_UEVT_2_ZIEL
  ADD CONSTRAINT FK_UEVT2ZIEL_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_RANGIERUNGSMATRIX
  ADD CONSTRAINT FK_RMATRIX_2_UEVT
      FOREIGN KEY (UEVT_ID)
      REFERENCES T_UEVT (UEVT_ID)
   
   ;

ALTER TABLE T_RANGIERUNGSMATRIX
  ADD CONSTRAINT FK_RMATRIX_2_P2P
      FOREIGN KEY (PRODUKT2PHYSIKTYP_ID)
      REFERENCES T_PRODUKT_2_PHYSIKTYP (ID)
   
   ;

ALTER TABLE T_RANGIERUNGSMATRIX
  ADD CONSTRAINT FK_RMATRIX_2_HVT
      FOREIGN KEY (HVT_STANDORT_ID_ZIEL)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT)
   
   ;

ALTER TABLE T_RANGIERUNGSMATRIX
  ADD CONSTRAINT FK_RMATRIX_2_PRODUKT
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_VERLAUF_ABTEILUNG
  ADD CONSTRAINT FK_VABT_2_VSTATUS
      FOREIGN KEY (VERLAUF_STATUS_ID)
      REFERENCES T_VERLAUF_STATUS (ID)
   
   ;

ALTER TABLE T_VERLAUF_ABTEILUNG
  ADD CONSTRAINT FK_VABT_2_ABT
      FOREIGN KEY (ABTEILUNG_ID)
      REFERENCES T_ABTEILUNG (ID)
   
   ;

ALTER TABLE T_VERLAUF_ABTEILUNG
  ADD CONSTRAINT FK_VABT_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES T_VERLAUF (ID)
   
   ;

ALTER TABLE T_PHYSIKUEBERNAHME
  ADD CONSTRAINT FK_PU_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID_A)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_PHYSIKUEBERNAHME
  ADD CONSTRAINT FK_PU_2_AUFTRAG_B
      FOREIGN KEY (AUFTRAG_ID_B)
      REFERENCES T_AUFTRAG (ID);

ALTER TABLE T_PHYSIKUEBERNAHME
  ADD CONSTRAINT FK_PHYSIKUEB_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES T_VERLAUF (ID)
   
   ;

ALTER TABLE T_PHYSIKUEBERNAHME
  ADD CONSTRAINT FK_PHYSIKUEB_TYP
      FOREIGN KEY (AENDERUNGSTYP)
      REFERENCES T_PHYSIKAENDERUNGSTYP (ID)
   
   ;

ALTER TABLE T_PROD_2_SL
  ADD CONSTRAINT FK_PRODSL_2_PROD
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_PROD_2_SL
  ADD CONSTRAINT FK_PRODSL_2_SL
      FOREIGN KEY (SL_ID)
      REFERENCES T_STRASSENLISTE (SL_ID)
   
   ;

ALTER TABLE T_PROD_2_SL
  ADD CONSTRAINT FK_PROD_SL_FREI
      FOREIGN KEY (FREIGABE_ID)
      REFERENCES T_PROD_SL_FREIGABE (ID)
   
   ;

ALTER TABLE T_HVT_BES_HIST
  ADD CONSTRAINT FK_HVTBESHIST_2_HVTBEST
      FOREIGN KEY (BEST_ID)
      REFERENCES T_HVT_BESTELLUNG (ID)
   
   ;

ALTER TABLE T_KUBENA_HVT
  ADD CONSTRAINT FK_T_KUBENA_HVT_1
      FOREIGN KEY (KUBENA_ID)
      REFERENCES T_KUBENA (ID);

ALTER TABLE T_KUBENA_HVT
  ADD CONSTRAINT FK_T_KUBENA_HVT_2
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_KUBENA_TDN
  ADD CONSTRAINT FK_T_KUBENA_TDN_1
      FOREIGN KEY (KUBENA_ID)
      REFERENCES T_KUBENA (ID);

ALTER TABLE T_KUBENA_PROD
  ADD CONSTRAINT FK_T_KUBENA_PROD_1
      FOREIGN KEY (KUBENA_ID)
      REFERENCES T_KUBENA (ID);

ALTER TABLE T_KUBENA_PROD
  ADD CONSTRAINT FK_T_KUBENA_PROD_2
      FOREIGN KEY (PROD_ID)
      REFERENCES T_PRODUKT (PROD_ID);

ALTER TABLE T_HVT_STANDORT_2_TECHNIK
  ADD CONSTRAINT FK_ST2T_2_TECHNIK
      FOREIGN KEY (HVT_TECHNIK_ID)
      REFERENCES T_HVT_TECHNIK (ID)
   
   ;

ALTER TABLE T_HVT_STANDORT_2_TECHNIK
  ADD CONSTRAINT FK_ST2T_2_STD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT)
   
   ;

ALTER TABLE T_CARRIER_LBZ
  ADD CONSTRAINT FK_CARRIER_LBZ_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES T_CARRIER (ID)
   
   ;

ALTER TABLE T_PROD_2_PROD
  ADD CONSTRAINT FK_P2P_2_CHAIN
      FOREIGN KEY (CHAIN_ID)
      REFERENCES T_SERVICE_CHAIN (ID)
   
   ;

ALTER TABLE T_PROD_2_PROD
  ADD CONSTRAINT FK_PROD_2_P2P
      FOREIGN KEY (PROD_SRC)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_PROD_2_PROD
  ADD CONSTRAINT FK_PROD_2_P2P_DEST
      FOREIGN KEY (PROD_DEST)
      REFERENCES T_PRODUKT (PROD_ID)
   
   ;

ALTER TABLE T_PROD_2_PROD
  ADD CONSTRAINT FK_P2P_2_AENDTYP
      FOREIGN KEY (PHYSIKAEND_TYP)
      REFERENCES T_TAL_AENDERUNGSTYP (ID)
   
   ;

ALTER TABLE T_SERVICECHAIN_2_COMMAND
  ADD CONSTRAINT FK_SRVCHAIN_2_CHAIN
      FOREIGN KEY (CHAIN_ID)
      REFERENCES T_SERVICE_CHAIN (ID)
   
   ;

ALTER TABLE T_SERVICECHAIN_2_COMMAND
  ADD CONSTRAINT FK_SRVCHAIN_2_COMMAND
      FOREIGN KEY (COMMAND_ID)
      REFERENCES T_SERVICE_COMMANDS (ID)
   
   ;

ALTER TABLE T_PVC_2_PROFIL
  ADD CONSTRAINT FK_PVC2PROFIL_2_PVC
      FOREIGN KEY (PVC_ID)
      REFERENCES T_PVC_VORGABE (ID)
   
   ;

ALTER TABLE T_PVC_2_PROFIL
  ADD CONSTRAINT FK_PVC2PROFIL_2_PROFIL
      FOREIGN KEY (PROFIL_ID)
      REFERENCES T_SDH_PROFIL (ID)
   
   ;

ALTER TABLE T_LEISTUNG_SNAPSHOT
  ADD CONSTRAINT FK_LS_SNAP_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES T_VERLAUF (ID)
   
   ;

ALTER TABLE T_VERLAUF_ACTIONS
  ADD CONSTRAINT FK_VERL_ACTIONS_2_VERLAUF
      FOREIGN KEY (VERLAUF_ID)
      REFERENCES T_VERLAUF (ID)
   
   ;

ALTER TABLE T_AUFTRAG_IMPORT_FILES
  ADD CONSTRAINT FK_T_AUFTRAG_IMPORT_FILES_1
      FOREIGN KEY (AUFTRAG_IMPORT_ID)
      REFERENCES T_AUFTRAG_IMPORT (ID)
   
   ;

ALTER TABLE T_IP_ENDGERAET
  ADD CONSTRAINT FK_T_IP_ENDGERAET_1
      FOREIGN KEY (ID)
      REFERENCES T_AUFTRAG (ID);

ALTER TABLE T_IP_ENDGERAET
  ADD CONSTRAINT FK_IPEG_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID)
   
   ;

ALTER TABLE T_IP_ENDGERAET
  ADD CONSTRAINT FK_IPEG_2_REF
      FOREIGN KEY (TYP)
      REFERENCES T_REFERENCE (ID)
   
   ;

ALTER TABLE T_PORT_FORWARD
  ADD CONSTRAINT FK_PORTFW_2_REF
      FOREIGN KEY (PROTOCOL)
      REFERENCES T_REFERENCE (ID)
   
   ;

ALTER TABLE T_DSLAM
  ADD CONSTRAINT FK_T_DSLAM_1
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT)
   
   ;

ALTER TABLE T_DSLAM
  ADD CONSTRAINT FK_DSLAM_2_HVTTECH
      FOREIGN KEY (HVT_TECHNIK_ID)
      REFERENCES T_HVT_TECHNIK (ID)
   
   ;