--
-- Script fuer Rufnummern-Leistungen
--

-- Rufnummerleistungen neu konfigurieren
delete from T_LB_2_PRODUKT;
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 16929, 40, 'PremiumCall Analog');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 18020, 40, 'PremiumCall Analog ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 250, 202, 'AK-phone KOMFORT');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 10702, 202, 'AK-phone TOP RV1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 10190, 202, 'AK-phone TOP');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 9724, 202, 'AK-phone PREMIUM');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 10703, 502, 'AK-phone PREMIUM');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 2250, 502, 'AK-phone KOMFORT');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 10191, 502, 'AK-phone TOP RV1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 9725, 502, 'AK-phone TOP');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13061, 1248, 'AK-phoneplus EXTRA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13060, 1248, 'AK-phoneplus KOMFORT');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 14876, 1248, 'AK-phoneplus talkflat');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13076, 1248, 'AK-phoneplus PREMIUM');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13077, 1248, 'AK-phoneplus PROFI');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13078, 1248, 'AK-phoneplus TOP');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13260, 1308, 'AK-phoneplus EXTRA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13261, 1308, 'AK-phoneplus KOMFORT');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 14877, 1308, 'AK-phoneplus talkflat');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13262, 1308, 'AK-phoneplus PREMIUM');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13263, 1308, 'AK-phoneplus PROFI');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 13264, 1308, 'AK-phoneplus TOP');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 16981, 41, 'PremiumCall ISDN MSN');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 16982, 41, 'PremiumCall ISDN MSN ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 17379, 41, 'PremiumCall ISDN MSN MS');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 17380, 41, 'PremiumCall ISDN MSN MS ADSL');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 255, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8437, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8417, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 5299, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9555, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9556, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9557, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9558, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9559, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9560, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9561, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9562, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9554, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7385, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7386, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8885, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 5559, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7343, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7344, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10708, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10709, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10710, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10197, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10198, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9734, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9735, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9736, 209, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10196, 209, 'AK-ISDN MSN ');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8418, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 5323, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9563, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9564, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7355, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7356, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 2255, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7967, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7962, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7963, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7964, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7965, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7966, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7961, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 7403, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9575, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9576, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9577, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9565, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9566, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9567, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9568, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9569, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9570, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9571, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9572, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9573, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9574, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8969, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8970, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 8971, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10711, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10712, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10713, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10199, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10200, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 10201, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9737, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9738, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9739, 509, 'AK-ISDN MSN ');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 9804, 509, 'AK-ISDN MSN ');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13556, 1249, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13557, 1249, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 14878, 1249, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13576, 1249, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13577, 1249, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13578, 1249, 'AK-ISDN MSNplus');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13724, 1328, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13736, 1328, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 14879, 1328, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13737, 1328, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13738, 1328, 'AK-ISDN MSNplus');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 13739, 1328, 'AK-ISDN MSNplus');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 259, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8439, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8421, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 5300, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10719, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10720, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9578, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9579, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9580, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9581, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9582, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9583, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9584, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9585, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7387, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7388, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8886, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 5560, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10718, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7347, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7348, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9740, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9741, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9742, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10206, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10207, 211, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10208, 211, 'AK-ISDN TK (S0) DSS1');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 2259, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8422, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 5324, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7970, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7971, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7972, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10721, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10722, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10723, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7404, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9604, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9605, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9606, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9607, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9608, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9609, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9610, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9611, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9612, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9613, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7974, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7973, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7968, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7969, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8972, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8973, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 8974, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7359, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 7360, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9614, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9615, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9616, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9743, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9744, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9764, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10209, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10210, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 10211, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9805, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9617, 511, 'AK-ISDN TK (S0) DSS1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (3, 9618, 511, 'AK-ISDN TK (S0) DSS1');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17423, 30, 'Maxi Analog');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17424, 30, 'Maxi Analog ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17425, 30, 'Maxi Analog AKW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17426, 30, 'Maxi Analog AUEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17427, 30, 'Maxi Analog EVO');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 15723, 30, 'Maxi Analog LEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17463, 30, 'Maxi Analog STAWA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17464, 30, 'Maxi Analog ADSL EVO');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 16783, 30, 'Maxi Analog ADSL LEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17460, 30, 'Maxi Analog ADSL STAWA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17461, 30, 'Maxi Analog ADSL AKW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17462, 30, 'Maxi Analog ADSL AUEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 17648, 100, 'MaxiKomplett Analog ADSL');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 15863, 31, 'Maxi ISDN');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 16784, 31, 'Maxi ISDN ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17428, 31, 'Maxi ISDN AKW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17443, 31, 'Maxi ISDN AUEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17444, 31, 'Maxi ISDN EVO');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17445, 31, 'Maxi ISDN LEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17446, 31, 'Maxi ISDN STAWA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17465, 31, 'Maxi ISDN ADSL AKW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17466, 31, 'Maxi ISDN ADSL AUEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17467, 31, 'Maxi ISDN ADSL EVO');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17468, 31, 'Maxi ISDN ADSL LEW');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17469, 31, 'Maxi ISDN ADSL STAWA');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17709, 101, 'MaxiKomplett ISDN 1000');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17710, 101, 'MaxiKomplett ISDN 2000');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17711, 101, 'MaxiKomplett ISDN 3000');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17712, 101, 'MaxiKomplett ISDN 6000');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 17713, 101, 'MaxiKomplett ISDN 16000');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 253, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 5297, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 5557, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7341, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7342, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7381, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7382, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9484, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9485, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9486, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9487, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9488, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9489, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9490, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9726, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9727, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10192, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10193, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10704, 205, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10705, 205, 'AK-ISDN MSN(S0) 1TR6');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 2253, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 5321, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7353, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7354, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 7401, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 8964, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 8965, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9504, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9505, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9506, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9507, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9508, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9509, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9510, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9730, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 9731, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10194, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10195, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10706, 505, 'AK-ISDN MSN(S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (6, 10707, 505, 'AK-ISDN MSN(S0) 1TR6');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 17091, 43, 'PremiumCall ISDN TK');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 17092, 43, 'PremiumCall ISDN TK ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 17383, 43, 'PremiumCall ISDN TK MS');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 17384, 43, 'PremiumCall ISDN TK MS ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 18266, 43, 'PremiumCall ISDN TK SDSL');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 257, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 5298, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 5558, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7345, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7346, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7383, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7384, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 8438, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 8884, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9524, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9525, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9526, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9527, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9528, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9529, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9530, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9531, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9532, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9728, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9729, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10202, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10203, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10714, 207, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10715, 207, 'AK-ISDN TK (S0) 1TR6');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 261, 214, 'AK-ISDN TK(S2M) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7349, 214, 'AK-ISDN TK(S2M) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7350, 214, 'AK-ISDN TK(S2M) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9765, 214, 'AK-ISDN TK(S2M) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10212, 214, 'AK-ISDN TK(S2M) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10724, 214, 'AK-ISDN TK(S2M) 1TR6');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 2257, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 5322, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7357, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7358, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7402, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 8966, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 8967, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 8968, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9544, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9545, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9546, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9547, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9548, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9549, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9550, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9551, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9552, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9553, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9732, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9733, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10204, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10205, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10716, 507, 'AK-ISDN TK (S0) 1TR6');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10717, 507, 'AK-ISDN TK (S0) 1TR6');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 2261, 514, 'AK-ISDN TK(S2M) 1TR6 KOMFORG');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7361, 514, 'AK-ISDN TK(S2M) 1TR6 EXTRA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 7362, 514, 'AK-ISDN TK(S2M) 1TR6 PROFI');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 9766, 514, 'AK-ISDN TK(S2M) 1TR6 TOP');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10213, 514, 'AK-ISDN TK(S2M) 1TR6 TOP RV1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (7, 10725, 514, 'AK-ISDN TK(S2M) 1TR6 PREMIUM');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 263, 216, 'AK-ISDN TK(S2M) DSS1 KOMFORT');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 7351, 216, 'AK-ISDN TK(S2M) DSS1 EXTRA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 7352, 216, 'AK-ISDN TK(S2M) DSS1 PROFI');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 9767, 216, 'AK-ISDN TK(S2M) DSS1 TOP');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 10214, 216, 'AK-ISDN TK(S2M) DSS1 TOP RV1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 10726, 216, 'AK-ISDN TK(S2M) DSS1 PREMIUM');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 265, 218, 'AK-ISDN PR(S2M) DSS1');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 2263, 516, 'AK-ISDN TK(S2M) DSS1 KOMFORT');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 7363, 516, 'AK-ISDN TK(S2M) DSS1 EXTRA');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 7364, 516, 'AK-ISDN TK(S2M) DSS1 PROFI');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 9768, 516, 'AK-ISDN TK(S2M) DSS1 TOP');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 10215, 516, 'AK-ISDN TK(S2M) DSS1 TOP RV1');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 10727, 516, 'AK-ISDN TK(S2M) DSS1 PREMIUM');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (8, 2265, 518, 'AK-ISDN PR(S2M) DSS1 KOMFORT');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 17037, 42, 'ISDN TK(S0)');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 17038, 42, 'ISDN TK(S0) ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 17381, 42, 'ISDN TK(S0) MS');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 17382, 42, 'ISDN TK(S0) MS ADSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 18263, 42, 'ISDN TK(S0) SDSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 18260, 42, 'PremiumCall ISDN MSN SDSL');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (10, 17142, 44, 'ISDN PMX (S2M)');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (10, 18268, 44, 'ISDN PMX (S2M) SDSL');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (10, 18270, 45, 'PremiumCall PMX SDSL');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (10, 17200, 45, 'PremiumCall PMX SDSL');

-- TODO Konfiguration mit neuen Leistungsnummern fuer die neuen Produkte aufnehmen
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (4, 20271, 2000, 'Maxi Analog');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (5, 20272, 2000, 'Maxi ISDN');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (1, 20223, 2001, 'PremiumCall Analog');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 20225, 2001, 'PremiumCall ISDN');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 20227, 2001, 'PremiumCall ISDN MS');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 20230, 2001, 'PremiumCall TK');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 20232, 2001, 'PremiumCall TK MS');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (10, 20235, 2001, 'PremiumCall PMX');

insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (9, 20881, 2001, 'PremiumCall TK MS');
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION) VALUES (2, 20901, 41, 'PremiumCall ISDN MSN MS');




-- Primary Key muss neu gesetzt werden!
alter table T_LB_2_PRODUKT add primary key (LB_ID, LEISTUNG__NO);



