-- DSLAM Profiles fuer KVZ anlegen
-- Baugruppentyp: NVLT-H
Insert into T_DSLAM_PROFILE
   (ID, NAME, BEMERKUNG, DOWNSTREAM, UPSTREAM,
    FASTPATH, UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, FASTPATH_TECH_LS,
    GUELTIG, VERSION, TM_DOWN, TM_UP, ADSL1FORCE,
    BAUGRUPPEN_TYP, DOWNSTREAM_NETTO, UPSTREAM_NETTO, L2POWER)
 Values
   (S_T_DSLAM_PROFILE_0.nextVal, 'MD_25000_2500_H', NULL, '25000', '2500',
    '0', NULL, 23, 114, NULL,
    '1', 0, NULL, NULL, '0',
    (select ID as BAUGRUPPEN_TYP_ID from T_HW_BAUGRUPPEN_TYP where NAME='NVLT-H'), NULL, NULL, NULL);
Insert into T_DSLAM_PROFILE
   (ID, NAME, BEMERKUNG, DOWNSTREAM, UPSTREAM,
    FASTPATH, UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, FASTPATH_TECH_LS,
    GUELTIG, VERSION, TM_DOWN, TM_UP, ADSL1FORCE,
    BAUGRUPPEN_TYP, DOWNSTREAM_NETTO, UPSTREAM_NETTO, L2POWER)
 Values
   (S_T_DSLAM_PROFILE_0.nextVal, 'MD_50000_5000_H', NULL, '50000', '5000',
    '0', NULL, 24, 27, NULL,
    '1', 0, NULL, NULL, '0',
    (select ID as BAUGRUPPEN_TYP_ID from T_HW_BAUGRUPPEN_TYP where NAME='NVLT-H'), NULL, NULL, NULL);


-- Baugruppentyp: FttX
Insert into T_DSLAM_PROFILE
   (ID, NAME, BEMERKUNG, DOWNSTREAM, UPSTREAM,
    FASTPATH, UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, FASTPATH_TECH_LS,
    GUELTIG, VERSION, TM_DOWN, TM_UP, ADSL1FORCE,
    BAUGRUPPEN_TYP, DOWNSTREAM_NETTO, UPSTREAM_NETTO, L2POWER)
 Values
   (S_T_DSLAM_PROFILE_0.nextVal, 'MD_25000_2500_H', NULL, '25000', '2500',
    '0', NULL, 23, 114, NULL,
    '1', 0, NULL, NULL, '0',
    (select ID as BAUGRUPPEN_TYP_ID from T_HW_BAUGRUPPEN_TYP where NAME='MDU'), NULL, NULL, NULL);
Insert into T_DSLAM_PROFILE
   (ID, NAME, BEMERKUNG, DOWNSTREAM, UPSTREAM,
    FASTPATH, UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, FASTPATH_TECH_LS,
    GUELTIG, VERSION, TM_DOWN, TM_UP, ADSL1FORCE,
    BAUGRUPPEN_TYP, DOWNSTREAM_NETTO, UPSTREAM_NETTO, L2POWER)
 Values
   (S_T_DSLAM_PROFILE_0.nextVal, 'MD_50000_5000_H', NULL, '50000', '5000',
    '0', NULL, 24, 27, NULL,
    '1', 0, NULL, NULL, '0',
    (select ID as BAUGRUPPEN_TYP_ID from T_HW_BAUGRUPPEN_TYP where NAME='MDU'), NULL, NULL, NULL);
Insert into T_DSLAM_PROFILE
   (ID, NAME, BEMERKUNG, DOWNSTREAM, UPSTREAM,
    FASTPATH, UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, FASTPATH_TECH_LS,
    GUELTIG, VERSION, TM_DOWN, TM_UP, ADSL1FORCE,
    BAUGRUPPEN_TYP, DOWNSTREAM_NETTO, UPSTREAM_NETTO, L2POWER)
 Values
   (S_T_DSLAM_PROFILE_0.nextVal, 'MD_100000_10000_H', NULL, '100000', '10000',
    '0', NULL, 25, 28, NULL,
    '1', 0, NULL, NULL, '0',
    (select ID as BAUGRUPPEN_TYP_ID from T_HW_BAUGRUPPEN_TYP where NAME='MDU'), NULL, NULL, NULL);


