-- Generischer Router fuer Router aus der Monline
INSERT INTO T_EG (
   ID, INTERNE__ID, NAME,
   BESCHREIBUNG, LS_TEXT, EXT_LEISTUNG__NO,
   VERFUEGBAR_VON, VERFUEGBAR_BIS, GARANTIEZEIT,
   PRODUKTCODE, CONFIGURABLE, CONF_PORTFORWARDING,
   CONF_S0BACKUP, TYPE)
VALUES (176, 176, 'Router',
    'Router', null, null,
    to_date('01.01.2000', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'), null,
    null, 1, 1,
    null, 4);

-- SDSL und DirectAcces
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,460,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,313,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,312,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,305,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,304,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,303,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,302,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,99,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,69,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,68,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,67,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,66,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,65,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,64,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,63,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,62,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,61,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,60,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,54,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,53,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,52,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,51,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,38,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,37,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,18,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,17,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,16,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,12,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,11,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,455,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,444,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,470,176,0,1,0);
INSERT INTO T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES (S_T_PROD_2_EG_0.nextval,400,176,0,1,0);
