ALTER TABLE T_AUFTRAG_HOUSING ADD ELECTRIC_COUNTER_NUMBER VARCHAR2(20);
ALTER TABLE T_AUFTRAG_HOUSING ADD ELECTRIC_COUNTER_NUMBER_2 VARCHAR2(20);
ALTER TABLE T_AUFTRAG_HOUSING ADD ELECTRIC_COUNTER_NUMBER_3 VARCHAR2(20);
ALTER TABLE T_AUFTRAG_HOUSING ADD ELECTRIC_COUNTER_NUMBER_4 VARCHAR2(20);
