-- Zusatz-Tabelle fuer Schlüssel-Daten

create table T_AUFTRAG_HOUSING_KEY (
    ID NUMBER(10) NOT NULL
  , AUFTRAG_ID NUMBER(10) NOT NULL
  , AUFTRAG_HOUSING_ID NUMBER(10) NOT NULL
  , TRANSPONDER_ID NUMBER(10) NOT NULL
  , CUSTOMER_FIRSTNAME VARCHAR(30)
  , CUSTOMER_LASTNAME VARCHAR(30)
  , GUELTIG_VON DATE NOT NULL
  , GUELTIG_BIS DATE NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_AUFTRAG_HOUSING_KEY ADD CONSTRAINT PK_T_AUFTRAG_HOUSING_KEY PRIMARY KEY (ID);
ALTER TABLE T_AUFTRAG_HOUSING_KEY ADD CONSTRAINT FK_T_AUFTRAG_HOUSING_2_KEY FOREIGN KEY (AUFTRAG_HOUSING_ID) REFERENCES T_AUFTRAG_HOUSING (ID);
ALTER TABLE T_AUFTRAG_HOUSING_KEY ADD CONSTRAINT FK_T_AUFTRAG_2_KEY FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

CREATE INDEX IX_FK_KEY_2_HOUSING ON T_AUFTRAG_HOUSING_KEY (AUFTRAG_HOUSING_ID) TABLESPACE "I_HURRICAN";
CREATE INDEX IX_FK_KEY_2_AUFTRAG ON T_AUFTRAG_HOUSING_KEY (AUFTRAG_ID) TABLESPACE "I_HURRICAN";

create SEQUENCE S_T_AUFTRAG_HOUSING_KEY_0 start with 1;
grant select on S_T_AUFTRAG_HOUSING_KEY_0 to public;

GRANT SELECT ON T_AUFTRAG_HOUSING_KEY TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_AUFTRAG_HOUSING_KEY TO R_HURRICAN_USER;
