-- Produktgruppe anlegen
INSERT INTO T_PRODUKTGRUPPE (ID, PRODUKTGRUPPE, AM_RESPONSIBILITY) VALUES (31, 'FTTC-Ausbau', 1200);

-- Produkt anlegen
Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, ANSCHLUSSART, PROD_NAME_PATTERN, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
   BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
   BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP,
   ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
   CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
   VERTEILUNG_DURCH, BA_RUECKLAEUFER, VERLAUF_CHAIN_ID,
   VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
   CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
   TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, VIER_DRAHT, VERSION, MIN_DN_COUNT, CPS_IP_DEFAULT, CPS_MULTI_DRAHT)
 Values
   (560, 31, 'FTTC-Ausbau', null, 0, 0, null, null,
    '0', TO_DATE('05/06/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '0',
    '0', '1', '0', 0,
    null, null, '0', '0', '0',
    '0', '0', '0', '0', '0',
    11, '1', 28,
    28, '1', '0', '0', null,
    null, null, null, null, null,
    null, null, null, 0, 0, null, '0');

-- Produktmapping
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values (1150, 560, 560, ' ', 0);
