UPDATE T_TECH_LEISTUNG
    SET EXTERN_LEISTUNG__NO = 20015
    WHERE ID = 300;

UPDATE T_TECH_LEISTUNG
    SET EXTERN_LEISTUNG__NO = 20016
    WHERE ID = 301;

UPDATE T_TECH_LEISTUNG
    SET EXTERN_LEISTUNG__NO = 20017
    WHERE ID = 302;