-- default flag der VOIP_ADD Leistung 'Endgeraeteport' entfernen
UPDATE T_PROD_2_TECH_LEISTUNG SET IS_DEFAULT = '0' WHERE TECH_LS_ID = 299;

-- Leistung 'VOIP_MGA' auf FTTX GK Produkte konfigurieren
INSERT INTO T_PROD_2_TECH_LEISTUNG
        (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES
        (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 300, NULL, '0' );
INSERT INTO T_PROD_2_TECH_LEISTUNG
        (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES
        (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 300, NULL, '0' );

-- Leistung 'VOIP_TK' auf FTTX GK Produkte konfigurieren
INSERT INTO T_PROD_2_TECH_LEISTUNG
        (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES
        (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 301, NULL, '0' );
INSERT INTO T_PROD_2_TECH_LEISTUNG
        (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES
        (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 301, NULL, '0' );

-- Leistung 'VOIP_PMX' auf FTTX GK Produkte konfigurieren
INSERT INTO T_PROD_2_TECH_LEISTUNG
        (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES
        (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 302, NULL, '0' );
INSERT INTO T_PROD_2_TECH_LEISTUNG
        (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES
        (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 541, 302, NULL, '0' );
