ALTER TABLE T_USER_TASK ADD (TV_60_SENT  CHAR(1));
update T_USER_TASK set TV_60_SENT = 0 where VORGANG_TYP = 'TAM';
update T_USER_TASK set TV_60_SENT = 1 where VORGANG_TYP = 'TAM' and TAM_BEARBEITUNG_STATUS = 'TV_60_TAGE';

