alter table T_PROD_2_CVLAN add TECH_LOCATION_TYPE_REF_ID decimal(10);
CREATE INDEX IX_FK_PROD2CVLAN_2_REF ON T_PROD_2_CVLAN (TECH_LOCATION_TYPE_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PROD_2_CVLAN ADD CONSTRAINT FK_PROD2CVLAN_2_REF
  FOREIGN KEY (TECH_LOCATION_TYPE_REF_ID) REFERENCES T_REFERENCE (ID);

alter table T_PROD_2_CVLAN add HVT_TECHNIK_ID decimal(10);
CREATE INDEX IX_FK_PROD2CVLAN_2_TECHNIK ON T_PROD_2_CVLAN (HVT_TECHNIK_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PROD_2_CVLAN ADD CONSTRAINT IX_FK_PROD2CVLAN_2_TECHNIK
  FOREIGN KEY (HVT_TECHNIK_ID) REFERENCES T_HVT_TECHNIK (ID);

alter table T_PROD_2_CVLAN drop unique (PROD_ID, CVLAN_TYP) drop index;
alter table T_PROD_2_CVLAN add constraint UK_PROD2CVLAN unique(PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID);

-- CVLANs fuer Retail Produkte (TechLocationTypeRefId: FTTH 11011, FTTB 11002  HvtTechnikId: HUAWEI 2, ALCATEL 6)

-- (FTTX Telefon || Maxi Deluxe Fon) & FTTB => kein VLAN

-- (FTTX Telefon=511 || Maxi Deluxe Fon=501) & FTTH & Hersteller = 'Alcatel' => POTS
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 501, 'POTS', 11011, 6, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 511, 'POTS', 11011, 6, '1');
-- (FTTX Telefon || Maxi Deluxe Fon) & FTTH & Hersteller = 'Huawei'=> VOIP
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 501, 'VOIP', 11011, 2, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 511, 'VOIP', 11011, 2, '1');

-- (FTTX DSL=512 || Maxi Deluxe Pur=502 ) => HSI + IAD
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 502, 'HSI', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 502, 'IAD', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 512, 'HSI', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 512, 'IAD', null, null, '1');

-- (FTTX DSL + Fon=513 || Maxi Deluxe Komplett=503 ) => HSI + IAD + VOIP
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 503, 'HSI', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 503, 'IAD', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 503, 'VOIP', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 513, 'HSI', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 513, 'IAD', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 513, 'VOIP', null, null, '1');

-- Glasfaser SDSL=541 => HSIPLUS + IAD
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 541, 'HSIPLUS', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 541, 'IAD', null, null, '1');

-- Premium Glasfaser-DSL Doppel-Flat=540 => HSIPLUS + IAD + VOIP
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 540, 'HSIPLUS', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 540, 'IAD', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 540, 'VOIP', null, null, '1');

-- Maxi FTTH Wohnheim=570 => HSI + IAD
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 570, 'HSIPLUS', null, null, '1');
insert into T_PROD_2_CVLAN (ID, VERSION, PROD_ID, CVLAN_TYP, TECH_LOCATION_TYPE_REF_ID, HVT_TECHNIK_ID, IS_MANDATORY)
  values (S_T_PROD_2_CVLAN_0.nextVal, 0, 570, 'IAD', null, null, '1');
