--
-- Aufbau der neuen Tabellen fuer die IPSec Site-to-Site Daten
--

CREATE TABLE T_IPSEC_S2S (
       ID NUMBER(10) NOT NULL
     , AUFTRAG_ID NUMBER(10) NOT NULL
     , WAN_GATEWAY VARCHAR2(40)
     , LOOPBACK_IP VARCHAR2(40)
     , VIRTUAL_LAN_IP VARCHAR2(40)
     , VIRTUAL_LAN_SUBMASK VARCHAR2(40)
     , VIRTUAL_WAN_IP VARCHAR2(40)
     , HOSTNAME VARCHAR2(40)
     , ISDN_BU CHAR(1)
     , ISDN_DIALIN_NUMBER VARCHAR2(20)
     , SPLIT_TUNNEL CHAR(1)
     , DESCRIPTION VARCHAR2(255)
     , ACCESS_CARRIER VARCHAR2(50)
     , ACCESS_BANDWIDTH VARCHAR2(50)
     , ACCESS_TYPE VARCHAR2(50)
     , ACCESS_AUFTRAG_ID NUMBER(10)
     , HAS_PRESHARED_KEY CHAR(1)
     , HAS_CERTIFICATE CHAR(1)
     , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_IPSEC_S2S
  ADD CONSTRAINT PK_T_IPSEC_S2S
      PRIMARY KEY (ID);

ALTER TABLE T_IPSEC_S2S ADD CONSTRAINT UK_T_IPSEC_S2S UNIQUE (AUFTRAG_ID);

ALTER TABLE T_IPSEC_S2S
  ADD CONSTRAINT FK_IPSECS2S_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID);

CREATE SEQUENCE S_T_IPSEC_S2S_0 start with 1;
grant select on S_T_IPSEC_S2S_0 to public;


CREATE TABLE T_IPSEC_S2S_LAN (
    ID NUMBER(10) NOT NULL
  , IPSEC_ID NUMBER(10)
  , LAN VARCHAR2(40) NOT NULL
  , SUBMASK VARCHAR2(40)
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);
ALTER TABLE T_IPSEC_S2S_LAN
  ADD CONSTRAINT PK_T_IPSEC_S2S_LAN
      PRIMARY KEY (ID);
ALTER TABLE T_IPSEC_S2S_LAN
  ADD CONSTRAINT FK_IPSECS2SLAN_2_IPSEC
      FOREIGN KEY (IPSEC_ID)
      REFERENCES T_IPSEC_S2S (ID);
CREATE SEQUENCE S_T_IPSEC_S2S_LAN_0 start with 1;
grant select on S_T_IPSEC_S2S_LAN_0 to public;


grant select on T_IPSEC_S2S to R_HURRICAN_READ_ONLY;
grant select on T_IPSEC_S2S_LAN to R_HURRICAN_READ_ONLY;
grant select, insert, update on T_IPSEC_S2S to R_HURRICAN_USER;
grant select, insert, update on T_IPSEC_S2S_LAN to R_HURRICAN_USER;
