MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  8 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  10 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  9 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  8 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  22 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  24 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  35 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  38 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  40 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  42 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  63 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

MERGE INTO T_BRAS_POOLS A USING
 (SELECT
  90 as "VP",
  'ac2-hr1-lanal052' as "NAS_IDENTIFIER",
  8 as "SLOT",
  0 as "PORT",
  'ac2-a91f-bri018' as "BACKUP_NAS_IDENTIFIER",
  9 as "BACKUP_SLOT",
  0 as "BACKUP_PORT"
  FROM DUAL) B
ON (A.VP = B.VP)
WHEN NOT MATCHED THEN
INSERT (
  VP, NAS_IDENTIFIER, SLOT, PORT, BACKUP_NAS_IDENTIFIER,
  BACKUP_SLOT, BACKUP_PORT)
VALUES (
  B.VP, B.NAS_IDENTIFIER, B.SLOT, B.PORT, B.BACKUP_NAS_IDENTIFIER,
  B.BACKUP_SLOT, B.BACKUP_PORT)
WHEN MATCHED THEN
UPDATE SET
  A.NAS_IDENTIFIER = B.NAS_IDENTIFIER,
  A.SLOT = B.SLOT,
  A.PORT = B.PORT,
  A.BACKUP_NAS_IDENTIFIER = B.BACKUP_NAS_IDENTIFIER,
  A.BACKUP_SLOT = B.BACKUP_SLOT,
  A.BACKUP_PORT = B.BACKUP_PORT;

