--
-- SQL-Script, nachdem die Authentication auf Oracle uebertragen wurde.
--

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)
/
ALTER TABLE ACCOUNT ADD CONSTRAINT UK_ACCOUNT_NAME UNIQUE (ACC_NAME)
/
CREATE INDEX APP_ID
	ON ACCOUNT (APP_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE APPLICATION ADD CONSTRAINT PK_APPLICATION PRIMARY KEY (ID)
/
ALTER TABLE APPLICATION ADD CONSTRAINT UK_APPLICATION_NAME UNIQUE (NAME)
/
ALTER TABLE COMPBEHAVIOR ADD CONSTRAINT PK_COMPBEHAVIOR PRIMARY KEY (ID)
/
ALTER TABLE COMPBEHAVIOR ADD CONSTRAINT UK_COMPBEHAVIOR UNIQUE (COMP_ID, ROLE_ID)
/
CREATE INDEX ROLE_ID
	ON COMPBEHAVIOR (ROLE_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX COMP_ID
	ON COMPBEHAVIOR (COMP_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE DB ADD CONSTRAINT PK_DB PRIMARY KEY (ID)
/
ALTER TABLE DB ADD CONSTRAINT UK_DB_NAME UNIQUE (NAME)
/
ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)
/
ALTER TABLE DEPARTMENT ADD CONSTRAINT UK_DEPARTMENT_NAME UNIQUE (NAME)
/
ALTER TABLE GUICOMPONENT ADD CONSTRAINT PK_GUICOMPONENT PRIMARY KEY (ID)
/
ALTER TABLE GUICOMPONENT ADD CONSTRAINT UK_GUICOMPONENT UNIQUE (NAME, PARENT, APP_ID)
/
CREATE INDEX GUICOMP_APP_ID
	ON GUICOMPONENT (APP_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE PWHISTORY ADD CONSTRAINT PK_PWHISTORY PRIMARY KEY (ID)
/
CREATE INDEX USER_ID
	ON PWHISTORY (USER_ID) TABLESPACE "I_HURRICAN"
/
ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID)
/
ALTER TABLE ROLE ADD CONSTRAINT UK_ROLE UNIQUE (NAME, APP_ID)
/
CREATE INDEX ROLE_APP_ID
	ON ROLE (APP_ID) TABLESPACE "I_HURRICAN"
/

ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (ID)
/
ALTER TABLE USERS ADD CONSTRAINT UK_USER_LOGINNAME UNIQUE (LOGINNAME)
/
CREATE INDEX IX_USER_DEP
	ON USERS (DEP_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX IX_USER_PW
	ON USERS (PASSWORD) TABLESPACE "I_HURRICAN"
/
ALTER TABLE USERACCOUNT ADD CONSTRAINT PK_USERACCOUNT PRIMARY KEY (ID)
/
ALTER TABLE USERACCOUNT ADD CONSTRAINT UK_USERACCOUNT_USERACC UNIQUE (USER_ID, ACCOUNT_ID)
/
ALTER TABLE USERACCOUNT ADD CONSTRAINT UK_USERACCOUNT_USERDB UNIQUE (USER_ID, DB_ID)
/
CREATE INDEX ACCOUNT_ID
	ON USERACCOUNT (ACCOUNT_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX UACC_USER_ID
	ON USERACCOUNT (USER_ID) TABLESPACE "I_HURRICAN"
/

CREATE INDEX DB_ID
	ON USERACCOUNT (DB_ID) TABLESPACE "I_HURRICAN"
/

ALTER TABLE USERROLE ADD CONSTRAINT PK_USERROLE PRIMARY KEY (ID)
/
ALTER TABLE USERROLE ADD CONSTRAINT UK_USERROLE UNIQUE (USER_ID, ROLE_ID)
/

CREATE INDEX UR_USER_ID
	ON USERROLE (USER_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX UR_ROLE_ID
	ON USERROLE (ROLE_ID) TABLESPACE "I_HURRICAN"
/

ALTER TABLE USERSESSION ADD CONSTRAINT PK_USERSESSION PRIMARY KEY (SESSION_ID)
/
CREATE INDEX US_USER_ID
	ON USERSESSION (USER_ID) TABLESPACE "I_HURRICAN"
/
CREATE INDEX US_APP_ID
	ON USERSESSION (APP_ID) TABLESPACE "I_HURRICAN"
/


ALTER TABLE ROLE
  ADD CONSTRAINT FK_ROLE_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE ACCOUNT
  ADD CONSTRAINT FK_DBACCOUNT_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE ACCOUNT
  ADD CONSTRAINT FK_DBACCOUNT_TO_DB
      FOREIGN KEY (DB_ID)
      REFERENCES DB (ID);

ALTER TABLE GUICOMPONENT
  ADD CONSTRAINT FK_GUICOMPONENT_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE USERS
  ADD CONSTRAINT FK_USER_TO_DEPART
      FOREIGN KEY (DEP_ID)
      REFERENCES DEPARTMENT (ID);

ALTER TABLE USERSESSION
  ADD CONSTRAINT FK_USERSESSION_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERSESSION
  ADD CONSTRAINT FK_USERSESSION_TO_APP
      FOREIGN KEY (APP_ID)
      REFERENCES APPLICATION (ID);

ALTER TABLE PWHISTORY
  ADD CONSTRAINT FK_PWHISTORY_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERACCOUNT
  ADD CONSTRAINT FK_USERACCOUNT_TO_ACC
      FOREIGN KEY (ACCOUNT_ID)
      REFERENCES ACCOUNT (ID);

ALTER TABLE USERACCOUNT
  ADD CONSTRAINT FK_USERACCOUNT_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERACCOUNT
  ADD CONSTRAINT FK_USERACC_2_DB
      FOREIGN KEY (DB_ID)
      REFERENCES DB (ID);

ALTER TABLE COMPBEHAVIOR
  ADD CONSTRAINT FK_COMPBEHAVIOR_TO_ROLE
      FOREIGN KEY (ROLE_ID)
      REFERENCES ROLE (ID);

ALTER TABLE COMPBEHAVIOR
  ADD CONSTRAINT FK_COMPBEHAVIOR_TO_COMP
      FOREIGN KEY (COMP_ID)
      REFERENCES GUICOMPONENT (ID);

ALTER TABLE USERROLE
  ADD CONSTRAINT FK_UR_TO_USER
      FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID);

ALTER TABLE USERROLE
  ADD CONSTRAINT FK_UR_TO_ROLE
      FOREIGN KEY (ROLE_ID)
      REFERENCES ROLE (ID);

--
-- Sequences erstellen
--

delete from usersession;
commit;   

select max(ID)+1 from USERS;
create sequence S_USERS_0 start with ?;
grant select on S_USERS_0 to public;

select max(ID)+1 from GUICOMPONENT;
create sequence S_GUICOMPONENT_0 start with ?;
grant select on S_GUICOMPONENT_0 to public;

select max(ID)+1 from DEPARTMENT;
create sequence S_DEPARTMENT_0 start with ?;
grant select on S_DEPARTMENT_0 to public;

commit;

-- 
-- DB Definition und Benutzer anpassen
--
update DB set DRIVER='oracle.jdbc.driver.OracleDriver', 
  URL='jdbc:oracle:thin:@mnetdbsvr17.m-net.de:1521:HCPROD01', 
  SCHEMA='HURRICAN', HIBERNATE_DIALECT='net.sf.hibernate.dialect.Oracle9Dialect', 
  FALLBACK_DRIVER=null, FALLBACK_URL=null, FALLBACK_SCHEMA=null, FALLBACK_HIBERNATE_DIALECT=null
  where NAME='cc';

update DB set DRIVER='oracle.jdbc.driver.OracleDriver', 
  URL='jdbc:oracle:thin:@mnetdbsvr17.m-net.de:1521:HCPROD01', 
  SCHEMA='SCHEDULER', HIBERNATE_DIALECT='net.sf.hibernate.dialect.Oracle9Dialect',
  DESCRIPTION='Definition der Scheduler-DB'
  where NAME='scheduler';

update DB set DRIVER='oracle.jdbc.driver.OracleDriver', 
  URL='jdbc:oracle:thin:@mnetdbsvr17.m-net.de:1521:HCPROD01', 
  SCHEMA='HURRICAN', HIBERNATE_DIALECT='net.sf.hibernate.dialect.Oracle9Dialect',
  DESCRIPTION='Definition der Report-DB',
  FALLBACK_DRIVER=null, FALLBACK_URL=null, FALLBACK_SCHEMA=null, FALLBACK_HIBERNATE_DIALECT=null
  where NAME='reporting';

update db set url='jdbc:oracle:thin:@192.168.229.19:1521:MNETPROD' where id=3;

commit;

update ACCOUNT set ACCOUNTUSER='HURRICANWRITER', ACCOUNTPASSWORD='dyMRupr3P1Nl1OkoxnPWiQ==' where ACC_NAME='cc.writer';
update ACCOUNT set ACCOUNTUSER='HURRICANREADER', ACCOUNTPASSWORD='dyMRupr3P1Nl1OkoxnPWiQ==' where ACC_NAME='cc.reader';
update ACCOUNT set ACCOUNTUSER='SCHEDULER' where ACC_NAME='scheduler.writer';
update ACCOUNT set ACCOUNTUSER='HURRICANWRITER', ACCOUNTPASSWORD='dyMRupr3P1Nl1OkoxnPWiQ==' where ACC_NAME='scheduler.cc.writer';
update ACCOUNT set ACCOUNTUSER='REPORTUSER' where ACC_NAME='report.server';
update ACCOUNT set ACCOUNTUSER='REPORTUSER' where ACC_NAME='report.user';
update ACCOUNT set ACCOUNTUSER='REPORTADMIN' where ACC_NAME='report.admin';
update ACCOUNT set ACCOUNTUSER='HURRICANWRITER' where ACC_NAME='reporting.cc.writer';
update ACCOUNT set ACCOUNTUSER='REPORTADMIN' where ACC_NAME='scheduler.report.admin';

commit;


create trigger TRD_DELETE_USER
  before delete on users for each row
begin
    delete from usersession where user_id = :old.id;
    delete from userrole where user_id = :old.id;
    delete from useraccount where user_id = :old.id;
    delete from pwhistory where user_id = :old.id;
end t_delete_user;
/

commit;


