-- ANF-217.01 neuer HVT Standorttyp (FTTB_H)
INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE, UNIT_ID, GUI_VISIBLE, DESCRIPTION, VERSION, CHANGED_AT, WBCI_CODE)
VALUES
  (11017, 'STANDORT_TYP', 'FTTB_H', 11102, '1',
   'Standort-Typ FTTB/FTTH (1-3WE kann mit ONTS und/oder DPOs versorgt werden)', 0, SYSDATE, '019 GF');

