-- ANF-217.01 Neuer RackTyp
CREATE TABLE T_HW_RACK_DPO (
  RACK_ID NUMBER(19) PRIMARY KEY NOT NULL,
  OLT_RACK_ID NUMBER(19) NOT NULL,
  SERIAL_NO varchar2(50),
  OLT_FRAME varchar2(2) NOT NULL,
  OLT_SHELF varchar2(2) NOT NULL,
  OLT_GPON_PORT varchar2(2) NOT NULL,
  OLT_GPON_ID varchar2(3) NOT NULL,
  OLT_SUBRACK varchar2(2),
  FREIGABE timestamp,
  DPO_TYPE varchar2(10) NOT NULL,
  VERSION decimal(18) DEFAULT 0  NOT NULL
);

ALTER TABLE T_HW_RACK_DPO ADD CONSTRAINT FK_HWRACKDPO_2_HWRACK FOREIGN KEY (RACK_ID) REFERENCES T_HW_RACK (ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK_DPO TO R_HURRICAN_HW_ADMIN;
GRANT SELECT ON T_HW_RACK_DPO TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_HW_RACK_DPO TO R_HURRICAN_TECHNIKMUC;

-- ID 9510 ff. sind bereits belegt
INSERT INTO T_REFERENCE (ID,TYPE,STR_VALUE,INT_VALUE,FLOAT_VALUE,UNIT_ID,GUI_VISIBLE,ORDER_NO,DESCRIPTION,VERSION)
VALUES (9600,'HW_RACK_TYPE','DPO',null,null,null,'1',100,'HW-Rack Typ DPO.',0);

