ALTER TABLE T_HW_RACK DROP CONSTRAINT CK_HW_RACK_TYP;
ALTER TABLE T_HW_RACK ADD CONSTRAINT CK_HW_RACK_TYP CHECK (RACK_TYP IN
                                                           ('DSLAM', 'DLU', 'ROUTER', 'LTG', 'UEVT', 'MDU', 'OLT', 'PDH', 'SDH', 'ONT', 'DPO')) ENABLE NOVALIDATE;
