-- TV Signallieferung MV
insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN,
   LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
   GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
   BRAUCHT_BUENDEL, ELVERLAUF, ENDSTELLEN_TYP, BESCHREIBUNG,
   ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
   CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
   EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID,
   VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
   CPS_PROD_NAME, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
   TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER, VIER_DRAHT, VERSION,
   MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN, CPS_IP_DEFAULT, CPS_MULTI_DRAHT,IP_POOL, IP_PURPOSE_V4, IP_PURPOSE_V4_EDITABLE,
   IP_NETMASK_SIZE_V4, IP_NETMASK_SIZE_V6, IP_NETMASK_SIZE_EDITABLE, AUTOMATION_POSSIBLE,
   SWITCH, GEOID_SRC, SDSL_N_DRAHT, AUTO_HVT_ZUORDNUNG, SMS_VERSAND)
 values
   (522, 20, '', 'TV Signallieferung MV', '',
    2, 2, 0, '0', NULL,
    TO_DATE('01/11/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1',
    '1', '0', 1, '',
    '', NULL, '0', '0', '0',
    '0', '0', '0', '1', '1',
    '', null, null, NULL, null,
   null, null, '0', '0', null,
    null, null, null, null,
    'M', 'S', null, '0', 0,
    0, null, '0', '0', null, null, '0',
    null, null, '0','0',
    null, 'HVT', null, '1','0');
