ALTER TABLE T_PRODUKT ADD (ERSTELL_STATUS_ID NUMBER(19) NULL);
ALTER TABLE T_PRODUKT ADD CONSTRAINT FK_PRODUKT_AUFTRAG_ERST_STATUS FOREIGN KEY (ERSTELL_STATUS_ID) REFERENCES T_AUFTRAG_STATUS (ID);

ALTER TABLE T_PRODUKT ADD (KUENDIGUNG_STATUS_ID NUMBER(19) NULL);
ALTER TABLE T_PRODUKT ADD CONSTRAINT FK_PRODUKT_AUFTRAG_KUEN_STATUS FOREIGN KEY (KUENDIGUNG_STATUS_ID) REFERENCES T_AUFTRAG_STATUS (ID);
