-- ANF-217.01 neue Physiktyp für DPO VDSL Port erstellen
Insert into T_PHYSIKTYP
   (ID, NAME, BESCHREIBUNG, HVT_TECHNIK_ID, HW_SCHNITTSTELLE,
    PT_GROUP, CPS_TRANSFER_METHOD, VERSION, MAX_BANDWIDTH_DOWNSTREAM, MAX_BANDWIDTH_UPSTREAM)
 Values
   (809, 'FTTB_DPO_VDSL2', 'FTTB DPO VDSL2 Breitband Versorgung', NULL, 'VDSL2',
    4, NULL, 0, 150000, 50000);
