Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 540, 72, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 540, 27, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 540, 43, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');



Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 511, 72, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 511, 27, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 511, 43, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');



Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 512, 72, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 512, 27, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 512, 43, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');



Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 513, 72, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 513, 27, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP,
    FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 513, 43, 11017,
    'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');


INSERT INTO T_FFM_QUALIFICATION (ID, FFM_PRODUCT_MAPPING_ID, FFM_QUALIFICATION)
  SELECT
    S_T_FFM_QUALIFICATION_0.nextVal,
    ffm.ID,
    'Endkundenservice FTTB_H'
  FROM T_FFM_PRODUCT_MAPPING ffm
    WHERE ffm.STANDORT_TYP = 11017;

