-- Physiktypzuordnung FTTX Telefon -> FTTC_VDSL2
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, USE_IN_RANG_MATRIX, VERSION)
 Values
   (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 511, 804, NULL, '0', NULL, 1, 0);
