alter table T_ABTEILUNG add VALID_FOR_UNIVERSAL_GUI CHAR(1) default '0';
update T_ABTEILUNG set VALID_FOR_UNIVERSAL_GUI='0';
alter table T_ABTEILUNG modify VALID_FOR_UNIVERSAL_GUI NOT NULL;


Insert into T_ABTEILUNG (ID, TEXT, NIEDERLASSUNG_ID, RELEVANT_4_PROJ, RELEVANT_4_BA, VALID_FOR_UNIVERSAL_GUI, VERSION)
 Values (15, 'ZP Zentrale Infrastruktur', 3, '1', '1', '1', 0);
Insert into T_ABTEILUNG (ID, TEXT, NIEDERLASSUNG_ID, RELEVANT_4_PROJ, RELEVANT_4_BA, VALID_FOR_UNIVERSAL_GUI, VERSION)
 Values (16, 'ZP Technikcenter', 3, '1', '1', '1', 0);
Insert into T_ABTEILUNG (ID, TEXT, NIEDERLASSUNG_ID, RELEVANT_4_PROJ, RELEVANT_4_BA, VALID_FOR_UNIVERSAL_GUI, VERSION)
 Values (17, 'ZP Zentrale IP-Systeme', 3, '1', '1', '1', 0);
Insert into T_ABTEILUNG (ID, TEXT, NIEDERLASSUNG_ID, RELEVANT_4_PROJ, RELEVANT_4_BA, VALID_FOR_UNIVERSAL_GUI, VERSION)
 Values (18, 'ZP Technologie', 3, '1', '1', '1', 0);
Insert into T_ABTEILUNG (ID, TEXT, NIEDERLASSUNG_ID, RELEVANT_4_PROJ, RELEVANT_4_BA, VALID_FOR_UNIVERSAL_GUI, VERSION)
 Values (19, 'ZP Ressourcen und Dokumentation', 3, '1', '1', '1', 0);


Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 15, 1, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 15, 3, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 15, 4, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 15, 6, 0);

Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 16, 1, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 16, 3, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 16, 4, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 16, 6, 0);

Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 17, 1, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 17, 3, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 17, 4, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 17, 6, 0);

Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 18, 1, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 18, 3, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 18, 4, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 18, 6, 0);

Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 19, 1, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 19, 3, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 19, 4, 0);
Insert into T_ABTEILUNG_2_NIEDERLASSUNG (ID, ABTEILUNG_ID, NIEDERLASSUNG_ID, VERSION)
 Values (S_T_ABT_2_NL_0.nextVal, 19, 6, 0);

