-- techn. Leistungen
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_LEISTUNG__NO, TYP, PROD_NAME_STR,
    DISPO, EWSD, SDH, IPS, SCT,
    SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (491, '150_VOIP_IPv6', 10219, 'KOMBI', ' ',
    '0', '0', '0', '0', '0',
    '1', TO_DATE('01/12/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 491, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 491, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 72, 491, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 73, 491, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 23, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 25, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 114, 23, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 28, 25, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 111, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 3, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 115, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 480, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 480, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 21, 480, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 22, 480, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 481, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 481, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 23, 481, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 114, 481, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 482, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 482, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 24, 482, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 27, 482, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 483, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 483, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 25, 483, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 28, 483, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 56, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 21, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 22, 21, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 490, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 66, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 67, 66, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 66, 490, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 67, 490, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 490, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 600, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 602, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 601, '0', 0);

Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 67, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 68, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 54, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 28, '0', 0);


-- DSLAM-Profile
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 85);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 87);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 1445);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 1446);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 1447);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 1448);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 1449);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2260);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2261);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2301);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2320);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2323);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2324);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2326);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2328);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2329);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2330);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2331);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2332);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2333);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2529);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2530);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2531);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 2544);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 3420);
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) Values (542, 3424);

-- DSLAM-Profil 150000/15000 dynamisch ermitteln
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
   (select 542, dp.id from t_dslam_profile dp where dp.name='MD_150000_15000_H');



