create table T_GEO_ID_CACHE (
    ID NUMBER(19) NOT NULL
  , STREET VARCHAR2(255) NOT NULL
  , HOUSENUM VARCHAR2(255)
  , HOUSENUMEXTENSION VARCHAR2(255)
  , ZIPCODE VARCHAR2(255) NOT NULL
  , CITY VARCHAR2(255) NOT NULL
  , COUNTRY VARCHAR2(255) NOT NULL
  , DEACTIVATED CHAR(1) DEFAULT 0 NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_GEO_ID_CACHE ADD CONSTRAINT PK_T_GEO_ID_CACHE PRIMARY KEY (ID);
comment on column T_GEO_ID_CACHE.ID is 'Geo ID aus Verfuegbarkeitsdatenbank; ID nicht ueber Sequence generiert!';

grant select on T_GEO_ID_CACHE to R_HURRICAN_READ_ONLY;
grant select, insert, update on T_GEO_ID_CACHE to R_HURRICAN_USER;
