create table T_GEO_ID_2_TECH_LOCATION (
    ID NUMBER(19) NOT NULL
  , GEO_ID NUMBER(19) NOT NULL
  , HVT_ID_STANDORT NUMBER(10) NOT NULL
  , TAL_LENGTH NUMBER(10)
  , KVZ_NUMBER VARCHAR2(10)
  , MAX_BANDWIDTH_ADSL NUMBER(10)
  , MAX_BANDWIDTH_SDSL NUMBER(10)
  , MAX_BANDWIDTH_VDSL NUMBER(10)
  , USERW VARCHAR2(25) NOT NULL
  , DATEW DATE NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_GEO_ID_2_TECH_LOCATION ADD CONSTRAINT PK_T_GEO_ID_2_TECH_LOCATION PRIMARY KEY (ID);
comment on column T_GEO_ID_2_TECH_LOCATION.GEO_ID is 'Geo-ID Referenz, die das Gebaeude bestimmt';
comment on column T_GEO_ID_2_TECH_LOCATION.HVT_ID_STANDORT is 'ID des technischen Standorts, ueber den die Geo-ID erschlossen ist';
comment on column T_GEO_ID_2_TECH_LOCATION.TAL_LENGTH is 'ungefaehre TAL-Laenge in Metern (technischer Standort -> Gebaeude) (nur bei HVT, KVZ)';
comment on column T_GEO_ID_2_TECH_LOCATION.KVZ_NUMBER is 'Nummer des zugehoerigen KVZs';
comment on column T_GEO_ID_2_TECH_LOCATION.MAX_BANDWIDTH_ADSL is 'Einschraenkung fuer die max. moegliche ADSL Bandbreite';
comment on column T_GEO_ID_2_TECH_LOCATION.MAX_BANDWIDTH_SDSL is 'Einschraenkung fuer die max. moegliche SDSL Bandbreite';
comment on column T_GEO_ID_2_TECH_LOCATION.MAX_BANDWIDTH_VDSL is 'Einschraenkung fuer die max. moegliche VDSL Bandbreite';

CREATE INDEX IX_FK_GEOIDMAPPING_2_GEO ON T_GEO_ID_2_TECH_LOCATION (GEO_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_GEO_ID_2_TECH_LOCATION ADD CONSTRAINT FK_GEOIDMAPPING_2_GEO
  FOREIGN KEY (GEO_ID) REFERENCES T_GEO_ID_CACHE (ID);

CREATE INDEX IX_FK_GEOIDMAPPING_2_HVT ON T_GEO_ID_2_TECH_LOCATION (HVT_ID_STANDORT) TABLESPACE "I_HURRICAN";
ALTER TABLE T_GEO_ID_2_TECH_LOCATION ADD CONSTRAINT FK_GEOIDMAPPING_2_HVT
  FOREIGN KEY (HVT_ID_STANDORT) REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

CREATE UNIQUE INDEX IUQ_GEO_ID_2_TECH_LOCATION ON T_GEO_ID_2_TECH_LOCATION (GEO_ID, HVT_ID_STANDORT);

grant select on T_GEO_ID_2_TECH_LOCATION to R_HURRICAN_READ_ONLY;
grant select, insert, update, delete on T_GEO_ID_2_TECH_LOCATION to R_HURRICAN_USER;

create sequence S_T_GEO_ID_2_TECH_LOCATION_0 start with 1;
grant select on S_T_GEO_ID_2_TECH_LOCATION_0 to public;


CREATE OR REPLACE TRIGGER TRBIU_GEO_ID_2_TECH_LOCATION BEFORE INSERT OR UPDATE on T_GEO_ID_2_TECH_LOCATION
for each row
begin
   -- DATEW setzen
   SELECT CURRENT_TIMESTAMP into :new.DATEW FROM dual;
end;
/

