-- Referenzen fuer die Technologietypen anlegen
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22250, 'TECHNOLOGY_TYPE', 'ADSL', NULL, NULL,
    NULL, '1', 10, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22251, 'TECHNOLOGY_TYPE', 'ADSL_POTS', NULL, NULL,
    NULL, '1', 20, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22252, 'TECHNOLOGY_TYPE', 'ADSL_ISDN', NULL, NULL,
    NULL, '1', 30, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22253, 'TECHNOLOGY_TYPE', 'ADSL2PLUS', NULL, NULL,
    NULL, '1', 40, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22254, 'TECHNOLOGY_TYPE', 'ADSL2PLUS_POTS', NULL, NULL,
    NULL, '1', 50, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22255, 'TECHNOLOGY_TYPE', 'ADSL2PLUS_ISDN', NULL, NULL,
    NULL, '1', 60, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22256, 'TECHNOLOGY_TYPE', 'FTTX_POTS', NULL, NULL,
    NULL, '1', 70, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22257, 'TECHNOLOGY_TYPE', 'ISDN', NULL, NULL,
    NULL, '1', 80, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22258, 'TECHNOLOGY_TYPE', 'POTS', NULL, NULL,
    NULL, '1', 90, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22259, 'TECHNOLOGY_TYPE', 'RF', NULL, NULL,
    NULL, '1', 100, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22260, 'TECHNOLOGY_TYPE', 'SDSL', NULL, NULL,
    NULL, '1', 110, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22261, 'TECHNOLOGY_TYPE', 'SHDSL', NULL, NULL,
    NULL, '1', 120, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22262, 'TECHNOLOGY_TYPE', 'VDSL2', NULL, NULL,
    NULL, '1', 130, NULL, 0);
