CREATE TABLE T_HVT_STANDORT_TECH_TYPE
(
  ID                     NUMBER(10)             NOT NULL,
  HVT_ID_STANDORT        NUMBER(10)             NOT NULL,
  TECH_TYPE_REF_ID       NUMBER(10)             NOT NULL,
  AVAILABLE_FROM         DATE,
  AVAILABLE_TO           DATE,
  USERW                  VARCHAR2(15),
  DATEW                  DATE,
  VERSION                NUMBER(18)   DEFAULT 0 NOT NULL
);

COMMENT ON TABLE T_HVT_STANDORT_TECH_TYPE IS 'Tabelle haelt n Kombinationen aus Technologietypen pro techn. Standort.';

COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.ID IS 'ID des Datensatzes';
COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.HVT_ID_STANDORT IS 'ID des techn. Standortes';
COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.TECH_TYPE_REF_ID IS 'ID des Technologietyps aus der T_REFERENCE';
COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.AVAILABLE_FROM IS 'Ab wann ist die Technologie verfügbar';
COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.AVAILABLE_TO IS 'Wann endet die Verfügbarkeit der Technologie';
COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.USERW IS 'Schreibender Zugriff des letzten Benutzers';
COMMENT ON COLUMN T_HVT_STANDORT_TECH_TYPE.DATEW IS 'Datum des letzten schreiben Zugriffs';

create SEQUENCE S_T_HVT_STANDORT_TECH_TYPE_0 start with 1;
grant select on S_T_HVT_STANDORT_TECH_TYPE_0 to public;

ALTER TABLE T_HVT_STANDORT_TECH_TYPE ADD CONSTRAINT PK_T_HVT_STANDORT_TECH_TYPE PRIMARY KEY (ID);

CREATE INDEX IX_FK_STOTT_2_STO ON T_HVT_STANDORT_TECH_TYPE (HVT_ID_STANDORT) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HVT_STANDORT_TECH_TYPE ADD CONSTRAINT FK_STOTT_2_STO
  FOREIGN KEY (HVT_ID_STANDORT) REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

CREATE INDEX IX_FK_STOTT_2_REF ON T_HVT_STANDORT_TECH_TYPE (TECH_TYPE_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HVT_STANDORT_TECH_TYPE ADD CONSTRAINT FK_STOTT_2_REF
  FOREIGN KEY (TECH_TYPE_REF_ID) REFERENCES T_REFERENCE (ID);

ALTER TABLE T_HVT_STANDORT_TECH_TYPE ADD CONSTRAINT UK_HVT_STANDORT_TECH_TYPE UNIQUE (HVT_ID_STANDORT, TECH_TYPE_REF_ID);

create trigger TRBIU_STOTT BEFORE INSERT or UPDATE on T_HVT_STANDORT_TECH_TYPE
for each row
begin
 -- TIMEST setzen
 SELECT CURRENT_TIMESTAMP into :new.DATEW FROM dual;
end;
/

GRANT SELECT ON T_HVT_STANDORT_TECH_TYPE TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HVT_STANDORT_TECH_TYPE TO R_HURRICAN_USER;

