-- Index fuer FK
CREATE INDEX IX_FK_IP_ADDRESS_PREFIX ON T_IP_ADDRESS(PREFIX) TABLESPACE "I_HURRICAN";

-- Feld 'VERSION' fuer Hibernate erstellen
ALTER TABLE T_IP_ADDRESS ADD (VERSION NUMBER(19) DEFAULT 0 NOT NULL);

-- NET_ID darf für 'nicht MOnline IPs' NULL sein
ALTER TABLE T_IP_ADDRESS MODIFY (NET_ID NUMBER(19) NULL );

-- TAIFUN_ORDER_NO kann NULL sein
ALTER TABLE T_IP_ADDRESS MODIFY (TAIFUN_ORDER_NO NUMBER(19) NULL );