-- T_PORT_FORWARD
ALTER TABLE T_PORT_FORWARD ADD (DEST_IP_ADDRESS_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_PF_DIPADDR_2_IPADDR ON T_PORT_FORWARD(DEST_IP_ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PORT_FORWARD ADD CONSTRAINT FK_PF_DIPADDR_2_IPADDR FOREIGN KEY (DEST_IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);

ALTER TABLE T_PORT_FORWARD ADD (SOURCE_IP_ADDRESS_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_PF_SIPADDR_2_IPADDR ON T_PORT_FORWARD(SOURCE_IP_ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PORT_FORWARD ADD CONSTRAINT FK_PF_SIPADDR_2_IPADDR FOREIGN KEY (SOURCE_IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);

-- T_EG_IP
ALTER TABLE T_EG_IP ADD (IP_ADDRESS_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EGIP_IPADDR_2_IPADDR ON T_EG_IP(IP_ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_IP ADD CONSTRAINT FK_EGIP_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);

-- T_EG_CONFIG
ALTER TABLE T_EG_CONFIG ADD (DHCP_POOL_FROM_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EGC_DPFID_2_IPADDR ON T_EG_CONFIG(DHCP_POOL_FROM_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_DPFID_2_IPADDR FOREIGN KEY (DHCP_POOL_FROM_ID) REFERENCES T_IP_ADDRESS (ID);

ALTER TABLE T_EG_CONFIG ADD (DHCP_POOL_TO_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EGC_DPTID_2_IPADDR ON T_EG_CONFIG(DHCP_POOL_TO_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_DPTID_2_IPADDR FOREIGN KEY (DHCP_POOL_TO_ID) REFERENCES T_IP_ADDRESS (ID);

ALTER TABLE T_EG_CONFIG ADD (DNS_SERVER_IP_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EGC_DSIPID_2_IPADDR ON T_EG_CONFIG(DNS_SERVER_IP_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_DSIPID_2_IPADDR FOREIGN KEY (DNS_SERVER_IP_ID) REFERENCES T_IP_ADDRESS (ID);

ALTER TABLE T_EG_CONFIG ADD (TRIGGERPUNKT_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EGC_TRPNKT_2_IPADDR ON T_EG_CONFIG(TRIGGERPUNKT_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_TRPNKT_2_IPADDR FOREIGN KEY (TRIGGERPUNKT_ID) REFERENCES T_IP_ADDRESS (ID);

-- T_EG_2_AUFTRAG
ALTER TABLE T_EG_2_AUFTRAG ADD (IP_ADDRESS_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EG2A_IPADDR_2_IPADDR ON T_EG_2_AUFTRAG(IP_ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_2_AUFTRAG ADD CONSTRAINT FK_EG2A_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);

-- T_EG_IAD
ALTER TABLE T_EG_IAD ADD (IP_ADDRESS_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_EGIAD_IPADDR_2_IPADDR ON T_EG_IAD(IP_ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_IAD ADD CONSTRAINT FK_EGIAD_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);

-- T_IP_ROUTE
ALTER TABLE T_IP_ROUTE ADD (IP_ADDRESS_ID NUMBER(19) NULL);
CREATE INDEX IX_FK_IPR_IPADDR_2_IPADDR ON T_IP_ROUTE(IP_ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_IP_ROUTE ADD CONSTRAINT FK_IPR_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);
