-- Die Sequence fuer Carrier updaten

DECLARE
  curval NUMBER;
  maxval NUMBER;
  inc NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_CARRIER_0 INCREMENT BY 1';
  SELECT MAX(ID) INTO maxval FROM T_CARRIER;
  SELECT S_T_CARRIER_0.NEXTVAL INTO curval FROM DUAL;
  inc := (maxval - curval);
  IF inc > 0 THEN
    EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_CARRIER_0 INCREMENT BY ' || inc;
    SELECT S_T_CARRIER_0.nextval into curval FROM DUAL;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_CARRIER_0 INCREMENT BY 1';
  END IF;
END;
/
