alter table T_ENDSTELLE add GEO_ID NUMBER(19);

CREATE INDEX IX_FK_ENDSTELLE_2_GEO ON T_ENDSTELLE (GEO_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_ENDSTELLE ADD CONSTRAINT FK_ENDSTELLE_2_GEO
  FOREIGN KEY (GEO_ID) REFERENCES T_GEO_ID_CACHE (ID);
