-- Referenzen fuer GeoID Klärung Typ(en) anlegen
INSERT INTO T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 VALUES
   (22311, 'GEOID_CLARIFICATION_TYPE', 'INSERT_GEO_ID', NULL, NULL,
    NULL, '1', 20, NULL, 0);

INSERT INTO T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 VALUES
   (22312, 'GEOID_CLARIFICATION_TYPE', 'UPDATE_GEO_ID', NULL, NULL,
    NULL, '1', 30, NULL, 0);
