-- T_PORT_FORWARD
ALTER TABLE T_PORT_FORWARD MODIFY(DEST_IP_ADDRESS NULL);

-- T_EG_IP
ALTER TABLE T_EG_IP MODIFY(IP_ADDRESS NULL);

-- T_IP_ROUTE
ALTER TABLE T_IP_ROUTE MODIFY(IP_ADDRESS NULL);

-- T_EG_ROUTING
ALTER TABLE T_EG_ROUTING MODIFY(DESTINATION_ADRESS NULL);