-- T_EG_ROUTING
ALTER TABLE T_EG_ROUTING DROP CONSTRAINT FK_EGR_NH_2_IPADDR;

ALTER TABLE T_EG_ROUTING DROP CONSTRAINT FK_EGR_DADDR_2_IPADDR;

-- T_PORT_FORWARD
ALTER TABLE T_PORT_FORWARD DROP CONSTRAINT FK_PF_DIPADDR_2_IPADDR;

ALTER TABLE T_PORT_FORWARD DROP CONSTRAINT FK_PF_SIPADDR_2_IPADDR;

-- T_EG_IP
ALTER TABLE T_EG_IP DROP CONSTRAINT FK_EGIP_IPADDR_2_IPADDR;

-- T_EG_CONFIG
ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_DPFID_2_IPADDR;

ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_DPTID_2_IPADDR;

ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_DSIPID_2_IPADDR;

ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_TRPNKT_2_IPADDR;

-- T_EG_2_AUFTRAG
ALTER TABLE T_EG_2_AUFTRAG DROP CONSTRAINT FK_EG2A_IPADDR_2_IPADDR;

-- T_EG_IAD
ALTER TABLE T_EG_IAD DROP CONSTRAINT FK_EGIAD_IPADDR_2_IPADDR;

-- T_IP_ROUTE
ALTER TABLE T_IP_ROUTE DROP CONSTRAINT FK_IPR_IPADDR_2_IPADDR;

-- T_IP_ADDRESS
ALTER TABLE T_IP_ADDRESS DROP CONSTRAINT UK_IPADDR_ADDRID ;
