alter table T_CB_VORGANG_ANLAGE add ARCHIVE_DOCUMENT_TYPE VARCHAR2(25);
alter table T_CB_VORGANG_ANLAGE add ARCHIVE_VERTRAGS_NR VARCHAR2(25);

update T_CB_VORGANG_ANLAGE set ARCHIVE_DOCUMENT_TYPE='CUDA_KUENDIGUNG', ARCHIVE_VERTRAGS_NR='0';

alter table T_CB_VORGANG_ANLAGE modify ARCHIVE_DOCUMENT_TYPE NOT NULL;
alter table T_CB_VORGANG_ANLAGE modify ARCHIVE_VERTRAGS_NR NOT NULL;
