
ALTER TABLE T_USER_TASK ADD (VERTRAGSNUMMER  VARCHAR2(50 Byte));

ALTER TABLE T_USER_TASK ADD (EMPFANGS_DATUM  DATE);

ALTER TABLE T_USER_TASK ADD (KUENDIGUNGS_DATUM  DATE);

ALTER TABLE T_USER_TASK ADD (STATUS_AKM_PV  VARCHAR2(30 Byte));

alter table T_USER_TASK add (
  constraint T_USER_TASK_STATUS_AKM_PV
  check (STATUS_AKM_PV in ('OFFEN','CLOSED')));