ALTER TABLE T_CARRIER ADD (HAS_WITA NUMBER(1,0) default 0); 

UPDATE T_CARRIER SET HAS_WITA = 1 WHERE TEXT = 'DTAG';
UPDATE T_CARRIER SET HAS_WITA = 1 WHERE TEXT = 'AKOM';
UPDATE T_CARRIER SET HAS_WITA = 1 WHERE TEXT = 'MNET';
UPDATE T_CARRIER SET HAS_WITA = 1 WHERE TEXT = 'QSC';
UPDATE T_CARRIER SET HAS_WITA = 1 WHERE TEXT = 'NefKom';