
ALTER TABLE T_CARRIERBESTELLUNG DROP COLUMN PROJEKT_KENNER;
ALTER TABLE T_CARRIERBESTELLUNG DROP COLUMN KOPPLUNG_KENNER;

ALTER TABLE T_CB_VORGANG ADD PROJEKT_KENNER VARCHAR2(30);
ALTER TABLE T_CB_VORGANG ADD KOPPLUNG_KENNER VARCHAR2(30);