ALTER TABLE T_USER_TASK RENAME COLUMN BEARBEITUNG_STATUS TO TAM_BEARBEITUNG_STATUS;
ALTER TABLE T_USER_TASK ADD (STATUS  VARCHAR2(30 BYTE));
ALTER TABLE T_USER_TASK ADD (BEARBEITER  VARCHAR2(50 BYTE));