update T_USER_TASK set STATUS = 'OFFEN' where STATUS is null;
ALTER TABLE T_USER_TASK MODIFY(STATUS NOT NULL);

ALTER TABLE T_USER_TASK ADD CONSTRAINT T_USER_TASK_STATUS
  CHECK ("STATUS" = 'OFFEN' or "STATUS" = 'GESCHLOSSEN');

update T_USER_TASK set TAM_BEARBEITUNG_STATUS = 'OFFEN' where TAM_BEARBEITUNG_STATUS = 'CLOSED';

ALTER TABLE T_USER_TASK MODIFY(TAM_BEARBEITUNG_STATUS  NULL);
ALTER TABLE T_USER_TASK DROP CONSTRAINT T_USER_TASK_BEARBEITUNG_STATUS;

ALTER TABLE T_USER_TASK ADD CONSTRAINT T_USER_TASK_TAM_STATUS
  CHECK ("TAM_BEARBEITUNG_STATUS"='OFFEN' OR "TAM_BEARBEITUNG_STATUS"='IN_BEARBEITUNG' OR "TAM_BEARBEITUNG_STATUS"='KUNDE_NICHT_ERREICHT' OR "TAM_BEARBEITUNG_STATUS"='KUNDE_MELDET_SICH' OR "TAM_BEARBEITUNG_STATUS"='TV_60_TAGE' OR "TAM_BEARBEITUNG_STATUS"='INFO_MAILED' );


