ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN
RENAME COLUMN AUFTRAGID TO AUFTRAG_ID;

DELETE FROM T_USER_TASK_2_AUFTRAGDATEN;

ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN
 ADD (CB_ID  NUMBER(19) NOT NULL);

ALTER TABLE T_USER_TASK_2_AUFTRAGDATEN
 ADD CONSTRAINT FK_USERTASK_2_AD_2_CB
  FOREIGN KEY (CB_ID)
  REFERENCES T_CARRIERBESTELLUNG (CB_ID);
