-- +++++++++++++++++++++++++++++++++++++++++++++++++++
-- Copyright (c) 2008 - M-net Telekommunikations GmbH
-- All rights reserved.
-- +++++++++++++++++++++++++++++++++++++++++++++++++++
--
-- View fuer die Darstellung der CrossConnections zu einem Port
--
-- Verwendete Tabellen:
--   + T_EQUIPMENT
--   + T_EQ_CROSS_CONNECTION
--


CREATE or REPLACE FORCE VIEW V_HURRICAN_CROSS_CONNECTION
  AS select
 CC.EQUIPMENT_ID as EQUIPMENT_ID
 , CC.BRAS_INNER as BRAS_INNER
 , CC.BRAS_OUTER as BRAS_OUTER
 , CC.LT_INNER as LT_INNER
 , CC.LT_OUTER as LT_OUTER
 , CC.NT_INNER as NT_INNER
 , CC.NT_OUTER as NT_OUTER
 , CC.VALID_FROM as VALID_FROM
 , CC.VALID_TO as VALID_TO
 , CC.USERW as USERW
 , REF.STR_VALUE as CC_TYPE
 , CC.BRAS_POOL_ID as BRAS_POOL_ID
 , BRAS.NAME as BRAS_POOL_NAME
 , BRAS.VP as BRAS_POOL_VP
 , BRAS.VC_MIN as BRAS_POOL_VC_MIN
 , BRAS.VC_MAX as BRAS_POOL_VC_MAX
 , BRAS.SLOT as BRAS_SLOT
 , BRAS.PORT as BRAS_PORT
 , BRAS.NAS_IDENTIFIER as BRAS__POOLNAS_ID
 , BRAS.BACKUP_SLOT as BRAS_POOL_SLOT
 , BRAS.BACKUP_PORT as BRAS_POOL_PORT
 , BRAS.BACKUP_NAS_IDENTIFIER as BRAS__POOLBACKUP_NAS_ID
 from T_EQ_CROSS_CONNECTION cc
 inner join T_REFERENCE ref on CC.CC_TYPE_REF_ID=REF.ID
 left join T_BRAS_POOLS bras on CC.BRAS_POOL_ID=BRAS.ID
 ;


CREATE OR REPLACE SYNONYM BSICRM.V_HURRICAN_CROSS_CONNECTION FOR V_HURRICAN_CROSS_CONNECTION;

GRANT SELECT ON V_HURRICAN_CROSS_CONNECTION TO R_HURRICAN_BSI_VIEWS;
