-- +++++++++++++++++++++++++++++++++++++++++++++++++++
-- Copyright (c) 2015 - M-net Telekommunikations GmbH
-- All rights reserved.
-- +++++++++++++++++++++++++++++++++++++++++++++++++++
--
-- View fuer die Darstellung der Rufnummernplaene aus Hurrican
--
-- Verwendete Tabellen:
--   + T_AUFTRAG_VOIP_DN
--   + T_AUFTRAG_VOIP_DN_PLAN
--   + T_VOIP_DNPLAN_BLOCK
--
-- Besonderheiten:
--

CREATE or REPLACE FORCE VIEW V_HURRICAN_VOIP_DN_PLAN
AS
  SELECT
    T_AUFTRAG_VOIP_DN.AUFTRAG_ID AS TECH_ORDER_ID, T_AUFTRAG_VOIP_DN.DN__NO,
    T_AUFTRAG_VOIP_DN_PLAN.GUELTIG_AB,
    T_VOIP_DNPLAN_BLOCK.ANFANG, T_VOIP_DNPLAN_BLOCK.ENDE, T_VOIP_DNPLAN_BLOCK.ZENTRALE
  FROM T_AUFTRAG_VOIP_DN
    INNER JOIN T_AUFTRAG_VOIP_DN_PLAN ON T_AUFTRAG_VOIP_DN.ID = T_AUFTRAG_VOIP_DN_PLAN.AUFTRAG_VOIP_DN_ID
    INNER JOIN T_VOIP_DNPLAN_BLOCK ON T_AUFTRAG_VOIP_DN_PLAN.ID = T_VOIP_DNPLAN_BLOCK.VOIP_DN_PLAN_ID
;

CREATE OR REPLACE SYNONYM BSICRM.V_HURRICAN_VOIP_DN_PLAN FOR V_HURRICAN_VOIP_DN_PLAN;

GRANT SELECT ON V_HURRICAN_VOIP_DN_PLAN TO R_HURRICAN_BSI_VIEWS;
