CREATE TABLE T_WBCI_GESCHAEFTSFALL_TODO (GESCHAEFTSFALL_ID NUMBER(19, 0) NOT NULL, TODO_LISTE_ID NUMBER(19, 0) NOT NULL);
CREATE TABLE T_WBCI_TODO_LISTE (id NUMBER(19, 0) NOT NULL, VERSION NUMBER(19, 0) NOT NULL, NAME VARCHAR2(30 CHAR), PRIMARY KEY (id));
CREATE TABLE T_WBCI_TODO_EINTRAG (id NUMBER(19, 0) NOT NULL, VERSION NUMBER(19, 0) NOT NULL, TODO_LISTE_ID NUMBER(19, 0), TEXT VARCHAR2(255 CHAR), PRIMARY KEY (id));

ALTER TABLE T_WBCI_GESCHAEFTSFALL_TODO ADD CONSTRAINT FK_TODO_GESCHAEFTSFALL_ID FOREIGN KEY (GESCHAEFTSFALL_ID) REFERENCES T_WBCI_GESCHAEFTSFALL;
ALTER TABLE T_WBCI_TODO_EINTRAG ADD CONSTRAINT FK_TODO_EINTRAG_LIST_ID FOREIGN KEY (TODO_LISTE_ID) REFERENCES T_WBCI_TODO_LISTE;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_WBCI_GESCHAEFTSFALL_TODO TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_WBCI_TODO_LISTE TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_WBCI_TODO_EINTRAG TO R_HURRICAN_USER;

GRANT SELECT ON T_WBCI_GESCHAEFTSFALL_TODO TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_TODO_LISTE TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_WBCI_TODO_EINTRAG TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_TODO_LISTE_0;
CREATE SEQUENCE S_T_WBCI_TODO_EINTRAG_0;

GRANT SELECT ON S_T_WBCI_TODO_LISTE_0 TO PUBLIC;
GRANT SELECT ON S_T_WBCI_TODO_EINTRAG_0 TO PUBLIC;