ALTER TABLE T_WBCI_TODO_LISTE MODIFY NAME VARCHAR2(50 CHAR);

-- Insert basic todolisten with basic entries
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'RUEM_VA_VERSENDET', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'RUEM_VA_EMPFANGEN', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'AKM_TR_VERSENDET', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'AKM_TR_EMPFANGEN', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'ABBM_EMPFANGEN', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'ABBM_TR_EMPFANGEN', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'ABBM_TR_VERSENDET', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'STORNO_ERLM_EMPFANGEN (AUFNEHMEND)', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'STORNO_ERLM_VERSENDET (AUFNEHMEND)', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'STORNO_ERLM_EMPFANGEN (ABGEBEND)', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'STORNO_ERLM_VERSENDET (ABGEBEND)', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'STORNO_ABBM_EMPFANGEN (ABGEBEND)', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'TV_ERLM_EMPFANGEN (AUFNEHMEND)', 0);
INSERT INTO T_WBCI_TODO_LISTE (ID, NAME, VERSION) VALUES (S_T_WBCI_TODO_LISTE_0.nextval, 'TV_ERLM_VERSENDET (ABGEBEND)', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'RUEM_VA_VERSENDET'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'RUEM_VA_VERSENDET'), 'Portierungsgebühr einbuchen', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'RUEM_VA_VERSENDET'), 'Kunde informieren', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'RUEM_VA_EMPFANGEN'), 'Termin in Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'RUEM_VA_EMPFANGEN'), 'Kunde benachrichtigen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'AKM_TR_VERSENDET'), 'Bauauftrag oder WITA auslösen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'AKM_TR_EMPFANGEN'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'AKM_TR_EMPFANGEN'), 'WITA kündigen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'ABBM_EMPFANGEN'), 'Termin in Taifun aktualisieren ggf. rückgängig machen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'ABBM_TR_EMPFANGEN'), 'Bauauftrag oder WITA ändern', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'ABBM_TR_EMPFANGEN'), 'Storno notwendig?', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'ABBM_TR_VERSENDET'), 'EKPauf benachrichtigen bzw. klären', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_EMPFANGEN (AUFNEHMEND)'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_EMPFANGEN (AUFNEHMEND)'), 'Kunde benachrichtigen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_VERSENDET (AUFNEHMEND)'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_VERSENDET (AUFNEHMEND)'), 'Kunde benachrichtigen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_EMPFANGEN (ABGEBEND)'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_EMPFANGEN (ABGEBEND)'), 'Evtl. Taifunkündigung rückgängig machen', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_EMPFANGEN (ABGEBEND)'), 'Kunde benachrichtigen', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_EMPFANGEN (ABGEBEND)'), 'WITA kontrollieren', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_VERSENDET (ABGEBEND)'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_VERSENDET (ABGEBEND)'), 'Evtl. Taifunkündigung rückgängig machen', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_VERSENDET (ABGEBEND)'), 'Kunde benachrichtigen', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ERLM_VERSENDET (ABGEBEND)'), 'WITA kontrollieren', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'STORNO_ABBM_EMPFANGEN (ABGEBEND)'), 'EKPauf benachrichtigen bzw. klären', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'TV_ERLM_EMPFANGEN (AUFNEHMEND)'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'TV_ERLM_EMPFANGEN (AUFNEHMEND)'), 'WITA Terminverschiebung', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'TV_ERLM_EMPFANGEN (AUFNEHMEND)'), 'Kunde benachrichtigen', 0);

INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'TV_ERLM_VERSENDET (ABGEBEND)'), 'Taifun aktualisieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'TV_ERLM_VERSENDET (ABGEBEND)'), 'WITA kontrollieren', 0);
INSERT INTO T_WBCI_TODO_EINTRAG (ID, TODO_LISTE_ID, TEXT, VERSION) VALUES (S_T_WBCI_TODO_EINTRAG_0.nextval, (SELECT ID FROM T_WBCI_TODO_LISTE WHERE NAME = 'TV_ERLM_VERSENDET (ABGEBEND)'), 'Kunde benachrichtigen', 0);