delete from T_KUENDIGUNG_FRIST;
delete from T_KUENDIGUNG_CHECK;

alter table T_KUENDIGUNG_FRIST drop constraint CK_KUENDF_FRIST_AUF;
ALTER TABLE T_KUENDIGUNG_FRIST
ADD CONSTRAINT CK_KUENDF_FRIST_AUF
CHECK (FRIST_AUF IN (
    'ENDE_MVLZ',
    'MONATSENDE',
    'EINGANGSDATUM'
  )) ENABLE NOVALIDATE;

-- OE__NO=81
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 81, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=81),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=81),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=82
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 82, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=82),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=82),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=83
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 83, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=83),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=83),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=84
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 84, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=84),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=84),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=85
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 85, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=85),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=85),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=86
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 86, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=86),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=86),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=87
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 87, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=87),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=87),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');



-- OE__NO=91
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 91, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=91),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=91),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=92
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 92, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=92),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=92),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=93
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 93, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=93),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=93),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=94
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 94, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=94),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=94),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=95
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 95, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=95),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=95),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=96
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 96, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=96),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=96),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=97
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 97, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=97),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=97),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=98
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 98, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=98),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=98),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=99
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 99, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=99),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=99),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');


-- OE__NO=113
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 113, '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=113),
      '1', 24, 'ENDE_MVLZ', null, null, '6 Monate zum Ende der MVLZ; Verlängerung um 1 Jahr');
-- OE__NO=114
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 114, '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=114),
      '1', 24, 'ENDE_MVLZ', null, null, '6 Monate zum Ende der MVLZ; Verlängerung um 1 Jahr');
-- OE__NO=115
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 115, '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=115),
      '1', 24, 'ENDE_MVLZ', null, null, '6 Monate zum Ende der MVLZ; Verlängerung um 1 Jahr');



-- OE__NO=302
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 302, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=302),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=302),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=303
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 303, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=303),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=303),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=304
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 304, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=304),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=304),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=305
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 305, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=305),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=305),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=306
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 306, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=306),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=306),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=307
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 307, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=307),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=307),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=308
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 308, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=308),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=308),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=309
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 309, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=309),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=309),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=310
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 310, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=310),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=310),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=312
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 312, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=312),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=312),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=315
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 315, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=315),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=315),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=402
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 402, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=402),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=402),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=403
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 403, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=403),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=403),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=410
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 410, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=410),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=410),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=411
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 411, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=411),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=411),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=412
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 412, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=412),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=412),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=414
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 414, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=414),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=414),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=415
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 415, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=415),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=415),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=417
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 417, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=417),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=417),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=418
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 418, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=418),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=418),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=419
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 419, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=419),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=419),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=426
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 426, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=426),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=426),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=430
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 430, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=430),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=430),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=432
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 432, '0', 0);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=432),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=432),
      '1', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
-- OE__NO=433
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 433, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=433),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=433),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');


-- OE__NO=421
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 421, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=421),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=421),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=422
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 422, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=422),
      '0', 12, 'EINGANGSDATUM', 2006, 5, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=422),
      '0', 6, 'EINGANGSDATUM', 2009, 4, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=422),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende MVLZ');
-- OE__NO=423
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 423, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=423),
      '0', 12, 'EINGANGSDATUM', 2007, 4, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=423),
      '0', 6, 'EINGANGSDATUM', 2009, 4, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=423),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende MVLZ');


-- OE__NO=435
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 435, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=435),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=435),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=437
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 437, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=437),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=437),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=440
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 440, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=440),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=440),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=449
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 449, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=449),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=449),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');


-- OE__NO=451
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 451, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=451),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=451),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=452
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 452, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=452),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=452),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');

-- OE__NO=454
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 454, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=454),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=454),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');
-- OE__NO=455
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 455, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=455),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=455),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');


-- OE__NO=502
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 502, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=502),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=502),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=509
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 509, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=509),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=509),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=511
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 511, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=511),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=511),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=516
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 516, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=516),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=516),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=518
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 518, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=518),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=518),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=817
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 817, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=817),
      '0', 6, 'MONATSENDE', null, null, '6 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=817),
      '1', 6, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=874
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 874, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=874),
      '0', 6, 'MONATSENDE', null, null, '6 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=874),
      '1', 6, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende der MVLZ');

-- OE__NO=882
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 882, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=882),
      '0', 6, 'MONATSENDE', null, null, '6 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=882),
      '1', 6, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende der MVLZ');

-- OE__NO=1011
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1011, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1011),
      '0', 6, 'MONATSENDE', null, null, '6 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1011),
      '1', 6, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende der MVLZ');
-- OE__NO=1012
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1012, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1012),
      '0', 6, 'MONATSENDE', null, null, '6 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1012),
      '1', 6, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende der MVLZ');
-- OE__NO=1016
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1016, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1016),
      '0', 6, 'MONATSENDE', null, null, '6 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1016),
      '1', 6, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende der MVLZ');


-- OE__NO=1038
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1038, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1038),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1038),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=1041
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1041, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1041),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1041),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');

-- OE__NO=724
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 724, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=724),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=724),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=725
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 725, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=725),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=725),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=726
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 726, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=726),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=726),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=750
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 750, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=750),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=750),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=751
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 751, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=751),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=751),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=752
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 752, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=752),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=752),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');



-- OE__NO=1120
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1120, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1120),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1120),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=1121
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1121, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1121),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1121),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=1122
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1122, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1122),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1122),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=1123
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1123, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1123),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1123),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=1144
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1144, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1144),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1144),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=1145
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1145, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1145),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1145),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=893
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 893, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=893),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=893),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=894
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 894, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=894),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=894),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=902
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 902, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=902),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=902),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=903
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 903, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=903),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=903),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');


-- OE__NO=813
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 813, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=813),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=821
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 821, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=821),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1060
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1060, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1060),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1062
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1062, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1062),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1061
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1061, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1061),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1063
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1063, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1063),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1408
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1408, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1408),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1409
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1409, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1409),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1410
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1410, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1410),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');
-- OE__NO=1411
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1411, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=1411),
      '1', 12, 'ENDE_MVLZ', null, null, '6 Wochen zum Ende MVLZ');


-- OE__NO=2000
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2000, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2000),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2000),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');
-- OE__NO=2001
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2001, '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2001),
      '0', 4, 'EINGANGSDATUM', null, null, '4 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2001),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende MVLZ; sonst Verlängerung um 3 Monate');

-- OE__NO=2002
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2002, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2002),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2002),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate zum Ende der MVLZ');

-- OE__NO=2003
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2003, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2003),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2003),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');
-- OE__NO=2004
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2004, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2004),
      '0', 2, 'MONATSENDE', null, null, '2 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2004),
      '1', 2, 'ENDE_MVLZ', null, null, '2 Wochen zum Ende der MVLZ');

-- OE__NO=2005
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2005, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2005),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2005),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate ab Ende der MVLZ');

-- OE__NO=2006
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2006, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2006),
      '0', 4, 'MONATSENDE', null, null, '4 Wochen zum Monatsende');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2006),
      '1', 4, 'ENDE_MVLZ', null, null, '4 Wochen zum Ende der MVLZ');

-- OE__NO=2008
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2008, '0', 1);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2008),
      '0', 12, 'EINGANGSDATUM', null, null, '3 Monate ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2008),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate ab Ende der MVLZ');


-- OE__NO=2011
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2011, '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2011),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2011),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ, Verlängerung um 1 Jahr');
-- OE__NO=2012
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2012, '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2012),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2012),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ, Verlängerung um 1 Jahr');
-- OE__NO=2014
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2014, '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2014),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=2014),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ, Verlängerung um 1 Jahr');

-- OE__NO=3007
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3007 , '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3007),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3007),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ');

-- OE__NO=3012
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3012 , '0', 3);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3012),
      '1', 4, 'ENDE_MVLZ', null, null, '1 Monat vor Ende der MVLZ, Verlängerung um 3 Monate');


-- OE__NO=3401
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3401 , '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3401),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3401),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ, Verlängerung um 1 Jahr');

-- OE__NO=3402
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3402 , '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3402),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3402),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ, Verlängerung um 1 Jahr');

-- OE__NO=3403
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3403 , '0', 12);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3403),
      '0', 6, 'EINGANGSDATUM', null, null, '6 Wochen ab Eingangsdatum');
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3403),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ, Verlängerung um 1 Jahr');

-- OE__NO=2009
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2009 , '0', 0);
insert into T_KUENDIGUNG_FRIST (ID, KUENDIGUNG_CHECK_ID, MIT_MVLZ, FRIST_IN_WOCHEN, FRIST_AUF, VERTRAG_AB_JAHR, VERTRAG_AB_MONAT, DESCRIPTION)
  values (S_T_KUENDIGUNG_FRIST_0.nextVal, (select c.id from T_KUENDIGUNG_CHECK c where c.OE__NO=3403),
      '1', 12, 'ENDE_MVLZ', null, null, '3 Monate vor Ende der MVLZ');


-- OE__NO=44
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 44, '1', 0);
-- OE__NO=45
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 45, '1', 0);

