

delete from T_KUENDIGUNG_FRIST where KUENDIGUNG_CHECK_ID in
  (select c.ID from T_KUENDIGUNG_CHECK c where c.OE__NO in (113, 114, 115, 817, 1011, 1012, 1016, 1120, 1121, 1122, 1123, 2006, 3012));
delete from T_KUENDIGUNG_CHECK where OE__NO in (113, 114, 115, 817, 1011, 1012, 1016, 1120, 1121, 1122, 1123, 2006, 3012);

insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 110, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 111, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 112, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 113, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 114, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 115, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 794, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 814, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 815, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 816, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 817, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 820, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 822, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 823, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 824, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 825, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 892, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 895, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 896, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 897, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 898, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 901, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 904, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 905, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 906, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 907, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1009, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1010, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1011, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1012, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1013, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1014, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1015, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1016, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1120, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1121, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1122, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 1123, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 2006, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3012, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3016, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3017, '1', 0);
insert into T_KUENDIGUNG_CHECK (ID, OE__NO, DURCH_VERTRIEB, AUTO_VERLAENGERUNG)
  values (S_T_KUENDIGUNG_CHECK_0.nextVal, 3018, '1', 0);