ALTER TABLE T_HW_BAUGRUPPEN_TYP add DEF_SCHICHT2_PROTOKOLL varchar2(10);

alter table T_HW_BAUGRUPPEN_TYP add constraint CK_HW_BAUGRP_TYP_SCHICHT2PROT check (DEF_SCHICHT2_PROTOKOLL in ('ATM', 'EFM'));
