CREATE TABLE T_WBCI_ANTWORTFRIST (id NUMBER(19, 0) NOT NULL, version NUMBER(19, 0), status VARCHAR2(25), FRIST_IN_STUNDEN NUMBER(19, 0), PRIMARY KEY (id));
alter table T_WBCI_ANTWORTFRIST add constraint UQ_WBCI_ANTWORTFRIST_STATUS UNIQUE (status);

GRANT SELECT, INSERT, UPDATE ON T_WBCI_ANTWORTFRIST TO R_HURRICAN_USER;
GRANT SELECT ON T_WBCI_ANTWORTFRIST TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_WBCI_ANTWORTFRIST_0;
GRANT SELECT ON S_T_WBCI_ANTWORTFRIST_0 TO PUBLIC;

ALTER TABLE T_WBCI_REQUEST ADD ANSWER_UNTILL TIMESTAMP(6);
