ALTER TABLE T_WBCI_REQUEST rename column ANSWER_UNTILL to ANSWER_DEADLINE;
ALTER TABLE T_WBCI_REQUEST ADD IS_MNET_RESPONSIBLE NUMBER(1,0);

ALTER TABLE T_WBCI_ANTWORTFRIST
ADD CONSTRAINT CK_WBCI_ANTWORTFRIST_STATUS
CHECK (STATUS IN (
    'VA_EMPFANGEN',
    'RUEM_VA_VERSENDET',
    'ABBM_VERSENDET',
    'AKM_TR_EMPFANGEN',
    'ABBM_TR_VERSENDET',
    'VA_VORGEHALTEN',
    'VA_VERSENDET',
    'RUEM_VA_EMPFANGEN',
    'ABBM_EMPFANGEN',
    'AKM_TR_VERSENDET',
    'ABBM_TR_EMPFANGEN',
    'TV_EMPFANGEN',
    'TV_ERLM_VERSENDET',
    'TV_ABBM_VERSENDET',
    'TV_VORGEHALTEN',
    'TV_VERSENDET',
    'TV_ERLM_EMPFANGEN',
    'TV_ABBM_EMPFANGEN',
    'STORNO_VORGEHALTEN',
    'STORNO_VERSENDET',
    'STORNO_ERLM_EMPFANGEN',
    'STORNO_ABBM_EMPFANGEN',
    'STORNO_EMPFANGEN',
    'STORNO_ERLM_VERSENDET',
    'STORNO_ABBM_VERSENDET'
  )) ENABLE NOVALIDATE;
