INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'VA_EMPFANGEN', 72, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'VA_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'RUEM_VA_VERSENDET', 192, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'RUEM_VA_EMPFANGEN', 192, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'TV_EMPFANGEN', 72, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'TV_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STORNO_EMPFANGEN', 72, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STORNO_VERSENDET', 72, 0);

INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STORNO_ERLM_EMPFANGEN', 24, 0);
INSERT INTO T_WBCI_ANTWORTFRIST (ID, STATUS, FRIST_IN_STUNDEN, VERSION)
    VALUES (S_T_WBCI_ANTWORTFRIST_0.nextVal, 'STORNO_ERLM_VERSENDET', 24, 0);
