-- map CPS-Chain (CPS - DSL+VOIP am HVT) 2 Produkt (DSL + VoIP) 4 lockSubscriber 
INSERT INTO T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 VALUES
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 480, 14006, 59, 0);
