apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: adl-env01
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - name: config-server
      targetPort: 8888
      port: 8888
