apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
patches:
  -  path: ./patches/deployment.yaml
  -  path: ./patches/ingress.yaml
  -  path: ./patches/service.yaml
