alter table T_IPSEC_S2S add  HOSTNAME_PASSIVE VARCHAR(40);
COMMENT ON COLUMN T_IPSEC_S2S.HOSTNAME_PASSIVE
      IS 'der passive Host-Name';

alter table T_IPSEC_S2S add VIRTUAL_LAN_TO_SCRAMBLE VARCHAR(40);
COMMENT ON COLUMN T_IPSEC_S2S.VIRTUAL_LAN_TO_SCRAMBLE
      IS 'zu verschluesselndes Netz, bspw. 172.17.208.112/29';