ALTER TABLE T_VPN ADD (
  NIEDERLASSUNG_ID NUMBER(10),
  VPN_SALESREP VARCHAR(50),
  VPN_QOS CHAR(1),
  CONSTRAINT FK_VPN_2_NIEDERLASSUNG FOREIGN KEY (NIEDERLASSUNG_ID) REFERENCES T_NIEDERLASSUNG(ID)
);
