apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: adl-env01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker.adl.dev.bitconex.com/bitconex-config-server:latest
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: config-server-configmap
      imagePullSecrets:
        - name: docker-regcred
