apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
        namespace: flux-system
      spec:
        template:
          metadata:
          spec:
            containers:
            - name: manager
              env:
              - name: AZURE_AUTH_METHOD
                value: msi
              envFrom:
              - secretRef:
                  name: azure-sp-secret
    target:
      kind: Deployment
      name: kustomize-controller