--
-- Aufbau der Log-DB fuer die Migration
--

CREATE TABLE MIG_STATUS (
       ID INT(9) NOT NULL
     , STATUS VARCHAR(100) NOT NULL
     , PRIMARY KEY (ID)
)TYPE=InnoDB;

CREATE TABLE MIG_LOG (
       ID INT(11) NOT NULL AUTO_INCREMENT
     , AUFTRAG_ID INT(9) NOT NULL
     , ORDER__NO INT(10)
     , KUNDE__NO INT(9)
     , MIG_STATUS INT(9) NOT NULL
     , MIG_INFO TEXT
     , MIG_AT DATETIME NOT NULL
     , PRIMARY KEY (ID)
)TYPE=InnoDB;

ALTER TABLE MIG_LOG
  ADD CONSTRAINT FK_MIGLOG_2_MIGSTATUS
      FOREIGN KEY (MIG_STATUS)
      REFERENCES MIG_STATUS (ID)
   ON DELETE NO ACTION
   ON UPDATE CASCADE;

-- Default-Daten setzen
insert into MIG_STATUS (ID, STATUS) values (0, 'OK'),(1, 'INFO'),(2, 'WARNING'),(3, 'ERROR');

