-- ADDRESS_ID anlegen
CREATE SEQUENCE S_T_IP_ADDRESS_ID_0
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

ALTER TABLE T_IP_ADDRESS ADD (ADDRESS_ID NUMBER(19) NOT NULL);
CREATE INDEX IX_UK_IPADDR_ADDRID ON T_IP_ADDRESS (ADDRESS_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_IP_ADDRESS ADD CONSTRAINT UK_IPADDR_ADDRID UNIQUE (ADDRESS_ID);

-- T_EG_ROUTING
ALTER TABLE T_EG_ROUTING DROP CONSTRAINT FK_EGR_NH_2_IPADDR;
ALTER TABLE T_EG_ROUTING ADD CONSTRAINT FK_EGR_NH_2_IPADDR FOREIGN KEY (NEXT_HOP_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

ALTER TABLE T_EG_ROUTING DROP CONSTRAINT FK_EGR_DADDR_2_IPADDR;
ALTER TABLE T_EG_ROUTING ADD CONSTRAINT FK_EGR_DADDR_2_IPADDR FOREIGN KEY (DESTINATION_ADRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

-- T_PORT_FORWARD
ALTER TABLE T_PORT_FORWARD DROP CONSTRAINT FK_PF_DIPADDR_2_IPADDR;
ALTER TABLE T_PORT_FORWARD ADD CONSTRAINT FK_PF_DIPADDR_2_IPADDR FOREIGN KEY (DEST_IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

ALTER TABLE T_PORT_FORWARD DROP CONSTRAINT FK_PF_SIPADDR_2_IPADDR;
ALTER TABLE T_PORT_FORWARD ADD CONSTRAINT FK_PF_SIPADDR_2_IPADDR FOREIGN KEY (SOURCE_IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

-- T_EG_IP
ALTER TABLE T_EG_IP DROP CONSTRAINT FK_EGIP_IPADDR_2_IPADDR;
ALTER TABLE T_EG_IP ADD CONSTRAINT FK_EGIP_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

-- T_EG_CONFIG
ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_DPFID_2_IPADDR;
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_DPFID_2_IPADDR FOREIGN KEY (DHCP_POOL_FROM_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_DPTID_2_IPADDR;
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_DPTID_2_IPADDR FOREIGN KEY (DHCP_POOL_TO_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_DSIPID_2_IPADDR;
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_DSIPID_2_IPADDR FOREIGN KEY (DNS_SERVER_IP_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

ALTER TABLE T_EG_CONFIG DROP CONSTRAINT FK_EGC_TRPNKT_2_IPADDR;
ALTER TABLE T_EG_CONFIG ADD CONSTRAINT FK_EGC_TRPNKT_2_IPADDR FOREIGN KEY (TRIGGERPUNKT_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

-- T_EG_2_AUFTRAG
ALTER TABLE T_EG_2_AUFTRAG DROP CONSTRAINT FK_EG2A_IPADDR_2_IPADDR;
ALTER TABLE T_EG_2_AUFTRAG ADD CONSTRAINT FK_EG2A_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

-- T_EG_IAD
ALTER TABLE T_EG_IAD DROP CONSTRAINT FK_EGIAD_IPADDR_2_IPADDR;
ALTER TABLE T_EG_IAD ADD CONSTRAINT FK_EGIAD_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);

-- T_IP_ROUTE
ALTER TABLE T_IP_ROUTE DROP CONSTRAINT FK_IPR_IPADDR_2_IPADDR;
ALTER TABLE T_IP_ROUTE ADD CONSTRAINT FK_IPR_IPADDR_2_IPADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ADDRESS_ID);
