drop sequence S_T_CARRIERBESTELLUNG_ATYP_0;
drop sequence S_T_CARRIERBESTELLUNG_ANLAGE_0;
drop table T_CARRIERBESTELLUNG_ANLAGE;
drop table T_CARRIERBESTELLUNG_ANLAGETYP;


CREATE TABLE T_CB_VORGANG_ANLAGE
(
   ID                   NUMBER (19, 0) NOT NULL,
   VERSION              NUMBER (19, 0) DEFAULT 0 NOT NULL,
   ARCHIVEKEY           VARCHAR2 (255) NOT NULL,
   MIMETYPE             VARCHAR2 (50) NOT NULL,
   ANLAGENTYP           VARCHAR2 (50) NOT NULL,
   CBVORGANG_ID NUMBER(19,0) NOT NULL,
   constraint           FK_CBVA_2_CBV
   foreign key          (CBVORGANG_ID)
   references           T_CB_VORGANG (ID),
   PRIMARY KEY          (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_CB_VORGANG_ANLAGE TO R_HURRICAN_USER;
GRANT SELECT ON T_CB_VORGANG_ANLAGE TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_CB_VORGANG_ANLAGE_0
   START WITH 1;

GRANT SELECT ON S_T_CB_VORGANG_ANLAGE_0 TO PUBLIC;

