ALTER TABLE T_CARRIERBESTELLUNG DROP COLUMN CARRIERBESTELLUNGPV_ID;
ALTER TABLE T_VORABSTIMMUNG ADD (
    ES_TYP CHAR(1), 
    AUFTRAG_ID NUMBER(19));
    
-- ONLY TO ALLOW FOR NOT-NULL CONSTRAINTS
DELETE FROM T_VORABSTIMMUNG;
    
ALTER TABLE T_VORABSTIMMUNG MODIFY (
    ES_TYP CHAR(1) NOT NULL, 
    AUFTRAG_ID NUMBER(19) NOT NULL);
    
ALTER TABLE T_VORABSTIMMUNG ADD CONSTRAINT FK_VORABSTIMMUNG_2_AUFTRAG FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);
ALTER TABLE T_VORABSTIMMUNG ADD (
  CONSTRAINT T_VORABSTIMMUNG_ES_TYP
  CHECK (ES_TYP IN ('A', 'B')));
   
ALTER TABLE T_VORABSTIMMUNG ADD CONSTRAINT T_VORABSTIMMUNG_UNIQUE UNIQUE (ES_TYP, AUFTRAG_ID);

