--
-- SQL Script, um notwendige Baugruppentypen fuer Alcatel xDSL anzulegen.
--

insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (40, 'ABLTF', 24, 'Alcatel ABLTF', 1, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (41, 'ADLTK', 12, 'Alcatel ADLTK', 0, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (42, 'ADLTN', 24, 'Alcatel ADLTN', 0, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (43, 'EBLTD', 48, 'Alcatel EBLTD', 0, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (44, 'EBLTF', 48, 'Alcatel EBLTF', 1, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (45, 'NALTD', 48, 'Alcatel NALTD', 1, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (46, 'NSLTA', 24, 'Alcatel NSLTA', 1, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (47, 'SHLTB', 12, 'Alcatel SHLTB', 0, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (48, 'SMLTA', 24, 'Alcatel SMLTA', 0, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (49, 'SMLTC', 24, 'Alcatel SMLTC', 1, null);
insert into T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME)
  values (50, 'SMLTJ', 24, 'Alcatel SMLTJ', 0, null);
commit;

drop sequence S_T_HW_BAUGRUPPEN_TYP_0;
create sequence S_T_HW_BAUGRUPPEN_TYP_0 start with 51;
grant select on S_T_HW_BAUGRUPPEN_TYP_0 to public;
commit;
