--
-- SQL-Script, um eine Version Spalte (optimistic locking) zu den Hardware Racks hinzuzufuegen
--

ALTER TABLE T_HW_RACK_DSLAM
 RENAME COLUMN VERSION TO SOFTWARE_VERSION;

ALTER TABLE T_HW_RACK_DLU
ADD (VERSION NUMBER(18) DEFAULT 0 NOT NULL);

ALTER TABLE T_HW_RACK_DSLAM
 ADD (VERSION NUMBER(18) DEFAULT 0 NOT NULL);

ALTER TABLE T_HW_RACK_LTG
 ADD (VERSION NUMBER(18) DEFAULT 0 NOT NULL);

ALTER TABLE T_HW_RACK_MDU
 ADD (VERSION NUMBER(18) DEFAULT 0 NOT NULL);

ALTER TABLE T_HW_RACK_OLT
 ADD (VERSION NUMBER(18) DEFAULT 0 NOT NULL);

ALTER TABLE T_HW_RACK_ROUTER
 ADD (VERSION NUMBER(18) DEFAULT 0 NOT NULL);
