-- Produkt SIP-Trunk anlegen

-- SIP-DOMAIN
INSERT INTO T_PROD_2_SIP_DOMAIN
   (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW,
    DATEW, VERSION, DEFAULT_DOMAIN)
 VALUES
   (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 580, 22208, 22346, 'IMPORT',
    TO_DATE('11/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0, '1')
;

-- Sperren
INSERT INTO T_SPERRE_VERTEILUNG
   (PROD_ID, ABTEILUNG_ID)
 VALUES
   (580, 3)
;

-- Standorttypen definieren
-- Standardprodukte / KVZ
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 580, 11001, 1, 'IMPORT', SYSDATE, 0);

-- Standardprodukte / HVT
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 580, 11000, 2, 'IMPORT', SYSDATE, 0);

-- ConnectDSL-Produkte / NK
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 580, 11004, 3, 'IMPORT', SYSDATE, 0);


-- Produktmapping
-- SIP-Trunk
INSERT INTO T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 VALUES
   (580, 580, 580, 'sip-trunk', 0)
;


-- Technische Leistung anlegen
insert into T_TECH_LEISTUNG (ID, NAME, EXTERN_LEISTUNG__NO, TYP, STR_VALUE,
                             PROD_NAME_STR, DESCRIPTION,
                             GUELTIG_VON, GUELTIG_BIS)
    VALUES (470, 'SIP_TRUNK_VOIP', 32000, 'VOIP_PROFIL', null,
            ' ', 'VOIP-Profil für Sip-Trunk',
            to_date('01.11.2013', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'))
;

-- Mapping Produkt-Technische Leistung
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 580, 470, 0, 1)
;

