INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE)
    VALUES (75,'Beim Kunden prüfen',0,'0','0',null,'1',null);
INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE)
    VALUES (76,'Totalausfall',0,'0','0',null,'1',null);
INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE)
    VALUES (77,'MDU / Baugruppe tauschen',0,'0','0',null,'1',null);
INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE)
    VALUES (78,'Bandbreitenprobleme',0,'0','0',null,'1',null);
INSERT INTO T_BA_VERL_ANLASS (ID,NAME,BA_VERL_GRUPPE,IS_CONFIGURABLE,IS_AUFTRAGSART,POSITION_NO,AKT,CPS_SO_TYPE)
    VALUES (79,'Spezielle Messung notwendig',0,'0','0',null,'1',null);
