alter table T_FFM_PRODUCT_MAPPING modify (PROD_ID NULL);
alter table T_FFM_PRODUCT_MAPPING modify (BA_ANLASS_ID NULL);

delete from T_FFM_QUALIFICATION;
delete from T_FFM_PRODUCT_MAPPING;

-- HVT
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 11000, 'RTL_Neu_MK_HVT', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11000;


-- 11002	RTL_Neu_MK_FttB	45	TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT	Endkundenservice FTTB
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 11002, 'RTL_Neu_MK_FttB', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTB'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11002;


-- 11011	RTL_Neu_MK_FttH	90	TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT	Endkundenservice FTTH
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 11011, 'RTL_Neu_MK_FttH', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11011;


-- 11013	RTL_Neu_MK_FttC	90	TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT	Endkundenservice FTTC
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 11013, 'RTL_Neu_MK_FttC', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTC'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11013;


-- 11017	RTL_Neu_MK_FTTB_H	45	TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT	Endkundenservice FTTB_H
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 11017, 'RTL_Neu_MK_FTTB_H', 45, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice FTTB_H'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11017;


-- 110	70		RTL_Int	240	HEADER_ONLY_WITHOUT_TIMESLOT	Interne Arbeit
INSERT INTO T_FFM_PRODUCT_MAPPING (ID, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
  values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 110, 70, 'RTL_Int', 240, 'HEADER_ONLY_WITHOUT_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Interne Arbeit'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 110;
