-- ANF-368: Neue Tabelle fuer SIP Peering Partner
CREATE TABLE T_SIP_PEERING_PARTNER (
  ID NUMBER(19, 0) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(64 CHAR) NOT NULL,
  IS_ACTIVE CHAR(1 CHAR) DEFAULT '1' NOT NULL,
  VERSION NUMBER(19, 0) NOT NULL
);

ALTER TABLE T_SIP_PEERING_PARTNER ADD CONSTRAINT UK_SIP_PP_NAME UNIQUE (NAME);

GRANT SELECT, INSERT, UPDATE ON T_SIP_PEERING_PARTNER TO R_HURRICAN_USER;
GRANT SELECT ON T_SIP_PEERING_PARTNER TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_SIP_PEERING_PARTNER_0;
GRANT SELECT ON S_T_SIP_PEERING_PARTNER_0 TO PUBLIC;


-- Neue Tabelle fuer die SBC(Session Border Controller) IP Sets
CREATE TABLE T_SIP_SBC_IP_SET (
  ID NUMBER(19, 0) PRIMARY KEY NOT NULL,
  SIP_PP_ID NUMBER (19, 0) NOT NULL,
  GUELTIG_VON timestamp NOT NULL,
  GUELTIG_BIS timestamp NOT NULL,
  VERSION NUMBER(19, 0) NOT NULL
);

ALTER TABLE T_SIP_SBC_IP_SET ADD CONSTRAINT FK_SIP_SBC_IP_2_PP FOREIGN KEY (SIP_PP_ID) REFERENCES T_SIP_PEERING_PARTNER (ID);

GRANT SELECT, INSERT, UPDATE ON T_SIP_SBC_IP_SET TO R_HURRICAN_USER;
GRANT SELECT ON T_SIP_SBC_IP_SET TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_SIP_SBC_IP_SET_0;
GRANT SELECT ON S_T_SIP_SBC_IP_SET_0 TO PUBLIC;


-- Neue Tabelle fuer die SBC(Session Border Controller) IP Adressen
CREATE TABLE T_SIP_SBC_IP (
  ID NUMBER(19, 0) PRIMARY KEY NOT NULL,
  SIP_SBC_IP_SET_ID NUMBER (19, 0) NOT NULL,
  IP_ADDRESS_ID NUMBER (19, 0) NOT NULL,
  VERSION NUMBER(19, 0) NOT NULL
);

ALTER TABLE T_SIP_SBC_IP ADD CONSTRAINT FK_SIP_SBC_IP_2_SET FOREIGN KEY (SIP_SBC_IP_SET_ID) REFERENCES T_SIP_SBC_IP_SET (ID);
ALTER TABLE T_SIP_SBC_IP ADD CONSTRAINT FK_SIP_SBC_IP_2_IP_ADDR FOREIGN KEY (IP_ADDRESS_ID) REFERENCES T_IP_ADDRESS (ID);

GRANT SELECT, INSERT, UPDATE ON T_SIP_SBC_IP TO R_HURRICAN_USER;
GRANT SELECT ON T_SIP_SBC_IP TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_SIP_SBC_IP_0;
GRANT SELECT ON S_T_SIP_SBC_IP_0 TO PUBLIC;
