-- SBC IP ohne ID und mit PK ueber SIP_SBC_IP_SET_ID	und IP_ADDRESS_ID
ALTER TABLE T_SIP_SBC_IP DROP PRIMARY KEY DROP INDEX;
ALTER TABLE T_SIP_SBC_IP DROP COLUMN ID;
ALTER TABLE T_SIP_SBC_IP DROP COLUMN VERSION;
DROP SEQUENCE S_T_SIP_SBC_IP_0;
