ALTER TABLE T_FFM_PRODUCT_MAPPING drop constraint CK_FFMPRODMAP_AGGSTRATEGY;

ALTER TABLE T_FFM_PRODUCT_MAPPING ADD (
  CONSTRAINT CK_FFMPRODMAP_AGGSTRATEGY
  CHECK (AGGREGATION_STRATEGY IN (
    'HEADER_ONLY_WITHOUT_TIMESLOT',
    'HOUSING',
    'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT',
    'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT'
  )));

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE,
    FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 370, null, 'RTL_Hou', 240, 'HOUSING');

INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT
    ffm.ID,
    S_T_FFM_QUALIFICATION_0.nextVal,
    'Endkundenservice Housing'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 370;

