-- T_SIP_SBC_IP und T_SIP_SBC_IP_SET benoetigen Delete Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SIP_SBC_IP_SET TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SIP_SBC_IP TO R_HURRICAN_USER;
