Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 370, 13, 'RTL_Kündigungen', 30, 'HOUSING');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Housing'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 370 and BA_ANLASS_ID=13;


-- 101 / AK-phone appartement
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 101, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
 INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 101 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 101, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 101 and BA_ANLASS_ID=13;

-- 451      Connect-LAN
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 451, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 451 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 451, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 451 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 451 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 451, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 451 and BA_ANLASS_ID=13;


-- 455      Direct Access
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 455, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 455 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 455, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 455 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 455 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 455, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 455 and BA_ANLASS_ID=13;


-- 460      ConnectDSL SDSL
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 460, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 460 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 460, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 460 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 460 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 460, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 460 and BA_ANLASS_ID=13;


-- 338  ISDN PMX
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 338, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'PMX'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 338 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 338, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'PMX'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 338 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 338 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 338, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'PMX'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 338 and BA_ANLASS_ID=13;


-- 450      Connect
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 450, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 450 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 450, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 450 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 450 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 450, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 450 and BA_ANLASS_ID=13;


-- 443      PMX Leitung
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 443, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 443 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 443, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 443 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 443 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 443, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 443 and BA_ANLASS_ID=13;


-- 452      MetroEthernet
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 452, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 452 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 452, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 452 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 452 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 452, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 452 and BA_ANLASS_ID=13;



-- 441      M-net Partner L2TP VPN
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 441, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 441 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 441, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 441 and BA_ANLASS_ID=13;



-- 456      Connect Zusatzleitung
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 456, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 456 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 456, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 456 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 456 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 456, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 456 and BA_ANLASS_ID=13;


--462      Connect Basic
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 462, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 462 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 462, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 462 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 462 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 462, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 462 and BA_ANLASS_ID=13;


--3        AK-phone ISDN S2M P
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 3, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'PMX'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 3 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 3, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'PMX'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 3 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 3 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 3, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'PMX'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 3 and BA_ANLASS_ID=13;


--453      Dark Fiber
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 453, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 453 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 453, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 453 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 453 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 453, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 453 and BA_ANLASS_ID=13;


--25,26,39,42,47,48      AK-connect
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 25, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 25 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 25, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 25 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 25 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 25, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 25 and BA_ANLASS_ID=13;

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 26, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 26 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 26, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 26 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 26 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 26, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 26 and BA_ANLASS_ID=13;

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 39, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 39 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 39, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 39 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 39 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 39, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 39 and BA_ANLASS_ID=13;

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 42, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 42 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 42, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 42 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 42 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 42, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 42 and BA_ANLASS_ID=13;

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 47, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 47 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 47, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 47 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 47 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 47, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 47 and BA_ANLASS_ID=13;

Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 48, null, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 48 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 48, 11000, 'RTL_NEU_IK', 240, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 48 and STANDORT_TYP=11000;
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 48 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 48, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Connect'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 48 and BA_ANLASS_ID=13;



-- RTL_sonstige (Duration: 60)
-- 570    Maxi FTTH Wohnheim
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 570, 11011, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 570 and STANDORT_TYP=11011;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 570, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 570 and BA_ANLASS_ID=13;

--521    TV Signallieferung
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 521, null, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'TV'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 521 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 521, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'TV'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 521 and BA_ANLASS_ID=13;

--444    VPN IPSec Site-to-Site
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 444, null, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 444 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 444, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'VPN'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 444 and BA_ANLASS_ID=13;

--40     AK-intern Trail
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 40, null, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 40 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 40, 11000, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 40 and STANDORT_TYP=11000;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 40, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 40 and BA_ANLASS_ID=13;

--471    UMTS Backup
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 471, null, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 471 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 471, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 471 and BA_ANLASS_ID=13;

--454    DarkCopper
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 454, null, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 454 and BA_ANLASS_ID is null;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 454, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Sonstiges'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 454 and BA_ANLASS_ID=13;

--520    FTTH Infrastruktur
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 520, 11011, 'RTL_sonstige', 60, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 520 and STANDORT_TYP = 11011;
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, PROD_ID, BA_ANLASS_ID, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 520, 13, 11011, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.PROD_ID = 520 and BA_ANLASS_ID=13;



-- Default Konfigurationen fuer Kuendigung
Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11000, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 10000 and BA_ANLASS_ID=13;


Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11002, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTB'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11002 and BA_ANLASS_ID=13;


Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11011, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTH'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11011 and BA_ANLASS_ID=13 and prod_id is null;


Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11013, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTC'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11013 and BA_ANLASS_ID=13 and prod_id is null;


Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION, AGGREGATION_STRATEGY)
 Values (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11017, 13, 'RTL_Kündigungen', 30, 'TECHNICAL_PARAMS_INCLUDED_WITH_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice FTTB_H'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11017 and BA_ANLASS_ID=13;
