Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION,
    AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11001, 'RTL_Neu_MK_HVT', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11001 and BA_ANLASS_ID is null and prod_id is null;


Insert into T_FFM_PRODUCT_MAPPING
   (ID, VERSION, STANDORT_TYP, BA_ANLASS_ID, FFM_ACTIVITY_TYPE, FFM_PLANNED_DURATION,
    AGGREGATION_STRATEGY)
 Values
   (S_T_FFM_PRODUCT_MAPPING_0.nextVal, 0, 11001, 13, 'RTL_Kündigungen', 90, 'TECHNICAL_PARAMS_INCLUDED_WITH_FIXED_TIMESLOT');
INSERT INTO T_FFM_QUALIFICATION (FFM_PRODUCT_MAPPING_ID, ID, FFM_QUALIFICATION)
  SELECT ffm.ID, S_T_FFM_QUALIFICATION_0.nextVal, 'Endkundenservice HVT'
  FROM T_FFM_PRODUCT_MAPPING ffm
  WHERE ffm.STANDORT_TYP = 11001 and BA_ANLASS_ID=13 and prod_id is null;


update T_FFM_QUALIFICATION set FFM_QUALIFICATION='Sonstige' where FFM_QUALIFICATION='Sonstiges';


update T_FFM_PRODUCT_MAPPING set FFM_ACTIVITY_TYPE='RTL_K'||UNISTR('\00FC')||'ndigungen' where FFM_ACTIVITY_TYPE like 'RTL_K%ndigungen';
