CREATE TABLE T_AUFTRAG_2_PEERING_PARTNER (
  ID NUMBER(19, 0) PRIMARY KEY NOT NULL,
  AUFTRAG_ID NUMBER(19, 0) NOT NULL,
  PEERING_PARTNER_ID NUMBER(19, 0) NOT NULL,
  GUELTIG_VON timestamp NOT NULL,
  GUELTIG_BIS timestamp NOT NULL,
  VERSION NUMBER(19, 0) NOT NULL
);

ALTER TABLE T_AUFTRAG_2_PEERING_PARTNER ADD CONSTRAINT FK_AUFTRAG_2_PP_PPID FOREIGN KEY (PEERING_PARTNER_ID) REFERENCES T_SIP_PEERING_PARTNER (ID);
ALTER TABLE T_AUFTRAG_2_PEERING_PARTNER ADD CONSTRAINT FK_AUFTRAG_2_PP_AUFTRAG_ID FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

CREATE INDEX IX_AUFTRAG2PP_AID ON T_AUFTRAG_2_PEERING_PARTNER (AUFTRAG_ID);
CREATE INDEX IX_AUFTRAG2PP_PPID ON T_AUFTRAG_2_PEERING_PARTNER (PEERING_PARTNER_ID);

GRANT SELECT, INSERT, UPDATE ON T_AUFTRAG_2_PEERING_PARTNER TO R_HURRICAN_USER;
GRANT SELECT ON T_AUFTRAG_2_PEERING_PARTNER TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_AUFTRAG_2_PP_0;
GRANT SELECT ON S_T_AUFTRAG_2_PP_0 TO PUBLIC;
