-- script to export the FFM qualifications to a separate entity table

-- modify former table to mapping table
RENAME T_FFM_QUALIFICATION TO T_FFM_PRODMAP_2_QUALIFICATION;
DROP SEQUENCE S_T_FFM_QUALIFICATION_0;
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION DROP CONSTRAINT UQ_FFM_QUALIFICATION;
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION ADD FFM_QUALIFICATION_ID NUMBER(19, 0);

-- new table
CREATE TABLE T_FFM_QUALIFICATION (
  id                  NUMBER(19, 0)           NOT NULL,
  VERSION             NUMBER(19, 0) DEFAULT 0 NOT NULL,
  QUALIFICATION       VARCHAR2(100)           NOT NULL,
  ADDITIONAL_DURATION NUMBER(19, 0)           NULL,
  PRIMARY KEY (id)
);
ALTER TABLE T_FFM_QUALIFICATION ADD CONSTRAINT UQ_FFM_QUALIFICATIONS UNIQUE (QUALIFICATION);
GRANT SELECT, INSERT, UPDATE, DELETE ON T_FFM_QUALIFICATION TO R_HURRICAN_USER;
GRANT SELECT ON T_FFM_QUALIFICATION TO R_HURRICAN_READ_ONLY;

-- sequence
CREATE SEQUENCE S_T_FFM_QUALIFICATION_0;
GRANT SELECT ON S_T_FFM_QUALIFICATION_0 TO PUBLIC;

-- insert current values
INSERT INTO T_FFM_QUALIFICATION (ID, VERSION, QUALIFICATION)
  SELECT
    S_T_FFM_QUALIFICATION_0.nextval,
    0,
    q.FFM_QUALIFICATION
  FROM (SELECT DISTINCT FFM_QUALIFICATION
        FROM T_FFM_PRODMAP_2_QUALIFICATION) q;

-- replace string values with IDs
UPDATE T_FFM_PRODMAP_2_QUALIFICATION mapping
SET FFM_QUALIFICATION_ID = (
  SELECT quali.ID
  FROM T_FFM_QUALIFICATION quali
  WHERE quali.QUALIFICATION = mapping.FFM_QUALIFICATION
);
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION MODIFY FFM_QUALIFICATION_ID NOT NULL;
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION ADD CONSTRAINT FK_FFM_PRODMAP_2_FFM_QUALI FOREIGN KEY (FFM_QUALIFICATION_ID) REFERENCES T_FFM_QUALIFICATION (ID);

--clean up the table
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION DROP COLUMN FFM_QUALIFICATION;
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION DROP COLUMN ID;
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION DROP COLUMN VERSION;
ALTER TABLE T_FFM_PRODMAP_2_QUALIFICATION ADD CONSTRAINT PK_FFM_PRODMAP_QUALI_ID PRIMARY KEY (FFM_QUALIFICATION_ID, FFM_PRODUCT_MAPPING_ID);
