Insert into T_FFM_QUALIFICATION (ID, VERSION, QUALIFICATION, ADDITIONAL_DURATION)
 Values (S_T_FFM_QUALIFICATION_0.nextVal, 0, 'Inhousverkabelung', NULL);
update T_TECH_LEISTUNG set
   FFM_QUALIFICATION_ID=(select q.ID from T_FFM_QUALIFICATION q where QUALIFICATION='Inhousverkabelung')
 where ID=602;

Insert into T_FFM_QUALIFICATION (ID, VERSION, QUALIFICATION, ADDITIONAL_DURATION)
 Values (S_T_FFM_QUALIFICATION_0.nextVal, 0, 'VOIP-TK', 60);
update T_TECH_LEISTUNG set
   FFM_QUALIFICATION_ID=(select q.ID from T_FFM_QUALIFICATION q where QUALIFICATION='VOIP-TK')
 where ID=301;