create table T_IA_LEVEL1 (
   ID NUMBER(19,0) not null,
   VERSION NUMBER(19,0) default 0 not null,
   NAME VARCHAR2(50) not null,
   PRIMARY KEY (ID)
);

ALTER TABLE T_IA_LEVEL1 ADD CONSTRAINT UQ_IA_LEVEL1 UNIQUE (NAME);
GRANT SELECT, INSERT, UPDATE, DELETE ON T_IA_LEVEL1 TO R_HURRICAN_USER;
GRANT SELECT ON T_IA_LEVEL1 TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_IA_LEVEL1_0;
GRANT SELECT ON S_T_IA_LEVEL1_0 TO PUBLIC;


create table T_IA_LEVEL2 (
   ID NUMBER(19,0) not null,
   VERSION NUMBER(19,0) default 0 not null,
   LEVEL1_ID NUMBER(19,0) not null,
   NAME VARCHAR2(50) not null,
   PRIMARY KEY (ID)
);

ALTER TABLE T_IA_LEVEL2 ADD CONSTRAINT FK_IALEVEL1_2_LEVEL2 FOREIGN KEY (LEVEL1_ID) REFERENCES T_IA_LEVEL1 (ID);
ALTER TABLE T_IA_LEVEL2 ADD CONSTRAINT UQ_IA_LEVEL2 UNIQUE (NAME);
GRANT SELECT, INSERT, UPDATE, DELETE ON T_IA_LEVEL2 TO R_HURRICAN_USER;
GRANT SELECT ON T_IA_LEVEL2 TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_IA_LEVEL2_0;
GRANT SELECT ON S_T_IA_LEVEL2_0 TO PUBLIC;




create table T_IA_LEVEL3 (
   ID NUMBER(19,0) not null,
   VERSION NUMBER(19,0) default 0 not null,
   LEVEL2_ID NUMBER(19,0) not null,
   NAME VARCHAR2(50) not null,
   PRIMARY KEY (ID)
);

ALTER TABLE T_IA_LEVEL3 ADD CONSTRAINT FK_IALEVEL2_2_LEVEL3 FOREIGN KEY (LEVEL2_ID) REFERENCES T_IA_LEVEL2 (ID);
ALTER TABLE T_IA_LEVEL3 ADD CONSTRAINT UQ_IA_LEVEL3 UNIQUE (NAME);
GRANT SELECT, INSERT, UPDATE, DELETE ON T_IA_LEVEL3 TO R_HURRICAN_USER;
GRANT SELECT ON T_IA_LEVEL3 TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_IA_LEVEL3_0;
GRANT SELECT ON S_T_IA_LEVEL3_0 TO PUBLIC;
