ALTER TABLE T_IA_LEVEL3 RENAME COLUMN LEVEL2_ID to LEVEL3_ID;
ALTER TABLE T_IA_LEVEL3 RENAME CONSTRAINT FK_IALEVEL2_2_LEVEL3 TO FK_IALEVEL3_2_LEVEL5;
ALTER TABLE T_IA_LEVEL3 RENAME CONSTRAINT UQ_IA_LEVEL3 TO UQ_IA_LEVEL5;
RENAME T_IA_LEVEL3 TO T_IA_LEVEL5;
RENAME S_T_IA_LEVEL3_0 TO S_T_IA_LEVEL5_0;

ALTER TABLE T_IA_LEVEL2 RENAME CONSTRAINT FK_IALEVEL1_2_LEVEL2 TO FK_IALEVEL1_2_LEVEL3;
ALTER TABLE T_IA_LEVEL2 RENAME CONSTRAINT UQ_IA_LEVEL2 TO UQ_IA_LEVEL3;
RENAME T_IA_LEVEL2 TO T_IA_LEVEL3;
RENAME S_T_IA_LEVEL2_0 TO S_T_IA_LEVEL3_0;

ALTER TABLE T_IA RENAME COLUMN IA_LEVEL2 to IA_LEVEL5;
