-- Positionen von Column Level3 und Level5 vertauscht
ALTER TABLE T_IA RENAME COLUMN IA_LEVEL5 to IA_LEVEL2;
ALTER TABLE T_IA RENAME COLUMN IA_LEVEL3 to IA_LEVEL5;
ALTER TABLE T_IA RENAME COLUMN IA_LEVEL2 to IA_LEVEL3;
