--update or insert the new konfig
CREATE OR REPLACE PROCEDURE ADD_FFM_QUALIFICATION
  (quali_name IN VARCHAR2, duration IN NUMBER)
IS
  BEGIN
    UPDATE T_FFM_QUALIFICATION
    SET ADDITIONAL_DURATION = duration
    WHERE ID = (SELECT sub.ID
                FROM T_FFM_QUALIFICATION sub
                WHERE sub.QUALIFICATION = quali_name);
    IF (SQL%NOTFOUND)
    THEN
      INSERT INTO T_FFM_QUALIFICATION (ID, VERSION, QUALIFICATION, ADDITIONAL_DURATION)
      VALUES (S_T_FFM_QUALIFICATION_0.nextval, 0, quali_name, duration);
    END IF;
  END;
/

CALL ADD_FFM_QUALIFICATION('Endkundenservice FTTB', NULL);
CALL ADD_FFM_QUALIFICATION('Endkundenservice FTTC', NULL);
CALL ADD_FFM_QUALIFICATION('Endkundenservice FTTH', NULL);
CALL ADD_FFM_QUALIFICATION('Endkundenservice HVT', NULL);
CALL ADD_FFM_QUALIFICATION('Endkundenservice GEWOFAG', NULL);
CALL ADD_FFM_QUALIFICATION('SDSL', 60);
CALL ADD_FFM_QUALIFICATION('SIP Trunk', 45);
CALL ADD_FFM_QUALIFICATION('Connect', NULL);
CALL ADD_FFM_QUALIFICATION('VPN', 60);
CALL ADD_FFM_QUALIFICATION('PMX', -180);
CALL ADD_FFM_QUALIFICATION('TV', NULL);
CALL ADD_FFM_QUALIFICATION('Housing', NULL);
CALL ADD_FFM_QUALIFICATION('SIP Trunk Access', NULL);
CALL ADD_FFM_QUALIFICATION('VOIP-TK', 60);
CALL ADD_FFM_QUALIFICATION('Installationsservice', 20);
CALL ADD_FFM_QUALIFICATION('Inhousverkabelung', NULL);

DROP PROCEDURE ADD_FFM_QUALIFICATION;

