ALTER TABLE T_BA_ZUSATZ ADD STANDORT_TYP_REF_ID NUMBER(19, 0);
ALTER TABLE T_BA_ZUSATZ ADD CONSTRAINT FK_BA_ZUSATZ_2_REF_STD_TYP FOREIGN KEY (STANDORT_TYP_REF_ID) REFERENCES T_REFERENCE (ID);

ALTER TABLE T_BA_ZUSATZ ADD CONSTRAINT BA_ZUSATZ_HVT_GRP_OR_STD_TYP CHECK (HVT_GRUPPE_ID IS NULL OR STANDORT_TYP_REF_ID IS NULL);