update T_IA set IA_LEVEL5 = null, IA_LEVEL3 = null, IA_LEVEL1 = null;
ALTER TABLE T_IA MODIFY (IA_LEVEL1 NUMBER(19,0));
ALTER TABLE T_IA MODIFY (IA_LEVEL3 NUMBER(19,0));
ALTER TABLE T_IA MODIFY (IA_LEVEL5 NUMBER(19,0));
