ALTER TABLE T_IA drop COLUMN IA_LEVEL1;
ALTER TABLE T_IA drop COLUMN IA_LEVEL3;
ALTER TABLE T_IA drop COLUMN IA_LEVEL5;

ALTER TABLE T_IA ADD (IA_LEVEL1 VARCHAR2(50 BYTE));
ALTER TABLE T_IA ADD (IA_LEVEL1_ID VARCHAR2(50 BYTE));
ALTER TABLE T_IA ADD (IA_LEVEL3 VARCHAR2(50 BYTE));
ALTER TABLE T_IA ADD (IA_LEVEL3_ID VARCHAR2(50 BYTE));
ALTER TABLE T_IA ADD (IA_LEVEL5 VARCHAR2(50 BYTE));
ALTER TABLE T_IA ADD (IA_LEVEL5_ID VARCHAR2(50 BYTE));
