ALTER TABLE T_IA_LEVEL1 MODIFY (SAP_ID VARCHAR2(50) NOT NULL);
ALTER TABLE T_IA_LEVEL1 ADD CONSTRAINT UQ_IA_LEVEL1_SAPID UNIQUE (SAP_ID);

ALTER TABLE T_IA_LEVEL3 MODIFY (SAP_ID VARCHAR2(50) NOT NULL);
ALTER TABLE T_IA_LEVEL3 ADD CONSTRAINT UQ_IA_LEVEL3_SAPID UNIQUE (SAP_ID);

ALTER TABLE T_IA_LEVEL5 MODIFY (SAP_ID VARCHAR2(50) NOT NULL);
ALTER TABLE T_IA_LEVEL5 ADD CONSTRAINT UQ_IA_LEVEL5_SAPID UNIQUE (SAP_ID);
