-- add dslam types to t_reference table
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) values (23306, 'HW_DSLAM_TYPE', 'MA5600v3', '1', 10, 'HW-Typ DSLAM');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) values (23307, 'HW_DSLAM_TYPE', 'MA5600T', '1', 20, 'HW-Typ DSLAM');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) values (23308, 'HW_DSLAM_TYPE', 'MA5603T', '1', 30, 'HW-Typ DSLAM');
