-- physiktyp 'FTTB_DPO_VDSL2'
UPDATE T_PHYSIKTYP SET MAX_BANDWIDTH_UPSTREAM = 100000 WHERE ID = 809;

-- DPO baugruppen
UPDATE T_HW_BAUGRUPPEN_TYP SET MAX_BANDWIDTH_UPSTREAM = 100000 WHERE HW_TYPE_NAME = 'DPO';