INSERT INTO T_PRODUKT
(PROD_ID, PRODUKTGRUPPE_ID, ANSCHLUSSART, AKTIONS_ID, MAX_DN_COUNT,
 DN_BLOCK, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
 BRAUCHT_BUENDEL, ELVERLAUF, ENDSTELLEN_TYP, LI_NR, VPN_PHYSIK,
 PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE,
 EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT, VERTEILUNG_DURCH, BA_RUECKLAEUFER, VERLAUF_CHAIN_ID,
 VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
 TDN_USE_FROM_MASTER, VIER_DRAHT, VERSION, MIN_DN_COUNT, CPS_IP_DEFAULT,
 CPS_MULTI_DRAHT, IP_POOL, IP_PURPOSE_V4, IP_PURPOSE_V4_EDITABLE, IP_NETMASK_SIZE_V4,
 IP_NETMASK_SIZE_V6, IP_NETMASK_SIZE_EDITABLE, AUTOMATION_POSSIBLE, GEOID_SRC, AUTO_HVT_ZUORDNUNG,
 SMS_VERSAND, BUENDEL_BILLING_HAUPTAUFTRAG, SEND_STATUS_UPDATE)
VALUES
  (98, 4, 'SDSL n-Draht Option FTTC', 1, 0,
   '0', TO_DATE('01/01/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
   TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1',
   '0', '1', 1, 2, '1',
   '0', '0', '0', '0', '0',
   '0', '0', 4, '1', 30,
   15, '1', '0', '0', '1',
   '1', '1', 6, 0, '0',
   '0', 1, 22371, '1', 32,
   64, '0', '0', 'HVT', '1',
   '0', '0', '1');

INSERT INTO T_PRODUKT_2_PHYSIKTYP
(ID, PROD_ID, PHYSIKTYP, VERSION, PRIORITY,
 USE_IN_RANG_MATRIX)
VALUES
  (S_T_PRODUKT_2_PHYSIKTYP_0.nextval, 98, 804, 0, NULL,
   '1');

INSERT INTO T_PRODUKT_2_SCHNITTSTELLE
(PROD_ID, SCHNITTSTELLE_ID)
VALUES
  (98, 38);

INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE
(ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW,
 DATEW, VERSION)
VALUES
  (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextval, 98, 11013, 1, 'Release 18',
   TO_DATE('01/01/2015 10:52:57', 'MM/DD/YYYY HH24:MI:SS'), 0);

INSERT INTO T_PRODUKT_MAPPING
(MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
VALUES
  (98, 98, 98, 'sdsl_sub', 0);


CREATE OR REPLACE PROCEDURE reports_for_ndraht_fttc
IS
  BEGIN
    FOR report_id IN (SELECT DISTINCT rep_id
                      FROM T_REPORT_2_PROD
                      WHERE prod_id IN (99, 541)) LOOP
      INSERT INTO T_REPORT_2_PROD
      (ID, REP_ID, PROD_ID, VERSION)
      VALUES
        (S_T_REPORT_2_PROD_0.nextval, report_id.rep_id, 98, 0);
    END LOOP;
  END;
/
CALL reports_for_ndraht_fttc();
DROP PROCEDURE reports_for_ndraht_fttc;


CREATE OR REPLACE PROCEDURE rangmatrix_dslvoip_adsl2plus_h(physiktyp_id IN NUMBER, prio IN NUMBER)
IS
  BEGIN
    FOR uevtid IN (SELECT
                     UEVT.UEVT_ID,
                     hvt.HVT_ID_STANDORT
                   FROM T_UEVT uevt
                     JOIN T_HVT_STANDORT hvt ON (uevt.HVT_ID_STANDORT = hvt.HVT_ID_STANDORT)
                     JOIN T_REFERENCE refer ON (REFER.ID = hvt.STANDORT_TYP_REF_ID)
                   WHERE REFER.STR_VALUE IN ('KVZ')) LOOP
      INSERT INTO T_RANGIERUNGSMATRIX matrix
      (ID, PROD_ID, UEVT_ID, PRODUKT2PHYSIKTYP_ID, PRIORITY, HVT_STANDORT_ID_ZIEL, PROJEKTIERUNG, GUELTIG_VON, GUELTIG_BIS, BEARBEITER)
      VALUES
        (S_T_RANGIERUNGSMATRIX_0.NEXTVAL, 98, uevtid.UEVT_ID,
         (SELECT prod_2_physik.ID
          FROM T_PRODUKT_2_PHYSIKTYP prod_2_physik
          WHERE PROD_2_PHYSIK.PROD_ID = 98
                AND PROD_2_PHYSIK.PHYSIKTYP = physiktyp_id
                AND PARENTPHYSIKTYP_ID IS NULL),
         prio, uevtid.hvt_id_standort, NULL, to_date('01/01/2015', 'DD/MM/YYYY'), to_date('01/01/2200', 'DD/MM/YYYY'),
         'Import');
    END LOOP;
  END;
/
CALL rangmatrix_dslvoip_adsl2plus_h(804, 10);
DROP PROCEDURE rangmatrix_dslvoip_adsl2plus_h;
