ALTER TABLE T_PRODUKT drop constraint T_PRODUKT_SDSL_N_DRAHT;

ALTER TABLE T_PRODUKT modify SDSL_N_DRAHT VARCHAR2(20);

ALTER TABLE T_PRODUKT ADD
  CONSTRAINT T_PRODUKT_SDSL_N_DRAHT
  CHECK (SDSL_N_DRAHT IN ('ZWEI', 'VIER', 'ACHT', 'OPTIONAL_BONDING'));

update T_PRODUKT set SDSL_N_DRAHT='OPTIONAL_BONDING' where PROD_ID=541;
