ALTER TABLE T_FFM_QUALIFICATION_MAPPING drop CONSTRAINT CK_FFM_QUALMAP_IDS;

ALTER TABLE T_FFM_QUALIFICATION_MAPPING ADD CONSTRAINT CK_FFM_QUALMAP_IDS
CHECK (
     (PRODUCT_ID IS NOT NULL AND TECH_LEISTUNG_ID IS NULL and STANDORT_REF_ID IS NULL)
  OR (TECH_LEISTUNG_ID IS NOT NULL AND PRODUCT_ID IS NULL AND STANDORT_REF_ID IS NULL)
  OR (STANDORT_REF_ID IS NOT NULL AND PRODUCT_ID IS NULL AND TECH_LEISTUNG_ID IS NULL)
);