DELETE FROM T_FFM_PRODMAP_2_QUALIFICATION;

DELETE FROM T_FFM_PRODUCT_MAPPING pm WHERE pm.STANDORT_TYP IS NOT NULL AND pm.FFM_ACTIVITY_TYPE='RTL_NEU_IK' AND pm.BA_FFM_TYP='NEU'
AND pm.PROD_ID IN (3, 25, 26, 39, 42, 47, 48, 338, 443, 450, 451, 452, 453, 455, 456, 460, 462);

DELETE FROM T_FFM_PRODUCT_MAPPING pm WHERE pm.STANDORT_TYP IS NOT NULL AND pm.FFM_ACTIVITY_TYPE='RTL_sonstige' AND pm.BA_FFM_TYP='NEU'
AND pm.PROD_ID IN (40);

DROP TABLE T_FFM_PRODMAP_2_QUALIFICATION;