-- neue Kombi-Leistung fuer 10 MBit/VoIP/IPv6
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_LEISTUNG__NO, TYP, PROD_NAME_STR,
    DISPO, EWSD, SDH, IPS, SCT,
    SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION, PREVENT_AUTO_DISPATCH,
    DESCRIPTION)
 Values
   (499, '10/1_VOIP_IPv6', 10224, 'KOMBI', ' ',
    '0', '0', '0', '0', '0',
    '1', TO_DATE('01/03/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0, '0',
    'Kombi-Leistung, fuehrt zu 10 MBit, 1MBit, VOIP IPv6');


-- Kombi-Leistung fuer Produkte 513+514 anlegen
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 499, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 33, 499, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 22, 499, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 57, 499, '1', 0);

Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 499, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 33, 499, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 22, 499, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 Values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 57, 499, '1', 0);


-- 10/1 DSLAM-Profile den Produkten 513+514 zuordnen
delete from T_PROD_2_DSLAMPROFILE
  where PROD_ID in (513,514) and DSLAM_PROFILE_ID in
    (select d.ID from T_DSLAM_PROFILE d where d.DOWNSTREAM_TECH_LS = 33 AND d.UPSTREAM_TECH_LS = 22);

insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
  select 513, d.ID from T_DSLAM_PROFILE d where d.DOWNSTREAM_TECH_LS = 33 AND d.UPSTREAM_TECH_LS = 22;
insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
  select 514, d.ID from T_DSLAM_PROFILE d where d.DOWNSTREAM_TECH_LS = 33 AND d.UPSTREAM_TECH_LS = 22;


-- Rufnummernleistungen konfigurieren
Insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION, VERSION)
 Values (16, 88320, 3401, 'Surf+Fon Flat (10.000)', 0);

