-- wie in HUR-20945 gefordert
update T_FFM_PRODUCT_MAPPING set FFM_PLANNED_DURATION = 90 where FFM_ACTIVITY_TYPE = 'RTL_Neu_MK_FTTB_H';
update T_FFM_PRODUCT_MAPPING set FFM_PLANNED_DURATION = 45 where FFM_ACTIVITY_TYPE = 'RTL_Neu_MK_FttC';
update T_FFM_PRODUCT_MAPPING set FFM_PLANNED_DURATION = 45 where FFM_ACTIVITY_TYPE = 'RTL_Neu_MK_HVT';
