-- Dummy Subrack Typ
INSERT INTO T_HW_SUBRACK_TYP (BG_COUNT, DESCRIPTION, HW_TYPE_NAME,  ID, NAME, PORT_COUNT, RACK_TYP, VERSION)
VALUES ( 15, null, 'XDSL_MUC', S_T_HW_SUBRACK_TYP_0.nextval, 'VDSL_MA5600', 64, 'DSLAM', 0 );

-- Subracks anlegen
INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 625, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 645, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 642, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 641, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 631, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 634, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 626, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 632, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 635, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 640, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 662, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 663, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 664, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

INSERT INTO T_HW_SUBRACK (ID, MOD_NUMBER, RACK_ID,  SUBRACK_TYP_ID, VERSION)
VALUES ( S_T_HW_SUBRACK_0.nextval, '1-1', 665, (select ID from T_HW_SUBRACK_TYP where NAME = 'VDSL_MA5600'), 0 );

-- Subracks zuordnen
update T_HW_BAUGRUPPE bg set SUBRACK_ID = (select ID from T_HW_SUBRACK where RACK_ID = bg.rack_ID) where HW_BG_TYP_ID = 231;
