ALTER TABLE T_MWF_MELDUNG DROP CONSTRAINT CHK_EMAIL_STATUS;
ALTER TABLE T_MWF_MELDUNG
  ADD CONSTRAINT CHK_EMAIL_STATUS CHECK (
  EMAIL_STATUS IN
  ('OFFEN', 'GESENDET', 'KEINE_EMAIL', 'VERALTET', 'UNGUELTIG', 'UNERWUENSCHT', 'KEINE_CONFIG', 'FALSCHER_AUFTRAGSTATUS'));
