-- update E-Mail Betreff fuer  MELDUNG_TYP = 'ABM' und AENDERUNGSKENNZEICHEN=STANDARD
UPDATE T_SMS_CONFIG
SET EMAIL_BETREFF = 'Terminankündigung'
WHERE MELDUNG_TYP = 'ABM' AND AENDERUNGSKENNZEICHEN = 'STANDARD';
