ALTER TABLE T_HW_BAUGRUPPEN_TYP ADD (PORT_COUNT_OUT  NUMBER(9));

ALTER TABLE T_HW_RACK DROP CONSTRAINT CK_HW_RACK_TYP;

ALTER TABLE T_HW_RACK ADD (CONSTRAINT CK_HW_RACK_TYP CHECK (RACK_TYP IN ('DSLAM', 'DLU', 'ROUTER', 'LTG', 'UEVT', 'MDU', 'OLT', 'PDH', 'SDH')));


INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'LT22CM', 4, 2, 'SMXLS auf Steckplatz 206 - 209; OMX2S2 auf Steckplatz 202 - 217, ', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'LT2ME1', 2, 2, 'SMXLS auf Steckplatz 206 - 209; OMX2S2 auf Steckplatz 202 - 217, ', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'LT12CM', 4, 2, 'SMXLS auf Steckplatz 202 - 205; OMX16S auf Steckplatz 202, 203, 205 - 207, 209 - 211, 213 - 215 und 217', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'DSMX', 1, 16, 'OMX16S auf Steckplatz 202, 203, 205 - 207, 209 - 211, 213 - 215 und 217', '1', 'PDH', 'PDH', NULL);

 
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'QSTU', 4, 4, 'ULAFS auf Slot 01 - 16', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'STU4', 4, 4, 'ULAFS auf Slot 01 - 16', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'BSTU4', 4, 4, 'ULAFS auf Slot 01 - 16', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'BSTU', 2, 2, 'ULAFS auf Slot 01 - 16', '1', 'PDH', 'PDH', NULL);
