INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'A63E1', 63, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'Tr2M', 21, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'ES4-8FE', 8, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'DE1B32', 32, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'ADM1o/2Mb', 21, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'TC21E1', 21, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'A21E1', 21, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, PORT_COUNT_OUT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'ISA-ES1-8FE', 8, null, 'SDH Baugruppe', '1', 'SDH', 'SDH', NULL);
