-- Zusatz-Tabelle fuer Housing-Daten

create table T_AUFTRAG_HOUSING (
    ID NUMBER(10) NOT NULL
  , AUFTRAG_ID NUMBER(10) NOT NULL
  , GUELTIG_VON DATE NOT NULL
  , GUELTIG_BIS DATE NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_AUFTRAG_HOUSING ADD CONSTRAINT PK_T_AUFTRAG_HOUSING PRIMARY KEY (ID);

CREATE INDEX IX_FK_HOUSING_2_AUFTRAG ON T_AUFTRAG_HOUSING (AUFTRAG_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_AUFTRAG_HOUSING ADD CONSTRAINT FK_HOUSING_2_AUFTRAG
  FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);


create SEQUENCE S_T_AUFTRAG_HOUSING_0 start with 1;
grant select on S_T_AUFTRAG_HOUSING_0 to public;

GRANT SELECT ON T_AUFTRAG_HOUSING TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_AUFTRAG_HOUSING TO R_HURRICAN_USER;
