-- Legacy Felder aus der KuP
ALTER TABLE T_AUFTRAG_CONNECT ADD (TTS  VARCHAR2(100 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT ADD (VERFUEGBARKEIT  VARCHAR2(20 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT ADD (PRODUKTCODE  VARCHAR2(100 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT ADD (PRODUKTSPEZIFIKATION  VARCHAR2(500 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT ADD (PROJEKTLEITER  VARCHAR2(100 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT ADD (PROJEKTLEITER_KUENDIGUNG  VARCHAR2(100 BYTE));
