ALTER TABLE T_AUFTRAG_CONNECT MODIFY(PRODUKTCODE VARCHAR2(200 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT MODIFY(PRODUKTSPEZIFIKATION VARCHAR2(600 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT MODIFY(PROJEKTLEITER VARCHAR2(150 BYTE));
ALTER TABLE T_AUFTRAG_CONNECT MODIFY(PROJEKTLEITER_KUENDIGUNG VARCHAR2(150 BYTE));