-- Konfiguration fuer manuellen Rangierungsaufbau (Connect)

delete from t_produkt_eq_config where prod_id<500;

alter table T_PRODUKT_EQ_CONFIG add IS_RANGIERUNGSPART_DEFAULT CHAR(1);
alter table T_PRODUKT_EQ_CONFIG add IS_RANGIERUNGSPART_ADDITIONAL CHAR(1);
update t_produkt_eq_config set IS_RANGIERUNGSPART_DEFAULT='1' where PROD_ID<500;
update t_produkt_eq_config set IS_RANGIERUNGSPART_ADDITIONAL='0' where PROD_ID<500;

-- Produkt 450
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT Definition (DTAG Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 2, 'EQ_OUT', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 2, 'EQ_OUT', 'rangSchnittstelle', 'H', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 3, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 3, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 4, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 450, 4, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');

-- Produkt 451
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT Definition (DTAG Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 2, 'EQ_OUT', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 2, 'EQ_OUT', 'rangSchnittstelle', 'H', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 3, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 3, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 4, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 451, 4, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');

-- Produkt 452
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT Definition (DTAG Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 2, 'EQ_OUT', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 2, 'EQ_OUT', 'rangSchnittstelle', 'H', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 3, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 3, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 4, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 452, 4, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');

-- Produkt 453
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 453, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 453, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 453, 2, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 453, 2, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 453, 3, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 453, 3, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');

-- Produkt 454
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT Definition (DTAG Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 2, 'EQ_OUT', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 2, 'EQ_OUT', 'rangSchnittstelle', 'H', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 3, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 3, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 4, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 454, 4, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');

-- Produkt 455
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT Definition (DTAG Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 2, 'EQ_OUT', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 2, 'EQ_OUT', 'rangSchnittstelle', 'H', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 3, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 3, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 4, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 455, 4, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');

-- Produkt 456
-- EQ_IN Definition (ULAF bzw. OMX/SMX Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 1, 'EQ_IN', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 1, 'EQ_IN', 'hwSchnittstelle', 'PDH-IN', '1', '0');
-- EQ_OUT Definition (DTAG Port)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 2, 'EQ_OUT', 'status', 'frei', '1', '0');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 2, 'EQ_OUT', 'rangSchnittstelle', 'H', '1', '0');
-- EQ_OUT 2 Definition (Zwischenleiste)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 3, 'EQ_OUT', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 3, 'EQ_OUT', 'hwSchnittstelle', 'PDH-OUT', '0', '1');
-- EQ_IN 2 Definition (SDH)
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 4, 'EQ_IN', 'status', 'frei', '0', '1');
insert into T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
  values (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 456, 4, 'EQ_IN', 'hwSchnittstelle', 'SDH', '0', '1');
