INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 VALUES (9507, 'HW_RACK_TYPE', 'SDH', NULL, NULL, NULL, '1', 70, 'HW-Rack Typ SDH.', 0);

INSERT INTO T_REFERENCE (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 VALUES (9508, 'HW_RACK_TYPE', 'PDH', NULL, NULL, NULL, '1', 80, 'HW-Rack Typ PDH.', 0);
