CREATE TABLE T_HW_RACK_SDH
(
  RACK_ID  NUMBER(9)                            NOT NULL
) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING;

ALTER TABLE T_HW_RACK_SDH ADD (CONSTRAINT T_HW_RACK_SDH_PK PRIMARY KEY (RACK_ID));

ALTER TABLE T_HW_RACK_SDH ADD (CONSTRAINT FK_HW_RACK_SDH_HW_RACK 
 FOREIGN KEY (RACK_ID) REFERENCES T_HW_RACK (ID) DEFERRABLE INITIALLY IMMEDIATE);

grant select on T_HW_RACK_SDH to R_HURRICAN_READ_ONLY;
grant select, insert, update on T_HW_RACK_SDH to R_HURRICAN_USER;
 
CREATE TABLE T_HW_RACK_PDH
(
  RACK_ID  NUMBER(9)                            NOT NULL
) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING;

ALTER TABLE T_HW_RACK_PDH ADD (CONSTRAINT T_HW_RACK_PDH_PK PRIMARY KEY (RACK_ID));

ALTER TABLE T_HW_RACK_PDH ADD (CONSTRAINT FK_HW_RACK_PDH_HW_RACK 
 FOREIGN KEY (RACK_ID) REFERENCES T_HW_RACK (ID) DEFERRABLE INITIALLY IMMEDIATE);

grant select on T_HW_RACK_PDH to R_HURRICAN_READ_ONLY;
grant select, insert, update on T_HW_RACK_PDH to R_HURRICAN_USER;
