-- notwendige Tabelle für Leitungsnummern
CREATE TABLE T_LEITUNGSNUMMER
(
  ID              NUMBER(10)                    NOT NULL,
  ENDSTELLE_ID    NUMBER(10)                    NOT NULL,
  LN_TYP          VARCHAR2(10 BYTE)             NOT NULL,
  LEITUNGSNUMMER  VARCHAR2(50 BYTE)             NOT NULL,
  VERSION         NUMBER(18)                    NOT NULL
);

-- Kommentare
COMMENT ON TABLE T_LEITUNGSNUMMER IS 'Tabelle, um Leitungsnummern für Endstellen zu definieren';
COMMENT ON COLUMN T_LEITUNGSNUMMER.LN_TYP IS 'Typ der Leitungsnummer (Kunde oder Carrier)';
COMMENT ON COLUMN T_LEITUNGSNUMMER.LEITUNGSNUMMER IS 'Bezeichnung der Leitungsnummer';

-- Constraints
ALTER TABLE T_LEITUNGSNUMMER ADD (CONSTRAINT T_LEITUNGSNUMMER_PK PRIMARY KEY (ID));

ALTER TABLE T_LEITUNGSNUMMER ADD (CONSTRAINT FK_LEITUNGSNUMMER_2_ENDSTELLE
    FOREIGN KEY (ENDSTELLE_ID) REFERENCES T_ENDSTELLE (ID)
);

-- Sequenz
CREATE SEQUENCE S_T_LEITUNGSNUMMER_0;

-- Indexes
CREATE INDEX IX_FK_LEITUNGSNUMMER_2_ENDST ON T_LEITUNGSNUMMER (ENDSTELLE_ID);

-- Rechte für Tabelle und Sequenz
GRANT SELECT, INSERT, UPDATE, DELETE ON T_LEITUNGSNUMMER TO R_HURRICAN_USER;
GRANT SELECT ON T_LEITUNGSNUMMER TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON S_T_LEITUNGSNUMMER_0 TO PUBLIC;
