INSERT INTO T_PHYSIKTYP (ID, NAME, BESCHREIBUNG, HVT_TECHNIK_ID, MAX_BANDWIDTH, HW_SCHNITTSTELLE, PT_GROUP, CPS_TRANSFER_METHOD, VERSION)
 VALUES (120, 'CONNECT', 'Connect-Physiken', NULL, NULL, 'CONNECT', 5, NULL, 0);

INSERT INTO T_HW_BAUGRUPPEN_TYP
	(ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID, VERSION, PORT_COUNT_OUT)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'Geplant-PDH-4-Port', 4, 'Geplante PDH-Baugruppe mit 4 Ports',  '1', 'PDH', 'PDH', NULL, 0,  NULL);

