ALTER TABLE T_DSLAM_PROFILE RENAME COLUMN L2POWER TO L2POWER_OLD;

ALTER TABLE T_DSLAM_PROFILE ADD (L2POWER CHAR(1));

UPDATE T_DSLAM_PROFILE SET L2POWER = 1 WHERE L2POWER_OLD = 'L2 Power Save Mode enabled';
UPDATE T_DSLAM_PROFILE SET L2POWER = 0 WHERE L2POWER_OLD = 'noL2 Power Save Mode';
UPDATE T_DSLAM_PROFILE SET L2POWER = 0 WHERE L2POWER_OLD = 'noL2 Power Save Mode (n/a)';

ALTER TABLE T_DSLAM_PROFILE DROP COLUMN L2POWER_OLD;
