DROP INDEX IX_FK_LEITUNGSNUMMER_2_ENDST;

ALTER TABLE T_LEITUNGSNUMMER DROP CONSTRAINT FK_LEITUNGSNUMMER_2_ENDSTELLE;
ALTER TABLE T_LEITUNGSNUMMER RENAME COLUMN ENDSTELLE_ID TO AUFTRAG_ID;

ALTER TABLE T_LEITUNGSNUMMER ADD (CONSTRAINT FK_LEITUNGSNUMMER_2_AUFTRAG
    FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID)
);

CREATE INDEX IX_FK_LEITUNGSNUMMER_2_AUFTR ON T_LEITUNGSNUMMER (AUFTRAG_ID);
