CREATE TABLE T_MIG_EQ2PORTNAME AS
SELECT EQ.EQ_ID, R.MANAGEMENTBEZ||'-'||EQ.HW_EQN AS PORTNAME FROM T_EQUIPMENT EQ, T_HW_RACK R, T_HW_BAUGRUPPE BG WHERE EQ.HW_BAUGRUPPEN_ID = BG.ID AND R.ID = BG.RACK_ID AND EQ.HW_SCHNITTSTELLE = 'ADSL-OUT';
CREATE INDEX IX_PORTNAME_EQ2PORTNAME ON T_MIG_EQ2PORTNAME(PORTNAME);

GRANT SELECT ON T_MIG_EQ2PORTNAME TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_MIG_EQ2PORTNAME TO R_HURRICAN_TECHNIKMUC;
GRANT SELECT, UPDATE ON T_MIG_EQ2PORTNAME TO R_HURRICAN_TOOLS;
GRANT INSERT, SELECT, UPDATE ON T_MIG_EQ2PORTNAME TO R_HURRICAN_USER;