--
-- Rechte für Tabelle T_KUNDE_NBZ und Sequenz S_T_KUNDE_NBZ
--
GRANT SELECT ON S_T_KUNDE_NBZ TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_KUNDE_NBZ TO R_HURRICAN_USER;
GRANT SELECT ON T_KUNDE_NBZ TO R_HURRICAN_READ_ONLY;