
ALTER TABLE T_HW_BAUGRUPPEN_TYP DROP (PORT_COUNT_OUT);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'GTU', 1, 'PDH Baugruppe', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'GTU4', 1, 'PDH Baugruppe', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'OTSU-2M', 2, 'PDH Baugruppe', '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'Geplant-PDH-1-Port', 1, 'Geplante PDH-Baugruppe mit 1 Port',  '1', 'PDH', 'PDH', NULL);

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'Geplant-PDH-2-Port', 2, 'Geplante PDH-Baugruppe mit 2 Ports',  '1', 'PDH', 'PDH', NULL);

UPDATE T_HW_BAUGRUPPEN_TYP SET NAME = 'DSMX34' WHERE NAME = 'DSMX';
