
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID)
 VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextval, 'BOTU', 5, 'PDH Baugruppe, 1 Optischer Eingang',  '1', 'PDH', 'PDH', NULL);

