Insert into T_DSLAM_PROFILE_CHANGE_REASON (ID, NAME, VERSION, WHOLESALE)
 Values (11, 'Init', 0, '0');

update T_AUFTRAG_2_DSLAMPROFILE set CHANGE_REASON_ID=11 where CHANGE_REASON_ID is null;
alter table T_AUFTRAG_2_DSLAMPROFILE modify CHANGE_REASON_ID NOT NULL;

drop table T_DSLAM_PROFILE_CHANGE;
