INSERT INTO t_counter (counter, intvalue) VALUES ('innenauftrag', 1000);

ALTER TABLE T_IA ADD ( "PROJEKTLEITER_USER_ID" NUMBER(5) );

ALTER TABLE T_IA_BUDGET ADD ( "BUDGET_USER_ID" NUMBER(5) );

-- TODO BUDGET_USER_ID modify auf NOT NULL

UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 200 WHERE PROJEKTLEITER = 'Thiel Dorothea';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 16 WHERE PROJEKTLEITER = 'Steigenberger Eric';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 255 WHERE PROJEKTLEITER = 'Sailer Günter';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 23 WHERE PROJEKTLEITER = 'Christa Robert';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 62 WHERE PROJEKTLEITER = 'Lippert Ulrich-Walter';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 100 WHERE PROJEKTLEITER = 'Winkler Michael';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 97 WHERE PROJEKTLEITER = 'Weschta Peter';
UPDATE HURRICAN.T_IA_BUDGET SET HURRICAN.T_IA_BUDGET.budget_user_id = 166 WHERE PROJEKTLEITER = 'Schön Georg';

UPDATE T_IA_BUDGET SET budget_user_id = 186 WHERE budget_user_id = 166;