-- ATTENTIION: File must not contain ; to close a statement instead each statement is closed by / in a separate line

--
-- SQL-Script, um die Hurrican-DB in einen Devel-Modus zu setzen
-- (Pfade und eMails etc. werden auf Test-Werte geaendert).
--

update t_registry set INT_VALUE=0 where id=0
/

-- Updates fuer Mail-Adressen
UPDATE t_registry
SET STR_VALUE = '${developer.email}'
WHERE ID IN (40, 202, 203, 206, 963, 1006, 1151, 1152, 1203, 3007, 4050, 4052, 4053, 5000, 5001, 5003, 5004, 5005, 5050, 5051, 5052)
/

update t_registry set STR_VALUE='c:\temp\kdp{0}.xml' where ID=20
/

ALTER TABLE T_SPERRE_INFO MODIFY(EMAIL VARCHAR2(200 BYTE))
/
delete from t_sperre_info
/
insert into t_sperre_info (ID, ABTEILUNG_ID, EMAIL, ACTIVE) values (1, 5, '${developer.email}', 1)
/


-- Update fuer WITA
update t_wita_config set CONFIG_VALUE='100' where CONFIG_KEY LIKE 'wita.count.of.days.before.sent%'
/
update t_wita_config set CONFIG_VALUE='0' where CONFIG_KEY = 'wita.count.of.minutes.request.onhold'
/
update t_wita_config set CONFIG_VALUE='active' where CONFIG_KEY in ('wita.mode.send', 'wita.mode.receive')
/
update T_WITA_SEND_LIMIT set SEND_LIMIT = -1
/
delete from T_WITA_SEND_COUNT
/
insert into T_CARRIER (ID, TEXT, COMPANY_NAME, TIMEST, USERW, WITA_PROVIDER_NAME_AUFNEHMEND)
     values (999999, 'Wita Simulator', 'Flexagon', SYSDATE, 'schmidan', 'Flexagon')
/

-- Updates fuer WBCI
update t_feature set FLAG='1' where NAME = 'WBCI_RRNP_AUTO_PROCESSING'
/
update t_feature set FLAG='1' where NAME = 'WBCI_DIAL_NUMBER_UPDATE'
/
update t_feature set FLAG='1' where NAME = 'WBCI_ABGEBEND_RUEMVA_AUTO_PROCESSING'
/
update t_feature set FLAG='1' where NAME = 'WBCI_ABGEBEND_STR_AUF_AUTO_PROCESSING'
/

update t_wita_config set CONFIG_VALUE='-1' where CONFIG_KEY = 'wbci.count.of.minutes.request.onhold'
/

-- Benachrichtigung externe Partner
ALTER TABLE T_EXT_SERVICE_PROVIDER MODIFY(MAIL VARCHAR2(200 BYTE))
/
update t_ext_service_provider set MAIL='${developer.email}'
/
UPDATE T_NIEDERLASSUNG SET DISPO_TEAMPOSTFACH = '${developer.email}'
/

-- Update WebService-Config
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.cps.async.url}' where ID=1
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.cps.sync.url}' where ID=2
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.taifun.url}' where ID=3
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.command.user.url}' where ID=4
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.command.hurrican.url}' where ID=5
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.monline.url}' where ID=9
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.bsi.visitprotocol.url}' where ID=10
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.elektra.url}' where ID=11
/
update T_WEBSERVICE_CONFIG set WS_URL='${webservice.config.command.resource.inventory.url}' where ID=12
/

-- FTTX Testdaten l�schen und neu aufbauen
--delete from T_FTTX_CVLAN where EKP_FRAME_CONTRACT_ID != 1
--/
--delete from T_FTTX_EKP_2_A10NSPPORT where EKP_FRAME_CONTRACT_ID != 1
--/
--delete from T_FTTX_EKP_FRAME_CONTRACT  where ID != 1
--/
--create table T_FTTX_A10_NSP_PORT_TDN_TEMP (VBZ_ID decimal(19))
--/
--insert into T_FTTX_A10_NSP_PORT_TDN_TEMP (VBZ_ID) select VBZ_ID from T_FTTX_A10_NSP_PORT where ID != 1
--/
--delete from T_FTTX_A10_PORT_2_OLT where A10_NSP_PORT_ID != 1
--/
--delete from T_FTTX_A10_NSP_PORT where ID != 1
--/
--delete from T_FTTX_A10_NSP where ID != 1
--/
--delete from T_TDN where ID in (select VBZ_ID from T_FTTX_A10_NSP_PORT_TDN_TEMP)
--/
--drop table T_FTTX_A10_NSP_PORT_TDN_TEMP
--/

-- EKP mit CVLAN und A10Nsp
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('DTAG1','DTAG1-001',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-001'),'HSI','PPPoE',7,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-001'),'VOIP','PPPoE',7,130)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-001'),'MC','PPPoE',8,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('DTAG1','DTAG1-002',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-002'),'HSI','PPPoE',7,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-002'),'VOIP','PPPoE',7,140)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-002'),'MC','PPPoE',8,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('DTAG1','DTAG1-003',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-003'),'HSI','PPPoE',7,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-003'),'VOIP','PPPoE',7,150)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-003'),'MC','PPPoE',8,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('DTAG2','DTAG2-001',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG2-001'),'HSI','PPPoE',7,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG2-001'),'VOIP','PPPoE',7,160)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG2-001'),'MC','PPPoE',8,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('EKP001','1.0',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = '1.0'),'HSI','PPPoE',60,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = '1.0'),'VOIP','PPPoE',61,160)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = '1.0'),'MC','PPPoE',62,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = '1.0'),'POTS','PPPoE',63,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('TELEF','TELEF-001',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-001'),'MC','PPPoE',10,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-001'),'HSI','PPPoE',11,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-001'),'VOIP','PPPoE',12,180)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-001'),'VOD','IPoE',13,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('TELEF','TELEF-002',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-002'),'MC','PPPoE',10,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-002'),'HSI','PPPoE',11,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-002'),'VOIP','PPPoE',12,190)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-002'),'VOD','IPoE',13,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('TELEF','TELEF-003',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-003'),'MC','PPPoE',10,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-003'),'HSI','PPPoE',11,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-003'),'VOIP','PPPoE',12,200)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-003'),'VOD','IPoE',13,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('UATP1','UATP1-001',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP1-001'),'MC','PPPoE',100,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP1-001'),'HSI','PPPoE',101,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP1-001'),'VOIP','PPPoE',102,110)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP1-001'),'VOD','IPoE',103,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('UATP2','UATP2-001',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP2-001'),'HSI','PPPoE',110,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP2-001'),'VOIP','PPPoE',112,110)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP2-001'),'MC','PPPoE',124,null)
/
INSERT INTO T_FTTX_EKP_FRAME_CONTRACT (EKP_ID,FRAME_CONTRACT_ID,ID,VERSION) VALUES ('CONG','CONG-001',S_T_FTTX_EKP_FRAME_CONTRACT_0.nextval,0)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'CONG-001'),'HSI','PPPoE',120,null)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'CONG-001'),'VOIP','PPPoE',123,160)
/
INSERT INTO T_FTTX_CVLAN (ID,VERSION,EKP_FRAME_CONTRACT_ID,TYP,PROTOCOLL,VLAN_VALUE,PBIT_LIMIT) VALUES (S_T_FTTX_CVLAN_0.nextval,0,
    (select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'CONG-001'),'MC','PPPoE',125,null)
/


-- A10NSP, Port, VBZ fuer Port und Beziehung zum EKP_FRAME_CONTRACT (jeweils default Port)
INSERT INTO T_FTTX_A10_NSP (ID,VERSION,A10_NSP_NUMMER,A10_NSP_NAME) VALUES (S_T_FTTX_A10_NSP_0.nextval,0,52,'WSDTE1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000002')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSDTE1'),(select ID from T_TDN where TDN='FE00000002'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000002'),'1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000003')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSDTE1'),(select ID from T_TDN where TDN='FE00000003'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-002'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000003'),'1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000004')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSDTE1'),(select ID from T_TDN where TDN='FE00000004'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG1-003'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000004'),'1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000005')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSDTE1'),(select ID from T_TDN where TDN='FE00000005'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'DTAG2-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000005'),'1')
/
INSERT INTO T_FTTX_A10_NSP (ID,VERSION,A10_NSP_NUMMER,A10_NSP_NAME) VALUES (S_T_FTTX_A10_NSP_0.nextval,0,53,'WSEK01')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000006')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSEK01'),(select ID from T_TDN where TDN='FE00000006'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = '1.0'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000006'),'1')
/
INSERT INTO T_FTTX_A10_NSP (ID,VERSION,A10_NSP_NUMMER,A10_NSP_NAME) VALUES (S_T_FTTX_A10_NSP_0.nextval,0,54,'WSTEF1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000007')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSTEF1'),(select ID from T_TDN where TDN='FE00000007'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000007'),'1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000008')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSTEF1'),(select ID from T_TDN where TDN='FE00000008'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-002'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000008'),'1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000009')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSTEF1'),(select ID from T_TDN where TDN='FE00000009'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'TELEF-003'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000009'),'1')
/

INSERT INTO T_FTTX_A10_NSP (ID,VERSION,A10_NSP_NUMMER,A10_NSP_NAME) VALUES (S_T_FTTX_A10_NSP_0.nextval,0,55,'WSUAT1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000010')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSUAT1'),(select ID from T_TDN where TDN='FE00000010'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP1-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000010'),'1')
/
INSERT INTO T_FTTX_A10_NSP (ID,VERSION,A10_NSP_NUMMER,A10_NSP_NAME) VALUES (S_T_FTTX_A10_NSP_0.nextval,0,56,'WSUAT2')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000011')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSUAT2'),(select ID from T_TDN where TDN='FE00000011'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP2-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000011'),'1')
/
INSERT INTO T_FTTX_A10_NSP (ID,VERSION,A10_NSP_NUMMER,A10_NSP_NAME) VALUES (S_T_FTTX_A10_NSP_0.nextval,0,57,'WSCON1')
/
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000012')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSCON1'),(select ID from T_TDN where TDN='FE00000012'))
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'CONG-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000012'),'1')
/

-- zusaetzliche A10Nsp_ports fuer spezielle OLTs
insert into T_TDN (ID, TDN) values (S_T_TDN_0.nextVal, 'FE00000013')
/
INSERT INTO T_FTTX_A10_NSP_PORT (ID,VERSION,A10_NSP_ID,VBZ_ID) VALUES (S_T_FTTX_A10_NSP_PORT_0.nextval,0,
    (select ID from T_FTTX_A10_NSP where A10_NSP_NAME='WSUAT1'),(select ID from T_TDN where TDN='FE00000013'))
/
INSERT INTO T_FTTX_A10_PORT_2_OLT (A10_NSP_PORT_ID,HW_RACK_OLT_ID)
    VALUES ((select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000013'),950)
/
INSERT INTO T_FTTX_A10_PORT_2_OLT (A10_NSP_PORT_ID,HW_RACK_OLT_ID)
    VALUES ((select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000013'),951)
/
INSERT INTO T_FTTX_A10_PORT_2_OLT (A10_NSP_PORT_ID,HW_RACK_OLT_ID)
    VALUES ((select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000013'),952)
/
INSERT INTO T_FTTX_EKP_2_A10NSPPORT (EKP_FRAME_CONTRACT_ID,A10_NSP_PORT_ID,IS_DEFAULT_4_EKP)
    VALUES ((select ID from T_FTTX_EKP_FRAME_CONTRACT where FRAME_CONTRACT_ID = 'UATP1-001'),
    (select p.ID from T_FTTX_A10_NSP_PORT p join T_TDN v on p.VBZ_ID = v.ID where v.TDN='FE00000013'),'0')
/

-- sequence pauschal erhoehen, da Oracle es nicht schafft einen konsistenten dump zu erzeugen ...
declare
       type tabs is table of number index by pls_integer;
       c tabs;
    begin
       for counter in (select sequence_name n from user_sequences)
    loop
        execute immediate
       'select '||counter.n||'.nextval from dual connect by level<=1000'
        bulk collect into c;
    end loop;
end;
/

-- set sequence to good value
DECLARE
  curval NUMBER;
  maxval NUMBER;
  inc NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_RSM_RANG_COUNT_0 INCREMENT BY 1';
  SELECT MAX(ID) INTO maxval FROM T_RSM_RANG_COUNT;
  SELECT S_T_RSM_RANG_COUNT_0.NEXTVAL INTO curval FROM DUAL;
  inc := (maxval - curval);
  IF inc > 0 THEN
    EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_RSM_RANG_COUNT_0 INCREMENT BY ' || inc;
    SELECT S_T_RSM_RANG_COUNT_0.nextval into curval FROM DUAL;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_RSM_RANG_COUNT_0 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  curval NUMBER;
  maxval NUMBER;
  inc NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_RSM_PORT_USAGE_0 INCREMENT BY 1';
  SELECT MAX(ID) INTO maxval FROM T_RSM_PORT_USAGE;
  SELECT S_T_RSM_PORT_USAGE_0.NEXTVAL INTO curval FROM DUAL;
  inc := (maxval - curval);
  IF inc > 0 THEN
    EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_RSM_PORT_USAGE_0 INCREMENT BY ' || inc;
    SELECT S_T_RSM_PORT_USAGE_0.nextval into curval FROM DUAL;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE S_T_RSM_PORT_USAGE_0 INCREMENT BY 1';
  END IF;
END;
/
