--
-- SQL-Script, um die Kontaktdaten der Carrier zu halten
--

drop table T_CARRIER_CONTACT;
CREATE TABLE T_CARRIER_CONTACT (
       ID NUMBER(10) NOT NULL 
     , CARRIER_ID NUMBER(10) NOT NULL
     , BRANCH_OFFICE VARCHAR2(30) NOT NULL
     , RESSORT VARCHAR2(30)
     , CONTACT_NAME VARCHAR2(20)
     , STREET VARCHAR2(30)
     , HOUSENUM VARCHAR2(10)
     , POSTAL_CODE VARCHAR2(10)
     , CITY VARCHAR2(30)
     , FAULT_CLEARING_PHONE VARCHAR2(20)
     , FAULT_CLEARING_FAX VARCHAR2(20)
);
commit;

ALTER TABLE T_CARRIER_CONTACT ADD CONSTRAINT PK_T_CARRIER_CONTACT PRIMARY KEY (ID);
commit;

alter table T_HVT_STANDORT add CARRIER_CONTACT_ID NUMBER(10);
ALTER TABLE T_HVT_STANDORT
  ADD CONSTRAINT FK_HVTSTD_2_CCONTACT
      FOREIGN KEY (CARRIER_CONTACT_ID)
      REFERENCES T_CARRIER_CONTACT (ID);
commit;
      
ALTER TABLE T_CARRIER_CONTACT
  ADD CONSTRAINT FK_CCONTACT_2_CARRIER
      FOREIGN KEY (CARRIER_ID)
      REFERENCES T_CARRIER (ID);
commit;

insert into T_CARRIER_CONTACT (ID, CARRIER_ID, BRANCH_OFFICE, RESSORT, FAULT_CLEARING_PHONE, FAULT_CLEARING_FAX) 
  values (1, 12, 'TK NL Süd', 'MSA 3', '089/6277-4577', '089/6277-4588');
insert into T_CARRIER_CONTACT (ID, CARRIER_ID, BRANCH_OFFICE, RESSORT, FAULT_CLEARING_PHONE, FAULT_CLEARING_FAX) 
  values (2, 12, 'TNL Stuttgart', 'QNM-MNS', '0800/3309506', '0800/3309365');
commit;

update T_HVT_STANDORT set CARRIER_CONTACT_ID=1 where ZBDTAG=1.0;
update T_HVT_STANDORT set CARRIER_CONTACT_ID=2 where ZBDTAG=2.0;
commit;

GRANT SELECT, INSERT, UPDATE ON T_CARRIER_CONTACT TO R_HURRICAN_USER;
GRANT SELECT ON T_CARRIER_CONTACT TO R_HURRICAN_READ_ONLY;
GRANT SELECT, UPDATE ON T_CARRIER_CONTACT TO R_HURRICAN_TOOLS;
commit;

