--
-- SQL-Script, um die Tabellen fuer den Hardware-Monitor anzulegen.
--

CREATE TABLE T_RS_MONITOR_RUN (
       ID NUMBER(9) NOT NULL
     , MONITOR_TYPE NUMBER(9) NOT NULL
     , STATE NUMBER(9) NOT NULL
     , STARTED_AT TIMESTAMP NOT NULL
     , FINISHED_AT TIMESTAMP
     , RUN_EXECUTED_BY VARCHAR2(15) NOT NULL
);

ALTER TABLE T_RS_MONITOR_RUN 
  ADD CONSTRAINT PK_T_RS_MONITOR_RUN 
      PRIMARY KEY (ID);

CREATE INDEX IX_FK_RSMONRUN_2_REF
	ON T_RS_MONITOR_RUN (STATE) TABLESPACE "I_HURRICAN";
ALTER TABLE T_RS_MONITOR_RUN
  ADD CONSTRAINT FK_RSMONRUN_2_REF
      FOREIGN KEY (STATE)
      REFERENCES t_reference (ID);

CREATE INDEX IX_FK_RSMONRUNTYPE_2_REF
	ON T_RS_MONITOR_RUN (MONITOR_TYPE) TABLESPACE "I_HURRICAN";
ALTER TABLE T_RS_MONITOR_RUN
  ADD CONSTRAINT FK_RSMONRUNTYPE_2_REF
      FOREIGN KEY (MONITOR_TYPE)
      REFERENCES t_reference (ID);

CREATE TABLE T_RS_MONITOR_CONFIG (
       ID NUMBER(9) NOT NULL
     , HVT_ID_STANDORT NUMBER(9) NOT NULL
     , MONITOR_TYPE NUMBER(9) NOT NULL
     , PHYSIKTYP NUMBER(9)
     , PHYSIKTYP_ADD NUMBER(9)
     , EQ_RANG_SCHNITTSTELLE VARCHAR2(10)
     , EQ_UEVT VARCHAR2(100)
     , MIN_COUNT NUMBER(9)
     , ALARMIERUNG CHAR(1) default(1) not null
     , USERW VARCHAR2(15)
     , DATEW TIMESTAMP
);

ALTER TABLE T_RS_MONITOR_CONFIG
  ADD CONSTRAINT PK_T_RS_MONITOR_CONFIG
      PRIMARY KEY (ID);

CREATE INDEX IX_FK_RSMONCONF_2_PT
	ON T_RS_MONITOR_CONFIG (PHYSIKTYP) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_FK_RSMONCONF_2_PT2
	ON T_RS_MONITOR_CONFIG (PHYSIKTYP_ADD) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_FK_RSMONCONF_2_HVTSTD
	ON T_RS_MONITOR_CONFIG (HVT_ID_STANDORT) TABLESPACE "I_HURRICAN";

CREATE INDEX IX_FK_RSMONCONF_2_REF
	ON T_RS_MONITOR_CONFIG (MONITOR_TYPE) TABLESPACE "I_HURRICAN";	

ALTER TABLE T_RS_MONITOR_CONFIG
  ADD CONSTRAINT FK_RSMONCONF_2_HVTSTD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

ALTER TABLE T_RS_MONITOR_CONFIG
  ADD CONSTRAINT FK_RSMONCONF_2_PT
      FOREIGN KEY (PHYSIKTYP)
      REFERENCES t_physiktyp (ID);

ALTER TABLE T_RS_MONITOR_CONFIG
  ADD CONSTRAINT FK_RSMONCONF_2_PT2
      FOREIGN KEY (PHYSIKTYP_ADD)
      REFERENCES t_physiktyp (ID);

ALTER TABLE T_RS_MONITOR_CONFIG
  ADD CONSTRAINT FK_RSMONCONF_2_REF
      FOREIGN KEY (MONITOR_TYPE)
      REFERENCES t_reference (ID);

commit;

-- Sequences anlegen
create SEQUENCE S_T_RS_MONITOR_CONFIG_0 start with 1125;
grant select on S_T_RS_MONITOR_CONFIG_0 to public;

create SEQUENCE S_T_RS_MONITOR_RUN_0 start with 1;
grant select on S_T_RS_MONITOR_RUN_0 to public;


-- Referenzdaten fuer Monitor-Status anlegen
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (300, 'RS_MONITOR_STATE', 'running', '1', 10, 
  'Status fuer den Ressourcen-Monitor zeigt an, dass die Auswertung noch laeuft.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (301, 'RS_MONITOR_STATE', 'finished', '1', 20, 
  'Status fuer den Ressourcen-Monitor zeigt an, dass die Auswertung beendet ist.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (302, 'RS_MONITOR_STATE', 'error', '1', 30, 
  'Status fuer den Ressourcen-Monitor zeigt an, dass die Auswertung einen Fehler verursacht hat.');

--
-- Referenzdaten fuer Monitor-Typ anlegen.
-- (Diese Werte werden auch in T_RS_MONITOR_RUN.HW_MONITOR_RUN verwendet)
--
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (350, 'RS_MONITOR_TYPE', 'Rangierungen', '1', 10, 
  'RessourcenMonitor-Typ fuer die Auswertung von Rangierungen.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (351, 'RS_MONITOR_TYPE', 'Ports', '1', 20, 
  'RessourcenMonitor-Typ fuer die Auswertung von Ports.');

commit;

GRANT SELECT ON T_RS_MONITOR_RUN TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON T_RS_MONITOR_CONFIG TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_RS_MONITOR_RUN TO R_HURRICAN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_RS_MONITOR_CONFIG TO R_HURRICAN_USER;

CREATE TABLE T_RSM_EQ_VIEW (
       HVT_ID_STANDORT NUMBER(10),
       UEVT_ID NUMBER(10),
       UEVT VARCHAR(10), 
       CUDA_PHYSIK CHAR(5),
       CARRIER VARCHAR(50),
       CUDA_FREI NUMBER(10),
       CUDA_VORBEREITET NUMBER(10),
       CUDA_RANGIERT NUMBER(10),
       HVT_NAME VARCHAR(50), 
       ONKZ VARCHAR(10),
       ASB NUMBER(10),
       SCHWELLWERT NUMBER(10),
       RANG_SS_TYPE VARCHAR(50)
);

ALTER TABLE T_RSM_EQ_VIEW
  ADD CONSTRAINT FK_UCV_2_HVT
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

CREATE TABLE T_RSM_EQ_COUNT (
       UEVT VARCHAR(10) NOT NULL, 
       HVT_ID_STANDORT NUMBER(10), 
       CUDA_PHYSIK VARCHAR(50), 
       RANG_LEISTE1 VARCHAR(10), 
       RANG_SS_TYPE VARCHAR(50), 
       BELEGT NUMBER(10), 
       FREI NUMBER(10)
);

ALTER TABLE T_RSM_EQ_COUNT
  ADD CONSTRAINT FK_CB_2_HVT
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES t_hvt_standort (HVT_ID_STANDORT);

-- Grants
grant select on T_RSM_EQ_VIEW to R_HURRICAN_READ_ONLY;
grant select, insert, update, delete on T_RSM_EQ_VIEW to R_HURRICAN_USER;
grant select on T_RSM_EQ_COUNT to R_HURRICAN_READ_ONLY;
grant select, insert, update, delete on T_RSM_EQ_COUNT to R_HURRICAN_USER;


-- Rangierungs-Monitor
CREATE TABLE T_RSM_RANG_COUNT (
		HVT_ID_STANDORT NUMBER(10) NOT NULL,
		PHYSIKTYP NUMBER(10) NOT NULL,
		PHYSIKTYP_ADDITIONAL NUMBER(10),
		BELEGT NUMBER(10) NOT NULL,
		FREI NUMBER(10) NOT NULL,
		FREIGABE_BEREIT NUMBER(10) NOT NULL,
		DEFEKT NUMBER(10) NOT NULL,
		IM_AUFBAU NUMBER(10) NOT NULL,
		VORHANDEN NUMBER(10) NOT NULL
);

ALTER TABLE T_RSM_RANG_COUNT
  ADD CONSTRAINT FK_RC_2_PT1
      FOREIGN KEY (PHYSIKTYP)
      REFERENCES t_physiktyp(ID);
      
ALTER TABLE T_RSM_RANG_COUNT
  ADD CONSTRAINT FK_RC_2_PT2
      FOREIGN KEY (PHYSIKTYP_ADDITIONAL)
      REFERENCES t_physiktyp(ID);

grant select on T_RSM_RANG_COUNT to R_HURRICAN_READ_ONLY;
grant select, insert, update, delete on T_RSM_RANG_COUNT to R_HURRICAN_USER;

insert into t_registry (ID, NAME, STR_VALUE, DESCRIPTION) 
values ( 1150, 'scheduler.rm.job', 'rmJobGroup.startRessourcenMonitor', 'Name fuer Ressourcen-Monitor-Job');
insert into t_registry (ID, NAME, STR_VALUE, DESCRIPTION) 
values ( 1151, 'rm.alarmierung.rangierung', 'andreas.gilg@m-net.de', 'Email-Adressen fuer Alarmierung des Rangierungsmonitors');
insert into t_registry (ID, NAME, STR_VALUE, DESCRIPTION) 
values ( 1152, 'rm.alarmierung.eq', 'andreas.gilg@m-net.de', 'Email-Adressen fuer Alarmierung des EQ-Monitors');


ALTER TABLE T_RSM_EQ_VIEW DROP COLUMN ORTSTEIL;
ALTER TABLE T_RSM_EQ_VIEW ADD HVT_NAME VARCHAR(50);
ALTER TABLE T_RS_MONITOR_CONFIG ADD ALARMIERUNG CHAR(1) default(1) not null ;
