--
-- SQL-Script, um die Tabellen fuer die Hardware-Definitionen
-- anzulegen.
--

CREATE TABLE T_HW_BAUGRUPPEN_TYP (
       ID NUMBER(9) NOT NULL
     , NAME VARCHAR2(20) NOT NULL
     , PORT_COUNT NUMBER(9)
     , DESCRIPTION VARCHAR2(255)
);
COMMENT ON TABLE T_HW_BAUGRUPPEN_TYP IS 'Tabelle definiert die moeglichen Baugruppentypen mit optionaler Anzahl der maximalen Ports.';

CREATE TABLE T_HW_RACK (
       ID NUMBER(9) NOT NULL
     , RACK_TYP VARCHAR2(15) NOT NULL
     , ANLAGENBEZ VARCHAR2(50)
     , GERAETEBEZ VARCHAR2(50)
     , HVT_ID_STANDORT NUMBER(9) NOT NULL
     , HVT_RAUM_ID NUMBER(9)
     , HW_PRODUCER NUMBER(9) NOT NULL
     , GUELTIG_VON DATE NOT NULL
     , GUELTIG_BIS DATE NOT NULL
);
COMMENT ON TABLE T_HW_RACK IS 'Definiert die verschiedenen Racks und gibt den Standort an';
COMMENT ON COLUMN T_HW_RACK.RACK_TYP IS 'Definition fuer die Art des Racks. Entspricht Tabellen-Suffix, z.B. DSLAM, DLU etc.';

CREATE TABLE T_HW_RACK_DSLAM (
       RACK_ID NUMBER(9) NOT NULL
     , DHCP82_NAME VARCHAR2(50)
     , VPI_UBR_ADSL NUMBER(9)
     , VPI_SDSL NUMBER(9)
     , OUTER_TAG_ADSL NUMBER(9)
     , OUTER_TAG_SDSL NUMBER(9)
     , IP_ADDRESS CHAR(20)
     , EINBAUPLATZ CHAR(10)
     , ANSCHLUSS CHAR(25)
     , ANS_SLOT_PORT CHAR(25)
     , ANS_ART CHAR(25)
     , SCHMIDTSCHES_KONZEPT CHAR(1)
     , VERSION CHAR(20)
     , ERX_IFACE_DATEN VARCHAR2(10)
     , ERX_STANDORT VARCHAR2(50)
     , PHYSIK_ART VARCHAR2(10)
     , PHYSIK_WERT VARCHAR2(10)
     , ATM_PATTERN VARCHAR2(50)
);
COMMENT ON TABLE T_HW_RACK_DSLAM IS 'Detail-Informationen zu einem DSLAM';

CREATE TABLE T_HW_RACK_DLU (
       RACK_ID NUMBER(9) NOT NULL
     , DLU_NUMBER VARCHAR2(20)
     , DLU_TYPE VARCHAR2(20)
);
COMMENT ON TABLE T_HW_RACK_DLU IS 'Detail-Informationen zu einer DLU';

CREATE TABLE T_HW_RACK_ROUTER (
       RACK_ID NUMBER(9) NOT NULL
     , ROUTER_TYP VARCHAR2(50)
     , SERIAL_NUMBER VARCHAR2(50)
);
COMMENT ON TABLE T_HW_RACK_ROUTER IS 'Detail-Informationen zu einem ROUTER';

CREATE TABLE T_HW_RACK_LTG (
       RACK_ID NUMBER(9) NOT NULL
     , LTG_NUMBER VARCHAR2(10) NOT NULL
     , LTG_TYPE VARCHAR2(10)
     , LTG_LDPARP VARCHAR2(10)
);
COMMENT ON TABLE T_HW_RACK_LTG IS 'Detail-Informationen zu einer LineTrunkGroup';
COMMENT ON COLUMN T_HW_RACK_LTG.LTG_LDPARP IS 'Definition des Ladeparameters';

CREATE TABLE T_HW_BAUGRUPPE (
       ID NUMBER(9) NOT NULL
     , RACK_ID NUMBER(9) NOT NULL
     , HW_BG_TYP_ID NUMBER(9) NOT NULL
     , EINGEBAUT CHAR(1)
     , INVENTAR_NR VARCHAR2(50)
     , MOD_NUMBER VARCHAR(10)
);
COMMENT ON TABLE T_HW_BAUGRUPPE IS 'Definiert eine bestimmte Baugruppe. Diese ist wiederum einem Rack zugeordnet.';
COMMENT ON COLUMN T_HW_BAUGRUPPE.RACK_ID IS 'Angabe, in welchem Rack sich die Baugruppe befindet.';
COMMENT ON COLUMN T_HW_BAUGRUPPE.HW_BG_TYP_ID IS 'Angabe, um welche Art von Baugruppe es sich handelt.';
COMMENT ON COLUMN T_HW_BAUGRUPPE.GERAETEBEZ IS 'Offizielle Geraetebezeichnung fuer diese Baugruppe. (Entspricht ConnectMaster Bezeichnung)';

CREATE TABLE T_HVT_RAUM (
       ID NUMBER(9) NOT NULL
     , HVT_ID_STANDORT NUMBER(9) NOT NULL
     , RAUM VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE T_HVT_RAUM IS 'Definition eines Raumes in einem Technik-Standort.';
COMMENT ON COLUMN T_HVT_RAUM.RAUM IS 'Offizielle Bezeichnung des Raums.';

ALTER TABLE T_HVT_RAUM
  ADD CONSTRAINT PK_T_HVT_RAUM
      PRIMARY KEY (ID);

ALTER TABLE T_HW_BAUGRUPPEN_TYP
  ADD CONSTRAINT PK_T_HW_BAUGRUPPEN_TYP
      PRIMARY KEY (ID);

ALTER TABLE T_HW_RACK
  ADD CONSTRAINT PK_T_HW_RACK
      PRIMARY KEY (ID);

ALTER TABLE T_HW_RACK_DSLAM
  ADD CONSTRAINT PK_T_HW_RACK_DSLAM
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_DLU
  ADD CONSTRAINT PK_T_HW_RACK_DLU
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_LTG
  ADD CONSTRAINT PK_T_HW_RACK_LTG
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_ROUTER
  ADD CONSTRAINT PK_T_HW_RACK_ROUTER
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_BAUGRUPPE
  ADD CONSTRAINT PK_T_HW_BAUGRUPPE
      PRIMARY KEY (ID);

CREATE INDEX IX_FK_HWRACK_2_PRODUCER
	ON T_HW_RACK (HW_PRODUCER) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_RACK
  ADD CONSTRAINT FK_HWRACK_2_PRODUCER
      FOREIGN KEY (HW_PRODUCER)
      REFERENCES T_HVT_TECHNIK (ID);

CREATE INDEX IX_FK_HWRACK_2_HVTRAUM
	ON T_HW_RACK (HVT_RAUM_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_RACK
  ADD CONSTRAINT FK_HWRACK_2_HVTRAUM
      FOREIGN KEY (HVT_RAUM_ID)
      REFERENCES T_HVT_RAUM (ID);

CREATE INDEX IX_FK_HWBG_2_RACK
	ON T_HW_BAUGRUPPE (RACK_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BAUGRUPPE
  ADD CONSTRAINT FK_HWBG_2_RACK
      FOREIGN KEY (RACK_ID)
      REFERENCES T_HW_RACK (ID);

CREATE INDEX IX_FK_HWBG_2_BGTYP
	ON T_HW_BAUGRUPPE (HW_BG_TYP_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HW_BAUGRUPPE
  ADD CONSTRAINT FK_HWBG_2_BGTYP
      FOREIGN KEY (HW_BG_TYP_ID)
      REFERENCES T_HW_BAUGRUPPEN_TYP (ID);

CREATE INDEX IX_FK_HVTRAUM_2_HVTSTD
	ON T_HVT_RAUM (HVT_ID_STANDORT) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HVT_RAUM
  ADD CONSTRAINT FK_HVTRAUM_2_HVTSTD
      FOREIGN KEY (HVT_ID_STANDORT)
      REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_HW_RACK DROP CONSTRAINT CK_HW_RACK_TYP;
ALTER TABLE T_HW_RACK
  add CONSTRAINT CK_HW_RACK_TYP
     CHECK (RACK_TYP IN ('DSLAM', 'DLU', 'ROUTER', 'LTG', 'UEVT'));
ALTER TABLE T_HW_RACK ENABLE CONSTRAINT CK_HW_RACK_TYP;

commit;

-- Sequences anlegen
drop SEQUENCE S_T_HW_BAUGRUPPEN_TYP_0;
create SEQUENCE S_T_HW_BAUGRUPPEN_TYP_0 start with 19;
grant select on S_T_HW_BAUGRUPPEN_TYP_0 to public;

drop SEQUENCE S_T_HW_BAUGRUPPE_0;
create SEQUENCE S_T_HW_BAUGRUPPE_0 start with 7608;
grant select on S_T_HW_BAUGRUPPE_0 to public;

drop SEQUENCE S_T_HW_RACK_0;
create SEQUENCE S_T_HW_RACK_0 start with 890;
grant select on S_T_HW_RACK_0 to public;

drop SEQUENCE S_T_HVT_RAUM_0;
create SEQUENCE S_T_HVT_RAUM_0 start with 105;
grant select on S_T_HVT_RAUM_0 to public;
commit;

-- Tabelle T_HVT_STANDORT um Parameter 'Kreuzungstyp' erweitern
alter table T_HVT_STANDORT add KREUZUNGS_TYP NUMBER(9);
CREATE INDEX IX_FK_HVTSTD_KTYP_2_REF
	ON T_HVT_STANDORT (KREUZUNGS_TYP) TABLESPACE "I_HURRICAN";
ALTER TABLE T_HVT_STANDORT
  ADD CONSTRAINT FK_HVTSTD_KTYP_2_REF
      FOREIGN KEY (KREUZUNGS_TYP)
      REFERENCES t_reference (ID);
-- Referenzdaten fuer Kreuzungstypen
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (400, 'HVT_KREUZUNGSTYP', 'nicht erlaubt', '1', 10, 
  'Kreuzung ist auf dem gesamten HVT nicht erlaubt. Ausnahme: Stoerungsbehebung');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (401, 'HVT_KREUZUNGSTYP', 'uneingeschraenkt erlaubt', '1', 20, 
  'Kreuzung sind auf dem gesamten HVT erlaubt (auch zwischen Raeumen).');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (402, 'HVT_KREUZUNGSTYP', 'innerhalb eines Raumes', '1', 30, 
  'Kreuzung sind nur innerhalb eines Raumes zugelassen.');  
commit;


-- Tabelle T_EQUIPMENT um HW_BG Referenz erweitern
alter table T_EQUIPMENT ADD HW_BAUGRUPPEN_ID NUMBER(9);
CREATE INDEX IX_FK_EQUIPMENT_2_HWBG
	ON T_EQUIPMENT (HW_BAUGRUPPEN_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EQUIPMENT
  ADD CONSTRAINT FK_EQUIPMENT_2_HWBG
      FOREIGN KEY (HW_BAUGRUPPEN_ID)
      REFERENCES T_HW_BAUGRUPPE (ID);

--
-- nicht mehr benoetigte Daten von T_EQUIPMENT entfernen
--
-- alter table T_EQUIPMENT drop column BAUGRUPPE_EINGEBAUT;
-- alter table T_EQUIPMENT drop column DSLAM_ID;
-- drop index IX_FK_EQUIPMENT_2_DSLAM;
-- ALTER TABLE T_EQUIPMENT drop CONSTRAINT FK_EQUIPMENT_2_DSLAM;
-- drop table T_DSLAM;
commit;


-- Rollenberechtigungen definieren
CREATE ROLE "R_HURRICAN_HW_ADMIN" NOT IDENTIFIED;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_BAUGRUPPE TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_BAUGRUPPEN_TYP TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK_DSLAM TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK_DLU TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK_LTG TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HW_RACK_ROUTER TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HVT_RAUM TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_UEVT TO R_HURRICAN_HW_ADMIN;
GRANT SELECT, UPDATE ON T_HVT_STANDORT TO R_HURRICAN_HW_ADMIN;
GRANT "R_HURRICAN_HW_ADMIN" TO "TOOL";
GRANT "R_HURRICAN_HW_ADMIN" TO "HURRICANWRITER";
commit;


-- Eintraege in t_reference
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9500, 'HW_RACK_TYPE', 'DLU', '1', 10, 'HW-Rack Typ DLU.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9501, 'HW_RACK_TYPE', 'DSLAM', '1', 20, 'HW-Rack Typ DSLAM.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9502, 'HW_RACK_TYPE', 'LTG', '1', 30, 'HW-Rack Typ LTG.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9503, 'HW_RACK_TYPE', 'ROUTER', '1', 40, 'HW-Rack Typ ROUTER.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9504, 'HW_RACK_TYPE', 'UEVT', '1', 50, 'HW-Rack Typ UEVT.');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9510, 'HW_DLU_TYPE', 'DLUD', '1', 10, 'HW-Typ DLU');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9511, 'HW_DLU_TYPE', 'DLUB', '1', 20, 'HW-Typ DLU');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9512, 'HW_DLU_TYPE', 'DLUG', '1', 30, 'HW-Typ DLU');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9520, 'HW_LTG_TYPE', 'LTGC', '1', 10, 'HW-Typ LTG');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9521, 'HW_LTG_TYPE', 'LTGB', '1', 20, 'HW-Typ LTG');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9530, 'HW_ERX_STANDORT', 'STAWA', '1', 10, 'ERX-Standorte');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9531, 'HW_ERX_STANDORT', 'BBH', '1', 20, 'ERX-Standorte');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9532, 'HW_ERX_STANDORT', 'ac2-hr1-lanal052', '1', 30, 'ERX-Standorte');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9533, 'HW_ERX_STANDORT', 'ac2-a91f-bri018', '1', 40, 'ERX-Standorte');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9540, 'HW_PHYSIK_ART', 'VLAN', '1', 10, 'Physikarten');
insert into T_REFERENCE (ID, TYPE, STR_VALUE, GUI_VISIBLE, ORDER_NO, DESCRIPTION) 
  values (9541, 'HW_PHYSIK_ART', 'VPI', '1', 10, 'Physikarten');
commit;

-- Trigger
drop trigger TRBI_HW_BAUGRUPPEN_TYP;
create trigger TRBI_HW_BAUGRUPPEN_TYP before insert on T_HW_BAUGRUPPEN_TYP
for each row
when (new.ID is null)
begin
 select S_T_HW_BAUGRUPPEN_TYP_0.nextval into :new.ID from dual;
end;
/

drop trigger TRBI_HW_BAUGRUPPE;
create trigger TRBI_HW_BAUGRUPPE before insert on T_HW_BAUGRUPPE
for each row
when (new.ID is null)
begin
 select S_T_HW_BAUGRUPPE_0.nextval into :new.ID from dual;
end;
/

drop trigger TRBI_HW_RACK;
create trigger TRBI_HW_RACK before insert on T_HW_RACK
for each row
when (new.ID is null)
begin
 select S_T_HW_RACK_0.nextval into :new.ID from dual;
end;
/

drop trigger TRBI_HVT_RAUM;
create trigger TRBI_HVT_RAUM before insert on T_HVT_RAUM
for each row
when (new.ID is null)
begin
 select S_T_HVT_RAUM_0.nextval into :new.ID from dual;
end;
/
commit;

-- Updates (Falls Tabellen neu aufgebaut werden, nicht nötig)
alter TABLE T_HW_RACK_DSLAM drop COLUMN GUELTIG_VON;
alter TABLE T_HW_RACK_DSLAM drop COLUMN GUELTIG_BIS;
alter TABLE T_HW_RACK_DLU drop COLUMN GUELTIG_VON;
alter TABLE T_HW_RACK_DLU drop COLUMN GUELTIG_BIS;
alter TABLE T_HW_RACK_ROUTER drop COLUMN GUELTIG_VON;
alter TABLE T_HW_RACK_ROUTER drop COLUMN GUELTIG_BIS;
alter TABLE T_HW_RACK_LTG drop COLUMN GUELTIG_VON;
alter TABLE T_HW_RACK_LTG drop COLUMN GUELTIG_BIS;

drop SEQUENCE S_T_HW_RACK_DSLAM_0;
drop SEQUENCE S_T_HW_RACK_DLU_0;
drop SEQUENCE S_T_HW_RACK_LTG_0;
drop SEQUENCE S_T_HW_RACK_ROUTER_0;

ALTER TABLE T_HW_RACK_DLU DROP CONSTRAINT PK_T_HW_RACK_DLU;
drop index IX_FK_HWRACKDLU_2_RACK;
ALTER TABLE T_HW_RACK_DLU DROP COLUMN ID;
ALTER TABLE T_HW_RACK_DLU
  ADD CONSTRAINT PK_T_HW_RACK_DLU
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_DSLAM DROP CONSTRAINT PK_T_HW_RACK_DSLAM;
drop index IX_FK_HWRACKDSLAM_2_RACK;
ALTER TABLE T_HW_RACK_DSLAM DROP COLUMN ID;
ALTER TABLE T_HW_RACK_DSLAM
  ADD CONSTRAINT PK_T_HW_RACK_DSLAM
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_LTG DROP CONSTRAINT PK_T_HW_RACK_LTG;
drop index IX_FK_HWRACKLTG_2_RACK;
ALTER TABLE T_HW_RACK_LTG DROP COLUMN ID;
ALTER TABLE T_HW_RACK_LTG
  ADD CONSTRAINT PK_T_HW_RACK_LTG
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_ROUTER DROP CONSTRAINT PK_T_HW_RACK_ROUTER;
drop index IX_FK_HWRACKROUTER_2_RACK;
ALTER TABLE T_HW_RACK_ROUTER DROP COLUMN ID;
ALTER TABLE T_HW_RACK_ROUTER
  ADD CONSTRAINT PK_T_HW_RACK_ROUTER
      PRIMARY KEY (RACK_ID);

ALTER TABLE T_HW_RACK_DSLAM ADD ATM_PATTERN VARCHAR2(50);
UPDATE T_HW_RACK_DSLAM set ATM_PATTERN='atm 0/{0}/0/{1}:0.100' WHERE DHCP82_NAME is not null;

commit;


-- Erweiterung T_UEVT
ALTER TABLE T_UEVT ADD RACK_ID NUMBER(9);

CREATE INDEX IX_FK_UEVT_2_HWRACK
	ON T_UEVT (RACK_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_UEVT
  ADD CONSTRAINT FK_UEVT_2_HWRACK
      FOREIGN KEY (RACK_ID)
      REFERENCES T_HW_RACK (ID);


