--
-- VoiP Passworte von T_AUFTRAG_VOIP nach neue Tabelle T_AUFTRAG_VOIP_DN
-- DN__NO null wenn kein Eintrag gefunden in Taifun-DN-Tabelle
--

-- Tabelle T_AUFTRAG_VOIP_DN anlegen
CREATE TABLE T_AUFTRAG_VOIP_DN (
	ID number(9) not null,
	DN__NO number(10) not null,
	AUFTRAG_ID number(10) not null, 
	SIP_PASSWORD VARCHAR2(10) NOT NULL
);

ALTER TABLE T_AUFTRAG_VOIP_DN ADD CONSTRAINT PK_T_AUFTRAG_VOIP_DN PRIMARY KEY (ID);
      
ALTER TABLE T_AUFTRAG_VOIP_DN
  ADD CONSTRAINT FK_AUFTRAGVOIPDN_2_AUFTRAG
      FOREIGN KEY (AUFTRAG_ID)
      REFERENCES T_AUFTRAG (ID);
      
ALTER TABLE T_AUFTRAG_VOIP_DN
  ADD UNIQUE (DN__NO, AUFTRAG_ID);
      
GRANT SELECT ON T_AUFTRAG_VOIP_DN TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_AUFTRAG_VOIP_DN TO R_HURRICAN_USER;

create sequence S_T_AUFTRAG_VOIP_DN_0 start with 1;
grant select on S_T_AUFTRAG_VOIP_DN_0 to public;



-- ALTER TABLE T_AUFTRAG_VOIP DROP COLUMN sip_password;

commit;

alter table T_AUFTRAG_VOIP modify SIP_PASSWORD VARCHAR2(10) NULL;
