-- FTTB Standorttyp hinzufuegen
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
 Values (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 521, 11002, 2, 'IMPORT', SYSDATE, 0);
