server:
  port: ${PORT:8081}
spring:
  autoconfigure:
   exclude:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
reporting: 
  client: 
   base-url: http://localhost:8080/reporting
   
