@startuml
state state_fork <<fork>>
state state_join <<join>>
[*] --> ACKNOWLEDGED
ACKNOWLEDGED --> PROVISION_IN_PROGRESS : CREATE_ORDER_MESSAGE_SENT
PROVISION_IN_PROGRESS --> WAITING_ORDER_CONFIRMATION : QEB_MESSAGE_RECEIVED
WAITING_ORDER_CONFIRMATION --> state_fork : ABM_MESSAGE_RECEIVED
state PAYMENT_PROCESSING {
    state_fork --> WAITING_PAYMENT_COMPLETION_NOTIFICATION
    state_fork --> WAITING_PAYMENT_NOTIFICATION
    WAITING_PAYMENT_COMPLETION_NOTIFICATION --> PAYMENT_COMPLETION_NOTIFICATION_RECEIVED : ENTM_MESSAGE_RECEIVED
    WAITING_PAYMENT_NOTIFICATION --> PAYMENT_NOTIFICATION_RECEIVED : ERLM_MESSAGE_RECEIVED
    PAYMENT_COMPLETION_NOTIFICATION_RECEIVED --> state_join
    PAYMENT_NOTIFICATION_RECEIVED --> state_join
}
state_join --> COMPLETED
COMPLETED --> [*]
@enduml