drop table T_EG_SBC_IP;

CREATE TABLE T_EG_SBC_IP
(
    EG2A_ID NUMBER(19,0),
    IP_ADDRESS_ID NUMBER(19,0),
    primary key (EG2A_ID, IP_ADDRESS_ID),
    FOREIGN KEY ( EG2A_ID ) REFERENCES T_EG_2_AUFTRAG ( ID ),
    FOREIGN KEY ( IP_ADDRESS_ID ) REFERENCES T_IP_ADDRESS ( ID )
);

GRANT SELECT, INSERT, UPDATE, DELETE ON T_EG_SBC_IP TO R_HURRICAN_USER;
GRANT SELECT ON T_EG_SBC_IP TO R_HURRICAN_READ_ONLY;
