
-- DSLAM Profil 1000/1000 fuer FTTX Telefon über Fritz!Box 7360
INSERT INTO T_DSLAM_PROFILE (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, BAUGRUPPEN_TYP, ENABLED_FOR_AUTOCHANGE)
 VALUES (S_T_DSLAM_PROFILE_0.nextVal, 'MD_1000_1000_H', '1000', '1000', '0', 43, 22, '1', 0, '0', null, '0');

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
 VALUES (511, (select d.id from T_DSLAM_PROFILE d where d.NAME='MD_1000_1000_H' and d.BAUGRUPPEN_TYP is null));
