-- techn. Leistung 300 Mbit/s Downstream
insert into T_TECH_LEISTUNG
  (ID, NAME, EXTERN_LEISTUNG__NO, TYP, LONG_VALUE, STR_VALUE, PROD_NAME_STR, DESCRIPTION, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
  (66, '300000 kbit/s', 10066, 'DOWNSTREAM',
   300000, '300000', '300000', 'Downstream 300.000 kbit/s',
   '0', '0', '0', '1', '0', '1',
   TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
   TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

-- techn. Leistung 30 Mbit/s Upstream
insert into T_TECH_LEISTUNG
  (ID, NAME, EXTERN_LEISTUNG__NO, TYP, LONG_VALUE, STR_VALUE, PROD_NAME_STR, DESCRIPTION, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
   (67, '30000 kbit/s', 10067, 'UPSTREAM',
    30000, '30000', '30000', 'Upstream 30.000 kbit/s',
    '0', '0', '0', '1', '0','1',
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));


-- KOMBI Leistung 300_VOIP_IPv6
insert into T_TECH_LEISTUNG
   (ID, NAME, TYP, EXTERN_LEISTUNG__NO, PROD_NAME_STR, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
   (490, '300_VOIP_IPv6', 'KOMBI', 10211, ' ',
    '0', '0', '0', '0', '0', '1',
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

-- techn. Leistungen fuer FTTX Glasfaser Down-Upstream-Buendel 100/10 und 300/30
insert into T_TECH_LEISTUNG
   (ID, NAME, TYP, EXTERN_LEISTUNG__NO, PROD_NAME_STR, DESCRIPTION, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
   (404, 'FTTX_GF_100/10_MGA', 'KOMBI', 10212,
    ' ', 'Kombi-Leistung, fuehrt zu: 100 MBit, 10 MBit, VOIP_MGA, Endgeraeteport',
    '0', '0', '0', '0', '0', '1',
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

insert into T_TECH_LEISTUNG
   (ID, NAME, TYP, EXTERN_LEISTUNG__NO, PROD_NAME_STR, DESCRIPTION, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
   (405, 'FTTX_GF_100/10_TK', 'KOMBI', 10213,
    ' ', 'Kombi-Leistung, fuehrt zu: 100 MBit, 10 MBit, VOIP_TK, Endgeraeteport',
    '0', '0', '0', '0', '0', '1',
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

insert into T_TECH_LEISTUNG
   (ID, NAME, TYP, EXTERN_LEISTUNG__NO, PROD_NAME_STR, DESCRIPTION, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
   (406, 'FTTX_GF_300/30_MGA', 'KOMBI', 10214,
    ' ', 'Kombi-Leistung, fuehrt zu: 300 MBit, 30 MBit, VOIP_MGA, Endgeraeteport',
    '0', '0', '0', '0', '0', '1',
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

insert into T_TECH_LEISTUNG
   (ID, NAME, TYP, EXTERN_LEISTUNG__NO, PROD_NAME_STR, DESCRIPTION, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS)
 values
   (407, 'FTTX_GF_300/30_TK', 'KOMBI', 10215,
    ' ', 'Kombi-Leistung, fuehrt zu: 300 MBit, 30 MBit, VOIP_TK, Endgeraeteport',
    '0', '0', '0', '0', '0', '1',
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

-- Mapping der KOMBI Leistungen fuer Premium GF
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 404, '0', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 405, '0', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 406, '0', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 407, '0', 0);

-- Mapping der 100/10 Mbit/s Leistungen fuer Premium GF
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 25, 404, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 28, 404, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 25, 405, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 28, 405, '1', 0);

-- Mapping der 300/30 Mbit/s Leistungen fuer Premium GF
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 66, 406, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 67, 406, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 66, 407, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 67, 407, '1', 0);


-- Mapping der KOMBI Leistung fuer Surf-Flat und Surf&Fon-Flat
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 512, 490, '0', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 490, '0', 0);

-- Surf-Flat 300/30
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 512, 66, null, '0', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 512, 67, 66, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 512, 66, 490, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 512, 67, 490, '1', 0);

-- TECH_LS_DEPENDECY = dynamische IPv6
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 512, 57, 490, '1', 0);


-- Surf&Fon-Flat 300/30
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 66, null, '0', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 67, 66, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 66, 490, '1', 0);

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 67, 490, '1', 0);

-- TECH_LS_DEPENDECY = dynamische IPv6
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 513, 57, 490, '1', 0);
