INSERT INTO T_HW_BAUGRUPPEN_TYP (ID,NAME,PORT_COUNT,DESCRIPTION,IS_ACTIVE,HW_SCHNITTSTELLE_NAME,HW_TYPE_NAME,HVT_TECHNIK_ID,VERSION,MAX_BANDWIDTH,TUNNELING,DEF_SCHICHT2_PROTOKOLL)
   VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextVal,'ONT_RF',1,'RF-Ports der ONT','1','RF','ONT',null,0,null,null,null);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID,NAME,PORT_COUNT,DESCRIPTION,IS_ACTIVE,HW_SCHNITTSTELLE_NAME,HW_TYPE_NAME,HVT_TECHNIK_ID,VERSION,MAX_BANDWIDTH,TUNNELING,DEF_SCHICHT2_PROTOKOLL)
   VALUES (S_T_HW_BAUGRUPPEN_TYP_0.nextVal,'ONT_VDSL2',1,'VDSL-Port der ONT','1','VDSL2','ONT',null,0,null,null,null);
