-- Die Baugruppentypen fuer ONTs muessen laut spezifikation ueberarbeitet werden
-- Folgende Baugruppentypen mit Portcount wird es in Zukunft geben:

--  I-221E-A, Portcounts: RF 1, POTS 2, ETH 2
UPDATE T_HW_BAUGRUPPEN_TYP
SET NAME         = 'I-221E-A_RF', DESCRIPTION = 'RF-Ports der Alcatel ONT I-221E-A',
  HVT_TECHNIK_ID = 6
WHERE NAME = 'ONT_RF';

UPDATE T_HW_BAUGRUPPEN_TYP
SET NAME      = 'I-221E-A_ETH', PORT_COUNT = 2,
  DESCRIPTION = 'Ethernet-Ports der Alcatel ONT I-221E-A', HVT_TECHNIK_ID = 6
WHERE NAME = 'ONT_VDSL2';

INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-221E-A_POTS', 2, 'POTS-Ports der Alcatel ONT I-221E-A', '1', 'POTS', 'ONT', 6, 0,
   NULL, NULL, NULL);

-- I-010G-P, Portcounts: RF 0, POTS 0, ETH 1
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-010G-P_RF', 0, 'RF-Ports der Alcatel ONT I-010G-P', '1', 'RF', 'ONT', 6, 0, NULL,
   NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-010G-P_ETH', 1, 'Ethernet-Ports der Alcatel ONT I-010G-P', '1', 'ETH', 'ONT', 6,
   0, NULL, NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-010G-P_POTS', 0, 'POTS-Ports der Alcatel ONT I-010G-P', '1', 'POTS', 'ONT', 6, 0,
   NULL, NULL, NULL);


--  I-241G-Q, Portcounts: RF 1, POTS 2, ETH 4
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-241G-Q_RF', 1, 'RF-Ports der Alcatel ONT I-241G-Q', '1', 'RF', 'ONT', 6, 0, NULL,
   NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-241G-Q_ETH', 4, 'Ethernet-Ports der Alcatel ONT I-241G-Q', '1', 'ETH', 'ONT', 6,
   0, NULL, NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'I-241G-Q_POTS', 2, 'POTS-Ports der Alcatel ONT I-241G-Q', '1', 'POTS', 'ONT', 6, 0,
   NULL, NULL, NULL);


-- HG8242, Portcounts: RF 1, POTS 2, ETH 4
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'HG8242_RF', 1, 'RF-Ports der Alcatel ONT HG8242', '1', 'RF', 'ONT', 2, 0, NULL,
   NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'HG8242_ETH', 4, 'Ethernet-Ports der Alcatel ONT HG8242', '1', 'ETH', 'ONT', 2, 0,
   NULL, NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'HG8242_POTS', 2, 'POTS-Ports der Alcatel ONT HG8242', '1', 'POTS', 'ONT', 2, 0,
   NULL, NULL, NULL);


-- HG865, Portcounts: RF 1, POTS 2, ETH 4
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'HG865_RF', 1, 'RF-Ports der Alcatel ONT HG865', '1', 'RF', 'ONT', 2, 0, NULL, NULL,
   NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'HG865_ETH', 4, 'Ethernet-Ports der Alcatel ONT HG865', '1', 'ETH', 'ONT', 2, 0,
   NULL, NULL, NULL);
INSERT INTO T_HW_BAUGRUPPEN_TYP (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE, HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME,
                                 HVT_TECHNIK_ID, VERSION, MAX_BANDWIDTH, TUNNELING, DEF_SCHICHT2_PROTOKOLL)
VALUES
  (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'HG865_POTS', 2, 'POTS-Ports der Alcatel ONT HG865', '1', 'POTS', 'ONT', 2, 0, NULL,
   NULL, NULL);
