INSERT INTO T_REFERENCE (ID,TYPE,STR_VALUE,GUI_VISIBLE,DESCRIPTION,VERSION,CHANGED_AT)
    VALUES (14010,'CPS_SERVICE_ORDER_TYPE','createHardware','0',
    'Wert definiert den ServiceOrder-Typ, um Hardware zu initialisieren',0,TO_DATE('05/16/2014 14:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO T_REFERENCE (ID,TYPE,STR_VALUE,GUI_VISIBLE, DESCRIPTION,VERSION,CHANGED_AT)
    VALUES (14106,'CPS_TX_SOURCE','HURRICAN_ONT','0',
    'Wert definiert, dass die Transaction fuer eine MDU bestimmt ist',0,TO_DATE('05/16/2014 14:00:00', 'MM/DD/YYYY HH24:MI:SS'));

