UPDATE T_HW_BAUGRUPPEN_TYP SET DESCRIPTION='RF-Ports der Huawei ONT HG8242' WHERE NAME='HG8242_RF' and HW_TYPE_NAME = 'ONT';
UPDATE T_HW_BAUGRUPPEN_TYP SET DESCRIPTION='Ethernet-Ports der Huawei ONT HG8242' WHERE NAME='HG8242_ETH' and HW_TYPE_NAME = 'ONT';
UPDATE T_HW_BAUGRUPPEN_TYP SET DESCRIPTION='POTS-Ports der Huawei ONT HG8242' WHERE NAME='HG8242_POTS' and HW_TYPE_NAME = 'ONT';
UPDATE T_HW_BAUGRUPPEN_TYP SET DESCRIPTION='RF-Ports der Huawei ONT HG865' WHERE NAME='HG865_RF' and HW_TYPE_NAME = 'ONT';
UPDATE T_HW_BAUGRUPPEN_TYP SET DESCRIPTION='Ethernet-Ports der Huawei ONT HG865' WHERE NAME='HG865_ETH' and HW_TYPE_NAME = 'ONT';
UPDATE T_HW_BAUGRUPPEN_TYP SET DESCRIPTION='POTS-Ports der Huawei ONT HG865' WHERE NAME='HG865_POTS' and HW_TYPE_NAME = 'ONT';