update T_KUENDIGUNG_FRIST set FRIST_AUF='EINGANGSDATUM', AUTO_VERLAENGERUNG=0, DESCRIPTION='12 Wochen ab Eingangsdatum' where ID in (92);
update T_KUENDIGUNG_FRIST set FRIST_AUF='EINGANGSDATUM', AUTO_VERLAENGERUNG=0, DESCRIPTION='4 Wochen ab Eingangsdatum' where ID in (45);
