-- nicht mehr benoetigte technische Leistungen vom Produkt entfernen
delete from T_PROD_2_TECH_LEISTUNG ptl 
where ptl.PROD_ID = 540 and ptl.TECH_LS_ID in (112,113,24,27,114);

delete from T_PROD_2_TECH_LEISTUNG ptl 
where ptl.PROD_ID = 540 and ptl.TECH_LS_ID in (300,301,302);


update t_tech_leistung set STR_VALUE='POTS' where ID=111;
update t_tech_leistung set STR_VALUE='ISDN' where ID in (112,113);


-- neue techn. Leistungen als Kombi-Leistung anlegen
INSERT INTO T_TECH_LEISTUNG
   (ID, NAME, TYP, PROD_NAME_STR, EXTERN_LEISTUNG__NO, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, DESCRIPTION, VERSION)
 VALUES
   (400, 'FTTX_GF_50/5_MGA', 'KOMBI', ' ', 10200, '0', '0', '0', '0', '0', '1',
    TO_DATE('02/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    'Kombi-Leistung, fuehrt zu: 50 MBit, 5 MBit, VOIP_MGA, Endgeraeteport', 0);
INSERT INTO T_TECH_LEISTUNG
   (ID, NAME, TYP, PROD_NAME_STR, EXTERN_LEISTUNG__NO, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, DESCRIPTION, VERSION)
 VALUES
   (401, 'FTTX_GF_50/5_TK', 'KOMBI', ' ', 10201, '0', '0', '0', '0', '0', '1',
    TO_DATE('02/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    'Kombi-Leistung, fuehrt zu: 50 MBit, 5 MBit, VOIP_TK, Endgeraeteport', 0);

-- Prod2TechLs Mappings aufnehmen
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 400, '0', 1);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 24, 400, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 27, 400, '1', 1);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 299, 400, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 300, 400, '1', 0);

Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 401, '0', 1);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 24, 401, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 27, 401, '1', 1);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 299, 401, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 301, 401, '1', 0);

