insert into T_REFERENCE (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
values (22372, 'IP_PURPOSE_TYPE_V6', 'Kundennetz', 1, null, null, 1, 10, 'IP Anforderung: Kundennetz', 0);

insert into T_REFERENCE (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE, UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
values (22373, 'IP_PURPOSE_TYPE_V6', 'DHCPv6-PD', 1, null, null, 1, 20, 'IP Anforderung: DHCPv6-PD', 0);