CREATE TABLE T_ERROR_LOG (
       ID NUMBER(9) NOT NULL,
       ERROR_NAME VARCHAR2(250),
       ERROR_DESCRIPTION VARCHAR2(2000),
       CREATED_AT TIMESTAMP
);

COMMENT ON TABLE T_ERROR_LOG IS 'Table for error log entries';

ALTER TABLE T_ERROR_LOG ADD CONSTRAINT PK_T_ERROR_LOG PRIMARY KEY (ID);

create SEQUENCE S_T_ERROR_LOG start with 1;
grant select on S_T_ERROR_LOG to public;

