-- ANF-547/HUR-23774
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION,
    AKTIV_BIS_NULL_ON_SYNC, BA_HINWEIS, PREVENT_AUTO_DISPATCH, AUTO_EXPIRE)
 Values
   (117, 'Installationsservice+IPTV', NULL, 10102, 'SERVICE',
    NULL, NULL, NULL, ' ', 'Service-Leistung zur Installation und IP-TV',
    '0', '0', '0', '0', '0',
    '0', '1', TO_DATE('11/25/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0,
    NULL, NULL, '1', '0');
