ALTER TABLE T_ERROR_LOG
DROP COLUMN GERAETEBEZ;

ALTER TABLE T_ERROR_LOG
DROP COLUMN SERIAL_NO;

ALTER TABLE T_ERROR_LOG
ADD (service VARCHAR2(250));

ALTER TABLE T_ERROR_LOG
ADD (stacktrace VARCHAR2(2000));


CREATE OR REPLACE VIEW V_HURRICAN_ERROR_LOG AS
SELECT * FROM T_ERROR_LOG;

GRANT SELECT ON V_HURRICAN_ERROR_LOG TO EDWH_USER;
GRANT SELECT ON V_HURRICAN_ERROR_LOG TO R_HURRICAN_BSI_VIEWS;
GRANT SELECT ON V_HURRICAN_ERROR_LOG TO R_HURRICAN_USER;
GRANT SELECT ON V_HURRICAN_ERROR_LOG TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON V_HURRICAN_ERROR_LOG TO HURRICAN_TECH_MUC;
