-- ANF-547/HUR-23774 FTTX/VDSL Produkte mit mindestens 50 MBit/s

-- FTTX DSL (512)
INSERT INTO T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION, PRIORITY)
 VALUES
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 512, 117, NULL, '0', 0, NULL);

-- FTTX DSL + FON (513)
INSERT INTO T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION, PRIORITY)
 VALUES
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 513, 117, NULL, '0', 0, NULL);

-- TAL VDSL + Fon (514)
INSERT INTO T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION, PRIORITY)
 VALUES
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 514, 117, NULL, '0', 0, NULL);

-- TAL VDSL (515)
INSERT INTO T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION, PRIORITY)
 VALUES
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 515, 117, NULL, '0', 0, NULL);
