ALTER TABLE T_WITA_SEND_LIMIT
 ADD (DATEW  DATE);

UPDATE T_WITA_SEND_LIMIT
   SET DATEW = LAST_CHANGE_AT;

ALTER TABLE T_WITA_SEND_LIMIT
MODIFY(DATEW  NOT NULL);

ALTER TABLE T_WITA_SEND_LIMIT DROP COLUMN LAST_CHANGE_BY;

ALTER TABLE T_WITA_SEND_LIMIT DROP COLUMN LAST_CHANGE_AT;


CREATE OR REPLACE TRIGGER TRBIU_WITA_SEND_LIMIT BEFORE INSERT or UPDATE on T_WITA_SEND_LIMIT
for each row
begin
 -- TIMEST setzen
 SELECT LOCALTIMESTAMP into :new.DATEW FROM dual;
end;
/
