-- SIP Inter Trunk
-- Produktgruppe
insert into T_PRODUKTGRUPPE (ID, PRODUKTGRUPPE, AM_RESPONSIBILITY, REALM, VERSION) Values (25, 'SIP Inter Trunk', 1201, NULL, 0);

-- Mapping Produktgruppe zu GUI Panel(s)
-- QoS Panel
INSERT INTO T_GUI_MAPPING (ID, GUI_ID, REFERENZ_ID, REFERENZ_HERKUNFT)
    VALUES (S_T_GUI_MAPPING_0.nextVal, 203, 25, 'de.augustakom.hurrican.model.cc.ProduktGruppe');
-- Rufnummer Panel
INSERT INTO T_GUI_MAPPING (ID, GUI_ID, REFERENZ_ID, REFERENZ_HERKUNFT)
    VALUES (S_T_GUI_MAPPING_0.nextVal, 213, 25, 'de.augustakom.hurrican.model.cc.ProduktGruppe');

-- Produkt
insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN,
    LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
    BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
    BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG,
    ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
    CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
    EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID,
    VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
    CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
    TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER, VIER_DRAHT, VERSION,
    MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN, CPS_IP_DEFAULT, CPS_MULTI_DRAHT)
 values
   (530, 25, NULL, 'SIP Inter Trunk', NULL,
    NULL, 1, 0, '0', NULL,
    '0', TO_DATE('12/09/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1',
    '0', '1', '0', 1, 'für Reseller',
    NULL, NULL, '0', '0', '0',
    '0', '0', '0', '0', '0',
    NULL, 11, '0', NULL, 15,
    15, '1', '0', '0', '0',
    NULL, '0', '0', NULL, NULL,
    'A', 'B', NULL, '0', 6,
    0, NULL, '0', '0');

-- Produktmapping
insert into T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values
   (1050, 530, 530, '.', 0);




-- SIP Inter Trunk Endkunde
-- Produktgruppe
insert into T_PRODUKTGRUPPE (ID, PRODUKTGRUPPE, AM_RESPONSIBILITY, REALM, VERSION) Values (26, 'SIP Inter Trunk Endkunde', 1200, NULL, 0);

-- Mapping Produktgruppe zu GUI Panel(s)
-- Rufnummern Panel
INSERT INTO T_GUI_MAPPING (ID, GUI_ID, REFERENZ_ID, REFERENZ_HERKUNFT)
    VALUES (S_T_GUI_MAPPING_0.nextVal, 202, 26, 'de.augustakom.hurrican.model.cc.ProduktGruppe');
-- Endstellen Panel
INSERT INTO T_GUI_MAPPING (ID, GUI_ID, REFERENZ_ID, REFERENZ_HERKUNFT)
    VALUES (S_T_GUI_MAPPING_0.nextVal, 203, 26, 'de.augustakom.hurrican.model.cc.ProduktGruppe');

-- Produkt
insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN,
    LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
    BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
    BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG,
    ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
    CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
    EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID,
    VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
    CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
    TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER, VIER_DRAHT, VERSION,
    MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN, CPS_IP_DEFAULT, CPS_MULTI_DRAHT)
 values
   (531, 26, NULL, 'SIP Inter Trunk Endkunde', NULL,
    NULL, 1, 0, '0', 60,
    '0', TO_DATE('12/09/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1',
    '0', '1', '0', 1, 'für Endkunden',
    NULL, NULL, '0', '0', '0',
    '0', '0', '0', '0', '0',
    NULL, 11, '0', NULL, NULL,
    15, '1', '0', '0', '1',
    'SIPInterTrunkCustomer', '0', '1', NULL, NULL,
    'A', 'B', NULL, '0', 2,
    1, NULL, NULL, NULL);


-- Produktmapping
insert into T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values
   (1051, 531, 531, '.', 0);

-- CPS SO to Chain Mapping
-- deleteSubscriber to CPS cancel Subscriber
insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 531, 14002, 54, 0);
