-- Referenzen fuer die bestehenden Switches anlegen
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22200, 'SWITCH', 'AUG01', NULL, NULL,
    NULL, '1', 10, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22201, 'SWITCH', 'AUG02', NULL, NULL,
    NULL, '1', 20, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22202, 'SWITCH', 'MUC01', NULL, NULL,
    NULL, '1', 30, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22203, 'SWITCH', 'MUC02', NULL, NULL,
    NULL, '1', 40, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22204, 'SWITCH', 'MUC03', NULL, NULL,
    NULL, '1', 50, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22205, 'SWITCH', 'MUC04', NULL, NULL,
    NULL, '1', 60, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22206, 'SWITCH', 'MUC05', NULL, NULL,
    NULL, '1', 70, NULL, 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22207, 'SWITCH', 'NEF01', NULL, NULL,
    NULL, '1', 80, NULL, 0);
