CREATE TABLE T_AUFTRAG_SIP_INTER_TRUNK
(
  ID                   NUMBER(10)             NOT NULL,
  AUFTRAG_ID           NUMBER(10)             NOT NULL,
  SWITCH_REF_ID        NUMBER(10)             NOT NULL,
  TRUNK_GROUP          VARCHAR2(32)           NOT NULL,
  VERSION              NUMBER(18)   DEFAULT 0 NOT NULL
);

COMMENT ON TABLE T_AUFTRAG_SIP_INTER_TRUNK IS 'Tabelle haelt n Kombinationen aus Switch/TrunkGroup pro SIP Hauptauftrag.';

COMMENT ON COLUMN T_AUFTRAG_SIP_INTER_TRUNK.ID IS 'ID des Datensatzes';
COMMENT ON COLUMN T_AUFTRAG_SIP_INTER_TRUNK.AUFTRAG_ID IS 'ID des SIP Hauptauftrages';
COMMENT ON COLUMN T_AUFTRAG_SIP_INTER_TRUNK.SWITCH_REF_ID IS 'ID des Switches aus der T_REFERENCE';
COMMENT ON COLUMN T_AUFTRAG_SIP_INTER_TRUNK.TRUNK_GROUP IS 'Die Trunk Group als Freitext';

create SEQUENCE S_T_AUFTRAG_SIP_INTER_TRUNK_0 start with 1;
grant select on S_T_AUFTRAG_SIP_INTER_TRUNK_0 to public;

ALTER TABLE T_AUFTRAG_SIP_INTER_TRUNK ADD CONSTRAINT PK_T_AUFTRAG_SIP_INTER_TRUNK PRIMARY KEY (ID);

CREATE INDEX IX_FK_AUFTRAGSIPINT_2_AUFTRAG ON T_AUFTRAG_SIP_INTER_TRUNK (AUFTRAG_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_AUFTRAG_SIP_INTER_TRUNK ADD CONSTRAINT FK_AUFTRAGSIPINT_2_AUFTRAG
  FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

CREATE INDEX IX_FK_AUFTRAGSIPINT_2_REF ON T_AUFTRAG_SIP_INTER_TRUNK (SWITCH_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_AUFTRAG_SIP_INTER_TRUNK ADD CONSTRAINT FK_AUFTRAGSIPINT_2_REF
  FOREIGN KEY (SWITCH_REF_ID) REFERENCES T_REFERENCE (ID);

GRANT SELECT ON T_AUFTRAG_SIP_INTER_TRUNK TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_AUFTRAG_SIP_INTER_TRUNK TO R_HURRICAN_USER;

