alter table T_AUFTRAG_SIP_INTER_TRUNK add USERW varchar2(25);
alter table T_AUFTRAG_SIP_INTER_TRUNK add DATEW date;

CREATE OR REPLACE TRIGGER TRBIU_AUFTRAG_SIP BEFORE INSERT OR UPDATE on T_AUFTRAG_SIP_INTER_TRUNK
for each row
begin
   -- DATEW setzen
   SELECT CURRENT_TIMESTAMP into :new.DATEW FROM dual;
end;
/