CREATE TABLE T_IP_ROUTE
(
  ID                   NUMBER(10)             NOT NULL,
  AUFTRAG_ID           NUMBER(10)             NOT NULL,
  IP_ADDRESS           VARCHAR2(40)           NOT NULL,
  PREFIX_LENGTH        NUMBER(10)             NOT NULL,
  METRIK               NUMBER(10)             NOT NULL,
  DESCRIPTION          VARCHAR2(255),
  VERSION              NUMBER(18)   DEFAULT 0 NOT NULL,
  DELETED              CHAR(1)      DEFAULT 0 NOT NULL,
  USERW                VARCHAR2(25),
  DATEW                date
);

COMMENT ON TABLE T_IP_ROUTE IS 'Tabelle mit zusaetzlichen IP-Routen fuer den Auftrag.';

COMMENT ON COLUMN T_IP_ROUTE.AUFTRAG_ID IS 'ID des Auftrags';
COMMENT ON COLUMN T_IP_ROUTE.IP_ADDRESS IS 'Die IP der zusaetzlichen Route';
COMMENT ON COLUMN T_IP_ROUTE.PREFIX_LENGTH IS 'Die Laenge der zusaetzlichen Route';
COMMENT ON COLUMN T_IP_ROUTE.METRIK IS 'Die Metrik der zusaetzlichen Route';

create SEQUENCE S_T_IP_ROUTE_0 start with 1;
grant select on S_T_IP_ROUTE_0 to public;

ALTER TABLE T_IP_ROUTE ADD CONSTRAINT PK_T_IP_ROUTE PRIMARY KEY (ID);

CREATE INDEX IX_FK_IPROUTE_2_AUFTRAG ON T_IP_ROUTE (AUFTRAG_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_IP_ROUTE ADD CONSTRAINT FK_IPROUTE_2_AUFTRAG
  FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

GRANT SELECT ON T_IP_ROUTE TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_IP_ROUTE TO R_HURRICAN_USER;

CREATE OR REPLACE TRIGGER TRBIU_IP_ROUTES BEFORE INSERT OR UPDATE on T_IP_ROUTE
for each row
begin
   -- DATEW setzen
   SELECT CURRENT_TIMESTAMP into :new.DATEW FROM dual;
end;
/
