apiVersion: v1
kind: Service
metadata:
  name: SERVICE-APP-service
  namespace: NAMESPACE
spec:
  $patch: replace
  selector:
    app: SERVICE-APP
  ports:
    - $patch: replace
    - port: 8080
      targetPort: 8080