-- Im Feld UEVT der Tabelle T_RSM_EQ_COUNT landet das Feld RANG_VERTEILER der T_EQUIPMENT Tabelle
-- RANG VERTEILER ist vom Typ VARCHAR2(40 BYTE)
ALTER TABLE T_RSM_EQ_COUNT MODIFY(UEVT VARCHAR2(40 BYTE));