
alter table T_CB_VORGANG_SUB_ORDER add RET_LBZ VARCHAR2(30 BYTE);
alter table T_CB_VORGANG_SUB_ORDER add RET_VTRNR VARCHAR2(25 BYTE);
alter table T_CB_VORGANG_SUB_ORDER add RET_AQS VARCHAR2(70 BYTE);
alter table T_CB_VORGANG_SUB_ORDER add RET_LL VARCHAR2(70 BYTE);

