-- Reset Sequence for T_VERLAUF_ABTEILUNG_STATUS
DROP SEQUENCE S_T_VERLAUF_ABTEILUNG_STATUS_0;
CREATE SEQUENCE S_T_VERLAUF_ABTEILUNG_STATUS_0
    INCREMENT BY 1 START WITH 11;
-- Grants for sequence
GRANT SELECT ON S_T_VERLAUF_ABTEILUNG_STATUS_0 TO PUBLIC;

-- New Values for Netzplanung
Insert into T_VERLAUF_ABTEILUNG_STATUS
   (ID, ABTEILUNG_ID, STATUS)
 Values
   (S_T_VERLAUF_ABTEILUNG_STATUS_0.nextval, 11, 'Klärung intern');
Insert into T_VERLAUF_ABTEILUNG_STATUS
   (ID, ABTEILUNG_ID, STATUS)
 Values
   (S_T_VERLAUF_ABTEILUNG_STATUS_0.nextval, 11, 'Rückmeldung Kunde fehlt');
Insert into T_VERLAUF_ABTEILUNG_STATUS
   (ID, ABTEILUNG_ID, STATUS)
 Values
   (S_T_VERLAUF_ABTEILUNG_STATUS_0.nextval, 11, 'Störung');
Insert into T_VERLAUF_ABTEILUNG_STATUS
   (ID, ABTEILUNG_ID, STATUS)
 Values
   (S_T_VERLAUF_ABTEILUNG_STATUS_0.nextval, 11, 'Negativliste');
