
update T_PRODUKT set CPS_ACCOUNT_TYPE='DIALIN' where CPS_ACCOUNT_TYPE='DIAL_IN';
update T_PRODUKT set CPS_ACCOUNT_TYPE='MAXI' where CPS_ACCOUNT_TYPE='MAXI-HSI';
update T_PRODUKT set CPS_ACCOUNT_TYPE='SDSL' where CPS_ACCOUNT_TYPE='SDSL-HSI';


