
ALTER TABLE T_HW_BAUGRUPPEN_TYP ADD (HVT_TECHNIK_ID  NUMBER(10));
COMMENT ON COLUMN T_HW_BAUGRUPPEN_TYP.HVT_TECHNIK_ID IS 'Hersteller';

ALTER TABLE T_HW_BAUGRUPPEN_TYP ADD CONSTRAINT FK_BG_TYP_TECHNIK
 FOREIGN KEY (HVT_TECHNIK_ID) REFERENCES T_HVT_TECHNIK (ID)
    DEFERRABLE INITIALLY IMMEDIATE;


update T_HW_BAUGRUPPEN_TYP set HVT_TECHNIK_ID = 6
where name in ('ADLTK', 'ADLTN', 'ABLTF', 'EBLTD', 'EBLTF', 'NALTD', 'NSLTA', 'SHLTB', 'SMLTA', 'SMLTC', 'SMLTJ');

update T_HW_BAUGRUPPEN_TYP set HVT_TECHNIK_ID = 1
where name in ('SLMAFPE', 'SLMAITF', 'SLMAITFG', 'SLMDTFB', 'SLMDTFC');
