INSERT INTO T_DSLAM_PROFILE (
   ID, NAME, BEMERKUNG,
   DOWNSTREAM, UPSTREAM, FASTPATH,
   UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS,
   FASTPATH_TECH_LS, GUELTIG)
VALUES (S_T_DSLAM_PROFILE_0.nextVal, 'MAXI_8000_1280_F_D001' , 1,
    '8000', '1280', 0,
    'H13', null, null,
    1, 1);

INSERT INTO T_DSLAM_PROFILE (
   ID, NAME, BEMERKUNG,
   DOWNSTREAM, UPSTREAM, FASTPATH,
   UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS,
   FASTPATH_TECH_LS, GUELTIG)
VALUES (S_T_DSLAM_PROFILE_0.nextVal, 'MMAX_16000_1280_F_D001_ADSL1' , 1,
    '16000', '1280', 0,
    'H04', null, null,
    1, 1);

INSERT INTO T_DSLAM_PROFILE (
   ID, NAME, BEMERKUNG,
   DOWNSTREAM, UPSTREAM, FASTPATH,
   UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS,
   FASTPATH_TECH_LS, GUELTIG)
VALUES (S_T_DSLAM_PROFILE_0.nextVal, 'KiTa_128_768_ADSL1' , 1,
    '768', '128', 0,
    'H04', null, null,
    1, 1);

INSERT INTO T_DSLAM_PROFILE (
   ID, NAME, BEMERKUNG,
   DOWNSTREAM, UPSTREAM, FASTPATH,
   UETV, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS,
   FASTPATH_TECH_LS, GUELTIG)
VALUES (S_T_DSLAM_PROFILE_0.nextVal, 'KiTa_128_768' , 1,
    '768', '128', 0,
    'H13', null, null,
    1, 1);

