
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (275, 'Direct-Access, 2 Mbit/s, X.21, NTL, Standard', NULL,
   30174, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (276, 'Direct-Access, 2 Mbit/s, G703, NTL, Standard', NULL,
   30175, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (277, 'Direct-Access, 2 Mbit/s, Ethernet, NTL, Standard', NULL,
   30176, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (278, 'Direct-Access, 4 Mbit/s, X.21, NTL, Standard', NULL,
   30177, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (279, 'Direct-Access, 4 Mbit/s, Ethernet, NTL, Standard', NULL,
   30178, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (280, 'Direct-Access, 6 Mbit/s, Ethernet, NTL, Standard', NULL,
   30179, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (281, 'Direct-Access, 8 Mbit/s, Ethernet, NTL, Standard', NULL,
   30180, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (282, 'Direct-Access, 10 Mbit/s, Ethernet, NTL, Standard', NULL,
   30181, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (283, 'Direct-Access, 20 Mbit/s, Ethernet, NTL, Standard', NULL,
   30182, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (284, 'Direct-Access, 25 Mbit/s, Ethernet, NTL,Standard', NULL,
   30183, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (285, 'Direct-Access, 30 Mbit/s, Ethernet, NTL,Standard', NULL,
   30184, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (286, 'Direct-Access, 34 Mbit/s, NTL,Standard', NULL,
   30185, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (287, 'Direct-Access, 50 Mbit/s, Ethernet, NTL,Standard', NULL,
   30186, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (288, 'Direct-Access, 100 Mbit/s, Ethernet, NTL,Standard', NULL,
   30187, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (289, 'Direct-Access, 155 Mbit/s, NTL,Standard', NULL,
   30188, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (290, 'Direct-Access, 1 Gbit/s, Ethernet, NTL,Standard', NULL,
   30189, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (291, 'Direct-Access, 10 Gbit/s, Ethernet, NTL,Standard', NULL,
   30190, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);

Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (292, 'Direct-Access, gem‰ﬂ Vereinbarung, Standard', NULL,
   30191, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL, '1', '0', '1', '0', '0',
    '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);


insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 2 Mbit/s, X.21, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 2 Mbit/s, G703, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 2 Mbit/s, Ethernet, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 4 Mbit/s, X.21, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 4 Mbit/s, Ethernet, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 6 Mbit/s, Ethernet, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 8 Mbit/s, Ethernet, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 10 Mbit/s, Ethernet, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 20 Mbit/s, Ethernet, NTL, Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 25 Mbit/s, Ethernet, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 30 Mbit/s, Ethernet, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 34 Mbit/s, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 50 Mbit/s, Ethernet, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 100 Mbit/s, Ethernet, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 155 Mbit/s, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 1 Gbit/s, Ethernet, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, 10 Gbit/s, Ethernet, NTL,Standard'));
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 455, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='Direct-Access, gem‰ﬂ Vereinbarung, Standard'));

