
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (293, '10GBASE-X, 10 Gbit/s, Singlemode', NULL,
   30192, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL,
    '1', '0', '1', '0', '0', '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 451, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='10GBASE-X, 10 Gbit/s, Singlemode'));


Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_MISC__NO, EXTERN_LEISTUNG__NO, TYP,
    LONG_VALUE, STR_VALUE, PARAMETER, PROD_NAME_STR, DESCRIPTION,
    DISPO, EWSD, SDH, IPS, SCT,
    CHECK_QUANTITY, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION)
 Values
   (294, '10GBASE-X, 10 Gbit/s, Multimode', NULL,
   30193, 'CONNECT_LEITUNG', NULL, NULL, NULL, ' ', NULL,
    '1', '0', '1', '0', '0', '1', '1', TO_DATE('01/08/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0);
insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, IS_DEFAULT, TECH_LS_ID)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 451, '0',
  (select t.ID from T_TECH_LEISTUNG t where t.NAME='10GBASE-X, 10 Gbit/s, Multimode'));


