ALTER TABLE T_RANGIERUNG MODIFY(FREIGEGEBEN VARCHAR2(15 BYTE));

UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'gesperrt' WHERE FREIGEGEBEN = '0';
UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'freigegeben' WHERE FREIGEGEBEN = '1';
UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'deactivated' WHERE FREIGEGEBEN = '2';
UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'Backbone_down' WHERE FREIGEGEBEN = '4';
UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'WEPLA' WHERE FREIGEGEBEN = '5';
UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'defekt' WHERE FREIGEGEBEN = '7';
UPDATE T_RANGIERUNG SET FREIGEGEBEN = 'in_Aufbau' WHERE FREIGEGEBEN = '9';

ALTER TABLE T_HW_BG_CHANGE_PORT2PORT MODIFY(RANG_FREIGABE_ORIG_OLD VARCHAR2(15 BYTE));

UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'gesperrt' WHERE RANG_FREIGABE_ORIG_OLD = '0';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'freigegeben' WHERE RANG_FREIGABE_ORIG_OLD = '1';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'deactivated' WHERE RANG_FREIGABE_ORIG_OLD = '2';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'Backbone_down' WHERE RANG_FREIGABE_ORIG_OLD = '4';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'WEPLA' WHERE RANG_FREIGABE_ORIG_OLD = '5';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'defekt' WHERE RANG_FREIGABE_ORIG_OLD = '7';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_OLD = 'in_Aufbau' WHERE RANG_FREIGABE_ORIG_OLD = '9';

ALTER TABLE T_HW_BG_CHANGE_PORT2PORT MODIFY(RANG_FREIGABE_ORIG_NEW VARCHAR2(15 BYTE));

UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'gesperrt' WHERE RANG_FREIGABE_ORIG_NEW = '0';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'freigegeben' WHERE RANG_FREIGABE_ORIG_NEW = '1';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'deactivated' WHERE RANG_FREIGABE_ORIG_NEW = '2';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'Backbone_down' WHERE RANG_FREIGABE_ORIG_NEW = '4';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'WEPLA' WHERE RANG_FREIGABE_ORIG_NEW = '5';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'defekt' WHERE RANG_FREIGABE_ORIG_NEW = '7';
UPDATE T_HW_BG_CHANGE_PORT2PORT SET RANG_FREIGABE_ORIG_NEW = 'in_Aufbau' WHERE RANG_FREIGABE_ORIG_NEW = '9';
