-- INSERT MODEM TO T_EG
INSERT INTO T_EG VALUES(666, 666, 'Modem', 'Modem fuer GFast Technologie', 'Modem', NULL, TO_DATE('2016-10-17', 'YYYY-MM-DD'),
                             TO_DATE('2200-01-01', 'YYYY-MM-DD'), NULL, NULL, 1, 1, 0, 4, 0, 1, NULL, NULL);

-- INSERT MAPPINGS FROM PRODUCTS TO MODEM
-- FTTX DSL + FON
INSERT INTO T_PROD_2_EG(ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES(S_T_PROD_2_EG_0.nextval, 513, 666, 0, 1, 0);
-- Premium Glasfaser-DSL Doppel-Flat
INSERT INTO T_PROD_2_EG(ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES(S_T_PROD_2_EG_0.nextval, 540, 666, 0, 1, 0);
-- Glasfaser SDSL
INSERT INTO T_PROD_2_EG(ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES(S_T_PROD_2_EG_0.nextval, 541, 666, 0, 1, 0);
-- Glasfaser ADSL
INSERT INTO T_PROD_2_EG(ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION) VALUES(S_T_PROD_2_EG_0.nextval, 542, 666, 0, 1, 0);