
-- create table for g.fast profile
create table T_GFAST_PROFILE (
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    NAME VARCHAR2(500) NOT NULL,
    BAUGRUPPE_TYP_ID NUMBER(19),
    VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

GRANT SELECT, INSERT, UPDATE ON T_GFAST_PROFILE TO R_HURRICAN_USER;
GRANT SELECT ON T_GFAST_PROFILE TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_GFAST_PROFILE_0 START WITH 1 MAXVALUE 9999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
GRANT SELECT ON S_T_GFAST_PROFILE_0 TO PUBLIC;


-- create table for g.fast profile defaults
create table T_GFAST_PROFILE_DEFAULTS (
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    PROFILE_ID NUMBER(19) NOT NULL,
    PARAMETER_NAME VARCHAR2(2000) NOT NULL,
    PARAMETER_VALUE VARCHAR2(2000),
    PARAMETER_TYP VARCHAR2(100),
    IS_DEFAULT NUMBER(1) DEFAULT 0 NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

GRANT SELECT, INSERT, UPDATE ON T_GFAST_PROFILE_DEFAULTS TO R_HURRICAN_USER;
GRANT SELECT ON T_GFAST_PROFILE_DEFAULTS TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_GFAST_PROFILE_DEFAULTS_0 START WITH 1 MAXVALUE 9999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
GRANT SELECT ON S_T_GFAST_PROFILE_DEFAULTS_0 TO PUBLIC;


-- create table for g.fast values
create table T_GFAST_AUFTRAG_VALUES (
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    AUFTRAG_ID NUMBER(19) NOT NULL,
    PARAMETER_NAME VARCHAR2(2000) NOT NULL,
    PARAMETER_VALUE VARCHAR2(2000),
    PARAMETER_TYP VARCHAR2(100),
    VALID_FROM DATE,
    VALID_TO DATE,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

CREATE INDEX IX_GFAST_AUFTRAG_VALUE ON T_GFAST_AUFTRAG_VALUES (AUFTRAG_ID);

GRANT SELECT, INSERT, UPDATE ON T_GFAST_AUFTRAG_VALUES TO R_HURRICAN_USER;
GRANT SELECT ON T_GFAST_AUFTRAG_VALUES TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_GFAST_AUFTRAG_VALUES_0 START WITH 1 MAXVALUE 9999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
GRANT SELECT ON S_T_GFAST_AUFTRAG_VALUES_0 TO PUBLIC;


-- create table for g.fast parameters mapper
create table T_GFAST_PARAMETER_MAPPER (
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    PARAM_NAME VARCHAR2(2000) NOT NULL,
    PARAM_GUI_NAME VARCHAR2(2000),
    PARAM_GUI_DESCRIPTION VARCHAR2(2000),
    PARAM_CPS_NAME VARCHAR2(2000),
    VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IX_GFAST_PARAM_MAPPER_NAME ON T_GFAST_PARAMETER_MAPPER (PARAM_NAME);

GRANT SELECT, INSERT, UPDATE ON T_GFAST_PARAMETER_MAPPER TO R_HURRICAN_USER;
GRANT SELECT ON T_GFAST_PARAMETER_MAPPER TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_GFAST_PARAMETER_MAPPER_0 START WITH 1 MAXVALUE 9999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
GRANT SELECT ON S_T_GFAST_PARAMETER_MAPPER_0 TO PUBLIC;

