DROP TABLE T_GFAST_PROFILE;
DROP SEQUENCE S_T_GFAST_PROFILE_0;

ALTER TABLE T_GFAST_PROFILE_DEFAULTS DROP COLUMN PROFILE_ID;
ALTER TABLE T_GFAST_PROFILE_DEFAULTS ADD HW_BAUGRUPPEN_TYP_ID NUMBER(19);

ALTER TABLE T_GFAST_PROFILE_DEFAULTS add constraint FK_BAUGRUPPE_TYP_ID foreign key (HW_BAUGRUPPEN_TYP_ID) references T_HW_BAUGRUPPEN_TYP(id);


