INSERT INTO T_PROFILE_DEFAULT VALUES (1,'Rate Up','18',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','25',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','30',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','50',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','100',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','150',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','300',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','500',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','800',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','1',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','2,5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','10',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','20',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','30',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','40',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','50',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','100',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','6',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','7',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','8',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','9',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','10',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','11',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','12',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','13',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','14',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','15',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','16',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','17',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','18',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','19',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','20',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','21',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','6',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','7',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','8',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','9',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','10',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','11',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Startfrequenz','2.2 MHz',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Startfrequenz','17 MHz',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Startfrequenz','35 MHz',0,0,1515);

/* Baugruppe 1516 MA5811S_DE16 */

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','18',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','25',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','30',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','50',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','100',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','150',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','300',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','500',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Up','800',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','1',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','2,5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','10',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','20',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','30',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','40',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','50',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Rate Down','100',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'G.fast Line Spectrum','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'SOS','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Virtual Noise','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INM','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'RFI','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'UPBO','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','6',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','7',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','8',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','9',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','10',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','11',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','12',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','13',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','14',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','15',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','16',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','17',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','18',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','19',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','20',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'DPBO','21',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','6',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','7',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','8',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','9',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','10',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'noise margin','11',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','5',0,1,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'INP Delay','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Startfrequenz','2.2 MHz',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Startfrequenz','17 MHz',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES ((SELECT max(id)+1 FROM T_PROFILE_DEFAULT),'Startfrequenz','35 MHz',0,0,1516);