DROP SEQUENCE S_T_PROFILE_DEFAULTS_0;
CREATE SEQUENCE S_T_PROFILE_DEFAULTS_0 START WITH 1 MAXVALUE 9999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
GRANT SELECT ON S_T_PROFILE_DEFAULTS_0 TO PUBLIC;

TRUNCATE TABLE T_PROFILE_DEFAULT;

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','18',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','25',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','30',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','50',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','100',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','150',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','300',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','500',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','800',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','1',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','2,5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','10',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','20',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','30',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','40',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','50',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','100',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','6',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','7',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','8',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','9',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','10',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','11',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','12',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','13',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','14',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','15',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','16',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','17',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','18',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','19',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','20',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','21',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','5',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','6',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','7',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','8',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','9',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','10',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','11',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','2',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','3',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','4',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','5',1,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','6',0,0,1515);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Startfrequenz','2.2 MHz',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Startfrequenz','17 MHz',0,0,1515);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Startfrequenz','35 MHz',0,0,1515);

/* Baugruppe 1516 MA5811S_DE16 */

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','18',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','25',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','30',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','50',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','100',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','150',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','300',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','500',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Up','800',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','1',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','2,5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','10',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','20',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','30',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','40',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','50',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Rate Down','100',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'G.fast Line Spectrum','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'SOS','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Virtual Noise','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INM','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'RFI','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','5',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'UPBO','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','6',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','7',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','8',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','9',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','10',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','11',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','12',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','13',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','14',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','15',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','16',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','17',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','18',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','19',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','20',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'DPBO','21',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','5',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','6',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','7',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','8',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','9',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','10',1,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'noise margin','11',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','2',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','3',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','4',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','5',0,1,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'INP Delay','6',0,0,1516);

INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Startfrequenz','2.2 MHz',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Startfrequenz','17 MHz',0,0,1516);
INSERT INTO T_PROFILE_DEFAULT VALUES (S_T_PROFILE_DEFAULTS_0.nextval,'Startfrequenz','35 MHz',0,0,1516);