CREATE TABLE T_PROFILE_AUFTRAG (
  ID               NUMBER(19) PRIMARY KEY NOT NULL,
  AUFTRAG_ID       NUMBER(19),
  EQUIPMENT_ID     NUMBER(19)             NOT NULL,
  CHANGE_REASON_ID NUMBER(19)             NOT NULL,
  BEMERKUNG        VARCHAR2(255),
  GUELTIG_VON      DATE                   NOT NULL,
  GUELTIG_BIS      DATE                   NOT NULL,
  USERW            VARCHAR2(255)          NOT NULL,
  VERSION          NUMBER(19) DEFAULT 0   NOT NULL
);

GRANT SELECT, INSERT, UPDATE ON T_PROFILE_AUFTRAG TO R_HURRICAN_USER;
GRANT SELECT ON T_PROFILE_AUFTRAG TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_PROFILE_AUFTRAG_0 START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
GRANT SELECT ON S_T_PROFILE_AUFTRAG_0 TO PUBLIC;
