DELETE FROM T_PROFILE_AUFTRAG_VALUE;

ALTER TABLE T_PROFILE_AUFTRAG_VALUE
  DROP (ID, AUFTRAG_ID, EQUIPMENT_ID, VALID_FROM, VALID_TO, VERSION);

ALTER TABLE T_PROFILE_AUFTRAG_VALUE
  ADD PROFILE_AUFTRAG_ID NUMBER(19, 0) NOT NULL;

ALTER TABLE T_PROFILE_AUFTRAG_VALUE
  ADD FOREIGN KEY (PROFILE_AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

ALTER TABLE T_PROFILE_AUFTRAG_VALUE
  ADD CONSTRAINT UK_T_PRF_AUFTR_VAL_PNAME_PA_ID UNIQUE (PARAMETER_NAME, PROFILE_AUFTRAG_ID);
