ALTER TABLE T_PROFILE_AUFTRAG_VALUE
  ADD CONSTRAINT FK_T_PROFILE_AUFTRAG_VAL_A_ID FOREIGN KEY (PROFILE_AUFTRAG_ID) REFERENCES T_PROFILE_AUFTRAG (ID);

ALTER TABLE T_PROFILE_AUFTRAG_VALUE
  ADD CONSTRAINT UK_T_PRF_AUFTR_VAL_PNAME_PA_ID UNIQUE (PARAMETER_NAME, PROFILE_AUFTRAG_ID);
