ALTER TABLE T_PROFILE_PARAMETER_MAPPER ADD SORTORDER NUMBER;

INSERT INTO T_PROFILE_PARAMETER_MAPPER VALUES(S_T_PROFILE_PARAMETER_MAPPER_0.nextval, 'Rate Down', 'Rate Down', NULL, NULL, 0, 1);
INSERT INTO T_PROFILE_PARAMETER_MAPPER VALUES(S_T_PROFILE_PARAMETER_MAPPER_0.nextval, 'Rate Up', 'Rate Up', NULL, NULL, 0, 2);

DECLARE
	x NUMBER := 3;
BEGIN
	FOR entry IN(SELECT DISTINCT pd.PARAMETER_NAME FROM T_PROFILE_DEFAULT pd WHERE pd.IS_DEFAULT = 1 AND pd.PARAMETER_NAME != 'Rate Up' AND pd.PARAMETER_NAME != 'Rate Down' ORDER BY pd.PARAMETER_NAME)
	LOOP
		INSERT INTO T_PROFILE_PARAMETER_MAPPER VALUES(S_T_PROFILE_PARAMETER_MAPPER_0.nextval, entry.PARAMETER_NAME, entry.PARAMETER_NAME, NULL, NULL, 0, x);
		x := x + 1;
	END LOOP;
END;
/