rename T_PROFILE_DEFAULT to T_PROFILE_PARAMETER;
rename S_T_PROFILE_DEFAULTS_0 to S_T_PROFILE_PARAMTER_0;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_PROFILE_PARAMETER TO R_HURRICAN_USER;
GRANT SELECT ON T_PROFILE_PARAMETER TO R_HURRICAN_READ_ONLY;
GRANT SELECT ON S_T_PROFILE_PARAMTER_0 TO PUBLIC;
