DELETE FROM T_RANGIERUNGSMATRIX WHERE PROD_ID = 511 AND PRODUKT2PHYSIKTYP_ID = (SELECT id FROM T_PRODUKT_2_PHYSIKTYP WHERE PHYSIKTYP = 810 AND PROD_ID = 511);

DELETE FROM T_RANGIERUNGSMATRIX WHERE PROD_ID = 512 AND PRODUKT2PHYSIKTYP_ID = (SELECT id FROM T_PRODUKT_2_PHYSIKTYP WHERE PHYSIKTYP = 810 AND PROD_ID = 512);

DELETE FROM T_RANGIERUNGSMATRIX WHERE PROD_ID = 513 AND PRODUKT2PHYSIKTYP_ID = (SELECT id FROM T_PRODUKT_2_PHYSIKTYP WHERE PHYSIKTYP = 810 AND PROD_ID = 513);

DELETE FROM T_RANGIERUNGSMATRIX WHERE PROD_ID = 541 AND PRODUKT2PHYSIKTYP_ID = (SELECT id FROM T_PRODUKT_2_PHYSIKTYP WHERE PHYSIKTYP = 810 AND PROD_ID = 541);

DELETE FROM T_RANGIERUNGSMATRIX WHERE PROD_ID = 542 AND PRODUKT2PHYSIKTYP_ID = (SELECT id FROM T_PRODUKT_2_PHYSIKTYP WHERE PHYSIKTYP = 810 AND PROD_ID = 542);