update  T_CARRIER_CONTACT set CONTACT_NAME =  'Jan Bükers'
where BRANCH_OFFICE = 'WBCI-Eskalationskontakt'
and FAULT_CLEARING_EMAIL = 'buekers@sipgate.de'
and CARRIER_ID in
(SELECT ID FROM T_CARRIER WHERE PORTIERUNGSKENNUNG = 'D248' or  PORTIERUNGSKENNUNG = 'D218' or PORTIERUNGSKENNUNG = 'D146');
