-- Aktualisiert die Namen fuer CPS-Mapping
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165DPBOPROF'
WHERE PARAM_NAME = 'DPBO';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165SPECTRUMPROF'
WHERE PARAM_NAME = 'G.fast Line Spectrum';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165INMPROFILE'
WHERE PARAM_NAME = 'INM';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165CH1INPPROF'
WHERE PARAM_NAME = 'INP Delay';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165RFIPROF'
WHERE PARAM_NAME = 'RFI';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165CH1DSPROF'
WHERE PARAM_NAME = 'Rate Down';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165CH1USPROF'
WHERE PARAM_NAME = 'Rate Up';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165SOSPROF'
WHERE PARAM_NAME = 'SOS';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165UPBOPROF'
WHERE PARAM_NAME = 'UPBO';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165VNPROF'
WHERE PARAM_NAME = 'Virtual Noise';
UPDATE T_PROFILE_PARAMETER_MAPPER
SET PARAM_CPS_NAME = 'TR165NMPROF'
WHERE PARAM_NAME = 'noise margin';
