INSERT INTO T_PROFILE_PARAMETER_MAPPER VALUES
  (S_T_PROFILE_PARAMETER_MAPPER_0.nextval, 'TDD Profil', 'TDD-Profil', NULL, 'GFASTROFID', 0, 12);

INSERT INTO T_PROFILE_PARAMETER (
  SELECT
    S_T_PROFILE_PARAMETER_0.nextval, 'TDD Profil', '3', 1, 0, BGID.S1
  FROM DUAL, (SELECT DISTINCT HW_BAUGRUPPEN_TYP_ID AS S1
              FROM T_PROFILE_PARAMETER) BGID);
