-- ANF-756 GK-Produktkonfiguration 'ALL IP' Produkt loeschen und neu anlegen
CREATE OR REPLACE PROCEDURE delete_report_2_prod(prodid in NUMBER)
IS
 BEGIN
  FOR r_2_p IN (SELECT r2p.ID FROM T_REPORT_2_PROD r2p WHERE r2p.PROD_ID = prodid) LOOP
   DELETE FROM T_REP2PROD_STATI where REP2PROD_ID = r_2_p.id;
  END LOOP;
 END;
/

call delete_report_2_prod(543);
call delete_report_2_prod(544);

drop PROCEDURE delete_report_2_prod;

delete from T_REPORT_2_PROD where prod_Id = 543 or prod_Id = 544;

delete from T_PROD_2_PROD where prod_src = 543 or prod_src = 544;
delete from T_PROD_2_PROD where prod_dest = 543 or prod_dest = 544;
delete from T_PRODUKT_2_SCHNITTSTELLE where prod_Id = 543 or prod_Id = 544;
delete from T_CPS_DATA_CHAIN_CONFIG  where prod_Id = 543 or prod_Id = 544;
delete from T_SPERRE_VERTEILUNG where prod_Id = 543 or prod_Id = 544;
delete from T_PRODUKT_EQ_CONFIG where prod_Id = 543 or prod_Id = 544;
delete from T_PRODUKT_2_TECH_LOCATION_TYPE where prod_Id = 543 or prod_Id = 544;
delete from T_PRODUKT_2_PHYSIKTYP where prod_Id = 543 or prod_Id = 544;
delete from T_PROD_2_SIP_DOMAIN where prod_Id = 543 or prod_Id = 544;
delete from T_PROD_2_DSLAMPROFILE where prod_Id = 543 or prod_Id = 544;
delete from T_BA_VERL_AEND_PROD_2_GRUPPE where prod_Id = 543 or prod_Id = 544;
delete from T_PROD_2_TECH_LEISTUNG where prod_Id = 543 or prod_Id = 544;
delete from T_PRODUKT_MAPPING where prod_Id = 543 or prod_Id = 544;
delete from T_PROD_2_EG where prod_Id = 543 or prod_Id = 544;
delete from T_Produkt where prod_Id = 543 or prod_Id = 544;
delete from T_SERVICE_COMMAND_MAPPING where REF_Id = (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check') and REF_CLASS = 'de.augustakom.hurrican.model.cc.command.ServiceChain';
delete from T_SERVICE_CHAIN where name = 'GK-TAL-VoIP-Check';
delete from T_SERVICE_COMMAND_MAPPING where REF_Id = (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT') and REF_CLASS = 'de.augustakom.hurrican.model.cc.command.ServiceChain';
delete from T_SERVICE_CHAIN where name = 'CPS - GK DSL+VoiP am HVT';


Insert into T_SERVICE_CHAIN(ID, NAME, TYPE, VERSION)
 Values (S_T_SERVICE_CHAIN_0.nextval, 'GK-TAL-VoIP-Check', 'VERLAUF_CHECK', 0);


Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2013, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 1, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2000, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 2, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2001, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 3, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2009, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 4, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2004, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 5, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2018, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 6, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2005, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 7, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2006, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 8, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2007, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 9, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2008, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 10, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2017, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 11, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2025, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 12, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2027, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 13, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2028, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 14, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2010, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 15, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 2026, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 16, 0);

Insert into T_SERVICE_CHAIN(ID, NAME, TYPE, VERSION)
 Values (S_T_SERVICE_CHAIN_0.nextval, 'CPS - GK DSL+VoiP am HVT', 'cPS_DATA', 0);


Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 5001, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 1, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 5003, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 2, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 5004, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 3, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 5005, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 4, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 5002, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 5, 0);
Insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO, VERSION)
 Values (S_T_SERVICE_COMMAND_MAPPI_0.nextval, 5013, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - GK DSL+VoiP am HVT'), 'de.augustakom.hurrican.model.cc.command.ServiceChain', 6, 0);


INSERT INTO T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
    GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ENDSTELLEN_TYP, BESCHREIBUNG, ACCOUNT_VORS,
    LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
    EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID,
    BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
    TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER, VIER_DRAHT, MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN,
    IP_POOL, IP_PURPOSE_V4, IP_PURPOSE_V4_EDITABLE, IP_NETMASK_SIZE_V4, IP_NETMASK_SIZE_V6, IP_NETMASK_SIZE_EDITABLE,
    AUTOMATION_POSSIBLE, "SWITCH", GEOID_SRC, SDSL_N_DRAHT, AUTO_HVT_ZUORDNUNG, SMS_VERSAND, ERSTELL_STATUS_ID, KUENDIGUNG_STATUS_ID,
    BUENDEL_BILLING_HAUPTAUFTRAG, SEND_STATUS_UPDATE, AFTR_ADDRESS, P_BIT_DATEN, P_BIT_VOIP )
 VALUES
   (543,                                    -- PROD_ID
    18,                                     -- PRODUKTGRUPPE_ID
    NULL,                                   -- PRODUKT_NR
    'Premium DSL + VoIP',                   -- ANSCHLUSSART
    'Premium DSL {DOWNSTREAM} VoIP',        -- PROD_NAME_PATTERN
    NULL,                                   -- LEITUNGSART
    1,                                      -- AKTIONS_ID
    10,                                     -- MAX_DN_COUNT
    '0',                                    -- DN_BLOCK
    60,                                     -- DN_TYP
    TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), -- GUELTIG_VON
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), -- GUELTIG_BIS
    '0',                                    -- AUFTRAGSERSTELLUNG
    '1',                                    -- LTGNR_ANLEGEN
    '0',                                    -- BRAUCHT_BUENDEL
    '1',                                    -- ELVERLAUF
    1,                                      -- ENDSTELLEN_TYP
    NULL,                                   -- BESCHREIBUNG
    'XA',                                   -- ACCOUNT_VORS
    1,                                      -- LI_NR
    '1',                                    -- VPN_PHYSIK
    '0',                                    -- PROJEKTIERUNG
    '0',                                    -- IS_PARENT
    '0',                                    -- CHECK_CHILD
    '1',                                    -- IS_COMBI_PRODUKT
    '1',                                    -- AUTO_PRODUCT_CHANGE
    '1',                                    -- EXPORT_KDP_M
    '1',                                    -- CREATE_KDP_ACCOUNT_REPORT
    NULL,                                   -- EXPORT_AK_PRODUKTE
    4,                                      -- VERTEILUNG_DURCH
    '0',                                    -- BA_RUECKLAEUFER
    NULL,                                   -- PROJEKTIERUNG_CHAIN_ID
    (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'GK-TAL-VoIP-Check'), -- VERLAUF_CHAIN_ID
    13,                                     -- VERLAUF_CANCEL_CHAIN_ID
    '1',                                    -- BA_CHANGE_REALDATE
    '0',                                    -- CREATE_AP_ADDRESS
    '0',                                    -- ASSIGN_IAD
    '1',                                    -- CPS_PROVISIONING
    'PremiumDSL+VoIP',                             -- CPS_PROD_NAME
    '1',                                    -- CPS_AUTO_CREATION
    'MAXI',                                 -- CPS_ACCOUNT_TYPE
    '1',                                    -- CPS_DSL_PRODUCT
    'W',                                    -- TDN_KIND_OF_USE_PRODUCT
    'A',                                    -- TDN_KIND_OF_USE_TYPE
    NULL,                                   -- TDN_USE_FROM_MASTER
    '0',                                    -- VIER_DRAHT
    3,                                      -- MIN_DN_COUNT
    NULL,                                   -- TDN_KIND_OF_USE_TYPE_VPN
    1,                                      -- IP_POOL
    22371,                                  -- IP_PURPOSE_V4
    '0',                                    -- IP_PURPOSE_V4_EDITABLE
    32,                                     -- IP_NETMASK_SIZE_V4
    48,                                     -- IP_NETMASK_SIZE_V6
    '1',                                    -- IP_NETMASK_SIZE_EDITABLE
    '1',                                    -- AUTOMATION_POSSIBLE
    21,                                     -- SWITCH
    'HVT',                                  -- GEOID_SRC
    NULL,                                   -- SDSL_N_DRAHT
    '1',                                    -- AUTO_HVT_ZUORDNUNG
    '0',                                    -- SMS_VERSAND
    NULL,                                   -- ERSTELL_STATUS_ID
    NULL,                                   -- KUENDIGUNG_STATUS_ID
    '0',                                    -- BUENDEL_BILLING_HAUPTAUFTRAG
    '1',                                    -- SEND_STATUS_UPDATE
    NULL,               -- AFTR_ADDRESS
    1,                                      -- P_BIT_DATEN
    5);                                     -- P_BIT_VOIP

INSERT INTO T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
    GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ENDSTELLEN_TYP, BESCHREIBUNG, ACCOUNT_VORS,
    LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
    EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID,
    BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
    TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER, VIER_DRAHT, MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN,
    IP_POOL, IP_PURPOSE_V4, IP_PURPOSE_V4_EDITABLE, IP_NETMASK_SIZE_V4, IP_NETMASK_SIZE_V6, IP_NETMASK_SIZE_EDITABLE,
    AUTOMATION_POSSIBLE, "SWITCH", GEOID_SRC, SDSL_N_DRAHT, AUTO_HVT_ZUORDNUNG, SMS_VERSAND, ERSTELL_STATUS_ID, KUENDIGUNG_STATUS_ID,
    BUENDEL_BILLING_HAUPTAUFTRAG, SEND_STATUS_UPDATE, AFTR_ADDRESS, P_BIT_DATEN, P_BIT_VOIP )
 VALUES
   (544,                                    -- PROD_ID
    18,                                     -- PRODUKTGRUPPE_ID
    NULL,                                   -- PRODUKT_NR
    'Premium DSL only',              -- ANSCHLUSSART
    'Premium DSL {DOWNSTREAM} only (IPv6)', -- PROD_NAME_PATTERN
    NULL,                                   -- LEITUNGSART
    1,                                      -- AKTIONS_ID
    0,                                      -- MAX_DN_COUNT
    '0',                                    -- DN_BLOCK
    60,                                     -- DN_TYP
    TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), -- GUELTIG_VON
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    '0',                                    -- AUFTRAGSERSTELLUNG
    '1',                                    -- LTGNR_ANLEGEN
    '0',                                    -- BRAUCHT_BUENDEL
    '1',                                    -- ELVERLAUF
    1,                                      -- ENDSTELLEN_TYP
    NULL,                                   -- BESCHREIBUNG
    'XA',                                   -- ACCOUNT_VORS
    1,                                      -- LI_NR
    '1',                                    -- VPN_PHYSIK
    '0',                                    -- PROJEKTIERUNG
    '0',                                    -- IS_PARENT
    '0',                                    -- CHECK_CHILD
    '1',                                    -- IS_COMBI_PRODUKT
    '1',                                    -- AUTO_PRODUCT_CHANGE
    '1',                                    -- EXPORT_KDP_M
    '1',                                    -- CREATE_KDP_ACCOUNT_REPORT
    NULL,                                   -- EXPORT_AK_PRODUKTE
    4,                                      -- VERTEILUNG_DURCH
    '0',                                    -- BA_RUECKLAEUFER
    NULL,                                   -- PROJEKTIERUNG_CHAIN_ID
    16,                                     -- VERLAUF_CHAIN_ID
    15,                                     -- VERLAUF_CANCEL_CHAIN_ID
    '1',                                    -- BA_CHANGE_REALDATE
    '0',                                    -- CREATE_AP_ADDRESS
    '0',                                    -- ASSIGN_IAD
    '1',                                    -- CPS_PROVISIONING
    'PremiumDSL',                           -- CPS_PROD_NAME
    '1',                                    -- CPS_AUTO_CREATION
    'MAXI',                                 -- CPS_ACCOUNT_TYPE
    '1',                                    -- CPS_DSL_PRODUCT
    'W',                                    -- TDN_KIND_OF_USE_PRODUCT
    'A',                                    -- TDN_KIND_OF_USE_TYPE
    NULL,                                   -- TDN_USE_FROM_MASTER
    '0',                                    -- VIER_DRAHT
    0,                                      -- MIN_DN_COUNT
    NULL,                                   -- TDN_KIND_OF_USE_TYPE_VPN
    1,                                      -- IP_POOL
    22371,                                  -- IP_PURPOSE_V4
    '0',                                    -- IP_PURPOSE_V4_EDITABLE
    32,                                     -- IP_NETMASK_SIZE_V4
    48,                                     -- IP_NETMASK_SIZE_V6
    '1',                                    -- IP_NETMASK_SIZE_EDITABLE
    '1',                                    -- AUTOMATION_POSSIBLE
    NULL,                                   -- SWITCH
    'HVT',                                  -- GEOID_SRC
    NULL,                                   -- SDSL_N_DRAHT
    '1',                                    -- AUTO_HVT_ZUORDNUNG
    '0',                                    -- SMS_VERSAND
    NULL,                                   -- ERSTELL_STATUS_ID
    NULL,                                   -- KUENDIGUNG_STATUS_ID
    '0',                                    -- BUENDEL_BILLING_HAUPTAUFTRAG
    '1',                                    -- SEND_STATUS_UPDATE
    NULL,                                   -- AFTR_ADDRESS
    NULL,                                   -- P_BIT_DATEN
    NULL);                                  -- P_BIT_VOIP


-- Constraint UK_T_PRODUKT_2_PHYSIKTYP um PHYSIKTYP_ADDITIONAL erweitern
ALTER TABLE T_PRODUKT_2_PHYSIKTYP DROP CONSTRAINT UK_T_PRODUKT_2_PHYSIKTYP;
DROP INDEX UK_T_PRODUKT_2_PHYSIKTYP;
ALTER TABLE T_PRODUKT_2_PHYSIKTYP ADD CONSTRAINT UK_T_PRODUKT_2_PHYSIKTYP UNIQUE (PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, PARENTPHYSIKTYP_ID);


-- Physiktypenzuordnung
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 543, 102, 104, NULL, NULL, 1, 5, '1');                                                                         -- ADSL2+ (Alc-IP)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 543, 102, 103, NULL, NULL, 1, 5, '1');                                                                         -- ADSL2+ (Alc-IP)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 543, 105, NULL, NULL, NULL, 1, 10, '1');                                                                       -- ADSL2+ only (Alc-IP)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 543, 516, 512, NULL, NULL, 0, 5, '1');                                                                         -- ADSL2+ MS (H)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 543, 516, 508, NULL, NULL, 0, 5, '1');                                                                         -- ADSL2+ MS (H)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 543, 517, NULL, NULL, NULL, 0, 10, '1');                                                                       -- ADSL2+ only MS (H)

INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 544, 102, 104, NULL, NULL, 1, 5, '1');                                                                         -- ADSL2+ (Alc-IP)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 544, 102, 103, NULL, NULL, 1, 5, '1');                                                                         -- ADSL2+ (Alc-IP)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 544, 105, NULL, NULL, NULL, 0, 10, '1');                                                                       -- ADSL2+ only (Alc-IP)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 544, 516, 512, NULL, NULL, 0, 5, '1');                                                                         -- ADSL2+ MS (H)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 544, 516, 508, NULL, NULL, 0, 5, '1');                                                                         -- ADSL2+ MS (H)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
 VALUES (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 544, 517, NULL, NULL, NULL, 0, 10, '1');                                                                       -- ADSL2+ only MS (H)


-- Standorttypen
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 543, 11001, 1, 'IMPORT', SYSDATE, 0);                                      -- KVZ
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 543, 11009, 2, 'IMPORT', SYSDATE, 0);                                      -- GEWOFAG
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 543, 11000, 3, 'IMPORT', SYSDATE, 0);                                      -- HVT
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 543, 11004, 4, 'IMPORT', SYSDATE, 0);                                      -- NK

INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 544, 11001, 1, 'IMPORT', SYSDATE, 0);                                      -- KVZ
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 544, 11009, 2, 'IMPORT', SYSDATE, 0);                                      -- GEWOFAG
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 544, 11000, 3, 'IMPORT', SYSDATE, 0);                                      -- HVT
INSERT INTO T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
VALUES (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 544, 11004, 4, 'IMPORT', SYSDATE, 0);                                      -- NK


-- Equipment-Konfig definieren
INSERT INTO T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
VALUES (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 543, 1, 'EQ_OUT', 'rangSchnittstelle', 'H', 0, '1', '0');
INSERT INTO T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
VALUES (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 543, 1, 'EQ_OUT', 'status', 'frei', 0, '1', '0');

INSERT INTO T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
VALUES (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 544, 1, 'EQ_OUT', 'rangSchnittstelle', 'H', 0, '1', '0');
INSERT INTO T_PRODUKT_EQ_CONFIG (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM, EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
VALUES (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 544, 1, 'EQ_OUT', 'status', 'frei', 0, '1', '0');


-- Sperren
INSERT INTO T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID) VALUES (543, 2);                                                  -- ST Online
INSERT INTO T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID) VALUES (544, 2);                                                  -- ST Online


-- CPS
-- createSubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 543, 14000, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - DSL+VOIP am HVT'), 0);             -- createSubscriber
-- modifySubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 543, 14001, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - DSL+VOIP am HVT'), 0);             -- modifySubscriber
-- deleteSubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 543, 14002, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - Cancel Subscriber'), 0);            -- deleteSubscriber
-- lockSubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 543, 14006, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - DSL+VOIP am HVT'), 0);             -- lockSubscriber

-- createSubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 544, 14000, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - DSL only (IPv6) am HVT'), 0);      -- createSubscriber
-- modifySubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 544, 14001, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - DSL only (IPv6) am HVT'), 0);      -- modifySubscriber
-- deleteSubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 544, 14002, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - Cancel Subscriber'), 0);           -- deleteSubscriber
-- lockSubscriber
INSERT INTO T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
VALUES (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 544, 14006, (SELECT id FROM T_SERVICE_CHAIN WHERE name = 'CPS - DSL only (IPv6) am HVT'), 0);      -- lockSubscriber


-- Produktschnittstellen
INSERT INTO T_PRODUKT_2_SCHNITTSTELLE (PROD_ID, SCHNITTSTELLE_ID) VALUES (543, 32);                                                             -- ADSL2+
INSERT INTO T_PRODUKT_2_SCHNITTSTELLE (PROD_ID, SCHNITTSTELLE_ID) VALUES (544, 32);                                                             -- ADSL2+


-- SIP-Domain
-- DSL + VoIP (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextval, 543, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc06'), (SELECT ID FROM T_REFERENCE WHERE TYPE = 'SIP_DOMAIN_TYPE' AND STR_VALUE = 'biz.m-call.de'), 'IMPORT', SYSDATE, 0, '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextval, 543, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc06'), (SELECT ID FROM T_REFERENCE WHERE TYPE = 'SIP_DOMAIN_TYPE' AND STR_VALUE = 'maxi.m-call.de'), 'IMPORT', SYSDATE, 0, '0');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextval, 543, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), (SELECT ID FROM T_REFERENCE WHERE TYPE = 'SIP_DOMAIN_TYPE' AND STR_VALUE = 'mga.mnet-voip.de'), 'IMPORT', SYSDATE, 0, '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextval, 543, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), (SELECT ID FROM T_REFERENCE WHERE TYPE = 'SIP_DOMAIN_TYPE' AND STR_VALUE = 'phone.mnet-voip.de'), 'IMPORT', SYSDATE, 0, '0');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextval, 543, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc08'), (SELECT ID FROM T_REFERENCE WHERE TYPE = 'SIP_DOMAIN_TYPE' AND STR_VALUE = 'mga.test.mnet-voip.de'), 'IMPORT', SYSDATE, 0, '1');
INSERT INTO T_PROD_2_SIP_DOMAIN (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
VALUES (S_T_PROD_2_SIP_DOMAIN_0.nextval, 543, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc08'), (SELECT ID FROM T_REFERENCE WHERE TYPE = 'SIP_DOMAIN_TYPE' AND STR_VALUE = 'phone.test.mnet-voip.de'), 'IMPORT', SYSDATE, 0, '0');


-- Produktwechsel
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 440, 543, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 543, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 481, 543, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 480, 543, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 543, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 446, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 445, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 440, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 431, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 430, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 481, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 480, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 420, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 421, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 543, 544, 5000, 150, NULL, 0);

INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 440, 544, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 481, 544, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 480, 544, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 544, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 446, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 445, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 440, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 431, 5000, 1, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 480, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 481, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 421, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 420, 5000, 150, NULL, 0);
INSERT INTO T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, DESCRIPTION, VERSION)
 VALUES (S_T_PROD_2_PROD_0.nextVal, 544, 430, 5000, 1, NULL, 0);


-- DSLAM-Profile
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_17600_1280_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_17600_1280_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_22000_1280_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_22000_1280_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-INPx-ID8-TM6' AND d.BAUGRUPPEN_TYP=14));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-FP-TM6' AND d.BAUGRUPPEN_TYP=14));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-INPx-ID8-TM6' AND d.BAUGRUPPEN_TYP=311));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-FP-TM6' AND d.BAUGRUPPEN_TYP=311));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-INPx-ID8-TM6' AND d.BAUGRUPPEN_TYP=28));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (543, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-FP-TM6' AND d.BAUGRUPPEN_TYP=28));

INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1152_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_1792_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_2336_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_3552_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_320_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_5024_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_F_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MAXI_7168_640_H_D001_ADSL1' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_17600_1280_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_17600_1280_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_22000_1280_F_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='MMAX_22000_1280_H_D001' AND d.BAUGRUPPEN_TYP IS NULL));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-FP-TM6' AND d.BAUGRUPPEN_TYP=311));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-FP-TM6' AND d.BAUGRUPPEN_TYP=14));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-FP-TM6' AND d.BAUGRUPPEN_TYP=28));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-INPx-ID8-TM6' AND d.BAUGRUPPEN_TYP=28));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-INPx-ID8-TM6' AND d.BAUGRUPPEN_TYP=14));
INSERT INTO T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID) VALUES (544, (SELECT d.ID FROM T_DSLAM_PROFILE d WHERE d.NAME='Ax-18-1-INPx-ID8-TM6' AND d.BAUGRUPPEN_TYP=311));


-- Report Konfiguration (REPORT_2_PROD / REP2PROD_STATI)
CREATE OR REPLACE PROCEDURE clone_report_2_prod(prod_id_src in NUMBER, prod_id_dest in NUMBER)
IS
  id NUMBER(19,0);

  BEGIN
    FOR r_2_p IN (SELECT r2p.ID, r2p.REP_ID FROM T_REPORT_2_PROD r2p WHERE r2p.PROD_ID = prod_id_src) LOOP

      SELECT S_T_REPORT_2_PROD_0.nextVal INTO id FROM DUAL;
      INSERT INTO T_REPORT_2_PROD
      (ID, REP_ID, PROD_ID, VERSION)
      VALUES
        (id, r_2_p.REP_ID, prod_id_dest, 0)
    ;
      FOR r2p_s IN (SELECT STATUS_ID FROM T_REP2PROD_STATI WHERE REP2PROD_ID = r_2_p.ID) LOOP
        INSERT INTO T_REP2PROD_STATI
        (ID, REP2PROD_ID, STATUS_ID, VERSION)
        VALUES
          (S_T_REP2PROD_STATI_0.nextVal, id, r2p_s.STATUS_ID, 0)
      ;
      END LOOP;
    END LOOP;
  END;
/

call clone_report_2_prod(445, 543);
call clone_report_2_prod(445, 544);
drop procedure clone_report_2_prod;


-- Aenderungsgruppen fuer Bauauftraege
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (543,1);                                -- alle Produkte
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (543,2);                                -- alle Produkte mit physikalischen Anschluss
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (543,4);                                -- Produkte mit Rufnummer
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (544,1);                                -- alle Produkte
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (544,2);                                -- alle Produkte mit physikalischen Anschluss


-- BA Verlauf Config - Steuerung fuer Bauauftragsverteilung
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 3, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');      -- Leistungsaenderungen
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 13, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Kuendigung
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 14, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Wegfall Rufnummer
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 27, 45, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Neuschaltung
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 43, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Anschlussuebernahme
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 44, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Austausch Rufnummern
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 67, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Aenderung Bandbreite
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 543, 72, 45, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Anbieterwechsel

INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 544, 3, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');      -- Leistungsaenderungen
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 544, 13, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Kuendigung
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 544, 27, 45, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Neuschaltung
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 544, 43, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Anschlussuebernahme
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 544, 67, 17, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Aenderung Bandbreite
INSERT INTO T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 VALUES
   (S_T_BA_VERL_CONFIG_0.nextVal, 544, 72, 45, TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), sysdate, 'IMPORT', 0, '1', '1');     -- Anbieterwechsel


-- neue technische Kombi-Leistungen
INSERT INTO T_TECH_LEISTUNG (ID, NAME, EXTERN_LEISTUNG__NO, TYP, PROD_NAME_STR, DISPO, EWSD, SDH, IPS, SCT, SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION, PREVENT_AUTO_DISPATCH, DESCRIPTION)
 VALUES
   (173, 'FTTX_GF_25/5_TK', 10263, 'KOMBI', ' ', '0', '0', '0', '0', '0', '1', TO_DATE('09/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0, '0',
    'Kombi-Leistung, fuehrt zu: 25 MBit, 5 MBit, VOIP_TK, Endgeraeteport');


-- techn. Leistungen dem Produkt zuordnen
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 4, NULL, '0', 0);      -- feste IP-Adresse incl. Always-on
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 351, NULL, '0', 0);    -- weiterer Endgeräteport
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 115, NULL, '0', 0);    -- Installation Kunden-PC
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 650, NULL, '0', 0);    -- Montage

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 170, NULL, '0', 0);    -- Kombi-Leistung 18 MBit, 1 MBit, VOIP_MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 21, 170, '1', 0);      -- Downstream 18 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 22, 170, '1', 0);      -- Upstream 1 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 57, 170, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 56, 170, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 300, 170, '1', 0);     -- VoIP-MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 350, 170, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 171, NULL, '0', 0);    -- Kombi-Leistung 18 MBit, 1 MBit, VOIP_TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 21, 171, '1', 0);      -- Downstream 18 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 22, 171, '1', 0);      -- Upstream 1 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 57, 171, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 56, 171, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 301, 171, '1', 0);     -- VoIP-TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 543, 350, 171, '1', 0);     -- Endgeraeteport


INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 4, NULL, '0', 0);      -- feste IP-Adresse incl. Always-on
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 460, NULL, '1', 0);    -- QoS-Profil fuer Sip-Trunk VOIP-Ready
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 115, NULL, '0', 0);    -- Installation Kunden-PC
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 650, NULL, '1', 0);    -- Montage

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 180, NULL, '0', 0);    -- Kombi-Leistung 18 MBit, 1 MBit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 21, 180, '1', 0);      -- Downstream 18 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 22, 180, '1', 0);      -- Upstream 1 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 57, 180, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 544, 56, 180, '1', 0);      -- dynamische IPv4


-- Produktnamenaenderung
UPDATE T_PRODUKT SET ANSCHLUSSART = 'Premium FTTX DSL + Fon', PROD_NAME_PATTERN = 'Premium FTTX DSL + Fon {DOWNSTREAM}' WHERE PROD_ID = 540;
UPDATE T_PRODUKT SET ANSCHLUSSART = 'Premium FTTX DSL', PROD_NAME_PATTERN = 'Premium FTTX DSL {DOWNSTREAM}' WHERE PROD_ID = 542;

-- Neue Leistungen zu bestehenden Produkten hinzukonfigurieren
delete from T_PROD_2_TECH_LEISTUNG WHERE PROD_ID = 540 and TECH_LS_DEPENDENCY in (172, 173, 174, 175, 176, 177, 178, 179);
delete from T_PROD_2_TECH_LEISTUNG WHERE PROD_ID = 540 and TECH_LS_ID in (172, 173, 174, 175, 176, 177, 178, 179);

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 172, NULL, '0', 0);    -- Kombi-Leistung 25 MBit, 5 MBit, VOIP_MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 23, 172, '1', 0);      -- Downstream 25 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 27, 172, '1', 0);      -- Upstream 5 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 172, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 172, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 300, 172, '1', 0);     -- VoIP-MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 172, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 173, NULL, '0', 0);    -- Kombi-Leistung 25 MBit, 5 MBit, VOIP_TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 23, 173, '1', 0);      -- Downstream 25 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 27, 173, '1', 0);      -- Upstream 5 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 173, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 173, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 301, 173, '1', 0);     -- VoIP-TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 173, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 174, NULL, '0', 0);    -- Kombi-Leistung 50 MBit, 10 MBit, VOIP_MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 24, 174, '1', 0);      -- Downstream 50 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 28, 174, '1', 0);      -- Upstream 10 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 174, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 174, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 300, 174, '1', 0);     -- VoIP-MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 174, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 175, NULL, '0', 0);    -- Kombi-Leistung 50 MBit, 10 MBit, VOIP_TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 24, 175, '1', 0);      -- Downstream 50 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 28, 175, '1', 0);      -- Upstream 10 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 175, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 175, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 301, 175, '1', 0);     -- VoIP-TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 175, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 176, NULL, '0', 0);    -- Kombi-Leistung 100 MBit, 40 MBit, VOIP_MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 25, 176, '1', 0);      -- Downstream 100 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 74, 176, '1', 0);      -- Upstream 40 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 176, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 176, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 300, 176, '1', 0);     -- VoIP-MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 176, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 177, NULL, '0', 0);    -- Kombi-Leistung 100 MBit, 40 MBit, VOIP_TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 25, 177, '1', 0);      -- Downstream 100 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 74, 177, '1', 0);      -- Upstream 40 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 177, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 177, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 301, 177, '1', 0);     -- VoIP-TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 177, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 178, NULL, '0', 0);    -- Kombi-Leistung 300 MBit, 60 MBit, VOIP_MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 66, 178, '1', 0);      -- Downstream 300 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 68, 178, '1', 0);      -- Upstream 60 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 178, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 178, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 300, 178, '1', 0);     -- VoIP-MGA
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 178, '1', 0);     -- Endgeraeteport

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 179, NULL, '0', 0);    -- Kombi-Leistung 300 MBit, 60 MBit, VOIP_TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 66, 179, '1', 0);      -- Downstream 300 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 68, 179, '1', 0);      -- Upstream 60 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 57, 179, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 56, 179, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 301, 179, '1', 0);     -- VoIP-TK
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 540, 350, 179, '1', 0);     -- Endgeraeteport

delete from T_PROD_2_TECH_LEISTUNG WHERE PROD_ID = 542 and TECH_LS_DEPENDENCY in (181, 182, 183, 184);
delete from T_PROD_2_TECH_LEISTUNG WHERE PROD_ID = 542 and TECH_LS_ID in (181, 182, 183, 184);

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 181, NULL, '0', 0);    -- Kombi-Leistung 25 MBit, 5 MBit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 23, 181, '1', 0);      -- Downstream 25 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 27, 181, '1', 0);      -- Upstream 5 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 181, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 56, 181, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 460, 181, '1', 0);     -- QoS-Profil fuer Sip-Trunk VOIP-Ready

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 182, NULL, '0', 0);    -- Kombi-Leistung 50 MBit, 10 MBit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 24, 182, '1', 0);      -- Downstream 50 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 28, 182, '1', 0);      -- Upstream 10 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 182, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 56, 182, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 460, 182, '1', 0);     -- QoS-Profil fuer Sip-Trunk VOIP-Ready

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 183, NULL, '0', 0);    -- Kombi-Leistung 100 MBit, 40 MBit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 25, 183, '1', 0);      -- Downstream 100 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 74, 183, '1', 0);      -- Upstream 40 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 183, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 56, 183, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 460, 183, '1', 0);     -- QoS-Profil fuer Sip-Trunk VOIP-Ready

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 184, NULL, '0', 0);    -- Kombi-Leistung 300 MBit, 60 MBit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 66, 184, '1', 0);      -- Downstream 300 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 68, 184, '1', 0);      -- Upstream 60 Mbit
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 57, 184, '1', 0);      -- dynamische IPv6
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 56, 184, '1', 0);      -- dynamische IPv4
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 542, 460, 184, '1', 0);     -- QoS-Profil fuer Sip-Trunk VOIP-Ready


-- Produktmapping
INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE) VALUES (543, 543, 543, '.');
INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE) VALUES (544, 544, 544, '.');

Insert into T_PROD_2_EG (ID, PROD_ID, EG_ID, IS_DEFAULT, IS_ACTIVE, VERSION)
 Values (S_T_PROD_2_EG_0.nextval, 543, 5, '1', '1', 0);

update T_PRODUKT_2_PHYSIKTYP set USE_IN_RANG_MATRIX = 0 where PROD_ID in (511, 512, 513, 541, 542) and PHYSIKTYP = 810;

delete from T_RANGIERUNGSMATRIX where prod_id in (543, 544);

CREATE OR REPLACE PROCEDURE insert_rangmatrix(prod IN NUMBER)
IS
  BEGIN
    FOR PROD2PHYSIK in (SELECT p2p.id, p2p.PRIORITY FROM T_PRODUKT_2_PHYSIKTYP p2p WHERE p2p.PROD_ID = prod) LOOP
      FOR UEVTID IN (SELECT UEVT.UEVT_ID, hvt.HVT_ID_STANDORT
                     FROM T_UEVT uevt JOIN T_HVT_STANDORT hvt ON (uevt.HVT_ID_STANDORT = hvt.HVT_ID_STANDORT)
                       JOIN T_REFERENCE refer ON (REFER.ID = hvt.STANDORT_TYP_REF_ID)
                     WHERE REFER.STR_VALUE IN ('HVT')) LOOP
        INSERT INTO T_RANGIERUNGSMATRIX (ID, PROD_ID, UEVT_ID, PRODUKT2PHYSIKTYP_ID, PRIORITY, HVT_STANDORT_ID_ZIEL, PROJEKTIERUNG, GUELTIG_VON, GUELTIG_BIS, BEARBEITER)
        VALUES
          (S_T_RANGIERUNGSMATRIX_0.NEXTVAL, prod, UEVTID.UEVT_ID, PROD2PHYSIK.ID, PROD2PHYSIK.PRIORITY, UEVTID.hvt_id_standort, NULL, to_date('12/01/2016', 'DD/MM/YYYY'), to_date('01/01/2200', 'DD/MM/YYYY'), 'Import');
      END LOOP;
    END LOOP;
  END;
/
CALL insert_rangmatrix(544);
CALL insert_rangmatrix(543);
DROP PROCEDURE insert_rangmatrix;

