ALTER TABLE T_PROFILE_AUFTRAG_VALUE MODIFY (PARAMETER_NAME varchar2(2000) NOT NULL);

ALTER TABLE T_PROFILE_AUFTRAG_VALUE MODIFY (PARAMETER_VALUE varchar2(2000) NOT NULL);

ALTER TABLE T_PROFILE_AUFTRAG_VALUE MODIFY (PROFILE_AUFTRAG_ID NUMBER(19) NOT NULL);

ALTER TABLE T_PROFILE_PARAMETER MODIFY (PARAMETER_VALUE varchar2(2000) NOT NULL);