DELETE FROM T_HVT_STANDORT_TECH_TYPE
WHERE ID IN (
  SELECT stech.ID FROM T_HVT_STANDORT_TECH_TYPE stech
  WHERE stech.HVT_ID_STANDORT IN (
    SELECT s.HVT_ID_STANDORT FROM T_HVT_STANDORT s
      JOIN T_REFERENCE r ON s.STANDORT_TYP_REF_ID = r.ID
    WHERE r.STR_VALUE IN ('FTTB', 'FTTH','FTTB_H')
  )
);