-- Physiktypmapping ProdID 540 und Physiktyp 810(FTTB_GFAST)
INSERT INTO T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL, PARENTPHYSIKTYP_ID, VERSION, PRIORITY, USE_IN_RANG_MATRIX)
SELECT S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 540, 810, NULL, NULL, NULL, 1, 200, '0'
FROM dual WHERE NOT EXISTS (SELECT * FROM T_PRODUKT_2_PHYSIKTYP WHERE PROD_ID = 540 AND PHYSIKTYP =  810);
