Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, ANSCHLUSSART, PROD_NAME_PATTERN, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
   BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN,
   BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP,
   ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
   CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
   VERTEILUNG_DURCH, BA_RUECKLAEUFER, VERLAUF_CHAIN_ID,
   VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING,
   CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT,
   TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, VIER_DRAHT, VERSION, MIN_DN_COUNT, CPS_IP_DEFAULT, CPS_MULTI_DRAHT)
 Values
   (514, 21, 'TAL VDSL + Fon', 'TAL VDSL + Fon {DOWNSTREAM}',
    1, 10, '0', 60,
    '0', TO_DATE('01/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1',
    '0', '1', '0', 1,
    'X9', 1, '1', '0', '0',
    '0', '0', '0', '1', '1',
    4, '0', 45,
    15, '1', '0', '0', '1',
    'TAL_VDSL_FON', '1', '1', 'MAXI', '1',
    'W', 'V', '0', 0, 1, '1', '0');
    
-- DSLAM Profile
Insert into T_DSLAM_PROFILE
   (ID, NAME, DOWNSTREAM, UPSTREAM, FASTPATH, 
    DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS, GUELTIG, VERSION, ADSL1FORCE, 
    BAUGRUPPEN_TYP)
 values
   (S_T_DSLAM_PROFILE_0.nextVal, 'MD_18000_1000_H', '18000', '1000', '0', 
    21, 22, '1', 0, '0', 
    null);


-- DSLAM Profile zuordnen
Insert into T_PROD_2_DSLAMPROFILE (PROD_ID, DSLAM_PROFILE_ID)
 values (514, (select d.ID from T_DSLAM_PROFILE d where d.NAME='MD_50000_5000_H' and d.BAUGRUPPEN_TYP is null));

-- techn. Leistungen dem Produkt zuordnen
Insert into T_PROD_2_TECH_LEISTUNG(ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 24, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 27, 24, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 111, '1', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 113, '0', 0);
Insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, IS_DEFAULT, VERSION)
 values (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 514, 115, '0', 0);
 

-- Physikzuordnung
Insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, VIRTUELL, VERSION)
 values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 514, 804, '0', 0);

-- Standorttypen definieren
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW, DATEW, VERSION)
 values (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextVal, 514, 11000, 1, 'IMPORT', SYSDATE, 0);

-- BA Anlaesse konfigurieren
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) Values (514, 1);
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) Values (514, 2);
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) Values (514, 4);


-- BA Konfiguration
Insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 values (S_T_BA_VERL_CONFIG_0.nextVal, 514, 27, 18, SYSDATE, TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), SYSDATE, 'Import', 0, '1', '1');
Insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 values (S_T_BA_VERL_CONFIG_0.nextVal, 514, 13, 18, SYSDATE, TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), SYSDATE, 'Import', 0, '1', '1');
Insert into T_BA_VERL_CONFIG (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON, GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN, CPS_NECESSARY)
 values (S_T_BA_VERL_CONFIG_0.nextVal, 514, 44, 17, SYSDATE, TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), SYSDATE, 'Import', 0, '1', '1');
 
-- Schnittstelle definieren
Insert into T_PRODUKT_2_SCHNITTSTELLE (PROD_ID, SCHNITTSTELLE_ID) Values (514, 38);

-- Sperren
Insert into T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID) Values (514, 2);
Insert into T_SPERRE_VERTEILUNG (PROD_ID, ABTEILUNG_ID) Values (514, 3);

-- CPS
Insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 514, 14000, 53, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 514, 14001, 53, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 514, 14002, 54, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 514, 14006, 53, 0);

 
-- SIP Domain
Insert into T_PROD_2_SIP_DOMAIN
   (ID, PROD_ID, SWITCH_REF_ID, SIP_DOMAIN_REF_ID, USERW, DATEW, VERSION, DEFAULT_DOMAIN)
 values (S_T_PROD_2_SIP_DOMAIN_0.nextVal, 514, 22208, 22344, 'IMPORT', TO_DATE('01/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0, '1');
 
-- Prod2Prod
Insert into T_PROD_2_PROD (ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID, VERSION)
 values (S_T_PROD_2_PROD_0.nextVal, 514, 514, 5000, 1, 0);
 
