

ALTER TABLE T_AUFTRAG_HOUSING MODIFY ELECTRIC_COUNTER_START decimal(12,2);
ALTER TABLE T_AUFTRAG_HOUSING MODIFY ELECTRIC_COUNTER_END decimal(12,2);

ALTER TABLE T_AUFTRAG_HOUSING ADD (
    ELECTRIC_COUNTER_START_2 decimal(12,2),
    ELECTRIC_COUNTER_END_2 decimal(12,2),
    ELECTRIC_COUNTER_START_3 decimal(12,2),
    ELECTRIC_COUNTER_END_3 decimal(12,2),
    ELECTRIC_COUNTER_START_4 decimal(12,2),
    ELECTRIC_COUNTER_END_4 decimal(12,2)
);