-- Change CrossConnection data definition

ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN NE_OUTER_TAG TO NT_OUTER;

ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN NE_INNER_TAG TO NT_INNER;

ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN CPE_OUTER_TAG TO LT_OUTER;

ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN CPE_INNER_TAG TO LT_INNER;

ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN VALID_FROM TO BRAS_OUTER;
ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(BRAS_OUTER NUMBER(9) NULL);


ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN VALID_TO TO BRAS_INNER;
ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(BRAS_INNER NUMBER(9) NULL);


ALTER TABLE T_EQ_CROSS_CONNECTION
RENAME COLUMN USERW TO VALID_FROM;
ALTER TABLE T_EQ_CROSS_CONNECTION
MODIFY(VALID_FROM DATE);


ALTER TABLE T_EQ_CROSS_CONNECTION
 ADD (VALID_TO  DATE  NOT NULL);

ALTER TABLE T_EQ_CROSS_CONNECTION
 ADD (USERW  VARCHAR2(25 BYTE)  NOT NULL);
