ALTER TABLE T_HW_RACK_DSLAM
 ADD (OUTER_TAG_VOIP  NUMBER(9));

ALTER TABLE T_HW_RACK_DSLAM
 ADD (BRAS_VPI_ADSL  NUMBER(9));

ALTER TABLE T_HW_RACK_DSLAM
 ADD (BRAS_OUTER_TAG_ADSL  NUMBER(9));

ALTER TABLE T_HW_RACK_DSLAM
 ADD (BRAS_OUTER_TAG_SDSL  NUMBER(9));

ALTER TABLE T_HW_RACK_DSLAM
 ADD (BRAS_OUTER_TAG_VOIP  NUMBER(9));

COMMENT ON COLUMN T_HW_RACK_DSLAM.VPI_UBR_ADSL IS '= ADSL-VP';
COMMENT ON COLUMN T_HW_RACK_DSLAM.VPI_SDSL IS '= SDSL-VP';
COMMENT ON COLUMN T_HW_RACK_DSLAM.OUTER_TAG_ADSL IS '= ADSL-SVLAN';
COMMENT ON COLUMN T_HW_RACK_DSLAM.OUTER_TAG_SDSL IS '= SDSL-SVLAN';
COMMENT ON COLUMN T_HW_RACK_DSLAM.VPI_CPE_MGMT IS '= CPE-VP (Management)';
COMMENT ON COLUMN T_HW_RACK_DSLAM.OUTER_TAG_IAD_MGMT IS '= IAD-VLAN (Management)';
COMMENT ON COLUMN T_HW_RACK_DSLAM.OUTER_TAG_CPE_MGMT IS '= CPI-VLAN (Management)';
COMMENT ON COLUMN T_HW_RACK_DSLAM.OUTER_TAG_VOIP IS '= VoiIP-SVLAN';
COMMENT ON COLUMN T_HW_RACK_DSLAM.BRAS_VPI_ADSL IS '= ADSL-VP BRAS-Seite';
COMMENT ON COLUMN T_HW_RACK_DSLAM.BRAS_OUTER_TAG_ADSL IS '= ADSL-SVLAN BRAS-Seite';
COMMENT ON COLUMN T_HW_RACK_DSLAM.BRAS_OUTER_TAG_SDSL IS '= SDSL-SVLAN BRAS-Seite';
COMMENT ON COLUMN T_HW_RACK_DSLAM.BRAS_OUTER_TAG_VOIP IS '= VoIP-SVLAN BRAS-Seite';
