
alter table T_LOCK_DETAIL add CPS_TX_ID NUMBER(10);
comment on column T_LOCK_DETAIL.CPS_TX_ID is 'ID der CPS-Tx ueber die die Sperre abgearbeitet wurde';

CREATE INDEX IX_FK_LOCKDET_2_CPSTX ON T_LOCK_DETAIL (CPS_TX_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_LOCK_DETAIL ADD CONSTRAINT FK_LOCKDET_2_CPSTX
  FOREIGN KEY (CPS_TX_ID) REFERENCES T_CPS_TX (ID);


