INSERT INTO T_REFERENCE (
   ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID,
   GUI_VISIBLE, ORDER_NO, DESCRIPTION)
VALUES (6013, 'INTERNET_PROTOCOL', 'Sonstiger Port',
    NULL, NULL, NULL,
    '1', NULL, NULL);