INSERT INTO T_REFERENCE (
   ID, TYPE, STR_VALUE,
   INT_VALUE, FLOAT_VALUE, UNIT_ID,
   GUI_VISIBLE, ORDER_NO, DESCRIPTION)
VALUES (6014, 'INTERNET_PROTOCOL', 'Alle Ports',
    -1, NULL, NULL,
    '1', NULL, NULL);