--
-- Add the necessary colums to T_EG_CONFIG
-- to be able to migrate CPE_CONFIG from KUP
--

ALTER TABLE T_EG_CONFIG
 ADD (WANVC  NUMBER(10));

ALTER TABLE T_EG_CONFIG
 ADD (WANVP  NUMBER(10));

ALTER TABLE T_EG_CONFIG
 ADD (DHCP_POOL_TO  VARCHAR2(20));

ALTER TABLE T_EG_CONFIG
 ADD (DHCP_POOL_FROM  VARCHAR2(20));

ALTER TABLE T_EG_CONFIG
 ADD (DNS_SERVER  CHAR(1));

ALTER TABLE T_EG_CONFIG
 ADD (FIREWALL  CHAR(1));

ALTER TABLE T_EG_CONFIG
 ADD (FIREWALL_PASSWORD  VARCHAR2(50));

ALTER TABLE T_EG_CONFIG
 ADD (USER_ID_FREMD  VARCHAR2(50));

ALTER TABLE T_EG_CONFIG
 ADD (PASSWORD_FREMD  VARCHAR2(50));
