-- Renames the fields of the Routing entity

ALTER TABLE T_EG_ROUTING DROP COLUMN NAME;
ALTER TABLE T_EG_ROUTING DROP COLUMN PREFIX;
ALTER TABLE T_EG_ROUTING DROP COLUMN PREFIX_LENGTH;

ALTER TABLE T_EG_ROUTING ADD (DESTINATION_ADRESS VARCHAR2(50 BYTE) NOT NULL);
ALTER TABLE T_EG_ROUTING ADD (DESTINATION_NETMASK VARCHAR2(50 BYTE) NOT NULL);