--
-- S0A SDSL S0 mit TK-Leistung versehen
--

INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 37, 103, null, 0);
