--
-- Add version to EG_ACL and set other versions NOT NULL
--
ALTER TABLE T_EG_ACL
RENAME COLUMN ACL_TEXT TO TEXT;

ALTER TABLE T_EG_ACL
RENAME COLUMN ACL_NAME TO NAME;

ALTER TABLE T_EG_ACL
RENAME COLUMN ACL_ROUTERTYP TO ROUTERTYP;

ALTER TABLE T_EG_ACL
 ADD (VERSION  NUMBER(20)   NOT NULL);

ALTER TABLE T_EG_CONFIG
MODIFY(VERSION  NOT NULL);

ALTER TABLE T_EG_IP
MODIFY(VERSION  NOT NULL);

ALTER TABLE T_EG_ROUTING
MODIFY(VERSION  NOT NULL);

ALTER TABLE T_PORT_FORWARD
MODIFY(VERSION  NOT NULL);

ALTER TABLE T_EG_2_AUFTRAG
MODIFY(VERSION  NOT NULL);