alter table T_PRODUKT drop column LTGNR_VORS;

-- IP-VPN UMTS
Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN,
    LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
    BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG,
    LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP,
    BESCHREIBUNG, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG,
    IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M,
    CREATE_KDP_ACCOUNT_REPORT, EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, BRAUCHT_VPI_VCI,
    PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS,
    ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION,
    CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER,
    VIER_DRAHT, VERSION, MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN)
 Values
   (470, 23, NULL, 'IP-VPN UMTS', NULL,
    NULL, 1, 0, '0', NULL,
    '0', TO_DATE('08/01/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0',
    '1', '0', '1', '0', 0,
    NULL, NULL, NULL, '0', '0',
    '0', '0', '0', '0', '0',
    '0', NULL, 11, '0', '0',
    NULL, 15, 15, '1', '0',
    '0', '0', NULL, '0', '0',
    NULL, NULL, 'V', 'I', NULL,
    '0', 0, 0, NULL);
Insert into T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values
   (470, 470, 470, '.', 0);

-- UMTS Backup
Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN,
    LEITUNGSART, AKTIONS_ID, MAX_DN_COUNT, DN_BLOCK, DN_TYP,
    BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG,
    LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP,
    BESCHREIBUNG, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG,
    IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M,
    CREATE_KDP_ACCOUNT_REPORT, EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, BRAUCHT_VPI_VCI,
    PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS,
    ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION,
    CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER,
    VIER_DRAHT, VERSION, MIN_DN_COUNT, TDN_KIND_OF_USE_TYPE_VPN)
 Values
   (471, 23, NULL, 'IP-VPN UMTS Backup', NULL,
    NULL, 1, 0, '0', NULL,
    '0', TO_DATE('08/01/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0',
    '1', '0', '1', '0', 0,
    NULL, NULL, NULL, '0', '0',
    '0', '0', '0', '0', '0',
    '0', NULL, 11, '0', '0',
    NULL, 15, 15, '1', '0',
    '0', '0', NULL, '0', '0',
    NULL, NULL, 'V', 'I', NULL,
    '0', 0, 0, NULL);
Insert into T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values
   (471, 471, 471, '.', 0);



