ALTER TABLE T_HW_RACK_MDU ADD (MDU_TYPE VARCHAR2(10));

UPDATE T_HW_RACK_MDU MDU SET MDU.MDU_TYPE = (SELECT BG.MOD_NUMBER FROM T_HW_BAUGRUPPE BG WHERE MDU.RACK_ID = BG.RACK_ID);

ALTER TABLE T_HW_RACK_MDU MODIFY MDU_TYPE VARCHAR2(10) NOT NULL;