-- Modulbezeichnung für bisherige MDUs korrigieren
UPDATE T_HW_BAUGRUPPE SET MOD_NUMBER = '0-1' WHERE HW_BG_TYP_ID = 37;

-- Neue Baugruppen für POTS-Ports einfügen
INSERT INTO T_HW_BAUGRUPPE (ID, RACK_ID, HW_BG_TYP_ID, EINGEBAUT, INVENTAR_NR, MOD_NUMBER, SUBRACK_ID, VERSION, BEMERKUNG)
   SELECT S_T_HW_BAUGRUPPE_0.NEXTVAL AS ID, BG.RACK_ID,
          (SELECT TYP.ID FROM T_HW_BAUGRUPPEN_TYP TYP WHERE TYP.NAME = 'MA5652G_POTS') AS HW_BG_TYP_ID,
          BG.EINGEBAUT, BG.INVENTAR_NR, '0-2' AS MOD_NUMBER, BG.SUBRACK_ID, 0 AS VERSION, BG.BEMERKUNG
     FROM T_HW_BAUGRUPPE BG
    WHERE BG.HW_BG_TYP_ID = 37;
