-- POTS-Ports auf neue POTS-Baugruppe schwenken
UPDATE T_EQUIPMENT EQ SET EQ.HW_BAUGRUPPEN_ID = (
	SELECT BG.ID FROM T_HW_BAUGRUPPE BG, T_HW_BAUGRUPPE BG_OLD WHERE BG_OLD.RACK_ID = BG.RACK_ID AND BG.HW_BG_TYP_ID != 37 AND BG_OLD.ID = EQ.HW_BAUGRUPPEN_ID
) WHERE EQ.HW_SCHNITTSTELLE = 'POTS';
