-- Add hardware type name

ALTER TABLE T_HW_BAUGRUPPEN_TYP
 ADD (HW_TYPE_NAME  VARCHAR2(64 BYTE));

UPDATE T_HW_BAUGRUPPEN_TYP
SET    HW_TYPE_NAME = 'MDU'
WHERE  ID IN (37);

UPDATE T_HW_BAUGRUPPEN_TYP
SET    HW_TYPE_NAME = 'XDSL_AGB'
WHERE  ID IN (14, 15, 16, 17, 28, 29);

UPDATE T_HW_BAUGRUPPEN_TYP
SET    HW_TYPE_NAME = 'EWSD_DLU'
WHERE  ID IN (1, 2, 3, 4, 20);

UPDATE T_HW_BAUGRUPPEN_TYP
SET    HW_TYPE_NAME = 'XDSL_MUC'
WHERE  ID IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50);

