-- Alter regexp table

TRUNCATE TABLE T_CFG_REG_EXP;


ALTER TABLE T_CFG_REG_EXP
MODIFY(REF_ID  NULL);


ALTER TABLE T_CFG_REG_EXP
RENAME COLUMN REF_CLASS TO REF_NAME;
ALTER TABLE T_CFG_REG_EXP
MODIFY(REF_NAME  NULL);


ALTER TABLE T_CFG_REG_EXP
RENAME COLUMN REQUESTED_INFO TO REF_CLASS;
ALTER TABLE T_CFG_REG_EXP
MODIFY(REF_CLASS VARCHAR2(255 BYTE) NOT NULL);


ALTER TABLE T_CFG_REG_EXP
RENAME COLUMN REGULAR_EXP TO REQUESTED_INFO;
ALTER TABLE T_CFG_REG_EXP
MODIFY(REQUESTED_INFO VARCHAR2(32 BYTE));


ALTER TABLE T_CFG_REG_EXP
RENAME COLUMN DESCRIPTION TO REGULAR_EXP;
ALTER TABLE T_CFG_REG_EXP
MODIFY(REGULAR_EXP  NOT NULL);


ALTER TABLE T_CFG_REG_EXP
 ADD (MATCH_GROUP  NUMBER(10));

ALTER TABLE T_CFG_REG_EXP
 ADD (DESCRIPTION  VARCHAR2(255));


ALTER TABLE T_CFG_REG_EXP
 ADD CONSTRAINT CK_CFG_REG_EXP_REF
 CHECK ((REF_ID IS NOT NULL) OR (REF_NAME IS NOT NULL));

