--
-- SQL-Script, um die fuer SDSL notwendigen Data-Chains zu erstellen
--

insert into T_SERVICE_COMMANDS (ID, NAME, CLASS, TYPE, DESCRIPTION)
  values (5009, 'cps.radius.sdsl.data',
  'de.augustakom.hurrican.service.cc.impl.command.cps.CPSGetRadiusSDSLDataCommand',
  'CPS_DATA', 'Sammelt die Radius-Daten fuer eine CPS-Provisionierung; Ermittlung fuer SDSL!');

-- Chain fuer reine SDSL Produkte
insert into T_SERVICE_CHAIN (ID, NAME, TYPE, DESCRIPTION)
  values (56, 'CPS - SDSL', 'CPS_DATA',
  'Chain-Definition, um Daten fuer SDSL Produkte zu ermitteln.');
insert into T_SERVICE_COMMAND_MAPPING (ID, COMMAND_ID, REF_ID, REF_CLASS, ORDER_NO)
  values (S_T_SERVICE_COMMAND_MAPPI_0.nextVal, 5009,
  56, 'de.augustakom.hurrican.model.cc.command.ServiceChain', 10);


update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_256' where PROD_ID=60;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (60, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (60, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (60, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (60, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_512' where PROD_ID=61;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (61, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (61, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (61, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (61, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_1024' where PROD_ID=62;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (62, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (62, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (62, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (62, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_2300' where PROD_ID=63;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (63, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (63, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (63, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (63, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_4600' where PROD_ID=64;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (64, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (64, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (64, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (64, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_6800' where PROD_ID=66;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (66, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (66, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (66, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (66, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='SDSL_10000' where PROD_ID=67;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (67, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (67, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (67, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (67, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='AK_SDSL_1024' where PROD_ID=16;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (16, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (16, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (16, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (16, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='AK_SDSL_512' where PROD_ID=17;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (17, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (17, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (17, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (17, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='AK_SDSL_2300' where PROD_ID=18;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (18, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (18, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (18, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (18, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='AK_SDSLoffice_1200' where PROD_ID=312;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (312, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (312, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (312, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (312, 14006, 56);

update T_PRODUKT set CPS_PROVISIONING='1', CPS_PROD_NAME='AK_SDSLoffice_2300' where PROD_ID=313;
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (313, 14000, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (313, 14001, 56);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (313, 14002, 54);
insert into T_CPS_DATA_CHAIN_CONFIG (PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (313, 14006, 56);

