--
-- Script erstellt neue ConnectDSL Produkte
--

alter session set nls_date_format='yyyy-mm-dd';

INSERT INTO T_PRODUKT (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, LEITUNGSART, PROD_NAME_PATTERN, AKTIONS_ID,
    BRAUCHT_DN, AUFTRAGSERSTELLUNG, LTGNR_VORS, LTGNR_ANLEGEN, BRAUCHT_BUENDEL,
    ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, IS_PARENT, PROJEKTIERUNG,
    CHECK_CHILD, VERTEILUNG_DURCH, EXPORT_KDP_M, AUTO_PRODUCT_CHANGE, IS_COMBI_PRODUKT, GUELTIG_VON, GUELTIG_BIS)
    VALUES (444, 4, '', 'VPN IPSec Site-to-Site', null, 'VPN IPSec Site-to-Site', 1,
    0, 0, 'DV', 1, 1,
    1, 0, 1, 'X', 4, 1, 1, 1,
    0, 4, 0, 0, 0, '2009-01-01', '2200-01-01');
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (444, 1);
INSERT INTO T_BA_VERL_AEND_PROD_2_GRUPPE (PROD_ID, BA_VERL_AEND_GRUPPE_ID) VALUES (444,2);

-- Zuordnung techn. Leistungen zu Produkt
-- QoS
INSERT INTO T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT) VALUES (S_T_PROD_2_TECH_LEISTUNG_0.nextVal, 444, 50, null, 0);

-- Mapping fuer Produkt aufnehmen, wenn in Taifun eingerichtet
INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE) VALUES (502, 444, 444, 'sdsl');


update T_PRODUKT_MAPPING set mapping_group=501 where PROD_ID=461;
