apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE-APP-deployment
  namespace: NAMESPACE
spec:
  template:
    spec:
      containers:
        - name: SERVICE-APP
          ports:
            - $patch: replace
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: git-token
      imagePullSecrets:
        - name: docker-regcred
