UPDATE T_PRODUKT
SET CPS_PROVISIONING = 1, CPS_PROD_NAME = 'TV-MK', CPS_AUTO_CREATION = 1
WHERE prod_id = 500;

UPDATE T_PRODUKT
SET CPS_PROVISIONING = 1, CPS_PROD_NAME = 'TV-MK', CPS_AUTO_CREATION = 1
WHERE prod_id = 521;
