CREATE TABLE T_MWF_BESTANDSVALIDIERUNG2 (
   ID DECIMAL(19) PRIMARY KEY NOT NULL,
   VERSION DECIMAL(19) DEFAULT 0  NOT NULL,
   LEITUNGSSCHLUESSELZAHL VARCHAR2(4) NOT NULL,
   ONKZA VARCHAR2(5) NOT NULL,
   ONKZB VARCHAR2(5) NOT NULL,
   ORDNUNGSNUMMER VARCHAR2(10) NOT NULL);
  
GRANT SELECT, INSERT, UPDATE ON T_MWF_BESTANDSVALIDIERUNG2 TO R_HURRICAN_USER;
GRANT SELECT ON T_MWF_BESTANDSVALIDIERUNG2 TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_MWF_BESTANDSVALIDIERUNG2_0
   START WITH 1;
GRANT SELECT ON S_T_MWF_BESTANDSVALIDIERUNG2_0 TO PUBLIC;
 
ALTER TABLE T_MWF_GESCHAEFTSFALL ADD BESTANDSVALIDIERUNG2_ID DECIMAL(19);
ALTER TABLE T_MWF_AUFTRAGSPOSITION ADD POSITION_ID DECIMAL(19);