-- Nicht SIP DOMAIN sondern SWITCH darf NULL sein
ALTER TABLE T_PROD_2_SIP_DOMAIN MODIFY SIP_DOMAIN_REF_ID Number(10) NOT NULL;
ALTER TABLE T_PROD_2_SIP_DOMAIN MODIFY SWITCH_REF_ID Number(10) NULL;

-- FK
ALTER TABLE T_PROD_2_SIP_DOMAIN ADD CONSTRAINT FK_P2SIPD_SW_2_REF
  FOREIGN KEY (SWITCH_REF_ID) REFERENCES T_REFERENCE (ID);

-- Maxi Pur hat keinen Switch, lediglich eine default SIP Domain
UPDATE T_PROD_2_SIP_DOMAIN SET SWITCH_REF_ID=null
    WHERE PROD_ID=440 AND SWITCH_REF_ID=22204 AND SIP_DOMAIN_REF_ID=22343;
