-- Wita geschaeftsfalltyp zu CB_Vorgang hinzufügen

ALTER TABLE T_CB_VORGANG
 ADD (CBV_TYPE  VARCHAR2(20));

UPDATE T_CB_VORGANG CBV
SET CBV.CBV_TYPE = 'ESAA_INTERN';

ALTER TABLE T_CB_VORGANG
MODIFY(CBV_TYPE  NOT NULL);

ALTER TABLE T_CB_VORGANG
 ADD (WITA_GESCHAEFTSFALL_TYP  VARCHAR2(50));