ALTER TABLE T_MWF_BESTANDSSUCHE ADD (ANLAGEN_ONKZ  VARCHAR2(5));
ALTER TABLE T_MWF_BESTANDSSUCHE ADD (ANLAGEN_DURCHWAHL  VARCHAR2(8));
ALTER TABLE T_MWF_BESTANDSSUCHE ADD (ANLAGEN_ABFRAGE_STELLE  VARCHAR2(6));
