ALTER TABLE T_MWF_GF_PRODUKT RENAME COLUMN STANDORTA_ID TO STANDORTKUNDE_ID;
ALTER TABLE T_MWF_GF_PRODUKT RENAME COLUMN STANDORTB_ID TO STANDORTKOLLOKATION_ID;

ALTER TABLE T_MWF_LEITUNGS_BEZEICHNUNG RENAME COLUMN ONKZ_A TO ONKZ_KUNDE;
ALTER TABLE T_MWF_LEITUNGS_BEZEICHNUNG RENAME COLUMN ONKZ_B TO ONKZ_KOLLOKATION;

