CREATE TABLE T_MWF_ANLAGE
(
   ID                    NUMBER (19, 0) NOT NULL,
   VERSION               NUMBER (19, 0) DEFAULT 0 NOT NULL,
   GESCHAEFTSFALL_ID              NUMBER(19,0),
   DATEINAME         VARCHAR2 (255) NOT NULL,
   DATEITYP       VARCHAR2 (10) NOT NULL,
   BESCHREIBUNG       VARCHAR2 (160),
   INHALT   CLOB NOT NULL,
   ANLAGENTYP   VARCHAR2 (50) NOT NULL,
   PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_MWF_ANLAGE TO R_HURRICAN_USER;
GRANT SELECT ON T_MWF_ANLAGE TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_MWF_ANLAGE_0
   START WITH 1;

GRANT SELECT ON S_T_MWF_ANLAGE_0 TO PUBLIC;