globalProperties:
  apis: ""
  supportingFiles: ""
  models: false

additionalProperties:
  modelsLibrary: de.bitconex.tmf.appointment.model
  basePackage: de.bitconex.tmf.appointment.client
  invokerPackage: de.bitconex.tmf.appointment.client
  apiPackage: de.bitconex.tmf.appointment.client.api