globalProperties:
  models: ""
  supportingFiles: false
  apis: false

additionalProperties:
  library: webclient
  basePackage: de.bitconex.tmf.appointment
  invokerPackage: de.bitconex.tmf.appointment
  modelPackage: de.bitconex.tmf.appointment.model
  useLombok: true
  useSerializable: true
