/*
 * Copyright (c) 2014 - M-net Telekommunikations GmbH
 * All rights reserved.
 * -------------------------------------------------------
 * File created: 22.07.2015
 */
package de.mnet.wita.acceptance;

/**
 *
 */
public enum WitaAcceptanceUseCase {

    DEFAULT,
    NEU_QEB_ABM_ERLM_ENTM,
    NEU_QEB_ABM_ENTM_ERLM,  // wrong message order test case
    NEU_QEB_ABM_ERLM_ENTM_NBIT,
    NEU_QEB_ABM_TV_ABM_ERLM_ENTM,
    NEU_QEB_ABM_STORNO_ABBM,
    NEU_QEB_STORNO_ERLM_ENTM,
    NEU_QEB_ABM_ABM_ERLM_ENTM,
    NEU_QEB_ABM_ABBM,
    NEU_QEB_ERLM_ENTM,
    NEU_ABM_TAM_TAM,
    NEU_ABM_TAM_MTAM,
    NEU_ABM_TAM_TV_TAM,
    NEU_ABBM,
    NEU_ABM_TV_TAM_ABM,
    NEU_ABM_TV_TAM_ERLM,
    NEU_QEB_ABM_TAM_TAM_ABBM,
    NEU_QEB_ABM_BEFORE_HOLIDAY,

    NEU_QEB_TV_ABM_ERLM_TV_ABBM,
    NEU_QEB_ABM,

    TAL_BEREIT_NEU_01A,
    TAL_BEREIT_NEU_02B,

    TAL_BEREIT_NEU_01B,
    TAL_BEREIT_NEU_02A,
    TAL_BEREIT_NEU_02AA,
    TAL_BEREIT_NEU_02AB,
    TAL_BEREIT_NEU_03,
    TAL_BEREIT_NEU_04,
    TAL_BEREIT_NEU_05,
    TAL_BEREIT_NEU_06,
    TAL_BEREIT_NEU_07,
    TAL_BEREIT_NEU_08,
    TAL_BEREIT_NEU_09,
    TAL_BEREIT_NEU_10,
    TAL_BEREIT_NEU_11,
    TAL_BEREIT_NEU_12A,
    TAL_BEREIT_NEU_12B,
    TAL_BEREIT_NEU_13,
    TAL_BEREIT_NEU_14A,
    TAL_BEREIT_NEU_14B,
    TAL_BEREIT_NEU_15,
    TAL_BEREIT_NEU_16,
    TAL_BEREIT_NEU_17,
    TAL_BEREIT_NEU_18,
    TAL_BEREIT_NEU_19,
    TAL_BEREIT_NEU_20,
    TAL_BEREIT_NEU_21,
    TAL_BEREIT_NEU_22,
    TAL_BEREIT_NEU_23,
    TAL_BEREIT_NEU_24,
    TAL_BEREIT_NEU_25,
    TAL_BEREIT_NEU_26,
    TAL_BEREIT_NEU_27,

    TAL_TEQ_NOK_01,

    SER_POW_QEB_STORNO_ERLM_ENTM,
    SER_POW_QEB_TV_ABM_ERLM_ENTM,

    HVT_KVZ,
    HVT_KVZ_OTHER_KUENDIGUNG_DATE,
    HVT_KVZ_OTHER_KUE_DATE_2,
    HVT_KVZ_OTHER_KUE_DATE_KVZ,
    HVT_KVZ_ABBM_KVZ,
    HVT_KVZ_ABBM_HVT,

    TAL_KUENDIGUNG_KUE_KD_01,
    TAL_KUENDIGUNG_KUE_KD_02,
    TAL_KUENDIGUNG_KUE_KD_03,
    TAL_KUENDIGUNG_KUE_KD_03_KD2,
    TAL_KUENDIGUNG_KUE_KD_04,
    TAL_KUENDIGUNG_KUE_KD_05,

    KUE_KD_QEB_ABM_ERLM_ENTM,
    KUE_KD_QEB_STORNO_ERLM_ENTM,
    KUE_KD_QEB_ABM_TV,
    TAL_KUENDIGUNG_KUE_DT_01,
    KUEDT_ENTM_ERLM,

    TAL_AENDERUNG_LAE_01,
    TAL_AENDERUNG_LAE_VZMPV_01,
    TAL_AENDERUNG_LAE_02,
    LAE_QEB_ABM_ERLM_ENTM,
    LAE_QEB_STORNO_ELRM_ENTM,
    LAE_QEB_ABM_TV_ABM_ERLM_ENTM,

    LMAE_QEB_ABM_ERLM_ENTM,
    LMAE_QEB_STORNO_ERLM_ENTM,
    LMAE_QEB_TV_ABM_ERLM_ENTM,

    TAL_Verbundleistung_VBL3_01,
    TAL_Verbundleistung_VBL3_02,
    TAL_Verbundleistung_VBL3_03,
    TAL_Verbundleistung_VBL3_04,
    TAL_Verbundleistung_VBL3_05,
    TAL_Verbundleistung_VBL3_06,

    TAL_Verbundleistung_VBLT_01,
    TAL_Verbundleistung_VBLT_02,
    TAL_Verbundleistung_VBLT_03,
    TAL_Verbundleistung_VBLT_04,
    TAL_Verbundleistung_VBLT_05,
    TAL_Verbundleistung_VBLT_06,
    TAL_Verbundleistung_VBLT_07,
    TAL_Verbundleistung_VBLT_08,

    TAL_Verbundleistung_VBLT_09,

    TAL_AENDERUNG_AEN_LMAE_01,
    TAL_AENDERUNG_AEN_LMAE_02,
    TAL_AENDERUNG_AEN_LMAE_03,

    TAL_AENDERUNG_AEN_LMAE_03_VBL,

    TAL_SERVICE_POW_01,

    TAL_RUFNUMMERNEXPORT_REX_MK_01,
    TAL_RUFNUMMERNEXPORT_REX_MK_02,
    TAL_RUFNUMMERNEXPORT_REX_MK_03,

    TAL_PROVIDERWECHSEL_PV3_01,
    TAL_PROVIDERWECHSEL_PV3_02,
    TAL_PROVIDERWECHSEL_PV3_03,
    TAL_PROVIDERWECHSEL_PV3_06,
    TAL_PROVIDERWECHSEL_PV3_08,

    TAL_PROVIDERWECHSEL_PV3_04,
    TAL_PROVIDERWECHSEL_PV3_05,
    TAL_PROVIDERWECHSEL_PV3_07,
    TAL_PROVIDERWECHSEL_PV3_09,
    TAL_PROVIDERWECHSEL_PV3_10,
    TAL_PROVIDERWECHSEL_PV3_11,
    TAL_PROVIDERWECHSEL_PV3_12,
    PV_NEU,
    AKMPV_AKMPV,
    AKMPV_RUEMPV_ABBMPV,
    AKMPV_RUEMPV_ABMPV_ABBMPV,
    AKMPV_ENTMPV,
    AKMPV_ERLMPV_ENTMPV,
    AKMPV_RUEMPV_ABMPV_ENTM_ERLM, // wrong message order test case

    TAL_AUSKUNFT_BESTANDSUEBERSICHT_01,
    REX_MK_QEB_STORNO_ERLM_ENTM,
    REX_MK_QEB_TV_ABM_ERLM,

    TAL_WITA_VERSION_MIGR_NEU,
    TAL_VW_PV_04,
    TAL_VW_SER_POW_06,
    ENCODING_NEU_ABBM,
    TAL_ZF_LOGIC_SINCE_FEB_2014_NEU,
    TAL_ZF_LOGIC_SINCE_FEB_2014_KUEKD,

    TAL_WITA_WBCI_CONFORM_01A,
    TAL_WITA_WBCI_CONFORM_01B,
    TAL_WITA_WBCI_CONFORM_02,
    TAL_WITA_WBCI_CONFORM_03,
    TAL_WITA_WBCI_CONFORM_04,
    TAL_WITA_WBCI_CONFORM_05,
    TAL_WITA_WBCI_CONFORM_06,
    TAL_WITA_WBCI_CONFORM_07,
    TAL_WITA_WBCI_CONFORM_08,

    TAL_PV_TAM,
    TAL_VBL_TAM,
    TAL_NEU_TKG_TAM;
}
