ALTER TABLE T_RANGIERUNG DROP COLUMN RELEASE_CLARIFY_INFO;
ALTER TABLE T_AUFTRAG_TECHNIK ADD RANG_CLEARANCE_INFO VARCHAR2(128);

COMMENT ON COLUMN T_AUFTRAG_TECHNIK.RANG_CLEARANCE_INFO IS 'Klärfall Info für Rangierungsfreigaben, die manuell geklärt werden müssen';
