-- Spalte Klaerfallinfo loeschen
ALTER TABLE T_AUFTRAG_TECHNIK DROP COLUMN RANG_CLEARANCE_INFO;

-- Tabelle fuer Klaerfaelle erstellen
CREATE TABLE T_RANGIERUNG_FREIGABE_INFO
(
  ID              NUMBER(19)             NOT NULL,
  RANGIER_ID      NUMBER(10)             NOT NULL,
  AUFTRAG_ID      NUMBER(10),
  INFO            VARCHAR2(255),
  DATEW           DATE,
  VERSION         NUMBER(18)   DEFAULT 0 NOT NULL
);

COMMENT ON TABLE T_RANGIERUNG_FREIGABE_INFO IS 'Tabelle haelt Klärungen, die durch die automatische Freigabe erstellt werden';

COMMENT ON COLUMN T_RANGIERUNG_FREIGABE_INFO.ID IS 'ID des Datensatzes';
COMMENT ON COLUMN T_RANGIERUNG_FREIGABE_INFO.RANGIER_ID IS 'FK Referenz auf die Rangierung';
COMMENT ON COLUMN T_RANGIERUNG_FREIGABE_INFO.AUFTRAG_ID IS 'optionale FK Referenz auf den Auftrag';
COMMENT ON COLUMN T_RANGIERUNG_FREIGABE_INFO.INFO IS 'der Klärfall Text';
COMMENT ON COLUMN T_RANGIERUNG_FREIGABE_INFO.DATEW IS 'Datum des letzten schreibenden Zugriffs';

create SEQUENCE S_T_RANGIERUNG_FREIGABE_INFO_0 start with 1;
grant select on S_T_RANGIERUNG_FREIGABE_INFO_0 to public;

ALTER TABLE T_RANGIERUNG_FREIGABE_INFO ADD CONSTRAINT PK_T_RANGIERUNG_FREIGABE_INFO PRIMARY KEY (ID);

CREATE INDEX IX_FK_RANGFI_2_RANG ON T_RANGIERUNG_FREIGABE_INFO (RANGIER_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_RANGIERUNG_FREIGABE_INFO ADD CONSTRAINT FK_RANGFI_2_RANG
  FOREIGN KEY (RANGIER_ID) REFERENCES T_RANGIERUNG (RANGIER_ID);

CREATE INDEX IX_FK_RANGFI_2_AUFT ON T_RANGIERUNG_FREIGABE_INFO (AUFTRAG_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_RANGIERUNG_FREIGABE_INFO ADD CONSTRAINT FK_RANGFI_2_AUFT
  FOREIGN KEY (AUFTRAG_ID) REFERENCES T_AUFTRAG (ID);

CREATE trigger TRBIU_RANGFI BEFORE INSERT or UPDATE on T_RANGIERUNG_FREIGABE_INFO
for each row
BEGIN
 -- TIMESTAMP setzen
 SELECT CURRENT_TIMESTAMP INTO :new.DATEW FROM dual;
END;
/

GRANT SELECT ON T_RANGIERUNG_FREIGABE_INFO TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE ON T_RANGIERUNG_FREIGABE_INFO TO R_HURRICAN_USER;