alter table T_MWF_ANSPRECHPARTNER modify ANREDE VARCHAR2(10);
alter table T_MWF_AUFTRAGSMANAGEMENT modify ANREDE VARCHAR2(10);
alter table T_MWF_MONTAGELEISTUNG modify ANREDE VARCHAR2(10);
alter table T_MWF_STANDORT_KUNDE modify ANREDE VARCHAR2(10);
