-- SIP Domänen -> Produkt
CREATE TABLE T_PROD_2_SIP_DOMAIN
(
  ID                NUMBER(19)             NOT NULL,
  PROD_ID           NUMBER(10)             NOT NULL,
  SWITCH_REF_ID     NUMBER(10)             NOT NULL,
  SIP_DOMAIN_REF_ID NUMBER(10)             NOT NULL,
  USERW             VARCHAR2(15),
  DATEW             DATE,
  VERSION           NUMBER(18)   DEFAULT 0 NOT NULL
);

COMMENT ON TABLE T_PROD_2_SIP_DOMAIN IS 'Tabelle haelt SIP Domain Konfigurationen für die Produkten';

COMMENT ON COLUMN T_PROD_2_SIP_DOMAIN.ID IS 'ID des Datensatzes';
COMMENT ON COLUMN T_PROD_2_SIP_DOMAIN.PROD_ID IS 'FK Referenz auf das Produkt';
COMMENT ON COLUMN T_PROD_2_SIP_DOMAIN.SWITCH_REF_ID IS 'ID der Switch Kennung aus der T_REFERENCE';
COMMENT ON COLUMN T_PROD_2_SIP_DOMAIN.SIP_DOMAIN_REF_ID IS 'ID der SIP Domain Kennung aus der T_REFERENCE';
COMMENT ON COLUMN T_PROD_2_SIP_DOMAIN.USERW IS 'Schreibender Zugriff des letzten Benutzers';
COMMENT ON COLUMN T_PROD_2_SIP_DOMAIN.DATEW IS 'Datum des letzten schreibenden Zugriffs';

create SEQUENCE S_T_PROD_2_SIP_DOMAIN_0 start with 1;
grant select on S_T_PROD_2_SIP_DOMAIN_0 to public;

ALTER TABLE T_PROD_2_SIP_DOMAIN ADD CONSTRAINT PK_T_PROD_2_SIP_DOMAIN PRIMARY KEY (ID);

CREATE INDEX IX_FK_P2SIPD_2_PROD ON T_PROD_2_SIP_DOMAIN (PROD_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PROD_2_SIP_DOMAIN ADD CONSTRAINT FK_P2SIPD_2_PROD
  FOREIGN KEY (PROD_ID) REFERENCES T_PRODUKT (PROD_ID);

CREATE INDEX IX_FK_P2SIPD_SW_2_REF ON T_PROD_2_SIP_DOMAIN (SWITCH_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PROD_2_SIP_DOMAIN ADD CONSTRAINT FK_P2SIPD_SW_2_REF
  FOREIGN KEY (SWITCH_REF_ID) REFERENCES T_REFERENCE (ID);

CREATE INDEX IX_FK_P2SIPD_DM_2_REF ON T_PROD_2_SIP_DOMAIN (SIP_DOMAIN_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PROD_2_SIP_DOMAIN ADD CONSTRAINT FK_P2SIPD_DM_2_REF
  FOREIGN KEY (SIP_DOMAIN_REF_ID) REFERENCES T_REFERENCE (ID);

CREATE trigger TRBIU_PROD_2_SIP_DOM BEFORE INSERT or UPDATE on T_PROD_2_SIP_DOMAIN
for each row
BEGIN
 -- TIMESTAMP setzen
 SELECT CURRENT_TIMESTAMP INTO :new.DATEW FROM dual;
END;
/

GRANT SELECT ON T_PROD_2_SIP_DOMAIN TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PROD_2_SIP_DOMAIN TO R_HURRICAN_USER;



-- ****************************************************************************
-- SIP Domain Referenzen anlegen
-- ****************************************************************************
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22340, 'SIP_DOMAIN_TYPE', 'privat.sip.m-online.net', NULL, NULL,
    NULL, '1', 10, 'SIP Domäne für privat', 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22341, 'SIP_DOMAIN_TYPE', 'business.sip.m-online.de', NULL, NULL,
    NULL, '1', 20, 'SIP Domäne für business', 0);
insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (22342, 'SIP_DOMAIN_TYPE', 'internet.sip.m-online.de', NULL, NULL,
    NULL, '1', 30, 'SIP Domäne für internet', 0);



-- ****************************************************************************
-- SIP Domain Referenzen anlegen
-- ****************************************************************************
ALTER TABLE T_AUFTRAG_VOIP_DN ADD SIP_DOMAIN_REF_ID NUMBER(10);

COMMENT ON COLUMN T_AUFTRAG_VOIP_DN.SIP_DOMAIN_REF_ID IS 'ID der SIP Domain Kennung aus der T_REFERENCE';

CREATE INDEX IX_FK_AUFTRAGVOIPDN_2_REF ON T_AUFTRAG_VOIP_DN (SIP_DOMAIN_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_AUFTRAG_VOIP_DN ADD CONSTRAINT FK_AUFTRAGVOIPDN_2_REF
  FOREIGN KEY (SIP_DOMAIN_REF_ID) REFERENCES T_REFERENCE (ID);
