apiVersion: v1
kind: Service
metadata:
  name: api-gate-service
  namespace: adl
spec:
  $patch: replace
  selector:
    app: api-gate
  ports:
    - $patch: replace
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https