spring:
  application:
    name: adlatus-domain
  config:
    import: optional:configserver:${CONFIG_SERVER:https://configserver.env01.adl.dev.bitconex.com}
  cloud:
    config:
      uri: ${CONFIG_SERVER:https://configserver.env01.adl.dev.bitconex.com}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

# todo: Externalize this for dev profiles
# create PROD profile
wita:
  api:
    basepath:
      url: http://localhost:8088/mockWholesaleBinding
