-- Produktmapping fuer Surf&Fon Produkte erweitern:
-- zusaetzliche Mappings fuer Steuerleistungen TAL bzw. FTTX

-- optionale Steuerleistung TAL (EXT_PRODUKT__NO = 997)
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1215, 900, 420, 'dsl', 0, NULL);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1215, 999, 420, 'phone', 0,  NULL);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1215, 997, 420, '.', 0,  NULL);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1216, 900, 421, 'phone_dsl', 0, 2);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1216, 997, 421, '.', 0, NULL);
  
-- TAL VDSL
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1226, 901, 514, 'phone_dsl', 0, 2);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1226, 997, 514, '.', 0, 2);
    
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1227, 901, 514, 'dsl', 0, 2);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1227, 999, 514, 'phone', 0, 2);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1227, 997, 514, '.', 0, 2);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1228, 904, 515, 'phone_dsl', 0, 2);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1228, 997, 515, '.', 0, 2);


-- optionale Steuerleistung FTTX (EXT_PRODUKT__NO = 998)
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1217, 903, 512, 'dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1217, 998, 512, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION,PRIORITY)
 Values (1218, 904, 512, 'phone_dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION,PRIORITY)
 Values (1218, 998, 512, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1219, 905, 512, 'phone_dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1219, 998, 512, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1220, 900, 513, 'phone_dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1220, 998, 513, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1221, 999, 513, 'phone', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1221, 900, 513, 'dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1221, 998, 513, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1222, 901, 513, 'phone_dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1222, 998, 513, '.', 0, 1);
    
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1223, 999, 513, 'phone', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1223, 901, 513, 'dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1223, 998, 513, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1224, 902, 513, 'phone_dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1224, 998, 513, '.', 0, 1);
 
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1225, 902, 513, 'dsl', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1225, 999, 513, 'phone', 0, 1);
Insert into T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION, PRIORITY)
 Values (1225, 998, 513, '.', 0, 1);
    
 
 