/*
 * Agreement Management
 * This is Swagger UI environment generated for the TMF Agreement Management specification
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.agreement.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.agreement.model.AgreementSpecCharacteristicValue;
    import de.bitconex.tmf.agreement.model.TimePeriod;
    import java.net.URI;
    import java.util.ArrayList;
    import java.util.List;
    import com.fasterxml.jackson.annotation.*;
import java.io.Serializable;

        /**
* A characteristic quality or distinctive feature of an agreement.
*/
    @JsonPropertyOrder({
        AgreementSpecCharacteristic.JSON_PROPERTY_CONFIGURABLE,
        AgreementSpecCharacteristic.JSON_PROPERTY_DESCRIPTION,
        AgreementSpecCharacteristic.JSON_PROPERTY_NAME,
        AgreementSpecCharacteristic.JSON_PROPERTY_VALUE_TYPE,
        AgreementSpecCharacteristic.JSON_PROPERTY_SPEC_CHARACTERISTIC_VALUE,
        AgreementSpecCharacteristic.JSON_PROPERTY_VALID_FOR,
        AgreementSpecCharacteristic.JSON_PROPERTY_AT_BASE_TYPE,
        AgreementSpecCharacteristic.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        AgreementSpecCharacteristic.JSON_PROPERTY_AT_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class AgreementSpecCharacteristic implements Serializable {
        public static final String JSON_PROPERTY_CONFIGURABLE = "configurable";
            private Boolean configurable;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_VALUE_TYPE = "valueType";
            private String valueType;

        public static final String JSON_PROPERTY_SPEC_CHARACTERISTIC_VALUE = "specCharacteristicValue";
            private List<AgreementSpecCharacteristicValue> specCharacteristicValue;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

