/*
 * Agreement Management
 * This is Swagger UI environment generated for the TMF Agreement Management specification
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.agreement.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.agreement.model.AgreementSpecCharacteristic;
    import de.bitconex.tmf.agreement.model.AgreementSpecificationRelationship;
    import de.bitconex.tmf.agreement.model.AttachmentRefOrValue;
    import de.bitconex.tmf.agreement.model.CategoryRef;
    import de.bitconex.tmf.agreement.model.RelatedParty;
    import de.bitconex.tmf.agreement.model.TimePeriod;
    import java.net.URI;
    import java.time.OffsetDateTime;
    import java.util.ArrayList;
    import java.util.List;
    import com.fasterxml.jackson.annotation.*;
import java.io.Serializable;

        /**
* A template of an agreement that can be used when establishing partnerships
*/
    @JsonPropertyOrder({
        AgreementSpecification.JSON_PROPERTY_ID,
        AgreementSpecification.JSON_PROPERTY_HREF,
        AgreementSpecification.JSON_PROPERTY_DESCRIPTION,
        AgreementSpecification.JSON_PROPERTY_IS_BUNDLE,
        AgreementSpecification.JSON_PROPERTY_LAST_UPDATE,
        AgreementSpecification.JSON_PROPERTY_LIFECYCLE_STATUS,
        AgreementSpecification.JSON_PROPERTY_NAME,
        AgreementSpecification.JSON_PROPERTY_VERSION,
        AgreementSpecification.JSON_PROPERTY_ATTACHMENT,
        AgreementSpecification.JSON_PROPERTY_RELATED_PARTY,
        AgreementSpecification.JSON_PROPERTY_SERVICE_CATEGORY,
        AgreementSpecification.JSON_PROPERTY_SPECIFICATION_CHARACTERISTIC,
        AgreementSpecification.JSON_PROPERTY_SPECIFICATION_RELATIONSHIP,
        AgreementSpecification.JSON_PROPERTY_VALID_FOR,
        AgreementSpecification.JSON_PROPERTY_AT_BASE_TYPE,
        AgreementSpecification.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        AgreementSpecification.JSON_PROPERTY_AT_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class AgreementSpecification implements Serializable {
        public static final String JSON_PROPERTY_ID = "id";
            private String id;

        public static final String JSON_PROPERTY_HREF = "href";
            private String href;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_IS_BUNDLE = "isBundle";
            private Boolean isBundle;

        public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
            private OffsetDateTime lastUpdate;

        public static final String JSON_PROPERTY_LIFECYCLE_STATUS = "lifecycleStatus";
            private String lifecycleStatus;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_VERSION = "version";
            private String version;

        public static final String JSON_PROPERTY_ATTACHMENT = "attachment";
            private List<AttachmentRefOrValue> attachment = new ArrayList<>();

        public static final String JSON_PROPERTY_RELATED_PARTY = "relatedParty";
            private List<RelatedParty> relatedParty;

        public static final String JSON_PROPERTY_SERVICE_CATEGORY = "serviceCategory";
            private CategoryRef serviceCategory;

        public static final String JSON_PROPERTY_SPECIFICATION_CHARACTERISTIC = "specificationCharacteristic";
            private List<AgreementSpecCharacteristic> specificationCharacteristic;

        public static final String JSON_PROPERTY_SPECIFICATION_RELATIONSHIP = "specificationRelationship";
            private List<AgreementSpecificationRelationship> specificationRelationship;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;



}

