/*
 * Agreement Management
 * This is Swagger UI environment generated for the TMF Agreement Management specification
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.agreement.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import de.bitconex.tmf.agreement.model.Quantity;
    import de.bitconex.tmf.agreement.model.TimePeriod;
    import java.net.URI;
    import com.fasterxml.jackson.annotation.*;
import java.io.Serializable;

        /**
* An attachment by value or by reference. An attachment complements the description of an element, for example through a document, a video, a picture.
*/
    @JsonPropertyOrder({
        AttachmentRefOrValue.JSON_PROPERTY_ID,
        AttachmentRefOrValue.JSON_PROPERTY_HREF,
        AttachmentRefOrValue.JSON_PROPERTY_ATTACHMENT_TYPE,
        AttachmentRefOrValue.JSON_PROPERTY_CONTENT,
        AttachmentRefOrValue.JSON_PROPERTY_DESCRIPTION,
        AttachmentRefOrValue.JSON_PROPERTY_MIME_TYPE,
        AttachmentRefOrValue.JSON_PROPERTY_NAME,
        AttachmentRefOrValue.JSON_PROPERTY_URL,
        AttachmentRefOrValue.JSON_PROPERTY_SIZE,
        AttachmentRefOrValue.JSON_PROPERTY_VALID_FOR,
        AttachmentRefOrValue.JSON_PROPERTY_AT_BASE_TYPE,
        AttachmentRefOrValue.JSON_PROPERTY_AT_SCHEMA_LOCATION,
        AttachmentRefOrValue.JSON_PROPERTY_AT_TYPE,
        AttachmentRefOrValue.JSON_PROPERTY_AT_REFERRED_TYPE
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class AttachmentRefOrValue implements Serializable {
        public static final String JSON_PROPERTY_ID = "id";
            private String id;

        public static final String JSON_PROPERTY_HREF = "href";
            private String href;

        public static final String JSON_PROPERTY_ATTACHMENT_TYPE = "attachmentType";
            private String attachmentType;

        public static final String JSON_PROPERTY_CONTENT = "content";
            private String content;

        public static final String JSON_PROPERTY_DESCRIPTION = "description";
            private String description;

        public static final String JSON_PROPERTY_MIME_TYPE = "mimeType";
            private String mimeType;

        public static final String JSON_PROPERTY_NAME = "name";
            private String name;

        public static final String JSON_PROPERTY_URL = "url";
            private String url;

        public static final String JSON_PROPERTY_SIZE = "size";
            private Quantity size;

        public static final String JSON_PROPERTY_VALID_FOR = "validFor";
            private TimePeriod validFor;

        public static final String JSON_PROPERTY_AT_BASE_TYPE = "@baseType";
            private String atBaseType;

        public static final String JSON_PROPERTY_AT_SCHEMA_LOCATION = "@schemaLocation";
            private URI atSchemaLocation;

        public static final String JSON_PROPERTY_AT_TYPE = "@type";
            private String atType;

        public static final String JSON_PROPERTY_AT_REFERRED_TYPE = "@referredType";
            private String atReferredType;



}

