/*
 * Agreement Management
 * This is Swagger UI environment generated for the TMF Agreement Management specification
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bitconex.tmf.agreement.model;

import java.util.Objects;
import java.util.Arrays;
    import com.fasterxml.jackson.annotation.JsonInclude;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.JsonValue;
    import java.time.OffsetDateTime;
    import com.fasterxml.jackson.annotation.*;
import java.io.Serializable;

        /**
* A period of time, either as a deadline (endDateTime only) a startDateTime only, or both
*/
    @JsonPropertyOrder({
        TimePeriod.JSON_PROPERTY_END_DATE_TIME,
        TimePeriod.JSON_PROPERTY_START_DATE_TIME
    })
@lombok.Data
@lombok.Builder
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)

public class TimePeriod implements Serializable {
        public static final String JSON_PROPERTY_END_DATE_TIME = "endDateTime";
            private OffsetDateTime endDateTime;

        public static final String JSON_PROPERTY_START_DATE_TIME = "startDateTime";
            private OffsetDateTime startDateTime;



}

