
alter table T_HW_BG_CHANGE_CARD modify HW_BAUGRUPPEN_ID_NEW NULL;

GRANT DELETE ON T_HW_BG_CHANGE_CARD_SOURCE TO R_HURRICAN_USER;

ALTER TABLE T_HW_BG_CHANGE_CARD_SOURCE ADD CONSTRAINT UK_T_HWBG_CARD_SOURCE
  UNIQUE (HW_BG_CHANGE_CARD_ID, HW_BAUGRUPPEN_ID_TO_CHANGE);
