package de.mnet.wita;

/**
 * Constants to trigger WITA simulator behavior.
 * <p/>
 * WITA simulator chooses defined behavior by the set user name.
 */
public enum WitaSimulatorTestUser {

    NUR_TEQ("NUR_TEQ"), // nicht konfiguriert, deshalb kommt nur die TEQ
    // Bereitstellung

    NEU_ABBM("NEU_ABBM"),
    NEU_QEB_ABBM(NEU_ABBM.getName(), "NEU_QEB_ABBM"),
    NEU_QEB_ABM("NEU_QEB_ABM"),
    NEU_QEB_ABM_ABBM("NEU_QEB_ABM_ABBM"),
    NEU_QEB_ABM_ABM_ERLM_ENTM("NEU_QEB_ABM_ABM_ERLM_ENTM"),
    NEU_QEB_ABM_ERLM_ENTM("NEU_QEB_ABM_ERLM_ENTM"),
    NEU_QEB_ABM_BEFORE_HOLIDAY("NEU_QEB_ABM_BEFORE_HOLIDAY"),
    NEU_QEB_ABM_ENTM_ERLM("NEU_QEB_ABM_ENTM_ERLM"),
    NEU_QEB_ABM_STORNO_ABBM("NEU_QEB_ABM_STORNO_ABBM"), // NEU_QEB_ABM_STORNO_ABBM_ERLM_ENTM
    NEU_QEB_ABM_ERLM_STORNO_ABBM("NEU_QEB_ABM_ERLM_STORNO_ABBM"), // NEU_QEB_ABM_STORNO_ERLM_ABBM_ENTM
    NEU_QEB_STORNO_STORNO("NEU_QEB_STORNO_STORNO"), // NEU_QEB_STORNO_ERLM_ENTM_STORNO_ABBM
    NEU_QEB_TV_ABM_ERLM_TV_ABBM("NEU_QEB_TV_ABM_ERLM_TV_ABBM"),
    NEU_QEB_ABM_TV_ABM_ERLM_ENTM("NEU_QEB_ABM_TV_ABM_ERLM_ENTM"),
    NEU_QEB_STORNO_ERLM_ENTM("NEU_QEB_STORNO_ERLM_ENTM"),
    NEU_ABM_TAM_ENTM("NEU_ABM_TAM_ENTM"), // Workflow Error
    NEU_QEB_ERLM_ENTM("NEU_QEB_ERLM_ENTM"), // Workflow Error
    NEU_QEB_ENTM("NEU_QEB_ENTM"), // Workflow Error
    NEU_ABM_TAM_TAM("NEU_ABM_TAM_TAM"),
    NEU_ABM_TAM_MTAM("NEU_ABM_TAM_MTAM"),
    NEU_ABM_TAM_TV_TAM("NEU_ABM_TAM_TV_TAM"),
    NEU_ABM_TV_TAM_ABM("NEU_ABM_TV_TAM_ABM"),
    NEU_ABM_TV_TAM_ERLM("NEU_ABM_TV_TAM_ERLM"),
    NEU_QEB_ABM_TAM_TAM_ABBM("NEU_QEB_ABM_TAM_TAM_ABBM"),

    TAL_BEREIT_NEU_01A("TAL_Bereit_Neu_01a", "V0700_TAL_NEU_01a"), //NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_01B("TAL_Bereit_Neu_01b", "V0700_TAL_NEU_01b"), //NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_02A("TAL_Bereit_Neu_02a"), //NEU_QEB_ABM_ERLM_ENTM nur noch für V4 gültig
    TAL_BEREIT_NEU_02AA("TAL_Bereit_Neu_02aa", "V0700_TAL_NEU_02aa"), //NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_02AB("TAL_Bereit_Neu_02ab", "V0700_TAL_NEU_02ab"), //NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_02BA("TAL_Bereit_Neu_02b", "V0700_TAL_NEU_02ba"), //NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_02BB("TAL_Bereit_Neu_02b", "V0700_TAL_NEU_02bb"), //NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_03("TAL_Bereit_Neu_03", "V0700_TAL_NEU_03"), // NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_04("TAL_Bereit_Neu_04", "V0700_TAL_NEU_04"), // NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_05("TAL_Bereit_Neu_05", "V0700_TAL_NEU_05"), // NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_06("TAL_Bereit_Neu_06", "V0700_TAL_NEU_06"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_07("TAL_Bereit_Neu_07", "V0700_TAL_NEU_07"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_08("TAL_Bereit_Neu_08", "V0700_TAL_NEU_08"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_09("TAL_Bereit_Neu_09", "V0700_TAL_NEU_09"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_10("TAL_Bereit_Neu_10", "V0700_TAL_NEU_10"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_11("TAL_Bereit_Neu_11", "V0700_TAL_NEU_11"),
    TAL_BEREIT_NEU_12A("TAL_Bereit_Neu_12a", "V0700_TAL_NEU_12a"),
    TAL_BEREIT_NEU_12B("TAL_Bereit_Neu_12b", "V0700_TAL_NEU_12b"),
    TAL_BEREIT_NEU_13("TAL_Bereit_Neu_13", "V0700_TAL_NEU_13"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_14a("TAL_Bereit_Neu_14a", "V0700_TAL_NEU_14a"), // NEU_QEB_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_14b("TAL_Bereit_Neu_14b", "V0700_TAL_NEU_14b"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_15("TAL_Bereit_Neu_15", "V0700_TAL_NEU_15"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_16("TAL_Bereit_Neu_16", "V0700_TAL_NEU_16"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_17("TAL_Bereit_Neu_17", "V0700_TAL_NEU_17"), // NEU_ABBM
    TAL_BEREIT_NEU_18("TAL_Bereit_Neu_18", "V0700_TAL_NEU_18"), // NEU_QEB_ABBM
    TAL_BEREIT_NEU_19("TAL_Bereit_Neu_19", "V0700_TAL_NEU_19"), //NEU_QEB_STORNO_STORNO
    TAL_BEREIT_NEU_20("TAL_Bereit_Neu_20", "V0700_TAL_NEU_20"), //NEU_QEB_ABM_STORNO_ABBM
    TAL_BEREIT_NEU_21("TAL_Bereit_Neu_21", "V0700_TAL_NEU_21"), //NEU_QEB_ABM_ERLM_STORNO_ABBM
    TAL_BEREIT_NEU_22("TAL_Bereit_Neu_22", "V0700_TAL_NEU_22"), //NEU_QEB_TV_ABM_ERLM_TV_ABBM
    TAL_BEREIT_NEU_23("TAL_Bereit_Neu_23", "V0700_TAL_NEU_23"), // NEU_QEB_ABM_TAM_ABM_ERLM_ENTM
    TAL_BEREIT_NEU_24("TAL_Bereit_Neu_24", "V0700_TAL_NEU_24"), // NEU_QEB_ABM_TAM_ERLM-K_ENTM
    TAL_BEREIT_NEU_25("TAL_Bereit_Neu_25"),
    TAL_BEREIT_NEU_26("TAL_Bereit_Neu_26"),
    TAL_BEREIT_NEU_27("TAL_Bereit_Neu_27"),

    // Kuendigung
    KUE_KD_QEB_ABM_ERLM_ENTM("KUE_KD_QEB_ABM_ERLM_ENTM"),
    KUE_KD_QEB_ABM_TV("KUE_KD_QEB_ABM_TV"), // KUE-KD_QEB_ABM_TV_ABM_ERLM_ENTM
    KUE_KD_QEB_STORNO_ERLM_ENTM("KUE_KD_QEB_STORNO_ERLM_ENTM"),
    TAL_KUENDIGUNG_KUE_KD_01_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_KUE-KD_01"),
    TAL_KUENDIGUNG_KUE_KD_01("TAL_Kündigung_KUE-KD_01", "V0700_TAL_KUE-KD_01"), // KUE-KD_QEB_ABM_ERLM_ENTM
    TAL_KUENDIGUNG_KUE_KD_02_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_KUE-KD_02"),
    TAL_KUENDIGUNG_KUE_KD_02("TAL_Kündigung_KUE-KD_02", "V0700_TAL_KUE-KD_02"), // KUE-KD_QEB_ABBM
    TAL_KUENDIGUNG_KUE_KD_03_LAE("LAE_QEB_ABM_ERLM_ENTM", "V0700_TAL_KUE-KD_03"), // LAE_QEB_ABM_ERLM_ENTM
    TAL_KUENDIGUNG_KUE_KD_03("TAL_Kündigung_KUE-KD_03", "V0700_TAL_KUE-KD_03"), // KUE-KD_QEB_ABM_ERLM_ENTM
    TAL_KUENDIGUNG_KUE_KD_03_KD2("TAL_Kündigung_KUE-KD_03_KD2", "V0700_TAL_KUE-KD_03"), // KUE-KD_QEB_ABBM
    TAL_KUENDIGUNG_KUE_KD_04_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_KUE-KD_04"),
    TAL_KUENDIGUNG_KUE_KD_04("TAL_Kündigung_KUE-KD_04", "V0700_TAL_KUE-KD_04"), // KUE-KD_QEB_ABM_Storno_ERLM_ENTM
    TAL_KUENDIGUNG_KUE_KD_05_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_KUE-KD_05"),
    TAL_KUENDIGUNG_KUE_KD_05("TAL_Kündigung_KUE-KD_05", "V0700_TAL_KUE-KD_05"), // KUE-KD_QEB_ABM_TV_ABM_ERLM_ENTM

    // Kuendigung durch DTAG
    TAL_KUENDIGUNG_KUE_DT_01("TAL_Kündigung_KUE-DT_01", "V0700_TAL_KUE-DT_01"),
    KUEDT_ENTM_ERLM("KUEDT_ENTM_ERLM"), // NEU,QEB,ABM,ERLM,ENTM,ENTM(KUE-DT),ERLM(KUE-DT)
    USERTEST_KUEDT("USERTEST_KUEDT"), // NEU_QEB_ABM_TAM_ERLMK_ENTM_ERLM_ENTM

    // LeistungsAenderung
    LAE_QEB_ABM_ERLM_ENTM("LAE_QEB_ABM_ERLM_ENTM"),
    LAE_QEB_ABM_TV_ABM_ERLM_ENTM("LAE_QEB_ABM_TV_ABM_ERLM_ENTM"),
    LAE_QEB_STORNO_ELRM_ENTM("LAE_QEB_STORNO_ELRM_ENTM"),
    TAL_AENDERUNG_LAE_01_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM_nbit", "V0700_TAL_LAE_01"),
    TAL_AENDERUNG_LAE_01("TAL_Änderung_LAE_01", "V0700_TAL_LAE_01"), // LAE_QEB_ABM_VZM_ERLM_ENTM
    TAL_AENDERUNG_LAE_VZMPV_01("TAL_Änderung_LAE_VZMPV_01", "V0700_TAL_LAE_01"),
    TAL_AENDERUNG_LAE_02_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM_nbit", "V0700_TAL_LAE_02"),
    TAL_AENDERUNG_LAE_02("TAL_Änderung_LAE_02", "V0700_TAL_LAE_02"), // LAE_QEB_ABBM

    // LeistungsmerkmalAenderung
    TAL_AENDERUNG_AEN_LMAE_01("TAL_Aenderung_AEN-LMAE_01", "V0700_TAL_AEN-LMAE_01"), // LMAE_QEB_VZM_ABM_ERLM_ENTM
    TAL_AENDERUNG_AEN_LMAE_01_NEU("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_AEN-LMAE_01"), // NEU_QEB_ABM_ERLM_ENTM
    TAL_AENDERUNG_AEN_LMAE_02("TAL_Aenderung_AEN-LMAE_02", "V0700_TAL_AEN-LMAE_02"), // LMAE_QEB_ABBM
    TAL_AENDERUNG_AEN_LMAE_02_NEU("LAE_QEB_ABM_ERLM_ENTM", "V0700_TAL_AEN-LMAE_02"), // NEU_QEB_ABM_ERLM_ENTM
    TAL_AENDERUNG_AEN_LMAE_03("TAL_Aenderung_AEN-LMAE_03", "V0700_TAL_AEN-LMAE_03"), // LMAE_QEB_ABBM
    TAL_AENDERUNG_AEN_LMAE_03_VBL("TAL_Verbundleistung_VBLT_01", "V0700_TAL_AEN-LMAE_03"), // VBL_ABM_ERLM_ENTM
    LMAE_QEB_STORNO_ERLM_ENTM("LMAE_QEB_STORNO_ERLM_ENTM"),
    LMAE_QEB_TV_ABM_ERLM_ENTM("LMAE_QEB_TV_ABM_ERLM_ENTM"),
    LMAE_QEB_ABM_ERLM_ENTM("LMAE_QEB_ABM_ERLM_ENTM"),

    // Portwechsel
    SER_POW_QEB_STORNO_ERLM_ENTM("SER_POW_QEB_STORNO_ERLM_ENTM"),
    SER_POW_QEB_TV_ABM_ERLM_ENTM("SER_POW_QEB_TV_ABM_ERLM_ENTM"),
    TAL_SERVICE_POW_01_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_SER-POW_01"),
    TAL_SERVICE_POW_01("TAL_Service_POW_01", "V0700_TAL_SER-POW_01"), // SER-POW_QEB_ABM_ERLM_ENTM

    // Providerwechsel
    TAL_PROVIDERWECHSEL_PV3_01("TAL_Providerwechsel_PV3_01", "V0700_TAL_PV3_01"), // PV_QEB_ABM_ERLM_ENTM
    TAL_PROVIDERWECHSEL_PV3_02("TAL_Providerwechsel_PV3_02", "V0700_TAL_PV3_02"), // PV_QEB_ABM_ERLM_ENTM
    TAL_PROVIDERWECHSEL_PV3_03("TAL_Providerwechsel_PV3_03", "V0700_TAL_PV3_03"), // PV_QEB_ABBM
    TAL_PROVIDERWECHSEL_PV3_04("TAL_Providerwechsel_PV3_04", "V0700_TAL_PV3_04"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV_ABMPV_ERLMPV_ENTMPV
    TAL_PROVIDERWECHSEL_PV3_05("TAL_Providerwechsel_PV3_05", "V0700_TAL_PV3_05"), // PV_QEB_ABBM
    TAL_PROVIDERWECHSEL_PV3_06("TAL_Providerwechsel_PV3_06", "V0700_TAL_PV3_06"), // PV_QEB_STORNO_ERLM_ENTM
    TAL_PROVIDERWECHSEL_PV3_07("TAL_Providerwechsel_PV3_07", "V0700_TAL_PV3_07"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_ABBMPV
    TAL_PROVIDERWECHSEL_PV3_08("TAL_Providerwechsel_PV3_08", "V0700_TAL_PV3_08"), // PV_QEB_TV_ABM_ERLM_ENTM
    TAL_PROVIDERWECHSEL_PV3_09("TAL_Providerwechsel_PV3_09", "V0700_TAL_PV3_09"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV_ABMPV_ERLMPV_ENTMPV
    TAL_PROVIDERWECHSEL_PV3_10("TAL_Providerwechsel_PV3_10", "V0700_TAL_PV3_10"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV
    TAL_PROVIDERWECHSEL_PV3_11("TAL_Providerwechsel_PV3_11", "V0700_TAL_PV3_11"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV
    TAL_PROVIDERWECHSEL_PV3_12("TAL_Providerwechsel_PV3_12", "V0700_TAL_PV3_12"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV_ABMPV_ABMPV
    AKMPV_RUEMPV_ABMPV_ABBMPV("AKMPV_RUEMPV_ABMPV_ABBMPV"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV_ABMPV_ABBMPV
    AKMPV_RUEMPV_ABBMPV("AKMPV_RUEMPV_ABBMPV"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV_ABBMPV
    AKMPV_RUEMPV_ABMPV_ENTM_ERLM("AKMPV_RUEMPV_ABMPV_ENTM_ERLM"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_RUEMPV_ABMPV_ENTMPV_ERLMPV
    USERTEST_AKMPV_RUEMPV_ABBMPV("USERTEST_AKMPV_RUEMPV_ABBMPV"), // NEU_QEB_ABM_TAM_ERLMK_ENTM_AKMPV_RUEMPV_ABBMPV
    USERTEST_AKMPV_RUEMPV_ABMPV("USERTEST_AKMPV_RUEMPV_ABMPV"), // NEU_QEB_ABM_TAM_ERLMK_ENTM_AKMPV_RUEMPV_ABBMPV
    AKMPV_ERLMPV_ENTMPV("AKMPV_ERLMPV_ENTMPV"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_ERLMPV_ENTMPV -- Workflow Error
    AKMPV_ENTMPV("AKMPV_ENTMPV"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_ENTMPV -- Workflow Error
    AKMPV_AKMPV("AKMPV_AKMPV"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_AKMPV
    PV_NEU("PV_NEU"),

    TAL_PROVIDERWECHSEL_TAM_MTAM_RUEMPV("TAL_PV_TAM_MTAM_RUEMPV"),
    TAL_VBL_TAM_MTAM_RUEMPV("TAL_VBL_TAM_MTAM_RUEMPV"),

    // REX-MK
    TAL_RUFNUMMERNEXPORT_REX_MK_01("TAL_Rufnummernexport_REX-MK_01", "V0700_TAL_REX-MK_01"), // REX-MK_QEB_ABM_ERLM
    TAL_RUFNUMMERNEXPORT_REX_MK_02("TAL_Rufnummernexport_REX-MK_02", "V0700_TAL_REX-MK_02"), // REX-MK_QEB_ABM_ERLM
    TAL_RUFNUMMERNEXPORT_REX_MK_03("TAL_Rufnummernexport_REX-MK_03", "V0700_TAL_REX-MK_03"), // REX-MK_QEB_ABBM
    REX_MK_QEB_STORNO_ERLM_ENTM("REX_MK_QEB_STORNO_ERLM_ENTM"),
    REX_MK_QEB_TV_ABM_ERLM("REX_MK_QEB_TV_ABM_ERLM"),

    // Verbundleistung (abgebender Carrier=DTAG)
    TAL_VERBUNDLEISTUNG_VBLT_01("TAL_Verbundleistung_VBLT_01", "V0700_TAL_VBLT_01"), // VBL_ABM_ERLM_ENTM
    TAL_VERBUNDLEISTUNG_VBLT_02("TAL_Verbundleistung_VBLT_02", "V0700_TAL_VBLT_02"), // VBL_ABM_ERLM_ENTM
    TAL_VERBUNDLEISTUNG_VBLT_03("TAL_Verbundleistung_VBLT_03", "V0700_TAL_VBLT_03"), // VBL_QEB_ABBM
    TAL_VERBUNDLEISTUNG_VBLT_04("TAL_Verbundleistung_VBLT_04", "V0700_TAL_VBLT_04"), // VBL_QEB_ABBM
    TAL_VERBUNDLEISTUNG_VBLT_05("TAL_Verbundleistung_VBLT_05", "V0700_TAL_VBLT_05"), // VBL_QEB_STORNO_ERLM_ENTM
    TAL_VERBUNDLEISTUNG_VBLT_06("TAL_Verbundleistung_VBLT_06", "V0700_TAL_VBLT_06"),
    TAL_VERBUNDLEISTUNG_VBLT_07("TAL_Verbundleistung_VBLT_07", "V0700_TAL_VBLT_07"),
    TAL_VERBUNDLEISTUNG_VBLT_08("TAL_Verbundleistung_VBLT_08", "V0700_TAL_VBLT_08"), // VBL_QEB_TV_ABM_ERLM_ENTM
    TAL_VERBUNDLEISTUNG_VBLT_09("TAL_Verbundleistung_VBLT_09", "V0700_TAL_VBLT_09"), // VBL_QEB_STORNO_ERLM_ENTM

    // Verbundleistung (3er-Prozess)
    TAL_VERBUNDLEISTUNG_VBL3_01("TAL_Verbundleistung_VBL3_01", "V0700_TAL_VBL3_01"),
    TAL_VERBUNDLEISTUNG_VBL3_02("TAL_Verbundleistung_VBL3_02", "V0700_TAL_VBL3_02"),
    TAL_VERBUNDLEISTUNG_VBL3_03("TAL_Verbundleistung_VBL3_03", "V0700_TAL_VBL3_03"),
    TAL_VERBUNDLEISTUNG_VBL3_04("TAL_Verbundleistung_VBL3_04", "V0700_TAL_VBL3_04"),
    TAL_VERBUNDLEISTUNG_VBL3_05("TAL_Verbundleistung_VBL3_05", "V0700_TAL_VBL3_05"),
    TAL_VERBUNDLEISTUNG_VBL3_06("TAL_Verbundleistung_VBL3_06", "V0700_TAL_VBL3_06"),

    TAL_VERFUEGBARKEIT_01("NEU_QEB_ABM", "V0700_TAL_Verfügbarkeit_01"), // TAL Neu und DTAG antwortet mit 100 QEBs

    TAL_AUSKUNFT_AUS_BUE_01("TAL_Auskunft_AUS-BUE_01", "V0700_TAL_AUS-BUE_01"), // AUS-BUE_QEB_ERGM_ENTM

    TAL_NOK_01("TAL_TEQ-NOK_01", "V0700_TAL_TEQ-NOK_01"), // DTAG sendet QEB mit falscher Version und ABBM mit Alternativ-Produkt
    TAL_NOK_02("NEU_QEB_ABM", "V0700_TAL_TEQ-NOK_02"), // Dummy Auftrag senden, ActiveMQ wird manuell beendet

    TAL_VW_NEU_01("TAL_Wita_Version_Migr_NEU", "V0700_TAL_VW_NEU_01"),
    TAL_VW_KUE_02_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_VW_KUE_02"),
    TAL_VW_KUE_02("TAL_Wita_Version_Migr_KUE", "V0700_TAL_VW_KUE_02"),
    TAL_VW_LAE_03_NEUBESTELLUNG("NEU_QEB_ABM_ERLM_ENTM", "V0700_TAL_VW_LAE_03"),
    TAL_VW_LAE_03("TAL_Wita_Version_Migr_LAE", "V0700_TAL_VW_LAE_03"),
    TAL_VW_PV_04("TAL_Wita_Version_Migr_PV", "V0700_TAL_VW_PV_04"),
    TAL_VW_VBLT_05("TAL_Wita_Version_Migr_VBLT", "V0700_TAL_VW_VBLT_05"),
    TAL_WITA_VERSION_MIGR_STORNO("TAL_Wita_Version_Migr_Storno"), // PV_QEB_STORNO_ERLM_ENTM
    TAL_WITA_VERSION_MIGR_AKMPV("TAL_Wita_Version_Migr_AkmPV"), // NEU_QEB_ABM_ERLM_ENTM_AKMPV_ABBMPV
    TAL_WITA_VERSION_MIGR_TV("TAL_Wita_Version_Migr_TV"), // PV_QEB_TV_ABM_ERLM_ENTM
    TAL_WITA_WBCI_CONFORM_01A("TAL_Wita_Wbci_Conform_01a"), // 2 x VBL (geklamert) DTAG
    TAL_WITA_WBCI_CONFORM_01B("TAL_Wita_Wbci_Conform_01b"), // 2 x VBL (geklamert) VODAFONE
    TAL_WITA_WBCI_CONFORM_02("TAL_Wita_Wbci_Conform_02"), // 2 x PVL (geklamert)
    TAL_WITA_WBCI_CONFORM_03("TAL_Wita_Wbci_Conform_03"), // Check vor wbci and wita dates (TV)
    TAL_WITA_WBCI_CONFORM_04("TAL_Wita_Wbci_Conform_04"), // Check vor wbci and wita dates (TV) => no TV sent in case of an date mismatch
    TAL_WITA_WBCI_CONFROM_05("TAL_Wita_Wbci_Conform_05"), // Check vor wbci and wita dates (ABM) => mark as Klaerfall
    TAL_WITA_WBCI_CONFORM_06("TAL_Wita_Wbci_Conform_06"), // automatic WBCI ERLM-TV processing => triggers a WITA TV
    TAL_WITA_WBCI_CONFORM_07("TAL_Wita_Wbci_Conform_07"), // automatic WBCI AKM-TR processing => triggers a WITA NEU
    TAL_WITA_WBCI_CONFORM_08("TAL_Wita_Wbci_Conform_08"), // automatic WBCI STR-AUFH ERLM processing => triggers a WITA Storno

    TAL_ZF_LOGIC_SINCE_FEB_2014_NEU("TAL_Zf_Since_Feb_2014_NEU"),
    TAL_ZF_LOGIC_SINCE_FEB_2014_KUEKD("TAL_Zf_Since_Feb_2014_KUEKD"),

    // HVT_KVZ
    HVT_KVZ("HVT_KVZ"),
    HVT_KVZ_OTHER_KUENDIGUNG_DATE("HVT_KVZ_OTHER_KUENDIGUNG_DATE"),
    HVT_KVZ_OTHER_KUE_DATE_2("HVT_KVZ_OTHER_KUE_DATE_2"),
    HVT_KVZ_OTHER_KUE_DATE_KVZ("HVT_KVZ_OTHER_KUE_DATE_KVZ"),
    HVT_KVZ_ABBM_KVZ("HVT_KVZ_ABBM_KVZ"),
    HVT_KVZ_ABBM_KVZ_SECOND_KVZ("HVT_KVZ_ABBM_KVZ_SECOND_KVZ"),
    HVT_KVZ_ABBM_HVT("HVT_KVZ_ABBM_HVT"),

    ENCODING_NEU_ABBM("ENCODING_NEU_ABBM");

    /**
     * Nachname für WITA-Simulator-Tests
     */
    private String simulatorName;
    /**
     * Nachname für KFT-Tests mit DTAG (Version v7)
     */
    private String dtagNameV7;

    /**
     * Für Usernamen, die für WITA-Simulator und KFT-Tests gleich sind
     */
    WitaSimulatorTestUser(String userName) {
        checkSimulatorUsername(userName);
        this.simulatorName = userName;
    }

    /**
     * Für Usernamen, die für WITA-Simulator und KFT-Tests unterschiedlich sind
     */
    WitaSimulatorTestUser(String simulatorName, String dtagNameV7) {
        checkSimulatorUsername(simulatorName);
        this.simulatorName = simulatorName;
        this.dtagNameV7 = dtagNameV7;
    }

    private void checkSimulatorUsername(String simulatorName) {
        if (simulatorName.length() > 30) {
            throw new RuntimeException(
                    "User-Namen, die länger als 30 Zeichen sind, werden vom WITA-Simulator nicht unterstützt, wie z.B.:"
                            + simulatorName
            );
        }
    }

    public String getName() {
        String recipient = System.getProperty("wita.message.recipient", "SIMULATOR");
        if (recipient.equalsIgnoreCase("DTAG_V7")) {
            return dtagNameV7;
        }

        return simulatorName;
    }

    public static boolean existsUsername(String name) {
        for (WitaSimulatorTestUser user : WitaSimulatorTestUser.values()) {
            if (user.getName().equals(name)) {
                return true;
            }
        }
        return false;
    }
}
