UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'BEREITSTELLUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Bereitstellung';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'BEREITSTELLUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'NEU';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'BESTANDSUEBERSICHT'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Bestandsuebersicht';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'BESTANDSUEBERSICHT'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'AUS-BUE';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'KUENDIGUNG_KUNDE'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Kuendigung';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'KUENDIGUNG_KUNDE'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'KUE-KD';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'KUENDIGUNG_TELEKOM'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'KUE-DT';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'LEISTUNGSMERKMAL_AENDERUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'AEN-LMAE';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'LEISTUNGSMERKMAL_AENDERUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'LeistungsmerkmalAenderung';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'LEISTUNGS_AENDERUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'LAE';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'LEISTUNGS_AENDERUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Leistungsaenderung';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'PORTWECHSEL'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'SER-POW';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'PORTWECHSEL'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Portwechsel';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'PRODUKTGRUPPENWECHSEL'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'PGW';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'PRODUKTGRUPPENWECHSEL'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Produktgruppenwechsel';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'PROVIDERWECHSEL'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'PV';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'PROVIDERWECHSEL'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Providerwechsel';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'REX-MK';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'RnrExportMitKuendigung';

UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'VERBUNDLEISTUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'VBL';
UPDATE   T_IO_ARCHIVE IO
   SET   IO.REQUEST_GESCHAEFTSFALL = 'VERBUNDLEISTUNG'
 WHERE   IO.REQUEST_GESCHAEFTSFALL = 'Verbundleistung';

ALTER TABLE T_IO_ARCHIVE
 ADD CONSTRAINT CK_IO_ARCHIVE_GF
  CHECK (REQUEST_GESCHAEFTSFALL IN (
  'BEREITSTELLUNG',
  'BESTANDSUEBERSICHT',
  'KUENDIGUNG_KUNDE',
  'KUENDIGUNG_TELEKOM',
  'LEISTUNGSMERKMAL_AENDERUNG',
  'LEISTUNGS_AENDERUNG',
  'PORTWECHSEL',
  'PRODUKTGRUPPENWECHSEL',
  'PROVIDERWECHSEL',
  'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG',
  'VERBUNDLEISTUNG',
  'UNBEKANNT'));