ALTER TABLE T_MWF_REQUEST
MODIFY(REQUEST_WURDE_STORNIERT  DEFAULT '0');

UPDATE T_MWF_REQUEST
SET REQUEST_WURDE_STORNIERT = '0'
WHERE REQUEST_WURDE_STORNIERT is null;

ALTER TABLE T_MWF_REQUEST
MODIFY(REQUEST_WURDE_STORNIERT  NOT NULL);