CREATE TABLE T_EXCEPTION_LOG
(
   ID                    NUMBER (19)            NOT NULL,
   VERSION               NUMBER (19) DEFAULT 0  NOT NULL,
   CONTEXT               VARCHAR2 (50),
   HOST                  VARCHAR2 (30)          NOT NULL,
   ERROR_MESSAGE         VARCHAR2 (255)         NOT NULL,
   STACKTRACE            CLOB,
   DATE_OCCURED          DATE                   NOT NULL,
   BEARBEITER            VARCHAR2 (50),
   SOLUTION              VARCHAR2 (255),
   DATEW                 DATE,
   PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE ON T_EXCEPTION_LOG TO R_HURRICAN_USER;
GRANT SELECT ON T_EXCEPTION_LOG TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_EXCEPTION_LOG_0
   START WITH 1;

GRANT SELECT ON S_T_EXCEPTION_LOG_0 TO PUBLIC;


CREATE OR REPLACE TRIGGER TRBIU_EXCEPTION_LOG BEFORE INSERT or UPDATE on T_EXCEPTION_LOG
for each row
begin
 SELECT LOCALTIMESTAMP into :new.DATEW FROM dual;
end T_EXCEPTION_LOG;
/

