ALTER TABLE T_MWF_MELDUNGS_POSITION ADD (POSITIONSATTRIBUTE_ID  NUMBER(19));

CREATE TABLE T_MWF_POSITIONSATTRIBUTE
(
  ID                           NUMBER(19)       NOT NULL,
  VERSION                      NUMBER(19)       NOT NULL,
  ERLTERMIN_OFFENER_AUFTRAG    DATE,
  ALTERNATIVPRODUKT            VARCHAR2(100),
  FEHLAUFTRAGSNUMMER           VARCHAR2(100),
  STANDORT_KUNDE_KORREKTUR_ID  NUMBER(19),
  BESTANDSSUCHE_ID             NUMBER(19)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE T_MWF_POSITIONSATTRIBUTE ADD (
  CONSTRAINT T_MWF_POSITIONSATTRIBUTE_PK
  PRIMARY KEY
  (ID));


GRANT SELECT, INSERT, UPDATE ON T_MWF_POSITIONSATTRIBUTE TO R_HURRICAN_USER;
GRANT SELECT ON T_MWF_POSITIONSATTRIBUTE TO R_HURRICAN_READ_ONLY;

create sequence S_T_MWF_POSITIONSATTRIBUTE_0 start with 1;
grant select on S_T_MWF_POSITIONSATTRIBUTE_0 to public;

CREATE TABLE T_MWF_STANDORT_KUNDE_KORR
(
  ID                   NUMBER(19)               NOT NULL,
  VERSION              NUMBER                   NOT NULL,
  GEBAEUDETEIL_NAME    VARCHAR2(25),
  GEBAEUDETEIL_ZUSATZ  VARCHAR2(25),
  STRASSENNAME         VARCHAR2(40)             NOT NULL,
  HAUSNUMMER           VARCHAR2(4)              NOT NULL,
  HAUSNUMMERNZUSATZ    VARCHAR2(6),
  POSTLEITZAHL         VARCHAR2(10)             NOT NULL,
  ORTSNAME             VARCHAR2(40)             NOT NULL,
  ORTSTEIL             VARCHAR2(40),
  LAND                 VARCHAR2(2)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE T_MWF_STANDORT_KUNDE_KORR ADD (
  CONSTRAINT T_MWF_STANDORT_KUNDE_KORR_PK
  PRIMARY KEY
  (ID));

GRANT SELECT, INSERT, UPDATE ON T_MWF_STANDORT_KUNDE_KORR TO R_HURRICAN_USER;
GRANT SELECT ON T_MWF_STANDORT_KUNDE_KORR TO R_HURRICAN_READ_ONLY;

create sequence S_T_MWF_STANDORT_KUNDE_KORR_0 start with 1;
grant select on S_T_MWF_STANDORT_KUNDE_KORR_0 to public;

ALTER TABLE T_MWF_LEITUNGS_BEZEICHNUNG ADD (POSITIONSATTRIBUTE_ID  NUMBER(19));
ALTER TABLE T_MWF_PORT_RUFNUMMERNBLOCK ADD (ANSCHLUSS_PORTIERUNG_KORR_ID  NUMBER(19));

alter table T_MWF_MELDUNGS_POSITION add constraint FK_MPOS2POS_ATTRIBUTE foreign key (POSITIONSATTRIBUTE_ID) references T_MWF_POSITIONSATTRIBUTE;
alter table T_MWF_POSITIONSATTRIBUTE add constraint FK_POSATT2STANDORT_KUNDE foreign key (STANDORT_KUNDE_KORREKTUR_ID) references T_MWF_STANDORT_KUNDE_KORR;
alter table T_MWF_LEITUNGS_BEZEICHNUNG add constraint FK_LEITUNGSBEZ2POS_ATTRIBUTE foreign key (POSITIONSATTRIBUTE_ID) references T_MWF_POSITIONSATTRIBUTE;
alter table T_MWF_PORT_RUFNUMMERNBLOCK add constraint FK_PORT_RFBLOCK2PORT_KORREKT foreign key (ANSCHLUSS_PORTIERUNG_KORR_ID) references T_MWF_POSITIONSATTRIBUTE;

ALTER TABLE T_MWF_PORT_RUFNUMMERNBLOCK MODIFY(PORTIERUNGS_ID  NULL);

ALTER TABLE T_CB_VORGANG MODIFY(RET_BEMERKUNG VARCHAR2(1024 BYTE));

