-- Konfigurationstabelle zw. Produkt / Standorttyp inkl. Prio erstellen

create table T_PRODUKT_2_TECH_LOCATION_TYPE (
    ID NUMBER(10) NOT NULL
  , PROD_ID NUMBER(10) NOT NULL
  , TECH_LOCATION_TYPE_REF_ID NUMBER(10) NOT NULL
  , PRIORITY NUMBER(10) NOT NULL
  , USERW VARCHAR2(25) NOT NULL
  , DATEW DATE NOT NULL
  , VERSION NUMBER(18) DEFAULT 0 NOT NULL
);

ALTER TABLE T_PRODUKT_2_TECH_LOCATION_TYPE ADD CONSTRAINT PK_T_PRODUKT_2_TECH_LOCATION PRIMARY KEY (ID);
comment on table T_PRODUKT_2_TECH_LOCATION_TYPE is 'Definiert, ueber welche Standorttypen das Produkt realisiert werden kann';
comment on column T_PRODUKT_2_TECH_LOCATION_TYPE.PROD_ID is 'Produkt-ID';
comment on column T_PRODUKT_2_TECH_LOCATION_TYPE.TECH_LOCATION_TYPE_REF_ID is 'Referenz-ID des Standort-Typs';
comment on column T_PRODUKT_2_TECH_LOCATION_TYPE.PRIORITY is 'Prioritaet fuer den Standort-Typ (niedriger Wert = hohe Prio)';

CREATE INDEX IX_FK_PROD2TL_2_PRODID ON T_PRODUKT_2_TECH_LOCATION_TYPE (PROD_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PRODUKT_2_TECH_LOCATION_TYPE ADD CONSTRAINT FK_PROD2TL_2_PRODID
  FOREIGN KEY (PROD_ID) REFERENCES T_PRODUKT (PROD_ID);

CREATE INDEX IX_FK_PROD2TL_2_REF ON T_PRODUKT_2_TECH_LOCATION_TYPE (TECH_LOCATION_TYPE_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_PRODUKT_2_TECH_LOCATION_TYPE ADD CONSTRAINT FK_PROD2TL_2_REF
  FOREIGN KEY (TECH_LOCATION_TYPE_REF_ID) REFERENCES T_REFERENCE (ID);

grant select on T_PRODUKT_2_TECH_LOCATION_TYPE to R_HURRICAN_READ_ONLY;
grant select, insert, update, delete on T_PRODUKT_2_TECH_LOCATION_TYPE to R_HURRICAN_USER;

create sequence S_T_PRODUKT_2_TECH_LOC_TYPE_0 start with 1;
grant select on S_T_PRODUKT_2_TECH_LOC_TYPE_0 to public;

CREATE UNIQUE INDEX IUQ_PROD2TECHLOCATIONTYPE1 ON T_PRODUKT_2_TECH_LOCATION_TYPE (PROD_ID, TECH_LOCATION_TYPE_REF_ID);
CREATE UNIQUE INDEX IUQ_PROD2TECHLOCATIONTYPE2 ON T_PRODUKT_2_TECH_LOCATION_TYPE (PROD_ID, PRIORITY);

CREATE OR REPLACE TRIGGER TRBIU_PRODUKT_2_TECHLOCTYPE BEFORE INSERT OR UPDATE on T_PRODUKT_2_TECH_LOCATION_TYPE
for each row
begin
   -- DATEW setzen
   SELECT CURRENT_TIMESTAMP into :new.DATEW FROM dual;
end;
/
