alter table t_gewo_whg add GEO_ID NUMBER(19);
COMMENT ON COLUMN T_GEWO_WHG.GEO_ID IS 'GeoID, die die Lokation darstellt';

CREATE INDEX IX_FK_GEWO_2_GEO ON T_GEWO_WHG (GEO_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_GEWO_WHG ADD CONSTRAINT FK_GEWO_2_GEO
  FOREIGN KEY (GEO_ID) REFERENCES T_GEO_ID_CACHE (ID);
