-- Address ID und Endstelle ID indizieren
CREATE INDEX IX_VENTO_MIG_ADR2GEOID_ESID ON VENTO_MIG_ADDRESS2GEOID (ENDSTELLE_ID) NOLOGGING PARALLEL 4;
CREATE INDEX IX_VENTO_MIG_ADR2GEOID_ADRID ON VENTO_MIG_ADDRESS2GEOID (ADDRESS_ID) NOLOGGING PARALLEL 4;