-- Erstellt Views fuer den Accounting bzw. CDR-Vergleich zwischen Taifun und Navision.

CREATE OR REPLACE VIEW NAVI_CHK_ACCOUNTING AS
SELECT C.COST,
       NC.COST AS NAVI_COST,
       NC.A_NUMBER AS NAVI_A_NUMBER,
       NC.AREA_CODE AS NAVI_AREA_CODE,
       NC.B_NUMBER AS NAVI_B_NUMBER,
       NC.CALL_LENGH AS NAVI_CALL_LENGH,
       NC.CDR_FILE AS  NAVI_CDR_FILE,
       NC.CONN_ID AS NAVI_CONN_ID,
       NC.COUNTRY_AREA_CODE AS NAVI_COUNTRY_AREA_CODE,
       NC.END_DATETIME AS NAVI_END_DATETIME,
       NC.ID AS NAVI_ID,
       NC.NAVI_CONTRACT_NO AS NAVI_CONTRACT_NO,
       NC.NAVI_CUST_NO AS NAVI_CUST_NO,
       NC.START_DATETIME AS NAVI_START_DATETIME,
       NC.TARIF_AREA AS NAVI_TARIF_AREA,
       NC.TARIF_MODEL AS NAVI_TARIF_MODEL,
       NC.TAX_TIME AS NAVI_TAX_TIME,
       C.A_NUMBER,
       C.A2_NUMBER,
       C.AUFTRAG_NO,
       C.B_NUMBER,
       C.C_NUMBER,
       C.CALL_DATETIME,
       C.CALL_LENGTH,
       C.CAUSE_VALUE,
       C.CDR_FILE_NO,
       C.CENTREX,
       C.CONN_ID,
       C.CUST_NO,
       C.DURATION_ANSWER,
       C.DURATION_DIAL,
       C.FILE_OFFSET,
       C.FIRST_RECORD,
       C.IND_INTERCONN,
       C.IND_SFC,
       C.LAST_RECORD,
       C.NO_ANSWER,
       C.NODE_CONN_NO,
       C.ORIG_B_NUMBER,
       C.TARIFF_TRANSIT,
       C.TAX_TIME,
       C.TOT_CALL_LENGTH,
       C.PRICE_NO,
       P.SHORT_NAME AS TARIF_SHORT_NAME,
       P.DESCRIPTION AS TARIF_DESCRIPTION
  FROM    NAVI_CALL NC
       JOIN A_CDR_OK_${billing.period}_0 C  ON NC.CONN_ID = C.CONN_ID AND C.IND_INTERCONN is null AND C.ORIG_B_NUMBER = NC.B_NUMBER AND C.SERVICE_INFO <> 3
       JOIN A_CDR_FILE F ON C.CDR_FILE_NO = F.CDR_FILE_NO AND F.FILE_NAME Like 'NEF%'
       JOIN T_PRICE P ON C.PRICE_NO = P.PRICE_NO
/

-- SERVICE INFO = 3 := Datengespräche (werden in Navision faelschlicherweise nicht abgerechnet)
-- IND_INTERCONN != null := Interconnect-Verbindungen


CREATE OR REPLACE VIEW NAVI_CHK_ACCOUNTING_OK AS
SELECT * FROM NAVI_CHK_ACCOUNTING
WHERE COST = NAVI_COST
/

CREATE OR REPLACE VIEW NAVI_CHK_ACCOUNTING_DIFF AS
SELECT * FROM NAVI_CHK_ACCOUNTING
WHERE COST <> NAVI_COST
/

CREATE OR REPLACE VIEW NAVI_CHK_ACCOUNTING_WAIT AS
SELECT w.* FROM A_CDR_WAIT w
JOIN AUFTRAG a on w.AUFTRAG_NO = a.AUFTRAG_NO
AND a.userw='NAVI_MIG'
/

CREATE OR REPLACE VIEW NAVI_CHK_ACCOUNTING_DELETE AS
select d.* from A_CDR_DELETE d
JOIN AUFTRAG a on d.AUFTRAG_NO = a.AUFTRAG_NO
AND a.userw='NAVI_MIG'
/

CREATE OR REPLACE VIEW NAVI_CHK_ACCOUNTING_FILTERED AS
select c.* from A_CDR_FILTERED_${billing.period} c
JOIN AUFTRAG a on c.AUFTRAG_NO = a.AUFTRAG_NO
AND a.userw='NAVI_MIG'
/




