-- create database links
BEGIN
    EXECUTE IMMEDIATE ('DROP DATABASE LINK BSICRM.MNET.DE');
    EXCEPTION
     WHEN OTHERS THEN
        NULL;
END;
/
CREATE DATABASE LINK BSICRM.MNET.DE CONNECT TO ${db.ors.user.schema}
    IDENTIFIED BY "${db.ors.user.password}" USING '${db.bsi.tns.name}'
/
BEGIN
    EXECUTE IMMEDIATE ('DROP DATABASE LINK HURRICAN.MNET.DE');
    EXCEPTION
     WHEN OTHERS THEN
        NULL;
END;
/
CREATE   DATABASE LINK HURRICAN.MNET.DE CONNECT TO ${db.hurrican.user.schema}
    IDENTIFIED BY "${db.hurrican.user.password}" USING '${db.hurrican.tns.name}'
/
BEGIN
    EXECUTE IMMEDIATE ('DROP DATABASE LINK KUPVIS.MNET.DE');
    EXCEPTION
     WHEN OTHERS THEN
        NULL;
END;
/
CREATE  DATABASE LINK KUPVIS.MNET.DE CONNECT TO ${db.kup.user.schema}
    IDENTIFIED BY "${db.kup.user.password}" USING '${db.kup.tns.name}'
/

--------------------------------------------------------------------------------
-- LKe 8.9.2010 lesender readonly Zugriff auf das Nuernberger ICCS
--------------------------------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE ('DROP DATABASE LINK ICCS.MNET.DE');
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
CREATE   DATABASE LINK ICCS.MNET.DE CONNECT TO ICCS_RO
 IDENTIFIED BY iccs$ro$
 USING 'ICPROD01.m-net.de'
/

--------------------------------------------------------------------------------
-- end: LKe 8.9.2010
--------------------------------------------------------------------------------

-- create a few synonyms for BSI that would exist as views in a seperate schema if we would bother to create a BSICRM user for every dev schema
CREATE OR REPLACE  SYNONYM BSICRM_ALL_CONTR_T2CRM FOR BSI_ALL_CONTR_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_CONTRACTS_T2CRM FOR BSI_CONTRACTS_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_CONTR_2CANCEL_T2CRM FOR BSI_CONTR_2CANCEL_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_CONTR_ACCT_T2CRM FOR BSI_CONTR_ACCT_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_CONTR_DETAILS_T2CRM FOR BSI_CONTR_DETAILS_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_CUST_ACCT_T2CRM FOR BSI_CUST_ACCT_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_CUST_BILLSPEC_T2CRM FOR BSI_CUST_BILLSPEC_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_DETEME_T2CRM FOR BSI_DETEME_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_DN_T2CRM FOR BSI_DN_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_FIRMEN_CRM2T FOR BSI_FIRMEN_CRM2TAIFUN
/
CREATE OR REPLACE  SYNONYM BSICRM_FIRMEN_T2CRM FOR BSI_FIRMEN_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_GEO_BUILDING FOR BSI_GEO_BUILDING_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_GEO_CITY FOR BSI_GEO_CITY_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_GEO_COUNTRY FOR BSI_GEO_COUNTRY_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_GEO_STREET FOR BSI_GEO_STREET_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_JOURNAL_T2CRM FOR BSI_JOURNAL_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_PERSON_CRM2T FOR BSI_PERSON_CRM2TAIFUN
/
CREATE OR REPLACE  SYNONYM BSICRM_PERSON_T2CRM FOR BSI_PERSON_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSI_BARRING_T2CRM FOR BSI_BARRING_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSI_DELIVERY_PARCEL_T2CRM FOR BSI_DELIVERY_PARCEL_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSI_DEVICE_T2CRM FOR BSI_DEVICE_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSI_SAP_T2CRM FOR BSI_SAP_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSI_SERVICE_MOBILE_T2CRM FOR BSI_SERVICE_MOBILE_TAIFUN2CRM
/

CREATE OR REPLACE  SYNONYM BSICRM_BARRING_T2CRM FOR BSI_BARRING_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_DEL_ASSIGNM_T2CRM FOR BSI_DELIVERY_ASSIGNMENT_T2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_DEL_PARCEL_T2CRM FOR BSI_DELIVERY_PARCEL_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_DEVICE_T2CRM FOR BSI_DEVICE_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_PERS2SERV_T2CRM FOR BSI_PERS2SERV_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_SAP_T2CRM FOR BSI_SAP_TAIFUN2CRM
/
CREATE OR REPLACE  SYNONYM BSICRM_SERVICE_MOB_T2CRM FOR BSI_SERVICE_MOBILE_TAIFUN2CRM
/

CREATE OR REPLACE FORCE VIEW TRF_JOURNAL_AUFTRAG
(
   VISIT_PROTOCOL_NR,
   VISIT_NR,
   REASON_UID,
   EVT_START,
   USER_NAME,
   AUFTRAG__NO,
   TICKET_NR,
   NOTES,
   INFOMATERIALVERSAND,
   TYPE_UID
)
AS
   SELECT   P.*, C.TYPE_UID
     FROM      TRF_PROTOCOL_TAIFUN@BSICRM.MNET.DE P
            LEFT OUTER JOIN
               TRF_CONTACT_TAIFUN@BSICRM.MNET.DE C
            ON P.VISIT_NR = C.VISIT_NR
/
