-- @operation grant read, write on directories to database owner
GRANT READ,WRITE ON DIRECTORY BULKACCOUNT_${db.user.postfix} TO ${db.user.schema}
/

DROP VIEW ${db.user.schema}.BSI_FIRMEN_CRM2TAIFUN
/
CREATE OR REPLACE FORCE VIEW ${db.user.schema}.BSI_FIRMEN_CRM2TAIFUN AS SELECT * FROM TRF_INTERESSENT_COMP_OUT@BSICRM.MNET.DE
/
DROP SYNONYM NAVIMIG_${db.user.postfix}.BSI_FIRMEN_CRM2TAIFUN
/
CREATE OR REPLACE SYNONYM NAVIMIG_${db.user.postfix}.BSI_FIRMEN_CRM2TAIFUN FOR ${db.user.schema}.BSI_FIRMEN_CRM2TAIFUN
/
DROP SYNONYM ${db.user.schema}.BSICRM_FIRMEN_CRM2T
/
CREATE OR REPLACE SYNONYM ${db.user.schema}.BSICRM_FIRMEN_CRM2T FOR ${db.user.schema}.BSI_FIRMEN_CRM2TAIFUN
/
GRANT SELECT ON ${db.user.schema}.BSI_FIRMEN_CRM2TAIFUN TO BSICRM
/
GRANT SELECT ON ${db.user.schema}.BSI_FIRMEN_CRM2TAIFUN TO NAVIMIG_${db.user.postfix}
/
DROP VIEW ${db.user.schema}.BSI_PERSON_CRM2TAIFUN
/
CREATE OR REPLACE FORCE VIEW ${db.user.schema}.BSI_PERSON_CRM2TAIFUN AS SELECT * FROM TRF_INTERESSENT_PERS_OUT@BSICRM.MNET.DE
/
DROP SYNONYM NAVIMIG_${db.user.postfix}.BSI_PERSON_CRM2TAIFUN
/
CREATE OR REPLACE SYNONYM NAVIMIG_${db.user.postfix}.BSI_PERSON_CRM2TAIFUN FOR ${db.user.schema}.BSI_PERSON_CRM2TAIFUN
/
DROP SYNONYM ${db.user.schema}.BSICRM_PERSON_CRM2T
/
CREATE OR REPLACE SYNONYM ${db.user.schema}.BSICRM_PERSON_CRM2T FOR ${db.user.schema}.BSI_PERSON_CRM2TAIFUN
/
GRANT SELECT ON ${db.user.schema}.BSI_PERSON_CRM2TAIFUN TO BSICRM
/
GRANT SELECT ON ${db.user.schema}.BSI_PERSON_CRM2TAIFUN TO NAVIMIG_${db.user.postfix}
/

DROP VIEW ${db.user.schema}.CUSTOMER_AND_PROSPECT
/
CREATE OR REPLACE VIEW ${db.user.schema}.CUSTOMER_AND_PROSPECT
(
	SOURCE_TABLE,
	TAIFUN_CUST_NO,
	BSI_COMPANY_NR,
	ACTIVE,
	NAME,
	FIRSTNAME,
	TITLE,
	USER_USER_NR,
	FORMAT,
	BIRTHDAY,
	DEPARTMENT,
	LANGUAGE,
	ADDRESS_TYPE,
	COUNTRY_ISO_CODE,
	ADDRESS_CITY_ID,
	CITY,
	ZIP_CODE,
	ADDRESS_STREET_SECTION_ID,
	STREET,
	ADDRESS_GEO_ID,
	HOUSE_NUM,
	HOUSE_NUM_ADD,
	ADDRESS_VALID_FROM,
	ADDRESS_NAME_ADD,
	ADDRESS_PO_BOX,
	ADDRESS_PHONE_CENTRAL,
	ADDRESS_FAX,
	ADDRESS_MOBILE,
	ADDRESS_VOIP,
	ADDRESS_EMAIL,
	ADDRESS_PHONE,
	CSR_NO,
	SECTOR_UID,
	REGION_UID,
	RATING_UID,
	ADDRESS_WWW
) AS
-- CUSTOMER_AND_PROSPECT: Unified search view
SELECT
	'BSI_Person'			as	SOURCE_TABLE,
	COMPANY_NO				as	TAIFUN_CUST_NO,
	RTRIM(COMPANY_NR)		as	BSI_COMPANY_NR,
	ACTIVE					as	IS_ACTIVE,
	RTRIM(PERSON_LAST_NAME)	as	NAME,
	RTRIM(PERSON_FIRST_NAME)	as	FIRSTNAME,
	RTRIM(PERSON_TITLE)		as	TITLE,
	USER_USER_NR			as	USER_USER_NR,
	RTRIM(PERSON_SALUTATION_UID)	as	FORMAT,
	PERSON_EVT_BIRTH		as	BIRTHDAY,
	RTRIM(USER_ORGANISATION_UID)	as	DEPARTMENT,
	RTRIM(PERSON_LANGUAGE_UID)		as	LANGUAGE,
	TO_NUMBER(ADDRESS_TYPE_UID)		as	ADDRESS_TYPE,
	COUNTRY_ISO_CODE		as	COUNTRY_ISO_CODE,
	CITY_ID					as	ADDRESS_CITY_ID,
	CITY_NAME				as	CITY,
	ZIP_CODE				as	ZIP_CODE,
	STREET_SECTION_ID		as	ADDRESS_STREET_SECTION_ID,
	STREET_NAME				as	STREET,
	GEO_ID					as	ADDRESS_GEO_ID,
	HOUSE_NUM				as	HOUSE_NUM,
	HOUSE_NUM_ADD			as	HOUSE_NUM_ADD,
	ADDRESS_VALID_FROM		as	ADDRESS_VALID_FROM,
	RTRIM(ADDRESS_NAME_ADD)	as	ADDRESS_NAME_ADD,
	RTRIM(ADDRESS_PO_BOX)	as	ADDRESS_PO_BOX,
	RTRIM(ADDRESS_PHONE_CENTRAL)	as	ADDRESS_PHONE_CENTRAL,
	RTRIM(ADDRESS_FAX)		as	ADDRESS_FAX,
	RTRIM(ADDRESS_MOBILE)	as	ADDRESS_MOBILE,
	RTRIM(ADDRESS_VOIP)		as	ADDRESS_VOIP,
	RTRIM(ADDRESS_EMAIL)	as	ADDRESS_EMAIL,
	RTRIM(ADDRESS_PHONE)	as	ADDRESS_PHONE,
	PERSON_ADVISOR_NO		as	CSR_NO,
	null					as	SECTOR_UID,
	null					as	REGION_UID, 
	null					as	RATING_UID,
	null					as	ADDRESS_WWW 
FROM
    TRF_INTERESSENT_PERS_OUT@BSICRM.MNET.DE
WHERE
	ADDRESS_TYPE_UID is not null
UNION ALL
SELECT
	'BSI_Company'			as	SOURCE_TABLE,
	COMPANY_NO				as	TAIFUN_CUST_NO,
	RTRIM(COMPANY_NR)		as	BSI_COMPANY_NR,
	NULL					as	IS_ACTIVE,
	RTRIM(NAME)				as	NAME,
	NULL					as	FIRSTNAME,
	NULL					as	TITLE,
	NULL					as	USER_USER_NR,
	NULL					as	FORMAT,
	NULL					as	BIRTHDAY,
	NULL					as	DEPARTMENT,
	RTRIM(ADDRESS_LANGUAGE_UID)	as	LANGUAGE,
	ADDRESS_TYPE_UID		as	ADDRESS_TYPE,
	COUNTRY_ISO_CODE		as	COUNTRY_ISO_CODE,
	CITY_ID					as	ADDRESS_CITY_ID,
	CITY_NAME				as	CITY,
	ZIP_CODE				as	ZIP_CODE,
	STREET_SECTION_ID		as	ADDRESS_STREET_SECTION_ID,
	STREET_NAME				as	STREET,
	GEO_ID					as	ADDRESS_GEO_ID,
	HOUSE_NUM				as	HOUSE_NUM,
	HOUSE_NUM_ADD			as	HOUSE_NUM_ADD,
	ADDRESS_VALID_FROM		as	ADDRESS_VALID_FROM,
	RTRIM(ADDRESS_NAME_ADD)	as	ADDRESS_NAME_ADD,
	RTRIM(ADDRESS_PO_BOX)	as	ADDRESS_PO_BOX,
	NULL					as	ADDRESS_PHONE_CENTRAL,
	RTRIM(ADDRESS_FAX)		as	ADDRESS_FAX,
	NULL					as	ADDRESS_MOBILE,
	NULL					as	ADDRESS_VOIP,
	RTRIM(ADDRESS_EMAIL)	as	ADDRESS_EMAIL,
	RTRIM(ADDRESS_PHONE)	as	ADDRESS_PHONE,
	COMPANY_PERSON_UID		as	CSR_NO,
	SECTOR_UID				as	SECTOR_UID,
	REGION_UID				as	REGION_UID, 
	RTRIM(RATING_UID)		as	RATING_UID,
	RTRIM(ADDRESS_WWW)		as	ADDRESS_WWW 
FROM
    TRF_INTERESSENT_COMP_OUT@BSICRM.MNET.DE
WHERE
	ADDRESS_TYPE_UID is not null
UNION ALL
-- From CUSTOMER with ADDRESS
-- ADDRESS_TYPE 1000 is used as a catch all "Taifun address type"
SELECT
	'Taifun_Customer'		as	SOURCE_TABLE,
	k.CUST_NO				as	TAIFUN_CUST_NO,
	NULL					as	BSI_COMPANY_NR,
	k.IS_ACTIVE				as	IS_ACTIVE,
	NVL(a.NAME, k.NAME)		as	NAME,
	NVL(a.FIRSTNAME, k.FIRSTNAME)	as	FIRSTNAME,
	a.TITLE					as	TITLE,
	NULL					as	USER_USER_NR,
	a.FORMAT				as	FORMAT,
	k.BIRTHDAY				as	BIRTHDAY,
	a.DEPARTMENT			as	DEPARTMENT,
	a.LANGUAGE				as	LANGUAGE,
	1000					as	ADDRESS_TYPE,
	a.GEO_COUNTRY_ID		as	COUNTRY_ISO_CODE,
	a.VENTO_CITY_ID			as	ADDRESS_CITY_ID,
	CITY					as	CITY,
	ZIP_CODE				as	ZIP_CODE,
	a.VENTO_STREET_SECTION_ID as ADDRESS_STREET_SECTION_ID,
	STREET					as	STREET,
	a.VENTO_GEO_ID			as	ADDRESS_GEO_ID,
	HOUSE_NUM				as	HOUSE_NUM,
	HOUSE_NUM_ADD			as	HOUSE_NUM_ADD,
	a.VALID_FROM			as	ADDRESS_VALID_FROM,
	a.NAME_ADD				as	ADDRESS_NAME_ADD,
	a.PO_BOX				as	ADDRESS_PO_BOX,
	k.PHONE_CENTRAL			as	ADDRESS_PHONE_CENTRAL,
	k.FAX					as	ADDRESS_FAX,
	k.MOBILE				as	ADDRESS_MOBILE,
	k.VOIP					as	ADDRESS_VOIP,
	k.EMAIL					as	ADDRESS_EMAIL,
	k.PHONE_BUSINESS		as	ADDRESS_PHONE,
	k.CSR_NO				as	CSR_NO,
	k.SECTOR_NO				as	SECTOR_UID,
	k.AREA_NO				as	REGION_UID, 
	k.CREDIT_RATING_ID		as	RATING_UID,
	k.WWW					as	ADDRESS_WWW 
FROM
	CUSTOMER k, ADDRESS a
WHERE
	a.CUST_NO=k.CUST_NO
/
DROP SYNONYM NAVIMIG_${db.user.postfix}.CUSTOMER_AND_PROSPECT
/
CREATE OR REPLACE SYNONYM NAVIMIG_${db.user.postfix}.CUSTOMER_AND_PROSPECT FOR ${db.user.schema}.CUSTOMER_AND_PROSPECT
/
GRANT SELECT ON ${db.user.schema}.CUSTOMER_AND_PROSPECT TO NAVIMIG_${db.user.postfix}
/
