-- GRANTS fuer in Taifun anlegen

--
-- GRANTs fuer die DB-Rolle 'R_MNET_READ_ONLY' fuer die Taifun-DB
--
GRANT SELECT ON "ARCH_PRINT_SET" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "ARCH_PRINT_FILE" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "ADDRESS" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "ADDRESS_FORMAT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AREA" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "ACCOUNT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAG" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAG__BN_FC" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAG__CONNECT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAG__KOMBI" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAG__SCV" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAGPOS" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAGTEXT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "AUFTRAGSTATUS" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "BLZ" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "DN" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "DN_TNB" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "CUST_ACCOUNT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "CUSTOMER" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "CUSTOMER_ALIAS" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "LEISTUNG" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "OE" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "BILL_SPEC" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "CONTACT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "DN_BLOCK" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "DN_TNB" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "LEISTUNG_LANG" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "OE_LANG" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "PERSON" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "PERSON2CUSTOMER" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "P2C_TYPE" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "PRODUCT_TYPE" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "SERVICE_VALUE_PRICE" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "SERVICE_BLOCK_PRICE" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "WEBGATE_PW" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON "BILLINGSEGMENT" TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON PRODUCT_TYPE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON STREET_SECTION TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON SERVICE_ROOM TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON GEO_CITY TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON GEO_STREET TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON CHANGE_BILL_SPEC TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON UTI_MODIFICATION_LOG TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON VAT_CODE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON VAT_RATE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON BIE_RUN TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON BIE_CYCLE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON T_PRICE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON T_TYPE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON T_PRICE_TYPE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON DEVICE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON DEVICE2SERVICE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON DEVICE2SERVICE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON DEVICETYPE TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON MACADDR TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON TIME_SLOT TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON TIME_SLOT_CONFIG TO "R_MNET_READ_ONLY"
/

GRANT SELECT ON BLOCKADE to "R_MNET_READ_ONLY"
/

GRANT SELECT ON DEVICE__FRITZBOX TO "R_MNET_READ_ONLY"
/


--
-- GRANTs fuer die DB-Rolle 'R_BILLING_READER' fuer die Taifun-DB.
GRANT select, insert, update ON ACCOUNT TO "R_BILLING_READER"
/

GRANT SELECT ON ADDRESS TO "BSICRM"
/

GRANT SELECT, INSERT, UPDATE ON ADDRESS TO "VENTO"
/
