-- Abfrage des ASB pro DSLAM / EWSD / MDU
-- (wird aus dem Service-Portal aufgerufen)

CREATE OR REPLACE VIEW V_ASB_PRO_DSLAM_EWSD_MDU as
 select distinct HVT_GRUPPE.ONKZ,
	STANDORT.ASB,
	STANDORT.HVT_ID_STANDORT,
	RACK.GERAETEBEZ,
	RACK.MANAGEMENTBEZ,
	RACK.RACK_TYP,
	DLU.DLU_NUMBER,
	 SW.NAME AS SWITCH
 from T_HW_RACK  RACK
    left join T_HVT_STandort STANDORT on (RACK.HVT_ID_STANDORT = STANDORT.HVT_ID_STANDORT)
    left join T_HVT_GRUPPE HVT_GRUPPE on (HVT_GRUPPE.HVT_GRUPPE_ID = STANDORT.HVT_GRUPPE_ID)
    left join T_HW_RACK_DLU DLU on (DLU.RACK_ID = RACK.ID)
    left join T_HW_SWITCH SW on (SW.ID = DLU.SWITCH);


GRANT SELECT ON V_ASB_PRO_DSLAM_EWSD_MDU TO HURRICAN_TECH_MUC;