CREATE OR REPLACE VIEW V_AUFTRAG_2_VLAN AS
SELECT
    AD.PRODAK_ORDER__NO,
    TDN.TDN AS LINE_ID,
    VLAN.CVLAN_TYP,
    CASE when VLAN.CVLAN_TYP = 'MC' THEN 'MULTICAST' ELSE 'UNICAST' END AS TYP,
    VLAN.CVLAN,
    VLAN.SVLAN_EKP,
    VLAN.SVLAN_MDU,
    VLAN.SVLAN_OLT,
    VLAN.GUELTIG_VON AS VLAN_GUELTIG_VON,
    VLAN.GUELTIG_BIS AS VLAN_GUELTIG_BIS,
    AD.INBETRIEBNAHME,
    AD.KUENDIGUNG,
    RACKOLT.GERAETEBEZ,
    OLT.OLT_NR,
    OLT.VLAN_AKTIV_AB
FROM T_AUFTRAG_DATEN ad
    JOIN T_AUFTRAG_TECHNIK at ON (AD.AUFTRAG_ID = AT.AUFTRAG_ID)
    JOIN T_TDN tdn ON (AT.TDN_ID = TDN.ID)
    JOIN T_ENDSTELLE es ON (AT.AT_2_ES_ID = ES.ES_GRUPPE)
    JOIN T_RANGIERUNG rang ON (RANG.RANGIER_ID = ES.RANGIER_ID)
    JOIN T_EQ_VLAN vlan ON (VLAN.EQUIPMENT_ID = RANG.EQ_IN_ID AND VLAN.GUELTIG_BIS > NVL(AD.INBETRIEBNAHME, AD.VORGABE_SCV) AND VLAN.GUELTIG_VON < NVL(AD.KUENDIGUNG, to_date('01.01.2200', 'dd.mm.yyyy')))
    JOIN T_EQUIPMENT eq ON (EQ.EQ_ID = RANG.EQ_IN_ID)
    JOIN T_HW_BAUGRUPPE baugr ON (BAUGR.ID = EQ.HW_BAUGRUPPEN_ID)
    JOIN T_HW_RACK rack ON (RACK.ID = BAUGR.RACK_ID)
    LEFT JOIN T_HW_RACK_MDU mdu ON (MDU.RACK_ID = rack.ID)
    LEFT JOIN T_HW_RACK_ONT ont ON (ONT.RACK_ID = rack.ID)
    JOIN T_HW_RACK_OLT olt ON ((MDU.OLT_RACK_ID = OLT.RACK_ID) or (ONT.OLT_RACK_ID = OLT.RACK_ID))
    JOIN T_HW_RACK rackOlt ON (OLT.RACK_ID = RACKOLT.ID)
WHERE AD.GUELTIG_BIS = to_date('01.01.2200', 'dd.mm.yyyy')
    AND (AD.STATUS_ID >= 4000 AND AD.STATUS_ID < 9800)
    AND AT.GUELTIG_BIS = to_date('01.01.2200', 'dd.mm.yyyy')
    AND RANG.GUELTIG_BIS = to_date('01.01.2200', 'dd.mm.yyyy');

GRANT SELECT ON V_AUFTRAG_2_VLAN TO HURRICAN_TECH_MUC;

