
alter table T_RSM_RANG_COUNT add PORT_REACH NUMBER(10);

create table T_RSM_PORT_USAGE (
  ID NUMBER(10) NOT NULL,
  YEAR NUMBER(10) NOT NULL,
  MONTH NUMBER(10) NOT NULL,
  HVT_ID_STANDORT NUMBER(10) NOT NULL,
  PHYSIKTYP NUMBER(10) NOT NULL,
  PHYSIKTYP_ADDITIONAL NUMBER(10),
  PORTS_USED NUMBER(10),
  PORTS_CANCELLED NUMBER(10),
  DIFF_COUNT NUMBER(10) NOT NULL
);
comment on table T_RSM_PORT_USAGE is 'Tabelle zur Protokollierung des Port-Verbrauchs innerhalb von x Monaten';

create SEQUENCE S_T_RSM_PORT_USAGE_0 start with 1;
grant select on S_T_RSM_PORT_USAGE_0 to public;

ALTER TABLE T_RSM_PORT_USAGE ADD CONSTRAINT PK_T_RSM_PORT_USAGE PRIMARY KEY (ID);

CREATE INDEX IX_FK_RSMPORTUSAGE2HVT ON T_RSM_PORT_USAGE (HVT_ID_STANDORT) TABLESPACE "I_HURRICAN";
ALTER TABLE T_RSM_PORT_USAGE ADD CONSTRAINT FK_RSMPORTUSAGE2HVT
  FOREIGN KEY (HVT_ID_STANDORT) REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT);

ALTER TABLE T_RSM_PORT_USAGE ADD (
  CONSTRAINT FK_RSMPORTUSAGE_2_PT1
 FOREIGN KEY (PHYSIKTYP)
 REFERENCES T_PHYSIKTYP (ID),
  CONSTRAINT FK_RSMPORTUSAGE_2_PT2
 FOREIGN KEY (PHYSIKTYP_ADDITIONAL)
 REFERENCES T_PHYSIKTYP (ID));
GRANT DELETE, INSERT, SELECT, UPDATE ON T_RSM_PORT_USAGE TO R_HURRICAN_USER;

Insert into T_REFERENCE
   (ID, TYPE, STR_VALUE, INT_VALUE, FLOAT_VALUE,
    UNIT_ID, GUI_VISIBLE, ORDER_NO, DESCRIPTION, VERSION)
 Values
   (352, 'RS_MONITOR_TYPE', 'Port-Reichweite', NULL, NULL,
    NULL, '1', 10, 'RessourcenMonitor-Typ fuer die Ermittlung der voraussichtlichen Reichweite von Ports.', 0);

