apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE-APP-deployment
  namespace: NAMESPACE
spec:
  template:
    spec:
      containers:
        - name: SERVICE-APP
          ports:
            - $patch: replace
            - containerPort: 80
              hostPort: 8081
      imagePullSecrets:
        - name: docker-regcred
