insert into T_PRODUKT (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, LEITUNGSART, AKTIONS_ID, BRAUCHT_DN, DN_MOEGLICH, MAX_DN_COUNT, DN_BLOCK, DN_TYP, BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_VORS, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT, EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, BRAUCHT_VPI_VCI, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER)
values (
350, 									-- PROD_ID
1, 										-- PRODUKTGRUPPE_ID
null, 									-- PRODUKT_NR
'M-Net Vor-Ort ANALOG', 				-- ANSCHLUSSART
'M-Net Vor-Ort ANALOG', 				-- PROD_NAME_PATTERN
null,									-- LEITUNGSART
1,										-- AKTIONS_ID
1,										-- BRAUCHT_DN
0,										-- DN_MOEGLICH
1,										-- MAX_DN_COUNT
0,										-- DN_BLOCK
60, 									-- DN_TYP
0,										-- BRAUCHT_DN4ACCOUNT
to_date('01.12.2009', 'dd.mm.yyyy'),	-- GUELTIG_VON
to_date('01.01.2200', 'dd.mm.yyyy'),	-- GUELTIG_BIS
0,										-- AUFTRAGSERSTELLUNG
'DV', 									-- LTGNR_VORS
1,										-- LTGNR_ANLEGEN
0,										-- BRAUCHT_BUENDEL
1,										-- ELVERLAUF
0,										-- ABRECHNUNG_IN_HURRICAN
0,										-- ENDSTELLEN_TYP
null,									-- BESCHREIBUNG
null,									-- ACCOUNT_VORS
null,									-- LI_NR
0,										-- VPN_PHYSIK
0,										-- PROJEKTIERUNG
0,										-- IS_PARENT
0,										-- CHECK_CHILD
0,										-- IS_COMBI_PRODUKT
1,										-- AUTO_PRODUCT_CHANGE
1,										-- EXPORT_KDP_M
1,										-- CREATE_KDP_ACCOUNT_REPORT
null,									-- EXPORT_AK_PRODUKTE
4,										-- VERTEILUNG_DURCH
0,										-- BA_RUECKLAEUFER
0,										-- BRAUCHT_VPI_VCI
null,									-- PROJEKTIERUNG_CHAIN_ID
16,										-- VERLAUF_CHAIN_ID
13,										-- VERLAUF_CANCEL_CHAIN_ID
0,										-- BA_CHANGE_REALDATE
0,										-- CREATE_AP_ADDRESS
0,										-- ASSIGN_IAD
0, 										-- CPS_PROVISIONING
null,									-- CPS_PROD_NAME
null,									-- STATUSMELDUNGEN
0, 										-- CPS_AUTO_CREATION
null,						      		-- CPS_ACCOUNT_TYPE
0, 										-- CPS_DSL_PRODUCT
'W',									-- TDN_KIND_OF_USE_PRODUCT
'A',									-- TDN_KIND_OF_USE_TYPE
null									-- TDN_USE_FROM_MASTER
);


insert into T_PRODUKT (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, LEITUNGSART, AKTIONS_ID, BRAUCHT_DN, DN_MOEGLICH, MAX_DN_COUNT, DN_BLOCK, DN_TYP, BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_VORS, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT, EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, BRAUCHT_VPI_VCI, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER)
values (
351, 									-- PROD_ID
1, 										-- PRODUKTGRUPPE_ID
null, 									-- PRODUKT_NR
'M-Net Vor-Ort ISDN', 					-- ANSCHLUSSART
'M-Net Vor-Ort ISDN',	 				-- PROD_NAME_PATTERN
null,									-- LEITUNGSART
1,										-- AKTIONS_ID
1,										-- BRAUCHT_DN
0,										-- DN_MOEGLICH
10,										-- MAX_DN_COUNT
0,										-- DN_BLOCK
60, 									-- DN_TYP
0,										-- BRAUCHT_DN4ACCOUNT
to_date('01.12.2009', 'dd.mm.yyyy'),	-- GUELTIG_VON
to_date('01.01.2200', 'dd.mm.yyyy'),	-- GUELTIG_BIS
0,										-- AUFTRAGSERSTELLUNG
'DV', 									-- LTGNR_VORS
1,										-- LTGNR_ANLEGEN
0,										-- BRAUCHT_BUENDEL
1,										-- ELVERLAUF
0,										-- ABRECHNUNG_IN_HURRICAN
0,										-- ENDSTELLEN_TYP
null,									-- BESCHREIBUNG
null,									-- ACCOUNT_VORS
null,									-- LI_NR
0,										-- VPN_PHYSIK
0,										-- PROJEKTIERUNG
0,										-- IS_PARENT
0,										-- CHECK_CHILD
0,										-- IS_COMBI_PRODUKT
1,										-- AUTO_PRODUCT_CHANGE
1,										-- EXPORT_KDP_M
1,										-- CREATE_KDP_ACCOUNT_REPORT
null,									-- EXPORT_AK_PRODUKTE
4,										-- VERTEILUNG_DURCH
0,										-- BA_RUECKLAEUFER
0,										-- BRAUCHT_VPI_VCI
null,									-- PROJEKTIERUNG_CHAIN_ID
16,										-- VERLAUF_CHAIN_ID
13,										-- VERLAUF_CANCEL_CHAIN_ID
0,										-- BA_CHANGE_REALDATE
0,										-- CREATE_AP_ADDRESS
0,										-- ASSIGN_IAD
0, 										-- CPS_PROVISIONING
null,									-- CPS_PROD_NAME
null,									-- STATUSMELDUNGEN
0, 										-- CPS_AUTO_CREATION
null,						      		-- CPS_ACCOUNT_TYPE
0, 										-- CPS_DSL_PRODUCT
'W',									-- TDN_KIND_OF_USE_PRODUCT
'A',									-- TDN_KIND_OF_USE_TYPE
null									-- TDN_USE_FROM_MASTER
);

insert into T_PRODUKT (PROD_ID, PRODUKTGRUPPE_ID, PRODUKT_NR, ANSCHLUSSART, PROD_NAME_PATTERN, LEITUNGSART, AKTIONS_ID, BRAUCHT_DN, DN_MOEGLICH, MAX_DN_COUNT, DN_BLOCK, DN_TYP, BRAUCHT_DN4ACCOUNT, GUELTIG_VON, GUELTIG_BIS, AUFTRAGSERSTELLUNG, LTGNR_VORS, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ABRECHNUNG_IN_HURRICAN, ENDSTELLEN_TYP, BESCHREIBUNG, ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT, CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT, EXPORT_AK_PRODUKTE, VERTEILUNG_DURCH, BA_RUECKLAEUFER, BRAUCHT_VPI_VCI, PROJEKTIERUNG_CHAIN_ID, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE, CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, STATUSMELDUNGEN, CPS_AUTO_CREATION, CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER)
values (
352, 									-- PROD_ID
1, 										-- PRODUKTGRUPPE_ID
null, 									-- PRODUKT_NR
'M-Net Vor-Ort PMX', 					-- ANSCHLUSSART
'M-Net Vor-Ort PMX',	 				-- PROD_NAME_PATTERN
null,									-- LEITUNGSART
1,										-- AKTIONS_ID
1,										-- BRAUCHT_DN
0,										-- DN_MOEGLICH
10,										-- MAX_DN_COUNT
1,										-- DN_BLOCK
60, 									-- DN_TYP
0,										-- BRAUCHT_DN4ACCOUNT
to_date('01.12.2009', 'dd.mm.yyyy'),	-- GUELTIG_VON
to_date('01.01.2200', 'dd.mm.yyyy'),	-- GUELTIG_BIS
0,										-- AUFTRAGSERSTELLUNG
'DV', 									-- LTGNR_VORS
1,										-- LTGNR_ANLEGEN
0,										-- BRAUCHT_BUENDEL
1,										-- ELVERLAUF
0,										-- ABRECHNUNG_IN_HURRICAN
0,										-- ENDSTELLEN_TYP
null,									-- BESCHREIBUNG
null,									-- ACCOUNT_VORS
null,									-- LI_NR
0,										-- VPN_PHYSIK
0,										-- PROJEKTIERUNG
0,										-- IS_PARENT
0,										-- CHECK_CHILD
0,										-- IS_COMBI_PRODUKT
1,										-- AUTO_PRODUCT_CHANGE
1,										-- EXPORT_KDP_M
1,										-- CREATE_KDP_ACCOUNT_REPORT
null,									-- EXPORT_AK_PRODUKTE
4,										-- VERTEILUNG_DURCH
0,										-- BA_RUECKLAEUFER
0,										-- BRAUCHT_VPI_VCI
null,									-- PROJEKTIERUNG_CHAIN_ID
16,										-- VERLAUF_CHAIN_ID
13,										-- VERLAUF_CANCEL_CHAIN_ID
0,										-- BA_CHANGE_REALDATE
0,										-- CREATE_AP_ADDRESS
0,										-- ASSIGN_IAD
0, 										-- CPS_PROVISIONING
null,									-- CPS_PROD_NAME
null,									-- STATUSMELDUNGEN
0, 										-- CPS_AUTO_CREATION
null,						      		-- CPS_ACCOUNT_TYPE
0, 										-- CPS_DSL_PRODUCT
'W',									-- TDN_KIND_OF_USE_PRODUCT
'A',									-- TDN_KIND_OF_USE_TYPE
null									-- TDN_USE_FROM_MASTER
);


INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE)
VALUES (350, 350, 350, 'phone');
INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE)
VALUES (351, 351, 351, 'phone');
INSERT INTO T_PRODUKT_MAPPING (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE)
VALUES (352, 352, 352, 'phone');
