-- Konfiguration fuer Produkt "M-net vor Ort"

-- Physiktypen zuordnen
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP)
  values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 350, 51);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP)
  values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 351, 51);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP)
  values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 352, 51);

-- CPS-Konfiguration
update T_PRODUKT set
  CPS_PROVISIONING='1',
  CPS_PROD_NAME='Mnet_vor_Ort',
  CPS_AUTO_CREATION='1',
  CPS_ACCOUNT_TYPE=null,
  CPS_DSL_PRODUCT=null
  where PROD_ID in (350,351,352);

insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 350, 14000, 50);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 350, 14001, 50);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 350, 14002, 54);

insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 351, 14000, 50);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 351, 14001, 50);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 351, 14002, 54);

insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 352, 14000, 50);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 352, 14001, 50);
insert into T_CPS_DATA_CHAIN_CONFIG (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID)
  values (S_T_CPS_DATA_CHAIN_CONFIG_0.nextVal, 352, 14002, 54);



