-- Leistungsbuendel definieren fuer die Mnet-vor-Ort Produkte bzw. Leistungen
-- Produkt 350
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (4, 22896, NULL, 310, NULL);
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (4, 25220, NULL, 305, NULL);
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (4, 25896, NULL, 303, NULL);
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (4, 25897, NULL, 302, NULL);

-- Produkt 351
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (2, 22577, NULL, 308, NULL);
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (2, 23753, NULL, 305, NULL);

-- Produkt 352
insert into T_LB_2_PRODUKT (LB_ID, LEISTUNG__NO, PROTOKOLL_LEISTUNG__NO, PRODUCT_OE__NO, DESCRIPTION)
    values (10, 39385, NULL, 305, NULL);
