-- Create T_VERLAUF_ABTEILUNG_STATUS
CREATE TABLE T_VERLAUF_ABTEILUNG_STATUS
(
  ID            NUMBER(10),
  ABTEILUNG_ID  NUMBER(10)                      NOT NULL,
  STATUS        VARCHAR2(50)                    NOT NULL
)
LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING;

-- Constraints T_VERLAUF_ABTEILUNG_STATUS
ALTER TABLE T_VERLAUF_ABTEILUNG_STATUS ADD(CONSTRAINT T_VERLAUF_ABTEILUNG_STATUS_PK
	PRIMARY KEY (ID));

ALTER TABLE T_VERLAUF_ABTEILUNG_STATUS ADD (CONSTRAINT FK_VABTSTATUS_ABT
FOREIGN KEY (ABTEILUNG_ID) 
	REFERENCES T_ABTEILUNG (ID)
    DEFERRABLE INITIALLY IMMEDIATE);

-- Sequence for T_VERLAUF_ABTEILUNG_STATUS
CREATE SEQUENCE S_T_VERLAUF_ABTEILUNG_STATUS_0
	INCREMENT BY 1 START WITH 1;

-- Grants for T_VERLAUF_ABTEILUNG_STATUS and sequence
GRANT SELECT ON S_T_VERLAUF_ABTEILUNG_STATUS_0 TO PUBLIC;
GRANT SELECT ON T_VERLAUF_ABTEILUNG_STATUS to R_HURRICAN_USER;
GRANT SELECT ON T_VERLAUF_ABTEILUNG_STATUS to R_HURRICAN_READ_ONLY;

-- Alter T_VERLAUF_ABTEILUNG
ALTER TABLE T_VERLAUF_ABTEILUNG ADD (ABTEILUNG_STATUS_ID NUMBER(10));

ALTER TABLE T_VERLAUF_ABTEILUNG ADD (WIEDERVORLAGE  DATE);

ALTER TABLE T_VERLAUF_ABTEILUNG ADD(CONSTRAINT FK_VABT_STATUS
	FOREIGN KEY (ABTEILUNG_STATUS_ID) REFERENCES T_VERLAUF_ABTEILUNG_STATUS (ID)
	DEFERRABLE INITIALLY IMMEDIATE);
