-- Produkte fuer Alcatel-Physiktypen konfigurieren

insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 446, 100, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 446, 101, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 446, 102, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 431, 100, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 431, 101, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 431, 102, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 421, 100, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 421, 101, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 421, 102, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 411, 100, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 411, 101, 104);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 411, 102, 104);

insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 445, 100, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 445, 101, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 445, 102, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 430, 100, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 430, 101, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 430, 102, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 420, 100, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 420, 101, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 420, 102, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 410, 100, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 410, 101, 103);
insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 410, 102, 103);

insert into T_PRODUKT_2_PHYSIKTYP (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL) values (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 440, 105, null);


