
alter table T_HVT_STANDORT add FC_RAUM_ID NUMBER(10);
alter table T_HVT_STANDORT add BETRIEBSRAUM_ID NUMBER(10);

ALTER TABLE T_HVT_STANDORT ADD (
CONSTRAINT FK_HVTSTFCRAUM_2_HVTST
 FOREIGN KEY (FC_RAUM_ID)
 REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT));

ALTER TABLE T_HVT_STANDORT ADD (
CONSTRAINT FK_HVTSTBR_2_HVTST
 FOREIGN KEY (BETRIEBSRAUM_ID)
 REFERENCES T_HVT_STANDORT (HVT_ID_STANDORT));
