update T_PHYSIKTYP set HW_SCHNITTSTELLE='ADSL-OUT' where HW_SCHNITTSTELLE='ADSL_PUR';
update T_PHYSIKTYP set HW_SCHNITTSTELLE='ADSL-OUT' where HW_SCHNITTSTELLE='ADSL_OUT';
update T_PHYSIKTYP set HW_SCHNITTSTELLE='SDSL-OUT' where HW_SCHNITTSTELLE='SDSL_OUT';