-- Legt die neuen Wholesale-Profile an und ordnet sie dann dem Produkt zu.

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_100000_20000_H',
               '100000',
               '20000',
               '0',
               25,
               54,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_50000_10000_H',
               '50000',
               '10000',
               '0',
               24,
               28,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_50000_20000_H',
               '50000',
               '20000',
               '0',
               24,
               54,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_25000_5000_H',
               '25000',
               '5000',
               '0',
               23,
               27,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_25000_10000_H',
               '25000',
               '10000',
               '0',
               23,
               28,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_16000_1000_H',
               '16000',
               '1000',
               '0',
               12,
               22,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_DSLAM_PROFILE (ID,
                               NAME,
                               DOWNSTREAM,
                               UPSTREAM,
                               FASTPATH,
                               DOWNSTREAM_TECH_LS,
                               UPSTREAM_TECH_LS,
                               GUELTIG,
                               VERSION,
                               ADSL1FORCE,
                               BAUGRUPPEN_TYP,
                               ENABLED_FOR_AUTOCHANGE)
     VALUES   (S_T_DSLAM_PROFILE_0.NEXTVAL,
               'MD_16000_2000_H',
               '16000',
               '2000',
               '0',
               12,
               26,
               '1',
               0,
               '0',
               NULL,
               '0');

INSERT INTO   T_PROD_2_DSLAMPROFILE P2D (PROD_ID, DSLAM_PROFILE_ID)
   SELECT   600 AS PROD_ID, D.ID
     FROM   T_DSLAM_PROFILE D
    WHERE       D.NAME IN
                   ('MD_100000_20000_H',
                    'MD_100000_10000_H',
                    'MD_50000_20000_H',
                    'MD_50000_10000_H',
                    'MD_25000_10000_H',
                    'MD_25000_5000_H',
                    'MD_16000_1000_H',
                    'MD_16000_2000_H')
            AND D.BAUGRUPPEN_TYP IS NULL;