-- add the ItuCarrierCode to the Carrier table
ALTER TABLE T_CARRIER ADD (ITU_CARRIER_CODE VARCHAR2(15));

-- add missing ItuCarrierCodes
--1&1
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.1UND1' WHERE PORTIERUNGSKENNUNG = 'D201';
--Mnet
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.MNET' WHERE COMPANY_NAME = 'M-net Telekommunikations GmbH';
--Akom
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.MNET' WHERE PORTIERUNGSKENNUNG = 'D043';
--Nefkom
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.MNET' WHERE PORTIERUNGSKENNUNG = 'D007';
--Telekom
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.DTAG' WHERE PORTIERUNGSKENNUNG = 'D001';
--Vodafone
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.VFDE' WHERE PORTIERUNGSKENNUNG = 'D009';
--Kabel Deutschland
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.KDVS' WHERE COMPANY_NAME = 'Kabel Deutschland GmbH';
--Telefonica
UPDATE T_CARRIER SET ITU_CARRIER_CODE = 'DEU.TEFGER' WHERE PORTIERUNGSKENNUNG = 'D061';
