insert into T_TECH_LEISTUNG (ID, NAME, EXTERN_LEISTUNG__NO, TYP, LONG_VALUE, STR_VALUE,
                             PROD_NAME_STR, DESCRIPTION,
                             GUELTIG_VON, GUELTIG_BIS)
    VALUES (460, 'VOIP_READY_66', 31000, 'QOS_PROFILE', 66, 'VR66',
            ' ', 'QoS-Profil für Sip-Trunk. Long_value = VoIP-Prio, String-Value = Profil-Name',
            to_date('01.11.2013', 'dd.mm.yyyy'), to_date('01.01.2200', 'dd.mm.yyyy'))
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
    values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 541, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 460, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 99, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 69, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 68, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 67, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 66, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 65, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 64, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 63, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 62, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 61, 460, 0, 0)
;

insert into T_PROD_2_TECH_LEISTUNG (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT)
  values (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 60, 460, 0, 0)
;
