-- Size must be increased because of the count of possible wbci meldungscodes
ALTER TABLE T_IO_ARCHIVE MODIFY REQUEST_MELDUNGSCODE VARCHAR2(400);
ALTER TABLE T_IO_ARCHIVE MODIFY REQUEST_MELDUNGSTEXT VARCHAR2(4000);
