delete from T_WITA_SEND_LIMIT where GESCHAEFTSFALL_TYP IN ('VA_KUE_MRN', 'VA_KUE_ORN', 'VA_RRNP');

--DTAG
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_MRN', 'DEU.DTAG', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_ORN', 'DEU.DTAG', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_RRNP', 'DEU.DTAG', '1', -1, 0, SYSDATE);
--VODAFONE
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_MRN', 'DEU.VFDE', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_ORN', 'DEU.VFDE', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_RRNP', 'DEU.VFDE', '1', -1, 0, SYSDATE);
--1UND1
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_MRN', 'DEU.1UND1', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_ORN', 'DEU.1UND1', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_RRNP', 'DEU.1UND1', '1', -1, 0, SYSDATE);
--KABEL_DEUTSCHLAND
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_MRN', 'DEU.KDVS', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_ORN', 'DEU.KDVS', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_RRNP', 'DEU.KDVS', '1', -1, 0, SYSDATE);
--TELEFONICA
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_MRN', 'DEU.TEFGER', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_KUE_ORN', 'DEU.TEFGER', '1', -1, 0, SYSDATE);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, ITU_CARRIER_CODE, ALLOWED, SEND_LIMIT, VERSION, DATEW)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VA_RRNP', 'DEU.TEFGER', '1', -1, 0, SYSDATE);
