alter table T_CARRIERBESTELLUNG add TAL_REAL_TIMESLOT varchar2(25);

alter table T_CARRIERBESTELLUNG add constraint CHK_CB_REAL_TIMESLOT check
  (TAL_REAL_TIMESLOT in ('VORMITTAG', 'NACHMITTAG', 'GANZTAGS'));
