BEGIN
    execute immediate('ALTER TABLE HURRICAN_MIG_LOG DROP PRIMARY KEY CASCADE');
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

BEGIN
    execute immediate('DROP TABLE HURRICAN_MIG_LOG CASCADE CONSTRAINTS');
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

CREATE TABLE HURRICAN_MIG_LOG
(
  LOG_ID                 NUMBER(10),
  MIGRESULT_ID           NUMBER(10),
  SCRIPT_NAME            VARCHAR2(4000 BYTE),
  SEVERITY               VARCHAR2(4000 BYTE),
  CLASSIFICATION         NUMBER(20),
  CLASSIFICATION_STRING  VARCHAR2(200 BYTE),
  MESSAGE                VARCHAR2(4000 BYTE),
  EXCEPTION_MSG          CLOB,
  LOG_TIMESTAMP          DATE,
  LOG_USERNAME           VARCHAR2(50 BYTE),
  LOG_UPD_TIMESTAMP      DATE,
  LOG_UPD_USERNAME       VARCHAR2(50 BYTE)
) NOLOGGING;


BEGIN
    execute immediate('DROP SEQUENCE SEQ_HURRICAN_MIG_LOG');
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

CREATE SEQUENCE SEQ_HURRICAN_MIG_LOG INCREMENT BY 1 START WITH 1000;

CREATE INDEX IX_HURRICAN_MIG_LOG_SCRIPT ON HURRICAN_MIG_LOG (SCRIPT_NAME) NOLOGGING PARALLEL 4;


CREATE OR REPLACE TRIGGER TRG_HURRICAN_MIG_LOG
BEFORE INSERT OR UPDATE ON HURRICAN_MIG_LOG
FOR EACH ROW
DECLARE
    iCounter HURRICAN_MIG_LOG.LOG_ID%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
        IF :new.LOG_ID is NULL THEN
            Select SEQ_HURRICAN_MIG_LOG.NEXTVAL INTO iCounter FROM Dual;
           :new.LOG_ID := iCounter;
        END IF;
    END IF;

    IF :new.LOG_TIMESTAMP IS NULL THEN
      :new.LOG_TIMESTAMP  := SYSDATE;
    END IF;
   IF :new.LOG_USERNAME IS NULL THEN
       :new.LOG_USERNAME := USER;
    END IF;

    IF UPDATING THEN
        IF NOT (:new.LOG_ID = :old.LOG_ID) THEN
            RAISE cannot_change_counter;
        END IF;

       :new.LOG_UPD_TIMESTAMP  := SYSDATE;
       :new.LOG_UPD_USERNAME := USER;

    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         raise_application_error(-20000, 'Cannot Change Counter Value');
END;
/

ALTER TABLE HURRICAN_MIG_LOG ADD (PRIMARY KEY (LOG_ID));

ALTER TABLE HURRICAN_MIG_LOG ADD (CONSTRAINT FK_HURRICAN_MIGLOG_MIGRESULT
  FOREIGN KEY (MIGRESULT_ID) REFERENCES HURRICAN_MIG_RESULT (ID));

