BEGIN
    execute immediate('DROP TABLE HURRICAN_MIG_IDS CASCADE CONSTRAINTS');
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

CREATE TABLE HURRICAN_MIG_IDS
(
  LOG_ID             NUMBER(10) NOT NULL,
  NUMERIC_ID         NUMBER(19),
  STRING_ID          VARCHAR2(1000 BYTE),
  NAME               VARCHAR2(1000 BYTE),
  SOURCE             CHAR(1) NOT NULL
) NOLOGGING;

ALTER TABLE HURRICAN_MIG_IDS ADD CONSTRAINT FK_HURRICAN_MIG_ID_MIG_LOG
  FOREIGN KEY (LOG_ID) REFERENCES HURRICAN_MIG_LOG (LOG_ID);

CREATE INDEX IX_HURRICAN_MIG_IDS_LOG_ID ON HURRICAN_MIG_IDS (LOG_ID) NOLOGGING PARALLEL 4;

CREATE INDEX IX_HURRICAN_MIG_IDS_NUM_ID ON HURRICAN_MIG_IDS (NUMERIC_ID) NOLOGGING PARALLEL 4;

CREATE INDEX IX_HURRICAN_MIG_IDS_STR_ID ON HURRICAN_MIG_IDS (STRING_ID) NOLOGGING PARALLEL 4;


