-- Remove columns of fallback datasource

ALTER TABLE DB DROP COLUMN FALLBACK_DRIVER;
ALTER TABLE DB DROP COLUMN FALLBACK_URL;
ALTER TABLE DB DROP COLUMN FALLBACK_SCHEMA;
ALTER TABLE DB DROP COLUMN FALLBACK_HIBERNATE_DIALECT;

ALTER TABLE ACCOUNT DROP COLUMN FALLBACK_USER;
ALTER TABLE ACCOUNT DROP COLUMN FALLBACK_PASSWORD;