-- SQL Script, um die Konfiguration fuer manuellen Rangierungsaufbau zu definieren

delete from T_PRODUKT_EQ_CONFIG where prod_id in (63,64);

-- Konfig fuer Produkt 'SDSL 2300'
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 63, 1, 'EQ_OUT', 'status',
    'frei', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 63, 1, 'EQ_OUT', 'carrier',
    'DTAG', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 63, 1, 'EQ_OUT', 'rangSchnittstelle',
    'H', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 63, 2, 'EQ_IN', 'status',
    'frei', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 63, 2, 'EQ_IN', 'hwSchnittstelle',
    'SDSL-OUT', 0, '1', '0');



-- Konfig fuer Produkt 'SDSL 4600'
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 64, 1, 'EQ_OUT', 'status',
    'frei', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 64, 1, 'EQ_OUT', 'carrier',
    'DTAG', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 64, 1, 'EQ_OUT', 'rangSchnittstelle',
    'H', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 64, 2, 'EQ_IN', 'status',
    'frei', 0, '1', '0');
Insert into T_PRODUKT_EQ_CONFIG
   (ID, PROD_ID, CONFIG_GROUP, EQ_TYP, EQ_PARAM,
    EQ_VALUE, VERSION, IS_RANGIERUNGSPART_DEFAULT, IS_RANGIERUNGSPART_ADDITIONAL)
 Values
   (S_T_PRODUKT_EQ_CONFIG_0.nextVal, 64, 2, 'EQ_IN', 'hwSchnittstelle',
    'SDSL-OUT', 0, '1', '0');

