
-- is recreated by changed repeatable scripts
DROP VIEW V_HURRICAN_TECH_ORDER_BASE;

ALTER TABLE T_AUFTRAG_TECHNIK DROP COLUMN ANBINDUNGSART;
ALTER TABLE T_AUFTRAG_TECHNIK DROP COLUMN ANBINDUNGSART_ID;

DROP TABLE T_ANBINDUNGSART;
