
Insert into T_PHYSIKTYP
   (ID, NAME, BESCHREIBUNG, HVT_TECHNIK_ID, MAX_BANDWIDTH,
    HW_SCHNITTSTELLE, PT_GROUP, CPS_TRANSFER_METHOD, VERSION)
 Values
   (804, 'FTTC_VDSL', NULL, NULL, 100000,
    'VDSL', 4, 'VDSL', 0);


Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL,
    PARENTPHYSIKTYP_ID, VERSION)
 Values
   (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 512, 804, NULL, '0',
    NULL, 0);
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, PHYSIKTYP_ADDITIONAL, VIRTUELL,
    PARENTPHYSIKTYP_ID, VERSION)
 Values
   (S_T_PRODUKT_2_PHYSIKTYP_0.nextVal, 513, 804, NULL, '0',
    NULL, 0);


