
Insert into T_HW_BAUGRUPPEN_TYP
   (ID, NAME, PORT_COUNT, DESCRIPTION, IS_ACTIVE,
    HW_SCHNITTSTELLE_NAME, HW_TYPE_NAME, HVT_TECHNIK_ID, VERSION)
 Values
   (S_T_HW_BAUGRUPPEN_TYP_0.nextVal, 'NVLT-H', 48, 'Alcatel NVLT-H VDSL', '1',
    'VDSL', 'XDSL_MUC', 6, 0);

