
ALTER TABLE T_WBCI_AUTOMATION_TASK ADD MELDUNG_ID NUMBER(19) default NULL;
ALTER TABLE T_WBCI_AUTOMATION_TASK ADD CONSTRAINT FK_AUTOMATION_TASK_MELDUNG_ID
  FOREIGN KEY (MELDUNG_ID) REFERENCES T_WBCI_MELDUNG;
