-- IP_PURPOSE_V4
ALTER TABLE T_PRODUKT ADD (IP_PURPOSE_V4 NUMBER(10) NULL);
ALTER TABLE T_PRODUKT ADD CONSTRAINT FK_PRODUKT_IP_PURPOSE_V4 FOREIGN KEY (IP_PURPOSE_V4) REFERENCES T_REFERENCE (ID);

-- IP_PURPOSE_V4_EDITABLE
ALTER TABLE T_PRODUKT ADD (IP_PURPOSE_V4_EDITABLE CHAR(1));

-- IP_NETMASK_SIZE_V4
ALTER TABLE T_PRODUKT ADD (IP_NETMASK_SIZE_V4 NUMBER(10) NULL);

-- IP_NETMASK_SIZE_V6
ALTER TABLE T_PRODUKT ADD (IP_NETMASK_SIZE_V6 NUMBER(10) NULL);

-- IP_NETMASK_SIZE_EDITABLE
ALTER TABLE T_PRODUKT ADD (IP_NETMASK_SIZE_EDITABLE CHAR(1));
