-- Niederlassung mit Referenz
ALTER TABLE T_NIEDERLASSUNG ADD IP_LOCATION NUMBER(10) NULL;

CREATE INDEX IX_FK_NDLNG_2_REF ON T_NIEDERLASSUNG (IP_LOCATION) TABLESPACE "I_HURRICAN";

ALTER TABLE T_NIEDERLASSUNG ADD CONSTRAINT FK_NDLNG_2_REF
  FOREIGN KEY (IP_LOCATION)
  REFERENCES T_REFERENCE (ID);

-- FKs anlegen
UPDATE T_NIEDERLASSUNG SET IP_LOCATION=(SELECT ID FROM T_REFERENCE WHERE TYPE='IP_BACKBONE_LOCATION_TYPE' AND STR_VALUE='AGB') where ID=1;
UPDATE T_NIEDERLASSUNG SET IP_LOCATION=(SELECT ID FROM T_REFERENCE WHERE TYPE='IP_BACKBONE_LOCATION_TYPE' AND STR_VALUE='AGB') where ID=2;
UPDATE T_NIEDERLASSUNG SET IP_LOCATION=(SELECT ID FROM T_REFERENCE WHERE TYPE='IP_BACKBONE_LOCATION_TYPE' AND STR_VALUE='MUC') where ID=3;
UPDATE T_NIEDERLASSUNG SET IP_LOCATION=(SELECT ID FROM T_REFERENCE WHERE TYPE='IP_BACKBONE_LOCATION_TYPE' AND STR_VALUE='NUE') where ID=4;
UPDATE T_NIEDERLASSUNG SET IP_LOCATION=(SELECT ID FROM T_REFERENCE WHERE TYPE='IP_BACKBONE_LOCATION_TYPE' AND STR_VALUE='MUC') where ID=5;

