
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'BEREITSTELLUNG', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'BESTANDSUEBERSICHT', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'KUENDIGUNG_KUNDE', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'LEISTUNGSMERKMAL_AENDERUNG', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'LEISTUNGS_AENDERUNG', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'PORTWECHSEL', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'PRODUKTGRUPPENWECHSEL', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'PROVIDERWECHSEL', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'RUFNUMMERNEXPORT_ANSCHLUSSKUENDIGUNG', -1, 'Init', SYSDATE, 0);
Insert into T_WITA_SEND_LIMIT (ID, GESCHAEFTSFALL_TYP, SEND_LIMIT, LAST_CHANGE_BY, LAST_CHANGE_AT, VERSION)
 Values (S_T_WITA_SEND_LIMIT_0.nextVal, 'VERBUNDLEISTUNG', -1, 'Init', SYSDATE, 0);



