
-- Fix Timestamp -> Date
ALTER TABLE T_MWF_MELDUNG
MODIFY(VERBINDLICHER_LIEFERTERMIN DATE);

-- Datew auf Mwf_Meldung
ALTER TABLE T_MWF_MELDUNG
 ADD (DATEW  DATE);

CREATE OR REPLACE TRIGGER TRBIU_MWF_MELDUNG BEFORE INSERT or UPDATE on T_MWF_MELDUNG
for each row
begin
 -- TIMEST setzen
 SELECT LOCALTIMESTAMP into :new.DATEW FROM dual;
end;
/

UPDATE T_MWF_MELDUNG
   SET DATEW = sysdate;

ALTER TABLE T_MWF_MELDUNG
MODIFY(DATEW  NOT NULL);

-- Datew auf Mwf_Request
ALTER TABLE T_MWF_REQUEST
 ADD (DATEW  DATE);

CREATE OR REPLACE TRIGGER TRBIU_MWF_REQUEST BEFORE INSERT or UPDATE on T_MWF_REQUEST
for each row
begin
 -- TIMEST setzen
 SELECT LOCALTIMESTAMP into :new.DATEW FROM dual;
end;
/

UPDATE T_MWF_REQUEST
   SET DATEW = sysdate;

ALTER TABLE T_MWF_REQUEST
MODIFY(DATEW  NOT NULL);

-- Datew auf CB_Vorgang
ALTER TABLE T_CB_VORGANG
 ADD (DATEW  DATE);

CREATE OR REPLACE TRIGGER TRBIU_CB_VORGANG BEFORE INSERT or UPDATE on T_CB_VORGANG
for each row
begin
 -- TIMEST setzen
 SELECT LOCALTIMESTAMP into :new.DATEW FROM dual;
end;
/

UPDATE T_CB_VORGANG
   SET DATEW = sysdate;

ALTER TABLE T_CB_VORGANG
MODIFY(DATEW  NOT NULL);