-- IMS Switches haben andere Sperrklassen. Fuege Spalte fuer Sperrklassen_IMS hinzu.
ALTER TABLE T_SPERRKLASSEN ADD SPERRKLASSE_IMS NUMBER(10) NULL;
ALTER TABLE T_SPERRKLASSEN MODIFY SPERRKLASSE NUMBER(10) NULL;

-- Fuege neue Sperrklassen fuer IMS in die bestehenden Datensaetze ein fuer die es eine Uebereinstimmung mit den alten
-- Sperrklassen gibt.
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=60 WHERE SPERRKLASSE=60;
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=2 WHERE SPERRKLASSE=62;
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=3 WHERE SPERRKLASSE=64;
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=4 WHERE SPERRKLASSE=92;

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 5, '0', '1', '0', '0', '0', '1', '0', '0', '0');

UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=6 WHERE SPERRKLASSE=124;
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=7 WHERE SPERRKLASSE=170;
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=8 WHERE SPERRKLASSE=165;
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=12 WHERE SPERRKLASSE=45;

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 13, '0', '0', '0', '1', '0', '0', '0', '0', '0');

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 14, '0', '0', '0', '0', '1', '0', '1', '0', '0');

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 15, '0', '1', '0', '0', '0', '0', '0', '0', '0');

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 16, '0', '0', '0', '0', '0', '0', '0', '1', '0');

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 17, '0', '1', '1', '1', '1', '0', '1', '1', '0');

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ, MOBIL, VPN, PRD,
    AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 18, '0', '1', '1', '0', '1', '0', '1', '1', '0');

UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=20 WHERE SPERRKLASSE=41;