-- Erstelle neue Tabelle T_HW_SWITCH fuer die Identifizierung von Switches und ihres Typs.
CREATE TABLE T_HW_SWITCH
(
   ID                   NUMBER (19, 0) NOT NULL,
   VERSION              NUMBER (19, 0) DEFAULT 0 NOT NULL,
   TYPE                 VARCHAR2 (50) NOT NULL,
   NAME                 NUMBER (19, 0) NOT NULL,
   constraint           FK_SWITCH_REFERENCE
   foreign key          (NAME)
   references           T_REFERENCE (ID),
   PRIMARY KEY          (ID)
);

-- Zugriff auf die Tabelle regeln
GRANT SELECT, INSERT, UPDATE ON T_HW_SWITCH TO R_HURRICAN_USER;
GRANT SELECT ON T_HW_SWITCH TO R_HURRICAN_READ_ONLY;

-- Sequenz fuer Primaerschluessel
CREATE SEQUENCE S_T_HW_SWITCH_0 START WITH 1;
-- Zugriff auf die Sequenz regeln
GRANT SELECT ON S_T_HW_SWITCH_0 TO PUBLIC;

-- Befuellen der Daten
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'IMS', 22208);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22200);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22201);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22202);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22203);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'SOFTSWITCH', 22204);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22205);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22206);
INSERT INTO T_HW_SWITCH (ID, TYPE, NAME) VALUES (S_T_HW_SWITCH_0.nextVal, 'EWSD', 22207);
