-- IMS Sperrklasse 4 und 8 haben keine alte Entsprechung und sind daher neu anzulegen
UPDATE T_SPERRKLASSEN SET SPERRKLASSE_IMS=NULL WHERE SPERRKLASSE in (92, 165);

INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ,
    MOBIL, VPN, PRD, AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 4, '0', '0', '0',
    '0', '1', '1', '1', '0', '0');

 INSERT INTO T_SPERRKLASSEN (ID, SPERRKLASSE_IMS, NATIONAL, PREMIUM_SERVICES_INT, MABEZ,
    MOBIL, VPN, PRD, AUSKUNFTSDIENSTE, INTERNATIONAL, ABGEHEND)
 Values (S_T_SPERRKLASSEN_0.nextVal, 8, '0', '1', '1',
    '0', '1', '1', '1', '1', '0');
