-- already executed in production but due to documentation issues checked in here
ALTER TABLE T_CB_VORGANG DROP
  CONSTRAINT T_CB_VORGANG_ZEITFENSTER;

ALTER TABLE T_CB_VORGANG ADD
  CONSTRAINT T_CB_VORGANG_ZEITFENSTER
  CHECK (REALISERUNG_ZEITFENSTER in ('SLOT_1','SLOT_2','SLOT_3','SLOT_4','SLOT_6','SLOT_7'));
