drop sequence S_T_HVT_UMZUG;

CREATE SEQUENCE S_T_HVT_UMZUG_0 START WITH 1;
GRANT SELECT ON S_T_HVT_UMZUG_0 TO PUBLIC;

CREATE SEQUENCE S_T_HVT_UMZUG_DETAIL_0 START WITH 1;
GRANT SELECT ON S_T_HVT_UMZUG_DETAIL_0 TO PUBLIC;