CREATE TABLE T_KVZ_SPERRE (
  ID NUMBER(19, 0) PRIMARY KEY NOT NULL,
  ONKZ VARCHAR2(8) NOT NULL,
  ASB NUMBER(10) NOT NULL,
  KVZ_NUMMER VARCHAR2(5) NOT NULL,
  VERSION NUMBER(19, 0) NOT NULL
);

ALTER TABLE T_KVZ_SPERRE ADD CONSTRAINT UK_KVZ_SPERRE UNIQUE (ONKZ, ASB, KVZ_NUMMER);

GRANT SELECT, INSERT, UPDATE ON T_KVZ_SPERRE TO R_HURRICAN_USER;
GRANT SELECT ON T_KVZ_SPERRE TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_KVZ_SPERRE_0;
GRANT SELECT ON S_T_KVZ_SPERRE_0 TO PUBLIC;
