alter table T_HVT_UMZUG_DETAIL add ENDSTELLEN_TYP CHAR(1) NOT NULL;
alter table T_HVT_UMZUG_DETAIL add ID NUMBER(19,0) not null;

ALTER TABLE T_HVT_UMZUG_DETAIL ADD
  CONSTRAINT PK_T_HVT_UMZUG_DETAIL
  PRIMARY KEY (ID);

 alter table T_HVT_UMZUG_DETAIL drop column AUFTRAG_STATUS_ID;