GRANT SELECT, INSERT, UPDATE ON T_HVT_UMZUG TO R_HURRICAN_USER;
GRANT SELECT ON T_HVT_UMZUG TO R_HURRICAN_READ_ONLY;

GRANT SELECT, INSERT, UPDATE ON T_HVT_UMZUG_DETAIL TO R_HURRICAN_USER;
GRANT SELECT ON T_HVT_UMZUG_DETAIL TO R_HURRICAN_READ_ONLY;


alter table T_HVT_UMZUG add version number(19,0);
alter table T_HVT_UMZUG_DETAIL add version number(19,0);

alter table T_HVT_UMZUG modify SWITCH_AT DATE;
