alter table T_HVT_UMZUG_DETAIL drop column UEVT_ID;
alter table T_HVT_UMZUG_DETAIL drop column UEVT_ID_NEU;

alter table T_HVT_UMZUG_DETAIL add UEVT_STIFT_ALT VARCHAR2(10) NOT NULL;
alter table T_HVT_UMZUG_DETAIL add UEVT_STIFT_NEU VARCHAR2(10);
alter table T_HVT_UMZUG_DETAIL add RANGIER_ID_ALT NUMBER(19,0);
alter table T_HVT_UMZUG_DETAIL add RANGIER_ID_NEU NUMBER(19,0);

