alter table T_HVT_UMZUG drop constraint CHK_HVT_UMZUG_STATUS;
alter table T_HVT_UMZUG add constraint CHK_HVT_UMZUG_STATUS check (STATUS in ('OFFEN', 'IN_PLANUNG', 'ERLEDIGT'));

alter table T_HVT_UMZUG rename column HVT_STANDORT_ID TO HVT_ID_STANDORT;

drop Table T_HVT_UMZUG_DETAIL;

CREATE TABLE T_HVT_UMZUG_DETAIL
(
   ID NUMBER(19,0) NOT NULL,
   HVT_UMZUG_ID NUMBER(19) NOT NULL,
   AUFTRAG_ID NUMBER(19),
   PROD_ID NUMBER(19),
   BEREITSTELLUNG_AM date,
   VTRNR varchar2(25 BYTE),
   ENDSTELLEN_TYP CHAR(1) NOT NULL,
   UEVT_STIFT_ALT VARCHAR2(10) NOT NULL,
   UEVT_STIFT_NEU VARCHAR2(10),
   RANGIER_ID_ALT NUMBER(19,0),
   RANGIER_ID_NEU NUMBER(19,0),
   ADDITIONAL_ORDER CHAR(1) DEFAULT 0,
   VERSION NUMBER(19,0) DEFAULT 0
);

ALTER TABLE T_HVT_UMZUG_DETAIL ADD
  CONSTRAINT PK_T_HVT_UMZUG_DETAIL
  PRIMARY KEY (ID);

GRANT SELECT, INSERT, UPDATE ON T_HVT_UMZUG_DETAIL TO R_HURRICAN_USER;
GRANT SELECT ON T_HVT_UMZUG_DETAIL TO R_HURRICAN_READ_ONLY;

ALTER TABLE T_HVT_UMZUG_DETAIL ADD
 CONSTRAINT AUFTR_ENDST_T_HVT_UMZUG_DETAIL
  UNIQUE (AUFTRAG_ID,ENDSTELLEN_TYP);




