-- create table for certified switches
CREATE TABLE T_EG_TYPE_2_HWSWITCH (
  EG_TYPE_ID   NUMBER(19, 0) NOT NULL,
  HW_SWICHT_ID NUMBER(19, 0) NOT NULL,
  PRIORITY     NUMBER(10, 0) NOT NULL,
  CONSTRAINT FK_EG_TYPE_ID_2_EG_TYPE FOREIGN KEY (EG_TYPE_ID) REFERENCES T_EG_TYPE (ID),
  CONSTRAINT FK_HW_SWITCH_ID_2_HW_SWITCH FOREIGN KEY (HW_SWICHT_ID) REFERENCES T_HW_SWITCH (ID),
  PRIMARY KEY (EG_TYPE_ID, HW_SWICHT_ID)
);

-- grants
GRANT SELECT, INSERT, UPDATE ON T_EG_TYPE_2_HWSWITCH TO R_HURRICAN_USER;
GRANT SELECT ON T_EG_TYPE_2_HWSWITCH TO R_HURRICAN_READ_ONLY;