delete from T_REFERENCE where TYPE='SWITCH';

ALTER TABLE T_PROD_2_SIP_DOMAIN RENAME COLUMN SWITCH_REF_ID TO HW_SWITCH;
ALTER TABLE T_AUFTRAG_TECHNIK RENAME COLUMN SWITCH_REF_ID TO HW_SWITCH;
ALTER TABLE T_AUFTRAG_SIP_INTER_TRUNK RENAME COLUMN SWITCH_REF_ID TO HW_SWITCH;
