-- ANF-449: Konfiguration fuer den MUC06 auf IMS/NSP anpassen

-- DSL + VoIP (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 480, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '1', null);

-- DSL only (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 440, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '1', null);

-- FTTX DSL (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 512, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '1', null);

-- FTTX DSL + Fon (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 513, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '1', null);

-- FTTX Telefon (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 511, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '0', null);
-- POTS
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 511, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22350, 'migration', 0, '1', null);

-- Glasfaser SDSL (MGA)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 541, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22351, 'migration', 0, '1', null);

-- Maxi FTTH Wohnheim (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 570, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '1', null);

-- Premium Glasfaser-DSL Doppel-Flat (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 540, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '0', null);
-- MGA
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 540, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22351, 'migration', 0, '1', null);

-- SIP-Trunk (SIP-Trunk)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 580, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22353, 'migration', 0, '1', null);

-- TAL VDSL + Fon (S&F)
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, 514, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22349, 'migration', 0, '1', null);


-- ##########################################
-- Beziehung zu den Endgeraeten konfigurieren
INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, null, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, null, 281);

INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, null, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, null, 282);

INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, null, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, null, 341);

INSERT INTO T_PROD_2_SIP_DOMAIN
  (ID, PROD_ID, HW_SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, DEFAULT_DOMAIN, EG_TYPE_ID)
VALUES
  (S_T_PROD_2_SIP_DOMAIN_0.nextval, null, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, null, 342);
