CREATE TABLE T_EG_TYPE_2_SIP_DOMAIN
(
  ID                NUMBER(19)             NOT NULL,
  EG_TYPE_ID        NUMBER(19)             NOT NULL,
  SWITCH            NUMBER(19)             NOT NULL,
  SIP_DOMAIN_REF_ID NUMBER(19)             NOT NULL,
  USERW             VARCHAR2(15),
  DATEW             DATE,
  VERSION           NUMBER(18)   DEFAULT 0 NOT NULL
);

COMMENT ON TABLE T_EG_TYPE_2_SIP_DOMAIN IS 'Tabelle haelt SIP Domain Konfigurationen fuer die Endgeraetetypen';

COMMENT ON COLUMN T_EG_TYPE_2_SIP_DOMAIN.ID IS 'ID des Datensatzes';
COMMENT ON COLUMN T_EG_TYPE_2_SIP_DOMAIN.EG_TYPE_ID IS 'FK Referenz auf das Endgeraetetypen-Tabelle';
COMMENT ON COLUMN T_EG_TYPE_2_SIP_DOMAIN.SWITCH IS 'FK Referenz auf das Switch-Tabelle';
COMMENT ON COLUMN T_EG_TYPE_2_SIP_DOMAIN.SIP_DOMAIN_REF_ID IS 'ID der SIP Domain Kennung aus der T_REFERENCE';
COMMENT ON COLUMN T_EG_TYPE_2_SIP_DOMAIN.USERW IS 'Schreibender Zugriff des letzten Benutzers';
COMMENT ON COLUMN T_EG_TYPE_2_SIP_DOMAIN.DATEW IS 'Datum des letzten schreibenden Zugriffs';

create SEQUENCE S_T_EG_TYPE_2_SIP_DOMAIN_0 start with 1;
grant select on S_T_EG_TYPE_2_SIP_DOMAIN_0 to public;

ALTER TABLE T_EG_TYPE_2_SIP_DOMAIN ADD CONSTRAINT PK_T_EG_TYPE_2_SIP_DOMAIN PRIMARY KEY (ID);

CREATE INDEX IX_FK_EGT2SIPD_2_EG_TYPE ON T_EG_TYPE_2_SIP_DOMAIN (EG_TYPE_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_TYPE_2_SIP_DOMAIN ADD CONSTRAINT FK_EGT2SIPD_2_EG_TYPE
  FOREIGN KEY (EG_TYPE_ID) REFERENCES T_EG_TYPE (ID);

CREATE INDEX IX_FK_EGT2SIPD_SW_2_HWSWITCH ON T_EG_TYPE_2_SIP_DOMAIN (SWITCH) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_TYPE_2_SIP_DOMAIN ADD CONSTRAINT FK_EGT2SIPD_SW_2_HWSWITCH
  FOREIGN KEY (SWITCH) REFERENCES T_HW_SWITCH (ID);

CREATE INDEX IX_FK_EGT2SIPD_DM_2_REF ON T_EG_TYPE_2_SIP_DOMAIN (SIP_DOMAIN_REF_ID) TABLESPACE "I_HURRICAN";
ALTER TABLE T_EG_TYPE_2_SIP_DOMAIN ADD CONSTRAINT FK_EGT2SIPD_DM_2_REF
  FOREIGN KEY (SIP_DOMAIN_REF_ID) REFERENCES T_REFERENCE (ID);

CREATE trigger TRBIU_EG_TYPE_2_SIP_DOM BEFORE INSERT or UPDATE on T_EG_TYPE_2_SIP_DOMAIN
for each row
BEGIN
 -- TIMESTAMP setzen
 SELECT CURRENT_TIMESTAMP INTO :new.DATEW FROM dual;
END;
/

GRANT SELECT ON T_EG_TYPE_2_SIP_DOMAIN TO R_HURRICAN_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_EG_TYPE_2_SIP_DOMAIN TO R_HURRICAN_USER;
