
-- MUC06
INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc06'), 22346, 'migration', 0, 281);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc06'), 22346, 'migration', 0, 282);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc06'), 22346, 'migration', 0, 341);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc06'), 22346, 'migration', 0, 342);



-- MUC07
INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, 281);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, 282);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, 341);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc07'), 22352, 'migration', 0, 342);



-- MUC08
INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc08'), 22357, 'migration', 0, 281);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc08'), 22357, 'migration', 0, 282);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc08'), 22357, 'migration', 0, 341);

INSERT INTO T_EG_TYPE_2_SIP_DOMAIN
  (ID, SWITCH, SIP_DOMAIN_REF_ID, USERW, VERSION, EG_TYPE_ID)
VALUES
  (S_T_EG_TYPE_2_SIP_DOMAIN_0.nextval, (SELECT ID FROM T_HW_SWITCH WHERE lower(NAME) = 'muc08'), 22357, 'migration', 0, 342);
