create table T_SWITCH_MIGRATION_LOG (
    ID number(19) PRIMARY KEY NOT NULL,
    BEARBEITER varchar2(64),
    MIGRATE_TIME timestamp not null,
    OLD_HW_SWITCH_ID number(19) not null,
    NEW_HW_SWITCH_ID number(19) not null,
    CPS_EXEC_TIME timestamp not null,
    VERSION NUMBER(19,0) DEFAULT 0
);

GRANT SELECT, INSERT, UPDATE ON T_SWITCH_MIGRATION_LOG TO R_HURRICAN_USER;
GRANT SELECT ON T_SWITCH_MIGRATION_LOG TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_SWITCH_MIGRATION_LOG_0 START WITH 1;
GRANT SELECT ON S_T_SWITCH_MIGRATION_LOG_0 TO PUBLIC;


create table T_SWITCH_MIGRATION_LOG_AUFTRAG (
    ID number(19) PRIMARY KEY NOT NULL,
    SWITCH_MIGRATION_LOG_ID number(19) not null,
    AUFTRAG_ID NUMBER(19) not null,
    MIGRATED char(1) DEFAULT 0,
    CPS_TX_ID number(19),
    MESSAGE varchar2(4000),
    VERSION NUMBER(19,0) DEFAULT 0
);

GRANT SELECT, INSERT, UPDATE ON T_SWITCH_MIGRATION_LOG_AUFTRAG TO R_HURRICAN_USER;
GRANT SELECT ON T_SWITCH_MIGRATION_LOG_AUFTRAG TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_SWITCH_MIG_LOG_AUFTRAG_0 START WITH 1;
GRANT SELECT ON S_T_SWITCH_MIG_LOG_AUFTRAG_0 TO PUBLIC;
