alter table T_HVT_UMZUG_DETAIL drop column RANGIER_ID_ALT;
alter table T_HVT_UMZUG_DETAIL drop column RANGIER_ADD_ID_ALT;

alter table T_HVT_UMZUG modify STATUS VARCHAR2(25);

alter table T_HVT_UMZUG drop constraint CHK_HVT_UMZUG_STATUS;
update T_HVT_UMZUG set STATUS='PLANUNG_VOLLSTAENDIG' where STATUS='PLANUNG_ERFOLGT';
alter table T_HVT_UMZUG add CONSTRAINT CHK_HVT_UMZUG_STATUS check
  (status in ('OFFEN', 'PLANUNG_VOLLSTAENDIG', 'AUSGEFUEHRT', 'BEENDET', 'DEAKTIVIERT'));