-- create table for dslam profile mappings
create table T_DSLAM_PROFILE_MAPPING (
    ID NUMBER(19, 0) PRIMARY KEY NOT NULL,
    PROFIL_NAME_ALT VARCHAR2(50) NOT NULL,
    PROFIL_NAME_NEU VARCHAR2(50) NOT NULL,
    UETV VARCHAR2(10)
);

GRANT SELECT, INSERT, UPDATE ON T_DSLAM_PROFILE_MAPPING TO R_HURRICAN_USER;
GRANT SELECT ON T_DSLAM_PROFILE_MAPPING TO R_HURRICAN_READ_ONLY;

CREATE SEQUENCE S_T_DSLAM_PROFILE_MAPPING_0 START WITH 1;
GRANT SELECT ON S_T_DSLAM_PROFILE_MAPPING_0 TO PUBLIC;