-- Produkt Internet Grundversorgung
Insert into T_PRODUKT
   (PROD_ID, PRODUKTGRUPPE_ID, ANSCHLUSSART, PROD_NAME_PATTERN, AKTIONS_ID,
    MAX_DN_COUNT, DN_BLOCK, DN_TYP, GUELTIG_VON, GUELTIG_BIS,
    AUFTRAGSERSTELLUNG, LTGNR_ANLEGEN, BRAUCHT_BUENDEL, ELVERLAUF, ENDSTELLEN_TYP,
    ACCOUNT_VORS, LI_NR, VPN_PHYSIK, PROJEKTIERUNG, IS_PARENT,
    CHECK_CHILD, IS_COMBI_PRODUKT, AUTO_PRODUCT_CHANGE, EXPORT_KDP_M, CREATE_KDP_ACCOUNT_REPORT,
    VERTEILUNG_DURCH, BA_RUECKLAEUFER, VERLAUF_CHAIN_ID, VERLAUF_CANCEL_CHAIN_ID, BA_CHANGE_REALDATE,
    CREATE_AP_ADDRESS, ASSIGN_IAD, CPS_PROVISIONING, CPS_PROD_NAME, CPS_AUTO_CREATION,
    CPS_ACCOUNT_TYPE, CPS_DSL_PRODUCT, TDN_KIND_OF_USE_PRODUCT, TDN_KIND_OF_USE_TYPE, TDN_USE_FROM_MASTER,
    VIER_DRAHT, VERSION, MIN_DN_COUNT, CPS_IP_DEFAULT, CPS_MULTI_DRAHT,
    IP_PURPOSE_V4_EDITABLE, IP_NETMASK_SIZE_EDITABLE, GEOID_SRC, AUTO_HVT_ZUORDNUNG, SMS_VERSAND,
    BUENDEL_BILLING_HAUPTAUFTRAG, SEND_STATUS_UPDATE)
 Values
   (590, 21, 'Internet Grundversorgung', 'Internet Grundversorgung', 1,
    0, null, null, TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    '0', '1', '0', '1', 1,
    'X9', 1, '0', '0', '0',
    '0', '0', '0', '1', '1',
    4, '0', 45, 15, '1',
    '0', '0', '1', 'FTTH_WOHNHEIM', '1',
    'MAXI', '1', 'W', 'V', '0',
    '0', 2, 0, '0', '0',
    '0', '0', 'HVT', '1', '0',
    '0', '1');

-- Schnittstelle
Insert into T_PRODUKT_2_SCHNITTSTELLE
   (PROD_ID, SCHNITTSTELLE_ID)
 Values
   (590, 38);

-- Sperren
Insert into T_SPERRE_VERTEILUNG
   (PROD_ID, ABTEILUNG_ID)
 Values
   (590, 2);
Insert into T_SPERRE_VERTEILUNG
   (PROD_ID, ABTEILUNG_ID)
 Values
   (590, 3);

-- Physiktypen
Insert into T_PRODUKT_2_PHYSIKTYP
   (ID, PROD_ID, PHYSIKTYP, VIRTUELL, VERSION,
    USE_IN_RANG_MATRIX)
 Values
   (S_T_PRODUKT_2_PHYSIKTYP_0.nextval, 590, 808, '0', 0,
    '0');

-- Anschlussuebernahmen
-- FTTX Telefon
Insert into T_PROD_2_PROD
(ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID,
 VERSION)
Values
  (S_T_PROD_2_PROD_0.nextval, 590, 511, 5000, 1,
   0);
-- FTTX DSL
Insert into T_PROD_2_PROD
(ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID,
 VERSION)
Values
  (S_T_PROD_2_PROD_0.nextval, 590, 512, 5000, 1,
   0);
--- FTTX DSL + PHONE
Insert into T_PROD_2_PROD
(ID, PROD_SRC, PROD_DEST, PHYSIKAEND_TYP, CHAIN_ID,
 VERSION)
Values
  (S_T_PROD_2_PROD_0.nextval, 590, 513, 5000, 1,
   0);

-- Standorttyp FTTH
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW,
    DATEW, VERSION)
 Values
   (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextval, 590, 11011, 1, 'Hurrican Developer',
    TO_DATE('06/17/2015 12:52:45', 'MM/DD/YYYY HH24:MI:SS'), 0);
--Standorttyp FTTB_H
Insert into T_PRODUKT_2_TECH_LOCATION_TYPE
   (ID, PROD_ID, TECH_LOCATION_TYPE_REF_ID, PRIORITY, USERW,
    DATEW, VERSION)
 Values
   (S_T_PRODUKT_2_TECH_LOC_TYPE_0.nextval, 590, 11017, 2, 'Hurrican Developer',
    TO_DATE('06/17/2015 12:52:45', 'MM/DD/YYYY HH24:MI:SS'), 0);

-- Techn. Leistungen
-- Kombileistung fuer Taifun-Mapping
Insert into T_TECH_LEISTUNG
   (ID, NAME, EXTERN_LEISTUNG__NO, TYP, PROD_NAME_STR,
    DISPO, EWSD, SDH, IPS, SCT,
    SNAPSHOT_REL, GUELTIG_VON, GUELTIG_BIS, VERSION, PREVENT_AUTO_DISPATCH)
 Values
   (530, 'GWG_Surf-Flat_3_Mbit/s', 10530, 'KOMBI', '.',
    '0', '0', '0', '0', '0',
    '1', TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0, '0');
-- 'Buendel' mit Abhaengigkeiten
Insert into T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT,
    VERSION)
 Values
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 590, 530, null, '0',
    0);
-- Downstream 3000
Insert into T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT,
    VERSION)
 Values
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 590, 10, 530, '1',
    0);
-- Upstream 1000
Insert into T_PROD_2_TECH_LEISTUNG
   (ID, PROD_ID, TECH_LS_ID, TECH_LS_DEPENDENCY, IS_DEFAULT,
    VERSION)
 Values
   (S_T_PROD_2_TECH_LEISTUNG_0.nextval, 590, 22, 530, '1',
    0);

-- Rangierungsmatrix: analog zu FTTH-Wohnheim keine Rangierungsmatrix

-- DSLAM-Profile (analog zu FTTH-Wohnheim nur ein DSLAM-Profil ohne Baugruppentyp)
Insert into T_DSLAM_PROFILE
   (ID, NAME, FASTPATH, DOWNSTREAM_TECH_LS, UPSTREAM_TECH_LS,
    GUELTIG, VERSION, ADSL1FORCE, ENABLED_FOR_AUTOCHANGE, DOWNSTREAM,
    UPSTREAM)
 Values
   (S_T_DSLAM_PROFILE_0.nextval, 'MD_3000_1000_H', '0', 10, 22,
    '1', 0, '0', '0', 3000,
    1000);
Insert into T_PROD_2_DSLAMPROFILE
   (PROD_ID, DSLAM_PROFILE_ID)
 Values
   (590, (select id from T_DSLAM_PROFILE where name = 'MD_3000_1000_H' and BAUGRUPPEN_TYP is null));

-- Rufnummernleistungen (T_LB_2_PRODUKT) sind bei einem reinen Internetprodukt nicht noetig
-- Reports: analog zu FTTH-Wohnheim keine Reports

-- CPS-Provisionierung
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 590, 14000, 53, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 590, 14001, 53, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 590, 14002, 54, 0);
Insert into T_CPS_DATA_CHAIN_CONFIG
   (ID, PROD_ID, SO_TYPE_REF_ID, CHAIN_ID, VERSION)
 Values
   (S_T_CPS_DATA_CHAIN_CONFIG_0.nextval, 590, 14006, 53, 0);

-- Produktmapping
Insert into T_PRODUKT_MAPPING
   (MAPPING_GROUP, EXT_PROD__NO, PROD_ID, MAPPING_PART_TYPE, VERSION)
 Values
   (1320, 600, 590, 'dsl', 0);

-- Bauauftraege
Insert into T_BA_VERL_CONFIG
   (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON,
    GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN,
    CPS_NECESSARY)
 Values
   (S_T_BA_VERL_CONFIG_0.nextval, 590, 72, 17, TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dbscript', 0, '1',
    '1');
Insert into T_BA_VERL_CONFIG
   (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON,
    GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN,
    CPS_NECESSARY)
 Values
   (S_T_BA_VERL_CONFIG_0.nextval, 590, 27, 17, TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dbscript', 0, '1',
    '1');
Insert into T_BA_VERL_CONFIG
   (ID, PROD_ID, ANLASS, ABT_CONFIG_ID, GUELTIG_VON,
    GUELTIG_BIS, DATEW, USERW, VERSION, AUTO_VERTEILEN,
    CPS_NECESSARY)
 Values
   (S_T_BA_VERL_CONFIG_0.nextval, 590, 43, 17, TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    TO_DATE('01/01/2200 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dbscript', 0, '1',
    '1');
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE
   (PROD_ID, BA_VERL_AEND_GRUPPE_ID)
 Values
   (590, 1);
Insert into T_BA_VERL_AEND_PROD_2_GRUPPE
   (PROD_ID, BA_VERL_AEND_GRUPPE_ID)
 Values
   (590, 2);

 -- VLANs
 Insert into T_PROD_2_CVLAN
   (ID, VERSION, PROD_ID, CVLAN_TYP, IS_MANDATORY)
 Values
   (S_T_PROD_2_CVLAN_0.nextval, 0, 590, 'HSIPLUS', '1');
Insert into T_PROD_2_CVLAN
   (ID, VERSION, PROD_ID, CVLAN_TYP, IS_MANDATORY)
 Values
   (S_T_PROD_2_CVLAN_0.nextval, 0, 590, 'IAD', '1');
