alter table T_VORABSTIMMUNG add PREVIOUS_LOCATION_ADDRESS_ID NUMBER(10);

ALTER TABLE T_VORABSTIMMUNG ADD CONSTRAINT
    FK_VORAB_2_ADDRESS FOREIGN KEY (PREVIOUS_LOCATION_ADDRESS_ID)
    REFERENCES T_ADDRESS (ID);

